### ISSUE TITLE
How to stack or group notifications

### ISSUE THREAD

**Issue by JoaquinDelPrado** [zo0r/react-native-push-notification#1001]
i want to stack notifications like WhatsApp or something.

I try with `tag: 'myTag'` and `group: myGroup` without results

**Comment by yzxj** [comment]
I think it's [not yet supported](https://github.com/zo0r/react-native-push-notification/blob/HEAD/trouble-shooting.md#1-local-notifications):

> **Android local notifications**
> These are highly customisable (more so than noisy remote push notifications) but this library doesn't yet support all features, for example you cannot stack notifications using the "grouping" feature.

I would like to have this feature too.

**Comment by JoaquinDelPrado** [comment]
ohh... thanks for your help
