### ISSUE TITLE
Notification on debug works on release not Android

### ISSUE THREAD

**Issue by uendar** [zo0r/react-native-push-notification#1005]
I have problem receiving notification when i install apk on phone, but when i test on debug it works perfectly

**Comment by cymonbr** [comment]
I've a same problem... Anybody have a solution?

**Comment by uendar** [comment]
What RNPN version you have ?

**Comment by cymonbr** [comment]
I use this basic config:

"react": "16.2.0",
"react-native": "0.52.2",
"react-native-push-notification": "^3.1.2"

**Comment by uendar** [comment]
did you find any solution

**Comment by cymonbr** [comment]
No, I'll probably shift my push to external and thus get around this problem.

**Comment by ithustle** [comment]
+1

**Comment by tlow92** [comment]
anyone found a solution?

**Comment by mak12** [comment]
Any luck with this issue?

**Comment by bunnings-kamrul** [comment]
any update on this?

**Comment by kamrulislam** [comment]
any findings on this?

**Comment by jackw-kounta** [comment]
Ive experienced this - resolved it - and created a PR

https://github.com/zo0r/react-native-push-notification/pull/1355

**Comment by Dallas62** [comment]
@kamrulislam @bunnings-kamrul @mak12 @tlow92 @ithustle @cymonbr @uendar 
Can you test the solution made by @jackw-kounta ?
Thanks!

**Comment by kamrulislam** [comment]
I have tested the solution with detached expo (sdk 36) app. It does register the device but it **cannot** open up the notification as the react context is not present. By the way, we need to set `FCM_ENABLED` flag to be true for the expo detached app to get this registration work.

**Comment by Dallas62** [comment]
The PR #1355 is merged into mater, and will be released ASAP.

**Comment by kievmontana** [comment]
Hey! found that on release mode Notifications work only when yarn/npm is running...

**Comment by Dallas62** [comment]
@kievmontana I'm not sure to understand ? Did you tries the version of the library on master ?

**Comment by kievmontana** [comment]
@Dallas62 I tried with the mentioned version as well, without success.
The strange thing is when I run `react-native run-android --variant=release` after a successful build, the notifications are working, but once I stop the server (yarn), and reload the app - notifications don't work. I guess I cant receive a token without a running server... Any hints? :)

**Comment by Dallas62** [comment]
@kievmontana Ok, i can suggest you to try the version on master:
Change the current version of react-native-push-notification:

```
    "react-native-push-notification": "git+https://github.com/zo0r/react-native-push-notification.git"
```

then run:

```
yarn install
```

OR

```
npm install
```
If you have feedback on this, it would be great!
