### ISSUE TITLE
push notification on Samsung does not works 

### ISSUE THREAD

**Issue by uendar** [zo0r/react-native-push-notification#1008]
I tested with other android smartphones that have pure android and works, while in samsung phones will not work. Any idea what can cause this?

**Comment by uendar** [comment]
I tested with other android smartphones that have pure android and works, while in samsung phones will not work. Any idea what can cause this?

**Comment by ClementPF** [comment]
@uendar did you manage to get it to work? I'm experiencing the same issue

**Comment by racsol** [comment]
Having the same issue!
