### ISSUE TITLE
On IOS 12.0.1, remote notification is not received through PushNotificationIOS

### ISSUE THREAD

**Issue by cx5168** [zo0r/react-native-push-notification#1012]
Environment:
  OS: Windows 10
  Node: 8.11.3
  Yarn: 1.12.3
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

Has anybody met?

**Comment by chenyifan88** [comment]
I have this problem too

**Comment by xoapit** [comment]
Have you had any solutions?

**Comment by xoapit** [comment]
I resolved this issue.  For iOS, we have 2 environments to push notification including sandbox and production. We have to create certificate right and push notification with Sandbox env when we test it.

**Comment by cx5168** [comment]
@xoapit
Can you give me a detailed step?
