### ISSUE TITLE
Android doesn't connect to Firebase

### ISSUE THREAD

**Issue by clemenskroell** [zo0r/react-native-push-notification#1015]
We setup up push notifications like for any other app (which worked normally). This time, we copied the android linking stuff from another working app, but it doesn't connect to the firebase server. Instead we receive the following logcat message:

`W/InstanceID: Instance ID SDK is deprecated ###bundle_id### should update to use Firebase Instance ID`

We use the exact same versions of the lib. The token gets generated normally.

While setting up the firebase project, it won't processed hanging in this view:
![screenshot 2019-03-06 at 14 17 08](https://user-images.githubusercontent.com/435783/53883871-8ec34500-401a-11e9-8902-40630815d00d.png)

Any advice?

**Comment by bjacog** [comment]
@clemenskroell I got the same behaviour, my messages are still delivered.
