### ISSUE TITLE
Can i set localNotificationSchedule with specific days to repeat?

### ISSUE THREAD

**Issue by aaronnunez95** [zo0r/react-native-push-notification#1022]
I want to set local notifications with specific days to repeat, for example, each monday and saturday in every week.

Any solution?

**Comment by Sheleya** [comment]
Any updates?

**Comment by aaronnunez95** [comment]
@Sheleya my solution was the following, if i has an event for Monday and Tuesday, i scheluded a two notifications with repeatType = 'week', one for mondays and the other for 'tuesdays'.

Hope this can help you.

**Comment by Sheleya** [comment]
I have a task that user sets the start and the end time of notification, and the interval between notifications. For example, start time - 10AM, end time - 8PM, interval - 3hrs, it means that every day the app should send me a notification from 10AM to 8PM every 3 hours

**Comment by aikewoody** [comment]
@Sheleya Have you found a solution for your specific problem?

In our app we want to repeat a local push notification every 30 seconds for a duration of 5 minutes.

**Comment by Estela01** [comment]
any update @Sheleya ?
