### ISSUE TITLE
Same device multiple accounts - remote notification

### ISSUE THREAD

**Issue by petrovkire** [zo0r/react-native-push-notification#1025]
Can i execute some function before the notification shows up ?

I am using the notifications for logged users, but if the user is not logged in at that moment or another user has logged from the device, the device token is same and they will receive the notification anyway.

**Comment by hohien** [comment]
I'm having the same, Do you find any solution?

**Comment by TheOverRide** [comment]
Well we decided to handle it on the server side, example if another user logs in to the account we check if that device exists in DB and if so we delete it from previous account and we assign it to the newly logged in user.
