### ISSUE TITLE
iOS: Multiple notification open events received before the JS notifications module has been initialized

### ISSUE THREAD

**Issue by d-vincent** [zo0r/react-native-push-notification#1026]
When tapping a notification on iOS to open the app, the onNotification method is not firing. I am met with the message: "Multiple notification open events received before the JS notifications module has been initialized" and I am not sure what to do. I am calling 
"NotifService.configure();" 
in the root file outside of the lifecycle, and I am also calling "PushNotification.popInitialNotification((notification) => {})"
which does not fire on iOS.
It is also worth noting that onNotification does not fire even when the app is in the foreground.
I am also using FCM to send these notifications as opposed to GCM.
Everything is working fine and as expected on Android. Any help?

**Comment by markuscosinus** [comment]
I'm having the same issue for local notifications. Any updates?

**Comment by mathiasmoeller** [comment]
Did anyone solve this issue yet?

**Comment by markuscosinus** [comment]
Didn't really solve it, however I noticed that for me this only happens after a reload. When I rebuild the app the notifications work fine.
