### ISSUE TITLE
Get the id from background

### ISSUE THREAD

**Issue by celestial2** [zo0r/react-native-push-notification#1028]
When i receive a notification while application is in background i am not getting the parameters sent with the notification in the function that it called in.

The message content is correct in the notification box, but when i open it i do not get its info. I need to get an id from it so i can trigger a specific action.

Has anyone encountered the same problem and found a solution ? 
Any ideas are appreciated.
Thanks.

**Comment by hammooooody** [comment]
For the benefit of others. 
Received notification content for Foreground and background differ slightly. Depending on what you put in `data` and `notification` objects which are sent by the admin. Take a look at [point 6](https://medium.com/enappd/firebase-push-notifications-in-react-native-apps-d9f60726ce9c) here and [this](https://stackoverflow.com/a/54490885).
