### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by TheOverRide** [zo0r/react-native-push-notification#1029]
Is this repository getting any updates and fixes anymore ?

**Comment by slavikdenis** [comment]
465 issues, 58 PR. Seems like a normal RN repo to me. See https://github.com/zo0r/react-native-push-notification/issues/716

**Comment by calcazar** [comment]
It's dead, use wix's react-native-notification

Very similar and has pushkit capability

**Comment by TheOverRide** [comment]
@calcazar 
Thanks buddy, i tried it and it works perfectly. 

If anyone else struggles here you definitely should try wix's.
Really accurate documentation & it's pretty easy to use and offers nice, well described functionalities.

**Comment by ThanhQuang1410** [comment]
Can i use react-native link with wix's

**Comment by TheOverRide** [comment]
By the manual you are adding the needed content in MainApplication.java and the gradle files manually, so you don't need react-native link. But if you want to use it i think it will not be a problem, just skip the steps in the installation that are doing that manually.
