### ISSUE TITLE
Silent Push Notification is not working App is killed ?

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [zo0r/react-native-push-notification#1031]
Hi,

I have integrate your SDK working fine in my Apps. According to requirement create silent push notification So change the payload at server side like below,

```
{
  "aps":
    {
	"content-available": 1
    }
}
```

According to the payload. on Foreground there is blank alert are there, and in background without killed it's fine. I have setup push notification code in my App.js file.

**But When App killed the Silent Push is not working.**

[Document](https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md)

Please can you help me.

Thanks.

**Comment by ddthuan87** [comment]
Did you have another good solution?

**Comment by ThomasLarge** [comment]
@kiritnim did you find out how to do this?

**Comment by ThomasLarge** [comment]
@ddthuan87 I have got this working now, have you made a VoIP certificate?
