### ISSUE TITLE
Android Local Scheduled Notification fires immediately

### ISSUE THREAD

**Issue by acrabb** [zo0r/react-native-push-notification#1033]
has anyone else run into this, where upon calling `PushNotification.localNotificationSchedule( { ... } )`, the notification _is_ scheduled, but fires right away. (And displays when the app is open, though that's not the point of this issue.)

**Comment by acrabb** [comment]
🤦‍♂️ it was scheduled in the past

**Comment by enzzoperez** [comment]
@acrabb Hi, can u show me an example of your localNotificationSchedule setting please?, it's passing to me, but I don't know if I'am passing the correct format of Date in the argument

```
PushNotification.localNotificationSchedule({
            title: "Notificación ", 
            message: "Esta es una notificación que configuraste con determinada fecha", 
            date: new Date(year, month, day, hour, minute)
  })
```
