### ISSUE TITLE
broadcast intent callback: result=CANCELLED

### ISSUE THREAD

**Issue by fermuch** [zo0r/react-native-push-notification#104]
If the app is closed/killed and I try to send a notification from the server, I get that message.

Full message:

```
W/GCM-DMM ( 9598): broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.mypackage.myapp (has extras) }
```

Is there something I can try to solve this?

**Comment by npomfret** [comment]
@fermuch do you still have this issue? if so, have you tried the latest release? if not, can we close it?

**Comment by fermuch** [comment]
Sorry I forgot to update the status! Since the last update I don't have 
this issue anymore. Thanks!

**Comment by sachin-sable** [comment]
@npomfret I am still having this issue with version 2.2.1 and some specific android devices i.e. One plus 3, One plus 5. Please let me know on which version you have fixed this. Or Any solution to this is greatly appreciated.

Thanks.
