### ISSUE TITLE
3.1.3 EISGIT error

### ISSUE THREAD

**Issue by rgollancz** [zo0r/react-native-push-notification#1043]
Installing version 3.1.3 is causing an `EISGIT` error. It looks like it's being caused by a `.git` directory in the installed module.

I've hardcoded to version 3.1.2 to get around the error for now.

**Comment by fishkingsin** [comment]
same here

**Comment by ThanhQuang1410** [comment]
Same here. Even if i install 3.1.2. Any solution?

**Comment by fishkingsin** [comment]
> Same here. Even if i install 3.1.2. Any solution?

uninstall 3.1.3 then install 3.1.2 explicitly

**Comment by ThomasK33** [comment]
_Or if one uses npm, create a postinstall script and use rimraf to delete the git directory._

Of course that's only a workaround

**Comment by ClementPF** [comment]
removing the .git file located @ `node_modules/react-native-push-notification` prevents the error.
You could automate the deletion like @ThomasK33 suggested

**Comment by kristoferpelchat** [comment]
@zo0r Any thoughts on when you could get to this? It's a quick fix that I could PR for you...

**Comment by wumke** [comment]
As can be found on [https://docs.npmjs.com/misc/developers](https://docs.npmjs.com/misc/developers)

> Keeping files out of your package§
> Use a .npmignore file to keep stuff out of your package. If there’s no .npmignore file, but there is a .gitignore file, then npm will ignore the stuff matched by the .gitignore file. If you want to include something that is excluded by your .gitignore file, you can create an empty .npmignore file to override it. Like git, npm looks for .npmignore and .gitignore files in all subdirectories of your package, not only the root directory.
> 
> .npmignore files follow the same pattern rules as .gitignore files:
> 
> Blank lines or lines starting with # are ignored.
> Standard glob patterns work.
> You can end patterns with a forward slash / to specify a directory.
> You can negate a pattern by starting it with an exclamation point !.
> By default, the following paths and files are ignored, so there’s no need to add them to .npmignore explicitly:
> 
> .*.swp
> ._*
> .DS_Store
> .git
> .hg
> .npmrc
> .lock-wscript
> .svn
> .wafpickle-*
> config.gypi
> CVS
> npm-debug.log

the .git should not be in the npm package, no idea how or why it ended up in there.... in the mean time just delete it and go :-)

**Comment by rbary** [comment]
Removing the .git in the npm package fixes the issue as mentioned by @wumke.
thnks !
