### ISSUE TITLE
mute sound for local notification not working

### ISSUE THREAD

**Issue by roysG** [zo0r/react-native-push-notification#1045]
I tried to change the value playSound to "false" but the notification sound is still on.
What should i do?

**Comment by cristianoccazinsp** [comment]
Facing the same issue. Local notifications always have sound AND vibration; can't mute them. Any thoughts?

**Comment by cristianoccazinsp** [comment]
Most likely related to the importance/priority flags. Since priority was deprecated, and notification channel importance is now used, based on the notification channel importance the notification can or not play sounds. This is from testing a notification channel with a foreground service. However, I wasn't able to mute the notification even with a low importance/priority.

**Comment by Shoaib-Raza** [comment]
Any update on this issue.
I am also facing the same issue, i want to mute the sound but playSound = false doesn't work.

**Comment by necto68** [comment]
https://github.com/zo0r/react-native-push-notification/issues/1140#issuecomment-528331545

**Comment by greenais** [comment]
The same issue here.
I expect my users to be disturbed by such inflexibility(

**Comment by dgreasi** [comment]
Facing same issue here.

Versions:
"react-native-push-notification": "^6.1.2",
"react-native": "0.63.2",

Any updates?

**Comment by dgreasi** [comment]
I actually found a workaround that is working on android but it will be also a silent notification, which means it will not be visible if you dont open your notifications tray.

In my case is what i wanted

On the createChannel you need to specify a low importance. Thus the working code for me:
```
PushNotification.createChannel(
    {
      channelId: 'silent-notification',
      channelName: 'A silent notification channel,
      importance: 2, // < 3 seems to do the job
      vibrate: false,
      soundName: undefined, // works even if it is not specified
    },
    (created) => console.log(`createChannel returned '${created}'`),
  );
```

The function that i use to trigger my local notification:
```
export const showNotification = (
  title: string,
  message: string,
  isSticky: boolean = false,
  soundName = 'default',
  isSilent = true,
) => {
  PushNotification.localNotification({
    title,
    message,
    channelId: 'silent-notification',
    ongoing: isSticky,
    vibrate: !isSilent,
    playSound: !isSilent,
    soundName,
    smallIcon: 'ic_notification_video',
    largeIcon: 'bootsplash_logo',
  });
};
```

**Comment by sonnd08** [comment]
The same issue
