### ISSUE TITLE
"Setting up Firebase Cloud Messaging" wizard changes the plugin's app.gradle

### ISSUE THREAD

**Issue by hariv1505** [zo0r/react-native-push-notification#1046]
Problem:
My app crashed whenever it was receiving notifications. Error in Android Studio console was: `Default FirebaseApp is not initialized in this process com.example.app. Make sure to call FirebaseApp.initializeApp(Context) first.`

Solution:
I installed the plugin before connecting to Firebase.

When connecting to Firebase, the "Connect your app" step is fine, and so is the "Add FCM to your app" step. However, the second step adds two more lines to the react-native-push-notification project.

![Selection_079](https://user-images.githubusercontent.com/3837155/56112554-bfde5000-5f9e-11e9-8c2b-faf5927299e4.png)

Neither are necessary because:
- the first one just isn't, it should only be added to your own root project
- the second one is accounted for when doing `react-native link` anyway

I guess the simplest thing to do is to make people aware that this can happen (I was scratching my head for a bit as to what I had done different before I realised), but above all else it's an FYI since I couldn't find the issue documented anywhere

**Comment by tmaly1980** [comment]
There's no need to install the plugin via Android Studio. Simply follow the instructions of this plugin's README.

**Comment by logantheproblemsolver** [comment]
@hariv1505 what plugin did you install on your app to get this issue to go away? I know it's been awhile, so I'm wondering if you still remember it, I'm having the same issue and I'm not sure why.

**Comment by hariv1505** [comment]
It was just installing this product first, then afterwards I connected up FCM using Android Studio. I didn't involve any other plugins specifically for overcoming this issue. 

Also I'm sure I followed the README correctly but still needed to hook up FCM - too long ago now, I may revisit if I have time.
