### ISSUE TITLE
Is it possible to have multiline notifications?

### ISSUE THREAD

**Issue by nschild** [zo0r/react-native-push-notification#1048]
Hello,
I am using version 3.1.2 and am having issues displaying multi-line notifications.

    PushNotification.localNotificationSchedule({
        title: "this shows an ellipsis",
        message: "this is a really long message that just keeps going and going and going. After a while, the message will be truncated with an ellipsis.",
      });
    };
    PushNotification.localNotificationSchedule({
        title: "this shows only the first line",
        message: "this is the message. \r\n This line is hidden \r\n So is this one.",
      });
    };
    PushNotification.localNotificationSchedule({
        title: "this shows only the first line",
        message: `this is the message. 
    This line is hidden 
    So is this one.`,
      });
    };
    PushNotification.localNotificationSchedule({
        title: "this shows only the first line",
        message: `A comment suggested using a plus symbol to force a line break. +
    This line is hidden +
    So is this one.`,
      });
    };
    
    // and to cover all the bases
    PushNotification.localNotificationSchedule({
        title: "this shows only the first line",
        message: "this is the message. <br> of course this is preceded by '<br>'.",
      });
    };

EDIT: I added the backtick tests, suggested from a comment that was removed?

Created via the backtick newline method. When expanded, it just reveals a ton of white space.
![Screen Shot 2019-04-17 at 11 06 27 AM](https://user-images.githubusercontent.com/48523809/56300043-32684080-6103-11e9-83b9-47a21e130bb3.png)

**Comment by RickSmallenbroek** [comment]
PushNotification.localNotificationSchedule({
visibility: "public",
message: `This is your first line` +
`And this will be your second line`,
        });

**Comment by RickSmallenbroek** [comment]
@nschild try doing this;

PushNotification.localNotificationSchedule({
visibility: "public",
message: `This is your first line` +
`And this will be your second line`,
        });

Instead of using the normal dubble quotes (") use a  grave accent (`) inside your message.
It will require some spacing but it worked for me.

**Comment by toxxiczny** [comment]
Put the message to bigText object

**Comment by silencer07** [comment]
@toxxiczny is it possible to merge this commit so that bigText can have html tags?

https://github.com/zo0r/react-native-push-notification/pull/1469
