### ISSUE TITLE
Cancelling a repeating notification

### ISSUE THREAD

**Issue by mo-patel** [zo0r/react-native-push-notification#1055]
Is there any method of cancelling a repeated notification? I currently schedule a notification to be fired at a specific time along with a repeat type. These notifications are then repeated infinitely unless manually cancelled each time using their id. Is there anyways to include a possible dateTime these notifications should stop firing?

**Comment by tberghuis** [comment]
When scheduling the notification you could store lastNotificationTime in some var then in the onNotification handler cancel the scheduled notifications if currentTime > lastNotificationTime.

**Comment by mo-patel** [comment]
Thank You for the reply.
I am already using this method but it would be a lot better if this functionality was supported by the library itself rather than having to rely on workarounds.

Also, there is an issue with the onNotification handler as it only fires a notification is clicked on but not received which could be a big usability issue.

**Comment by nicolascoutureau** [comment]
Hi, did you find a workaround?

**Comment by mo-patel** [comment]
No official way of doing this yet. I am still using the workaround mentioned by @tberghuis

**Comment by nicolascoutureau** [comment]
Thanks for your answer!

**Comment by erdenayozkanl** [comment]
Is there any way to do repeatly push notification in IOS?

**Comment by jagadeeshym-dev** [comment]
@mo-patel @tberghuis what is the work around to cancel repeated notification ??
onNotification method will be triggered during our first Initial notification or when notification is pressed.
onNotification method is not getting called for every repeated notification

my scenario is I need to continuously repeat notification for 5 minutes 
After 5 minutes notification need to be cancelled 
Not sure how to achieve this

can you please help us out

**Comment by Dallas62** [comment]
You can schedule a notification per X (minute?) until 5mn.
Be careful to not abuse this method, there is some limitations in some Android devices (max 30scheduled tasks/notification)

**Comment by jagadeeshym-dev** [comment]
@Dallas62 I did that, with repeatType as time and repeatTime as 10000 milliseconds.
I want to stop the schedule notification after 5 minutes.
I got stuck in this part

**Comment by Dallas62** [comment]
This is because you think about repeating the same notification.
You can setup a scheduled new/different notification every 10s.
