### ISSUE TITLE
onNewIntent should be public as of RN 0.28

### ISSUE THREAD

**Issue by kaminskypavel** [zo0r/react-native-push-notification#106]
if you're getting 

> error: onNewIntent(Intent) in MainActivity cannot override onNewIntent(Intent) in ReactActivity

change your onNewIntent to public

```
    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        mReactNativePushNotificationPackage.newIntent(intent);
    }

```

**Comment by cihancil** [comment]
+1

**Comment by zo0r** [comment]
https://github.com/zo0r/react-native-push-notification/pull/107
https://github.com/zo0r/react-native-push-notification/commit/2dd2f41a79cb0f956d64edc233f995fdf2981a65

**Comment by shriganesh64** [comment]
+1
