### ISSUE TITLE
Update ShortcutBadger

### ISSUE THREAD

**Issue by cristianoccazinsp** [zo0r/react-native-push-notification#1060]
Gradle is currently using ```'me.leolin:ShortcutBadger:1.1.8@aar'```, but the latest version is 1.1.23 which seems to have some nice fixes.

Steps to update this easily?

**Comment by eduardopelitti** [comment]
As far as I can see the latest released version on Maven is 1.1.22. 

But the library seems abandoned and there are various issues that have gone several months without answer from the repository owner.

**Comment by cristianoccazinsp** [comment]
You are right, the library doesn't really seem to be working at all, and seems abandoned. I guess using badge counts in Android is not reliable right now.
