### ISSUE TITLE
push notification not show in android 9

### ISSUE THREAD

**Issue by fatemehmemar123** [zo0r/react-native-push-notification#1063]
hi 
i install react-native-push-notification": "^2.0.1", 
and notification show in android 6 but not show in android 9 
please help me

**Comment by dewaadiperdana** [comment]
@fatemehmemar123 maybe you should use the newer version of the package, i use version `^3.1.3`, and it works fine on my device. But i'm not using the android 9, im on android 8 by the way.

**Comment by andrewtremblay-pear** [comment]
I was running into this issue as well. The solution was found in the documentation. 
I was missing necessary permissions and metadata in the android manifest:  https://github.com/zo0r/react-native-push-notification#android-manual-installation

**Comment by maamounapprise** [comment]
still has an issue although I added all required permissions. 

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.app"
  android:versionCode="<%= versionCode %>"
  android:versionName="<%= versionName %>">
  <uses-permission android:name="android.permission.WAKE_LOCK" />
<permission
        android:name="<%= bundleId %>.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
        <uses-permission android:name="<%= bundleId %>.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.USE_FINGERPRINT" />
    <application
      android:name=".MainApplication"
      android:label="<%= appName %>"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="<%= appName %>"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter android:label="filter_react_native">
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="<%= uriScheme %>" android:host="home" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
                android:value="ALERTS"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                    android:value="ALERTS"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@android:color/white"/>
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="<%= bundleId %>" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
    </application>
</manifest>
`

**Comment by faisal3413** [comment]
I solve the issue by downgrading the version of ‘react-native-push-notification’ to ‘3.1.2’.
