### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by ruslanchek** [zo0r/react-native-push-notification#1064]
This repo seems abandoned, isn't it? A huge amount of unresolved issues and PRs.

**Comment by cristianoccazinsp** [comment]
Would like to know this as well. It's a good repo, hopefully someone can take over and start merging PRs.

**Comment by orta** [comment]
Maybe this could get moved into react-native community? /cc @kelset

**Comment by kelset** [comment]
I wish - I tried to get the maintainers attentions almost two years ago now...  https://github.com/zo0r/react-native-push-notification/issues/575

and got no response anywhere (even tried to reach out via email).

I know there was a proposal in the RNComm to do some more work around push-notifications, but also that was sort of abandoned 😓

I'm open to moving this but it would require at least a few maintainers working a lot on it to bring it back to usable IMHO (and also, it needs @zo0r to move this repo to me first)

**Comment by paul-doherty** [comment]
@kelset maybe the bullet needs to be bitten and just fork it? Not the best option obviously but the alternative seems to be letting this atrophy. I for one am willing to assist maintaining

**Comment by Dallas62** [comment]
Hi @kelset 

Just saw your comment, what would be the process to move this repository to React-Native Community ?
I have write access to NPM, but not access of settings in Github at the moment.

The API of the library is not the best that can be done. But there is probably a way to merge this library with the iOS one to improve both of them at the same speed/time.

I'm a freelance so I will not be able to find more time than actually. But I can keep the same time-allocation to help on this project and other RNC projects.

Best regards,

**Comment by kelset** [comment]
There's currently no precise process and there's an ongoing conversation over which packages belongs into it: https://github.com/react-native-community/discussions-and-proposals/issues/176
which should receive an important update in terms of guidelines in the next few weeks. Until then I don't know what the best approach would be (and either way, it'd require admin access to the repo on GH)
