### ISSUE TITLE
How to get Scheduled Local Notifications in react-native (ANDROID)

### ISSUE THREAD

**Issue by ameenmattar** [zo0r/react-native-push-notification#1067]
I want to get all my scheduled local notifications, 
So on iOS i used this PushNotificationIOS.getScheduledLocalNotifications, while on Android i couldn't find a way.

```
 PushNotificationIOS.getScheduledLocalNotifications(Localarray => {
        console.log("getScheduledLocalNotifications", Localarray);
  });
```

**Is there a way in android too @zo0r  ?**

**Comment by l-Legacy-l** [comment]
I'm looking for the same feature, have you found a solution ?

**Comment by ameenmattar** [comment]
Unfortunetly  I haven't found a solution yet, what i did for android is that i used my local database 'realm' to save the push-notification as records,  and then retrieve them one by one whenever i want to use them. I hope  that we can find a way like the IOS one.

**Comment by Fatih5959** [comment]
Hello  @l-Legacy-l,@ameenmattar,  this method for android.
[PushNotification.getScheduledLocalNotifications(callback)](https://github.com/zo0r/react-native-push-notification#6-getscheduledlocalnotifications)
