### ISSUE TITLE
Push Notification (remote, foreground) doesn't use custom sound

### ISSUE THREAD

**Issue by renato-bvdash** [zo0r/react-native-push-notification#1069]
In my FCM notification I send a custom sound which is respectively in the `resources` / `res/raw` folders of the app. While on the background, the remote notification arrives and uses the specified sound (not default), yet when on the foreground, it uses the `default` sound.
I want to get the custom sound to be played while on the foreground as well.
This is the setup I have:

```
PushNotification.configure({
  // (optional) Called when Token is generated (iOS and Android)
  onRegister: function(token) {
    console.log('TOKEN:', token)
  },

  // (required) Called when a remote or local notification is opened or received
  onNotification: function(notification) {
    console.log('Ntif:', notification);
    
    if (notification && notification.userInteraction)
      takeToRoute(notification)

    // process the notification

    // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
    if (Platform.OS === 'ios')
      notification.finish(PushNotificationIOS.FetchResult.NoData);
  },

  // ANDROID ONLY: GCM or FCM Sender ID (product_number) (optional - not required for local notifications, but is need to receive remote push notifications)
  senderID: 'xxxxxxxxxx',
})
```

Any tips or help of any kind would be appreciated.

**Comment by williamwilliamwilliam** [comment]
Check out PR #1042 

I forked the repo and merged that PR. It solved the issue for me.

**Comment by apski** [comment]
> Check out PR #1042
> 
> I forked the repo and merged that PR. It solved the issue for me.

Is there a fix for iOS?

**Comment by sangameshrently** [comment]
@renato-bvdash How you mapped custom sound ?
