### ISSUE TITLE
Sample demo error - Implementation method for arguments 

### ISSUE THREAD

**Issue by AlexMachin1997** [zo0r/react-native-push-notification#1071]
Hi,

I'm trying to set up the example app but I can't seem to run it, I keep getting the following error message:

![image](https://user-images.githubusercontent.com/29917195/57882454-aa697980-781b-11e9-8ee8-f1264b2bf60c.png)

I'm not exactly sure what I've done wrong. All I did was install the npm dependencies and start the app, but I keep getting the error above. It would be much better to provide a set of detailed instructions on how to set the example up :)

**Comment by jackmew** [comment]
I face the same problem. How can you solve it? @AlexMachin1997 ?

**Comment by AlexMachin1997** [comment]
I ditched the plugin, I went with Expo instead much more reliable.

**Comment by jackmew** [comment]
I see.
