### ISSUE TITLE
popInitialNotification returns different notification format on iOS

### ISSUE THREAD

**Issue by jdmunro** [zo0r/react-native-push-notification#1075]
`onNotification` processes a notification before the application receives it, seen here: https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L220

However, `popInitialNotification` doesn't: https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L312

This causes in consistencies between the types of notification object. For instance, custom data will be called `data` in the case of `onNotification` but `_data` if using `popInitialNotification`.

**Comment by nighttiger1990** [comment]
same issue. And `popInitialNotification` only fire with data in Release mode (always null in debug mode). It's so difficult to debug. Hope this will be fix soon
