### ISSUE TITLE
Notification gets triggered automatically android

### ISSUE THREAD

**Issue by SiddharthRana** [zo0r/react-native-push-notification#1076]
I am trying to customise the data i receive from api and then show notification on android using localNotification. But the notification is triggered as soon as i hit the api. Please can someone help me with this problem.

**Comment by wbercx** [comment]
Do you have a code example? It sounds like you're not waiting for the API response to arrive.

**Comment by SiddharthRana** [comment]
`let self = this
        PushNotification.configure({ // done so that when device starts its token is obtained for push notifications
            onRegister: function (tokenObj) {
                console.log('fcm onRegister Token :', tokenObj);
                self.registerTokenOnServer(tokenObj.token)
            },
            onNotification: function (notification) {
                console.log('NOTIFICATION:', notification)
            },
            senderID: '278778628448',
            permissions: {
                alert: true,
                badge: true,
                sound: true,
            },
            popInitialNotification: false,
            requestPermissions: true,
        })`

This is my react native code. I want to handle notification in onNotification and then show it using localnotification. But it gets triggered as soon as i hit the api.

`
        <meta-data
            android:name="com.dieam.reactnativepushnotification.notification_channel_name"
            android:value="OSR_CHANNEL" />
        <meta-data
            android:name="com.dieam.reactnativepushnotification.notification_channel_description"
            android:value="OSR_CHANNEL_DESCRIPTION" />
        
        <meta-data
            android:name="com.dieam.reactnativepushnotification.notification_color"
            android:resource="@android:color/white" />

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>

        
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        `

This is the code for pushnotification in my manifest file.

**Comment by clfristoe** [comment]
When you say the notification is triggering instantly, do you mean the app is starting up automatically? And is the initial notification a data-only payload?

**Comment by SiddharthRana** [comment]
app is not starting automatically. see what i am trying to do is manipulate a string coming in notification data and then showing it on the phone. but notifications triggers as soon as i hit the api not giving me a chance to show what i want to.

**Comment by clfristoe** [comment]
I don't think I'm understanding what you're trying to do. What do you mean when you say the notification triggers? Does it immediately display on the device before you can make the changes to it?

**Comment by SiddharthRana** [comment]
Yes. I want to trigger notification using Pushnotification.localNotification(), but it gets triggered before it.
