### ISSUE TITLE
Install any Lib

### ISSUE THREAD

**Issue by lfoliveir4** [zo0r/react-native-push-notification#1077]
After installing the react-native-push-notification library, it is no longer possible to install any react native libraries. When trying to install another lib in the project, the error below is displayed:

![Captura de Tela 2019-05-27 às 14 33 56](https://user-images.githubusercontent.com/32423942/58433273-c9260680-808c-11e9-83f1-ca509928bac6.png)

To solve the problem it is necessary to uninstall the lib with "npm uninstall react-native-push-notification" and install the desired lib. But this process disrupts the performance of the project.

**Comment by freely322** [comment]
use `rm -rf .git` in project directory to fix it

**Comment by fpmweb** [comment]
I have the same problem

**Comment by freely322** [comment]
> I have the same problem

Try `rm -rf node_modules/*/.git`

**Comment by fpmweb** [comment]
Yes! now perfect.
The problem is the .git directory that must be deleted (every time).

And that for iOS, it is necessary to do the part of manual installation.

**Comment by lfoliveir4** [comment]
> use `rm -rf node_modules/*/.git` in project directory to fix it

It's Solved !!!
