### ISSUE TITLE
Duplicate onNotification calls

### ISSUE THREAD

**Issue by paul-doherty** [zo0r/react-native-push-notification#1078]
Hey,

I appear to be getting duplicate notifications for both iOS and Android. For a given push (without interaction) I get the onNotification handler called twice. For noisy/mixed notifications this means two notifications are shown in the notification centre.

E.g. from Android
This one appears to have the google metadata
```
{
    color: null
    data: {someData: "example"}
    finish: ƒ finish()
    foreground: true
    google.delivered_priority: "normal"
    google.message_id: "0:1559037885338181%6af40c24f9fd7ecd"
    google.original_priority: "normal"
    google.sent_time: 1559037885334
    google.ttl: 2419200
    id: "1513948521"
    message: "aBody"
    pinpoint.campaign.campaign_activity_id: "ad08775a9d21480aab6768c024060627"
    pinpoint.campaign.campaign_id: "24d11aa26b934153b5bde9205993e33e"
    pinpoint.campaign.treatment_id: "0"
    sound: "default"
    title: "aTitle"
    userInteraction: false
}
```

This one appears is the same but **without** google metadata

```
{
    color: null
    data: {someData: "example"}
    finish: ƒ finish()
    foreground: true
    id: "1505484046"
    message: "aBody"
    pinpoint.campaign.campaign_activity_id: "ad08775a9d21480aab6768c024060627"
    pinpoint.campaign.campaign_id: "24d11aa26b934153b5bde9205993e33e"
    pinpoint.campaign.treatment_id: "0"
    sound: "default"
    title: "aTitle"
    userInteraction: false
}
```

is anybody else experiencing this?

**Comment by SilwalUjjwal** [comment]
Yes, we are experiencing the same issues. This might have something to do with multiple specifications for FCM and GCM in the AndroidManifest file. 
To solve this, we tried keeping only FCM's specification in manifest file which solved the issue.

**Comment by paul-doherty** [comment]
@SilwalUjjwal Thank you very much. You were bang on the money.

https://developers.google.com/cloud-messaging/android/android-migrate-fcm agrees with you stating 
```
The FCM SDK automatically adds all required permissions as well as the required receiver 
funtionality. Make sure to remove the following obsolete (and potentially harmful, as they 
may cause message duplication) elements from your app's manifest:
```

I removed 
```
   <!-- < Only if you're using GCM or localNotificationSchedule() > -->
        <receiver
                android:name="com.google.android.gms.gcm.GcmReceiver"
                android:exported="true"
                android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>
        <!-- < Only if you're using GCM or localNotificationSchedule() > -->
```
and no longer receive them twice

Thanks again

**Comment by tmaly1980** [comment]
@paul-doherty Did you fix iOS? Was that a separate issue? The code above looks like it's for Android only

**Comment by rezasazesh** [comment]
Yes how did you fix this on iOS

**Comment by VanDinh18** [comment]
how did you fix this IOS. i have this issue on IOS

**Comment by anilkumar2273702** [comment]
Still, I'm getting the same issue.

`<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">

      
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                  android:value="true"/>
 
      
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                  android:resource="@color/white"/> 

      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED" />
              <action android:name="android.intent.action.QUICKBOOT_POWERON" />
              <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
          </intent-filter>
      </receiver> 

      <service
          android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
          android:exported="false" >
          <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
      </service>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      
    </application>`

**Comment by rakesho-vel** [comment]
I am also getting this issue, its working fine in Android and iOS as well, but when iOS app is killed (not in background) and I click on notification, it gives 2 onNotification events.

**Comment by hukpavlo** [comment]
@rakesho-vel did you solve it?

**Comment by rakesho-vel** [comment]
@hukpavlo , no, but I updated my implementation to make sure it doesn't affect the app functionality when user clicks on notification.
