### ISSUE TITLE
Detailed installation instruction

### ISSUE THREAD

**Issue by amundio** [zo0r/react-native-push-notification#1079]
Decided to learn react native this weekend and can't stop until I get it working... 
After being amazed by how easy it is to work with react-native and expo cli I decided to use the repo and start serving push notifications. And here the nightmare begins... Completely unsure how to configure xCode as this steps aren't described anywhere.

I do understand I need to eject my project but not sure how exactly. There are 2 options: 
- React Native: I'd like a regular React Native project.
- ExpoKit: I'll create or log in with an Expo account to use React Native and the Expo SDK.

Which one of the 2 above should I use when trying to link the notifications? Automatic notifications don't work on iOS and I am following the steps: https://facebook.github.io/react-native/docs/pushnotificationios.html#content

I can build bundle when first eject option picked but can't run it on mobile device after. ExpoKit option is causing multiple issues starting from cocapods working only in version 1.5.3 ending on missing RCTEventEmitter.h which I never got sorted...

Any help would be very appreciated.

**Comment by paulrenenichols** [comment]
I also am having problem with RCTEventEmitter.h with an ejected Expokit SDK 32 app.

**Comment by amundio** [comment]
I got pass through this one but was facing different issues after.

It's really easy if you use:

`react-native init myApp`
