### ISSUE TITLE
RSOD with version 1.1.0

### ISSUE THREAD

**Issue by joegoodall1** [zo0r/react-native-push-notification#108]
![img_0011](https://cloud.githubusercontent.com/assets/8888799/16334374/708744d6-39f8-11e6-8bdb-bfbb5288cb0f.jpg)

Getting this error after updating to 1.1.0 (no such error with 1.0.6).

**Comment by zo0r** [comment]
Fixed: https://github.com/zo0r/react-native-push-notification/commit/4ad315f9985387673c8cd33ccec22a2b3131d894

Try using **1.1.1**

**Comment by joegoodall1** [comment]
Makes sense. Thanks for the quick response.
