### ISSUE TITLE
AndroidManifest.xml example if you only need localNotificationSchedule to work

### ISSUE THREAD

**Issue by tberghuis** [zo0r/react-native-push-notification#1087]
The example given in the README is not clear as the comments mention `Only if you're using GCM or localNotificationSchedule()` . My app does not need GCM. 

Also do I need the permission for WAKE_LOCK?

**Comment by navasiloy** [comment]
You have to add all described in the doc https://github.com/zo0r/react-native-push-notification#android-manual-installation
except the bottom `Else` part
