### ISSUE TITLE
Notifications on Android are not displaying in either Foreground or Background

### ISSUE THREAD

**Issue by brianzzzasd** [zo0r/react-native-push-notification#1090]
Notifications are not popping up on Android, but in IOS, it's working properly. Any ideas?

```
Package Version '3.1.1'
buildToolsVersion '28.0.3'
```

Code  : 
- Notification
```
 PushNotification.localNotification({
      title: "test title",
      message: "test message",
 });
```
- Notification Configuration

```
PushNotification.configure({
    permissions: {
        alert: true,
        badge: true,
        sound: true
    },

    popInitialNotification: true,
    requestPermissions: true,
});

```

**Comment by maamounapprise** [comment]
@brianzzzasd Same issue, have you found a solution?

**Comment by ishaqashraf** [comment]
same issue , any solutions?

**Comment by maamounapprise** [comment]
found solution, i checked the logcat then saw an error at the conversion of the notification id. I had to fork the repo because our notification id is an object not a string.

**Comment by kalraneeraj24550** [comment]
i am also not getting notification, anyone please help

**Comment by brianzzzasd** [comment]
I closed this Issue since it looks like a duplicate one.

Though I haven't fixed this one yet.

**Comment by kalraneeraj24550** [comment]
i noticed that my notifications come when i have android OS less than oreo.
notifications were coming in my lollipop operating system.
To let notifications come even in oreo devices .
i added these lines in menifest


  <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
        android:value="YOUR NOTIFICATION CHANNEL NAME"/>

    <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
        android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION"/>

    
    <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
        android:resource="@android:color/white"/>

these lines solved mine issue
