### ISSUE TITLE
AndroidManifest.xml:22:18-91 Error:

### ISSUE THREAD

**Issue by Ethan0007** [zo0r/react-native-push-notification#1091]
Hi,

When configuring the push notification in the fresh project and run the application  i got this error:

 Error:
        Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.

 "react-native": "0.59.9",
 "react-native-push-notification": "3.1.3",

**Comment by mattimck** [comment]
I came to post about this too. Seems to be a new problem from today, due to a new gms version. Same problem is being discussed for `react-native-device-info`, where they already have a PR up https://github.com/react-native-community/react-native-device-info/pull/693/commits/ec930b3f61da83e46cd70ecd108e0fe7a873fcb0. 

This same change makes `react-native-push-notification` work too, from my own testing, so hopefully that helps you for now, too.

**Comment by uropsm** [comment]
same issue here.
@mattimck I just changed the gms version in build.gradle of react-native-push-notificatoin as the link. but It didn't work. Could you explain how to apply it?

**Comment by uropsm** [comment]
with @mattimck 's solution, 
I also changed firebase version to 17.6.0 and build is success.
Don't know yet if it works.

**Comment by mattimck** [comment]
FYI, PR is here https://github.com/zo0r/react-native-push-notification/pull/1092

**Comment by pram11** [comment]
after watching @mattimck 's solution,
I changed one but it came with error 'Could not find com.google.firebase:firebase-messaging:16.1.0.'
so I changed firebase version to 17.6.0, but it did not help.
keeps showing same error.

**Comment by uropsm** [comment]
> after watching @mattimck 's solution,
> I changed one but it came with error 'Could not find com.google.firebase:firebase-messaging:16.1.0.'
> so I changed firebase version to 17.6.0, but it did not help.
> keeps showing same error.

implementation "com.google.android.gms:play-services-gcm:${safeExtGet('googlePlayServicesVersion', '16.1.0')}"
    implementation "com.google.firebase:firebase-messaging:${safeExtGet('firebaseVersion', '17.6.0')}"

**Comment by mattimck** [comment]
Yep @pram11 , as @uropsm said, it should just be `googlePlayServicesVersion` that needs to be changed from `+` to `16.1.0`. I didn't seem to need to change firebase at all, but curious how you go with it.

**Comment by pram11** [comment]
oh, I found I changed some before check this article. :)

**Comment by jakubukrop** [comment]
I had the same situation as @uropsm - just changing `googlePlayServicesVersion` wasn't enough, I also needed to change the `firebaseVersion`.

**Comment by uropsm** [comment]
I don't know the details well.
but the problem is today's release(of firebase-messaging, play-services-gcm) started supporting andoridx. Supporting androidx causes the error.

So need to fix to previous version.
com.google.firebase:firebase-messaging:17.6.0
com.google.android.gms:play-services-gcm:16.1.0

**Comment by Ethan0007** [comment]
Hi,

the problem is that when we include the implementation project(':react-native-push-notification')
in app/build.gradle , i already update the 
com.google.firebase:firebase-messaging:17.6.0
com.google.android.gms:play-services-gcm:16.1.0, but when running the app got this warning.

![Screen Shot 2019-06-18 at 4 20 01 PM](https://user-images.githubusercontent.com/12542052/59671967-cd0afb80-91e8-11e9-87f9-0975f90acea4.png)

thanks.

**Comment by uropsm** [comment]
@Ethan0007 
did you clean project after changing?
cd /yourproject/android
./gradlew clean
cd ..
react-native run-android

**Comment by Ethan0007** [comment]
@uropsm yes sir, i do clean,

by the way this is my app/build.gradle,

![Screen Shot 2019-06-18 at 5 00 23 PM](https://user-images.githubusercontent.com/12542052/59672952-abab0f00-91ea-11e9-83ba-166476453b39.png)

and build.gradle:
![Screen Shot 2019-06-18 at 5 01 43 PM](https://user-images.githubusercontent.com/12542052/59673013-c2516600-91ea-11e9-9e86-ec05766cf630.png)

is it necessary to add play-service-base and play-service-gcm?

**Comment by Ethan0007** [comment]
@uropsm but when i comment implementation project(':react-native-push-notification') my application works. but suddenly when i include it it give an same error above.

**Comment by uropsm** [comment]
@Ethan0007 
I changed node_modules/react-native-push-notification/andorid/build.gradle
not my project build.gradle

**Comment by mattimck** [comment]
> I had the same situation as @uropsm - just changing `googlePlayServicesVersion` wasn't enough, I also needed to change the `firebaseVersion`.

Quite right - apologies for bad information above. When I got home from work, discovered I also needed to fix the firebase version 👍

**Comment by Ethan0007** [comment]
@uropsm  sir, where did i put node_modules/react-native-push-notification/andorid/build.gradle ?

**Comment by duongtungls** [comment]
@uropsm in app/build.gradle
you can use this
```
dependencies {
    compile "com.google.android.gms:play-services-gcm:16.1.0"
    compile "com.google.firebase:firebase-messaging:17.6.0"
    compile (project(':react-native-push-notification')) {
        exclude group: "com.google.android.gms", module: "play-services-gcm"
        exclude group: "com.google.firebase", module: "firebase-messaging"
    }
    ...
}
```

**Comment by Ethan0007** [comment]
its working. thanks!

**Comment by virtumonde** [comment]
Getting this error after running yarn start (already used the listed fix):
`events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8081
    at Server.setupListenHandle [as _listen2] (net.js:1360:14)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1485:7)
    at Promise (/home/virtumonde/Desktop/Development/InvestmentClicker1.0 (another copy)/node_modules/metro/src/index.js:253:20)
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/virtumonde/Desktop/Development/InvestmentClicker1.0 (another copy)/node_modules/metro/src/index.js:252:14)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/virtumonde/Desktop/Development/InvestmentClicker1.0 (another copy)/node_modules/metro/src/index.js:46:24)
    at _next (/home/virtumonde/Desktop/Development/InvestmentClicker1.0 (another copy)/node_modules/metro/src/index.js:66:9)
    at <anonymous>
error Command failed with exit code 1.
`
Is someone else getting this?

**Comment by duongtungls** [comment]
@virtumonde `Error: listen EADDRINUSE :::8081`
mean some where is running dev server on port 8081. You can `terminate all terminals` to close other dev server and `yarn start` again. If still doesn't work maybe `restart computer` finally solution

**Comment by virtumonde** [comment]
> @virtumonde `Error: listen EADDRINUSE :::8081`
> mean some where is running dev server on port 8081. You can `terminate all terminals` to close other dev server and `yarn start` again. If still doesn't work maybe `restart computer` finally solution

Thanks for your help.

**Comment by frattle** [comment]
What if I don't have or use play-services or firebase? I don 't have this dependency in build.graddle. 
I am using only local notification schedule (configured in manifest) but still getting same error.
Thank you

**Comment by schumannd** [comment]
@duongtungls thanks for the immediate solution.

So I guess the problem ist with the line

```node_modules//react-native-device-info/android/build.gradle:    implementation "com.google.android.gms:play-services-gcm:$googlePlayServicesVersion"```

Another bundle react-native-device-info has solved the issue in the following way:

```implementation "com.google.android.gms:play-services-auth:${safeExtGet('googlePlayServicesAuthVersion', '16.0.1')}"```

should we use a similar solution for this project? 

Also:
How does one set the variable `$googlePlayServicesVersion`? Setting that variable would seem like a cleaner solution than the one proposed by @duongtungls

**Comment by gumballhead** [comment]
You can also add these to your `gradle.properties` so they'll get picked up by that `safeExtGet` [function](https://github.com/zo0r/react-native-push-notification/blob/master/android/build.gradle#L18).

```
googlePlayServicesVersion=16.1.0
firebaseVersion=17.6.0
```

**Comment by kssai62** [comment]
> @uropsm in `app/build.gradle`
> you can use this
> 
> ```
> dependencies {
>     compile "com.google.android.gms:play-services-gcm:16.1.0"
>     compile "com.google.firebase:firebase-messaging:17.6.0"
>     compile (project(':react-native-push-notification')) {
>         exclude group: "com.google.android.gms", module: "play-services-gcm"
>         exclude group: "com.google.firebase", module: "firebase-messaging"
>     }
>     ...
> }
> ```

Still getting same error...

**Comment by duongtungls** [comment]
> > @uropsm in `app/build.gradle`
> > you can use this
> > ```
> > dependencies {
> >     compile "com.google.android.gms:play-services-gcm:16.1.0"
> >     compile "com.google.firebase:firebase-messaging:17.6.0"
> >     compile (project(':react-native-push-notification')) {
> >         exclude group: "com.google.android.gms", module: "play-services-gcm"
> >         exclude group: "com.google.firebase", module: "firebase-messaging"
> >     }
> >     ...
> > }
> > ```
> 
> Still getting same error...

You need clean project and re-sync Gradle before build

**Comment by duongtungls** [comment]
> As a fix, you add these to your `gradle.properties` so they'll get picked up by that `safeExtGet` [function](https://github.com/zo0r/react-native-push-notification/blob/master/android/build.gradle#L18).
> 
> ```
> googlePlayServicesVersion=16.1.0
> firebaseVersion=17.6.0
> ```

I tried with this way but got this error conflict with library `react-native-camera`
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
> Could not find com.google.android.gms:play-services-vision:16.1.0.
```

**Comment by schumannd** [comment]
@gumballhead ok thanks. This has been added only 3 Months ago, so an update of the package would be needed.

**Comment by frattle** [comment]
> As a fix, you can add these to your `gradle.properties` so they'll get picked up by that `safeExtGet` [function](https://github.com/zo0r/react-native-push-notification/blob/master/android/build.gradle#L18).
> 
> ```
> googlePlayServicesVersion=16.1.0
> firebaseVersion=17.6.0
> ```

Thanks, this helped

**Comment by jsmitrah** [comment]
My team faced this issue in three different projects. Each one need a different fix and all are working fine now.
I mentioned all 3 fixes below

Solution 1:

implementation(project(":react-native-push-notification"), {
exclude group: "com.google.android.gms"
exclude group: "com.google.firebase"
})

After that the notifications stopped working here so I have to add this in my app/android/build.gradle:
ext {
googlePlayServicesVersion = "16.0.0"
firebaseVersion = "17.3.4"
}

*********************************
Solution 2:

In another case i only added this line in my build.gradle file

ext {
buildToolsVersion = '28.0.3'
minSdkVersion = 23
compileSdkVersion = 27
targetSdkVersion = 27
supportLibVersion = '27.1.1'

// this line solve my problem
googlePlayServicesVersion = '16.+'
}

***********************************
Solution 3:

Finally in app/build.gradle
you can use this

dependencies {
    compile "com.google.android.gms:play-services-gcm:16.1.0"
    compile "com.google.firebase:firebase-messaging:17.6.0"
    compile (project(':react-native-push-notification')) {
        exclude group: "com.google.android.gms", module: "play-services-gcm"
        exclude group: "com.google.firebase", module: "firebase-messaging"
    }
    ...
}

**Comment by gh7800** [comment]
project/build.gradle
......
ext {
googlePlayServicesVersion = "16.0.0"
firebaseVersion = "17.0.0"
}

react-native-device-info Also used！

**Comment by kapilgorve** [comment]
I am using both React-native-push-notifications and react-native-device-info.

implementation(project(":react-native-push-notification"), {
exclude group: "com.google.android.gms"
exclude group: "com.google.firebase"
})
implementation(project(":react-native-device-info"), {
exclude group: "com.google.android.gms"
exclude group: "com.google.firebase"
})

After that the notifications stopped working here so I have to add this in my app/android/build.gradle:
ext {
googlePlayServicesVersion = "16.0.0"
firebaseVersion = "17.3.4"
}

**Comment by ssr011** [comment]
the above comments really did fix the issue, but after applying it, I'm now unable to receive a push notification

**Comment by ThanhQuang1410** [comment]
Dose anyone has solution with this problem without replacing
`implementation project(':react-native-push-notification')`
by
`compile (project(':react-native-push-notification')) {
        exclude group: "com.google.android.gms", module: "play-services-gcm"
        exclude group: "com.google.firebase", module: "firebase-messaging"
    }`
Because I have an automatic build system, `react-native link` only give me `implementation project(':react-native-push-notification')`

**Comment by pedrosimao** [comment]
@jsmitrah thanks! Solution 1 worked for me!

**Comment by tinpt123** [comment]
> > As a fix, you add these to your `gradle.properties` so they'll get picked up by that `safeExtGet` [function](https://github.com/zo0r/react-native-push-notification/blob/master/android/build.gradle#L18).
> > ```
> > googlePlayServicesVersion=16.1.0
> > firebaseVersion=17.6.0
> > ```
> 
> I tried with this way but got this error conflict with library `react-native-camera`
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
> > Could not find com.google.android.gms:play-services-vision:16.1.0.
> ```

Same issue

**Comment by duongtungls** [comment]
> > As a fix, you add these to your `gradle.properties` so they'll get picked up by that `safeExtGet` [function](https://github.com/zo0r/react-native-push-notification/blob/master/android/build.gradle#L18).
> > ```
> > googlePlayServicesVersion=16.1.0
> > firebaseVersion=17.6.0
> > ```
> 
> I tried with this way but got this error conflict with library `react-native-camera`
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
> > Could not find com.google.android.gms:play-services-vision:16.1.0.
> ```

@tinpt123 did you try the way like my answer ?

**Comment by tinpt123** [comment]
> > > As a fix, you add these to your `gradle.properties` so they'll get picked up by that `safeExtGet` [function](https://github.com/zo0r/react-native-push-notification/blob/master/android/build.gradle#L18).
> > > ```
> > > googlePlayServicesVersion=16.1.0
> > > firebaseVersion=17.6.0
> > > ```
> > 
> > 
> > I tried with this way but got this error conflict with library `react-native-camera`
> > ```
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> > Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
> > > Could not find com.google.android.gms:play-services-vision:16.1.0.
> > ```
> 
> @tinpt123 did you try the way like my answer ?

yes, but fail :(

**Comment by xkevin190** [comment]
> > > > As a fix, you add these to your `gradle.properties` so they'll get picked up by that `safeExtGet` [function](https://github.com/zo0r/react-native-push-notification/blob/master/android/build.gradle#L18).
> > > > ```
> > > > googlePlayServicesVersion=16.1.0
> > > > firebaseVersion=17.6.0
> > > > ```
> > > 
> > > 
> > > I tried with this way but got this error conflict with library `react-native-camera`
> > > ```
> > > FAILURE: Build failed with an exception.
> > > 
> > > * What went wrong:
> > > Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
> > > > Could not find com.google.android.gms:play-services-vision:16.1.0.
> > > ```
> > 
> > 
> > @tinpt123 did you try the way like my answer ?
> 
> yes, but fail :(

add `    googlePlayServicesVisionVersion = "16.2.0"` to worked for me
