### ISSUE TITLE
I have installed react-native-firebase

### ISSUE THREAD

**Issue by fouad1994** [zo0r/react-native-push-notification#1096]
Should I remove react-native-firebase when I install this library?
if not so this library I can't setup here is my some files

`
dependencies {
    implementation project(':react-native-reanimated')
    implementation project(':react-native-gesture-handler')
    compile project(':react-native-firebase')
    compile project(':react-native-vector-icons')
    compile project(':react-native-localization')
    compile project(':react-native-fast-image')
    compile project(':react-native-restart')
    compile project(':react-native-color-matrix-image-filters')
    implementation project(':react-native-svg')
    implementation project(':react-native-linear-gradient')
    compile(project(':react-native-push-notification')) {
        exclude group: "com.google.android.gms"
    }
    implementation "com.google.android.gms:play-services-gcm:16.1.0"
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation "com.google.android.gms:play-services-base:16.0.1"
//    implementation "com.google.firebase:firebase-core:16.0.6"
    implementation "com.google.firebase:firebase-auth:16.1.0"
    implementation "com.google.firebase:firebase-messaging:17.3.4"
    implementation 'com.google.firebase:firebase-inappmessaging-display:17.0.0'
    implementation project(':react-native-community-netinfo')
    compile('com.crashlytics.sdk.android:crashlytics:2.10.1@aar') {
        transitive = true;
    }
    compile (project(':react-native-camera')) {
        exclude group: "com.google.android.gms"
    }
    implementation ("com.google.android.gms:play-services-vision:16.2.0") {
        force = true
    }
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }
}
`

`

        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
            android:value="YOUR NOTIFICATION CHANNEL NAME"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
            android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION"/>
        
        <meta-data android:name="com.dieam.reactnativepushnotification.notification_color"
            android:resource="@android:color/white"/>

        
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>
        

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>

        
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
        

        
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        

        <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />
`

`
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
new ReactNativePushNotificationPackage(),
`

include ':react-native-push-notification'
project(':react-native-push-notification').projectDir = file('../node_modules/react-native-push-notification/android')

**Comment by slavikdenis** [comment]
Im using them together for a few months and have absolutly no problem.

**Comment by bgerhards** [comment]
https://github.com/zo0r/react-native-push-notification/pull/1092 pr out to fix it.

**Comment by yash1511** [comment]
@slavikdenis 
> Im using them together for a few months and have absolutely no problem.

how to check google play services version and firebase version?
It's one of the steps in the installing rn-push-notifications
