### ISSUE TITLE
Having a helluva time with 0.28.0

### ISSUE THREAD

**Issue by GantMan** [zo0r/react-native-push-notification#110]
Getting a very odd error when including with 0.28 from 0.27.2

We're reporting everything over at ignite
https://github.com/infinitered/ignite/issues/199

**Comment by GantMan** [comment]
Someone said the issue is using `require` vs `import`, [stated here](https://github.com/facebook/react-native/issues/8449#issuecomment-228664862) 

So I did a cursory search and found
https://github.com/zo0r/react-native-push-notification/blob/master/index.js

Still es5!?

**Comment by ammichael** [comment]
I tried to manually adjust to imports, but then I started receiving this errors when trying to use .configure function.

```
iOS Simulator Logsnull is not an object (evaluating 'this.callNative('getInitialNotification').then')
iOS Simulator LogsUnhandled JS Exception: null is not an object (evaluating 'this.callNative('getInitialNotification').then')
```

**Comment by JohnyDays** [comment]
@GantMan @ammichael Did you guys figure out how to get it up and running? Been messing around with the imports to no avail.

**Comment by GantMan** [comment]
Fortunately for me, my current project doesn't require Push, so I've put it down 100% for now.   Since this is the leading PN library for RN, I'll have to revisit the concept whenever a client has this in spec again :(

Hopefully it's been solved by then. 

Additionally, we really want to provide this in Ignite!  But it's really been a bumpy road :(

**Comment by JohnyDays** [comment]
I managed to fix it in my case, it was actually my fault because I had not properly configured react-native iOS push notifications. Had to link the library and add to the build phases like they ask for in the docs

**Comment by ammichael** [comment]
I've downgraded to RN 0.25. I was having too much problems with 0.28 and dependencies..

**Comment by Naoto-Ida** [comment]
I have `0.25.1` and it was working fine, but for some reason it started giving off this error:
`(evaluating 'this.callNative('getInitialNotification').then')`, which would crash the app.
This is urgent, would be grateful if someone knew how to solve it.
I've rechecked my configurations for push notifications for the Xcode project.

**Comment by zo0r** [comment]
@Naoto-Ida since **1.0.8** (current is **1.1.2**) is only compatible with **RN 0.28+**, use **1.0.7** instead for **RN 0.25**.

Install **1.0.7**:
`npm install react-native-push-notification@1.0.7`

**Comment by Naoto-Ida** [comment]
@zo0r Thanks, that solved it. It updated to **1.0.8** when I had to delete and repopulate the `node_modules` directory when I had the caching issue.

**Comment by GantMan** [comment]
I have a command called `newclear` which helps with those pesky cache issues.

https://github.com/GantMan/mobile-commander

**Comment by npomfret** [comment]
@GantMan do you still have this issue? if so, have you tried the latest release? if not, can we close it?

**Comment by GantMan** [comment]
We shipped that product and haven't used the module since.  I'll reopen if needed.
