### ISSUE TITLE
React native push notification build error

### ISSUE THREAD

**Issue by Lishenga** [zo0r/react-native-push-notification#1101]
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:16:5-84:19 to override.

What error is this? Because am trying to build my app for release but am getting this error

**Comment by martinplouy** [comment]
@Lishenga see this issue : https://github.com/zo0r/react-native-push-notification/issues/1098

**Comment by mikehardy** [comment]
https://github.com/mikehardy/jetifier#module-maintainers

**Comment by mikehardy** [comment]
specifically item 2 from that list

**Comment by faisal3413** [comment]
I solved this issue by

https://github.com/zo0r/react-native-push-notification/issues/1109#issuecomment-506285772
