### ISSUE TITLE
onNotification never called on Android with local notifications

### ISSUE THREAD

**Issue by cosivox** [zo0r/react-native-push-notification#1104]
The handler is never called neither with the app in foreground, background or killed with localNotificationSchedule. I've tried with 3.1.2 and 3.1.1 with no success and also I have all permissions and configurations as the documentation says. I have also set android:launchMode="singleTask" to avoid app to relaunch when tapping notifications.

**Comment by AndreyPatseiko** [comment]
The same problem!
If app stay in background and I tap in push notification in tray bar, my application just opening but **onNotification** method never called. (

**Comment by cosivox** [comment]
I have already figured it out, it was because of having another activity in AndroidManifest for the SplashScreen and that Activity was receiving the notification handler. I solved it with this solution https://github.com/zo0r/react-native-push-notification/issues/122#issuecomment-247355039

**Comment by AndreyPatseiko** [comment]
Have splashScreen activity in my app.
Just added this code in my **AndroidManifest.xml** and all work fine.

    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize" android:windowSoftInputMode="adjustResize" android:exported="true" android:launchMode="singleTask" android:screenOrientation="portrait">
       <intent-filter>
           <action android:name="android.intent.action.MAIN" />
           <category android:name="android.intent.category.INFO" />
        </intent-filter>
    </activity>

 Thanks.

**Comment by kashifaliquazi** [comment]
Hi, I am facing the same Issue.
On tapping the notification received in background or foreground not calling onNotification Handler.
Its working fine when app is killed.

Initially it was working fine it stopped working after Google made changes in Firebase SDK Here are the Links
https://developers.google.com/android/guides/releases#june_17_2019

**Comment by Srijita-Basak** [comment]
> Hi, I am facing the same Issue.
> On tapping the notification received in background or foreground not calling onNotification Handler.
> Its working fine when app is killed.
> 
> Initially it was working fine it stopped working after Google made changes in Firebase SDK Here are the Links
> https://developers.google.com/android/guides/releases#june_17_2019

Hello, 
Unfortunately I am having the same issue. Is it solved? Am receiving local notifications in all scenarios but onNotification is not getting called when app is in background or foreground.  Can anyone help me with this?
