### ISSUE TITLE
The firebaseVersion variable is useless, different Firebase components have different versions

### ISSUE THREAD

**Issue by sryze** [zo0r/react-native-push-notification#1108]
For example, firebase-messaging has a version different from firebase-core and firebase-analytics. Using this variable doesn't help at all.

```
implementation "com.google.firebase:firebase-messaging:${safeExtGet('firebaseVersion', '+')}"
```

^ this code caused my build to use androidx, which itself caused other problems. I could define `firebaseVersion` in my project, but it would actually mean Firebase Messaging version. 

Maybe rename `firebaseVersion` to `firebaseMessagingVersion`?

**Comment by mikehardy** [comment]
This can be done in a backwards-compatible way even, in the style react-native-camera did https://github.com/react-native-community/react-native-camera/blob/master/android/build.gradle#L78

**Comment by Dallas62** [comment]
Hi, the variable has been renamed.
