### ISSUE TITLE
FAILURE: Build failed with an exception.  * What went wrong: Execution failed for task ':app:processDebugManifest'. > Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91         is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).         Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.

### ISSUE THREAD

**Issue by nikhil-tayal** [zo0r/react-native-push-notification#1109]

**Comment by faisal3413** [comment]
I solved this issue by changing the version of below libraries to '15.0.2', in build.gradle file of react-native-push-notification.

> com.google.android.gms:play-services-gcm

> com.google.android.gms:play-services-gcm

My  react-native-push-notification build.gradle file now looks like

`buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

apply plugin: 'com.android.library'
def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION    = "15.0.2"

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
    compileSdkVersion safeExtGet('compileSdkVersion', 28)
    buildToolsVersion safeExtGet('buildToolsVersion', '28.0.3')

    defaultConfig {
        minSdkVersion safeExtGet('minSdkVersion', 16)
        targetSdkVersion safeExtGet('targetSdkVersion', 28)
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    def googlePlayServicesVersion = rootProject.hasProperty('googlePlayServicesVersion')  ? rootProject.googlePlayServicesVersion : DEFAULT_GOOGLE_PLAY_SERVICES_VERSION

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation "com.android.support:appcompat-v7:${safeExtGet('supportLibVersion', '28.0.0')}"
    implementation "com.facebook.react:react-native:${safeExtGet('reactNativeVersion', '+')}"
    implementation "com.google.android.gms:play-services-gcm:$googlePlayServicesVersion"
    implementation 'me.leolin:ShortcutBadger:1.1.8@aar'
    implementation "com.google.firebase:firebase-messaging:$googlePlayServicesVersion"
}
`

This issue is caused by breaking changes in latest version of google libraries where androidx and support libraries cannot coexist.

Hope it will work :)

**Comment by Webbgrey** [comment]
Still doesn't work any other ideas?

**Comment by faisal3413** [comment]
@Webbgrey  try this link to understand and solve the issue

https://www.jianshu.com/p/f7a7a8765294

**Comment by Webbgrey** [comment]
@faisal3413 Still doesn't work. I tried all versions but seems like there is no hope.

**Comment by faisal3413** [comment]
@Webbgrey run below command 

`cd android && ./gradlew :app:dependencies`

and saerch and find for 'androidx'  to know which modules have been using androidx, then downgrade google libraries versions like

> com.google.android.gms:play-services-gcm

> com.google.firebase:firebase-messaging

**Comment by saadmutahar** [comment]
@faisal3413 thanks, it worked for me. :)

**Comment by Webbgrey** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.firebase:firebase-messaging:15.0.1.
     Searched in the following locations:
       - file:/C:/Users/KadakWeb-PC/.m2/repository/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.pom
       - file:/C:/Users/KadakWeb-PC/.m2/repository/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.jar
       - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.pom
       - https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.jar
       - https://jcenter.bintray.com/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.pom
       - https://jcenter.bintray.com/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.jar
       - file:/C:/Users/KadakWeb-PC/Desktop/example/firebase/node_modules/react-native/android/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.pom
       - file:/C:/Users/KadakWeb-PC/Desktop/example/firebase/node_modules/react-native/android/com/google/firebase/firebase-messaging/15.0.1/firebase-messaging-15.0.1.jar
     Required by:
         project :app > project :react-native-push-notification
```

I just getting this

**Comment by faisal3413** [comment]
@Webbgrey this is other issue, try to add 

>  implementation 'com.google.firebase:firebase-messaging:15.0.2'

in dependencies of `android/app/build.gradle` file and try to sync with android studio.

**Comment by Webbgrey** [comment]
@faisal3413 Oh my good what a problematic module

```
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.gms:play-services-gcm:15.0.2.
     Searched in the following locations:
       - file:/C:/Users/KadakWeb-PC/.m2/repository/com/google/android/gms/play-services-gcm/15.0.2/play-services-gcm-15.0.2.pom
       - file:/C:/Users/KadakWeb-PC/.m2/repository/com/google/android/gms/play-services-gcm/15.0.2/play-services-gcm-15.0.2.jar
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-gcm/15.0.2/play-services-gcm-15.0.2.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-gcm/15.0.2/play-services-gcm-15.0.2.jar
       - https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/15.0.2/play-services-gcm-15.0.2.pom
       - https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/15.0.2/play-services-gcm-15.0.2.jar
       - file:/C:/Users/KadakWeb-PC/Desktop/example/firebase/node_modules/react-native/android/com/google/android/gms/play-services-gcm/15.0.2/play-services-gcm-15.0.2.pom
       - file:/C:/Users/KadakWeb-PC/Desktop/example/firebase/node_modules/react-native/android/com/google/android/gms/play-services-gcm/15.0.2/play-services-gcm-15.0.2.jar
     Required by:
         project :app > project :react-native-push-notification
```

**Comment by engylemure** [comment]
For solving this issue i would recommend to define explicitly the version for the ext variables 
at the `android/build.gradle` at your root project

```gradle
ext {
    googlePlayServicesVersion = "16.1.0" // default: "+"
    firebaseVersion = "15.0.2" // default: "+"

    // Other settings
    compileSdkVersion = <Your compile SDK version> // default: 23
    buildToolsVersion = "<Your build tools version>" // default: "23.0.1"
    targetSdkVersion = <Your target SDK version> // default: 23
    supportLibVersion = "<Your support lib version>" // default: 23.1.1
}
```

**Comment by bhlshrf** [comment]
try this:
add these two lines into the file './android/gradle.properties':
`android.useAndroidX=true
android.enableJetifier=true`

**Comment by LeanidHreska** [comment]
@bhlshrf That's working for me, thank you.

**Comment by maulidiyah-nur** [comment]
thank you @engylemure you save my life

**Comment by capJavert** [comment]
Published forked version with hardcoded (pre androidx) packages:
[@capjavert/react-native-push-notification](https://www.npmjs.com/@capjavert/react-native-push-notification)

Solved it like this because some other packages also depend on ext param googlePlayServicesVersion and I couldn't match versions to satisfy my build.

**Comment by DanielVenturini** [comment]
@capJavert @faisal3413 it works for me.

But, i don't change the `com.facebook.react:react-native`.

Thanks

**Comment by kalraneeraj24550** [comment]
thanks @engylemure sir, your solution worked for me

**Comment by Mouzmi** [comment]
@faisal3413 Your solution works perfectly, Thank you :)

**Comment by Dror-Bar** [comment]
Very tricky.
In my case, I unlinked and uninstalled and then installed & linked again, but version 3.1.2 (that doesn't have androidX).

Then I followed @engylemure helpful advice. However, I also had a firebase-analytics version 17.0.2 that I had to lower to 15.0.2 to get it to work.

**Comment by Jeijie** [comment]
Hi,
when i changed the version of googlePlayServicesVersion and firebaseVersion , i can't build in android.
Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
> Could not find com.google.android.gms:play-services-vision:16.1.0.
  Searched in the following locations:
    - file:/Users/mac/Library/Android/sdk/extras/m2repository/com/google/android/gms/play-services-vision/16.1.0/play-services-vision-16.1.0.pom
    - file:/Users/mac/Library/Android/sdk/extras/m2repository/com/google/android/gms/play-services-vision/16.1.0/play-services-vision-16.1.0.jar

**Comment by Josema** [comment]
> Hi,
> when i changed the version of googlePlayServicesVersion and firebaseVersion , i can't build in android.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
> 
> > Could not find com.google.android.gms:play-services-vision:16.1.0.
> > Searched in the following locations:
> > - file:/Users/mac/Library/Android/sdk/extras/m2repository/com/google/android/gms/play-services-vision/16.1.0/play-services-vision-16.1.0.pom
> > - file:/Users/mac/Library/Android/sdk/extras/m2repository/com/google/android/gms/play-services-vision/16.1.0/play-services-vision-16.1.0.jar

Same problem here
