### ISSUE TITLE
React-native 0.59.4 onHandleIntent Crashing for getToken()

### ISSUE THREAD

**Issue by gSrujana26** [zo0r/react-native-push-notification#1111]
Iimplemented as per document and trying to get token where PushNotification.configure({...})
App Crashing and the line where I was seeing in Android Studio at onHandleIntent in RNPushNotificationRegisterService
`InstanceID instanceID = InstanceID.getInstance(this);`

After I replace to onNewToken() App not crashing but unable to getToken

**Comment by titoasty** [comment]
Same problem for me, still investigating..

**Comment by Natkarock** [comment]
> Iimplemented as per document and trying to get token where PushNotification.configure({...})
> App Crashing and the line where I was seeing in Android Studio at onHandleIntent in RNPushNotificationRegisterService
> `InstanceID instanceID = InstanceID.getInstance(this);`
> 
> After I replace to onNewToken() App not crashing but unable to getToken

Did you solve your problem?

**Comment by Natkarock** [comment]
> Same problem for me, still investigating..

Did you solve your problem?

**Comment by titoasty** [comment]
> > Same problem for me, still investigating..
> 
> Did you solve your problem?

No, I'm actually using amplify for remote push and react-native-push-notification.
It's... hmm... working :) on a thin line.
