### ISSUE TITLE
FAILURE: Build failed with an exception. 3error

### ISSUE THREAD

**Issue by lanjinli** [zo0r/react-native-push-notification#1114]
Task :react-native-push-notification:compileDebugJavaWithJavac 
F:\ReactNative\zhyf\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotification.java:127: 错误: 找不到符号
        promise.resolve(managerCompat.areNotificationsEnabled());
                                     ^
  符号:   方法 areNotificationsEnabled()
  位置: 类型为NotificationManagerCompat的变量 managerCompat
F:\ReactNative\zhyf\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotificationHelper.java:208: 错误: 无法将类 Builder中的构造器 Builder应用到给定类型;
            NotificationCompat.Builder notification = new NotificationCompat.Builder(context, NOTIFICATION_CHANNEL_ID)
                                                      ^
  需要: Context
  找到: Context,String
  原因: 实际参数列表和形式参数列表长度不同
F:\ReactNative\zhyf\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotificationConfig.java:53: 错误: 无法从静态上下文中引用非静态 方法 getColor(Resources,int,Resources.Theme)
            return ResourcesCompat.getColor(context.getResources(), resourceId, null);
                                  ^
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
3 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-push-notification:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by lanjinli** [comment]
C:\Users\LLJ\.gradle\caches\transforms-1\files-1.1\appcompat-v7-26.1.0.aar\606973dc300b527a2bbb41d1e04d8dff\res\values\values.xml:246:5-69: AAPT: error: resource android:attr/fontVariationSettings not found.

C:\Users\LLJ\.gradle\caches\transforms-1\files-1.1\appcompat-v7-26.1.0.aar\606973dc300b527a2bbb41d1e04d8dff\res\values\values.xml:246:5-69: AAPT: error: resource android:attr/ttcIndex not found.

error: failed linking references.

**Comment by kbrandwijk** [comment]
I am running into exactly the same error.

**Comment by lanjinli** [comment]
@kbrandwijk Have you solved your problem? I still haven't

**Comment by ChinaHDJ** [comment]
老哥问题解决没？产品已经提刀了。帮帮我

**Comment by lanjinli** [comment]
@ChinaHDJ  我的解决了，
你试试在android / build.gradle中加上这两行
ext {
   ...
   googlePlayServicesVersion = "15.0.1"   //  add 
   firebaseVersion = "15.0.2"   // add
}

**Comment by ChinaHDJ** [comment]
> @ChinaHDJ 我的解决了，
> 你试试在android / build.gradle中加上这两行
> ext {
> ...
> googlePlayServicesVersion = "15.0.1" // add
> firebaseVersion = "15.0.2" // add
> }

哇，谢谢老哥，解决了。产品放下刀了
