### ISSUE TITLE
Hey, hello, I've met the following problems：Android resource linking failed

### ISSUE THREAD

**Issue by Sun-Target** [zo0r/react-native-push-notification#1115]
Android resource linking failed
error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v26/values-v26.xml:7: error: resource android:attr/colorError not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v26/values-v26.xml:11: error: resource android:attr/colorError not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v26/values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2637: error: resource android:attr/fontStyle not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2637: error: resource android:attr/font not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2637: error: resource android:attr/fontWeight not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2637: error: resource android:attr/fontVariationSettings not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2637: error: resource android:attr/ttcIndex not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2689: error: resource android:attr/startX not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2689: error: resource android:attr/startY not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2689: error: resource android:attr/endX not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2689: error: resource android:attr/endY not found.
/Users/sunrifa/sendiWork/dr_reborn_app_react/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2690: error: resource android:attr/offset not found.
error: failed linking references.
version: 3.1.3

**Comment by lanjinli** [comment]
I am also

**Comment by lanjinli** [comment]
Task :react-native-push-notification:compileDebugJavaWithJavac FAILED
F:\ReactNative\zhyf\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotification.java:127: 错误: 找不到符号
        promise.resolve(managerCompat.areNotificationsEnabled());
                                     ^
  符号:   方法 areNotificationsEnabled()
  位置: 类型为NotificationManagerCompat的变量 managerCompat
F:\ReactNative\zhyf\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotificationHelper.java:208: 错误: 无法将类 Builder中的构造器 Builder应用到给定类型;
            NotificationCompat.Builder notification = new NotificationCompat.Builder(context, NOTIFICATION_CHANNEL_ID)
                                                      ^
  需要: Context
  找到: Context,String
  原因: 实际参数列表和形式参数列表长度不同
F:\ReactNative\zhyf\node_modules\react-native-push-notification\android\src\main\java\com\dieam\reactnativepushnotification\modules\RNPushNotificationConfig.java:53: 错误: 无法从静态上下文中引用非静态 方法 getColor(Resources,int,Resources.Theme)
            return ResourcesCompat.getColor(context.getResources(), resourceId, null);
                                  ^
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
3 个错误

**Comment by irajwani** [comment]
Hi, Any solution here. I have the exact same error as @Sun-Traget. My project builds successfully when I build it through Android Studio. I am facing this error when I run "./gradlew clean && ./gradlew assembleRelease". Then nearing the end of the process, it runs into the following error:

Execution failed for task ':react-native-push-notification:verifyReleaseResources'.

r-n-p-n: v3.0.2
react-native: v0.59.9

**Comment by irajwani** [comment]
Fixed it:

Go to build.gradle for r-n-push-notification and use:

minSdkVersion 21,
compileSdkVersion 28,
targetSdkVersion 28,

And change your appcompat libraries accordingly.
