### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'RNPushNotification.getInitialNotication')

### ISSUE THREAD

**Issue by devShayanMutahir** [zo0r/react-native-push-notification#1116]
Hello, I am having error of push-notification but don't know how to resolve as i am new to react native.

![WhatsApp Image 2019-07-03 at 12 39 10 PM](https://user-images.githubusercontent.com/24715856/60572748-abd11000-9d8f-11e9-8d79-56d7124337f3.jpeg)

**Comment by Manhazito** [comment]
I solve it by adding **popInitialNotification: false** to the configuration.

**Comment by paruckerr** [comment]
After I migrate to 0.60.4 I tried to use react native push notification for Android and have the same issue, any ideas?

**Comment by nomulavani** [comment]
any update?
I am also facing same issue.
how to resolve this?
