### ISSUE TITLE
Better documentation needed for changes in AndroidManifest.xml

### ISSUE THREAD

**Issue by EnKrypt** [zo0r/react-native-push-notification#1120]
In the README, there is a section for the changes that need to be made in `AndroidManifest.xml` if you are using GCM or `localNotificationSchedule()`.

* But which of the changes are for GCM and which of them are for `localNotificationSchedule()`? That is not clear.

* Some XML parts are wrapped in a comment as such :
```
<!-- < Only if you're using GCM or localNotificationSchedule() > -->
<some xml="property" />
...
<!-- </ Only if you're using GCM or localNotificationSchedule() > -->
```

Implying that the parts outside this block might be optional, or not required.
But that is not the case. We need the parts outside as well, as discovered by me and #1105 

* There is also an `<!-- <Else> -->` block at the bottom which is ambiguous. For what is it an `else` to?

* Proper formatting is also inconsistent in some places. Sometimes there is a space before the XML closing syntax `/>` and sometimes there is none.

This is quite trivial to fix and should be simple for the author or a maintainer to address. I'd fix it myself, but sadly I cannot read and understand the changes properly because of these issues.

**Comment by Sanan4li** [comment]
I am facing an error due to this issue, I changed my AndroidManifest.xml and Now, I am getting weird error.
It should be updated.
