### ISSUE TITLE
Not compatible with RN 0.60

### ISSUE THREAD

**Issue by chrisspankroy** [zo0r/react-native-push-notification#1125]
When starting the bundler, this message is displayed:
```
warn The following packages use deprecated "rnpm" config that will stop working from next release:
- react-native-push-notification: https://github.com/zo0r/react-native-push-notification#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.
```

It's a fairly straightforward fix, I'd be glad to contribute if I find some open time in the near future

**Comment by chrisspankroy** [comment]
Opened #1126

**Comment by AnurajDev** [comment]
How can I get the 0.60 compatible version of react-native-push-notification currently?

**Comment by lukewlms** [comment]
In case you arrive here like I did needing to upgrade this library, I posted the process that worked for me here:

https://stackoverflow.com/a/58247875/152711
