### ISSUE TITLE
Fix react-native.config.js

### ISSUE THREAD

**Issue by chrisspankroy** [zo0r/react-native-push-notification#1127]
Follow-up to #1125 and #1126 
One thing I'm not sure about is if `react-native.config.js` should be:
```javascript
module.exports = {
    project: {
      android: {
        "packageInstance": "new ReactNativePushNotificationPackage()"
      } 
    }
};
```
or 
```javascript
module.exports = {
    dependency: {
        platforms: {
            android: {
                "packageInstance": "new ReactNativePushNotificationPackage()"
            } 
        }
    }
};
```
Is there a way to test which one works?

**Comment by jeveloper** [comment]
Seems fixed in the master branch.

@zo0r  Jorge , would you please publish 3.1.4 , you have all the good stuff it, seems that you forgot :) 
thanks!

**Comment by AnurajDev** [comment]
How can I get the 0.60 compatible version of react-native-push-notification currently?
