### ISSUE TITLE
In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings

### ISSUE THREAD

**Issue by lanjinli** [zo0r/react-native-push-notification#1129]
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
:app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Failed to process resources, see aapt output above for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
157 actionable tasks: 146 executed, 11 up-to-date

"dependencies": {
    "prop-types": "^15.6.2",
    "react": "^16.3.1",
    "react-native": "^0.55.4",
    "react-native-amap-geolocation": "^0.3.2",
    "react-native-animatable": "^1.3.1",
    "react-native-autoheight-webview": "^0.6.1",
    "react-native-camera": "^1.11.2",
    "react-native-image-picker": "^0.26.10",
    "react-native-image-zoom-viewer": "^2.2.17",
    "react-native-modal-dropdown": "^0.6.2",
    "react-native-picker": "^4.3.7",
    "react-native-popup-dialog": "^0.16.6",
    "react-native-push-notification": "^3.0.2",
    "react-native-qq": "^2.0.5",
    "react-native-qrcode-svg": "^5.1.2",
    "react-native-root-toast": "^3.0.2",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-storage": "^0.2.2",
    "react-native-svg": "^9.2.4",
    "react-native-swiper": "^1.5.13",
    "react-native-wechat": "^1.9.9",
    "react-native-yunpeng-alipay": "^2.0.0",
    "react-navigation": "^2.9.3",
    "redux": "^4.0.0"
  },

compileSdkVersion 26
    buildToolsVersion "26.0.2"
    defaultConfig {
        multiDexEnabled true
        applicationId "aaa.aaa.com"
        aaptOptions.cruncherEnabled = false
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
        resValue "string", "app_name", "aaa"
    }

dependencies {
    compile project(':react-native-svg')
    compile project(':react-native-camera')
    compile project(':react-native-autoheight-webview')
    compile project(':react-native-qq')
    compile project(':react-native-push-notification')
    compile project(':react-native-wechat')
    compile project(':react-native-amap-geolocation')
    compile project(':react-native-yunpeng-alipay')
    compile project(':react-native-picker')
    compile project(':react-native-image-picker')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:+'
    // From node_modules
    compile files('libs/json.jar')
}

**Comment by QAZDER** [comment]
i fixed it by this 
```
compileSdkVersion 26
buildToolsVersion "26.0.1" 
```
https://github.com/react-native-community/lottie-react-native/issues/343#issuecomment-412251499

**Comment by lanjinli** [comment]
@QAZDER It doesn't work. It's still an error

**Comment by lanjinli** [comment]
@zo0r The author can answer the question？

**Comment by QAZDER** [comment]
how about this     
in android/build.gradle
```

ext {
   ...
   googlePlayServicesVersion = "15.0.1"   //  add 
   firebaseVersion = "15.0.2"   // add
}
```
https://github.com/react-native-community/react-native-device-info/issues/694#issuecomment-502996499

**Comment by lanjinli** [comment]
@zo0r thanks, it's finally working
