### ISSUE TITLE
Accumulative Notifications

### ISSUE THREAD

**Issue by a-sierra** [zo0r/react-native-push-notification#113]
Hi, my team is developing a chat app and we are in the need to accumulate every push notification received as a message, on the same notification box/card (whatsapp like). Is there a way to achieve this? Thanks!

**Comment by npomfret** [comment]
I don't think it's possible in iOS, but android has grouped messages which I think is what you are referring to.  They aren't supported (yet) in this project, but you aren't the first person to ask for them.  When I have time I'll try to implement it.

**Comment by kfiroo** [comment]
@npomfret I see the code does get the `group` from the bundle [here](https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L112).
Not sure it works though

**Comment by npomfret** [comment]
I don't think this API fully supports the Android group style notification fully yet.

**Comment by filipemerker** [comment]
@npomfret Hey! Have you looked this up in the past years? (: Or can you give me any hint on how to implement a good chat experience with push? Today all my push notifications are remote via Amazon and chat notifications stack upon each other by the hundreds...

**Comment by filipemerker** [comment]
@a-sierra have your team came to any solution on how to group notifications?

**Comment by filipemerker** [comment]
@Gp2mv3 Hey! Whats with the closing? Any solution yet?

**Comment by Gp2mv3** [comment]
I closed the issue because it was one of the oldest one of the repo (I closed 50 issues).
@zo0r gave me the rights to the repo because he has no more time to manage everything here.

In regard of the issue, as a user of the package for a long time now, I see grouping automatically done on Android. I don't think I did something special.
