### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by vishwambhara** [zo0r/react-native-push-notification#1130]
I found these warnings when I ran the react-native start command:

warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-push-notification: https://github.com/zo0r/react-native-push-notification#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

**Comment by kbrandwijk** [comment]
Fixed in https://github.com/zo0r/react-native-push-notification/pull/1132
