### ISSUE TITLE
I can't install this plugin in my app

### ISSUE THREAD

**Issue by cookienawer** [zo0r/react-native-push-notification#1133]
Hi,

I have been trying to install this plugin for many hours and there is no way.

First I tried a project with an expo. I did the eject, I did "yarn add react-native-push-notification" and "react-native link react-native-push-notification". There was no way. I missed the error:

`typeerror:undefined is not an object (evaluating 'RNPushNotification.getInitialNotification')`

---

Then I created a project with react-native init push, I executed these commands "yarn add react-native-push-notification" and "react-native link react-native-push-notification" and in android / build.gradle I put:
```

...
ext {
        googlePlayServicesVersion = "+" // default: "+"
        firebaseVersion = "+" // default: "+"

        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
...

```
And when I run the program I get the error:

```

> Task: react-native-push-notification: compileDebugJavaWithJavac FAILED

Deprecated Grade features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
14 actionable tasks: 2 executed, 12 up-to-date
/Users/Marta/Documents/react-native/Push/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java:11: error: can not find symbol
import android.support.v4.app.NotificationManagerCompat;

...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ': react-native-push-notification: compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

Failed error to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app: installDebug -PreactNativeDevServerPort = 8081

```
I just want to launch local notifications from the app and I'm desperate. I hope you can help me.

Pakage.jason

```
{
  "name": "Push",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint."
  },
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.0",
    "react-native-push-notification": "^ 3.1.3"
  },
  "devDependencies": {
    "@ babel / core": "^ 7.5.4",
    "@ babel / runtime": "^ 7.5.4",
    "@ react-native-community / eslint-config": "^ 0.0.5",
    "babel-jest": "^ 24.8.0",
    "eslint": "^ 6.0.1",
    "jest": "^ 24.8.0",
    "metro-react-native-babel-preset": "^ 0.55.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
react-native:
react-native-cli: 2.0.1
react-native: 0.60.0

expo:
2.21.2

node: 
v12.6.0

**Comment by LucienChu** [comment]
I kind of came into the same issue but seems I solved it.

Open your project via Android Studio, try to build it. Then migrate your project to AndroidX. PLEASE HAVE YOUR PROJECT BACKED UP BEFORE YOU DO THE MIGRATION.

Then you can run to project, it should show another error, cannot remember, it saids sth like "android.support.annotation..." does not exist.

Then change it to "androidx.annotation..." I cannot remember since it is auto completed.

Then my project is built successfully.

All these error seems to be Google have move to androidx.
I am an newbie as well, plz don't have me thumbed down.

**Comment by cookienawer** [comment]
SOLVED

The problem is with version 0.60 of react native.

I created the project with 
`react-native init push --version react-native@0.59.9 `
and it worked
