### ISSUE TITLE
Unresolved class 'GcmReceiver'

### ISSUE THREAD

**Issue by caro-li** [zo0r/react-native-push-notification#1136]
Please help me.

**Comment by huyvm** [comment]
@caro-li hello, can you show more error?

**Comment by stefoid** [comment]
GCM is being replaced by FCM and latest google play does not have GcmReciever.  the quickest way to solve this is to drop back to a google player version 16+

**Comment by elisechant** [comment]
This is also what happens to me after following Android manual installation steps. 

<img width="763" alt="Screen Shot 2020-04-17 at 6 53 35 am" src="https://user-images.githubusercontent.com/2195815/79505751-2eedf900-8078-11ea-91dc-75fcb70be604.png">

I don't know how to add the Class, also as @stefoid points out "GCM is being replaced by FCM". 

The installation steps for Android need a revision.

**Comment by Dallas62** [comment]
Hi @elisechant 
I think you can remove this one, the localNotificationSchedule should work without the GCM Receiver,
Can you try ?
Thanks.

**Comment by ugetthat** [comment]
yes it works @Dallas62
