### ISSUE TITLE
[Android] RNPushNotification#canOverrideExistingModule()

### ISSUE THREAD

**Issue by yutin1987** [zo0r/react-native-push-notification#114]
RN 0.28.0

run failed.
Native module RNPushNotification tried to override RNPushNotification for module name RNPushNotification. If this was your intention, return true from RNPushNotification#canOverrideExistingModule()

**Comment by yutin1987** [comment]
Sorry, it is my mistake

**Comment by sungwoncho** [comment]
@yutin1987 Getting the same error on RN 0.41.2 and the latest version of RNPushNotification. What was your issue?

**Comment by waterdoo** [comment]
Same here, any idea what the source of the issue is?

**Comment by GremeAllanBryce** [comment]
same
