### ISSUE TITLE
No notifications on some devices

### ISSUE THREAD

**Issue by MarianneAK** [zo0r/react-native-push-notification#1142]
Local notification works perfectly on Samsung devices but not on Huawei devices.
Any idea how to fix this?

**Comment by ridvanaltun** [comment]
Hi, this library based on [this package](https://github.com/leolin310148/ShortcutBadger) for Android. The documentation says HUWAI devices *Not Fully Support*. 

Not all Android devices suportted because generally Android based devices (Samsung, HTC etc.) came with it's own launcher.
