### ISSUE TITLE
iOS setup issues. Should revisit iOS documentation

### ISSUE THREAD

**Issue by Return-1** [zo0r/react-native-push-notification#1147]
Right now the documentation for the iOS setup prompts to follow these instructions. https://facebook.github.io/react-native/docs/pushnotificationios.html#content

However this is both deprecated in RN core and doesnt work with the new autolinker system. Documentation should be revised to point here. https://github.com/react-native-community/react-native-push-notification-ios

A thing to note about **react-native-community/react-native-push-notification-ios** (at least at this point) is simply `npm install` doesnt work at this moment as there is an issue where you need to reference the podspec explicitly in your Podfile.

https://github.com/react-native-community/react-native-push-notification-ios/issues/11

Hope this helps someone, took multiple hours and the help of a friend to figure out.

EDIT: Going with the *react-native-community* version is not an approach that will work as it yields
>Native module cannot be null
most likely due to an import incompatibility.

Its a little confusing on how to make this work with ^0.60

**Comment by LuisBonsembiante** [comment]
Hi @Return-1 ...the library work for you in ios and RN 0.59.10???...not for me... I dont know what is the problem... I enabled Push notification in profiles and XCode...but nothing work.. thanks in advance.

**Comment by LuisBonsembiante** [comment]
Ready sorry..the documentation is so bad....

**Comment by GertjanReynaert** [comment]
I was able to get it running by installing the `master` version of `@react-native-community/push-notification-ios`, and the fork of this lib that's used in this pr: https://github.com/zo0r/react-native-push-notification/pull/1139

React-native auto linking did the rest.

I know its a stop-gap solution, but I'm just dropping this here if it might unblock someone

**Comment by LuisBonsembiante** [comment]
Thanks @GertjanReynaert . Right now I try the solution... everything work find for now..but I have a problem when click con the notification in iOS... this is de stacktrace:
"Native module cannot be null"......any idea about that...I will apreciate your opinion...thnaks.

**Comment by thekrol01** [comment]
It is a wrapper around the PushNotificationIOS. If you have set up your xcode project with podfiles you can just add to your podfile: 
pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'
and do a pod install.

**Comment by LuisBonsembiante** [comment]
thanks @thekrol01 I use the PushNotificationIOS community right now so the path path => '../node_modules/react-native/Libraries/PushNotificationIOS' is different... in other way in simulation work fine but not in hide...with local notifications... but I have a big problem when I try to make a release. "iOSPushNotification.a" is not find.

**Comment by GertjanReynaert** [comment]
With the latest version of `react-native-push-notification` (3.1.8) and `@react-native-community/push-notifications-ios` (1.0.2) I was able to get things working in RN60 by just doing the npm install and using the auto loading of RN60

**Comment by kirkryan** [comment]
HI @GertjanReynaert - thanks for sharing. I can also confirm that the latest build works fine react-native-push-notification (3.1.8) and @react-native-community/push-notifications-ios (1.0.2.

The install instructions look like they have been updated, but for anyone coming from a previous release where they were using React-RCTPushNotification here are the steps:

Firstly, React-RCTPushNotification has been removed from the normal react package (just like ASyncStorage was) and now resides within the community. Therefore you will need to:

1. Remove your PodFile entry for React-RCTPushNotification (your PodFile is in the ios directory): Remove this:
`pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'`
2. Install the new push notification module into your project: `yarn add @react-native-community/push-notifications-ios `
3. Go back to ios and run`pod install`
4. Replace all entries in your AppDelegate.m for RCTPushNotificationManager with RNCPushNotificationIOS
5. Also in the AppDelegate.m - remove `#import <React/RCTPushNotificationManager.h>` and replace with `#import <RNCPushNotificationIOS.h>`
6. In xCode, clean your build directory (Product -> Clean Build Folder)
7. Build

This one caught me off guard so I hope this helps someone!

**Comment by LuisBonsembiante** [comment]
@GertjanReynaert I work with 0.59.10 RN and doesnt work..
