### ISSUE TITLE
Handling notifications when app is closed

### ISSUE THREAD

**Issue by Return-1** [zo0r/react-native-push-notification#1150]
On iOS handling notifications that launch the app is relatively straightforward to use

 ```
PushNotificationIOS.getInitialNotification().then((notification) => {
//bootstrapping logic
})
```

However, what would be the equivalent API to use in this library here? The idea is that one should be able to capture the data the notification is coming with before the app is launched ( whether it exists or not ) so that then the app can appropriately route, bootstrap etc.

From my understanding of the documentation doing this isnt clear to me yet, i would be grateful if you could point me to the right direction and i shall submit a PR on the documentation as this seems to be a very common use case.

**Comment by Return-1** [comment]
Everyone keeps suggesting to use `react-native-firebase` instead. Surely this very common case can be handled with `react-native-push-notification` though.. Anyone aware?

**Comment by Estebank94** [comment]
I am also having this problem. onNotification is not being called when the app is closed.

**Comment by sidPuttur** [comment]
@Return-1 is there any update on this issue? I am facing this issue in both IOS and Android.

**Comment by Return-1** [comment]
> @Return-1 is there any update on this issue? I am facing this issue in both IOS and Android.

I did something rather despicable that seems to work but in no way do i endorse this approach.

`DeviceEventEmitter.addListener('pushReceived'`

This will trigger on Android. For that reason im deferring the bootstrapping process for what -after testing- seems to be sufficient ( in my case 200ms ). If nothing has been received by that moment i assume no notification triggered the app to open.

This is a truly terrible solution however it seems to do the trick for now. **Again, i do not endorse this** and i will be migrating away from it as soon as i can myself.

**Comment by cesarve77** [comment]
I note that I get this on the console:
```
Daemon Canceling Activities: {(
    com.apple.pushLaunch.xxxxxx:13400A
)}
CANCELED: com.apple.pushLaunch.xxxxxxxx:13400A at priority 10 <private>!
```
May be this issue is related to this:

https://stackoverflow.com/questions/53772983/ios-silent-push-notification-cancelled
https://stackoverflow.com/questions/44796613/silent-pushes-not-delivered-to-the-app-on-ios-11

**Comment by Sbphillips19** [comment]
does this still not exist?

**Comment by plafferty64830** [comment]
I've been struggling with this concept for some time now and have just figured it out.
I knew it was possible because whatsapp/facebook can be opened from a notification and we are directed to a specific page based on the notification content.

PushNotificationIOS.getInitialNotification() works as long as it's called outside PushNotification.configure in your index.js.

To access the data passed in the notification simply use:

`PushNotificationIOS.getInitialNotification().then((notification) => {
   const yourNotificationData = notificaton._data
})`
