### ISSUE TITLE
onNotification not triggered when app mode is background

### ISSUE THREAD

**Issue by Hanf92** [zo0r/react-native-push-notification#1152]
Please help me, onNotification will never be called when app is in background mode, but it is triggered when app in foreground mode.
Can someone help me? Thanks!

**Comment by tinpt123** [comment]
> Please help me, onNotification will never be called when app is in background mode, but it is triggered when app in foreground mode.
> Can someone help me? Thanks!

please up your code, we can fix it's

**Comment by mitevdev** [comment]
This is an iOS behavior and has nothing to do with react-native-push-notification. It behaves the same if you develop natively with Objective-C or swift. 

Sent from my iPhone

**Comment by Hanf92** [comment]
> > Please help me, onNotification will never be called when app is in background mode, but it is triggered when app in foreground mode.
> > Can someone help me? Thanks!
> 
> please up your code, we can fix it's

My app entry point is 
`return (
        <Provider store={store}>
            <PushNotificationController/>
            <AppContainer ref={navigatorRef => {
                NavigationService.setTopLevelNavigator(navigatorRef);
            }}/>
        </Provider>
    );`

Component PushNotificationController is 

`export const PushNotificationController = (props: PushNotificationProps) => {

    useEffect(() => {
        configurePushNotification(onRegister,onNotif)
    },[])

    const onRegister = (token: string) => {
        console.log('token', token);
    }

    const onNotif = (notif: any) => {
        console.log('notification ',notif);
        // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
        notif.finish(PushNotificationIOS.FetchResult.NoData);
    }

    return (null)
};`

the method `configurePushNotification` is the same as the example here: https://github.com/zo0r/react-native-push-notification/blob/master/example/NotifService.js

**Comment by Hanf92** [comment]
> This is an iOS behavior and has nothing to do with react-native-push-notification. It behaves the same if you develop natively with Objective-C or swift.
> […](#)
> Sent from my iPhone
> Am 01.08.2019 um 03:56 schrieb tinpt123 ***@***.***>: Please help me, onNotification will never be called when app is in background mode, but it is triggered when app in foreground mode. Can someone help me? Thanks! please up your code, we can fix it's — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

My problem is android os

**Comment by addingama** [comment]
@Hanf92 is this problem solved? how?

**Comment by Hanf92** [comment]
> @Hanf92 is this problem solved? how?

Oh yes, need to add this function on `componentDidMount` hook `PushNotification.popInitialNotification` and the message from firebase must be `"GCM": "{ \"data\": { \"message\": \"Test, ignore this message.\", \"title\": \"SOLDO test\"} }"`

**Comment by tommypd** [comment]
popInitialNotification works when app is killed, but it's not called when app is in bacgkround

**Comment by harishAtdrive** [comment]
@tommypd - facing same issue.

**Comment by swathycsv** [comment]
@tommypd - facing same issue . onNotification not triggered when app is in background.But works when killed/foreground state
