### ISSUE TITLE
localNotificationSchedule generates multiple notifications (repost)

### ISSUE THREAD

**Issue by ghost** [zo0r/react-native-push-notification#1153]
i saw same issue, so i repost the topic, i hope everyone help me.
localNotificationSchedule generate multiple notifications when i change "background" and back "foreground".
my code:  

 componentDidMount(){
    AppState.addEventListener('change', this.handleAppStateChange);
  }

 componentWillUnmount() {
    AppState.removeEventListener('change', this.handleAppStateChange);
  }

  handleAppStateChange(appState) {
    if (appState === 'background') {
      if (Platform.OS === 'ios') { 
      let date = new Date(Date.now())
        date = date.toISOString();
      }
      FOODS.forEach(item => {
        const date = new Date(Date.now()) 
        if (date <= item.time)
          PushNotification.localNotificationSchedule({
            message: `Your notification: ${item.title}`,
            date: item.time
          });   
      });
    }

**Comment by pluvd7j** [comment]
did you got the solution?

**Comment by pluvd7j** [comment]
i did my own code with some small trick
you can set the data to one object like below code
```
for (var i = 0; i < response.data.items.length; i++) {
        if(this.state.tempDate<response.data.items[i].createdDate){
        var title = response.data.items[i].title;
        var number = response.data.items[i].number;
        var Data = { "title": title, "number": number}    //--here is the main thing

        console.log(Data.title)
        
        this.pushNotification = setupPushNotification(this._handleNotificationOpen)

        this.pushNotification.localNotificationSchedule({
        title:Data.title, // (---------here)   
        repeatType: 'day',       
        message: "ID:"+Data.number,  //(--------here)
        date: new Date(Date.now() + 1 * 1000) // in 1 secs

      })
}
}
```

in the above code (Data.title) i'll send 5 title data to the notification title as same as message (Data.number)
in that u can set your data in object{} and call it in Notification title and it will automatically generate multiple title
