### ISSUE TITLE
Android localNotificationSchedule wrong date

### ISSUE THREAD

**Issue by Ilario17** [zo0r/react-native-push-notification#1154]
```
const date = new Date(Date.now() + (25 * 1000))

console.log(`date test: ${date}`);

PushNotification.localNotificationSchedule({
	id: '333',
	title: 'Hey',
	message: 'this is a msg!',
	priority: "max",
	autoCancel: false,
	soundName: 'popcorn.mp3',
	vibration: 30000,
	date
});
```
```
"react-native": "0.58.4",
"react-native-push-notification": "^3.1.2",
Android 5.1
```

date is completely ignored and the notification arrives in a random time that can even reach 5 minutes instead of the 25 seconds provided.

am I doing something wrong? how can i solve it?

Thanks

**Comment by adrianchancy** [comment]
I don't know much about the details, but you may try 
1) checking the timezone of the testing device or emulator
2) use PushNotification.cancelAllLocalNotifications() OR PushNotification.cancelLocalNotifications() before setting up the new ones.

**Comment by infiniteline** [comment]
I was having this issue as well. I would manually trigger a scheduled notification for 1 second in the future and it would go off hours later. I'm not convinced I'm not still having some time issues, but the console was reporting that my emulator was out of sync and I think it may be resolved by running the following. (Note: you have to have Android Platform Tools installed)

`
adb shell date -s `date +%G%m%d.%H%M%S`
`

**Comment by uhmin99** [comment]
issue is still happening in android
if you use Date to set 'date' option in localNotificationSchedule, ios works fine but android doesn't show notifications in right time

**Comment by uhmin99** [comment]
I got it solved by deleting all scheduled notification before adding new ones with same ids

`PushNotification.cancelAllLocalNotifications()`
