### ISSUE TITLE
unable to get notification if app  closed

### ISSUE THREAD

**Issue by satishkumarkt** [zo0r/react-native-push-notification#116]
Hi
I am send message to GCM using nodejs node-android module, my message is successfully send to GCM server but notification is not displayed in receiver device 
for ${applicationId} i am replacing my GCM package(com.test)
if app is in open state i am able to get notifications.

**Comment by mvnpgh** [comment]
+1

**Comment by shaikhussian** [comment]
+1

**Comment by shaikhussian** [comment]
is any one got solution for this, In android when app is in close any one receive notification

**Comment by satishkumarkt** [comment]
I had to add some stuff to my android app after reading #84 

```
To app/build.gradle:

apply plugin: 'com.google.gms.google-services'
...
compile "com.google.android.gms:play-services-gcm:8.3.0"

To android/build.gradle:
classpath 'com.google.gms:google-services:2.0.0-alpha6'

To manifest.xml:

    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
...
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

```
and add goggle cloud messaging  to android sdk manager(required)


After doing this I get notification when app is in close state

Hope it works the same for you.

**Comment by shaikhussian** [comment]
sorry to reply like this, when i tried your solution when app is in closed
state notification is not showing
below i am attaching the screen shot of my issue
here i didn't installed Google cloud messaging for Android library
installed only google play services,
Why because i din't find Google cloud messaging for Android library in my
android sdk

On Mon, Jul 11, 2016 at 1:11 PM, satish <notifications@github.com> wrote:

> Closed #116
> <https://github.com/zo0r/react-native-push-notification/issues/116>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/zo0r/react-native-push-notification/issues/116#event-718349923>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALZwVHTxtehnEvhpzWCxb8x926vL7xUkks5qUfPDgaJpZM4JBFgA>
> .
>



-- 
     Thanking You,
Regards:
Hussian Shaik,
(Stellent Soft.Pvt.Ltd)

**Comment by satishkumarkt** [comment]
please select obsolete option in android SDK manager(shown above) it shows  Google cloud messaging
install and try once

**Comment by juanpasolano** [comment]
@satishkumarkt: the `<meta-data...` part in the manifest you mentioned [up here](https://github.com/zo0r/react-native-push-notification/issues/116#issuecomment-232029098) is contained inside what tag?
