### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by cristianoccazinsp** [zo0r/react-native-push-notification#1162]
Changelog from 3.1.3 to 3.1.8?

**Comment by jeveloper** [comment]
This project is dead and Zo0r is not willing to introduce other maintainers

**Comment by tehOPEologist** [comment]
commits to master 10 days ago shows this repo isn't dead, unless you can link where @zo0r stated that.  i see version 3.1.9 in npm registry, so i'm guessing the readme/changelog just hasn't been updated/merged into master yet.  @zo0r can you chime in on this please?  thank you!
