### ISSUE TITLE
In ios not fire nitification if the app is open

### ISSUE THREAD

**Issue by cookienawer** [zo0r/react-native-push-notification#1163]
When I have the application open in ios notifications do not appear. In the xcode debug they do appear but the user of the app does not even notice.
Is there any way to force them to appear in the notification menu even if the app is open?

**Comment by melvinchng** [comment]
Yes, follow the instruction [here](https://facebook.github.io/react-native/docs/pushnotificationios) on setting up your `AppDelegate.m`.
