### ISSUE TITLE
Error while requiring react-native-push-notification package

### ISSUE THREAD

**Issue by khuang-citylift** [zo0r/react-native-push-notification#1165]
####Hi All,

**To install the package, I ran:**
npm install --save react-native-push-notification
react-native link react-native-push-notification

**In my .js file, which is my node server, I have:**
var PushNotification = require("react-native-push-notification"); // this line causes the error

**Here is the error:**
.../node_modules/react-native-push-notification/index.js:32
Notifications.callNative = function(name: String, params: Array) {
                                        ^

SyntaxError: Unexpected token :
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

Note: I saw two other issues with this same error but neither of them have a  #solution. #605 and #1112 

Thanks in advance for any help.

**Comment by nolanrbrady** [comment]
If you haven't already I would go through and make sure that the `react-native link` command properly linked the native package. Especially on iOS I've found it to be a bit hit or miss. As for the import using `import PushNotification, { PushNotification as IPushNotification, PushNotificationPermissions } from 'react-native-push-notification';` has been working very well for us.

**Comment by khuang-citylift** [comment]
I'm assuming I would need a .gradle for Android and an xcodeproj for iOS for this to work then? I am using Expo as my package manager so my binaries are automatically built by them. I don't have actual Android nor iOS projects, and according to the Expo documentation I should never have to manually modify these files.

**Comment by nolanrbrady** [comment]
Right, if you're using Expo without having ejected you won't be able to run this package since it requires access to the native code. A good solution for you may be using the Expo push notification API [here](https://docs.expo.io/versions/latest/guides/push-notifications/) or ejecting from Expo into ExpoKit so you can link native packages.

**Comment by khuang-citylift** [comment]
Awesome, thanks for the help Nolan. I'll look into both of those solutions. Going to close this issue.
