### ISSUE TITLE
[Potentially compromised] Fishy reference to other project

### ISSUE THREAD

**Issue by Jakst** [zo0r/react-native-push-notification#1169]
I noticed that there is a reference to another project called `january.ai/januarychallenge` in the Android project `external.root.project.path="$MODULE_DIR$/../../january.ai/januarychallenge/android"`.

It was introduced in #1095 and seems really fishy. Could this have malicious intent?

https://github.com/zo0r/react-native-push-notification/blob/a0532680280712238700a63ccca622d544a9afc0/android/react-native-push-notification.iml#L2

**Comment by jimbol** [comment]
Saw this too. Very odd

**Comment by Li357** [comment]
`*.iml` should have been [`.gitignore`](https://github.com/zo0r/react-native-push-notification/blob/master/.gitignore#L30)d. I couldn't find any trace of `january.ai`/`januarychallenge` in the project either.

**Comment by martwetzels** [comment]
Same here. Although I cannot find the reference in the iml-file as mentioned by @Jakst, gradle sync does fail on it.

**Comment by cayasso** [comment]
Can the `january.ai` fishy line be remove please? build is failing by this line!

**Comment by rgordon95** [comment]
I also have experienced this

**Comment by bdbch** [comment]
Same problem here, had this twice already. Why is this even included in the repository?

**Comment by bdbch** [comment]
Seems like it was added when androidx support was added:

https://github.com/zo0r/react-native-push-notification/commit/6a1c4af151b94533a062da42f5f1ed6c5a7d9d49#diff-478b0d9161e5da27ae7ca17405f561d5R2

**Comment by iamrenejr** [comment]
Also having my build failing due to this.

**Comment by phyzical** [comment]
Can confirm pr removes issue

**Comment by mcaubrey** [comment]
This is also causin gmy build to fail.

**Comment by rdewolff** [comment]
What's the status of this issue ?

**Comment by Dallas62** [comment]
Issue is resolved.
