### ISSUE TITLE
Hide notification in foreground

### ISSUE THREAD

**Issue by srednicki95** [zo0r/react-native-push-notification#1172]
Is it possible to hide the notification when app is in foreground?
Or show only when app is in backgroud or killed.

**Comment by mitevdev** [comment]
in iOS the received notification does not pop up when the App is in foreground, this is done by the OS only when it is in background. If you want to display the notification while he app is running (bad practice) you should do it by yourself. 

Sent from my iPhone

**Comment by srednicki95** [comment]
@mitevdev It's automatically popup notification when its get `message` in notification data. I only tested in Android

**Comment by srednicki95** [comment]
I saw in commit: https://github.com/zo0r/react-native-push-notification/commit/a913f84b1d87328e2c445a88d013e74a440378cb?diff=split#diff-ccbd69b1c5564f1a9e6eae125989a510L110
That `inForeground` flag is now ignored.
Its the only way to handle this is fork?

**Comment by xxRockOnxx** [comment]
too bad we have to fork it. it seems like this project is dead now 🙁

**Comment by lisichka999** [comment]
Hi @srednicki95 , may be you found the solution for prevent android notification to pop when app in foreground? Thanks you)

**Comment by srednicki95** [comment]
@lisichka999 Im now using `react-native-firebase` instead of that. But if you need you can use my forked version of this library.

**Comment by lisichka999** [comment]
@srednicki95 Thank you, I found the solution in another post. We also use firebase, but because they does not support remote notifications in v6 we want to give a try to this library.

**Comment by hiren2728** [comment]
> @srednicki95 Thank you, I found the solution in another post. We also use firebase, but because they does not support remote notifications in v6 we want to give a try to this library.

Can you please share the solution for the same. I am also looking for hiding the notification on android when app is in the foreground.

**Comment by emmbyiringiro** [comment]
The easy solution is to use React Native AppState package  to detect if app is background or foreground then push notification.

**Comment by lisichka999** [comment]
@emmbyiringiro please seethis PR https://github.com/zo0r/react-native-push-notification/pull/1183?email_source=notifications&email_token=AKRMYPCHQEJ3PXR7UGKVLQTQ7XASHA5CNFSM4IRRJWCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJ5Y6BY#issuecomment-578522887

**Comment by RediaUa** [comment]
> Hi @srednicki95 , may be you found the solution for prevent android notification to pop when app in foreground? Thanks you)

you can send silent notification and display local notification conditionally on the receiver side (it works on Android), but I don't know how it works on IOS

**Comment by Dallas62** [comment]
Hi, there is now an option in AndroidManifest to allow/disable foreground notifications.

**Comment by ocsby** [comment]
@Dallas62 Can you give more detail on what option in AndroidManifest can disable foreground notifications?  I tried looking at the documentation but did not find anything.  Thanks.

**Comment by Dallas62** [comment]
Please read the readme AndroidManifest in the "Android Manual Installation".
Regards

**Comment by classiebit** [comment]
This is working for us-

**Android**

`<meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground" android:value="false"/>`

**iOS**


    // Called when a notification is delivered to a foreground app.
    -(void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
    {
        completionHandler(UNNotificationPresentationOptionNone);
    }


In this way, when the app is in the foreground, no notification shown while in the background, notification is showing. Hence, this solution is working for us.
