### ISSUE TITLE
AndroidManifest com.google.firebase.MESSAGING_EVENT intent filter clarification

### ISSUE THREAD

**Issue by bengtan** [zo0r/react-native-push-notification#1175]
Hi,

I have a question regarding the `com.google.firebase.MESSAGING_EVENT` intent filter please. Our app uses both RNFirebase and react-native-push-notification.

According to [RNFirebase documentation](https://github.com/invertase/react-native-firebase-docs/blob/master/docs/messaging/android.md#update-android-manifest), this needs to be in AndroidManifest.xml:

```
<application ...>

  <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
    <intent-filter>
      <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
  </service>

</application>
```

According to your documentation, this needs to be in AndroidManifest.xml:

```
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

My question is ... Is it okay to have two services (`io.invertase.firebase.messaging.RNFirebaseMessagingService` and `com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService`) with the same intent-filter `com.google.firebase.MESSAGING_EVENT`?

If not, then how should AndroidManifest.xml be configured if we want to use both RNFirebase and react-native-push-notification?

**Comment by alex-mironov** [comment]
@bengtan did you manage to solve this? :)

**Comment by bengtan** [comment]
Hi,

It turned out to be a non-issue. The problem I was working on was caused by something else (but I forget what it is, now).

Thanks for the follow-up.
