### ISSUE TITLE
Unable to resolve module `@react-native-community/push-notification-ios` from `~/Code/React/MYS_Copy/node_modules/react-native-push-notification/component/index.ios.js`

### ISSUE THREAD

**Issue by tholhubner** [zo0r/react-native-push-notification#1176]
I am in the middle of upgrading our project to 0.60.5 and I am now running into this issue: 
```
Unable to resolve module `@react-native-community/push-notification-ios` from `/Users/tholhubner/Code/React/MYS_Copy/node_modules/react-native-push-notification/component/index.ios.js`
```
I have the dependency installed and I am completely up to date on this package as well, but I still seem to be getting this error. I have done all the typical steps, clearing watchman, removing node_modules, clearing npm caches, but nothing seems to solve this issue. 

If anyone has any suggestions, please send them my way.

**Comment by quynhnvicts** [comment]
Have you solved this issue? I am now running into this issue too.

**Comment by nhiicts** [comment]
I found the solution, you can try to delete 
```
  resolver: {
    blacklistRE: blacklist([
      // Refs: https://github.com/facebook/metro/issues/265
      /ios\/.*/,
      /android\/.*/,
      /__tests?__\/.*/,
      /__mocks?__\/.*/,
    ]),
}
```
in metro.config.js

**Comment by alvaro1728** [comment]
@nhiicts I removed that whole "resolver" section but it didn't help.

**Comment by 13thdeus** [comment]
Any update on this issue?

**Comment by davidvmckay** [comment]
> @nhiicts I removed that whole "resolver" section but it didn't help.

in my case, when I deleted the "resolver" section my app still refused to load.... but it was because I needed some of the blacklist entries for proper bundling.  this is what i ended up with that allowed the react-native-community/push-notification-ios package to be resolved by metro:

```javascript
// https://github.com/janeasystems/nodejs-mobile-react-native/tree/ed727edea17e8a9e1a85cef3413becc83b8a0328#duplicate-module-name
// https://github.com/facebook/metro/issues/265#issuecomment-424334996
const blacklist = require('metro-config/src/defaults/blacklist');

module.exports = {
  resolver:{
    blacklistRE: blacklist([
      // /node_modules\/.*\/node_modules\/react-native\/.*/,
      /nodejs-assets\/.*/,
      /CodePush\/.*/,
      /android\/.*/,
      // /ios\/.*/
    ])
  },
};

```

**Comment by betopompolo** [comment]
I'm running into this issue too. Trying to upgrade from version 3.1.9 to 6.1.1.

Any updates on this issue?

**Comment by betopompolo** [comment]
@tholhubner i was running into the same issue, but this lib uses the @react-native-community/push-notification-ios (as stated in [installation instructions](https://github.com/zo0r/react-native-push-notification#yarn)). 

I think this issue can be closed.
