### ISSUE TITLE
Scheduled local notifications are lost after reboot on Android

### ISSUE THREAD

**Issue by varungupta85** [zo0r/react-native-push-notification#118]
I think it is mentioned in the TODOs in the README that it is not supported at the moment. `PushNotificationIOS` supports it out of the box in iOS. So, I am assuming it will be supported for iOS using this package also. If you have some idea about how to support it in Android, can you some information here. I would like to add that feature and send a PR if someone can point me towards the right direction. Right now, I don't know what needs to be done in order to support this for Android. Thanks!

**Comment by varungupta85** [comment]
After checking out the code for `react-native-system-notifications` package, I was able to figure out that I need to add a `BroadcaseReceiver` to intercept the "boot" event and store the notifications in the `SharedPreferences` so that they persist between reboots and reload them when a "boot" event is received.

**Comment by andy9775** [comment]
Correct. This uses `alarmManager` which as you can see [here](https://developer.android.com/reference/android/app/AlarmManager.html) forgets alarms on reboot.

**Comment by npomfret** [comment]
This is addressed in master now, but not released yet.  Would you be able to help test before we push the release out?
