### ISSUE TITLE
This project is not maintained anymore?

### ISSUE THREAD

**Issue by GleidsonDaniel** [zo0r/react-native-push-notification#1189]
Look these pull request from 2018:
#636

Why was he ignored? 
I currently use the same in my application, but the surprising thing is why it was ignored at all this time.

**Comment by EJohnF** [comment]
Yea, 500+ open issues are another good indicator of almost no maintained.

**Comment by atulmy** [comment]
Considering the popularity and wide adoption, this project should be migrated to https://github.com/react-native-community

**Comment by giacomocerquone** [comment]
@atulmy I absolutely agree something official should be done for android too and in general these kind of packages should be checked by core members

**Comment by Linoa65** [comment]
Hello !

I'm totally agree, maybe creator needs to get helped by more contributors, or give the lead to someone wants to maintain this. Many features really useful still waitings to be merged since month or years, and more activity on this package is really needed.
I can help if it's necessary, just ask me and I can check/resolve conflicts at least on pull request to make this package go forward ^^

**Comment by atulmy** [comment]
@kelset, wanted your attention on this package.

**Comment by kelset** [comment]
I already tried a long time ago: https://github.com/zo0r/react-native-push-notification/issues/575

**Comment by giacomocerquone** [comment]
Ahahahahaha this is awesome guys!
Anyway I switched to firebase, way better.
Also wix native notification is not bad, I'd leave this package where it is and focus on the others that already have guidance and if in the future there will be a need for maintain those packages, I'd push there for let them become a react native community thing

**Comment by Dallas62** [comment]
Hi
I'm a new maintainer of the projet, I would be pleased to look at all suggestions, PR and issues.
PR are welcome 😉 
Regards,

**Comment by giacomocerquone** [comment]
This is a really great news! Thanks, I'll try to do something when possible
