### ISSUE TITLE
Not getting push notification permission alert in android (0.59.8)

### ISSUE THREAD

**Issue by srichallamalla935** [zo0r/react-native-push-notification#1196]
Followed the integration procedure in react-native-push-notification module
Getting device type  and device token but not arising permission alert in android

Versions
react-native:0.59.8
react-native-push-notification:3.1.9

##Code
```
  componentWillMount(){
      PushNotification.configure({
        // (optional) Called when Token is generated (iOS and Android)

        onRegister(token) {
          alert(`TOKEN@@@@: ${JSON.stringify(token)}`);
          deviceType = token.os;
          deviceToken = token.token;
        },

        // (required) Called when a remote or local notification is opened or received
        onNotification(notification) {
          console.log("NOTIFICATION:", notification);

          // process the notification

          // required on iOS only (see fetchCompletionHandler docs: 
       https://facebook.github.io/react-native/docs/pushnotificationios.html)
          notification.finish(PushNotificationIOS.FetchResult.NoData);
        },

        // ANDROID ONLY: GCM or FCM Sender ID (product_number) (optional - not required for 
        local notifications, but is need to receive remote push notifications)
        senderID: "301058192164",

        // IOS ONLY (optional): default: all - Permissions to register.
        permissions: {
          alert: true,
          badge: true,
          sound: true
        },

        // Should the initial notification be popped automatically
        // default: true
        popInitialNotification: true,

        /**
         * (optional) default: true
         * - Specified if permissions (ios) and token (android and ios) will requested or not,
         * - if not, you must call PushNotificationsHandler.requestPermissions() later
         */
        requestPermissions: true
      });
    }
```

**Comment by salazara** [comment]
Is there a solution for this yet?

**Comment by salazara** [comment]
I was able to solve this by updating to 3.1.9.

Just be wary that you may encounter this issue https://github.com/zo0r/react-native-push-notification/issues/1169. It will require you to simply delete "react-native-push-notification/android/react-native-push-notification.iml"

**Comment by srichallamalla935** [comment]
@salazara Are you getting alert in android . I am stilling not getting the alert in android
I m using  react-native-push-notification": "^3.1.9" version still no use even i have deleted the 
"react-native-push-notification.iml" file

**Comment by salazara** [comment]
@srichallamalla935 In that case, I would double check your AndroidManifest.xml.

See Android Manual Installation in https://github.com/zo0r/react-native-push-notification
and See https://github.com/zo0r/react-native-push-notification/issues/1156#issuecomment-519563243
