### ISSUE TITLE
Not able to add Large icon

### ISSUE THREAD

**Issue by urfusion** [zo0r/react-native-push-notification#1197]
I am a newbie in react native and mobile development.

I am trying to implement the notification which working fine only facing one issue that when I want to show icon only with data it will show as an image.

For example, I want to show like this but it shows large image too on click of an arrow button.

![image](https://user-images.githubusercontent.com/8436372/64703876-e1e6ea80-d4ca-11e9-81e9-e6a659891034.png)
![image](https://user-images.githubusercontent.com/8436372/64703888-ead7bc00-d4ca-11e9-91e4-761e970d712b.png)

Right now it is like this

![image](https://user-images.githubusercontent.com/8436372/64704451-f4adef00-d4cb-11e9-820d-25fa0a7313c2.png)

That is how I want.

![image](https://user-images.githubusercontent.com/8436372/64704491-07c0bf00-d4cc-11e9-932b-7345b0c78ba3.png)

Here is my AndroidManifest.xml

 
        <meta-data   android:name="com.google.firebase.messaging.default_notification_icon"
                    android:resource="@mipmap/ic_notification"/>  
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@android:color/white"/>

While on server side

> $notification = array('content-available' => true, 'mutable-content' => true, 'title' => $title, 'text' => $body, 'icon' => $icon, 'sound' => 'default', 'badge' => '1');

If I pass icon then nothing will show if I use image then icon show but with the big image too.

My code is as below

```
import PushNotification from 'react-native-push-notification';
import { PushNotificationIOS } from 'react-native';
import { NavigationActions, StackActions } from "react-navigation";


const localNotification = data => {
  console.log("const localNotification"+JSON.stringify(data))
  if (data) PushNotification.localNotification(data);
  return null;
};
let getToken;

const setToken = token => (getToken = token.token);

const configure = () => {
  PushNotification.configure({
    onRegister: setToken,
    smallIcon: "ic_notification",
    ongoing: true,
    onNotification: function(notification) {
      if (notification.foreground) {
        //alert("if");
        localNotification(notification);
      }else{

      }

      console.log("PushNotificationIOS"+ JSON.stringify(PushNotificationIOS))
      //alert("notification"+ JSON.stringify(notification))
      StackActions.reset({
        index: 0,
        key: null,
        actions: [NavigationActions.navigate({ routeName: "news" })]
      });
      this.props.navigation.navigate("news");

      // process the notification
      // required on iOS only
      notification.finish(PushNotificationIOS.FetchResult.NoData);
    },
    senderID: 'sender_id', //Have actual number
    permissions: {
      alert: true,
      badge: true,
      sound: true
    },

    popInitialNotification: true,
    requestPermissions: true
  });
};


export { configure, localNotification, getToken };
```

**Comment by TaraSinghDanu** [comment]
I am also not able to add large icon on android when app is in background state
