### ISSUE TITLE
 MainApplication.java       How add required lines to 0.60?

### ISSUE THREAD

**Issue by yalcinozer** [zo0r/react-native-push-notification#1198]
Do i have to downgrade to older versions or is there a way to link on 0.60? There is a different add method in 0.60 like below 

**packages.add()** 

I dont know how to add lines to link package. This issue is not special for this package but I need tihs packages so write on this repo. Thanks. :-)

**Comment by ralph-dev** [comment]
You shouldn't need to use that package command for 0.60+ react-native versions as it auto links. 
https://react-native-community.github.io/upgrade-helper/
Take a look at this ^
