### ISSUE TITLE
iOS13 push notifications not delivered without apns-push-type header set

### ISSUE THREAD

**Issue by matthova** [zo0r/react-native-push-notification#1199]
This not actually an issue, but a placeholder to make sure you don't file an issue related to iOS13 until *after* you've read the following: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns?language=objc

Specifically inside of the documentation on header-fields:
`
apns-push-type: (Required when delivering notifications to devices running iOS 13 and later, or watchOS 6 and later. Ignored on earlier system versions.) The type of the notification. The value of this header is alert or background. Specify alert when the delivery of your notification displays an alert, plays a sound, or badges your app's icon. Specify background for silent notifications that do not interact with the user. The value of this header must accurately reflect the contents of your notification's payload. If there is a mismatch, or if the header is missing on required systems, APNs may delay the delivery of the notification or drop it altogether. For information about configuring notification alerts, see Generating a Remote Notification. For more information about sending background notifications, see Pushing Background Updates to Your App.
`

**Comment by matthova** [comment]
More helpful info here: https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/

**Comment by HanliTheron** [comment]
Thanks a lot, do you know if this package will be updated to include the fix by default?

**Comment by matthova** [comment]
There's a lot of writing up here ^ but to clarify, any issue caused by iOS13 header-types is outside of the scope of this package. No update to this package is necessary.

**Comment by HanliTheron** [comment]
Thanks Matt, it seems it is the @react-native-community/push-notification-ios that needs updating.
