### ISSUE TITLE
app getting Crashes while receiving notification in android?

### ISSUE THREAD

**Issue by shaikhussian** [zo0r/react-native-push-notification#120]
Hai  while I am using this module, i got the notifications correctly in IOS,But in android app getting crash,please give me suggestions that how to resolve it

**Comment by shaikhussian** [comment]
please respond

**Comment by alexeypodolian** [comment]
@shaikhussian can you show error stacktrace? It'll help a lot with solving the issue.

**Comment by shaikhussian** [comment]
below is the crash report which i got 
![screen shot 2016-07-01 at 4 36 50 pm](https://cloud.githubusercontent.com/assets/11956308/16519957/43794568-3faa-11e6-88e3-ac30f144ecb6.png)

**Comment by alexeypodolian** [comment]
Update your `AndroidManifest.xml` according to Android installation manual. 

Check your permissions in `AndroidManifest.xml`, it should be something like this:

```
   <uses-permission android:name="android.permission.WAKE_LOCK" />
    <permission
        android:name="${applicationId}.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
```

**Comment by shaikhussian** [comment]
@alexeypodolian thank you for your response, i am getting notification, but when my app is in close state i didn't get any notification,please give me suggestions that how to resolve it

**Comment by alexeypodolian** [comment]
I don't know for sure why this happens, it needs time for debugging. I guess, there is a problem in Android module in this lib.

**Comment by shaikhussian** [comment]
Is there any solution in android issue for notification, When app is in close

**Comment by npomfret** [comment]
It should work when the app is in the background, but not when the app is closed.
