### ISSUE TITLE
how do i send notification to particular user by using react-native-push-notification ?

### ISSUE THREAD

**Issue by ParthSolanki7** [zo0r/react-native-push-notification#1200]

**Comment by usmansbk** [comment]
You can use Firebase, One-signal, AWS-amplify etc there are many options to choose from. This library is just a helper to receive the notifications.

**Comment by HarshitMadhav** [comment]
@ParthSolanki7  You can extract the device token of a particular device and then you can send the firebase push notification to that particular device using the device id.
