### ISSUE TITLE
auto linking for android is not working in 0.60

### ISSUE THREAD

**Issue by naveenthukkani** [zo0r/react-native-push-notification#1202]
Error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-push-notification (to unlink run: "react-native unlink react-native-push-notification")

if did also react-native unlink react-native-push-notification it is not working .. it is giving me same error

**Comment by r0b0t3d** [comment]
Please manual check below files then remove everything related to `react-native-push-notification`
1. `android>settings.gradle`
2. `android>app>build.gradle`

**Comment by Dallas62** [comment]
Hi @naveenthukkani 
Did you try with the latest version ?
Thanks

**Comment by Supun00SL** [comment]
@r0b0t3d I tried your solution, but it doesn't work for me. I removed everything and reinstalled the module. but it happens again.
