### ISSUE TITLE
Not receiving notification in android emulator

### ISSUE THREAD

**Issue by suresh777** [zo0r/react-native-push-notification#1203]
I added this plugin to my react native project. I am able to receive device token but if i send a message from fcm console i am not able to receive. I added playservices and google account in emulator

 componentDidMount(): void {
        console.log('Did mount')

        PushNotification.configure({
            // (optional) Called when Token is generated (iOS and Android)
            onRegister: function(token) {
                console.log("TOKEN:", token);
            },

            // (required) Called when a remote or local notification is opened or received
            onNotification: function(notification) {
                console.log("NOTIFICATION:", notification);

                // process the notification

                // required on iOS only (see fetchCompletionHandler docs: https://github.com/react-native-community/react-native-push-notification-ios)
                notification.finish(PushNotificationIOS.FetchResult.NoData);
            },

            // ANDROID ONLY: GCM or FCM Sender ID (product_number) (optional - not required for local notifications, but is need to receive remote push notifications)
            senderID: "447885574876",

            // IOS ONLY (optional): default: all - Permissions to register.
            permissions: {
                alert: true,
                badge: true,
                sound: true
            },

            // Should the initial notification be popped automatically
            // default: true
            popInitialNotification: true,

            /**
             * (optional) default: true
             * - Specified if permissions (ios) and token (android and ios) will requested or not,
             * - if not, you must call PushNotificationsHandler.requestPermissions() later
             */
            requestPermissions: true
        });

    }

manifest file:
 <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
                    android:value="Notification"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                    android:value="Notification Description"/>
        
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@android:color/white"/>

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>

        <service
                android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
                android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

**Comment by IonutRealDevs** [comment]
Have you added this on `/android/build.gradle`?
```
buildscript {
ext {
        googlePlayServicesVersion = "16.1.0" <- this
        firebaseVersion = "17.3.4" <- and this
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
   }
....
}
```

**Comment by suresh777** [comment]
I added all this stuff still i am not able to receive push notification in android emulator. But i am getting token. I am not getting any logs regarding push notification. It is not calling onNotification callback

**Comment by huyvm** [comment]
Hi @suresh777 maybe error from >= android 8, you can add channel to android package

**Comment by suresh777** [comment]
Where should i add channel code

**Comment by huyvm** [comment]
what's version that you use?

**Comment by suresh777** [comment]
android oreo,

 implementation 'com.google.firebase:firebase-core:17.2.0'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'

**Comment by IgorMitev** [comment]
@suresh777 please see:

<img width="1324" alt="channel" src="https://user-images.githubusercontent.com/21057931/65965466-f6c9f480-e45e-11e9-9a16-44b18070a9af.png">

**Comment by suresh777** [comment]
I have already added this part, I am asking that in MainActivity should i add notification channel code
