### ISSUE TITLE
I don't receive device token on iOS

### ISSUE THREAD

**Issue by IonutRealDevs** [zo0r/react-native-push-notification#1204]
Hello.
I have a problem on iOS, i don't receive device token and i don't know what i am doing wrong.
On Android all is working but on iOS don't. When i open the app on iOS device i get that prompt message if i want to allow to receive notifications.

I followed the tutorial from [here](https://github.com/react-native-community/react-native-push-notification-ios), but i used react-native link instead manual linking. What am i missing?

**Comment by huyvm** [comment]
Hi @IonutRealDevs Are you run in iOS with simulator or real device?

**Comment by IonutRealDevs** [comment]
Real device connected to mac, i know that on simulator is not working.

**Comment by huyvm** [comment]
@IonutRealDevs Hello, you can give your code in here, Notification implement only.

**Comment by IonutRealDevs** [comment]
```
import PushNotification from 'react-native-push-notification'

export default PushNotifications = () => {
  PushNotification.configure({
    onRegister: function(token) {
      console.log('Token', token)
    },
    senderID: '474326164077'
  })
}
```

Here is it. Also i added in AppDelegate.m the code from documentation.

**Comment by ameenmattar** [comment]
Same problem here, I am not sure if this a linking issue or not.
"react-native": "0.60.0",
 "react-native-push-notification": "^3.1.9",

same code as @IonutRealDevs  and the onRegister is not being called and no token generated

AppDelegate.m is : 
![Screen Shot 2019-10-02 at 5 44 32 PM](https://user-images.githubusercontent.com/32841332/66054203-4fbb8a80-e53c-11e9-8d1a-00b29ec478a4.png)

**Comment by ameenmattar** [comment]
What solved my issue was to enable the push notification in the capabilities, I forgot to do this at first

**Comment by IonutRealDevs** [comment]
Me too, i solved by enabling notifications in capabilities, but now i don't receive notifications . In AWS SNS the status for the token is Enabled first time, after i try to send a message, the status became Disabled... How to solve this?
