### ISSUE TITLE
userInteraction always false 

### ISSUE THREAD

**Issue by globicintbh** [zo0r/react-native-push-notification#1205]
Hello Friends ,, 

I have a problem with click on notification from notification center ( in android ) ,
when I receive notification the userInteraction is false and when i click the notification also it's keep false without any change .. 

any solution ?

**Comment by globicintbh** [comment]
actually I am using remote notification .

**Comment by globicintbh** [comment]
One thing also , I think is related with it , `onNotification()` is not fire when tapping also 
userInteraction I put inside` onNotification()` and whole code inside constructor

**Comment by IgnorancePulls** [comment]
Also same issue here.
Push notification is configured in componentDidMount however `userInteraction` is just missing on notification that is opened from notification center

**Comment by meznaric** [comment]
Same here.
Using: 3.1.3 - the version before AndroidX as we haven't migrated yet.
Also should migration to AndroidX be a major version bump? 🤔

**Comment by RodolfoGS** [comment]
Same here on iOS, when I have the app in foreground, I open the notificacion center and tap a notification, `onNotification` is called but the `userInteraction` flag is false.
Any solution?

react-native-puth-notification: 3.1.9
ios: 13.2.3

Android works great.

**Comment by yanavoznuk** [comment]
the same

**Comment by gaboelnuevo** [comment]
This workaround worked for me. (android)

```
import nextFrame from "next-frame";
// ..
async onNotification (notification) {
 await nextFrame();
    notification.userInteraction = notification.userInteraction || (!notification.foreground && AppState.currentState == "active");
}
```
