### ISSUE TITLE
Not working FCM Push notification iOS

### ISSUE THREAD

**Issue by nareshkumardaffodilsw** [zo0r/react-native-push-notification#1208]
I am getting my device token. I have used this device token to generate the push notification. But i am getting getting any call in AppDelegate or in onReceive functions. Please help me

**Comment by r0b0t3d** [comment]
You mean that you got fcm token already?
If so, could you try to check if that token is valid by using  [`NWPusher`](https://github.com/noodlewerk/NWPusher) or [`PushNotifications`](https://github.com/onmyway133/PushNotifications)

**Comment by batuhanorhn** [comment]
i having the same problem. Please help. @zo0r

**Comment by Dallas62** [comment]
Hi,
The token provided is not for Firebase but for APN.
