### ISSUE TITLE
Local notification is working  but remote notification is not working

### ISSUE THREAD

**Issue by mertbuldur** [zo0r/react-native-push-notification#1216]
Hi , The application also does not work now running remote notification before.
I am using React native firebase.
Works on Android ios also does not work.
I'm not getting any mistakes.
local notification is running.

**Comment by paras-kc** [comment]
I am facing the same error.

**Comment by KPS250** [comment]
Getting the same issue. However, I am getting token but no success with push notification on the device with the token.

**Comment by ezechielk** [comment]
Same here, someone found a solution ?

**Comment by Tino-F** [comment]
It seems to be an issue related to the token itself. See https://github.com/node-apn/node-apn/issues/666#issuecomment-551842757 not sure how to retrieve the token in the correct format yet.

**Comment by Aayushi1301** [comment]
Still same issue. I tried cloning the example project and followed installation steps in https://github.com/react-native-community/push-notification-ios but I am not able to receive remote notifications from firebase.

**Comment by Dallas62** [comment]
Hi,
The iOS library doesn't provide an FCM token but an APN token.
Please use the firebase library for this purpose, or migrate APN token to FCM token using the Firebase API, or use APN services.
Regards

**Comment by Aayushi1301** [comment]
@Dallas62 Thanks for the response. It helped. I used Firebase library to get the fcm token but still on sending remote notification from firebase, `didReceiveRemoteNotification` in AppDelegate or react-native-push-notification's `onNotification` is not being called. Can you suggest cause for this. I am running this on iPhone 10. Earlier using react-native-firebase/messaging the remote notifications came up fine in the same project.
