### ISSUE TITLE
Managing local schedueled notifications

### ISSUE THREAD

**Issue by frattle** [zo0r/react-native-push-notification#1218]
Hello, is it possible to manage all created local schedueled notifications? 
There is option for cancel all of them, but useful feature will be also to fetch all planned notifications for further updates/cancelling. 

Or is it common case, that you have to save notification ID, etc in parallel database? Thank you

**Comment by kckunal2612** [comment]
For iOS, `await PushNotificationIOS.getScheduledLocalNotifications()` is returning an array of notification objects which let you know about the local scheduled notifications (set when calling `PushNotification.localNotificationSchedule(mNotification)`).

For Android, what I am doing is using a local array (`const scheduled = []`), and I am adding my `mNotification` object to this array. I can then access this array anywhere in my code and manage them however I need.

**Comment by Breners** [comment]
kckunal how did you do that? I can only limit the scope of the array

**Comment by cbahir** [comment]
Any chance to update scheduled notification with their id?

i.e: I schedule one notification with ID. now I want to update that particular notification. I have it's ID, so can I di that?
