### ISSUE TITLE
Actions for push notification on ios

### ISSUE THREAD

**Issue by VSoull** [zo0r/react-native-push-notification#1219]
For push notification action for IOS the doc send us to https://github.com/holmesal/react-native-ios-notification-actions, the lib is not  working with rect-native 0.60+(pod setup issue) , do we have an alternative for this situation?

Thank you

**Comment by chenop** [comment]
for IOS - Docs sends you to use [this](https://github.com/react-native-community/push-notification-ios) (not the one you mentioned) - Still this does not work for me either

**Comment by Dallas62** [comment]
Changes have been made on the iOS library, can you check the documentation to know if this fit your needs ?
(Not available directly from this library actually)
