### ISSUE TITLE
RNPushNotification tried to override RNPushNotification 

### ISSUE THREAD

**Issue by Jason6809** [zo0r/react-native-push-notification#1220]
Why this happen ?

`package com.awesomefyp;

import android.app.Application;
import android.util.Log;

import com.facebook.react.PackageList;
import com.facebook.hermes.reactexecutor.HermesExecutorFactory;
import com.facebook.react.bridge.JavaScriptExecutorFactory;
import com.facebook.react.ReactApplication;
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;

import io.invertase.firebase.auth.RNFirebaseAuthPackage;
import io.invertase.firebase.firestore.RNFirebaseFirestorePackage;
import io.invertase.firebase.functions.RNFirebaseFunctionsPackage;
//import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;

import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.List;

public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            @SuppressWarnings("UnnecessaryLocalVariable")
            List<ReactPackage> packages = new PackageList(this).getPackages();
            // Packages that cannot be autolinked yet can be added manually here, for example:
            // packages.add(new MyReactNativePackage());
            packages.add(new RNFirebaseAuthPackage());
            packages.add(new RNFirebaseFirestorePackage());
            packages.add(new RNFirebaseFunctionsPackage());
            // packages.add(new RNFirebaseMessagingPackage());
            packages.add(new ReactNativePushNotificationPackage());
            return packages;
        }

        @Override
        protected String getJSMainModuleName() {
            return "index";
        }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, /* native exopackage */ false);
    }
}
`

**Comment by Jason6809** [comment]
Same problem existed, after remove duplicated import.

`package com.awesomefyp;

import android.app.Application;
import android.util.Log;

import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
import com.facebook.react.PackageList;
import com.facebook.hermes.reactexecutor.HermesExecutorFactory;
import com.facebook.react.bridge.JavaScriptExecutorFactory;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;

import io.invertase.firebase.auth.RNFirebaseAuthPackage;
import io.invertase.firebase.firestore.RNFirebaseFirestorePackage;
import io.invertase.firebase.functions.RNFirebaseFunctionsPackage;


import java.util.List;


public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            @SuppressWarnings("UnnecessaryLocalVariable")
            List<ReactPackage> packages = new PackageList(this).getPackages();
            // Packages that cannot be autolinked yet can be added manually here, for example:
            // packages.add(new MyReactNativePackage());
            packages.add(new RNFirebaseAuthPackage());
            packages.add(new RNFirebaseFirestorePackage());
            packages.add(new RNFirebaseFunctionsPackage());
            packages.add(new ReactNativePushNotificationPackage());
            return packages;
        }

        @Override
        protected String getJSMainModuleName() {
            return "index";
        }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, /* native exopackage */ false);
    }
}
`

**Comment by Jason6809** [comment]
can some teach me how to set canOverrideExistingModule = true. Thank you. This will more faster to solve my problem first.

**Comment by anilios** [comment]
I am also facing same issue..

**Comment by kaaoo** [comment]
Hey, probably, autolinking is enough, so you can just remove this line:
packages.add(new ReactNativePushNotificationPackage());

**Comment by shaunthomson2097** [comment]
I am nothing special, but I don't like to leave someone hanging as I know how it feels to get stuck for long. I hope this can help you.

I agree with @kaaoo that autolinking is enough, but in my case I also had to do the following as listed below, and then the whole thing worked again.

For a clean android project run the following commands. Just change the directories to suit yours. (I use a Windows laptop so if using Mac/Linux commands just change it.)

`cd android 

gradlew clean

cd ../ 

npm cache clean --force

npx react-native start --reset-cache

npx react-native run-android`

**Comment by shaunthomson2097** [comment]
I agree with @kaaoo that autolinking is enough, but in my case I also had to do the following as listed below, and then the whole thing worked again. I hope this works for you as well.

For a clean android project run the following commands. Just change the directories to suit yours. (I use a Windows laptop so if using Mac/Linux commands just change it.)

cd android

gradlew clean

cd ../

npm cache clean --force

npx react-native start --reset-cache

npx react-native run-android

**Comment by shaunthomson2097** [comment]
I agree with @kaaoo that autolinking is enough, but in my case I also had to do the following as listed below, and then the whole thing worked again. I hope this works for you as well.

For a clean android project run the following commands. Just change the directories to suit yours. (I use a Windows laptop so if using Mac/Linux commands just change it.)

In your project root dir run the commands below:

cd android

gradlew clean

cd ../

npm cache clean --force

npx react-native start --reset-cache

npx react-native run-android

**Comment by sudhiryadav** [comment]
In  v 7.x.x i had to create a channel. Working with default channel didn't worked.

**Comment by Dallas62** [comment]
Hi @sudhiryadav 

Yes, it's explained in the CHANGELOG.

Regards

**Comment by akshgods** [comment]
> In v 7.x.x i had to create a channel. Working with default channel didn't worked.

can any one guid me how to create channel and what should be name of channel?

**Comment by AissaRouk** [comment]
> Hey, probably, autolinking is enough, so you can just remove this line: packages.add(new ReactNativePushNotificationPackage());

This worked for me :)
