### ISSUE TITLE
After Install the package npm install --save react-native-push-notification; Terminal crashes after react-native run-android. 

### ISSUE THREAD

**Issue by erdenayozkanl** [zo0r/react-native-push-notification#1221]
**_After Install the package npm install --save react-native-push-notification; Terminal crashes after react-native run-android._** 
* Where:
Build file '/Users/ErusluDevloper/Desktop/Sleepy/node_modules/react-native-push-notification/android/build.gradle' line: 51

* What went wrong:
A problem occurred evaluating project ':react-native-push-notification'.
> Could not find method testImplementation() for arguments [junit:junit:4.12] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 4s

Even I tried to manual linking. **Android** is not working. Please help I am stocked.

**Comment by yalcinozer** [comment]
testImplementation() method has problems with operating systems in Turkish.
You can try to change
testImplementation()
to:
testİmplementation()

It may work for you.

**Comment by erdenayozkanl** [comment]
Selamın aleyküm,

testImplementation methodu neyin içinde? Ve benim bulduğum testImplementation methodunda değişiklik yapmak işe yaramadı. Teşekkürler vaktiniz için. 

Saygılarımla,
Erdenay Özkanlı

**Comment by yalcinozer** [comment]
As,

Dostum açıkçası günlerimi basit bir bildirim paketini eklemek için harcadım. Durum o hale geldiki uygulamayı kodlamaktan çok, hatasız build etmek için vakit harcıyordum. testImplementetion() ı İ ile yazdığımda o hatayı atladı ama başka yerde takılmıştı. Üzerinden biraz zaman geçti tam olarak hatırlamıyorum. Biliyorsun bu bir hack vari bir çözüm. Daha güzel çözüm alternatifleri vardır.

Allaha emanet.

**Comment by keremkurtulus** [comment]
I solved this issue after updating the android gradle plugin in my project.

In your android/build.gradle update the android gradle plugin version.
`dependencies {
        classpath("com.android.tools.build:gradle:3.4.2") 
}`
Instead use the latest version
`dependencies {
        classpath("com.android.tools.build:gradle:3.5.2")
}`

**Comment by passarante** [comment]
in node_modules\react-native-push-notification\android\build.gradle file

   implementation fileTree(dir: 'libs', include: ['*.jar'])
    ### **//testImplementation 'junit:junit:4.12'**** line -51
    implementation "com.android.support:appcompat-v7:$supportLibVersion"

comment the line and clean the gradle
