### ISSUE TITLE
react-native-push-notification generateDebugRFile

### ISSUE THREAD

**Issue by ouroran** [zo0r/react-native-push-notification#1223]
Hi..
I dont understand this problem. Is there anyone help me ?

![err](https://user-images.githubusercontent.com/56828766/67491441-9dc83780-f67d-11e9-9cb5-152b3727cd07.PNG)

**Comment by harsha-sira** [comment]
@ouroran Does not know the exact cause for this issue. but found a workaround. I remove the node_modules and reinstalling did the trick for me. Hope this will helpful
