### ISSUE TITLE
how to check google play services version and firebase version??

### ISSUE THREAD

**Issue by yash1511** [zo0r/react-native-push-notification#1224]
I am trying to install react-native-push-notification which requires the google play services version and firebase version in the android/build.gradle.
I'm new at this, please help me find these versions?

**Comment by alex-mironov** [comment]
@yash1511 how did you solve it? :)

**Comment by abdulbasitha** [comment]
please use 
googlePlayServicesVersion = "16.1.0"
firebaseVersion = "17.3.4"

**Comment by fogg4444** [comment]
Could this be documented better?

**Comment by sohaib3335** [comment]
Same here. It says "Your Google Play Services" version in the documentation and I have no idea what version it is.

**Comment by anilkumar2273702** [comment]
I'm also newer in react native mobile applications, I would like to know about google play services version and firebase version for push notifications.
@yash-atreya, have you got the answer?

**Comment by anilkumar2273702** [comment]
> try this
> googlePlayServicesVersion = "16.1.0"
> firebaseVersion = "17.3.4"

How you are giving this version?
