### ISSUE TITLE
Always start app when action button clicked

### ISSUE THREAD

**Issue by Jacky9425** [zo0r/react-native-push-notification#1227]
Hi, i manage to schedule a local notifications with action buttons, but the action buttons will trigger app start when clicked.

Did i missed out something cause i dont want the app start on action button click events, for example, the phone will schedule another notification on press action button without opening the app.

Any suggestions?

**Comment by ashokkumar88** [comment]
@Jacky9425 Did you find any work around?

**Comment by xdarkleonx** [comment]
I have this problem too

**Comment by Sanan4li** [comment]
Hi, I am facing same issue.. if you found any solution please share

**Comment by dehypnosis** [comment]
This feature is required to present complete customizable actions in notification!

**Comment by Dallas62** [comment]
Hi, this should be fixed in recent releases :wink:
