### ISSUE TITLE
Firebase Versioning Mismatch(The library com.google.firebase:firebase-iid is being requested by various other libraries at.....)

### ISSUE THREAD

**Issue by dnovakovic15** [zo0r/react-native-push-notification#1230]
Hi all,

I was hoping someone could help me with getting this module to work with firebase. Whenever I try to run react-native run-android, the following error shows up. The library com.google.firebase:firebase-iid is being requested by various other libraries at [[17.0.4,17.0.4], [20.0.0,20.0.0]], but resolves to 20.0.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

I tried upgrading my firebase versions to the latest ones and even my google play, but I still run into similar issues. I was hoping someone else has run into this issue. Below is my dependency tree.

eleaseUnitTestRuntimeClasspath - Resolved configuration for runtime for variant: releaseUnitTest
+--- project :react-native-push-notification
|    +--- com.android.support:appcompat-v7:27.1.1
|    |    +--- com.android.support:support-annotations:27.1.1
|    |    +--- com.android.support:support-core-utils:27.1.1
|    |    |    +--- com.android.support:support-annotations:27.1.1
|    |    |    \--- com.android.support:support-compat:27.1.1
|    |    |         +--- com.android.support:support-annotations:27.1.1
|    |    |         \--- android.arch.lifecycle:runtime:1.1.0
|    |    |              +--- android.arch.lifecycle:common:1.1.0
|    |    |              \--- android.arch.core:common:1.1.0
|    |    +--- com.android.support:support-fragment:27.1.1
|    |    |    +--- com.android.support:support-compat:27.1.1 (*)
|    |    |    +--- com.android.support:support-core-ui:27.1.1
|    |    |    |    +--- com.android.support:support-annotations:27.1.1
|    |    |    |    +--- com.android.support:support-compat:27.1.1 (*)
|    |    |    |    \--- com.android.support:support-core-utils:27.1.1 (*)
|    |    |    +--- com.android.support:support-core-utils:27.1.1 (*)
|    |    |    +--- com.android.support:support-annotations:27.1.1
|    |    |    +--- android.arch.lifecycle:livedata-core:1.1.0
|    |    |    |    +--- android.arch.lifecycle:common:1.1.0
|    |    |    |    +--- android.arch.core:common:1.1.0
|    |    |    |    \--- android.arch.core:runtime:1.1.0
|    |    |    |         \--- android.arch.core:common:1.1.0
|    |    |    \--- android.arch.lifecycle:viewmodel:1.1.0
|    |    +--- com.android.support:support-vector-drawable:27.1.1
|    |    |    +--- com.android.support:support-annotations:27.1.1
|    |    |    \--- com.android.support:support-compat:27.1.1 (*)
|    |    \--- com.android.support:animated-vector-drawable:27.1.1
|    |         +--- com.android.support:support-vector-drawable:27.1.1 (*)
|    |         \--- com.android.support:support-core-ui:27.1.1 (*)
|    +--- com.facebook.react:react-native:+ -> 0.57.8
|    |    +--- com.facebook.infer.annotation:infer-annotation:0.11.2
|    |    |    \--- com.google.code.findbugs:jsr305:3.0.1 -> 3.0.2
|    |    +--- javax.inject:javax.inject:1
|    |    +--- com.android.support:appcompat-v7:27.1.1 (*)
|    |    +--- com.facebook.fresco:fresco:1.10.0
|    |    |    +--- com.facebook.fresco:fbcore:1.10.0
|    |    |    +--- com.facebook.fresco:drawee:1.10.0
|    |    |    |    +--- com.facebook.fresco:fbcore:1.10.0
|    |    |    |    \--- com.facebook.fresco:imagepipeline:1.10.0
|    |    |    |         +--- com.facebook.fresco:imagepipeline-base:1.10.0
|    |    |    |         |    +--- com.facebook.soloader:soloader:0.5.0 -> 0.5.1
|    |    |    |         |    +--- com.parse.bolts:bolts-tasks:1.4.0
|    |    |    |         |    \--- com.facebook.fresco:fbcore:1.10.0
|    |    |    |         +--- com.facebook.soloader:soloader:0.5.0 -> 0.5.1
|    |    |    |         +--- com.parse.bolts:bolts-tasks:1.4.0
|    |    |    |         \--- com.facebook.fresco:fbcore:1.10.0
|    |    |    +--- com.facebook.fresco:imagepipeline:1.10.0 (*)
|    |    |    \--- com.facebook.soloader:soloader:0.5.0 -> 0.5.1
|    |    +--- com.facebook.fresco:imagepipeline-okhttp3:1.10.0
|    |    |    +--- com.squareup.okhttp3:okhttp:3.10.0 -> 3.11.0
|    |    |    |    \--- com.squareup.okio:okio:1.14.0
|    |    |    +--- com.facebook.fresco:fbcore:1.10.0
|    |    |    \--- com.facebook.fresco:imagepipeline:1.10.0 (*)
|    |    +--- com.facebook.soloader:soloader:0.5.1
|    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    +--- com.squareup.okhttp3:okhttp:3.11.0 (*)
|    |    +--- com.squareup.okhttp3:okhttp-urlconnection:3.11.0
|    |    |    \--- com.squareup.okhttp3:okhttp:3.11.0 (*)
|    |    +--- com.squareup.okio:okio:1.14.0
|    |    \--- org.webkit:android-jsc:r174650
|    +--- com.google.android.gms:play-services-gcm:+ -> 17.0.0
|    |    +--- androidx.collection:collection:1.0.0
|    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    +--- androidx.core:core:1.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    +--- androidx.collection:collection:1.0.0 (*)
|    |    |    +--- androidx.lifecycle:lifecycle-runtime:2.0.0
|    |    |    |    +--- androidx.lifecycle:lifecycle-common:2.0.0
|    |    |    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    |    |    +--- androidx.arch.core:core-common:2.0.0
|    |    |    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    |    \--- androidx.versionedparcelable:versionedparcelable:1.0.0
|    |    |         +--- androidx.annotation:annotation:1.0.0
|    |    |         \--- androidx.collection:collection:1.0.0 (*)
|    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    +--- androidx.documentfile:documentfile:1.0.0
|    |    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    |    +--- androidx.loader:loader:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    +--- androidx.lifecycle:lifecycle-livedata:2.0.0
|    |    |    |    |    +--- androidx.arch.core:core-runtime:2.0.0
|    |    |    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    |    |    \--- androidx.arch.core:core-common:2.0.0 (*)
|    |    |    |    |    +--- androidx.lifecycle:lifecycle-livedata-core:2.0.0
|    |    |    |    |    |    +--- androidx.lifecycle:lifecycle-common:2.0.0 (*)
|    |    |    |    |    |    +--- androidx.arch.core:core-common:2.0.0 (*)
|    |    |    |    |    |    \--- androidx.arch.core:core-runtime:2.0.0 (*)
|    |    |    |    |    \--- androidx.arch.core:core-common:2.0.0 (*)
|    |    |    |    \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0
|    |    |    |         \--- androidx.annotation:annotation:1.0.0
|    |    |    +--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
|    |    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    |    \--- androidx.print:print:1.0.0
|    |    |         \--- androidx.annotation:annotation:1.0.0
|    |    +--- com.google.android.gms:play-services-base:17.0.0
|    |    |    +--- androidx.collection:collection:1.0.0 (*)
|    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    +--- androidx.fragment:fragment:1.0.0
|    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    +--- androidx.legacy:legacy-support-core-ui:1.0.0
|    |    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |    |    |    |    +--- androidx.customview:customview:1.0.0
|    |    |    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    |    |    \--- androidx.core:core:1.0.0 (*)
|    |    |    |    |    +--- androidx.viewpager:viewpager:1.0.0
|    |    |    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    |    |    +--- androidx.coordinatorlayout:coordinatorlayout:1.0.0
|    |    |    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    |    |    +--- androidx.drawerlayout:drawerlayout:1.0.0
|    |    |    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    |    |    +--- androidx.slidingpanelayout:slidingpanelayout:1.0.0
|    |    |    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    |    |    +--- androidx.interpolator:interpolator:1.0.0
|    |    |    |    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    |    |    |    +--- androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
|    |    |    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    |    |    \--- androidx.interpolator:interpolator:1.0.0 (*)
|    |    |    |    |    +--- androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
|    |    |    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    |    |    \--- androidx.core:core:1.0.0 (*)
|    |    |    |    |    \--- androidx.cursoradapter:cursoradapter:1.0.0
|    |    |    |    |         \--- androidx.annotation:annotation:1.0.0
|    |    |    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |    |    |    +--- androidx.annotation:annotation:1.0.0
|    |    |    |    +--- androidx.loader:loader:1.0.0 (*)
|    |    |    |    \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0 (*)
|    |    |    +--- com.google.android.gms:play-services-basement:17.0.0
|    |    |    |    +--- androidx.collection:collection:1.0.0 (*)
|    |    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    |    \--- androidx.fragment:fragment:1.0.0 (*)
|    |    |    \--- com.google.android.gms:play-services-tasks:17.0.0
|    |    |         \--- com.google.android.gms:play-services-basement:17.0.0 (*)
|    |    +--- com.google.android.gms:play-services-basement:17.0.0 (*)
|    |    +--- com.google.android.gms:play-services-iid:[17.0.0] -> 17.0.0
|    |    |    +--- androidx.collection:collection:1.0.0 (*)
|    |    |    +--- androidx.core:core:1.0.0 (*)
|    |    |    +--- com.google.android.gms:play-services-base:17.0.0 (*)
|    |    |    +--- com.google.android.gms:play-services-basement:17.0.0 (*)
|    |    |    +--- com.google.android.gms:play-services-stats:17.0.0
|    |    |    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |    |    |    \--- com.google.android.gms:play-services-basement:17.0.0 (*)
|    |    |    \--- com.google.android.gms:play-services-tasks:17.0.0 (*)
|    |    \--- com.google.android.gms:play-services-stats:17.0.0 (*)
|    +--- me.leolin:ShortcutBadger:1.1.8
|    \--- com.google.firebase:firebase-messaging:+ -> 20.0.0
|         +--- androidx.collection:collection:1.0.0 (*)
|         +--- androidx.core:core:1.0.0 (*)
|         +--- com.google.android.gms:play-services-basement:17.0.0 (*)
|         +--- com.google.android.gms:play-services-tasks:17.0.0 (*)
|         +--- com.google.firebase:firebase-common:19.0.0
|         |    +--- com.google.android.gms:play-services-basement:17.0.0 (*)
|         |    +--- com.google.android.gms:play-services-tasks:17.0.0 (*)
|         |    \--- com.google.auto.value:auto-value-annotations:1.6.5
|         +--- com.google.firebase:firebase-iid:[20.0.0] -> 20.0.0
|         |    +--- androidx.collection:collection:1.0.0 (*)
|         |    +--- androidx.core:core:1.0.0 (*)
|         |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|         |    +--- com.google.android.gms:play-services-basement:17.0.0 (*)
|         |    +--- com.google.android.gms:play-services-stats:17.0.0 (*)
|         |    +--- com.google.android.gms:play-services-tasks:17.0.0 (*)
|         |    +--- com.google.firebase:firebase-common:19.0.0 (*)
|         |    \--- com.google.firebase:firebase-iid-interop:17.0.0
|         |         +--- com.google.android.gms:play-services-base:17.0.0 (*)
|         |         \--- com.google.android.gms:play-services-basement:17.0.0 (*)
|         \--- com.google.firebase:firebase-measurement-connector:18.0.0
|              \--- com.google.android.gms:play-services-basement:17.0.0 (*)
+--- project :react-native-gesture-handler
+--- project :react-native-firebase
|    +--- com.facebook.react:react-native:+ -> 0.57.8 (*)
|    +--- com.android.support:support-v4:27.1.1
|    |    +--- com.android.support:support-compat:27.1.1 (*)
|    |    +--- com.android.support:support-media-compat:27.1.1
|    |    |    +--- com.android.support:support-annotations:27.1.1
|    |    |    \--- com.android.support:support-compat:27.1.1 (*)
|    |    +--- com.android.support:support-core-utils:27.1.1 (*)
|    |    +--- com.android.support:support-core-ui:27.1.1 (*)
|    |    \--- com.android.support:support-fragment:27.1.1 (*)
|    \--- com.android.support:multidex:1.0.2
+--- project :react-native-view-overflow
|    \--- com.facebook.react:react-native:+ -> 0.57.8 (*)
+--- project :rn-fetch-blob
|    \--- com.facebook.react:react-native:+ -> 0.57.8 (*)
+--- project :react-native-image-picker
|    \--- com.facebook.react:react-native:+ -> 0.57.8 (*)
+--- project :react-native-vector-icons
|    \--- com.facebook.react:react-native:+ -> 0.57.8 (*)
+--- project :react-native-document-picker
|    \--- com.facebook.react:react-native:+ -> 0.57.8 (*)
+--- project :react-native-fingerprint-android
+--- project :react-native-keychain
|    +--- com.facebook.react:react-native:0.19.+ -> 0.57.8 (*)
|    \--- com.facebook.conceal:conceal:1.1.2
+--- com.android.support:appcompat-v7:27.1.1 (*)
+--- com.facebook.react:react-native:+ -> 0.57.8 (*)
+--- com.google.android.gms:play-services-base:16.0.1 -> 17.0.0 (*)
+--- com.google.firebase:firebase-core:16.0.6
|    +--- com.google.firebase:firebase-analytics:16.0.6
|    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 17.0.0 (*)
|    |    +--- com.google.android.gms:play-services-measurement-api:[16.0.4] -> 16.0.4
|    |    |    +--- com.google.android.gms:play-services-ads-identifier:16.0.0
|    |    |    |    \--- com.google.android.gms:play-services-basement:16.0.1 -> 17.0.0 (*)
|    |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 17.0.0 (*)
|    |    |    +--- com.google.android.gms:play-services-measurement-base:[16.0.5] -> 16.0.5
|    |    |    |    \--- com.google.android.gms:play-services-basement:16.0.1 -> 17.0.0 (*)
|    |    |    +--- com.google.android.gms:play-services-stats:16.0.1 -> 17.0.0 (*)
|    |    |    +--- com.google.android.gms:play-services-tasks:16.0.1 -> 17.0.0 (*)
|    |    |    +--- com.google.firebase:firebase-analytics-impl:[16.2.4] -> 16.2.4
|    |    |    |    +--- com.google.android.gms:play-services-ads-identifier:16.0.0 (*)
|    |    |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 17.0.0 (*)
|    |    |    |    +--- com.google.android.gms:play-services-measurement-base:[16.0.5] -> 16.0.5 (*)
|    |    |    |    +--- com.google.android.gms:play-services-stats:16.0.1 -> 17.0.0 (*)
|    |    |    |    +--- com.google.android.gms:play-services-tasks:16.0.1 -> 17.0.0 (*)
|    |    |    |    +--- com.google.firebase:firebase-common:16.0.3 -> 19.0.0 (*)
|    |    |    |    \--- com.google.firebase:firebase-iid:17.0.3 -> 20.0.0 (*)
|    |    |    +--- com.google.firebase:firebase-common:16.0.3 -> 19.0.0 (*)
|    |    |    \--- com.google.firebase:firebase-iid:17.0.3 -> 20.0.0 (*)
|    |    +--- com.google.android.gms:play-services-measurement-base:[16.0.5] -> 16.0.5 (*)
|    |    +--- com.google.android.gms:play-services-stats:16.0.1 -> 17.0.0 (*)
|    |    +--- com.google.firebase:firebase-analytics-impl:[16.2.4] -> 16.2.4 (*)
|    |    \--- com.google.firebase:firebase-common:16.0.3 -> 19.0.0 (*)
|    \--- com.google.firebase:firebase-measurement-connector-impl:17.0.4
|         +--- com.google.android.gms:play-services-basement:16.0.1 -> 17.0.0 (*)
|         +--- com.google.android.gms:play-services-measurement-api:[16.0.4] -> 16.0.4 (*)
|         +--- com.google.android.gms:play-services-measurement-base:[16.0.5] -> 16.0.5 (*)
|         +--- com.google.firebase:firebase-analytics:[16.0.6] -> 16.0.6 (*)
|         +--- com.google.firebase:firebase-analytics-impl:[16.2.4] -> 16.2.4 (*)
|         +--- com.google.firebase:firebase-common:16.0.3 -> 19.0.0 (*)
|         \--- com.google.firebase:firebase-measurement-connector:17.0.1 -> 18.0.0 (*)
+--- com.google.firebase:firebase-messaging:20.0.0 (*)
\--- com.google.firebase:firebase-iid:20.0.0 (*)

**Comment by NonkelDaniel** [comment]
I am also having this problem. How can one work around this or fix it?
