### ISSUE TITLE
Setup push notification in react native without using firebase

### ISSUE THREAD

**Issue by eriffat896** [zo0r/react-native-push-notification#1231]
I am trying to add notification in my app using `react-native-push-notification` according to [this documentation][1] for android. But when I come to change `android/build.gradle` file, it requires `googlePlayServicesVersion` and `firebaseVersion` and my app is using MySql-PHP file for its database.
So what can I write in front of `googlePlayServicesVersion` and `firebaseVersion` with that app's notification will start working.

  [1]: https://github.com/zo0r/react-native-push-notification

**Comment by ezechielk** [comment]
up !

**Comment by AhmedQamar10** [comment]
https://github.com/zo0r/react-native-push-notification/issues/796#issuecomment-608213235

**Comment by dom2221996** [comment]
if i dont want to use firebase then is it possible to use push notification as i have tried using with firebase property its giving me error as :-  Default firebaseApp is not initialized in the process com.projectName. Make sure to call FirebaseApp.initializeApp(context)first
what to do in this senerio

**Comment by Dallas62** [comment]
Hi @dom2221996 

Information are available in the readme, `.configure()`.
