### ISSUE TITLE
is this repo still maintained ?

### ISSUE THREAD

**Issue by ssolida** [zo0r/react-native-push-notification#1235]
600 Issues, 74 Pull requests....is that project still going on ? if not, is there a better alternative ?

**Comment by schumannd** [comment]
react-native-notification looks promising.

**Comment by anilios** [comment]
I think its not maintained by anyone now.. a lot of issues are pending

**Comment by Dallas62** [comment]
Hi @ssolida 
I'm a new maintainer of this projet, I will do my best to maintain this project and I will need some help like issue resolution / PR.
It would be great if other people come in this project as maintainer to avoid this lake of support and bring new ideas to make this library better.
Regards
