### ISSUE TITLE
Local notifications are not being sent to ios 13.1 device

### ISSUE THREAD

**Issue by kilimchoi** [zo0r/react-native-push-notification#1236]
I'm using react-native-push-notification 3.1.9 but I've been experiencing this issue where I'm not getting local notifications that are scheduled. It works on ios version before 13 but it stopped working after I upgraded my device to 13.1.2. Anyone has experienced this before? If so, how did you solve it?

**Comment by HanliTheron** [comment]
Hi, I think it is related to this https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/.
