### ISSUE TITLE
repeatType month

### ISSUE THREAD

**Issue by tosifkhan01** [zo0r/react-native-push-notification#1237]
Curently I'm using "react-native-push-notification": "3.1.1"

Can I use repeatType month without migrating to latest version 3.1.9?
3.1.9 supports androidX and currently I don't want to go for androidX.

Any solution?

**Comment by mo-patel** [comment]
A possible workaround you can do it specify the repeatType as 'time' and then the repeatTime equal to the amount of milliseconds for a month
