### ISSUE TITLE
Android error "For input string: "

### ISSUE THREAD

**Issue by Richi2293** [zo0r/react-native-push-notification#1239]
Hi,

I get this error when I try to use the library on Android.
On iOS it seems to work properly.

------

System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 337.67 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 19, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0
      System Images: android-25 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2
    react-native-git-upgrade: 0.2.7

-----

![screen](https://user-images.githubusercontent.com/5848941/68661184-cd5eb700-053a-11ea-8c7b-76f413c75ae4.png)

**Comment by matheusbaumgart** [comment]
Same here.. the error doesn't provide much context, huh? Any solutions?

**Comment by matheusbaumgart** [comment]
Thanks to: https://github.com/zo0r/react-native-push-notification/issues/639 I found out that the string has to be all numbers.

**Comment by sergiulucaci** [comment]
@Richi2293 facing the same issue, any workaround?

**Comment by Richi2293** [comment]
Hi,
the solution is as it says matheusbaumgart.
(In a nutshell it crashed because I used an int number or because I used a string as id of notification. I don't remember exactly what it was)

**Comment by sergiulucaci** [comment]
Ok, I found the issue. I was generating random ids using date

```
const id = new Date().getTime()
```

which would generate an id formed of 13 digits, which is bigger than the max value of an integer in java, which is `2^32 - 1`.
