### ISSUE TITLE
Customizable Actions

### ISSUE THREAD

**Issue by guanw** [zo0r/react-native-push-notification#1240]
We are trying to implement notification with customized action, something like this screenshot 
![image](https://user-images.githubusercontent.com/7311035/68730625-3e35bb80-059b-11ea-8306-470e5de497c5.png)

Is there any way to do it on the js level or it has to come down to native android/ios code? Thanks for any response in advance.

**Comment by guanw** [comment]
> Hi @guanw,
> 
> Any updates on this, Are you able to do it..?
> 
> I am also looking to implement same.

not really. I haven't worked on it since opening the issue.

**Comment by Dallas62** [comment]
Changes have been made on the iOS library, can you check the documentation to know if this fit your needs ?
(Not available directly from this library actually)
