### ISSUE TITLE
Custom Sound on Android Oreo or higher SOLVED

### ISSUE THREAD

**Issue by cookienawer** [zo0r/react-native-push-notification#1242]
Hi,

I have modified RNPushNotificationHelper.java so that the custom sound now works in oreo and higher versions.

How can I publish my modified file to the main branch?

I have never done it.

**Comment by cookienawer** [comment]
This is my fork with issue solved. 

https://github.com/cookienawer/react-native-push-notification

I am waiting for the editor of the complement to accept it and integrate it into the official version.

I have created a pull request. I do not know if it is necessary to do some other step to be incorporated into the official version.

**Comment by umkhan65** [comment]
@cookienawer it worked thanks

**Comment by Dallas62** [comment]
Hi, I saw your PR, but I think there is an unexpected issue when changing sound.

Can you try this PR #1042

Thanks!
