### ISSUE TITLE
Making it work with the latest react native

### ISSUE THREAD

**Issue by nanofelix** [zo0r/react-native-push-notification#1245]
This is not really an issue, just a hint for those who can't make this library to work. It seems this library isn't mantained anymore. I've spent many days trying to make a working demo for both ios and android with this library (with latest RN). After many unsuccessful attempts, i've stumbled upon an article, which wasn't showing in google search before, when I was searching a solution to make it work. Here it is https://dev.to/edmondso006/react-native-local-ios-and-android-notifications-2c58

**Comment by Webdev259** [comment]
It is working for me and I am using:
```
"react": "16.9.0", 
"react-native": "0.61.4"
```

Which I assume is the latest React and React Native version.

**Comment by nanofelix** [comment]
Indeed, it worked (almost) fine with android, but as for IOS i've encountered this problem https://github.com/zo0r/react-native-push-notification/issues/1144, and it seems it was due to breaking changes in how ios part was linked/compiled in react native since v 0.60.0 (something related to autolinking and cocoapods)

**Comment by kevincoleman** [comment]
Not saying this is fixed, but I at least have one working case on React Native `0.60.5`, with react-native-push-notification `3.1.9`.

I’m only using it for local notifications, though.

I used [this setup walk through](https://dev.to/edmondso006/react-native-local-ios-and-android-notifications-2c58), which seemed to work better than the official docs in this repo.

It would be great to try to enumerate the differences between how I have it configured and how it’s “supposed” to be configured to then test and work out the kinks. I’m not really up to this troubleshooting at the moment, but anyone who wants to try to reproduce the symptoms and do it themselves is welcome to. Here’s [my repo with the first working commit](https://github.com/kevincoleman/something-good/commit/ccb60b01a04b3fc4114d3288093073d5ec3ae8ef) after configuring it.

Note, I still don’t see an app badge appearing on the android simulator, but scheduled notifications are working in iOS/Android, and the app badge is working in iOS—so I assume the android badge issue is just my implementation, as the library itself seems to be working.

Hope this is helpful!
