### ISSUE TITLE
JSON value '10' of type NSString cannot be converted to NSNumber

### ISSUE THREAD

**Issue by yash1511** [zo0r/react-native-push-notification#1246]
I am testing the example app.
I receive the notification but below error keeps coming :
<img width="247" alt="Screenshot 2019-11-21 at 1 31 24 PM" src="https://user-images.githubusercontent.com/44857776/69338489-9e93bf80-0c63-11ea-9207-b07e185601ac.png">

How can I fix this?

**Comment by Bad-Listener** [comment]
Just use value 10 (integer, not string) ;)

**Comment by Dallas62** [comment]
I fixed the README and example application.
