### ISSUE TITLE
localNotificationSchedule is triggered instantly instead of date property value on iOS

### ISSUE THREAD

**Issue by Paranpreet** [zo0r/react-native-push-notification#1248]
localNotificationSchedule is triggered as soon as I click on button to set notification and receive the alert. It is working fine on android.

**Comment by FullstackJack** [comment]
I feel like this issue is happening to me as well. On Android, I can schedule a local notification 30 or 60 seconds in the future, but on iOS, I can't.

**Comment by philscott-dev** [comment]
Did you guys ever find a solution? Whenever i call scheduleLocalNotification, regardless of date, on iOS, I'll immediately get a 'ding' and no notification will be scheduled.
