### ISSUE TITLE
Example for Repeating Notification please? 

### ISSUE THREAD

**Issue by enzzoperez** [zo0r/react-native-push-notification#1254]
I'm doing the below to repeat notification
```
PushNotification.localNotification({
            id,
            title: titleReminder, 
            message: detailReminder,
            repeatType: repeatReminder, //'day', 'month', 'week'
            repeatTime: repeatTime 
        })
```
but the notifications are trigger one per second aprox.
I try set the repeat time in milliseconds but the problem persist.

Can you give me an example of your settings for this please?

Im using 
- RN: 0.60.5
- "react-native-push-notification": "^3.1.9"

**Comment by Jacky9425** [comment]
repeatType: "time",
repeatTime: 3000

repeats every 3 seconds, only works on android for repeat by "time" (seconds)

**Comment by erdenayozkanl** [comment]
How could I do it in IOS?

**Comment by Jacky9425** [comment]
You can generate your own dates and queue them accordingly

**Comment by erdenayozkanl** [comment]
how? Can you help me?

Erdenay Özkanlı

**Comment by enzzoperez** [comment]
The documentation is wrong, I had to use the localNotificationSchedule class in the following way

```
PushNotification.localNotificationSchedule({
            id,
            userInfo: {id: id},
            title: titleReminder, 
            message: detailReminder, 
            repeatType: "time",
            repeatTime: repeatTime,
            date: new Date(Date.now() + repeatTime)
  })
```
Where repeatTime is getting from
```
export const getRepeatInterval = repeatType => {
    if(repeatType === typeRepeatReminder.DAILY) return moment.duration(1, 'd').asMilliseconds()
    if(repeatType === typeRepeatReminder.WEEKLY) return moment.duration(7, 'd').asMilliseconds()
    if(repeatType === typeRepeatReminder.MONTHLY) return moment.duration(30, 'd').asMilliseconds()
}
```

in another way I got the problems of repeats each second.. For Ios I didn't try doing work the package

**Comment by erdenayozkanl** [comment]
Thank you it works for android but iOS
unfortunately not :(

**Comment by coolvasanth** [comment]
@enzzoperez What is moment here ?

**Comment by enzzoperez** [comment]
@coolvasanth moment is module moment js https://momentjs.com/docs/#/durations/  , I used this because native Date dont worked for me

**Comment by coolvasanth** [comment]
With above answer and moment js package, were u able to send notifications as configured ? I tried almost every answer, but still the notification comes randomly.

**Comment by enzzoperez** [comment]
@coolvasanth Furthermore of the two files in my previous answer

> The documentation is wrong, I had to use the localNotificationSchedule class in the following way
> 
> ```
> PushNotification.localNotificationSchedule({
>             id,
>             userInfo: {id: id},
>             title: titleReminder, 
>             message: detailReminder, 
>             repeatType: "time",
>             repeatTime: repeatTime,
>             date: new Date(Date.now() + repeatTime)
>   })
> ```
> 
> Where repeatTime is getting from
> 
> ```
> export const getRepeatInterval = repeatType => {
>     if(repeatType === typeRepeatReminder.DAILY) return moment.duration(1, 'd').asMilliseconds()
>     if(repeatType === typeRepeatReminder.WEEKLY) return moment.duration(7, 'd').asMilliseconds()
>     if(repeatType === typeRepeatReminder.MONTHLY) return moment.duration(30, 'd').asMilliseconds()
> }
> ```
> 
> in another way I got the problems of repeats each second.. For Ios I didn't try doing work the package


my package.json  is
```
    "moment": "^2.24.0",
    "native-base": "^2.13.5",
    "prop-types": "^15.7.2",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-push-notification": "^3.1.9"
     ....
```

**Comment by coolvasanth** [comment]
@enzzoperez  I tested it your suggestion. It works perfectly fine. Thank you so much for your help.

**Comment by AdnaanDEV** [comment]
> @enzzoperez I tested it your suggestion. It works perfectly fine. Thank you so much for your help.

can you please explain me how do you use the repeatTime coz i am not able to understand from above code.

**Comment by enzzoperez** [comment]
> > @enzzoperez I tested it your suggestion. It works perfectly fine. Thank you so much for your help.
> 
> can you please explain me how do you use the repeatTime coz i am not able to understand from above code.

 `typeRepeatReminder` is an object with text just for compare.. Is there a particular part do you not understand?

**Comment by Balthazar33** [comment]
Hi @enzzoperez,
If I want a notification to trigger in hour from now and then every 100 days at that same time, is the following code proper?

```
PushNotification.localNotificationSchedule({
                ...
                date: new Date(Date.now() + 60 * 1000 * 60, 
                repeatType:'time',
                repeatTime:(100) * 86400000), //Repeat every 100 days 
                importance:Importance.HIGH
               ...
            }); 
```

**Comment by enzzoperez** [comment]
> Hi @enzzoperez,
> If I want a notification to trigger in hour from now and then every 100 days at that same time, is the following code proper?
> 
> ```
> PushNotification.localNotificationSchedule({
>                 ...
>                 date: new Date(Date.now() + 60 * 1000 * 60, 
>                 repeatType:'time',
>                 repeatTime:(100) * 86400000), //Repeat every 100 days 
>                 importance:Importance.HIGH
>                ...
>             }); 
> ```

I remember that I did attempt without Moment but that didnt work, you could try out with that code and if doesnt work, you could try adding Moment

**Comment by Balthazar33** [comment]
> > Hi @enzzoperez,
> > If I want a notification to trigger in hour from now and then every 100 days at that same time, is the following code proper?
> > ```
> > PushNotification.localNotificationSchedule({
> >                 ...
> >                 date: new Date(Date.now() + 60 * 1000 * 60, 
> >                 repeatType:'time',
> >                 repeatTime:(100) * 86400000), //Repeat every 100 days 
> >                 importance:Importance.HIGH
> >                ...
> >             }); 
> > ```
> 
> I remember that I did attempt without Moment but that didnt work, you could try out with that code and if doesnt work, you could try adding Moment

Yes, this does work. 👍

**Comment by Balthazar33** [comment]
> > > Hi @enzzoperez,
> > > If I want a notification to trigger in hour from now and then every 100 days at that same time, is the following code proper?
> > > ```
> > > PushNotification.localNotificationSchedule({
> > >                 ...
> > >                 date: new Date(Date.now() + 60 * 1000 * 60, 
> > >                 repeatType:'time',
> > >                 repeatTime:(100) * 86400000), //Repeat every 100 days 
> > >                 importance:Importance.HIGH
> > >                ...
> > >             }); 
> > > ```
> > 
> > 
> > I remember that I did attempt without Moment but that didn't work, you could try out with that code and if doesn't work, you could try adding Moment
> 
> Yes, this does work. 👍

There's a problem with this, though.

I have an array of messages, about a 100, and I've looped over the array to schedule a notification for each of those, one day at a time. eg., message 1 on day 1, message 2 on day 2,...and then message 1 on day 101, and so on and so forth. 

The problem is, I got the notifications in the correct order for three days, but on the fourth day, I got the first notification again. 

Can someone help me see where I might be going wrong?
