### ISSUE TITLE
Local notifications

### ISSUE THREAD

**Issue by aamir-munir** [zo0r/react-native-push-notification#1257]
Hi,

it is not an issue but a general question. Can I use local notifications to keep the application alive in the background especially on iOS?

like what I like to do my application need to ping a server after a certain time (about 4-5 min), but application stop pinging once moved to the background.

Someone suggested using notifications as it awakes the app for a few minutes and if I send another scheduled local notification I can keep it alive.

Please, I need urgent help with this if someone has more information about it. I tried using scheduled notification but it looks like it did not work out.

Do I miss something?

TIA

**Comment by erdenayozkanl** [comment]
Use backgroundfetch for IOS. Instead of notification if you ask me

**Comment by itcurves** [comment]
> Use backgroundfetch for IOS. Instead of notification if you ask me

I was reading the docs it says I can do fetch after approx 15 minutes once called.

I need something almost every minute

**Comment by erdenayozkanl** [comment]
In theory, you can use as a function the localnotifschedule. İt is refreshing every minute on both. But 

Erdenay Özkanlı

**Comment by itcurves** [comment]
> In theory, you can use as a function the localnotifschedule. İt is refreshing every minute on both. But Erdenay Özkanlı
> […](#)

I tried schedule notif but looks like that stops too when app in background. Can you please elaborate how to use it?

**Comment by erdenayozkanl** [comment]
can you send me the code

**Comment by erdenayozkanl** [comment]
It is not compatible to use as you desire. I tried.

**Comment by itcurves** [comment]
means it will not work in the background? any other suggestions for what I like to archive?

**Comment by ssuchanowski** [comment]
You can try with silent push notifications (not local) that can trigger some background fetching.

But in general no one wants have apps doing something every minute - not sure what your use case is but some scenarios are possible to do, like for example significant location changes.

**Comment by itcurves** [comment]
> You can try with silent push notifications (not local) that can trigger some background fetching.
> 
> But in general no one wants have apps doing something every minute - not sure what your use case is but some scenarios are possible to do, like for example significant location changes.

@ssuchanowski yes we are dealing with a very old API that requires a ping almost every 2-3 minutes to keep the user logged in. I know this is not a good approach but we need that in our app.

2 questions if you can answer, please?

1. there is no way to handle using local notifications?
2. if we do remote notification what you recommend? to track who to send notification (we only like to send logged in users.) also one we send a silent notification does it keep the application alive 4-5 minutes after notification?

for your location change suggestion, we have an issue with that as it might be possible there is no location change for a long time (like user at stationary.

I hope you can give some more feedback based on my requirements.

Thanks

**Comment by ssuchanowski** [comment]
1/ As far as I know - NO, I dont think you will get a code callback when receiving local notification while in background or app killed - but you would have to verify that.
2/ So background fetch has I think 10sec max time run - but bad news is that iOS might decide to not trigger it at all.

While your app is live you dont need to rely on it b/c you can pull from the app side.


I am not understanding the use case completely - you need to have app open all the time or ping every x min regardless of its state?

**Comment by itcurves** [comment]
> 1/ As far as I know - NO, I dont think you will get a code callback when receiving local notification while in background or app killed - but you would have to verify that.
> 2/ So background fetch has I think 10sec max time run - but bad news is that iOS might decide to not trigger it at all.
> 
> While your app is live you dont need to rely on it b/c you can pull from the app side.
> 
> I am not understanding the use case completely - you need to have the app open all the time or ping every x min regardless of its state?

my app needs to ping a URL (just a sec of processing) almost every minute to let the server know that the user logged into the app.
and this only going to happen if the user is logged in, I need it to keep communicating while user login with the app in the foreground or background.

I am not concerned about if the app is not running (or killed) or the user does not log in so it is all conditional.

Summary:

only call API when:
1. User login using credentials (on logout I stop the API call)
2. app state (in use/foreground, background). No need to in case the user kills the app.

Thanks for all your help

**Comment by itcurves** [comment]
I am not sure if you use this:
https://github.com/ocetnik/react-native-background-timer

do you think it can work?

**Comment by ssuchanowski** [comment]
I dont know tbh - you have to test it yourself but I would fight business logic of pinging on inactive app first.

**Comment by erdenayozkanl** [comment]
it's as far as I know works while app is not closed. Works in background
but not while closed.

**Comment by Jacky9425** [comment]
try this `react-native-background-fetch`

**Comment by itcurves** [comment]
> try this `react-native-background-fetch`

already did, no success.

any other sugession

**Comment by chrissnape** [comment]
I was looking for something similar so that the app would schedule notifications for each day, even if it was closed, but I read that is impossible from my understanding. A change in geolocation can wake up the app, but I don't think that would be any use for you.

**Comment by Zainabalhaidary** [comment]
> I was looking for something similar so that the app would schedule notifications for each day, even if it was closed, but I read that is impossible from my understanding. A change in geolocation can wake up the app, but I don't think that would be any use for you.

Hi @chrissnape 
Any luck regarding this please? I am trying to do the same but not able to.
