### ISSUE TITLE
Need more updates on this package !!!

### ISSUE THREAD

**Issue by Linoa65** [zo0r/react-native-push-notification#1258]
Hello all :)

Like as answer on #1189, this package need to be more updated, many features interesting still waiting to be merged, and this one needs more people to help. I hope Zo0r will see this post, take some contributors or people to help you to maintain this, because this module is important for mobile apps, notifications can be core of some apps, and we can't do all we need to do we this.

I call some people to make this thread active and maybe to wake up back this really good module !

Best regards,
Florient

**Comment by Return-1** [comment]
Is this package still active?

If it's not it would be responsible to communicate this so that people know to migrate to a different solution.

**Comment by Dallas62** [comment]
Hi @Linoa65 
It's now possible, PR are welcome !
