### ISSUE TITLE
localNotificationSchedule are working on debug mode but are not working in release mode Android

### ISSUE THREAD

**Issue by mak12** [zo0r/react-native-push-notification#1260]
`
    "react": "16.4.0",
    "react-native": "0.59.1",
    "react-native-push-notification": "^3.1.9",
`
localNotificationSchedule are not working in release mode but are working on debug mode, have invested alot of time in R&D but no luck.

**Comment by d0rf47** [comment]
I am having the same problem!

**Comment by d0rf47** [comment]
I found a Solution

1 Clean your build cd android && ./gradlew clean
2  cd .. && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
3 cd android && ./gradlew assembleRelease -x bundleReleaseJsAndAssets

this should ensure that you index.android.bundle is up to date with all the changes made in your debug code. once the last command has executed you will find android/app/build/output/apk/release/app-release.apk 

this new file should have everything you have in the debug program. Good Luck

**Comment by mohsinriaz17** [comment]
i am having the same issue
does not work and either android or ios

did you guys find any solution?

**Comment by d0rf47** [comment]
I did actually, I had to clean my gradle then rebuild everything then rebundle everything and re create the build apk in that order

**Comment by d0rf47** [comment]
this
1 Clean your build cd android && ./gradlew clean
2 cd .. && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
3 cd android && ./gradlew assembleRelease -x bundleReleaseJsAndAssets

this should ensure that you index.android.bundle is up to date with all the changes made in your debug code. once the last command has executed you will find android/app/build/output/apk/release/app-release.apk

this new file should have everything you have in the debug program. Good Luck

**Comment by infinitbility** [comment]
> this
> 1 Clean your build cd android && ./gradlew clean
> 2 cd .. && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
> 3 cd android && ./gradlew assembleRelease -x bundleReleaseJsAndAssets
> 
> this should ensure that you index.android.bundle is up to date with all the changes made in your debug code. once the last command has executed you will find android/app/build/output/apk/release/app-release.apk
> 
> this new file should have everything you have in the debug program. Good Luck

after doing this I am getting `App keeps stopping`

any other solution...

**Comment by Dallas62** [comment]
Hi @infinitbility 
Can you try the version on master ?
Change the version in package.json:
```
"react-native-push-notification": "git+https://git@github.com/zo0r/react-native-push-notification.git"
```
Then run `npm install` or `yarn install`
Hope it will be ok for you !
