### ISSUE TITLE
Getting data from notification on iOS doesn't work.

### ISSUE THREAD

**Issue by Wout-Vanneste-student** [zo0r/react-native-push-notification#1261]
Hi, I'm having trouble receiving data when a user clicks on his notification. It works on Android, but not on iOS. I have added all the needed code to my AppDelegate.m. And I'm using the code provided here in the docs.

 I'm also a bit confused of where this code (coming from this docs) is relevant or needed in my project:

<img width="960" alt="Screenshot 2019-12-10 at 15 02 07" src="https://user-images.githubusercontent.com/44393610/70535888-1ca9fe80-1b5e-11ea-9abb-933c6871aac0.png">

I added the `notification.finish(PushNotificationIOS.FetchResult.NoData);` in my `PushNotification.configure({ ... onNotification: *here* ... })`. But again, this function doesn't seem to do a thing. I have installed the `react-native-community/react-native-push-notification-ios` so that shouldn't be the problem...

Anyone else having this issue?

**Comment by mynameisguy** [comment]
@Wout-Vanneste-student did you manage to pass data through the notification?
