### ISSUE TITLE
Remote notification 

### ISSUE THREAD

**Issue by ksmkr** [zo0r/react-native-push-notification#1263]
Not able to sent remote push notification.set all linking and also write code as mentioned with GCM sender id but, it is sending notification to person who hit that code.(means I am sending notification but only me receiving notification) How to resolve this?

Do I need to set receiver id or something else also on push notification how to handle action of yes or no.

Please help me in this as soon as possible.

**Comment by Dallas62** [comment]
Hi, sorry for the delay, the README.md has been updated for Firebase.
