### ISSUE TITLE
Remote Notification tap handler is missing

### ISSUE THREAD

**Issue by anilios** [zo0r/react-native-push-notification#1265]
I have setup remote notifications and everything is working fine on both iOS and Android devices.
All notifications are showing in background and foreground state, but when I tap on a notification app launches only and not navigating user to the appropriate screen e.g. Chat or comments page according to the notification type.

when I remove following code line then app automatically navigates user to the detail screen based on notification type when notification is shown and does not wait for user to tap on notification.

`if (userInteraction == false) return`

Here is my code:
![Screenshot 2019-12-12 at 11 03 09 AM](https://user-images.githubusercontent.com/694814/70685302-fe174500-1cce-11ea-9b63-0542d0277203.png)
![Screenshot 2019-12-12 at 11 03 47 AM](https://user-images.githubusercontent.com/694814/70685303-fe174500-1cce-11ea-94f3-596538bf6c73.png)

**Comment by Naomarik** [comment]
This particular bit of critical functionality was also broken for me.

At this particular point of time of writing the only viable alternative seems to be the wix library.

**Comment by anilios** [comment]
Which one you are referring Remote Notifications or Notification tap handling?

**Comment by sparsh** [comment]
I am facing the notification tap handling issue. When I tap on notification (and app is closed) I am not getting userInteraction value as true.
it is working fine when app is open.
@anilios did you found any solution ?

**Comment by tolmekian1453** [comment]
I've set up everything properly AFAIK and can only get it working when the app is killed then opened by tapping a notification, rather than it being in the background. Same with the CE fork (see https://github.com/calcazar/react-native-push-notification-CE/issues/12#issuecomment-569587808).
