### ISSUE TITLE
Android - Cancel remote notifications when app is in foreground

### ISSUE THREAD

**Issue by sharon-systalent** [zo0r/react-native-push-notification#1266]
Am using GCM for android push notification and trying to cancel remote notifications when app is in foreground.
Tried both **cancelAllLocalNotifications()** and **cancelLocalNotifications({id:pid})** in **onNotification** function. But nothing did work. Has anybody encountered the same issue?

> "react-native": "0.61.3"
> "react-native-push-notification": "3.1.9"

**Comment by thanhdevapp** [comment]
same problem, any idea?

**Comment by vovkasm** [comment]
Yes, same issue. And, imho, remote notifications should not be shown in the first place if app in the foreground. But the code is clear enough:
1. Service gets notification: https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java#L31
2. It forms the notifcation object, detects if app in background, and unconditionally send this info to js and to helper that show notification: https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java#L135
3. Helper is unconditionally show notification with NotificationManager https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L392-L397

**Comment by electricBonfire** [comment]
I was seeing the same behavior, I looked in logcat in android studio filtering for `RNPushNotification` I noticed an error related to writing badge permissions. I added the following  to AndroidManifest.xml `<uses-permission android:name="com.sec.android.provider.badge.permission.WRITE" />` this resolved the error and stopped the notifications from showing when app is in foreground.
