### ISSUE TITLE
Notification is appearing in tray on Android when the app is in a background

### ISSUE THREAD

**Issue by alex-mironov** [zo0r/react-native-push-notification#1270]
Can someone please clarify if such behavior is configurable? I would like to show notifications on top of the other apps when the application is in the background.

Current behaviour - just dot in a tray:
<img width="323" alt="Screen Shot 2019-12-16 at 16 44 28" src="https://user-images.githubusercontent.com/2544767/70940209-8476b280-2052-11ea-8bd2-9b323dd8ab49.png">

**Comment by andrewtremblay-pear** [comment]
For local notifications, look at the "visibility" and "importance" variables 

```
    visibility: "private", // (optional) set notification visibility, default: private
    importance: "high", // (optional) set notification importance, default: high
```
https://github.com/zo0r/react-native-push-notification#local-notifications

For remote push notifications, it might depend on the service you use.
