### ISSUE TITLE
No sound when get notification

### ISSUE THREAD

**Issue by Yashpk789987** [zo0r/react-native-push-notification#1271]
I am not getting any sound when i get any notification from fcm  . Even I also not get default sound.
Everything works fine but There is no sound in any notification.

PushNotification.configure({
      onRegister: function(token) {
        console.log('TOKEN:', token);
      }.bind(this),

      onNotification: function(notification) {
        console.log('NOTIFICATION:', notification);
      },
      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },
      senderID: '256504080411',
      requestPermissions: true,
    });
Using in constructor of App.js

versions

"react": "16.9.0",
 "react-native": "0.61.5",
"react-native-push-notification": "^3.1.9"

**Comment by Yashpk789987** [comment]
i am sending payload to my server 

  notification: {
    title: 'Title of your push notification',
    body: 'Body of your push notification',
    playSound: true,
    soundName: 'default'
  },

**Comment by Yashpk789987** [comment]
Anyone please help me

**Comment by erdenayozkanl** [comment]
İf you're using iOS while app is open, it will not give you sound. in background it will.

**Comment by Yashpk789987** [comment]
No I am using Android.

**Comment by HuYuee** [comment]
i have the same issue

**Comment by Yashpk789987** [comment]
> i have the same issue

Better To use react-native-firebase
It's more mature

**Comment by eddiana** [comment]
I was having the same problem. 
In your notification, try setting "sound":"default".  (instead of "playSound").  That seemed to do the trick for me.

**Comment by kdpadhiyar** [comment]
https://github.com/zo0r/react-native-push-notification/issues/1423#issue-614600690

lol his own example is not plying sound

@zo0r @eddiana @Yashpk789987 @erdenayozkanl @HuYuee @eddiana

**Comment by LaVielle** [comment]
I was having a similar issue with sound not working in background notifications. The fix was to pass correct FCM payload.
See here: https://github.com/zo0r/react-native-push-notification/issues/1868#issuecomment-784338446

**Comment by DevHamzaShahid** [comment]
In my case notifications were not comming in foreground for ios i have used local notifications for foreground like this:
 useEffect(() => {
    const unsubscribe = messaging().onMessage(async remoteMessage => {
      if (Platform.OS === 'ios') {
        PushNotification.localNotification({
          title: remoteMessage.notification.title,
          message: remoteMessage.notification.message,
          soundName: 'default',
          priority: 'high',
        });
      }
    });
    return unsubscribe;
  }, []);

it has a notification sound if not in your case don’t forget to add these lines in your app delegate:

i have added some more lines for better understanding:


if (@available(iOS 13.0, *)) {
    rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
    rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
//  rn notification
  UNUserNotificationCenter *center=[UNUserNotificationCenter currentNotificationCenter];
  center.delegate =self;
  
  return YES;
}

//rn notification
- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler
//Called when a notification is delivered to a foreground app.
{
  completionHandler(UNNotificationPresentationOptionSound | UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionBadge);
}

**Comment by subhanK7** [comment]
> 
@DevHamzaShahid 
What about background notifications? They are also being received without sound. Do you have something for that?

**Comment by ghost** [comment]
@subhanK7, Did you found any solution for above problem ?
