### ISSUE TITLE
onNotification does not fire when app in background

### ISSUE THREAD

**Issue by samaneh-kamalian** [zo0r/react-native-push-notification#1272]
Please help me! I use your module and after tow week in a test I understood that when app is closed or in foreground everything is well but if my app is in background onNotification does not call.
i follow this post https://product.farewell.io/visible-react-native-push-notifications-that-work-on-both-ios-and-android-5e90badb4a0f 
but it can not solve my problem.

**Comment by samaneh-kamalian** [comment]
> Please help me! I use your module and after tow week in a test I understood that when app is closed or in foreground everything is well but if my app is in background onNotification does not call.
> i follow this post https://product.farewell.io/visible-react-native-push-notifications-that-work-on-both-ios-and-android-5e90badb4a0f
> but it can not solve my problem.

**Comment by samaneh-kamalian** [comment]
> Please help me! I use your module and after tow week in a test I understood that when app is closed or in foreground everything is well but if my app is in background onNotification does not call.
> i follow this post https://product.farewell.io/visible-react-native-push-notifications-that-work-on-both-ios-and-android-5e90badb4a0f
> but it can not solve my problem.

**Comment by prih** [comment]
just add this

`<activity
        android:name=".MainActivity"
        android:launchMode="singleTask"`

**Comment by prih** [comment]
and this: [https://github.com/surialabs/react-native-push-notification/commit/39d7adb](url)

will help you with abandonPermissions for android, those who made this module probably forgot about android ...

**Comment by RahulNainwal** [comment]
That's worked for me @prih.

**Comment by tolmekian1453** [comment]
@prih's solution works, thanks! I know nothing about Android, so I wonder what else changing the launchMode will affect.

**Comment by tolmekian1453** [comment]
<img width="661" alt="Screen Shot 2019-12-29 at 21 59 11" src="https://user-images.githubusercontent.com/48541605/71569806-7713ec00-2a86-11ea-8345-1e625016e0f0.png">
Something is wrong with the snippet.

**Comment by choukat** [comment]
Hello, I have the same problem, onNotification is not called when app is in foreground, this link https://github.com/surialabs/react-native-push-notification/commit/39d7adb is dead, is someone can explain me what I have to do to make it work ? 

Thx

**Comment by choukat** [comment]
Mmmh, I don't know whty, but the link works in my post... don't understand, sorry for that :).

**Comment by prih** [comment]
link fixed...

**Comment by artmerlop** [comment]
@prih I tried your solution, but didn't worked, I'm having the same issue.

**Comment by prih** [comment]
> @prih I tried your solution, but didn't worked, I'm having the same issue.

android?

**Comment by artmerlop** [comment]
@prih yes, using FCM

**Comment by artmerlop** [comment]
@prih also setting popInitialNotification to true works when app is killed but the notification never clears after reading it.

**Comment by prih** [comment]
@artmerlop hmm... did not meet such a problem.

**Comment by artmerlop** [comment]
@prih however the main issue that I can't solve is the onNotification not firing when the app is inactive but not killed.

**Comment by Dallas62** [comment]
Hi,
This issue should be fixed on `3.3.1`.

**Comment by tomthornton** [comment]
> Hi,
> This issue should be fixed on `3.3.1`.

Still having this issue on 3.3.1

**Comment by Dallas62** [comment]
> @Dallas62 
> 
> > Hi,
> 
> > This issue should be fixed on `3.3.1`.
> 
> 
> 
> Still having this issue on 3.3.1

Hi,

Can you provide more information?
- OS ?
- AndroidManifest
- Implementation ?
- reproductible example?

Note that `onNotification` will not be called if the app is killed/background. Only if the user press the notification when the app is killed/background.

**Comment by tomthornton** [comment]
@Dallas62 I'm on iOS. Works fine for local notifications, but it's not being called when the notification is pressed when the app is in the background. I'm also using react-native-firebase/messaging to get the FCM token.

**Comment by Dallas62** [comment]
For iOS, I suggest you to take a look to the iOS library, react-native/push-notification-ios which is the Library for iOS.
This library just provide a binding over iOS library.
There is some issues on the case you reported.

**Comment by tomthornton** [comment]
@Dallas62 great thank you!
