### ISSUE TITLE
How to schedule a reminder notification prior to a given time

### ISSUE THREAD

**Issue by lukecyca** [zo0r/react-native-push-notification#1273]
In my scheduling app I want to create local notifications that occur 10 minutes prior to each appointment. I am able to do it like this:

```javascript
  PushNotification.localNotificationSchedule({
    date: appt.time.subtract(10, "minutes").toDate(),
    title: appt.title,
    message: appt.description,
    playSound: true,
    soundName: "default"
  });
```

The problem is when the alert shows up on iOS, it says "now" in the top right corner. Then ten minutes later (at the actual appointment time) it says "10 minutes ago". I would like this to display the relative time of the _actual appointment_ rather than the advance notification.

Is there an API to do this? Either in this library or through Swift/Obj-C such that I could extend this library to support it?

**Comment by Duduzera1997** [comment]
Your schedule notifications in iOS working? for me not work in no way...

**Comment by lukecyca** [comment]
> Your schedule notifications in iOS working? for me not work in no way...

Yes, they are working for me. I had to Apple Push Notification entitlement to the Xcode project and call `PushNotification.configure()` like for remote push notifications.

Anyway this issue is specifically about the relative time displayed in the iOS notification UI. If you are having issues please create a separate issue.

**Comment by chrissnape** [comment]
From my knowledge there is no way to do this, the only option I would suggest is to put the time of the appointment in the notification title

**Comment by iGroza** [comment]
+
