### ISSUE TITLE
What's the difference between `localNotificationSchedule` and `scheduleLocalNotification`?

### ISSUE THREAD

**Issue by pie6k** [zo0r/react-native-push-notification#1274]
I've just wasted an hour of debugging because I was using `scheduleLocalNotification` instead of `localNotificationSchedule`...

When I started to use `localNotificationSchedule` everything worked fine.

`scheduleLocalNotification` is inside codebase and typescript definition. (https://github.com/zo0r/react-native-push-notification/blob/6a6e9514c4bdd4d7182b3805785478f61a703088/index.js#L287)

Why is this different method even there?

**Comment by nate-whil** [comment]
If you look at localNotificationSchedule https://github.com/zo0r/react-native-push-notification/blob/6a6e9514c4bdd4d7182b3805785478f61a703088/index.js#L156

You can see it does some platform specific stuff, like getting the date in the right format for each platform, before calling localNotificationSchedule with the platform specific details object. If you call localNotificationSchedule directly, the properties on your notification details object, like the date, won't be in the right format.
