### ISSUE TITLE
Invariant Violation: Native module cannot be null.

### ISSUE THREAD

**Issue by TheHunterDog** [zo0r/react-native-push-notification#1275]
I have tried the example code wont work
I tried to ```import PushNotification from 'react-native-push-notification';
``` Wont work I installed ``` npm i @react-native-community/push-notification-ios ``` and still wont work 
any help ?

**Comment by tejas77** [comment]
> I have tried the example code wont work
> I tried to `import PushNotification from 'react-native-push-notification'; ` Wont work I installed `npm i @react-native-community/push-notification-ios` and still wont work
> any help ?

I had the same Issue...
What I did is install the push-notification-ios, just like you did. Just installing won't help.

- Did a pod install (Unsure If it works or not but still do it)
- Do this, it worked: I manually linked the push-notification-ios, the instructions are given on their page.

@TheHunterDog

**Comment by olegfilimonov** [comment]
This happened to me when I updated react-native-push-notification package. To resolve this, follow install instructions at https://github.com/react-native-community/react-native-push-notification-ios, then remove this line from podfile if you have it:
`pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'`

**Comment by gie3d** [comment]
I also had the same issue and this is what I did to solve:
1. `@react-native-community/push-notification-ios` has already been installed as a dependency of `react-native-push-notification`. So you do not need to install it separately
2. Update your podfile by adding this `pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'`
3. Run `pod install` in the `ios` folder
4. In your AppDelegate.m, update this https://github.com/react-native-community/react-native-push-notification-ios#update-appdelegatem

**Comment by Return-1** [comment]
i am also experiencing this. the above solutions dont seem to work : /

**Comment by tgreco** [comment]
Close the simulator and re-run/re-build.
Worked for me.

**Comment by TheHunterDog** [comment]
> I also had the same issue and this is what I did to solve:
> 
> 1. `@react-native-community/push-notification-ios` has already been installed as a dependency of `react-native-push-notification`. So you do not need to install it separately
> 2. Update your podfile by adding this `pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'`
> 3. Run `pod install` in the `ios` folder
> 4. In your AppDelegate.m, update this https://github.com/react-native-community/react-native-push-notification-ios#update-appdelegatem

This helped me really much will close issue now Thank you so much
