### ISSUE TITLE
Does this lib support geolocation based notifications?

### ISSUE THREAD

**Issue by pie6k** [zo0r/react-native-push-notification#1276]
Seems like Apple provides proper functionality to schedule local notifications based on user localization https://developer.apple.com/documentation/usernotifications/unlocationnotificationtrigger

It would be great to schedule such notifications with react native

**Comment by mathiasmoeller** [comment]
> Seems like Apple provides proper functionality to schedule local notifications based on user localization https://developer.apple.com/documentation/usernotifications/unlocationnotificationtrigger
> 
> It would be great to schedule such notifications with react native

This might be interesting for you @pie6k : https://www.npmjs.com/package/react-native-simple-native-geofencing
