### ISSUE TITLE
onRegister returns APNS device token instead of Firebase token

### ISSUE THREAD

**Issue by tolik85** [zo0r/react-native-push-notification#1277]
Hello!

I've implemented sending push notifications to Android and iOS on my server using Firebase.
I am using this library on my client apps.
On Android - onRegister returns the FCM token as needed.
On iOS - onRegister returns APNS device token, which is useless for me, because my server sends push notifications using Firebase only for both platforms.

Any way to make this library return the FCM token for iOS as well?
Any other solution to my problem?

Any help appreciated.

Thanks!

**Comment by Linrasis** [comment]
I have install Firebase messaging pour call token..

   ```
 firebase.messaging().hasPermission().then(enabled => {
      if (enabled) {
        firebase.messaging().getToken().then(token => {
          console.log("LOG: ", token);
          this.setDevice(token);
        })
      } else {
        firebase.messaging().requestPermission().then(() => {
          console.log("L'utilisateur à la permission de recevoir des notifications");
          firebase.messaging().getToken().then(token => {
            this.setDevice(token);
          })
        }).catch(error => {
          console.log(error);
          alert("Error", error);
        });
      }
    });
```

**Comment by PerlBug** [comment]
Same issue here

**Comment by Hashir524** [comment]
Any Solution, Stuck with the same problem? @tolik85 ? @Linrasis

**Comment by Linrasis** [comment]
Add firebase to app, for get token save in database and send notification with this token

Use : 
    "@react-native-community/push-notification-ios": "^1.0.3",
    "react-native-push-notification": "^3.1.9",
    "@react-native-firebase/admob": "^6.1.0",
    "@react-native-firebase/app": "^6.1.0",
    "@react-native-firebase/messaging": "^6.1.0",
    "react-native-device-info": "^5.4.0",

react-native-device-info for get unique id phone when save token (token re-new if install app, uninstall, etc..)... 

With firebase, juste add : 
```
firebase.messaging().hasPermission().then(enabled => {
   if (enabled) {
     firebase.messaging().getToken().then(token => {
       console.log("LOG: ", token);
       this.setDevice(token);
     })
   } else {
     firebase.messaging().requestPermission().then(() => {
       console.log("L'utilisateur à la permission de recevoir des notifications");
       firebase.messaging().getToken().then(token => {
         this.setDevice(token);
       })
     }).catch(error => {
       console.log(error);
       alert("Error", error);
     });
   }
 });
```
And save token : 
```
  setDevice = (token) => {
    fetch('https://api.mydomaine.com/save/token', {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        token: token,
        platform: Platform.OS,
        deviceUnique: DeviceInfo.getUniqueId(),
        deviceModel: DeviceInfo.getDeviceId(),
        version: VersionNumber.appVersion,
        api_id: NUMBERFIREBASE_ID,
      }),
    });
  }
```

Work perfectly with lastest react-native / firebase and this package for send notifications... with firebase V6 can't send notifications.. its fore this raison i use "react-native-push-notification". My old app use firebase V5 allinclusive token+notifications..

**Comment by FullstackJack** [comment]
Same here. These notifications and messaging libraries are a mess.

**Comment by rohitkum28** [comment]
Even I am facing the same issue. How can we convert the APNS token I receive in onRegister to FCM token?

**Comment by Dallas62** [comment]
Hi,
This library doesn’t implement iOS specific, if you want FCM token for iOS, use RNFirebase.
FCM is the official messaging provider for Android.
APNS is the official messaging provider for iOS.

**Comment by mvehar** [comment]
So what is the viable solution here? INstalling Firebase library to fetch FCM token on iOS?

**Comment by irsyaadbp** [comment]
> token

Hello @Linrasis 
then to bring up a notification is it required to call a local notification when **onMessage** and **setBackgroundMessageHandler** ?
`useEffect(() => {
    const unsubscribe = messaging().onMessage(async remoteMessage => {
      //Call local notification from react-native-push-notification
    });

    return unsubscribe;
  }, []);`
  
 or is this action unnecessary?
