### ISSUE TITLE
Notifications on Android, not working, but iOS working..

### ISSUE THREAD

**Issue by Linrasis** [zo0r/react-native-push-notification#1280]
Hello, sorry my english i am french.

I have switch firebase to "react-native-push-notification" when firebase update V6 version, so.. i have try fresh install react-native and add package "react-native-push-notification", on iOS work perfectly but android, don't work and no error on build. After 2 days work on this i publish issue for help me !

I have try APK and publish on Play Store for try receive notifications...

On main.js (react-native) :
```
PushNotification.configure({
       onRegister: function(token) {
         console.log("TOKEN:", token)
       },
       onNotification: function(notification) {
         console.log("REMOTE NOTIFICATION ==>", notification)
       },
       senderID: "310638074945",
       popInitialNotification: true,
       requestPermissions: true
})
```

On AndroidManifest.xml :

```
<meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
            android:value="Reception des notifications"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
            android:value="Reception général de toutes les notifications liés à lapplication"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
            android:resource="@android:color/white"/>
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

colors.xml : 
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="white">#FFF</color>
</resources>
```

build.gradle : 
```
buildscript {
    ext {
        googlePlayServicesVersion = "+"
        firebaseVersion = "+"
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")
        classpath("com.google.gms:google-services:4.2.0")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

settings.gradle : 
```
include ':react-native-push-notification'
project(':react-native-push-notification').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-push-notification/android')
```

app/build.gradle : 
```
implementation project(':react-native-push-notification')
apply plugin: 'com.google.gms.google-services'
```

MainApplication.java : 
```
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
.....
protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          new VectorIconsPackage();
          new ReactNativePushNotificationPackage();
          new RNVersionNumberPackage();
          new RNDeviceInfo();
          return packages;
        }
```

if you see my error.. tell me please :$

**Comment by Rojdestv** [comment]
my ios isnt working but android is working...any chane you can post what you have for ios in app delegate.m please? i can post what i have for android

**Comment by Linrasis** [comment]
`/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <RNCPushNotificationIOS.h>

@import Firebase;
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"FootParis"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

// Required to register for notifications
- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings
{
  [RNCPushNotificationIOS didRegisterUserNotificationSettings:notificationSettings];
}
// Required for the register event.
- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken
{
  [RNCPushNotificationIOS didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}
// Required for the notification event. You must call the completion handler after handling the remote notification.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
  fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}
// Required for the registrationError event.
- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error
{
  [RNCPushNotificationIOS didFailToRegisterForRemoteNotificationsWithError:error];
}
// Required for the localNotification event.
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
{
  [RNCPushNotificationIOS didReceiveLocalNotification:notification];
}

@end
`

**Comment by Rojdestv** [comment]
yea i have the same on ios in appdelegate... i wonder if its because im using RN 0.61 or xcode 11.3 might be the issue...

i looked through your android code and it looks the same as i have just that firebase is added and in app/gradle i have 'compile' vs you have 'implementation'... below is what i have.

On AndroidManifest.xml :
`  <application
    android:name=".MainApplication"
    android:allowBackup="true"
       android:icon="@mipmap/logo"
    android:label="@string/app_name"
    android:largeHeap="true"
    android:usesCleartextTraffic="true">
<receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher"/>
<receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
    <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED"/>
    </intent-filter>
</receiver>
<service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>`

build.gradle :
`buildscript {
  ext {
        googlePlayServicesVersion = "16.1.0" // default: "+"
    firebaseVersion = "15.0.2"

    minSdkVersion = 21
    targetSdkVersion = 28
    compileSdkVersion = 28

    buildToolsVersion = '28.0.0'
    supportLibVersion = '28.0.0'
      kotlinVersion = '1.3.50'
    repositoryUrl = "file:${System.env.HOME}/.m2/repository/"
  }
  repositories {
    google()
    jcenter()
    maven { url 'https://dl.bintray.com/android/android-tools/' }
  }
  dependencies {
   classpath 'com.android.tools.build:gradle:3.5.1'
    classpath 'com.google.gms:google-services:4.3.3'
    classpath 'de.undercouch:gradle-download-task:3.4.3'

    // https://github.com/awslabs/aws-device-farm-gradle-plugin/releases
    classpath 'com.amazonaws:aws-devicefarm-gradle-plugin:1.3'

    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
  }
}`

settings.gradle :
`include ':react-native-push-notification'
project(':react-native-push-notification').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-push-notification/android')`

app/build.gradle :
`    compile project(':react-native-push-notification')
apply plugin: 'com.google.gms.google-services'`

MainApplication.java :
`  import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;

public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(

        new ReactNativePushNotificationPackage()`

**Comment by Linrasis** [comment]
On iOS you use : 
@react-native-community/push-notification-ios ? And Firebase token ?

In your "Capabilities" you have activate "Background Modes -> Remote notifications" and "Push Notifications" ?

Thank's code, i look this and try on real phone.

**Comment by Linrasis** [comment]
I found my real problem, when getToken firebase, is not same getToken onRegister: function(token) function, but firebase for iOS is good.

**Comment by jf-ouellette** [comment]
@Linrasis Pourriez-vous élaborer un peu sur votre dernier commentaire? Je rencontre le même problème et votre solution pourrait probablement m'aider. Merci!

**Comment by Linrasis** [comment]
En gros, j’utilise le token de Firebase pour l’enregistrer dans ma base de données et le token de onNotifications pour Android, je n’ai pas compris pourquoi ça fonctionnais pas avec Android et Firebase !

**Comment by jf-ouellette** [comment]
@Linrasis Merci! Finalement j'ai décidé d'utiliser react-native-firebase v5
