### ISSUE TITLE
Notification not open app when closed

### ISSUE THREAD

**Issue by mezalejandro** [zo0r/react-native-push-notification#1284]
When the app is closed it does not open the push.
On Android Studio i have the error:
FirebaseMessaging: Notification pending intent canceled

**Comment by ruyjfs** [comment]
Try to install this: https://github.com/react-native-community/react-native-push-notification-ios
I hame the same error and works for me.

**Comment by samaneh-kamalian** [comment]
PushNotification.popInitialNotification((notification) => {
             if (notification) { this.handleOnPushNotification(notification); }
          });

**Comment by Cassianosch** [comment]
This library is kind of useless. only receive notification when the app is open...

**Comment by ruyjfs** [comment]
> This library is kind of useless. only receive notification when the app is open...



> When the app is closed it does not open the push.
> On Android Studio i have the error:
> FirebaseMessaging: Notification pending intent canceled

I found solution for me, and on IOS, I have to configure APNS on console.firebase, and my keycode id and team id, is incorrect. I change and work 100% on IOS. For use APNS, I have to put 
	"content_available": true into my sender data for enable APNS.
