### ISSUE TITLE
Set App Badge in IOS 

### ISSUE THREAD

**Issue by gamenic-arim** [zo0r/react-native-push-notification#1286]
I have found this
-> PushNotification.setApplicationIconBadgeNumber(6);
but i want in dynamically way i.e increment & decrement of app badge while getting notification increment and after reading notification decrement of app badge
@zo0r  help please

**Comment by gamenic-suresh** [comment]
> I have found this
> -> PushNotification.setApplicationIconBadgeNumber(6);
> but i want in dynamically way i.e increment & decrement of app badge while getting notification increment and after reading notification decrement of app badge
> @zo0r help please

We have to wait for the community support on it. https://stackoverflow.com/questions/56817030/firebase-cloud-messaging-ios-badges try this too but no success.

**Comment by RediaUa** [comment]
any progress?

**Comment by gamenic-arim** [comment]
@RediaUa 
still same yet

**Comment by lukebars** [comment]
I think this should be implemented on native side maybe? Would make it a lot easier to handle badge numbering.

**Comment by Dallas62** [comment]
Hi @lukebars 
This can be done with a get/set, one of the problem would be a bad used like in render() function

**Comment by agnieszkabugla** [comment]
any ideas on how to implement this on iOS?

**Comment by Dallas62** [comment]
> any ideas on how to implement this on iOS? 

Hi,

https://github.com/zo0r/react-native-push-notification/issues/1286#issuecomment-653486321
