### ISSUE TITLE
Display notifications in foreground (android & ios)

### ISSUE THREAD

**Issue by vikjovanov** [zo0r/react-native-push-notification#1288]
Hi,
how can I enable notification display in foreground plz ?

I would like to have the notifications that are displayed both in background and foreground.

thanks,
Viktor

**Comment by makarkotlov** [comment]
You need to send silent notifications to your app with `data` property, configure local notifications and set handlers using HeadlessJS functionality. The latter isn't supported by this library so you need to integrate `react-native-firebase`. Refer to [https://invertase.io/oss/react-native-firebase/v6/messaging/quick-start](url) and [https://medium.com/@anum.amin/react-native-integrating-push-notifications-using-fcm-349fff071591](url) and [https://github.com/invertase/react-native-firebase-docs/blob/master/docs/messaging/receiving-messages.md#4-optionalandroid-only-listen-for-fcm-messages-in-the-background](url)

**Comment by eldroan** [comment]
From my understanding react-native-firebase v6 no longer supports firebase notifications

**Comment by AhmedRazaVerge** [comment]
@vikjovanov did you find issues i have same issue.
