### ISSUE TITLE
Dynamic message for local scheduled notification?

### ISSUE THREAD

**Issue by YannBrrd** [zo0r/react-native-push-notification#1289]
Hi,

Is there a way to have a function called instead of static message when planning local notifications ? I want message changed everyday...

Thanks.

**Comment by christophe13012** [comment]
Bonjour Yann, j'ai la même question, avez-vous trouvé une solution ?
merci d'avance

**Comment by Dallas62** [comment]
Hi, you will have to plan your changes in advance and plan every notification. Or push the remote notification every day.

**Comment by YannBrrd** [comment]
Hello,

Nope, mais toujours intéressé par la réponse.... 
-- 
Regards,
Yann Barraud



27 avr. 2020 à 01:05 de notifications@github.com:
