### ISSUE TITLE
Implement local notification with Background-Fetch (Fresher)

### ISSUE THREAD

**Issue by JoHnsJiss** [zo0r/react-native-push-notification#1293]
How to implement local notification(React native push notification) with background fetch ?
I just created a local notification app which will work on foreground which has both schedule notification and local notification, But i need to connect this with my database and want to get the notification both in foreground and background within an interval of 15 minutes. I had used many ways to obtain it but i couldn't get the background notification for it. Can you please help me to solve this problem....
My code is given below.
index.js ->
import BackgroundFetch from 'react-native-background-fetch';
import NotificationService from './src/Notify'; //function file of notification
.
.
.
/*rest of code of index file
*/
AppRegistry.registerComponent(appName, () => App);
let MyHeadlessTask = async () => {
/rest of code for local notification/ //I just need the correct code for the local notification here
// console and other fetch request are working
BackgroundFetch.finish();
};
BackgroundFetch.registerHeadlessTask(MyHeadlessTask);

**Comment by Zainabalhaidary** [comment]
@JoHnsJiss Did you find a solution to this please? I am trying to do the same but no luck
