### ISSUE TITLE
[iOS] onRegister not fired after user allow notification

### ISSUE THREAD

**Issue by ctopher7** [zo0r/react-native-push-notification#1294]
yes, i already allow push notification in XCode, and yes i already uploaded the .p8 key to firebase. It works on android, but whats wrong on iOS? i already did everything that push-notification-ios asked to do (install, import on appdelegate.m)

edit: YES, it is running on real device too! (iphone X ios 13.3)

**Comment by ctopher7** [comment]
Okay so i have found a way to mitigate this. After all, onRegister on iOS does not return fcm token, but APNs token. You need to use @react-native-firebase/messaging in order to get fcm token for iOS device

**Comment by lrpinto** [comment]
Hi @ctopher7 

Initially your issue was ` onRegister not fired`. I wonder what was the issue for it no firing as I am having same problem.

**Comment by lrpinto** [comment]
I just found `registerWithFCM` from messaging needs to be called and have completed first the call to `PushNotifications.configure`. Otherwise `onRegister` is not triggered.

**Comment by rizkiandrianto** [comment]
> I just found `registerWithFCM` from messaging needs to be called and have completed before the call to `PushNotifications.configure`. Otherwise `onRegister` is not triggered.

@lrpinto There's no method `registerWithFCM` in messaging. Still wont fired onRegister :(

**Comment by Dallas62** [comment]
Hi, you have to call `requestPermissions` to enable onRegister on Android and iOS.

**Comment by rizkiandrianto** [comment]
> Hi, you have to call `requestPermissions` to enable onRegister on Android and iOS.

@Dallas62 I did, Still no luck. Is it because I use Notif Service Extension, and I must put the code inside the Notif Service instead in AppDelegate?

**Comment by Dallas62** [comment]
It might be an issue on an other repository then: 
https://github.com/react-native-community/push-notification-ios/issues/106

**Comment by lrpinto** [comment]
Sorry. registerWithFCM is a wrapper method I have around it.

I meant to have written registerForRemoteNotifications.
