### ISSUE TITLE
how to build heads up Notification using local notification 

### ISSUE THREAD

**Issue by rizwan92** [zo0r/react-native-push-notification#1297]
hello, I am getting message using firebase background messages, Now I want to show heads up notification using react-native-push notification's local notification method. like the picture below when my app is foreground, background, and killed

![image](https://user-images.githubusercontent.com/19162978/73118244-a0d20d00-3f77-11ea-956e-875b6631cc6a.png)

I have read every guide in troubleshooting pages did not find any documentation for that 
I am able to build notification but not able to show it like heads up shown in the picture above.

**Comment by Chasty** [comment]
Do we have a solution on this?
