### ISSUE TITLE
Changing AndroidManifest.xml for Scheduled Notification Results an Error

### ISSUE THREAD

**Issue by Sanan4li** [zo0r/react-native-push-notification#1298]
Hi,
When I add the permission and other service tags in AndroidManifest.xml that are written on the docs for scheduled notification results an error.
If I remove all those tags my app works fine for Local Notifications but I want to show Scheduled Notifications..
* What went wrong:
A problem occurred evaluating script.
> Failed to parse React Native CLI configuration. Expected running 'npx.cmd --quiet --no-install react-native config' command from 'E:\React and React Native Practices\React\React Native\FirebaseTest' directory to output valid JSON, but it didn't. This may be caused by npx resolving to a legacy global react-native binary. Please make sure to uninstall any global 'react-native' binaries: 'npm uninstall -g react-native react-native-cli' and try again

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

React Native > 0.60
Android OS : Nougat 8.1

**Comment by SL0TR** [comment]
@Sanan4li facing the same issue, did you get a solve for this yet?

**Comment by Sanan4li** [comment]
> @Sanan4li facing the same issue, did you get a solve for this yet?

Yes I solved it...
I don't remember exactly but follow the docs carefully...
Add everything  they have said in Manifest file and ignore "Only if" written there...
Reinstall app and it will work..
If not i will share other solution
