### ISSUE TITLE
No app context when onNotification is called and app is in foreground (Android)

### ISSUE THREAD

**Issue by nealwwilliams** [zo0r/react-native-push-notification#1303]
On Android when I receive a push notification and the app is in the foreground (and the notification is not clicked on),  I want to navigate to a specific screen and update data. However, I don't have my current app context in the onNotification function--it's like my app hasn't been launched yet and none of my screens have been registered. This only happens on Android when the app is in the foreground and the notification is not clicked on. I'm using react-native-navigation. Is this expected behavior? If so, what is the best way to get a message to my app that it needs to update data when onNotification is called and my app is in the foreground, and the notification is not clicked?

**Comment by hichemBaaliYA** [comment]
The best way is to make your notification click relaunch your app, then make your onNotification stuff in the first screen, or in tour App.js for example.

**Comment by nealwwilliams** [comment]
> The best way is to make your notification click relaunch your app, then make your onNotification stuff in the first screen, or in your App.js for example.

I left out some details in my original question. I edited the original question to clarify. When I click on the notification it works ok. When I don't click on the notification, and the app is in the foreground I don't have my app's context when onNotification is called. This is when I want to update my app.

**Comment by matamicen** [comment]
> > The best way is to make your notification click relaunch your app, then make your onNotification stuff in the first screen, or in your App.js for example.
> 
> I left out some details in my original question. I edited the original question to clarify. When I click on the notification it works ok. When I don't click on the notification, and the app is in the foreground I don't have my app's context when onNotification is called. This is when I want to update my app.

We have the same issue.

**Comment by matamicen** [comment]
We can't call any redux action or anything.

**Comment by matamicen** [comment]
@hichemBaaliYA @nealwwilliams 

Solved! by changing this:

```
  //  onNotification: function(notification) {
      onNotification: (notification) => {
```

Hope it helps!
