### ISSUE TITLE
OnNotification not getting called

### ISSUE THREAD

**Issue by Srijita-Basak** [zo0r/react-native-push-notification#1304]
Hello,
I am working with scheduled local notifications and getting all the notifications in all conditions but I am in no way able to get the onNotification called when app is in foreground or background when a notification is tapped. But it is working fine when app is killed and then we tap on the notification. Also if the app is killed and we tap on one of the notifications sent through app, all the notifications get cleared. Can anyone give me an working example where all these problems don't arise? Basically I want to tap on a notification be the app foreground or background or killed and I want to navigate to a screen. Thanks.

**Comment by krutik2403** [comment]
Same issue, i am using ` "react-native-push-notification": "^3.1.9"`. I am using `localNotification`. Notification appears but `onNotification` function isn't invoking.

**Comment by Srijita-Basak** [comment]
> Same issue, i am using ` "react-native-push-notification": "^3.1.9"`. I am using `localNotification`. Notification appears but `onNotification` function isn't invoking.

Am using the same version . But I have also downgraded it to 3.1.2/3.1.1  where few said it was working. But it's not. Am stuck on these since the last two days .

**Comment by darshanksexathought** [comment]
same issue here onNotification is not getting called on click of notification

**Comment by nlively** [comment]
Same here

**Comment by sergiulucaci** [comment]
Same, notification appears but `onNotification` method is not called.

**Comment by arslansajid** [comment]
Add this to AndroidManifest.xml

<activity
        android:name=".MainActivity"
        android:launchMode="singleTask"

This worked for me.

**Comment by sergiulucaci** [comment]
> Add this to AndroidManifest.xml
> 
> <activity
> android:name=".MainActivity"
> android:launchMode="singleTask"
> 
> This worked for me.

On Android works for me too, is the iOS that isn't working

**Comment by darshanksexathought** [comment]
Thanks well try this

**Comment by nicpro85** [comment]
on iOS as it uses @react-native-community/push-notification-ios you must add in your Xcode project in the appdelelgate 

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
  
  completionHandler(UIBackgroundFetchResultNoData);
}

**Comment by CrnogoracIvan** [comment]
@nicpro85 , I have same issue, and I added this part in AppDelegate.m

**Comment by xoapit** [comment]
> completionHandler(UIBackgroundFetchResultNoData);

I added a more line to complete as your suggestion: completionHandler(UIBackgroundFetchResultNoData);. It is working now. The event is fired when receiving notification in foreground mode. Thanks

**Comment by dgana** [comment]
It's not working for me in iOS 13.4 device ```completionHandler(UIBackgroundFetchResultNoData);```. only works in background. any idea?

```
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-push-notification": "^3.1.9",
"@react-native-community/push-notification-ios": "^1.0.7",
```

**Comment by MahmudHasanMenon** [comment]
> Add this to AndroidManifest.xml
> 
> <activity
> android:name=".MainActivity"
> android:launchMode="singleTask"
> 
> This worked for me.

This also worked for me.
