### ISSUE TITLE
iOS remote push notification?

### ISSUE THREAD

**Issue by rgetValue** [zo0r/react-native-push-notification#1305]
Hello guys!

I am using Firebase Cloud Messaging.
On Android everything works perfect.

But on iOS nothing works (i mean remotely notification).
**Do i need install "Firebase" package for iOS?**

**Comment by SamiChab** [comment]
Same here!

**Comment by Meph1k** [comment]
You need to use APNs for iOS ;)

**Comment by eldroan** [comment]
@Meph1k I'm looking at the apple developer docs for that, do I need to implement them natively or do they work with this library?

**Comment by rgetValue** [comment]
I use `react-native-firebase` – and now my app crashes ://

**Comment by Jonovono** [comment]
@rgetValue did you solve? I am seeing something similar?

**Comment by rgetValue** [comment]
@Jonovono nope :(((

**Comment by eldroan** [comment]
react-native-firebase deprecated notifications, you can go back to version 5 but having old libraries doesn't sound well. I've ended up using https://github.com/wix/react-native-notifications but I've haven't got around to test iOS notifications since I don't have an apple paid developer account yet to set things up.

**Comment by rgetValue** [comment]
@eldroan In `react-native-firebase` i'm using `onMessage` method.
When this method fired up – i'm generate local notification.

But it's crash my app :///

**Comment by geiz** [comment]
I found a solution by revisiting depreciated documents.
[https://reactnative.dev/docs/pushnotificationios](https://reactnative.dev/docs/pushnotificationios)

Put this into your AppDelegte.m in addition to everything else in the official document [https://github.com/react-native-community/react-native-push-notification-ios](https://github.com/react-native-community/react-native-push-notification-ios)
`
#import <UserNotifications/UserNotifications.h>

...
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  ...
  // Define UNUserNotificationCenter
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;

  return YES;
}
`

**Comment by Mavenic** [comment]
All configurations are done correctly, but still not working

**Comment by Gabsys** [comment]
> All configurations are done correctly, but still not working

Same :/

**Comment by Dallas62** [comment]
> > All configurations are done correctly, but still not working
> 
> 
> 
> Same :/ 

Sorry for that but this library does not implement specific iOS code, so I think you can find a solution in rn-push-notification-ios.

**Comment by Aayushi1301** [comment]
Still same issue. I tried cloning the example project and followed installation steps in https://github.com/react-native-community/push-notification-ios but I am not able to receive remote notifications from firebase.
