### ISSUE TITLE
BUG: ANDROID GRADLE FAILS (/january.ai/januarychallenge/android)

### ISSUE THREAD

**Issue by hzeraat2** [zo0r/react-native-push-notification#1308]
This is causing Android build to fail: 

https://github.com/zo0r/react-native-push-notification/blob/e0cf22247f6c091e4a45d70d5dfe79258318580d/android/react-native-push-notification.iml#L2

**Comment by shahzore-qureshi** [comment]
Try running `npx jetify` at the root of the React Native project.

**Comment by Dallas62** [comment]
It's now removed 😉
