### ISSUE TITLE
should onRegister: function(token)  need to be called every time app loaded

### ISSUE THREAD

**Issue by desis123** [zo0r/react-native-push-notification#1309]
This is not an issue rather a question , I tried to find this answer on google, but didnt get the right answer I am looking for. 

My first question is how long token would be valid for android . 

and second question is  should I call 

onRegister: function(token) {
        console.log('TOKEN:', token)

//saving the token in server ...
      },

to  generate token ... every time app is opened ?.. if not... how I will limit it ?

**Comment by Psiiirus** [comment]
I'm doing it every app load....but not sure if this is correct either.
