### ISSUE TITLE
Local Notification Sound

### ISSUE THREAD

**Issue by hamza-ameer** [zo0r/react-native-push-notification#1313]
Can anyone help?
React Native push local notification Sound repeats until app close.
Canceling the Notification did't stop the sound. Sound keeps repeating in background. What is the problem? Need your help.

**Comment by hamza-ameer** [comment]
here is my code


  PushNotification.localNotificationSchedule({
      //... You can use all the options from localNotifications
     
        /* Android Only Properties */
        id: '123', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        ticker: "My Notification Ticker", // (optional)
        autoCancel: true, // (optional) default: true
        largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
        smallIcon: "ic_launcher", // (optional) default: "ic_notification" with fallback for "ic_launcher"
        bigText: "Tralert Notification", // (optional) default: "message" prop
        subText: "You Reached Your Destination", // (optional) default: none
        color: "red", // (optional) default: system default
        vibrate: true, // (optional) default: true
        vibration: 3000, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
        tag: 'some_tag', // (optional) add tag to message
        group: "group", // (optional) add group to message
        ongoing: true, // (optional) set whether this is an "ongoing" notification
        priority: "max", // (optional) set notification priority, default: high
        visibility: "private", // (optional) set notification visibility, default: private
        importance: "max", // (optional) set notification importance, default: high
    
        /* iOS only properties */
        category: 'alert',
        userInfo: { id: '123' },
    

        

        /* iOS and Android properties */
        title: "Tralert", // (optional)
        message: "You Reached Your Destination", // (required)
        playSound: false, // (optional) default: true
       //soundName: 'alert.mp3', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default alarm sound will be played)
        repeatType: 'time',
        repeatTime:run_intervl, // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
        actions: '["Keep", "Cancel"]',  // (Android only) See the doc for notification actions to know more
         
    
    
      date: new Date(Date.now() + timer) // in 60 secs
    });

**Comment by kdpadhiyar** [comment]
https://github.com/zo0r/react-native-push-notification/issues/1423#issue-614600690

lol his own example is not plying sound
@zo0r @hamza-ameer

**Comment by kdpadhiyar** [comment]
@hamza-ameer  may be issue in your code check repeat and interval of your code and given time.
make sure to share proper code
