### ISSUE TITLE
where to handle onRefreshToken functionality of firebase v6 in react native push notifications ?

### ISSUE THREAD

**Issue by harsh-syook** [zo0r/react-native-push-notification#1314]
i tried for hours to integrate the react native firebase v6 with react native push notifications to leverage the push notifications and finally i was able to get push notifications on my real android device. :)
now i am wondering where to handle onRefreshToken in react native push notifications library cos there is no method for that only onregister is there. if anyone knows about where can i handle refreshtoken it would be very helpful , as i want token as soon as it gets refreshed and send it to my backend.

**Comment by tidianeb5** [comment]
i have the same issues

**Comment by dgana** [comment]
@harsh-syook I have the same issues also. I just want to ask did your onRegister function hit again as the option params inside PushNotification.configure?. And where can i get the current token of FCM. I have tried PushNotification.unregister() and PushNotification.abandonPermissions() but it seems there is no luck. Currently my app doesn't receive push notification using https://www.vysor.io/

react: 16.9.5
react-native: 0.61.5
react-native-push-notification: 3.1.9

**Comment by harsh-syook** [comment]
@dgana the FCM token you'll get from onRegister only that token u can use to send PNs. my onRegister works and it gives token. u need to check ur xml files n all
