### ISSUE TITLE
🔥 App crashes / iOS & Android / Backend message object with notificaiton key

### ISSUE THREAD

**Issue by rgetValue** [zo0r/react-native-push-notification#1317]
Hello.

When server sends push notification like this:
![image](https://user-images.githubusercontent.com/5750897/74985933-2941b180-5441-11ea-8a08-e5db130f0a74.png)

Apps (iOS & Android) crashes :(((

Only works with this code (and only on Android version):
![image](https://user-images.githubusercontent.com/5750897/74986005-5ee69a80-5441-11ea-94b2-05d37e4328d6.png)
For iOS app this push notification doesn't have title and body.

How can i fix this?

**Comment by Dallas62** [comment]
Hi @rgetValue 
Did you try to define an empty `data` field ?
`data: {},`
with the notification field ?
