### ISSUE TITLE
When app is in closed state(removed from background) and notification is received, the onNotification function is not triggered.

### ISSUE THREAD

**Issue by OnlineGoa** [zo0r/react-native-push-notification#1319]
When app is in closed state(removed from background) and notification is received, the **onNotification**  function is not triggered.

**Comment by nicpro85** [comment]
how did you manage to have the on notification be triggered when app is in background?

**Comment by Psiiirus** [comment]
@nicpro85  good question looking for exactly that behavior to track conversion (notfication received -> notification clicked)

**Comment by nicpro85** [comment]
I managed to be successful by implement methods in the appdelegate.m file as requested by the react-native-notification-iOS library because this repo use the the other one for the iOS part.

**Comment by Psiiirus** [comment]
@nicpro85  so have a working app which receives a callback if an app gets a new notification in the background?

**Comment by mtshv** [comment]
@nicpro85 so can you process an iOS notification is the app is closed (removed from the background)?

**Comment by nicpro85** [comment]
I haven’t tried but maybe it worked. Natively it’s another process that is triggered so I don’t know the implementation of this module

**Comment by nicpro85** [comment]
Maybe in the app did finishing launching if there is a notification payload in the options you may call the same react native callback than in the method called when the app is in the background

**Comment by raldred** [comment]
Same issue android 0.63.3

onNotification is not called on Android when app is closed, removed from background.
It is also not triggered when notification is tapped on the user.

Android
Foreground: ✅
Background: ✅
Closed: ❌
Opened from background: ✅
Opened from closed: ❌

iOS
Foreground: ✅
Background: ✅
Closed: ✅
Opened from background: ✅
Opened from closed: ✅

**Comment by Dallas62** [comment]
Hi,

You probably have a splashscreen which intercept the event.
Take a look in issues for a solution.

Regards

**Comment by raldred** [comment]
Thanks @Dallas62 
Yes we're using react native splash screen.
Does that interfere?
Calling configure before anything else.

**Comment by Dallas62** [comment]
https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-421537284

**Comment by raldred** [comment]
@Dallas62 thank you so much! That explains why we were having issues with detox too!!!
