### ISSUE TITLE
Not compatible RN 0.29+

### ISSUE THREAD

**Issue by drpiou** [zo0r/react-native-push-notification#132]
Android breaking changes are not applied, I can't compile anymore my RN project.

**Comment by stereodenis** [comment]
@zo0r what do you think?
```
Project/android/app/src/main/java/com/nptv/wtcceurosport/MainApplication.java:37: error: constructor ReactNativePushNotificationPackage in class ReactNativePushNotificationPackage cannot be applied to given types;
      mReactNativePushNotificationPackage = new ReactNativePushNotificationPackage(this);
                                            ^
  required: Activity
  found: <anonymous ReactNativeHost>
  reason: actual argument <anonymous ReactNativeHost> cannot be converted to Activity by method invocation conversion
Project/android/app/src/main/java/com/nptv/wtcceurosport/MainApplication.java:57: error: cannot find symbol
    super.onNewIntent(intent);
         ^
  symbol: method onNewIntent(Intent)
```

**Comment by stereodenis** [comment]
example of migration https://github.com/yamill/react-native-orientation/pull/85

**Comment by clintonjrobinson** [comment]
I did a quick fix to get this working again in this PR, it worked well for me. #134

**Comment by Streemo** [comment]
I'm getting this with react-native-push-notification@2.0.1, react-native@0.28.0. Apparently not calling the constructor on `this` solved the problem.

`mReactNativePushNotificationPackage = new ReactNativePushNotificationPackage(this)`
becomes
`mReactNativePushNotificationPackage = new ReactNativePushNotificationPackage()`
