### ISSUE TITLE
react-native-push-notification not working as expected on different Android versions and devices.

### ISSUE THREAD

**Issue by OnlineGoa** [zo0r/react-native-push-notification#1320]
Android 9.1.1 [MI] --> When the app is removed from the background, the notification sent for the first time is not received but on the second try, the notification was received(app removed from background).   
Android 8.1.0 [10orE] --> App crashed on receiving notification.

**Comment by ursNj** [comment]
same here :(

**Comment by radud** [comment]
Android 9.1.0 App goes to background when notification is received? Am I missing some configuration?

Many thanks, 
Radu

**Comment by arifinoid** [comment]
same here
