### ISSUE TITLE
No support for React Native Auto linking

### ISSUE THREAD

**Issue by tattivitorino** [zo0r/react-native-push-notification#1321]
No support for RN auto linking yet?

I ran pod install nothing happened no libs added.
Then I ran react-native link ..... it linked only Android
Then I installed the react community push package and ran pod install 

Is this the right way to set up?

**Comment by ovidiu-balau** [comment]
Can confirm, it doesn't link for iOS.

**Comment by Nextt1** [comment]
Yep. Not working for iOS. I checked the manual installation and ended up installing`push-notification-ios` and making changes in delegate files. Is this how it should work?
