### ISSUE TITLE
How to navigate to a particular page on opening an notification?

### ISSUE THREAD

**Issue by jaipatel01** [zo0r/react-native-push-notification#1324]
OnNotification is called whenever an notification is received or opened, **want a function to be called only when an notification is opened(i.e, tapped/on-click) .**
In the below code what happens is when an notification is received while the app is in foreground it directly navigates to 'Somepage', even if the user has not opened the notification.

PushNotification.configure({
    onNotification: function (notification) {
  ...
       navigationServices.navigate('SomePage')
    },
  })

**Comment by Psiiirus** [comment]
Hi @jaipatel01 ,
interesting I got the problem that my script isn't triggering if the notification is "just" received my onNotifcation only if the user user is clicking the notification.

But this maybe helps you
```

PushNotification.configure({
  onNotification: function (notification) {
  ...
    if(notification.userInteraction) {
      navigationServices.navigate('SomePage')
    }

  },
})

```

**Comment by jaipatel01** [comment]
Thanks Psiirus, 
I am able to navigate on opening the notification when the app is in foreground with your solution, but not able to do the same when the app is in background.
**How do i navigate to 'SomePage' on opening the notification when the app is in background?**

**Comment by Psiiirus** [comment]
I'm sorry but i think this is related to your navigation solution, I am using react navigation together with Redux and it works just fine.
Maybe store your "view open"-action in some kind of temporary handler until the app is loaded up completely and then call the "view open"-action. -> BUT this could be the complete wrong way maybe try to find some solution related to your specific navigation solution.

**Comment by fspider** [comment]
I also have faced problem with navigating to another screen.

This is main component.
```
import RemotePushController from './src/services/RemotePushController';

class Main extends Component {
  render() {
    return (
      <Provider theme={theme}>
        <App />
        <RemotePushController />
      </Provider>
    );
  }
```

RemotePushController.tsx
```
import React, { memo, useEffect } from 'react';
import PushNotification from 'react-native-push-notification';
import { senderID } from '../core/const';
import { AsyncStorage } from 'react-native';
import { connect } from 'react-redux';
import { change_save_data } from '../core/reducer';

const RemotePushController = ({ pData, changeSaveData }) => {
    const processNotification = (notification) => {
      try {
	   /// PROBLEM IS HERE
	   /// pData comes from redux, but i can not get pData. It outputs empty string.
	   /// But very some times, it works.
	    console.log(pData);
        const data = JSON.parse(notification.message_data);
        const message_id = notification.message_id;

      } catch (err) {
      }
    };


  useEffect(() => {
    PushNotification.configure({
      onRegister: async function(token) {
        try {
          await AsyncStorage.setItem('fmsToken', token.token);
          const fmsToken = (await AsyncStorage.getItem('fmsToken')) || '';
        } catch (error) {
        }
      },
      onNotification: function(notification) {
        console.log('REMOTE NOTIFICATION ==>', notification);
        processNotification(notification);
      },

      senderID: senderID,
      popInitialNotification: true,
      requestPermissions: true,
    });
  }, []);

  return null;
};

const mapStateToProps = (state) => ({
  pData: state.data,
});

const mapDispatchToProps = (dispatch) => ({
  changeSaveData: (...arg) => {
    dispatch(change_save_data(...arg));
  },
});
export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(RemotePushController);
```

**Comment by faizazafar** [comment]
configure = () =>
    PushNotification.configure({
      onNotification: this.handleNotification, //(...all) => console.log(...all, 'all'),
    });

the problem i am facing is that on forrground as soon as i receive the notification it navigates it to the respective screen. I wanted the navigation when the user press on nottification in foreground.

P.S it is worrking fine for background
