### ISSUE TITLE
Android grant permissions for remote Push Notification

### ISSUE THREAD

**Issue by rgetValue** [zo0r/react-native-push-notification#1325]
Hello.
How do I grant permissions for Push Notification?

What have I tried?

```
PushNotification.configure({
  ...
  requestPermissions: true
});
```

and

```
PushNotification.configure({
  ...
  requestPermissions: false
});
```

with (later in code)

```
PushNotification.requestPermissions();
```

**In both cases, token was generated.**

But I can't receive Push Notification until I go into the settings and grant permission for remote Push Notification.
It's on **Xiaomi**.

On **Lenovo** tablet – it's works.
**But i still doesn't have modal with ability to grant permissions for Push Notificaiton.**

**Comment by creditcoder** [comment]
Same case for me. I think it's related also the android version.

**Comment by hieuptit93** [comment]
I was the same

**Comment by Dallas62** [comment]
Hi @rgetValue 
Maybe some specific value in to add in `AndroidManifest` as permissions
