### ISSUE TITLE
BUG: iOS badge – 10

### ISSUE THREAD

**Issue by rgetValue** [zo0r/react-native-push-notification#1328]
Hello.

When i add this package to my project, I get 10 in badge area.
But i do not anything.

How to fix?

**Comment by arthedza** [comment]
> Hello.
> 
> When i add this package to my project, I get 10 in badge area.
> But i do not anything.
> 
> How to fix?

Hello! I have a similar problem. Notifications are increasing a counter by a number multiple of 10.
For example 1 notification -- 10 in a badge, 2 notifications -- 20 and so on

**Comment by Dallas62** [comment]
Hi,
Can you provide more information ?
there is a number parameter, did you set a value to it ?
Can you give an example to reproduce the issue ?
