### ISSUE TITLE
PushNotification.configure function is not called when the app is in background?

### ISSUE THREAD

**Issue by jaipatel01** [zo0r/react-native-push-notification#1332]
**Have written the PushNotification.configure function in App.js which is not called when the app is in background**, but works fine when the app is in foreground or the app is closed/killed.

const App = () => {
  PushNotification.configure({
    onNotification: async function (notification) {
      if (AppState.currentState == "active") {
       ......
      }
      else if (AppState.currentState == "background") {
      .......
      }
      else {
       .......
}
})

  useEffect(() => {
  ......
  }, []);

}

**Comment by fattomhk** [comment]
Are you using data message on Android?
