### ISSUE TITLE
Device token not register on android 8.0.1

### ISSUE THREAD

**Issue by anuj-njoshi** [zo0r/react-native-push-notification#1334]
Device specification  LG Device Details > LG Stylo 4, Android 8.0.1 
Particular this device cannot get the device token from onRegister

**Comment by Dallas62** [comment]
Hi @anuj-njoshi 
Can you check the PR #1355 ?
Thanks!

**Comment by Dallas62** [comment]
The PR #1355 is merged into mater, and will be released ASAP.

**Comment by Dallas62** [comment]
A new version is available, feel free to reopen if not fixed 😉
