### ISSUE TITLE
Option to disable foreground

### ISSUE THREAD

**Issue by borm** [zo0r/react-native-push-notification#1338]
[RNPushNotificationListenerService.java](https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java#L135)

```
if (BuildConfig.disableForeground && !isForeground) {
  pushNotificationHelper.sendToNotificationCentre(bundle);
}
```

but in this case notifications not received in background mode also

**Comment by Dallas62** [comment]
Hi @borm 
I implemented some thing like this in `3.4.0`.
