### ISSUE TITLE
how not to disappear push notification when gesture sideways

### ISSUE THREAD

**Issue by daheeahn** [zo0r/react-native-push-notification#1342]
If I click the push notification and it does not disappear, I can control it with `autoCancel`. But how do I make sure that I don't disappear even if I gesture sideways? Is there a function like attached gif? (That app is not my app. another app) 

![IMG_0050 (1) (1)](https://user-images.githubusercontent.com/38369729/76804745-66227d80-6820-11ea-9eff-8d327c8f0c9b.gif)

**Comment by kelokchan** [comment]
Try setting your `ongoing: true` to your notification

**Comment by Dallas62** [comment]
Hi @daheeahn 
Does the solution provided by @kelokchan work ?
