### ISSUE TITLE
Error with Hermes

### ISSUE THREAD

**Issue by marcinkieruzel** [zo0r/react-native-push-notification#1343]
Is this package working with Hermes on Android?

![image (1)](https://user-images.githubusercontent.com/25027015/77065161-0fb06d00-69e1-11ea-8731-c394a27b398e.png)

**Comment by krudos** [comment]
i had a similar issue but was because i used .flat() an that array function is not implemented on react native

**Comment by Dallas62** [comment]
Hi @marcinkieruzel

Do you reproduce this bug on the example application ?

Thanks!
