### ISSUE TITLE
Notification does not disappear with tap on action buttons

### ISSUE THREAD

**Issue by irondsd** [zo0r/react-native-push-notification#1344]
When I tap on notification anywhere except action buttons, onNotification gets called and the notification disappears properly. If I tap on any of the action buttons, onNotification gets called and app opens, but the notification stays in notification bar. Is it possible to change that? I need notification to disappear after that like the normal tap.

I tried cancelling notification in onNotification, but it still stays in notification bar. It looks like `PushNotification.cancelLocalNotifications({ id: id.toString() })` only works before notification actually fires. 

I understand that this library is not maintained anymore. But maybe some of your could help me. Any ideas how to fix this?

Just in case, the code:
```
export function setupNotifications() {
    console.log('notifications service initiated')
    PushNotification.configure({
        onNotification: function(notification) {
            onNotificationOpened(notification)
        },
        permissions: {
            alert: true,
            badge: true,
            sound: true,
        },
        popInitialNotification: true,
        requestPermissions: true,
    })
}

export function scheduleNotification(id, title, message, dateTime) {
    PushNotification.localNotificationSchedule({
        id: id.toString(),
        title: strings[title],
        message: message,
        vibrate: true,
        date: dateTime,
        largeIcon: 'app_icon', // (optional) default: "ic_launcher"
        smallIcon: 'app_icon', // (optional) default: "ic_notification" with fallback for "ic_launcher"
        actions: `["${strings.Start}", "${strings.RemindLater}"]`,
        playSound: true, // (optional) default: true
        ongoing: false, // (optional) set whether this is an "ongoing" notification
    })
}

export function cancelLocalNotification(id) {
    console.log('cancelled notification', id)
    PushNotification.cancelLocalNotifications({ id: id.toString() })
}

function onNotificationOpened(notification) {
    if (notification.action === strings.RemindLater) {
        ...
    } else {
       ...
    }
}
```

**Comment by irondsd** [comment]
I found the solution. Just in case it helps anyone:

To cancel future notification you should use `PushNotification.cancelLocalNotifications({ id: id.toString() })`
To cancel already delivered notification, use `PushNotification.clearLocalNotification(id)`

**Comment by DrSchmurge** [comment]
> I found the solution. Just in case it helps anyone:
> 
> To cancel future notification you should use `PushNotification.cancelLocalNotifications({ id: id.toString() })`
> To cancel already delivered notification, use `PushNotification.clearLocalNotification(id)`

Hi, id should be integer, right ? Not working for me =(

**Comment by dpaulino** [comment]
@irondsd 
> To cancel already delivered notification, use PushNotification.clearLocalNotification(id)

I'm trying to use this but it looks like `clearLocalNotification` does not exist for me. What package version are you using?

**Comment by jacksontrieu** [comment]
> Hi, id should be integer, right ? Not working for me =(

@DrSchmurge try the solution I posted in https://github.com/zo0r/react-native-push-notification/issues/1207#issuecomment-647127881, it may fix your issue
