### ISSUE TITLE
A replacement for this unmaintained package 🚧

### ISSUE THREAD

**Issue by ilyagru** [zo0r/react-native-push-notification#1349]
Guys, please recommend a good package for Push notifications for RN instead of this one. It seems this one is abandoned, so many issues and no input at all.

**Comment by Priceincoding** [comment]
https://github.com/wix/react-native-notifications looks good, well maintained and well documented, with a lot of useful resources/tutorials on google

**Comment by sregg** [comment]
react-native-notifications doesn't seem to provide location notifications for Android :(
I'm also looking for a (local) notification package after Invertase stopped providing one in react-native-firebase v6...

**Comment by euharrison** [comment]
I didn't finished my test yet, but it looks like react-native-notifications supports local notifications
https://github.com/wix/react-native-notifications/issues/19

**Comment by Dallas62** [comment]
Hi!

React-native-notifications is great but there is also some features not yet implemented.
That why I requested maintainer access to the owner of this project and it’s ok. I think this library is great too and must continue to live.
BUT,
I will not be able to manage this project alone.
If you are interested by this project, feel free to make some PRs or help me on current issues by marking duplicate issues, questions,... and tagging me. That would be great!

If you would like to be a maintainer too, do not hesitate to mention it in the issue.

Best regards,

**Comment by Zaporozhec7** [comment]
Thank you very much @Dallas62 for returning this project to life. Would be great make new releases based on new commits, because latest release already 80 commits behind master

**Comment by Dallas62** [comment]
Hi @Zaporozhec7 
I will ask the owner to get a CI to be able to release the package on NPM.
I can't release the library for now, I will keep this issue up to date.
Also, it would be great to get more maintainers on this project 😃

**Comment by Dallas62** [comment]
Hi!
I should be able to publish new versions on NPM. Jorge adds me as a maintainer on NPM.
I will retest the version on Master then release it if everthing is fine.
It would be great for future versions to define a ROADMAP and a strategy for the management of the project; If someone has experience on that I would be pleased to look at this.

**Comment by stephanoparaskeva** [comment]
> Hi!
> I should be able to publish new versions on NPM. Jorge adds me as a maintainer on NPM.
> I will retest the version on Master then release it if everthing is fine.
> It would be great for future versions to define a ROADMAP and a strategy for the management of the project; If someone has experience on that I would be pleased to look at this.

Thanks for the efforts man!
