### ISSUE TITLE
How to get android device token

### ISSUE THREAD

**Issue by paveytel** [zo0r/react-native-push-notification#135]
I am not sure how to retrieve a user's android device token. I did all the solutions on the closed issues, but still cant get a device token. I configured the sender id to be the project number on google api console. I call PushNotificationAndroid.requestPermissions() right after PushNotificationAndroid.configure({ ... }); 

Anyone know what I might be missing? 

Thanks

**Comment by Brendtron5000** [comment]
Are you testing this on an emulator? If so, which CPU/ABI  are you using? I was using "Intel Atom (x86)" and couldn't get it output the device token. I switched the CPU/ABI to "Google APIs Intel Atom (x86)" and was able to register the device and `console.log` it in `onRegister`.

**Comment by gopidon** [comment]
SenderId must be the Project number and NOT Project ID. The token is available in the onRegister callback. token is an object. u are looking for token.token. Hope this helps!

**Comment by paveytel** [comment]
Hi @gopidon , yes i am using the project number and not project ID as the sender ID.

**Comment by samin** [comment]
Any news on this, not registering here too, with sender ID as well

**Comment by samin** [comment]
We figured it out, `requestPermissions` has to be true for Android, even though comments on readme works only for iOS

**Comment by zo0r** [comment]
@samin thanks, **README** updated
https://github.com/zo0r/react-native-push-notification/commit/c7ab7cd84ea19e42047379aefaf568bb16a81936
