### ISSUE TITLE
Could not find com.google.android.gms:play-services-vision:16.1.0

### ISSUE THREAD

**Issue by Josema** [zo0r/react-native-push-notification#1350]
```
What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.      
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.gms:play-services-vision:16.1.0. 
     Searched in the following locations:
```

The README example says: `googlePlayServicesVersion = "<Your play services version>" // default: "+"`

But does not explain how do I get my version which is mandatory to get token on `onRegister` event. How do I get firebaseVersion and googlePlayServicesVersion?

---
More people are having this issue
https://github.com/zo0r/react-native-push-notification/issues/1109#issuecomment-590253924

**Comment by omaar** [comment]
The documentation is wrong
Should be: 

`googlePlayServicesVersion = "16.0.0" // default: "+"`

**Comment by Josema** [comment]
Same
```
 > Could not find com.google.android.gms:play-services-vision:16.0.0
```

**Comment by omaar** [comment]
Could you share your `build.gradle` file and `app/build.gradle`

`build.gradle` should look like this
`buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.0.0" // default: "+"
        firebaseVersion = "17.3.4" // default: "+"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:3.5.2')

        // Firebase message
        classpath 'com.google.gms:google-services:4.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}`

and `app/build.gradle` should look like this

`dependencies {
  ...
  // Firebase message
    implementation 'com.google.firebase:firebase-core:17.0.0'
    implementation 'com.google.firebase:firebase-messaging:19.0.0'
}`
 and at EOF
`apply plugin: 'com.google.gms.google-services'`

**Comment by Josema** [comment]
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28

        googlePlayServicesVersion = "16.0.0" // default: "+"
        firebaseVersion = "17.6.0" // default: "+"
    }

    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")
        classpath 'com.google.gms:google-services:4.3.3'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

app/build.gradle
```

dependencies {
    implementation project(':react-native-background-task')
    implementation project(':react-native-camera')
    implementation project(':react-native-user-agent')
    implementation project(':react-native-randombytes')
    implementation project(':react-native-local-auth')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-push-notification')
    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    
    // JSC from node_modules
    if (useIntlJsc) {
        implementation 'org.webkit:android-jsc-intl:+'
    } else {
        implementation 'org.webkit:android-jsc:+'
    }
}

apply plugin: 'com.google.gms.google-services'
```

**Comment by omaar** [comment]
Try to substitute the following line 

```
buildscript {
    ext {
       ...
       googlePlayServicesVersion = "17.0.2"
    }
}
```

**Comment by omaar** [comment]
Or maybe your problem is not with this library. Please read this issue for more info.

https://github.com/react-native-community/react-native-camera/issues/2641

**Comment by ambessh** [comment]
change google play services version in build gradle (root level)
   googlePlayServicesVersion = " 11.8.0"
