### ISSUE TITLE
Please Can i specify a Sound from somewhere else other than res/raw ?

### ISSUE THREAD

**Issue by allindeveloper** [zo0r/react-native-push-notification#1353]
scheduleNotif(sound,date,title,message,color,subText,bigText) {
    this.lastId++;
    PushNotification.localNotificationSchedule({
      date: new Date(Date.now() + (5 * 1000)), // in 10 secs
      //date:date,
      /* Android Only Properties */
      id: ''+this.lastId, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      ticker: "My Notification Ticker", // (optional)
      autoCancel: true, // (optional) default: true
      largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
      smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
      bigText: bigText, // (optional) default: "message" prop
      subText: subText, // (optional) default: none
      color: color, // (optional) default: system default
      vibrate: true, // (optional) default: true
      vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
      tag: 'some_tag', // (optional) add tag to message
      group: "group", // (optional) add group to message
      ongoing: false, // (optional) set whether this is an "ongoing" notification
      /* iOS only properties */
      alertAction: 'view', // (optional) default: view
      category: null, // (optional) default: null
      userInfo: null, // (optional) default: null (object containing additional notification data)
      /* iOS and Android properties */
      title: title, // (optional)
      message: "My Notification Message", // (required)
      playSound: true, // (optional) default: true
      soundName: sound, // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
    });

**Comment by ibunubi** [comment]
in this version you can't customise the notification sound for android 8+.
i just resolve my custom sound issue with this fork from [cookienawer](https://github.com/cookienawer/react-native-push-notification)

**Comment by allindeveloper** [comment]
oh okay, i just check the repo, but i can't find what you were referring to,
Can i pass a remote url or a uri to the sound ?

**Comment by allindeveloper** [comment]
Okay i just had a proper look at the commit diff, i think i'm to specify the sound uri?
How will that work for ios please ?
