### ISSUE TITLE
localNotification() does not work for IOS

### ISSUE THREAD

**Issue by chenop** [zo0r/react-native-push-notification#1359]
RN: 0.61.2
"react-native-push-notification": "^3.1.9"

Trying to invoke:
`PushNotification.localNotification({
		/* Android Only Properties */
		visibility: "public",
		largeIcon: "ic_notification",
		imageUrl,

		/* iOS and Android properties */
		title,
		message, // (required)
		actions: '["Close"]',
	});
`
Does not display notification on taskbar for IOS, Android work as expected.
What am I doing wrong?

**Comment by kyytiPetteri** [comment]
Getting same error when iOS app is on the foreground. When backgrounded shows notification nicely

**Comment by chenop** [comment]
@kyytiPetteri I think this is a different issue.
Manage to add solve it - I didn't upload APNs file to firebase console. Once I did everything started to work.

**Comment by oliver-ultyresults** [comment]
@chenop did you get a solve for this?  I'm finding the same problem
_(rn 0.61.3, react-native-push-notifications ^3.1.9, , & @react-native-community/PushNotificationsIOS: 1.1.1)_

When app in background, notification pops-up fine on Android.  But not on iOS.

I'm just interested in firing a local notification, rather than a push-from-remote notification, so wasn't planning on using firebase/anything else remote (though I do use firebase for analytics/crashlytics).

**Comment by tomthornton** [comment]
I'm having this same problem. I'm using react-native-firebase-messaging.

**Comment by chenop** [comment]
@tomthornton @oliver-ultyresults 
I personally didn't [upload the APNs file to firebase console](https://rnfirebase.io/messaging/usage/ios-setup) - once I did that it started to work.
Also debug your code and see if do you get the notification via onMessage hook:
`messaging().onMessage()` (foreground)
and 
`messaging().setBackgroundMessageHandler()` (background)

**Comment by tomthornton** [comment]
@chenop My push notifications had been working for awhile, but all the sudden it stopped. onMessage works for me but BackgroundMessageHandler does not

**Comment by chenop** [comment]
Also important point If you send the message via the Firebase Console it does not report any errors that occurs (probably small company like Amazon didnt have the budget for error messaging). 
But if you send it via a script an exception might be thrown and it may leads you to the problem.

Here is my script I did for sending messages:
DEVICE_TOKE - the device token you are sending to
PRIVATE_KEY_FILE - check comment how to download it
YOUR_PROJECT_NAME - you firebase project

`
const admin = require("firebase-admin");

// This registration token comes from the client FCM SDKs - this should be replace with your tested device
const TESTED_DEVICE_REGISTRATION_TOKEN = [DEVICE_TOKE];

// Download json from Firebase Console --> Settings --> Service Accounts --> Generate new private key
const serviceAccount = require([PRIVATE_KEY_FILE]);

admin.initializeApp({
	credential: admin.credential.cert(serviceAccount),
	databaseURL: "https://[YOUR_PROJECT_NAME].firebaseio.com",
});

const registrationToken = TESTED_DEVICE_REGISTRATION_TOKEN;

const message = {
	notification: {
		title: "My Title",
		body: "Can you see me?",
	},
	token: registrationToken,
};

// Send a message to the device corresponding to the provided
// registration token.
admin
	.messaging()
	.send(message)
	.then(response => {
		// Response is a message ID string.
		// eslint-disable-next-line no-console
		console.log("Successfully sent message:", response);
	})
	.catch(error => {
		// eslint-disable-next-line no-console
		console.log("Error sending message:", error);
	});
`

**Comment by tomthornton** [comment]
@chenop thanks! yep I'm sending them from my server and getting no error. I believe it's a conflict between react-native-firebase-messaging and react-native-push-notification competing for the notification.

**Comment by chenop** [comment]
@tomthornton not sure about that - react-native-firebase v6 is responsible for delivering the json to your device - thats it - nothing about displaying it.
react-native-push-notification basically accept title and body and display it (nothing related to messages sending over the internet).

Its true that sometimes the Firebase SDK (which react-native-firebase wraps) is displaying notification but not sure exactly when and for which platform.
