### ISSUE TITLE
localNotification() does not work for IOS > 10

### ISSUE THREAD

**Issue by quangdh** [zo0r/react-native-push-notification#1364]
# Bug
RN: 0.61.5
"react-native-push-notification": "^3.1.9"
My code:
PushNotification.localNotification({
        title: "Hello world",
        message: "Hello world",
});

Local notification does not working for IOS > 10

**Comment by Dallas62** [comment]
Hi!
Did you follow the installation of @react-native-community/push-notification-ios ?
There is an example folder, you can try it to see if it’s happening again.
Thanks!
