### ISSUE TITLE
How to detect if a notification has been touched by the user when app is in background?

### ISSUE THREAD

**Issue by strawberry-code** [zo0r/react-native-push-notification#1365]
I have a problem with background notifications on Android. When a notification arrives while the application is closed or in a background state, this notification is handled correctly, but it is performed too early compared to loading the GUI and for me this is a problem.

I tried to solve this problem by putting a setTimeout to run the notification logic, so that the app starts the UI has time to load, about 4 seconds I saw that it is enough. But it is absolutely not a good solution.

Another solution was to insert the notifications that arrive in an object, saving only the last notification. However, in this way the link with the notification on which the user has touched and the notification that is performed when the app starts (based on the object I registered) is lost.

It would be nice to understand if the notification has been touched or not by the user, so as to keep the notification object and execute it when the UI is ready.

Is there a way to tell if a notification has been touched by a user or not?

**Comment by developer-appdam** [comment]
I need the same, some help would be welcome!

**Comment by strawberry-code** [comment]
@developer-appdam I found the property [userInteraction](https://github.com/zo0r/react-native-push-notification#handling-notifications) that it is **true** in the case the user tap the notification, **false** elsewhere.

Pay attention, I noticed that on Android it may not work correctly, but on iOS it works fine.

**Comment by developer-appdam** [comment]
@strawberry-code that's good to hear. Where is this property located? In the push itself? 
Are you also getting the push onNotification when the app is in background without even interacting? Because the problem I have is that the push is just displayed on my log(I'm logging onNotification) and it doesn't matter if I tap or not, I don't get any other log.
Do you have the toggle of remote notifications enabled on your iOS project in the background modes capabilitities?

**Comment by strawberry-code** [comment]
> Where is this property located? In the push itself?

You can use this property as follow:

``` 
 // (required) Called when a remote or local notification is opened or received
  onNotification: function (notification) {
    console.log("NOTIFICATION Data: ", JSON.stringify(notification)); // You should see userInteraction property here

    // required on iOS only (see fetchCompletionHandler docs: https://github.com/react-native-community/react-native-push-notification-ios)
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },
```

> Do you have the toggle of remote notifications enabled on your iOS project in the background modes capabilitities?

Of course, yes.

> Are you also getting the push onNotification when the app is in background without even interacting? Because the problem I have is that the push is just displayed on my log(I'm logging onNotification) and it doesn't matter if I tap or not, I don't get any other log.

On iOS, if you have your App in foreground, you will not see the push notification "pop-up", but the notification actually is always handled and catched by `onNotification:`.

If you App is in foreground or closed, the notification will be processed by `onNotification`, but you can decide what to do by inspecting `userInteraction` property.

**Comment by allindeveloper** [comment]
Hi @strawberry-code 
Could you try this, probably on a SplashScreen, as it has worked for me...

```js
if(Platform.OS === "ios"){
    const res = await PushNotificationIOS.getInitialNotification()
    if(res !== null){
    console.log(res.getData)
    }else{
      console.log("res is null")
    }
  }else{
    PushNotification.popInitialNotification((callback)=>{
      if(callback !==null){
       consolo.log(callback.userInfo)
      }else{
       consoloe.log("userinfo is null")
      }
  })
  }
 ```

**Comment by Dallas62** [comment]
Hi!
If you can test the version on `dev` branch about `userInteraction`, issue on iOS should be fixed and recent version of Android also fixed `userInteraction` value.

**Comment by plus-** [comment]
@Dallas62 I'm using 6.1.3 and `userInteraction` is always false even when user click the notification. 

I'm not seeing anything in 7.0.0 changeling about it, is it still in development?

**Comment by Dallas62** [comment]
"Having the issue" is not a useful debug information. I suggest you to upgrade your dependencies on both plateform, iOS and Android.
Regards
