### ISSUE TITLE
Not able to slient the default Notifcations 

### ISSUE THREAD

**Issue by theyogendraDanwar** [zo0r/react-native-push-notification#1369]
Hello fellow developers

I am trying to integrate the rich notification functionality into the app but fully able to understand how to achieve that on top of that I am not able to silent the default notifications which are coming after integration. I want to disable the default notifications which are coming in and use localNotification method to push notifications when received message from FCM 

in the app.js I am calling initPushNotifications

`useEffect(() => {
    checkPermission();
    messageListener();
    initPushNotifications(onRegister, notifcations);
  }, [])`

`function onRegister (tt) {
    console.log(tt);
  }

  function notifcations (notification) {
    console.log("NOTIFICATION:", notification);
    // notification.finish(PushNotificationIOS.FetchResult.NoData);
  }`

NotifyService.js
`import PushNotification from 'react-native-push-notification';
export function initPushNotifications(regsiter, notification){
  PushNotification.configure({
    onNotification: notification,
    popInitialNotification: false,
    requestPermissions: true,
  })
}`

**Comment by Dallas62** [comment]
Hi @theyogendraDanwar 
You can refer to:
[silent-remote-push-notifications](https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md#3-silent-remote-push-notifications)
