### ISSUE TITLE
Custom sounds not playing if more than one sound on android

### ISSUE THREAD

**Issue by mirzaam786** [zo0r/react-native-push-notification#1375]
# Bug
The current code doesn't support more than one sound on version Oreo and above as this requires a notification channel per sound. I have had to look at an old branch and use that (https://github.com/MaximusBaton/react-native-push-notification) but this is very far behind the current commit. I have tried the current commit and it didn't work and with the changes incorporated into it, it does work. Otherwise you only get the default sound.

**Comment by mirzaam786** [comment]
Here's the article on channels and that for each channel, you can set the visual and auditory behavior that is applied to all notifications in that channel.
https://developer.android.com/training/notify-user/channels

**Comment by Dallas62** [comment]
Hi @mirzaam786 
Thanks for this report, can you try the PR #1042 ?

**Comment by mirzaam786** [comment]
Thanks for that. The code looks good to me, will give it a try but similar to wha ti had to do to create the multiple notification channels. Is this going to be merged into the latest soon?

**Comment by mirzaam786** [comment]
Im presuming this is the one i should try out: https://github.com/fleeteng/react-native-push-notification

**Comment by Dallas62** [comment]
Hi @mirzaam786 
You can test it by doing this: 
Change the current version of `react-native-push-notification`:
```
    "react-native-push-notification": "git+https://github.com/fleeteng/react-native-push-notification.git"
````
then run:
```
yarn install
```
**OR**
```
npm install
```
once it's done, you should be able to test the PR, if it's good for you, I will merge the PR.

**Comment by mirzaam786** [comment]
Ok I am testing it now and will confirm how this goes. Initial check seem positive. 

Looking at the code  this I'm not sure about. In the first instance, the default channel id is used in the contractor but then later is overridden with the soundName. Wouldn't it be more consistent to have the constructor have the right channel id in the first place? 
     NOTIFICATION_CHANNEL_ID_TMP = ""+ NOTIFICATION_CHANNEL_ID;
            NotificationCompat.Builder notification = new NotificationCompat.Builder(context, NOTIFICATION_CHANNEL_ID_TMP)
    
 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) { // API 26 and higher
    NOTIFICATION_CHANNEL_ID_TMP = NOTIFICATION_CHANNEL_ID +"-"+ soundName;  notification.setChannelId(NOTIFICATION_CHANNEL_ID_TMP);

**Comment by Dallas62** [comment]
Hi @mirzaam786 
The PR is now on master and release on version 3.2.1.
Regards,

**Comment by mirzaam786** [comment]
Thank you, i am now using the latest version and its working successfully. I will close this issue
