### ISSUE TITLE
open a modal by pressing an action (without opening the whole app)

### ISSUE THREAD

**Issue by mostafanadi** [zo0r/react-native-push-notification#1376]
hello 
i need to open a modal by pressing on an action button. can anyone help?
i post two pics of another app that implemented this feature.
![appjpg](https://user-images.githubusercontent.com/53375461/79681744-b894f680-8231-11ea-9775-234b345237da.jpg)

**Comment by Dallas62** [comment]
Hi @thisismoosi 
I don't think this feature is available on this library for now.
If you have an idea to implement it, feel free to make a PR 😃
