### ISSUE TITLE
NSString cannot be converted to NSNumber if fireDate is a string for iOS (React Native 0.62.2)

### ISSUE THREAD

**Issue by IgorVanian** [zo0r/react-native-push-notification#1383]
# Bug

On iOS, when calling localNotificationSchedule() with a JS Date object, I'm getting an error **JSON value '_myISODate_' of type NSString cannot be converted to NSNumber**.

Debugging deep brought me here: `node_modules/react-native/Libraries/PushNotificationIOS/RCTPushNotificationManager.mm`

```js
if (notification.fireDate()) {
    notificationDict[@"fireDate"] = @(*notification.fireDate());
}
```

From what I understand, `@()` points to a NSNumber in Objective-C and fireDate is a string as passed from `node_modules/react-native-push-notification/index.js`. Hence, the conversion throws an error.

By switching from `.toISOString()` to `.getDate()`, the error is gone and the notification is scheduled.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 22.71 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.7.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.1.2

## Steps To Reproduce

1. Schedule a local notification as normal on iOS.

Describe what you expected to happen:

1. NSString to NSNumber conversion error

**Comment by Dallas62** [comment]
Hi @IgorVanian 
I don't understand exactly this issue, did you install [@react-native-community/push-notification-ios](https://github.com/react-native-community/push-notification-ios) ?
Code for `fireDate`: https://github.com/react-native-community/push-notification-ios/blob/master/ios/RNCPushNotificationIOS.m#L88
See: https://reactnative.dev/docs/pushnotificationios

**Comment by IgorVanian** [comment]
Hi @Dallas62 ,
It seems that I still have a deprecated PushNotificationIOS from `node_modules/react-native/Libraries/PushNotificationIOS/RCTPushNotificationManager.mm`. The code above is from there.

I can see that it's not the case for the new [@react-native-community/push-notification-ios](@react-native-community/push-notification-ios)

Probably my problem was coming from there. I thought `push-notification-ios` was a dependency in `react-native-push-notification`. Should have checked that beforehand :)
