### ISSUE TITLE
Notification Listener is not working into Android.

### ISSUE THREAD

**Issue by parassinghh** [zo0r/react-native-push-notification#1384]
# Notification listener not working into android.
I am using react-native-push-notification. So the notification listener is working fine into the `Ios` platform
but not working fine into the android platform. When I receive a notification so I click on and then the notification listener never called.

## Environment info

`react-native info` output:

1 react-native version: 0.59.4
2 react-native-push-notification: 3.1.3
3 platform : Andorid

Library version: 3.1.3

**Comment by Dallas62** [comment]
Hi @parassinghh 
Can you provide more details on this issue ? (Code, Manifest, ...)
With the `example` project?
And your version is a bit old, can you update ?

**Comment by parassinghh** [comment]
> Hi @parassinghh
> Can you provide more details on this issue ? (Code, Manifest, ...)
> With the `example` project?
> And your version is a bit old, can you update ?

AndroidManifest.xml 
`   <permission
      android:name="${applicationId}.permission.C2D_MESSAGE"
      android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

  <application
      android:name=".MainApplication"
      android:label="@string/app_name_dev"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="true"
      android:theme="@style/AppTheme"
    >
     <activity
        android:name=".SplashActivity"
        android:theme="@style/splashScreenTheme"
        android:label="@string/app_name">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
     </activity>
     <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
       android:value="YOUR NOTIFICATION CHANNEL NAME"/>
     <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
       android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION"/>
     
     <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
       android:resource="@android:color/white"/>
     
      <receiver
        android:name="com.google.android.gms.gcm.GcmReceiver"
        android:exported="true"
        android:permission="com.google.android.c2dm.permission.SEND" >
        <intent-filter>
          <action android:name="com.google.android.c2dm.intent.RECEIVE" />
          <category android:name="${applicationId}" />
        </intent-filter>
      </receiver>
    <receiver android:name="io.invertase.firebase.notifications.RNFirebaseNotificationReceiver"/>
    
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
      <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
      </intent-filter>
   </receiver>
  <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
  
  <service
    android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm"
    android:exported="false" >
    <intent-filter>
      <action android:name="com.google.android.c2dm.intent.RECEIVE" />
    </intent-filter>
  </service>



    <service
      android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
      android:exported="false" >
        <intent-filter>
           <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
    </service>
    <service android:name="com.android.notification.MyFirebaseMessagingService">
        <intent-filter>
         <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
    </service>
    <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
       <intent-filter>
         <action android:name="com.google.firebase.MESSAGING_EVENT" />
       </intent-filter>
    </service>
`

**Comment by parassinghh** [comment]
@Dallas62 I have updated my liabrary veriosn but don't work.

**Comment by Dallas62** [comment]
Can you provide more informations? I will not be able to help.
Follow the installation instructions (udpated recently) and remove what's not needed.

**Comment by parassinghh** [comment]
> Can you provide more informations? I will not be able to help.
> Follow the installation instructions (udpated recently) and remove what's not needed.

Android Manifest.xml file

    <permission
      android:name="${applicationId}.permission.C2D_MESSAGE"
      android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

  <application
      android:name=".MainApplication"
      android:label="@string/app_name_dev"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="true"
      android:theme="@style/AppTheme"
    >
     <activity
        android:name=".SplashActivity"
        android:theme="@style/splashScreenTheme"
        android:label="@string/app_name">
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
     </activity>
     <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
       android:value="YOUR NOTIFICATION CHANNEL NAME"/>
     <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
       android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION"/>
     
     <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
       android:resource="@android:color/white"/>
     
      <receiver
        android:name="com.google.android.gms.gcm.GcmReceiver"
        android:exported="true"
        android:permission="com.google.android.c2dm.permission.SEND" >
        <intent-filter>
          <action android:name="com.google.android.c2dm.intent.RECEIVE" />
          <category android:name="${applicationId}" />
        </intent-filter>
      </receiver>
    <receiver android:name="io.invertase.firebase.notifications.RNFirebaseNotificationReceiver"/>
    
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
      <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
      </intent-filter>
   </receiver>
  <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
  
  <service
    android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm"
    android:exported="false" >
    <intent-filter>
      <action android:name="com.google.android.c2dm.intent.RECEIVE" />
    </intent-filter>
  </service>



    <service
      android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
      android:exported="false" >
        <intent-filter>
           <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
    </service>
    <service android:name="com.android.notification.MyFirebaseMessagingService">
        <intent-filter>
         <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
    </service>
    <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
       <intent-filter>
         <action android:name="com.google.firebase.MESSAGING_EVENT" />
       </intent-filter>
    </service>

**Comment by parassinghh** [comment]
@Dallas62 Do you know when the problem comes in Android ?

**Comment by Dallas62** [comment]
@parassinghh 
I think there is some informations missing in the manifest,
I do not see any:
```xml

       <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>

```

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification#android-manual-installation

**Comment by parassinghh** [comment]
@Dallas62 Here is my local schedule notification code.

 `import PushNotification from 'react-native-push-notification';
import { AsyncStorage } from 'react-native';
import constant from '../config/Constant';
import axios from 'axios';
import moment from 'moment';

const ROUTINE_NOTIFICATION = {
  morning: {
    message: [
      'Your morning habits are waiting for you 😊',
      'Rise and shine! You have some habits this morning',
      'Start the day off strong with your morning habits!'
    ],
    timeSlot: [7,0], //[hours,minutes,seconds]
    id: '1',
  },
  afternoon: {
    message: [
      "Take some time for your afternoon habits 😊",
      "Shake up your afternoon with a habit or two!",
      "Tomo here! You've got afternoon habits 😊"
    ],
    timeSlot: [12,0],
    id: '2',
  },
  evening: {
    message: [
      "There's no time like the present for an evening habit!",
      'Take a moment for your evening habits',
      'Remember to share your evening habits 😊'
    ],
    timeSlot: [17,0],
    id: '3',
  },
  night: {
    message: [
      "Looks like you've got nighttime habits",
      'Unwind with your nighttime habits',
      'Tomo here, reminding you to share your nighttime habits 😊'
    ],
    timeSlot: [22,0],
    id: '4',
  }
}


class xyz {
    constructor(options = {},onNotification) {
    this.id = options.notificationId || '';
    this.message = options.notificationMessage || '';
    this.repeatation = options.repeatation || 'day';
    this.date = options.notificationDate || '';
    this.userHabit = options.userHabit || [];
    this.payload = options.payload || {};
    this.configureNotification(onNotification);
  }

  configureNotification(onNotification) {
    PushNotification.configure({
      onNotification:  onNotification,
      permissions: {
        alert: true,
        badge: true,
        sound: true
      },
      popInitialNotification: true,
      requestPermissions: true,
    });
  }

  cancelAllNotifications() {
    PushNotification.cancelAllLocalNotifications();
  }

  cancelNotification(payload) {
    PushNotification.cancelLocalNotifications(payload);
  }

  async setRoutineNotification(){
    let options = {
      number : '1',
      repeatType: 'day',
    }
 
  // api call
    axios.get(url, config).then(async (response) => {
      PushNotification.cancelLocalNotifications({id: ROUTINE_NOTIFICATION.morning.id});
      PushNotification.cancelLocalNotifications({id: ROUTINE_NOTIFICATION.afternoon.id});
      PushNotification.cancelLocalNotifications({id: ROUTINE_NOTIFICATION.evening.id});
      PushNotification.cancelLocalNotifications({id: ROUTINE_NOTIFICATION.night.id});
      if('data' in response && 'data' in response['data']){
        for(let i = 0; i <= response.data.data.length-1; i++){
          let valuesToUpdate = {
            ...options
          };
          switch(response.data.data[i]['name']){
            case 'morning':
              valuesToUpdate.id = ROUTINE_NOTIFICATION.morning.id,
              valuesToUpdate.type = 'Before_Habit_Notification';
              valuesToUpdate.message = ROUTINE_NOTIFICATION.morning.message[Math.floor(Math.random() * 10)%3];
              let date = new Date();
              valuesToUpdate.date = (date.getHours()-5 > ROUTINE_NOTIFICATION.morning.timeSlot [0]) ? new Date(date.setDate(date.getDate() + 1)):
              new Date(date.setHours(...ROUTINE_NOTIFICATION.morning.timeSlot));
              break;
            case 'afternoon':
              valuesToUpdate.id = ROUTINE_NOTIFICATION.afternoon.id,
              valuesToUpdate.type = 'Before_Habit_Notification';
              valuesToUpdate.message = ROUTINE_NOTIFICATION.afternoon.message[Math.floor(Math.random() * 10)%3];
              let dateAfternoon = new Date();
              console.log(dateAfternoon.getHours());
              valuesToUpdate.date = (dateAfternoon.getHours() > ROUTINE_NOTIFICATION.afternoon.timeSlot [0]) ? new Date(dateAfternoon.setDate(dateAfternoon.getDate() + 1)):
              new Date(dateAfternoon.setHours(...ROUTINE_NOTIFICATION.afternoon.timeSlot));
              break;
            case 'evening':
              valuesToUpdate.id = ROUTINE_NOTIFICATION.evening.id,
              valuesToUpdate.type = 'Before_Habit_Notification';
              valuesToUpdate.message = ROUTINE_NOTIFICATION.evening.message[Math.floor(Math.random() * 10)%3];
              let dateEvening = new Date();
              valuesToUpdate.date = (dateEvening.getHours() > ROUTINE_NOTIFICATION.evening.timeSlot [0]) ? new Date(dateEvening.setDate(dateEvening.getDate() + 1)):
              new Date(dateEvening.setHours(...ROUTINE_NOTIFICATION.evening.timeSlot));
              break;
            case 'night':
              valuesToUpdate.id = ROUTINE_NOTIFICATION.night.id,
              valuesToUpdate.type = 'Before_Habit_Notification';
              valuesToUpdate.message = ROUTINE_NOTIFICATION.night.message[Math.floor(Math.random() * 10)%3];
              let dateNight = new Date();
              valuesToUpdate.date = (dateNight.getHours() > ROUTINE_NOTIFICATION.night.timeSlot [0]) ? new Date(dateNight.setDate(dateNight.getDate() + 1)):
              new Date(dateNight.setHours(...ROUTINE_NOTIFICATION.night.timeSlot));
              break;
          }
          PushNotification.localNotificationSchedule(valuesToUpdate);
        }
      }
    }).catch(error => {
      //console.log(error);
    });
  }
}

export default xyz;
`

**Comment by Dallas62** [comment]
Can you try the version on master ?

**Comment by parassinghh** [comment]
@Dallas62 How can use master version ?

**Comment by Dallas62** [comment]
You can try:
```
yarn add zo0r/react-native-push-notification#master
```
or with npm.

**Comment by parassinghh** [comment]
@Dallas62 I am getting error to install master version.
`could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-e0601c52': Permission denied`

**Comment by Dallas62** [comment]
This bug comes because your running non or yarn as root, which is not recommended...
It doesn’t come from the master branch

**Comment by Dallas62** [comment]
Hi, can you try ?
https://github.com/zo0r/react-native-push-notification/issues/1304#issuecomment-586135377

**Comment by parassinghh** [comment]
@Dallas62 yeah i am already used it.
<activity
      android:name=".MainActivity"
      android:label="@string/app_name"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
      android:windowSoftInputMode="adjustResize"
      android:exported="true"
      android:launchMode="singleTask">

**Comment by parassinghh** [comment]
@Dallas62 
Can you tell me why this problem occurs? Does it come with Android the most?

**Comment by Dallas62** [comment]
@parassinghh Did you tried the version on master ?
The issue you reported with `Permission denied` is due to a wrong configuration of npm/yarn on your machine (probably installed as root)

**Comment by mohammedasifp** [comment]
I am using react-native-push-notification in android. whenever notification comes, function is getting called continuously three times
