### ISSUE TITLE
Schedule Notification fired instantly

### ISSUE THREAD

**Issue by ali8404** [zo0r/react-native-push-notification#1386]
const alarmTime = new Date(alarmRecord.Date + " " + alarmRecord.Time);
              PushNotification.localNotificationSchedule({
                id: 1, 
                userInfo: { id: 1 },
                title: "Prayer Time",
                message: "Alarm time", // (required)
                date: new Date(alarmTime),
              });
schedule notification fired instantly althought  specific date time provided

Requirement: Need to generate the notifications at different times for the whole year

**Comment by Dallas62** [comment]
Hi @ali8404 
Can you check the value of Date ?
I'm not able to reproduce your issue.

**Comment by ali8404** [comment]
Hi @Dallas62 
const parseDate = Date.parse("26 Apr 2020 01:40:00");
  PushNotification.localNotificationSchedule({
                id: 1,
                userInfo: { id: 1 },
                title: "Prayer Time",
                message: "Prayer Time for Namaz e " + alarmRecord.namazName, // (required)
                date: new Date(parseDate),
              });
used this and its behaving same

**Comment by Dallas62** [comment]
I think you have a problem with the timezone.
if you try something like:
```js
new Date(Date.now() + 30 * 1000)
```
You should have the notification triggered in 30s.

**Comment by Dallas62** [comment]
If the test with the 30s works, try to look if your time is in the right timezone.

**Comment by ali8404** [comment]
thanks, @Dallas62  it was 12 and 24hours format issue.
Is there any way to schedule notifications for a whole year on specific dates and times at once?

**Comment by Dallas62** [comment]
There is some limitation on devices (samsung) to avoid too many scheduled notifications.
you can set a list of notifications at specific point in time. I don't think there is an method to get all scheduled notification for now, ut you can clear all notifications and set again notifications. 😄

**Comment by ali8404** [comment]
thanks, @Dallas62  "**you can clear all notifications and set again notifications.**" that will be a pain
