### ISSUE TITLE
onNotification being called only after the component is fully loaded

### ISSUE THREAD

**Issue by s-z-s** [zo0r/react-native-push-notification#1393]
Hello, I have setup the package successfully. But when a notification is clicked and the app opens, onNotification is being called only after everything has been loaded in the page. I need to open notifications page if the user has opened app by clicking a notification. How can I achieve this if the homepage is already loaded? 
Here is my App.js: 
```
export default class App extends Component{  
    constructor(props) {
      super(props);
      this.state = {
        senderId: appConfig.senderID,
        notiType: 'default'
      };
      this.notif = new NotifService(
        this.onRegister.bind(this),
        this.onNotif.bind(this),
      );
    }
    onRegister(token) {
        this.setState({registerToken: token.token, fcmRegistered: true});
    }

    onNotif(notif) {
        console.log(notif);
        if(notif.type != undefined) this.setState({notiType: notif.type});
    }
    componentDidMount(){
        this.notif.configure(
            this.onRegister.bind(this),
            this.onNotif.bind(this),
            this.state.senderId,
        );
    }
    
    render(){
            return (
                <NavigationContainer>
                {StackScreen(this.state.notiType)}
                </NavigationContainer>
            );
    }
}
```
Here, the state variable notiType returns default to the home page even before the onNotif() function has been fired. I am using NotifService.js from the example app.

**Comment by Dallas62** [comment]
Hi,
You will have to get the naviigator and trigger navigate to go on the notifiaction screen.

**Comment by Dallas62** [comment]
Since you put the logic of the library in `componentDidMount()`, yes 😉 
You can look at: https://reactjs.org/docs/state-and-lifecycle.html#adding-lifecycle-methods-to-a-class
and
![image](https://user-images.githubusercontent.com/3429329/80733341-dd307e80-8b0d-11ea-83c3-57006d25cb0c.png)

**Comment by s-z-s** [comment]
Oh did not know this. Thanks.

So if i put the logic in my constructor, will the onNotification be fired first??

**Comment by Dallas62** [comment]
Since `onNotification` respond to an event, this might not be enough. The event will be placed at the end of the event loop and if React is synchronous for the mounting part, `render()` will be made first.

**Comment by s-z-s** [comment]
Thanks @Dallas62  I will change my code accordingly then.
