### ISSUE TITLE
onNotification not fired when app is minimised

### ISSUE THREAD

**Issue by s-z-s** [zo0r/react-native-push-notification#1394]
In my project, onNotification function works fine when the app is in foreground. It even gets fired when the app has been closed and user opens the app by clicking on the notification. But when the app is minimised, on receiving notification and clicking it, the app opens but onNotification function is not being called. 
Here is my app.js: 
```
export default class App extends Component{  
    constructor(props) {
      super(props);
      this.state = {
        senderId: appConfig.senderID,
        notiType: 'default'
      };
      this.notif = new NotifService(
        this.onRegister.bind(this),
        this.onNotif.bind(this),
      );
    }
    onRegister(token) {
        this.setState({registerToken: token.token, fcmRegistered: true});
    }

    onNotif(notif) {
        console.log(notif);
        if(notif.type != undefined) this.setState({notiType: notif.type});
    }
    componentDidMount(){
        this.notif.configure(
            this.onRegister.bind(this),
            this.onNotif.bind(this),
            this.state.senderId,
        );
    }
    
    render(){
            return (
                <NavigationContainer>
                {StackScreen(this.state.notiType)}
                </NavigationContainer>
            );
    }
}
```

**Comment by Dallas62** [comment]
Hi,
Please give more informations, such as version of the library.

**Comment by s-z-s** [comment]
I am using 3.2.1 version. Is this issue fixed in 3.3.0? I just tried yarn upgrade `react-native-push-notification` but the version number in package.json did not change.

**Comment by Dallas62** [comment]
Yes this issue is fixed in 3.3.0.

**Comment by s-z-s** [comment]
Ok thanks a lot! Atleast this one got fixed automatically. 😅 I will close this issue.

**Comment by s-z-s** [comment]
@Dallas62 I upgraded to 3.3.0 but the problem persists.
Here's the notification I get when the app is closed and the notification click opens the app:
`{"collapse_key": "com.medinnepal", "finish": [Function finish], "foreground": false, "from": "804755898688", "google.delivered_priority": "high", "google.message_id": "0:1588264225571691%55ebe4c055ebe4c0", "google.original_priority": "high", "google.sent_time": 1588264225557, "google.ttl": 2419200, "type": "order"}`

And this is the log when the app is in foreground:
`{"color": null, "data": {"type": "order"}, "finish": [Function finish], "foreground": true, "id": "-669049391", "message": "Your order 23487329 has now been dispatched.", "sound": "sampleaudio", "title": "Medicine Order Status", "userInteraction": false}`

But when the app has been minimised, notification comes and on click, the app opens but onNotification is not fired.

**Comment by s-z-s** [comment]
@Dallas62  I upgraded to 3.3.0 but the problem persists.
Here's the notification I get when the app is closed and the notification click opens the app:
`{"collapse_key": "com.myapp", "finish": [Function finish], "foreground": false, "from": "43538792343", "google.delivered_priority": "high", "google.message_id": "0:1588264ghvhjgjhgkhj67587ebe4c055ebe4c0", "google.original_priority": "high", "google.sent_time": 1588264225557, "google.ttl": 2419200, "type": "order"}`

And this is the log when the app is in foreground:
`{"color": null, "data": {"type": "order"}, "finish": [Function finish], "foreground": true, "id": "-669049391", "message": "Your order has now been dispatched.", "sound": "sampleaudio", "title": "Order Status", "userInteraction": false}`

But when the app has been minimised, notification comes and on click, the app opens but onNotification is not fired.

**Comment by Dallas62** [comment]
https://firebase.google.com/docs/cloud-messaging/concept-options
>Notification messages with optional data payload
Both programmatically or via the Firebase console, you can send notification messages that contain an optional payload of custom key-value pairs. In the Notifications composer, use the Custom data fields in Advanced options.
App behavior when receiving messages that include both notification and data payloads depends on whether the app is in the background or the foreground—essentially, whether or not it is active at the time of receipt.
When in the background, apps receive the notification payload in the notification tray, and only handle the data payload when the user taps on the notification.
When in the foreground, your app receives a message object with both payloads available.

**Comment by s-z-s** [comment]
Thanks I will properly read before asking anymore questions. 😅

**Comment by Dallas62** [comment]
But for:
> But when the app has been minimised, notification comes and on click, the app opens but onNotification is not fired.
This is not normal, you should have `onNotification` trigger.
Maybe something is wrong in your configuration or use of the library.

**Comment by s-z-s** [comment]
I will try reconfiguring the package again. I may have messed up something trying to get the local scheduled notifications working. I tried many things but then at last turned out my OnePlus battery optimisation was stopping the scheduled notifications. So maybe I did something wrong during that time.

**Comment by s-z-s** [comment]
@Dallas62 [this](https://github.com/zo0r/react-native-push-notification/issues/727#issuecomment-386360518) solution worked for me and gave a log when app was opened from notification while in background. 
But this makes the app give a log two times when the app is opened from notification while closed as onNotification is also being called then. Can you implement this code in the package itself so onNotification is directly triggered?

**Comment by Dallas62** [comment]
I don’t have time now, but if you want to test by editing the file in node_modules, it’s the listener service and you can find the change on the fork (search the `if` with the `content-available` and a check on `message` key on `bundle`).
This should do the trick,
And if you can make a PR I will look at it 😉

**Comment by s-z-s** [comment]
@Dallas62 I have limited knowledge on this but I will try to change on node_modules and build too! I will update you if I end up somewhere.

Thanks. My problem has been solved for now, so closing this.

**Comment by s-z-s** [comment]
@Dallas62 how can I check the logs generated by the package? `adb -d logcat com.testapp`?

**Comment by bipul-yadav** [comment]
same issue ,

onNotification is not fired when the app is minimized and I click on notification,
but working perfectly when app is open or closed.

**Comment by amirulasrof** [comment]
Same issue happen to me as well. When app is minimized, onnotification is not triggered.
