### ISSUE TITLE
No pop up Notification on Remote Notifications

### ISSUE THREAD

**Issue by s-z-s** [zo0r/react-native-push-notification#1395]
In my app, I have setup local as well as remote notifications. The local notifications are working fine and show pop up notifications correctly. But remote notifications donot show as pop up notifications. They are only shown in the notification tray when the notification arrives. Why is it happening that local notifications work fine but remote notifications give such problems?

**Comment by Dallas62** [comment]
Hi,
This is not the same kind of notifications, the comportement cannot be compared. You might be able to configure this in the sender (server-side).

**Comment by s-z-s** [comment]
@Dallas62 doesn't the app handle all incoming notifications in the same way? Do remote notifications give pop ups on your phone?

**Comment by s-z-s** [comment]
@Dallas62 I am sending this data from server side:
`{"to":"myFCMtoken","notification":{"title":"Working Good","body":"Notification delivered successfully.","sound":"sampleaudio"},"data":{"type":"order"},"priority":"high"}`

In my previous app using react native firebase, this same data used to give pop up notifications.

**Comment by s-z-s** [comment]
Shouldn't the test message from firebase console be delivered with a pop up notification by default @Dallas62 ?

**Comment by wbercx** [comment]
This could be a regression. My local notifications display immediately using `3.2.1`, but are not displayed using `3.3.0`.  They do land in the notification tray though.

**Comment by s-z-s** [comment]
@wbercx I just noticed the same behavior in mine too. Local notifications used to work fine in 3.2.1. Now all notifications are displayed in the tray only. @Dallas62 do you have any idea about this?

**Comment by Dallas62** [comment]
Hi, I just release version `3.3.1` I made a mistake by confusing priority and importance between notification and channel, it's now fixed but you might need to clean node_modules and Cie.

**Comment by s-z-s** [comment]
@Dallas62 thanks for the quick update. Local notifications are working fine now. But still the problem persists for remote notifications.

**Comment by Dallas62** [comment]
Did you test with a fresh install?

**Comment by s-z-s** [comment]
I did the following steps:
1. react-native unlink
2. yarn remove
3. delete node_modules and build folders
4. yarn install
5. yarn add
6. react native link

**Comment by cladjules** [comment]
@s-z-s took me some time, but I figured out.
The default channel created by the library is
`String channel_id = NOTIFICATION_CHANNEL_ID + "-" + importance + "-" + DEFAULT_VIBRATION;
`
_Importance High and Vibration 300._
Importance is high, it will show the banner by default.

You need to tell Android to use that channel by default, add that to your AndroidManifest:
```
      <meta-data
        android:name="com.google.firebase.messaging.default_notification_channel_id"
        android:value="rn-push-notification-channel-id-4-300" />
```

You can add that after ```      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
          android:value="HealthForceGo"/>```

**Comment by Dallas62** [comment]
Hi @cladjules 
yes and there is a channel each time you pop a notification with different configuration (sound, vibration, importance).
To avoid a huge refactoring in channel management and break the current interface, this choice have been made.
For proper implementation, I would suggest to help `wix/react-native-notifications` that bind directly the API of Android which made channel management proper. But it doesn't support Scheduled notification at the moment.

**Comment by s-z-s** [comment]
@cladjules this solved the problem! Thanks a lot! 
@Dallas62 I was going through RNPushNotificationHelper.java and tried to changed default importance for notifications as high from there but didn't work.

**Comment by cladjules** [comment]
Glad it worked,
maybe, it would be worth adding that to the documentation? :)

**Comment by Dallas62** [comment]
I will allow both comportement soon to avoid to restrict the choice (had issue in both cases ...)

**Comment by s-z-s** [comment]
@Dallas62 are you recommending not to use the solution by @cladjules ?

**Comment by Dallas62** [comment]
Hi @s-z-s 
You can use this solution,
I think it’s a good way to choose the right default channel

**Comment by s-z-s** [comment]
Hi @Dallas62 
Thanks, I will use it then. 
Also, I think these two metas need to be added to the documentation: 

      ```
<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_stat_logo" />
      <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/ic_launcher_background" />
```

The notification tray was only displaying the app icon as a grey blob. Adding these gave me a custom icon there too.

**Comment by s-z-s** [comment]
I just noticed in RNPushNotificationHelper.java that if we put a transparent all white icon named as ic_notification.png in mipmap folder, the icon is used in the notification tray. The [above ](https://github.com/zo0r/react-native-push-notification/issues/1395#issuecomment-623942195) was for remote notifications and this is for local notifications.

**Comment by mowen0303** [comment]
> @s-z-s took me some time, but I figured out.
> The default channel created by the library is
> `String channel_id = NOTIFICATION_CHANNEL_ID + "-" + importance + "-" + DEFAULT_VIBRATION; `
> _Importance High and Vibration 300._
> Importance is high, it will show the banner by default.
> 
> You need to tell Android to use that channel by default, add that to your AndroidManifest:
> 
> ```
>       <meta-data
>         android:name="com.google.firebase.messaging.default_notification_channel_id"
>         android:value="rn-push-notification-channel-id-4-300" />
> ```
> 
> You can add that after ` <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_description" android:value="HealthForceGo"/>`

The message can be showed up, but there is still no sound. Do you know how to set the sound?

**Comment by cladjules** [comment]
> > @s-z-s took me some time, but I figured out.
> > The default channel created by the library is
> > `String channel_id = NOTIFICATION_CHANNEL_ID + "-" + importance + "-" + DEFAULT_VIBRATION; `
> > _Importance High and Vibration 300._
> > Importance is high, it will show the banner by default.
> > You need to tell Android to use that channel by default, add that to your AndroidManifest:
> > ```
> >       <meta-data
> >         android:name="com.google.firebase.messaging.default_notification_channel_id"
> >         android:value="rn-push-notification-channel-id-4-300" />
> > ```
> > 
> > 
> > You can add that after ` <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_description" android:value="HealthForceGo"/>`
> 
> The message can be showed up, but there is still no sound. Do you know how to set the sound?

You may have to specify that in the payload you send from your server,
e.g.
```
    "android":{
       "notification":{
          "body":"test",
          "title":"test",
          "sound":"default"
       }
    }
```

**Comment by vickyramz** [comment]
> > > @s-z-s took me some time, but I figured out.
> > > The default channel created by the library is
> > > `String channel_id = NOTIFICATION_CHANNEL_ID + "-" + importance + "-" + DEFAULT_VIBRATION; `
> > > _Importance High and Vibration 300._
> > > Importance is high, it will show the banner by default.
> > > You need to tell Android to use that channel by default, add that to your AndroidManifest:
> > > ```
> > >       <meta-data
> > >         android:name="com.google.firebase.messaging.default_notification_channel_id"
> > >         android:value="rn-push-notification-channel-id-4-300" />
> > > ```
> > > 
> > > 
> > > You can add that after ` <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_description" android:value="HealthForceGo"/>`
> > 
> > 
> > The message can be showed up, but there is still no sound. Do you know how to set the sound?
> 
> You may have to specify that in the payload you send from your server,
> e.g.
> 
> ```
>     "android":{
>        "notification":{
>           "body":"test",
>           "title":"test",
>           "sound":"default"
>        }
>     }
> ```

thanks for this...i really appreciate you..working like a charm

**Comment by intelligentiallc** [comment]
still having the same problem

**Comment by AliAmjadHassan** [comment]
> @Dallas62 I am sending this data from server side:
> `{"to":"myFCMtoken","notification":{"title":"Working Good","body":"Notification delivered successfully.","sound":"sampleaudio"},"data":{"type":"order"},"priority":"high"}`
> 
> In my previous app using react native firebase, this same data used to give pop up notifications.

this worked for me i was sending:
{
 "to":"MY_FCM_TOKEN",
 "data" : {
     "body" : "I am a firebase Notification",
     "title": "API"
 }
}
then i replaced word "data" with word "notification" it worked for me

**Comment by HerickRaposo** [comment]
> @szs me levou algum tempo, mas descobri.
> O canal padrão criado pela biblioteca é
> `String channel_id = NOTIFICATION_CHANNEL_ID + "-" + importance + "-" + DEFAULT_VIBRATION; `
> _Importance High e Vibration 300. A_
> importância é alta, ele mostrará o banner por padrão.
> 
> Você precisa dizer ao Android para usar esse canal por padrão, adicione-o ao seu AndroidManifest:
> 
> ```
>       <meta-data
>         android:name="com.google.firebase.messaging.default_notification_channel_id"
>         android:value="rn-push-notification-channel-id-4-300" />
> ```
> 
> Você pode adicionar isso depois ` <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_description" android:value="HealthForceGo"/>`

Its returned me error in app installation
```
<meta-data android:name="com.google.firebase.messaging.default_notification_channel_id"
                    android:value="rn-push-notification-channel-id-4-300" />
```
error:
```
:react-native-firebase_messaging:reactNativeAndroidDir C:\Programacao\MuryCartoes\cartaoReact\node_modules\react-native\android

> Task :app:processDebugMainManifest FAILED
[:react-native-firebase_app] C:\Programacao\MuryCartoes\cartaoReact\node_modules\@react-native-firebase\app\android\build\intermediates\library_manifest\debug\AndroidManifest.xml Warning:
        Package name 'io.invertase.firebase' used in: :react-native-firebase_app, :react-native-firebase.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
```
If anyone managed to make this blessed popup appear please tell me, I'm desperate, I've seen several videos and articles but nothing works.

**Comment by LukasVitek** [comment]
@HerickRaposo, you can use `tools:replace="android:value"`

```xml
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            tools:replace="android:value" android:value="rn-push-notification-channel-id-4-300" />
```

**Comment by guilherme-duarte-vagas** [comment]
> 

Dont forgot to add tools xmlns in top of android manifast

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="app.package.name"
  xmlns:tools="http://schemas.android.com/tools">
```

**Comment by guinduarte** [comment]
Dont forgot to add tools xmlns in top of android manifast
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="app.package.name"
  xmlns:tools="http://schemas.android.com/tools">
```

**Comment by nolife08021** [comment]
Having same issue on IOS, any idea to solve it?

**Comment by dangnguyen1004** [comment]
None of solutions work for me

![image](https://github.com/zo0r/react-native-push-notification/assets/67234142/e6d7aded-009d-4068-89d9-93ab61614c8d)
