### ISSUE TITLE
Scheduled Notification doesn't work in Android release mode

### ISSUE THREAD

**Issue by samouds** [zo0r/react-native-push-notification#1396]
Hello,

I have updated the library for my app for Android, remote notifications work well but local ones work only in debug mode. Didn't get anything in release mode.

Library version: 3.3.1

**Comment by Dallas62** [comment]
Hi @samouds 
can you reproduce this bug on example project ?

**Comment by Dallas62** [comment]
And what's the comportement on the device ?
There is many issues due to a wrong date: https://github.com/zo0r/react-native-push-notification/issues/1336#issuecomment-596361962

**Comment by kagmanoj25** [comment]
Hello samouds,

I'm also working on local notifications and also didn't get anything in release mode.

**Comment by samouds** [comment]
@Dallas62 Hello Dallas. Get more details.

I schedule a notification 10 seconds after launch to test it so it's not a date problem.

When I am testing it with my device, in debug mode I got the notification with the custom sound. When I run in release mode I got the notification but with the default sound.

When I release a beta version to the play store : I got nothing at all.

```
PushNotification.localNotificationSchedule({
      date: new Date(Date.now() + 10 * 1000),
      title: 'title',
      message: 'message',
      allowWhileIdle: true,
      priority: 'max',
      importance: 'max',
      visibility: 'public',
      playSound: true,
      soundName: 'mySound.mp3',
    });
```

**Comment by Dallas62** [comment]
Can you check this:
https://github.com/zo0r/react-native-push-notification/issues/996#issuecomment-620601326

**Comment by Dallas62** [comment]
Any update ?

**Comment by srajesh636** [comment]
@Dallas62 Local Notifications are not working on release mode (Android) not checked ios, on version 4.0.0

**Comment by Dallas62** [comment]
Hi @srajesh636 
Can you elaborate ?
This is probably not local notification that are not working, but a miss use of the library such as using `.configure()` inside a component.

**Comment by srajesh636** [comment]
> Hi @srajesh636
> Can you elaborate ?
> This is probably not local notification that is not working, but a miss use of the library such as using `.configure()` inside a component.

Hi, @Dallas62 thanks for the reply I am not using the configure method anywhere in the code, but I am able to get the local notifications on debug mode but when I build the release apk it does not work there.


```
PushNotification.localNotification({
    title,
    message: body,
  });
```

**Comment by Dallas62** [comment]
Hi @srajesh636,
There is few reason to not have local notifications.
- no channel available
- the method localNotification is not called

How do you trigger your local notification ? In foreground or background/killed state ?
Can you make sure the method is called ?
Can you check you have a channel created ?

**Comment by srajesh636** [comment]
@Dallas62 Tried Everything but nothing works, really tired now.
Channel is created 
localNotification() is called from foreground on clicking a button

Need Help , I simple question

If a notification works on debug mode and what can break it on release mode ?

**Comment by Dallas62** [comment]
Hi @srajesh636 
Can you answer this question:
How do you trigger your local notification ? In foreground or background/killed state ?

**Comment by Dallas62** [comment]
Hi @srajesh636 
Did you try to print what is send to the localNotification method, with the `Alert` component ?
Since you are not using remote notification, there is no reason of getting different behaviour on Release/Debug.
Without a reproductible example, I will not able to help since the example project is working on Release mode on a real device.

**Comment by Pankaj72018** [comment]
Really @Dallas62
