### ISSUE TITLE
RNPushNotification.requestPermissions got 1 arguments, expected 0

### ISSUE THREAD

**Issue by uganof** [zo0r/react-native-push-notification#1397]
Hi,
with 

react-native-push-notification version 3.3.1
react-native version 0,62,2

when set 

PushNotification.configure({
  ....
  requestPermissions: true
});

this error comes out in android with visual studio code debug: 
(If I start with command: react-native run-android run correctly)

RNPushNotification.requestPermissions got 1 arguments, expected 0

![Screenshot_1588344890](https://user-images.githubusercontent.com/20278052/80814869-f2201700-8bcc-11ea-96a8-e74b94f06126.png)

with version 3.1.9 work perfectly, 
do you have any idea why?

**Comment by Dallas62** [comment]
Hi @uganof 
Duplicate https://github.com/zo0r/react-native-push-notification/issues/1391
Please clear you build cache.
