### ISSUE TITLE
I get the notification but without sound and vibration - Android

### ISSUE THREAD

**Issue by ignacioiglesias43** [zo0r/react-native-push-notification#1398]
I installed it 3 days ago and everything was working fine, however I have had the problem since yesterday that I continued with my application, could someone tell me if I am doing something wrong? Or if I have something wrong?

Here is my android manifest:
![imagen](https://user-images.githubusercontent.com/51436771/80869314-feec4b80-8c5c-11ea-81c3-0865a994644c.png)

My code where I schedule the alarm:

![imagen](https://user-images.githubusercontent.com/51436771/80869274-c51b4500-8c5c-11ea-8e0a-d5c98f32b8f0.png)

**Comment by Dallas62** [comment]
Hi @ignacioiglesias43 
Can you use the issue template ?
Thanks.
