### ISSUE TITLE
I get the notification but without sound and vibration - Android

### ISSUE THREAD

**Issue by ignacioiglesias43** [zo0r/react-native-push-notification#1399]
# Bug
I installed it 3 days ago and everything was working fine, however I have had the problem since yesterday that I continued with my application, could someone tell me if I am doing something wrong? Or if I have something wrong?

Here is my android manifest:
![imagen](https://user-images.githubusercontent.com/51436771/80869314-feec4b80-8c5c-11ea-81c3-0865a994644c.png)

My code where I schedule the alarm:

![imagen](https://user-images.githubusercontent.com/51436771/80869274-c51b4500-8c5c-11ea-8e0a-d5c98f32b8f0.png)

## Environment info

`react-native info` output:

```
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 1.05 GB / 7.86 GB
  Binaries:
    Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 23, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel
x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  Languages:
    Java: 12.0.1 - /c/Program Files/Java/jdk-12.0.1/bin/javac
    Python: 2.7.17 - /c/Python27/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.3.0

Sorry for the last issue, I'm a bit desperate, it's for a final project :(

**Comment by Dallas62** [comment]
Hi @ignacioiglesias43 
Thanks for using the template, I will suggest you to test the version [`3.3.1`](https://github.com/zo0r/react-native-push-notification/releases/tag/3.3.1)
You might need to clean build cache/node_modules and reinstall the application.
Regards,

**Comment by ignacioiglesias43** [comment]
Thank you so much, it worked with updating to the lastest version
