### ISSUE TITLE
The notification icon in Android is not the App icon.

### ISSUE THREAD

**Issue by nbastoWM** [zo0r/react-native-push-notification#14]
The icon that shows in all the notifications is that default Android, not the app icon. 
How can I change it?

**Comment by nbastoWM** [comment]
OK, you have to put the icon as ```ic_launcher.png``` in the mipmap folders.

**Comment by npomfret** [comment]
I have images named _ic_launcher.png_ in each of the `mipmap-...` folders but the icon isn't appearing.  I think maybe my payload is wrong. What should the payload look like? I've followed the instructions on [here](https://developers.google.com/cloud-messaging/concept-options#notifications_and_data_messages) but can't get an icon appearing.

**Comment by connorzg** [comment]
I'm not sure if this is applicable to this repo but here you can [make an ic_notif.png](https://github.com/evollu/react-native-fcm/tree/master/Examples/simple-fcm-client/android/app/src/main/res/mipmap-hdpi)
