### ISSUE TITLE
Can not cancel delivered local notification

### ISSUE THREAD

**Issue by ignacioiglesias43** [zo0r/react-native-push-notification#1401]
# Bug
Hello again, this time I'm trying to cancel a delivered notification with cancelLocalNotifications method, but it seems that is not working.
Am I doing something wrong?

Here is where I send the notification:
![imagen](https://user-images.githubusercontent.com/51436771/80870743-b5542e80-8c65-11ea-906e-4b3f67247c87.png)

Here I'm trying to cancel it:
![imagen](https://user-images.githubusercontent.com/51436771/80870755-cac95880-8c65-11ea-92e0-230a2b400b12.png)

## Environment info

`react-native info` output:

```
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 1.05 GB / 7.86 GB
  Binaries:
    Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 21, 23, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel
x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  Languages:
    Java: 12.0.1 - /c/Program Files/Java/jdk-12.0.1/bin/javac
    Python: 2.7.17 - /c/Python27/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.3.1

**Comment by Dallas62** [comment]
Hi @ignacioiglesias43 
Can you test: https://github.com/zo0r/react-native-push-notification/issues/338#issuecomment-439443666
Regards,

**Comment by ignacioiglesias43** [comment]
It worked, thanks.
