### ISSUE TITLE
Notification Permission Pop up is displaying on app launch

### ISSUE THREAD

**Issue by MaganAnkur** [zo0r/react-native-push-notification#1412]
For some reason the popup asking permission for the push notifications is showing automatically when the app is opened for the first time even if I am configuring Push Notification later in the app.

Please let me know the way how can I stop auto ask permission on app launch.

**Comment by Dallas62** [comment]
Hi @MaganAnkur 
Some details on your implementation is appreciate.
Like the content of `.configure()`
I also suggest you to read this part: https://github.com/zo0r/react-native-push-notification#usage
Regards,

**Comment by MaganAnkur** [comment]
@Dellas62 Below is my content of .configure()
PushNotification.configure({
      onRegister: token => {
        LeanplumManager.setUserPushToken(token.token);
      },
      senderId: Config.FIREBASE_CLOUD_MESSAGING_SENDER_ID,
      requestPermissions: true,
      popInitialNotification: true,
    })

**Comment by Dallas62** [comment]
```js
  /**
   * (optional) default: true
   * - Specified if permissions (ios) and token (android and ios) will requested or not,
   * - if not, you must call PushNotificationsHandler.requestPermissions() later
   * - if you are not using remote notification or do not have Firebase installed, use this:
   *     requestPermissions: Platform.OS === 'ios'
   */
  requestPermissions: true,
```

**Comment by MaganAnkur** [comment]
@Dallas62 I tried changing my .configure() to below 
PushNotification.configure({
      onRegister: token => {
        LeanplumManager.setUserPushToken(token.token);
      },
      senderId: Config.FIREBASE_CLOUD_MESSAGING_SENDER_ID,
      requestPermissions: false,
      popInitialNotification: true,
    }); 

and added PushNotification.requestPermissions() later in the code.

Still I am getting the pop up on app launch.

**Comment by Dallas62** [comment]
Did you wait for an user interaction or you call it in a component on load ?

**Comment by MaganAnkur** [comment]
@Dallas62 
 .configure() is in a componentDidMount with requestPermission:false

and PushNotification.requestPermissions() is in some button click.

**Comment by Dallas62** [comment]
I just try the example application and changed `requestPermissions` to `false`, I'm not able to reproduce.
I will not be able to help with the few informations provided.
Please follow the issue template and provide a reproductible example, without that I cannot help you.

**Comment by MaganAnkur** [comment]
Do you think that it might be an old version issue as I am using 3.1.9

**Comment by Dallas62** [comment]
Are you testing on iOS or Android ? (I guess iOS)
I don't think it's an issue with the version (in this case), can you share the code of the button where the request is made ?

**Comment by Dallas62** [comment]
First of all, are ou sure `onConfirm` is not called at load ? (with `console.log` for example). 
And are you sure this is `react-native-push-notification` which is responsible of the request of permissions ?

**Comment by MaganAnkur** [comment]
I am sure onConfirm is not called on load and the other thing even if I have commented the code for .configure() I was still getting the notification permission pop up.
Can it be some native configuration in AppDelegate.m which is asking the permission?

**Comment by Dallas62** [comment]
If you removed all the code from this library, this is not possible that comes from here.
Maybe some informations in https://github.com/react-native-community/push-notification-ios
Or if you have something like `react-native-permissions`

**Comment by MaganAnkur** [comment]
thanks @Dallas62 for this info, let me check it in my code.

**Comment by MaganAnkur** [comment]
@Dallas62 I checked it in my code and found that no where on app load I am asking for Permission.request('notification') only thing I can see Permission.request('location')
Is there any chances that  request permission can be configured from FireBase on app launch

**Comment by Dallas62** [comment]
A quick test can be done is by removing the library (non uninstall/yarn remove) if it’s still requested it’s not from the library.
Then you will be able to find which library/code is requesting permissions

It can be firebase too

**Comment by MaganAnkur** [comment]
@Dallas62 I have updated React Native Permissions version to make sure that if it is not triggering the pop up.
I am using React Native Permissions for other permission such as Location.

I can see that location pop up is not launching until we request for but Notification permission is coming regardless.

Please share your insights..

**Comment by Dallas62** [comment]
This library doesn’t implement iOS specific code,
If the configuration is made to avoid calling requestPermissions, this can’t come from this library.
You should look at react-native-community/push-notification-ios, which is the library behind.
Maybe a integration bug in AppDelegate.
You can also check the code in the repository of the library (only JS), or add console.log in the node_modules to be sure it comes from the library.

**Comment by MaganAnkur** [comment]
@Dallas62 Thanks fo your input, I did check by doing console.log i node modules and even commenting request permission function call in node modules.
Seems its react-native-community/push-notification-ios which is triggering it.
Could you please give me some insights how can I manage it in react-native-community/push-notification-ios.

Regards

**Comment by Dallas62** [comment]
You will have to share a reproductible project if you wand more help.
I can't do more without codebase 😕

**Comment by MaganAnkur** [comment]
**Solution Alert**
@Dallas62 I found the solution, thanks alot for your inputs.
Below line of code was displaying the permission popup.

`if (notificationCenter) {
          selector = NSSelectorFromString(@"requestAuthorizationWithOptions:completionHandler:");
          IMP method = [notificationCenter methodForSelector:selector];
          void (*func)(id, SEL, unsigned long long, void (^)(BOOL, NSError *__nullable)) =
          (void *) method;
          func(notificationCenter, selector,
                0b111, /* badges, sounds, alerts */
  /*              ^(BOOL granted, NSError *__nullable error) {
                    if (error) {
                        NSLog(@"Leanplum: Failed to request authorization for user "
                              "notifications: %@", error);
                    }
                });
      }`

I commented that and it works.

**Comment by ketan-kumar** [comment]
@MaganAnkur 

I'm currently running in to same issue. Notification permission popup is displaying despite not having any lib except firebase.
Basically, initially i had all the lib (react-native-permission, react-native-push-notification, react-native-comunity/push-notification-ios) and i was facing the same problem. so in order to investigate(what is initiating this popup) i removed the code from where i was configuring the notification instance, removed the permission lib, removed the react-native-push-notification and react-native-comunity/push-notification-ios lib but still popup is coming at app launch.

can you please let me know where you commented the above lines ? Thanks!!

**Comment by MaganAnkur** [comment]
@ketan-kumar it was in AppDelegate where I commented.

**Comment by ketan-kumar** [comment]
@MaganAnkur 

Thanks for reply!! but sorry there are no such lines in my AppDelegate.
Is there anything that could initiate this popup at app launch ? because currently in my app, there is nothing related to permission, notification and their corresponding pods except firebase and i've tried creating the build several time by cleaning the project folder but nothing works for me.

Please help me to sort this out. Thanks!!

**Comment by MaganAnkur** [comment]
Could you pls share you AppDelegate, may be I can see

**Comment by ketan-kumar** [comment]
@MaganAnkur 

Sure!! below you can find it

```
#import <Firebase.h>
#import <UserNotifications/UserNotifications.h>
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#ifdef FB_SONARKIT_ENABLED
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
#ifdef FB_SONARKIT_ENABLED
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"tomo"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  // Define UNUserNotificationCenter
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;

  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

I've already removed the implementation code of `https://github.com/react-native-community/push-notification-ios` from delegate file in order to check whether this lib is the culprit or not...but sadly it was not. popup is still at app launch. Thanks!!!

**Comment by dzpt** [comment]
@Dallas62 why close this issue? 
this issue is persisted until today , i have no idea how do i ask for notif permission lately.
even after removed configure code, the permission is still pop up at launching

**Comment by Dallas62** [comment]
Because there is no reproducible example, and the example project is working fine.
Please diff the example project with your code.
Also iOS issue must be in iOS repository.

**Comment by iamabdulhaseeb** [comment]
This is how I solved it,

as documentation says that do the PushNotification.configure() in index.js, I did like that but I set requestPermissions to false there.

then in screen where I needed permission I simply called .requrePermissions() function on button press and it showed me the dailog to allow or disallow.

**Comment by oscarparedez-eagle** [comment]
> This is how I solved it,
> 
> as documentation says that do the PushNotification.configure() in index.js, I did like that but I set requestPermissions to false there.
> 
> then in screen where I needed permission I simply called .requrePermissions() function on button press and it showed me the dailog to allow or disallow.

Hi. What would be the equivalent for android?
