### ISSUE TITLE
Badge Number and Notification Dissappears when a HeadLess Task is About to Run or is Running

### ISSUE THREAD

**Issue by allindeveloper** [zo0r/react-native-push-notification#1413]
Hello,

Please I need some help,

When setting up a notification. i have configured a task to run at a particular time in the future which is equivalent to the time the headless task is supposed to run. now the headless task is to just play a song...

The issue is as soon as the headless task begins the Notification disappears from the Action Center and the Badge Number dissappears too, i don't get it.

But when there is not headless to run, the Notification stays in the Action Center and the Badge number remain...

Library Version:"react-native-push-notification": "^3.3.0",
Platform: Android
Device manufacturer / model: Google
React Native version "0.62.2"

**Comment by allindeveloper** [comment]
@Dallas62  Please could you take a look at this..

**Comment by Dallas62** [comment]
Hi,
I also have a work to be done, a life, so if you have a reproductible example this will help to solve this issue ASAP 😉

**Comment by allindeveloper** [comment]
Ahh okay..
This is my index.js with the HeadLess Task;
```js
import TrackPlayer from 'react-native-track-player';
import Sound from 'react-native-sound';
import App from './App';
import {name as appName} from './app.json';
import BackgroundFetch from "react-native-background-fetch";
import AsyncStorage from '@react-native-community/async-storage';
import moment from 'moment';

let MyHeadlessTask = async (event) => {
  // Get task id from event {}:
  let taskId = event.taskId;
  console.log('[BackgroundFetch HeadlessTask] start: ', taskId);
  let keys = []
  keys = await AsyncStorage.getAllKeys();
 
  var year = new Date().getFullYear(); //Current Year
  const filteredKeys = keys.filter(key => key!=="userData");
  let returnedMoments = filteredKeys.map(d => moment(d, "x"));
  const filteredMoments = returnedMoments.filter(r => r.isSame(moment(), 'day'));
  console.log("reacher here 4", filteredMoments);

  const returnedValue = filteredMoments[0];
  let data = await AsyncStorage.getItem(returnedValue.valueOf().toString());
  console.log("dataa",data)

  // Required:  Signal to native code that your task is complete.
  // If you don't do this, your app could be terminated and/or assigned
  // battery-blame for consuming too much time in background.
  BackgroundFetch.finish(taskId);
}

// Register your BackgroundFetch HeadlessTask
BackgroundFetch.registerHeadlessTask(MyHeadlessTask);
AppRegistry.registerComponent(appName, () => App);
```

Function is use to register the notification
```js
this.notif.scheduleNotif("",notificationDate,this.state.name,"This is a simple message",
    "#226b6e","This is a  sub Message",this.state.description,extraData,uuidVal)
```
And my `schedule` function in NotifService.js
```js
  scheduleNotif(sound,date,title,message,color,subText,bigText, userInfo,cancelId) {
    // let dirs = RNFetchBlob.fs.dirs
    this.lastId++;
    PushNotification.localNotificationSchedule({
      date: date, // in 10 secs
      //date:date,
      /* Android Only Properties */
      id:cancelId,
      // id: ''+this.lastId, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      ticker: "My Notification Ticker", // (optional)
      autoCancel: true, // (optional) default: true
      largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
      smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
      bigText: bigText, // (optional) default: "message" prop
      subText: subText, // (optional) default: none
      color: color, // (optional) default: system default
      vibrate: true, // (optional) default: true
      vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
      tag: 'some_tag', // (optional) add tag to message
      group: "group", // (optional) add group to message
      ongoing: false, // (optional) set whether this is an "ongoing" notification

      /* iOS only properties */
      alertAction: 'view', // (optional) default: view
      category: null, // (optional) default: null
      userInfo: userInfo, // (optional) default: null (object containing additional notification data)
      /* iOS and Android properties */
      title: title, // (optional)
      message: "My Notification Message", // (required)
      playSound: true, // (optional) default: true
      soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
    });
  }
```

**Comment by allindeveloper** [comment]
Hi @Dallas62 
I Hope the above would help...

**Comment by Dallas62** [comment]
I don't have time to test this since there is blocking issues before, but maybe there is a clear of the notifications when your app is starting. 
I refer to this comment: https://github.com/zo0r/react-native-push-notification/issues/1377#issuecomment-616393946

**Comment by allindeveloper** [comment]
Hmm, but the notification was not cleared by the user, it just clears on its own when the HeadLess task starts to run.

**Comment by Dallas62** [comment]
Maybe you clear notifications at Application Startup, and the code is called even  if its a headless task

**Comment by allindeveloper** [comment]
I dont think so, i never did any operation like that.

**Comment by Dallas62** [comment]
Hum I was looking at your code and maybe you can try to change autoCancel to false:
```js
autoCancel: true, // (optional) default: true
```
Because you use an alarmManager for your headless task so this might be not compatible.
You will need to clear your notifications to remove them on app startup.

Or if `autoCancel` is not working, you can trigger a localNotification in your headless task if this is the same date/time.

**Comment by allindeveloper** [comment]
okay, i'll try these

**Comment by allindeveloper** [comment]
Although i tried what you said, it did not work... and as soon as i opened the app it just Crashed...

Apparently as soon as the Notification has fired and the headless task begins to run... it just clears the notification from the action center and clears the badge number, and then when trying to open the App, it crashes....

Although i found a workaround..
I figured i could make the headless task run about 20000ms behind the data of the notification

```js
 BackgroundFetch.scheduleTask({
            stopOnTerminate: false,
            enableHeadless: true,
            taskId: 'com.foo.customtask',
            delay: this.state.backgroundSeconds - 20000,       // milliseconds
            forceAlarmManager: true,
            periodic: false
          });
```
`where backgroundSeconds is a datetime equivalent to the future date the notification would ring.
And this sort of works for me.. the headless task starts working first.. and the the notification rings...
