### ISSUE TITLE
Support only for Android

### ISSUE THREAD

**Issue by barak109** [zo0r/react-native-push-notification#1414]
I'm looking if there is some official branch for support only android, because i don't need support IOS and if i didn't give IOS the dependency it fall.

Thank you in advance

**Comment by Dallas62** [comment]
Hi @barak109 
Can you provide some example of you code ?
This Library doesn't need to install iOS specific if you need Android-only.

**Comment by barak109** [comment]
I get this error - "Invariant Violation: Native module cannot be null."
The problem come up just after i download the package, my IOS failed with this message, and android works fine.
I didn't use any code from the package.
Env-
 "react-native": "0.62.2",
  "react-native-push-notification": "^3.3.1",

**Comment by Dallas62** [comment]
Do you call the library on iOS ? like `.configure()` or other method ?

**Comment by barak109** [comment]
No i just did yarn add react-native-push-notification
build my project in IOS and the app throw the error.

**Comment by Dallas62** [comment]
I don't unterstand why you want it on Android and not iOS.
I miss something.
the iOS library is `@react-native-community/push-notification-ios`  which is the official library for React-Native (https://reactnative.dev/docs/pushnotificationios).
If you don't include the library this error should not happen and you can suffix your js files with `.android.js` or `.ios.js` to implement specific logic.

**Comment by barak109** [comment]
@Dallas62
  i want to use the Channel id in the android side of the library  because i need it for using react-native-firebase V6 to show the remote  notifications.

I know that "@react-native-community/push-notification-ios" this is the library of the IOS, But i didn't use it anywere in my code, but when i enter to node_modules/react-native-push-notification/package.json

I saw that the library use it as a dependency -
https://github.com/zo0r/react-native-push-notification/blob/master/package.json

**Comment by Dallas62** [comment]
If you think there is a good way to change this, a PR is welcome and I will review it ASAP 😉

**Comment by barak109** [comment]
Ok i get it work, your right thank you :) it was a problem in Xcode it took me a lot of good hours...

And Btw i trying to send local notification and i can see the notification and it's  vibrate but i didn't get sound 
do you know if there is some problem with the latest package - 3.3.1
this is my code 
```

export const androidNotif = (message) => {
  PushNotification.localNotification({
    title: message.data.title,
    message: message.data.body,
    largeIcon: "ic_launcher",
    smallIcon: "ic_notification",
    playSound: true,
    soundName: "default"
  });
};

```

**Comment by Dallas62** [comment]
In the version 3.3.1, this should be fixed in Android.

**Comment by Dallas62** [comment]
I will test sound ASAP but I have some works to be done before 😅

**Comment by barak109** [comment]
@Dallas62 Ok Thanks
 There is some stable version that i can count on it - 100% tested ?
And thank you again i really appreciate that  :)

**Comment by Dallas62** [comment]
This repository has been unmaintained for a long period 1-2 years, I ask for maintainer 1 month ago, and many issues has been fixed but there is some left.
IMO I will not able to refactor the library alone to fix conceptual issue (due to Android Channels) so a good alternative is `react-native-notifications`. They don't have scheduled notifications actually.
If you don't need scheduled notification I think `react-native-notifications` is a good alternative.

**Comment by barak109** [comment]
Maybe it will help someone else -
If you want to support only android after you install the package you will get this error in IOS -
"Invariant Violation: Native module cannot be null."

To fix it as @Dallas62 mention-
https://github.com/zo0r/react-native-push-notification/issues/1414#issuecomment-624037377
You just need to delete index.ios.js in the node_modules/react-native-push-notification/component.
Happy coding :)

**Comment by Dallas62** [comment]
Hi @barak109 
Good to see it does the trick.
To complete, you can also create an intermediate "service" (like notification-service) and add a version for iOS and Android `notification-service.ios.js` and `notification-service.android.js`.
- iOS version will not include the library and do nothing (in your case).
- Android version will implement the logic with the library.

This will avoid `index.ios.js` to be recreate at each `npm install` or `yarn install`.

**Comment by barak109** [comment]
@Dallas62 Thank you
I used this awesome package to deal with the patch - https://www.npmjs.com/package/patch-package
And i did some tests on the latest baranch 3.3.1
doesn't work -
-sound
-tag 
-largeIcon 
So i ended up use 3.2.1 branch there the sound works good - but you can't turn on/ turn off after initialize  it once(maybe this is channel id rule..).
The tag and the largeIcon doesn't work in 3.2.1 either.
I tried to fix it but i didn't have any experience in java.. so i failed 😅
So if you do some fixing in the future i will be glad if they include in it.
Thanks 🥇

**Comment by Dallas62** [comment]
In `3.2.1` there is no default channel, so scheduled notification might be not working weel.

**Comment by strawberry-code** [comment]
Solved by installing `@react-native-community/push-notification-ios` instead of using `react-native` and the run `pod install`.

Wrong import: `import PushNotificationIOS from 'react-native'`.

The good one: `import PushNotificationIOS from '@react-native-community/push-notification-ios'`
