### ISSUE TITLE
Why is fcmToken from Firebase and token received in onRegister for iOS is different?

### ISSUE THREAD

**Issue by Gabsys** [zo0r/react-native-push-notification#1415]
I set up messaging().getToken() from Firebase and also Push Notification from this library. But I realise the token received on iOS is different, why would this happen? On Android, both tokens received are the same

**Comment by Dallas62** [comment]
This Library doesn’t have implementation for iOS so this is the token from push-notification-ios which is APNS token.

**Comment by Gabsys** [comment]
Understood, thanks.

**Comment by tmaly1980** [comment]
@Gabsys This might not answer your question, but messaging().getToken() gets the firebase token, whereas you probably want the APNs token. If you're using something other than firebase (ie Amazon SNS), then you'll need the APNs token for ios devices. There's a dedicated function for that:

https://rnfirebase.io/reference/messaging#getAPNSToken

This has been frustrating me for days (having to mix and match react-native-firebase and react-native-push-notification), and I just stumbled upon it.
