### ISSUE TITLE
Handling onRefreshToken

### ISSUE THREAD

**Issue by tomto1** [zo0r/react-native-push-notification#1416]
# Question
How to handle change token by FCM? I get trigered onCreate when loging in but how to get token changed by FCM when user is loged?

**Comment by Dallas62** [comment]
Hi @tomto1 
On Android, you can use `PushNotificationsHandler.requestPermissions()` this will trigger `onRegister` with the current Firebase token.

**Comment by tomto1** [comment]
onRegister will always get new token from FCM even when user is loged in?

**Comment by Dallas62** [comment]
You can find this information in firebase documentation I guess

**Comment by tomto1** [comment]
Problem is that token changes when user is loged and i don't get new token. I seems that requestPermissions() solves the problem.

**Comment by Dallas62** [comment]
I will change the behavior this weekend to add automatically notify on token change

**Comment by tomto1** [comment]
Is it possible to handle token change when app is in background? Do i need to add listener?
