### ISSUE TITLE
Do scheduled local notifications require the app to be opened?

### ISSUE THREAD

**Issue by kamilklyta** [zo0r/react-native-push-notification#1419]
# Question

Do scheduled local notifications require the app to be opened?

1. Schedule local notifications (Android or IOS).
2. Close app.
3. Nothing happens - no notifications.
4. Open the app - The user receives all scheduled notifications from the period when the app was closed.

Is there a way to receive local notifications even when the app is closed? 🤔

**Comment by Dallas62** [comment]
Hi!
Can you provide more information such as version, configuration, manifest... ? 
This can help to debug 😉

**Comment by kamilklyta** [comment]
Hi!
Version:
```json
"@react-native-community/push-notification-ios": "^1.2.0",
"react-native-push-notification": "3.3.1",
"react-native": "0.59.9",
```
AndroidManifest and other configurations are exactly the same as this provided in readme.md.

**Comment by Dallas62** [comment]
Hi @kamilklyta 
I will take a look at this, I could have seen this behaviour on my App too, but after one day...
I will come back to you ASAP.

**Comment by Dallas62** [comment]
Hi,
Everything is ok for me, can wait tomorrow but maybe you have a battery saving activated or something that postpone the notification.
Android can change the time in some conditions, allow idle might be required if the notification is strictly required at the exact time. Such as important calendar event.

**Comment by kamilklyta** [comment]
Hi @Dallas62.
I accidentally have installed: `react-native-push-notification` package with version `3.1.2`. Updating to `3.3.1` solved this issue 💪 .

When battery-saving activated, notifications are sometimes postponed even for a few hours, but it's like expected behavior on the Android platform. Besides that everything works perfectly! Thanks for your help 🙏 and your precious time 🙏 😃 .

**Comment by Dallas62** [comment]
🎉🎉🎉
