### ISSUE TITLE
Can i handle function when local notification received

### ISSUE THREAD

**Issue by ryujw7** [zo0r/react-native-push-notification#1422]
# Question

I want to put function when local Push notification is received , not tabbed.

Can i implement function when notification received?

**Comment by Dallas62** [comment]
Hi @ryujw7 
I don't fully understand your question, can you provide more information ?
Such as: Which kink of notification, State of the application, ... ?

**Comment by ryujw7** [comment]
> Hi @ryujw7
> I don't fully understand your question, can you provide more information ?
> Such as: Which kink of notification, State of the application, ... ?

I understand this function process when notification received or tabbed the notification.
But when i receiving local notification, this function deos not working and working only tab the notifiaction on foreground.

So i need to know how can i implement function when notification received

```
 onNotification: function (notification) {
    console.log("NOTIFICATION:", notification);

    // process the notification

    // required on iOS only (see fetchCompletionHandler docs: https://github.com/react-native-community/react-native-push-notification-ios)
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },
```

Thank you!

**Comment by Dallas62** [comment]
````js
  // (required) Called when a remote is received in foreground or opened, or local notification is opened
  onNotification: function (notification) {
```
The function is called when remote notification comes and the app is in foreground, and if a local or remote notification is pressed, `onNotification` is called.

**Comment by ryujw7** [comment]
> ```js
>   // (required) Called when a remote is received in foreground or opened, or local notification is opened
>   onNotification: function (notification) {
> ```
> 
> The function is called when remote notification comes and the app is in foreground, and if a local or remote notification is pressed, `onNotification` is called.

@Dallas62 Thanks!

I understand the remote message and local message are different anyway.

You means i can't implement local notification handling like remote notification from firebase?
