### ISSUE TITLE
Your own example is not playing sound as schedule notification not even default sound is played.

### ISSUE THREAD

**Issue by kdpadhiyar** [zo0r/react-native-push-notification#1423]
Please help everyone who is asking for sound problem specially in React-Native..
i have tried everything what i can even all issues related to no sound .
make it working.else remove library.
i have tried your own example too for test but its also not playing sound LOL!!!!!
make it working.
@zo0r @Dallas62 
https://zo0r.me

**Comment by Dallas62** [comment]
Hi @kdpadhiyar 
I will take a look at this, don't forget you can also make PR. We are not paid for maintaining this library.

**Comment by kdpadhiyar** [comment]
@Dallas62  i know this but what to do if its not working.

**Comment by kdpadhiyar** [comment]
@Dallas62 
issue is resolved now.
thank you for your reply.
dont mind my words because community is everything where we can expect solution.Specially in react native.

**Comment by Dallas62** [comment]
I will test this and make changes in example project this week-end.

**Comment by u15767** [comment]
Hi, this really doesn't work. It is not a matter of custom sound. I debugged the code, especially the RNPushNotificationHelper.java

All notifications with default settings will be notified in a channel with the id
`rn-push-notification-channel-id-4-300`
This is the same id as the one generated for the default channel (see method checkOrCreateDefaultChannel), which is generated per default. Unfortunately, this channel is created without any sound. This means, any usage of notfications with all parameters set to defaults will not play sound although the default for sound is to play sound.

I don't know which solution you would prefer. I could think of providing the default sound also for the default notification channel. Another solution could be to ensure that notifications with all defaults used use a different channel.

As I don't want to decide this, I did not make a pull request out of it.

**Comment by kdpadhiyar** [comment]
> I will test this and make changes in example project this week-end.

its working well now. no need to check just mention in doc that for custom sound need to write sound file name directly do not need to write path as mentioned.
Thanks for your efforts
