### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by ssuchanowski** [zo0r/react-native-push-notification#1424]
Not bumping major version with breaking changes will make a lot of people's builds break miserably.

https://semver.org

**Comment by Dallas62** [comment]
Hi @schumannd 
I agree with this, and actually there is no API changes made that breaks the API compatibility.
Recent changes made have breaks builds for two reasons:
- `requestPermissions` which is a cache problem.
- `Java.lang.IllegalStateException: Default FirebaseApp is not initialised in this process [...]. Make sure to call FirebaseApp.initializeApp(Context) first.` Which have been documented and can be avoid with a small change on initialisation (if you don't use Firebase).

In my opinion, builds breaking are not a reason to bump major version.
Most of the changes were fixes and features. This is why minor version were bumped, some possible breaking changes have been marked in `CHANGELOG.md`.
In the future, if the API is no more backward-compatible the major version will be bump.

I think we need to think about end-users, if you install an application which is not able to handle notifications properly on recent Android SDK... It's not better. I totally assume headaches of developers for the well-being of end-users 😉 
Also, If you have any questions Github is open to get replies.

Regards,

**Comment by ssuchanowski** [comment]
cool!

There is an entry that is required to be removed from AndroidManifest - is that breaking anything if not done?

We use the `^` in the lib versions in npm so this changelog saying **breaking change** was an ultra red flag ;)

**Comment by Dallas62** [comment]
You can keep this entry in AndroidManifest, it will print a warning in the log of the device but nothing will crash.
Because it's useless to keep a service that do nothing, I marked it as a breaking change.
Since GCM it deprecated for at least 1 year, all changes about it should not affect someone.

**Comment by ssuchanowski** [comment]
👍
