### ISSUE TITLE
'onNotification' not fired in background - (Android)

### ISSUE THREAD

**Issue by osungjin** [zo0r/react-native-push-notification#143]
Everything works good when app is in the foreground.
But the app is in the background, It doesn't call onNotification function.

How to do it?

RN 0.27+

**Comment by osungjin** [comment]
Ooops. Sorry. I solved it!

**Comment by xphaul** [comment]
@osungjin how did you managed to solve it?

**Comment by osungjin** [comment]
@xphaul It's my a stupid mistake.
`    public void sendNotification(Bundle bundle) {
        Class intentClass = getMainActivityClass();
        if (intentClass == null) {
            return;
        }

        if (bundle.getString("message") == null) {
            return;
        }

        Resources res = mContext.getResources();
        String packageName = mContext.getPackageName();

        String title = bundle.getString("title");
        if (title == null) {
            ApplicationInfo appInfo = mContext.getApplicationInfo();
            title = mContext.getPackageManager().getApplicationLabel(appInfo).toString();
        }
`

It returns null If bundle doen't have message key.
I request testing data without message key.

**Comment by xphaul** [comment]
@osungjin okay thanks gonna check that out
