### ISSUE TITLE
Not getting userInteraction key in Android

### ISSUE THREAD

**Issue by bhadreshg-nimblechapps** [zo0r/react-native-push-notification#1430]
When I get the notification not getting userInteraction key in onNotification called receive data.
I have used 
"react-native": "0.62.2",
"react-native-push-notification": "^3.4.0"

In iOS I have received that key.

**Comment by Dallas62** [comment]
Hi @bhadreshg-nimblechapps 
Can you try this fix:
https://github.com/zo0r/react-native-push-notification/issues/1205#issuecomment-569374091
