### ISSUE TITLE
Documentation for `configure`

### ISSUE THREAD

**Issue by objectiveSee** [zo0r/react-native-push-notification#1433]
# Question

Is there documentation for the `configure` function? I didn't find it in the REAME. Specifically, I was looking to see if there's a promise or some indication of whether it fails or has an error. Thanks!

**Comment by Dallas62** [comment]
Hi,
I don’t fully understand,
The README have the full documentation of `.configure`, nothing more or less.

**Comment by objectiveSee** [comment]
@Dallas62 this README? https://github.com/zo0r/react-native-push-notification/blob/master/README.md

**Comment by Dallas62** [comment]
Exactly, in the usage part (https://github.com/zo0r/react-native-push-notification/blob/master/README.md#usage)
This is not the greatest documentation in the world, but if something can be improve, PR are welcome 😃

**Comment by objectiveSee** [comment]
It's not clear whether there's any error handling,  or if this code example includes all of the keys that can be passed to `configure`. If i figure any of that out Ill try to document it.
