### ISSUE TITLE
Remote notification listener does not occur. (only iOS)

### ISSUE THREAD

**Issue by cnhsttyle** [zo0r/react-native-push-notification#1437]
There are two problems.

The listener does not operate when clicking Notification in the foreground/background state.
(In the quit state, the listener will operate normally when clicking Notification.)
I cannot receive remote notification in the foreground.
To solve this problem,
I have modified the AppDelegate.m file as below.

center.delegate = self;

to

[center requestAuthorizationWithOptions:(UNAuthorizationOptionAlert + UNAuthorizationOptionSound + UNAuthorizationOptionBadge)completionHandler:^(BOOL granted, NSError * _Nullable error) {
if (granted) {
center.delegate = self;
}
}];

After I modified the settings
If I first run after installing the app, it will work normally for two problems
After re-running the app, it will not work normally.

LocalNotification works normally,
There is only a problem with Remote Message.

please help me

**Comment by HVHMobileDeveloper** [comment]
I worked for me

**Comment by Dallas62** [comment]
Hi @cnhsttyle 
Since this library doesn’t include any iOS code, you must look at the right repository:
@react-native/push-notification-ios.
Regards

**Comment by HVHMobileDeveloper** [comment]
Hi @cnhsttyle , I got the same with problem, did you using userInfor?  make sure don't have any the field in the userInfor == null,

**Comment by cnhsttyle** [comment]
@HVHMobileDeveloper 
When sending notification, I added { dryRun, contentAvailable: true, priority: 'high' } as an option value, which solved the problem

thanks.

**Comment by tomasswood** [comment]
I can confirm when sending the notification, `contentAvailable: true` fixes it for me
