### ISSUE TITLE
How can Get Count of Local Notification

### ISSUE THREAD

**Issue by admin2684** [zo0r/react-native-push-notification#1438]
Hi there 
I want using react-native-firebase and this library(react-native-push-notification)
I used react-native-push-notification for handling the notification and display in foreground and setting the badge count.

But I don't know how can get number of notifications available for setting the number of badge

How can do it?

**Comment by Dallas62** [comment]
Hi @admin2684 
You can try `getApplicationIconBadgeNumber()` which is for iOS only:
https://github.com/zo0r/react-native-push-notification#ios-only-methods

**Comment by admin2684** [comment]
thanks 

> Hi @admin2684
> You can try `getApplicationIconBadgeNumber()` which is for iOS only:
> https://github.com/zo0r/react-native-push-notification#ios-only-methods

Thanks
I made a pull request for full support big image and big icon with url
Please see this : #1444
