### ISSUE TITLE
Date format example for daily repeating local notification

### ISSUE THREAD

**Issue by cepem** [zo0r/react-native-push-notification#1439]
I'm trying to set multiple repeating local notifications daily at a specific hour, However I'm not really sure about how I should pass the date.

In order to get a notification each day at 8:30 , I'm calling  localNotificationSchedule like this
```
PushNotification.localNotificationSchedule({
        message: notificationsText[notificationType].text, 
        date: '08:30',
        repeatType: 'day',
      });
```

But I'm getting: `TypeError: details.date.getTime is not a function, (In 'details.date.getTime()', 'details.date.getTime' is undefined)`

What would be a good date format for this?

**Comment by Dallas62** [comment]
Hi @cepem 
https://github.com/zo0r/react-native-push-notification#scheduled-notifications
The date option must be a valid JS Date object, this represent the date for the first notification before repetition.

**Comment by cepem** [comment]
Thanks @Dallas62 .

Is there any way for me to not show older notifications when scheduling?

For example, let's suppose the current hour is 12:00, and I schedule a notification for 07:00, and 13:00.
Currently, as soon as I schedule (at current time 12:00) I'll also see the notification from 07:00 followed up by the other one at 13:00.

What should I do to only display the one from 07:00 starting from tomorrow and not spam the user when scheduling?

**Comment by Dallas62** [comment]
You can add a condition to exclude date in the past and avoid scheduling notification.

**Comment by wmonecke** [comment]
@Dallas62 I am having the same issue. Where would you add this condition? I don't see where we could insert any code to show or hide the notification.

**Comment by Dallas62** [comment]
Hi,
If the date is in the past, the notification will be triggered instantly.
You must check the date in your code to add one day if the current date is in the past.

**Comment by wmonecke** [comment]
@Dallas62 Ah, smart.
Thank you so much!

**Comment by thaopham-pixa** [comment]
Hello, 
I need have with the function like this:
I have an array of items, I want to push an item every day at 9 AM. How should I schedule?
Please help me! Thank you for any help, Thank you so much!

**Comment by adnanaslam475** [comment]
@thaopham-pixa did u find solution? if yes, please share here..

**Comment by adnanaslam475** [comment]
can any one answer @thaopham-pixa question? thanks

**Comment by cepem** [comment]
@adnanaslam475  @thaopham-pixa if what you're saying is that you wanna push out notifications with different text everyday but at the same hour, a quick solution that comes to my mind would be to to use something like moment.js in order to generate an array of dates for each item in your array of texts. 

Your array of dates could be something like: 

`const notificationDates = [new Date("October 13, 2021 09:00:00"), new Date("October 14, 2021 09:00:00"), new Date("October 15, 2021 09:00:00")]`

But you'll have to build it dynamically so you can increment the day. Once you have it, map your array of texts with the array of dates and run the schedule function over them. This isn't really the case for a repeating notification

**Comment by adnanaslam475** [comment]
how it will run if i dont open app for two days?

**Comment by cepem** [comment]
@adnanaslam475 if you run the schedule function on those dates, they will stay scheduled.

**Comment by adnanaslam475** [comment]
even i dont open app for two days, notification will display daily right?

**Comment by adnanaslam475** [comment]
and kindly tell me where do i put time like 10am, 11am...?

**Comment by KinzaShaikh** [comment]
@adnanaslam475 did you find solution for 10 am, 11 am?
