### ISSUE TITLE
Unfortunately, application has stopped

### ISSUE THREAD

**Issue by yond** [zo0r/react-native-push-notification#144]
My app crashes when setting the sender_id field for android.

The error I am getting is:
 
E/AndroidRuntime( 6114): FATAL EXCEPTION: IntentService[RNPushNotification]
E/AndroidRuntime( 6114): Process: com.privpro, PID: 6114
E/AndroidRuntime( 6114): java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
E/AndroidRuntime( 6114): 	at com.google.android.gms.iid.zzd.zzeb(Unknown Source)
E/AndroidRuntime( 6114): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
E/AndroidRuntime( 6114): 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
E/AndroidRuntime( 6114): 	at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
E/AndroidRuntime( 6114): 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
E/AndroidRuntime( 6114): 	at com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService.onHandleIntent(RNPushNotificationRegistrationService.java:20)
E/AndroidRuntime( 6114): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime( 6114): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 6114): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 6114): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by zo0r** [comment]
Related: https://github.com/zo0r/react-native-push-notification/issues/7#issuecomment-170382549

**Comment by raulmt** [comment]
Just in case people find this issue first when searching for this problem: I would say it's more related to #171 . I had Google Repository installed, but v44, because that's the only one my Android Studio version shows me. So then I found about #171 and I tried updating the google play services dependencies as they suggest there (from a failing 8.1.0 to 9.4.0) and now it works.
