### ISSUE TITLE
[Android] setApplicationIconBadgeNumber doesn't work without localNotification

### ISSUE THREAD

**Issue by marioot** [zo0r/react-native-push-notification#1440]
# Bug
Installation method: pod

The setApplicationIconBadgeNumber method doesn't show the badge number. When testing it with a localNotification call however, it is shown.
Also, I have observed that swiping the localNotification removes the badge as well.

It looks like the badge display logic is coupled with the localNotification. Maybe it has something to do with priorities?

## Environment info

System:
    OS: macOS 10.15.3
  Binaries:
    Node: 10.13.0 
    Yarn: 1.15.2 
    npm: 6.4.1 
    Watchman: 4.9.0
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.1, 25.0.2, 26.0.1, 26.0.3, 27.0.3, 28.0.3
      System Images: android-23 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5

Library version: 3.4.0

## Steps To Reproduce

Presume default configuration (as described in the docs)

Just call:
`PushNotification.setApplicationIconBadgeNumber(10);`
Expect the badge showing '10' on the app icon.

By calling:
```
PushNotification.setApplicationIconBadgeNumber(10);
PushNotification.localNotification({
    /* Android Only Properties */
    id: '123', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    ticker: 'My Notification Ticker', // (optional)
    autoCancel: true, // (optional) default: true
    largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
    smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
    bigText: 'My big text that will be shown when notification is expanded', // (optional) default: "message" prop
    subText: 'This is a subText', // (optional) default: none
    color: 'red', // (optional) default: system default
    vibrate: false, // (optional) default: true
    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
    tag: 'some_tag', // (optional) add tag to message
    group: 'group', // (optional) add group to message
    ongoing: false, // (optional) set whether this is an "ongoing" notification
    priority: 'high', // (optional) set notification priority, default: high
    visibility: 'private', // (optional) set notification visibility, default: private
    importance: 'high', // (optional) set notification importance, default: high
    allowWhileIdle: false, // (optional) set notification to work while on doze, default: false
    ignoreInForeground: false, // (optional) if true, the notification will not be visible when the app is in the foreground (useful for parity with how iOS notifications appear)

    /* iOS only properties */
    alertAction: 'view', // (optional) default: view
    category: '', // (optional) default: empty string
    userInfo: {}, // (optional) default: {} (using null throws a JSON value '<null>' error)

    /* iOS and Android properties */
    title: 'My Notification Title', // (optional)
    message: 'My Notification Message', // (required)
    playSound: false, // (optional) default: true
    soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
    number: 2, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
    // repeatType: 'day', // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
    actions: '["Yes", "No"]', // (Android only) See the doc for notification actions to know more
  });
```

While the notification is displayed, the badge is shown as well.

**Comment by Dallas62** [comment]
Hi @marioot 
Unfortunately, I think number in `localNotification` and `setApplictionIconBadgeNumber` can't work together with the stack of badge number in channels/notifications.
Also look to the library behind this feature:
https://github.com/leolin310148/ShortcutBadger

**Comment by marioot** [comment]
Not sure I understand what you mean?

Are you saying that `PushNotification.setApplicationIconBadgeNumber(10);` alone doesn't work and needs to have the notification present at all times?
Since that is what the problem is here.
I don't want to trigger localNotification at all, this is just a way I found to actually get the badge to show.

**Comment by Dallas62** [comment]
if `setApplictionIconBadgeNumber` is not working, take a look to:
https://github.com/leolin310148/ShortcutBadger
This is the library that handle this feature.

**Comment by marioot** [comment]
The thing is, it does work, but coupled with the notification itself.
Which is different to how iOS implementation works.

This is a bug.

I'll look at the suggested library wrapper as an alternative.

**Comment by Dallas62** [comment]
> The thing is, it does work, but coupled with the notification itself.
> Which is different to how iOS implementation works.
> 
> This is a bug.
> 
> I'll look at the suggested library wrapper as an alternative.

Yes this is a bug, but since this bug is not related to this library but it's coming from https://github.com/leolin310148/ShortcutBadger
It will not be fixed in this package.
Feel free to make an issue in https://github.com/leolin310148/ShortcutBadger or a PR to help the maintaner of this package.
If you have any other alternative of `ShortcutBadger`, I will look to integrate it.
Regards,

**Comment by marioot** [comment]
Ok, thanks for the explanation!

**Comment by code-by** [comment]
I have added react-native-push-notification v.6.1.1 into my RN project to show only counter on the app icon on Android. I have RN v.0.60.5.
What steps I need do to use setApplicationIconBadgeNumber? do I need link, manually modify android files, add 3-party modules, etc?
thank you

**Comment by VanessaCarpes** [comment]
a suggestion is to consider dependency with another library, since this one doesn't have commits since 2019 :/

**Comment by Dallas62** [comment]
Hi,

The main reason is that badges are not working like a simple `setBadge()` on Android.

Badge works differently on Android but no one want to use them like defined in Android documentation.

This it's hard to find every documentation of every manufacturer to display a simple number, which an API which change every models. I think there is no alternative.

Consider using badges as described in Android documentation.

Regards

**Comment by minisk93** [comment]
It looks like that badge count started depending on notification presence starting from android 8.0 (api 26).

From android docs:
Starting with 8.0 (API level 26), notification badges (also known as notification dots) appear on a launcher icon when the associated app has an active notification. Users can long-press on the app icon to reveal the notifications (alongside any app shortcuts), as shown in figure 1.
https://developer.android.com/training/notify-user/badges

Except that some of androids can ignore value passed to setApplicationIconBadgeNumber and just display total amount of notifications for app badge
