### ISSUE TITLE
PushNotification.configure error

### ISSUE THREAD

**Issue by dargains** [zo0r/react-native-push-notification#1448]
# Bug

Whenever I run 'PushNotification.configure' I get this error:

TypeError: Cannot read property 'then' of null

```
353 | Notifications.popInitialNotification = function(handler) {
> 354 | 	this.callNative('getInitialNotification').then(function(result){
355 | 		handler(result);
356 | 	});
357 | };
```

## Environment info

`react-native info` output:
System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 6.71 GB / 15.88 GB
  Binaries:
    Node: 14.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 14.0.1
    Python: 3.8.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: ~16.9.0 => 16.9.0
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 3.5.0

## Steps To Reproduce

1. expo init AwesomeProject
2. npm install --save react-native-push-notification
3. follow instructions to configure push
4. expo start

...

Describe what you expected to happen:

1. push configure to work

**Comment by Dallas62** [comment]
Hi,
Is it on iOS or Android?
Did you install react-native/push-notification-ios ?

**Comment by dargains** [comment]
it's android and web. I haven't tested on iOS.

**Comment by Dallas62** [comment]
It looks like the library is not installed/compiled in your application.
