### ISSUE TITLE
Cannot set 'repeatTime' to 1000 milliseconds, 'repeatType': 'time' in iOS

### ISSUE THREAD

**Issue by daheeahn** [zo0r/react-native-push-notification#1451]
In Document,

================================================
Repeating Notifications
(optional) Specify repeatType and optionally repeatTime while scheduling the local notification. Check the local notification example above.

Property repeatType could be one of month, week, day, hour, minute, time. If specified as time, it should be accompanied by one more parameter repeatTime which should the number of milliseconds between each interval.
================================================

I want to ring alarm every seconds.
So, it worked in Android (using repeatTime and repeatType)
But In iOS, it doesn't work

I followed all Issues about this and I tried all I can do
but I can't find any solution. 

If it is impossible, please add this feature!!

**Comment by wmonecke** [comment]
You want to repeat a notification every second and spam the user? There probably is a reason that this is not possible/ is not implemented.

**Comment by Dallas62** [comment]
Hi @daheeahn 
Has @wmonecke mentioned, not sure repeat a notification every second is a good idea.
But, if you need this feature, I suggest you to open an issue in the right repository:
https://github.com/react-native-community/push-notification-ios
I will check this and change the documentation if needed but it seems to be an Android-only option.

**Comment by daheeahn** [comment]
Hi @wmonecke @Dallas62. Thank you for your mentions!

I wanna make alarm application. like 알라미 (This app is on the App Store - Delight Room Co., Ltd.)
So, this feature is needed. 알라미 also send notification like spam 😹
When it is time for the alarm to sound, a push alarm comes one by one every 2-3 seconds. I was wondering how I implemented this. 
I will open this issue to right repository!

🙌 If any of you see this issue know, let me know how to send push alarm every 2~3 seconds! (Please tell me in a way other than the method of making an alarm every 2-3 seconds.) 🙌

**Comment by daheeahn** [comment]
@Dallas62 
And please change document  section
And please change 'Repeating Notifications' section in documnet that 'time' of repeatType is only available for Android.
