### ISSUE TITLE
onNotification fires every time when the app goes from background to foreground

### ISSUE THREAD

**Issue by Eldavid** [zo0r/react-native-push-notification#1455]
Hello!

During my work, I found a bug in my application. So I have tested your `example` application int this repo, where I was able to reproduce it:

0. Build the application for Android.
1. Click Local notification (now) button
2. Kill the application
3. Open it from the notification and close the Alert window
4. Send the application to background
5. Open it again

The Alert will pop up again, however, it displayed once before.

Expected behaviour:
Don't show the notification again, just once. 

Thank you for your help!

**Comment by Eldavid** [comment]
I've tested and it works! Thank you for your fast fix!

**Comment by strawberry-code** [comment]
Happening again.

"@react-native-community/push-notification-ios": "^1.0.6",
"react-native": "0.61.5",

buildToolsVersion = "29.0.2"
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 29
