### ISSUE TITLE
Remove unused notification channels 

### ISSUE THREAD

**Issue by calluna18** [zo0r/react-native-push-notification#1459]
# Question
I wonder if there is any way to remove unused notification channels (generated with another library we used to have before this)?

I am also a bit confused about how to create multiple channels and assign remote notifications to them.

If anyone could answer these questions or help point me towards some good documentation that I have missed I would be very grateful!

Thanks for all of your great work! 🙌

**Comment by Dallas62** [comment]
Hi!
Actually it’s not possible, in the future this would be possible 😉

**Comment by calluna18** [comment]
I see, thanks for a quick response! 😌

**Comment by Dallas62** [comment]
Hi @calluna18 
Can you check and test the version on `dev` ?
I implemented a minimum set of method for channel management, README is up to date.

**Comment by calluna18** [comment]
You are awesome @Dallas62! I just tried out the dev branch and it worked great for listing and removing my old notification channels! 😊

**Comment by Dallas62** [comment]
Hi, the version `4.0.0` has been released, feel free to reopen this issue if something is missing 😉
