### ISSUE TITLE
Message Notifications grouping

### ISSUE THREAD

**Issue by vmenekos** [zo0r/react-native-push-notification#1463]
I can't really find a way of grouping messages from same sender for example.

Current behaviors:
When i set group or id to be the same.. it just replaces the old message notification with the new message notification.
If i don't set id or group to be the same, it just pops new notification.

Expected:
Add new message in current first poped notification.

**Comment by vmenekos** [comment]
Thanks for pointing me on this.
How can i use this unreleased version?

**Comment by lukebars** [comment]
@vmenekos 
in your `package.json`:

`"@react-native-community/push-notification-ios": "github:zo0r/react-native-push-notification#dev",`

**Comment by Linh-Vo** [comment]
I set "groupSummary" is true, but it seems doesn't work. How can I use this feature ? I'm in dev package: github:zo0r/react-native-push-notification#dev
Thanks

**Comment by lukebars** [comment]
@Linh-Vo which platform are you on? Are you setting a `group` variable in notification scheduling?

**Comment by vmenekos** [comment]
@Linh-Vo have you set Notification group, id's etc to match a grouped notification?
I haven't tried dev version yet.. i ll wait for release cause i wouldn't use a not released version in any production.
Maybe it's better to wait for release, then test and get the feedback here for the devs.

**Comment by natasha08n** [comment]
Just tried version from dev branch, it doesn't work for me unfortunately
How my notification body looks
```
{
 id: params.id,
 autoCancel: false,
 color: colors.LUCKY_POINT,
 group: '1234567890',
 groupSummary: true,
}
```
I don't know, probably I used it in a wrong way... help appreciated

**Comment by saranya20-t** [comment]
@natasha08n did you find any solution for this? I'm also facing the same issue in grouping
