### ISSUE TITLE
How to set up notification actions on iOS

### ISSUE THREAD

**Issue by mathiasmoeller** [zo0r/react-native-push-notification#1465]
Is it possible to show notification actions on iOS? 
The [documentation for notification actions](https://github.com/zo0r/react-native-push-notification#notification-actions) refers to this repo for ios:
https://github.com/holmesal/react-native-ios-notification-actions

Sadly it is not maintained anymore. I found [a fork](https://github.com/nvojnovic/react-native-ios-notification-actions) that fixes the build issues.
Nevertheless, it still does not work.
In the documentation of the [iOS Push Notification plugin](https://github.com/react-native-community/push-notification-ios#presentlocalnotification) that is used internally to handle iOS notification, it says that 
> alertAction : The "action" displayed beneath an actionable notification. Defaults to "view". Note that Apple no longer shows this in iOS 10 +

But as far as I know, notification actions are still supported in iOS in general. Is there a way to make this work? Does anyone have a working example of this? Thanks!

My setup is:
- react-native: 0.59.5
- react-native-push-notification: github:zo0r/react-native-push-notification#dev (dev branch to get that lastest fixes for andoird notification actions)
- @react-native-community/push-notification-ios: 1.2.0
- react-native-ios-notification-actions: nvojnovic/react-native-ios-notification-actions

**Comment by Dallas62** [comment]
Hi @mathiasmoeller 
Actually there is no implementation in the library for iOS.
I think in the future we should fork push-notification-ios and add missing features, but this will be hard to maintain both iOS and Android.

**Comment by mathiasmoeller** [comment]
Yes, I agree this is probably a lot of work 😞.

Maybe remove the iOS part then from the documentation? It is at the very end of the [Section about Notification Actions](https://github.com/zo0r/react-native-push-notification#notification-actions).

**Comment by Dallas62** [comment]
I looked on the iOS library, I think we can fork it in the library and unify the interface.
Need some time to dig into it and see what can be done.
Since the iOS library allow different kinds of actions, maybe we can do the same on Android for the next release.

**Comment by Dallas62** [comment]
There is a try in PRs, for reply actions, but I don't like how it's implemented.
https://github.com/zo0r/react-native-push-notification/pull/612
And this PR https://github.com/zo0r/react-native-push-notification/pull/554 introduce this file:
https://github.com/zo0r/react-native-push-notification/pull/554/files#diff-9d57472c44f5636799695075c3ddcc18
Which will allow us more "complex" arguments like:
```js
actions: [{
  id: "yes",
  label: "Yes",
  icon: "..",
  color: ".."
}]
```

**Comment by mathiasmoeller** [comment]
@Dallas62 sorry was on vacation :) Do you think there is any chance these features will find their way into iOS any time soon? 😇

**Comment by Dallas62** [comment]
Hi @mathiasmoeller 
I will release the next version this week but actions for Android only.
I will look at iOS soon, I just need to find time 😄

**Comment by mathiasmoeller** [comment]
I can totally understand :) Just keep me up to date if you are able to work on the iOS part :)

**Comment by shawbedev** [comment]
Hi :) 

Any news on this issue ?

**Comment by GuillaumeMunsch** [comment]
Hi :) 

Any news on this issue ?
