### ISSUE TITLE
TypeError: RNPushNotification.getInitialNotification is not a function

### ISSUE THREAD

**Issue by frangeris** [zo0r/react-native-push-notification#147]
Hi guys,

I'm having some issues, before update to `2.0.1` I was able to call `PushNotification.configure` from `componentWillMount` lifecycle method, but now it throws a warning and the app do not load (white screen).

<img width="1169" alt="screen shot 2016-07-19 at 3 13 06 pm" src="https://cloud.githubusercontent.com/assets/811381/16961322/5c0b0180-4dc3-11e6-8a00-c76e3086b035.png">

Here's the code:

```javascript
import PushNotification from 'react-native-push-notification'

module.exports = React.createClass({
    componentWillMount() {
        PushNotification.configure({
            onNotification: function(notification) {
                console.log(notification)
            },
        })
    },
    ...
})

```
Any idea what could be the problem?

**Comment by frangeris** [comment]
Confirmed @zo0r, I just downgrade to `2.0.0` and the code works, what going on?

**Comment by zo0r** [comment]
@frangeris what version of **RN** are you using? Android or iOS?

**Comment by frangeris** [comment]
`react": "^15.2.1`
`react-native": "^0.29.0`

Android 4.2.2

**Comment by zo0r** [comment]
@frangeris I can't replicate the error, please try restarting the react-native packager and re-compile the project.

**Comment by frangeris** [comment]
Yeah, it seems was catching something.

```bash
rm -rf node_modules/
npm i
npm start -- --reset-cache
react-native run-android
```
Running the above solved the issue.

**Comment by MobiusHorizons** [comment]
I'm seeing this same error, and was unable to solve it with @frangeris solution. I have followed all the requisite steps from the troubleshooting steps. Any Ideas?

**Comment by MobiusHorizons** [comment]
Turns out `react-native link` doesn't seem to do the android side, so I had to follow the manual installation instructions.

**Comment by BAVhel** [comment]
and I have the same problem

**Comment by ahsanshibghotullah** [comment]
I have the same problem, using android 6.0
 "react-native": "0.49.3",
  "react-native-push-notification": "^3.0.1"
any solution?

**Comment by charanjit-singh** [comment]
Getting same error on latest version

**Comment by Dallas62** [comment]
This error is related to iOS,
Please check react-native-community/push-notification-ios.

**Comment by sargamverma** [comment]
I have the same problem, using android 6.0
"react-native": "0.49.3",
"react-native-push-notification": "^3.0.1"
any solution?

**Comment by Dallas62** [comment]
Hi @sargamverma 

This error is related to iOS,
Please check react-native-community/push-notification-ios

**Comment by sargamverma** [comment]
TypeError: RNPushNotification.getInitialNotification is not a function
I am implemented this with Expo ,is this working with Expo Applications?
I have the same problem, using Android 10
"react-native-push-notification": "^3.0.1"
I am using Android 10 
any solution?
