### ISSUE TITLE
Android did not receive remote notifications when app is in foreground

### ISSUE THREAD

**Issue by iarmankhan** [zo0r/react-native-push-notification#1470]
# Bug

App is not receiving any remote notifications when app is in foreground state. Background remote notifications are working correctly. 

I've also set this to `true` in manifest file:

```
<!-- Change the value to true to enable pop-up for in foreground (remote-only, for local use ignoreInForeground) -->
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="true"/>
```

## Environment info

`react-native info` output:

```bash
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
    Memory: 1.22 GB / 7.88 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_221 - C:\Program Files\Java\jdk1.8.0_221\bin\javac.EXE
    Python: 2.7.16 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: 3.5.2

## Steps To Reproduce

1. Install app on real device
2. Get device token and send test message from firebase while app is in foreground
...

Describe what you expected to happen:

1. App should receive notification even in foreground if we specify the line in manifest

Ps. I'm using the example app for now, so the configs are same

**Comment by iarmankhan** [comment]
Hello @Dallas62 

Well if it was a cache issue it should be solved by now, because after posting this issue here I built app multiple times and tested but it's still same.

I also tried it with released app (made using `--variant=release`) and it's same in that too.

**Comment by Dallas62** [comment]
Hi @iarmankhan @apalchys 

I would be please to help you, but I did the exact same test as @apalchys, and all is working as expected...

If appstate == foreground && `com.dieam.reactnativepushnotification.notification_foreground` == true
 - The notification is displayed and `onNotification` is triggered.

If appstate == foreground && `com.dieam.reactnativepushnotification.notification_foreground` == false
 - The notification is **NOT** displayed and `onNotification` is triggered.

Maybe I don't understand the issue, do you have more information like the content of the payload or the full step to reproduce with example project ?

I do all tests for issues on example project.

**Comment by theasc** [comment]
I have the exact same issue, here is my manifest
`<meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
            android:value="true"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
            android:value="Example-Channel"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
            android:value="Super channel description"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
            android:resource="@android:color/white"/>`

**Comment by Dallas62** [comment]
Hi @theasc 

"Having the same issue" is not helping to resolve this.

Can you provide a reproducible example ? Or a complete description on what is working and what is not working.
As I said previously, I tried to reproduce this and all work as expected.

**Comment by theasc** [comment]
Hi @Dallas62, It works now I was just missing the following part: 
<receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

**Comment by iarmankhan** [comment]
Hello @theasc 
Thank you for pointing that out, somehow I missed that. Sorry @Dallas62 for taking your time on this.
Thanks for your great work!
