### ISSUE TITLE
Android always using "Miscellaneous" channel & also creates 2 channels of same name

### ISSUE THREAD

**Issue by iarmankhan** [zo0r/react-native-push-notification#1471]
# Bug

I specified the custom channel name in manifest and installed it on real device. It shows 2 channels with my specified name & description. 

Whenever I send notification from firebase or my server, it will only receive it in "Miscellaneous" channel.

Is there any special param to send from server to receive notification in specific channel?

## Environment info

`react-native info` output:

```bash
 System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
    Memory: 1.22 GB / 7.88 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_221 - C:\Program Files\Java\jdk1.8.0_221\bin\javac.EXE
    Python: 2.7.16 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 3.5.2

## Steps To Reproduce

1. Run example app with firebase setup & send notifications from firebase
...

Describe what you expected to happen:

1. It should only create a single channel
2. App should receive notification in custom channel

## Reproducible sample code

All configs are same as example app

**Comment by Dallas62** [comment]
Hi @iarmankhan 
For the current version (3.5.2) this is the expected behavior since this avoid breaking changes.
For testing purposes, you can test version on `dev` branch.

**Comment by iarmankhan** [comment]
Okay, I'll look for it, thanks. 

Also is there any timeline when it will be available on main branch?

**Comment by Dallas62** [comment]
I target the release for the end of the month,
If you are not using Actions in notification, you should not have other breaking change.

**Comment by joshlbaker** [comment]
> expected behavior since this avoid breaking changes

Can you elaborate on this? How is this expected behavior?
I'm experiencing this issue as well and receiving some complaints. 

Seems like this isn't being set properly 
```
<meta-data
    android:name="com.google.firebase.messaging.default_notification_channel_id"
    android:value="@string/default_notification_channel_id"/>
```

Maybe just let the user set this on their end? Rather than 

```
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_name" android:value=CHANNEL_ID />

```

???

**Comment by Dallas62** [comment]
Through releases, some changes had been adopted but in a wrong way (partial work).
To avoid break the compatibility and make notifications works. There was no channel on previous versions, so wasn't working.

A cleaner channel management has been made on `dev` branch, but it's still not the best way to implement it.
Progressive changes will be made to avoid huge refactor.

**Comment by vermadivyanshu** [comment]
This is happening when i rename the default channel "rn-push-notification-channel-id-4-default-300", by adding the following:
```
<meta-data
        android:name="com.dieam.reactnativepushnotification.notification_channel_name.rn-push-notification-channel-id-4-default-300"
        android:value="Notifications"/>
```
