### ISSUE TITLE
ignoreInForeground on iOS?

### ISSUE THREAD

**Issue by SwordElucidator** [zo0r/react-native-push-notification#1480]
# Question

Hi, since now iOS will also push local notifications to user when app is in foreground, I tried to find a way to disable them but with no success. Currently ```ignoreInForeground``` option is only working on Android. Is there any way to achieve this? Thank you!

**Comment by Dallas62** [comment]
Hi @SwordElucidator 
I think you can achieve this but you will have to look in issues of:
https://github.com/react-native-community/push-notification-ios

I remember some options in `AppDelegate` you can pass to allow/avoid this. (It's also in iOS documentation)

**Comment by SwordElucidator** [comment]
Thanks @Dallas62 
I'll try and get it resolved.

**Comment by stephanoparaskeva** [comment]
Hi @SwordElucidator I'm trying to figure this out and I can't find anything on it. How do you prevent push notification on IOS if app is in foreground for a specific notification?
