### ISSUE TITLE
iOS token are not generated

### ISSUE THREAD

**Issue by sujatha2016** [zo0r/react-native-push-notification#1481]
In iOS if I uninstall current build and again install new one tokens are not generated. After sometime the tokens are generated I don't know how. I added  the below line of codes to check if any error are thrown but nothing coming.
` PushNotificationIOS.addEventListener(
          'registrationError',
          errorAlert => {
            console.log('errorAlert', JSON.stringify(errorAlert));
          },
        );` 
Can someone point our what might be possibly wrong and a final fix for the solution. I do wonder if no one else got this.

**Comment by Dallas62** [comment]
Hi @sujatha2016 
Uninstall will not always refresh the token. If you want this, look at `abandonPermissions`

**Comment by sujatha2016** [comment]
@Dallas62 where do I find that.

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification#abandon-permissions
https://github.com/react-native-community/push-notification-ios#abandonpermissions

**Comment by MehmoodArib** [comment]
@sujatha2016 @Dallas62 
How the solution given by @Dallas62  helped you in fixing this issue?
