### ISSUE TITLE
Can I build a reminder app with this?

### ISSUE THREAD

**Issue by shardy315** [zo0r/react-native-push-notification#1483]
Hello All,

I’d like to build a very basic reminder app. 

The user selects from a drop down if they want this static reminder every 30 or 60 mins, which days of the week and the start time and end time.

Then through a local notification, a static reminder is sent to the user.

Is that possible with this please?

I couldn’t see a repeat notification to be scheduled on a particular day of the week.

Thanks

**Comment by Dallas62** [comment]
Hi @shardy315 
Scheduled notification are made to schedule notification at a particular date.
If you want to set the repetition every monday.
Set a scheduled notification on the next monday, repeat the operation to all monday you need to cover.

**Comment by nastarfan** [comment]
hi @Dallas62 in my use case I want the reminder to be editable, can I set scheduled notification with the same ID as previously set to 'overwrite' the previous one? Or is there a way to cancel the scheduled notification?
thanks in advance

**Comment by Dallas62** [comment]
Hi,
You can cancel a notification if needed

**Comment by nastarfan** [comment]
cool, that'd be the way to go. Thanks
