### ISSUE TITLE
Missing data payload in array returned by getDeliveredNotifications()

### ISSUE THREAD

**Issue by blomax02** [zo0r/react-native-push-notification#1484]
My notification messages have both the notification and data object filled.
When calling the getDeliveredNotifications() on the android side, I get an array of notifications objects as expected, but it doesn’t contain any data payload. It just contain the title, body coming from the notification object part.
From the Android Firebase documentation, it is noted that the Data shall be in the extras of the intent.

Is there any way to get the data payload for each items returned by getDeliveredNotifications()?
Is this supposed to be supported?

**Comment by Dallas62** [comment]
Hi @blomax02 

I’m not sure you can extract data of delivered notifications.
Firebase documentation is about user pressing the notification.

To achieve this, why don’t you push notification with only-data, save data then trigger your notification (postLocalNotification)?

**Comment by blomax02** [comment]
The firebase documentation says that the data is in the intent extras. I really thought that the package would do this automagically for us.
I already thought about doing the "data only/local notfication" trick, but I wanted to be sure if the package supports it or not before going into a redesign.

**Comment by Dallas62** [comment]
@blomax02 The documentation is not saying that:
Data in the extras of the intent is only for payload with notification + data, when the user press the notification.
BUT this kind of payload doesn't trigger background handler.

In Firebase, there is 3 kinds of notifications:
- "Basic notification": Only a message display, no notification handler in the application.
- "Notification with data": Message with data to implement custom interaction when the user press the notification.
- "Data only": The application is trigger, but no direct interaction with the user (can be trigger by the application, but not by default).

https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages

# Handling messages
To receive messages, use a service that extends FirebaseMessagingService. Your service should override the onMessageReceived and onDeletedMessages callbacks. It should handle any message within 20 seconds of receipt (10 seconds on Android Marshmallow). The time window may be shorter depending on OS delays incurred ahead of calling onMessageReceived. After that time, various OS behaviors such as Android O's background execution limits may interfere with your ability to complete your work. For more information see our overview on message priority.

onMessageReceived is provided for most message types, with the following exceptions:

 - **Notification messages delivered when your app is in the background.** In this case, the notification is delivered to the device’s system tray. A user tap on a notification opens the app launcher by default.

- **Messages with both notification and data payload**, when received in the background. In this case, the notification is delivered to the device’s system tray, and the data payload is delivered in the extras of the intent of your launcher Activity.

App state | Notification | Data | Both
-- | -- | -- | --
Foreground | onMessageReceived | onMessageReceived | onMessageReceived
Background | System tray | onMessageReceived | Notification: system trayData: in extras of the intent.
