### ISSUE TITLE
How to setup remote notifications for IOS?

### ISSUE THREAD

**Issue by iarmankhan** [zo0r/react-native-push-notification#1486]
# Question
Hello, sorry if this sounds dumb but I'm very new with IOS development with React Native.
I used the example app to setup localnotification in my app. I also setup the Remote push notifications for android and it's working very well. 

Now I can't get my head around how to set the same for IOS. After reading some articles I get to know I need some type of certificates from apple developer account but all articles were around 2 years old.

Currently I have an apple developer account so I can generate certificated if needed.

Any help will be appreciated. Thank you

EDIT::

Should I follow this steps similar to android ?
![image](https://user-images.githubusercontent.com/40450695/85107603-dd0a5080-b22b-11ea-9d4a-c6fb03655de6.png)

**Comment by Dallas62** [comment]
Hi,
iOS is not using Firebase as Notification Provider,
Refer to this documentation:
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html#//apple_ref/doc/uid/TP40008194-CH8-SW1

**Comment by iarmankhan** [comment]
Thanks for the reply, I didn't know about it. Can you suggest any other library to send FCM notification to IOS?

**Comment by Dallas62** [comment]
Rnfirebase messaging from invertase

**Comment by iarmankhan** [comment]
Thank you.
