### ISSUE TITLE
iOS (13.5.1) - Local Notifications stopped working

### ISSUE THREAD

**Issue by scgough** [zo0r/react-native-push-notification#1487]
# Bug

Local notifications seem to have stopped working in the latest version of iOS for a legacy app I manage. No changes to the notification code have been made for a long time. 

I can check and register for notifications in the app. 
I'm not seeing any error message when a notif tries to fire. 

Are there any known compatibility issues with the latest iOS? I understand there is an older version of the library. 

## Environment info

react 16.8.3
react-native 0.59.9
react-native-push-notification 3.1.2

## Device:
iPhone 11 Pro
iOS 13.5.1

**Comment by Dallas62** [comment]
Hi @scgough 

For iOS m, you should have a look to:

react-native-push-notification-ios for react native community which is the library used.
This library is just a wrapped for ios.
