### ISSUE TITLE
Unable to receive the remote notification from firebase composer

### ISSUE THREAD

**Issue by tomNjerry** [zo0r/react-native-push-notification#1489]
# Bug
- Not able to receive the notification in app, as we are using react-native-firebasev6.2.0 and react-native-push-notification for receiving the notification to the app.

- In app there is the notification setting screen where user can disable/enable the notification for certain task.

- In app when the permission for notification is asked during create account/ sign-in or enabling  the notification we getToken() from the instanceID and generate the token & during disabling the notification & sign-out from app will deleteToken from the InstanceID

- We listen to the notification in App.tsx where we configure push notification were the sender id belong to the firebase project

- We are unable to receive the notification from firebase or backend notification as the token from onRegister token get conflicted with InstanceID -> getToken method
## Environment info

`react-native info` output:

```bash
 System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 25.28 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.20.0 - ~/.nvm/versions/node/v10.20.0/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v10.20.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 24, 25, 27, 28, 29, 30
      Build Tools: 28.0.3, 30.0.0
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: x.x.x

## Steps To Reproduce

1. Create account on app or sign-in to the app
2. Allow the push notification
3. Send notification from Firebase Console/Composer
...

Describe what you expected to happen:

1. Receive Notification on app foreground
2. Receive Notification when app is in background

## Reproducible sample code

```PushNotification.configure({
      //On Notification
      onNotification: (notification) => {
        console.log('Notification Received => ', notification);
      },


      // Android only
      senderID: 'Firebase Project SenderID',
      popInitialNotification: true,
      requestPermissions: true,
    });```

**Comment by Dallas62** [comment]
Hi @tomNjerry,

I'm not sure to understand why you are using both rnfirebase/messaging and this library.
You can combine them but you will have to choose which library handle remote notification and adapt your Manifest based on that.

This issue is probably caused by your application configuration, and I will not be able to help you without a reproduction project.

Regards,

**Comment by tomNjerry** [comment]
- Using both the library as react native firebase v 6.2.0 doesn't support the notification module which was available for v5.x.x
- The notification module support by react-native-firebase v6.2.0 is Notifee which is a paid version if we are building the app in production.
- So used the react-native-push-notification to configure the receiving of  notification to the app in android.
