### ISSUE TITLE
Question about the android build 

### ISSUE THREAD

**Issue by npomfret** [zo0r/react-native-push-notification#149]
I can't get the project to compile in Android Studio with making some changes to the gradle file.  Essentially, I need to add:

```
build script {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
    }
}
```

and 

```
android {
    ...
    repositories {
        maven { url 'http://repo1.maven.org/maven2' }
    }
}
```

Am I doing something wrong?  Or could we get this added to the project if other people are experiencing the same issue.

**Comment by peterpme** [comment]
What are you adding? Maven? Upgrading Gradle?

This sounds like something out of the scope of this project. Thanks

**Comment by npomfret** [comment]
What I mean is the project works fine only if included as a part of a react-native project.  But If I just load this project up on its own into android studio it refuses to compile unless I make these changes.  It seems to me its not a complete build file and cannot be built in isolation.  Unless I've missed something?
