### ISSUE TITLE
Setting a Particular hour for "localNotificationSchedule"

### ISSUE THREAD

**Issue by MidnightCoke** [zo0r/react-native-push-notification#1490]
```
   componentDidMount() {
    let user_date = new Date(Date.now());
    user_date.setHours(9);
    user_date.setMinutes(0);
    console.log(user_date);
    PushNotification.localNotificationSchedule({
      message: 'Added Daily News',
      date: user_date,
      repeatType: 'day',
    });
  }

```

I am trying to set a particular hour to set daily notification. 
I tried to figure out but i couldn't find any solution. I just want to show 1 notification a day. What should i do for set a static hour?

**Comment by Dallas62** [comment]
Hi,

Scheduled Notification `date` is the date of the first notification.
It’s “scheduled” not “repeated”.

If the `date` is in the past this will be triggered instantly. In your example, if the current time is after 9am, the date of the notification is in the past.

Then when the date is pasted, the repeat options is used for scheduling futures notifications.

Please, take a look at #1386

Regards

**Comment by MidnightCoke** [comment]
Thanks man!

Appreciate That.

**Comment by MidnightCoke** [comment]
I have one more question how can i locally daily notification?
