### ISSUE TITLE
Every Day particular hour notification

### ISSUE THREAD

**Issue by MidnightCoke** [zo0r/react-native-push-notification#1491]
How can i repeat every day 9:00 am notification can anyone help me i couldn't find any solution. I'm not using firebase

**Comment by Dallas62** [comment]
Hi,

Has said in #1490

Scheduled your notifications in the future with a repeat interval to 1 day.

You can also setup many scheduled notifications at specific day/time.

Please avoid create many issues.
This kind of issue has already been answered.

Regards,
