### ISSUE TITLE
Add Donate Button/Sponsoring for Maintainers To README

### ISSUE THREAD

**Issue by Faolain** [zo0r/react-native-push-notification#1493]
This is not as much of a feature request as much as it is a request to please add a place where we can donate to the maintainers of this repository. @Dallas62 in particular has been a massive help to myself and to many others and for this reason, deserves to receive some financial compensation for the time spent maintaining such an important and large project. 

For the maintainers maybe in the meantime, you can join the waitlist for https://github.com/sponsors official donation/sponsor support. If you are not able to join the waitlist then adding a donate button to your page would suffice https://github.com/patharanordev/donate-in-git or a cryptocurrency address. 

Thank you again for all your hard work!

**Comment by Dallas62** [comment]
Hi @Faolain 
Thanks for this request ! 🥰 
I set up sponsor buttons in the default "FUNDING" part of Github, through Github Sponsor and BuyMeACoffee for one time donation.
I will try to find more time for this project to offer at least a better documentation. And also try to offer more compatibility between iOS and Android.
Thanks again !
