### ISSUE TITLE
How can we display group notification in android using through this library.

### ISSUE THREAD

**Issue by TrushalRank** [zo0r/react-native-push-notification#1495]
Any one can help me for display push notification in group with this library. I want to display push notification in group like in below image,
![p04uO](https://user-images.githubusercontent.com/49527805/86204705-c77b1c00-bb85-11ea-8999-809e1c586f08.png)

Thanks for the help in advance !!

**Comment by Dallas62** [comment]
Hi,
Can you try the `dev` branch ?
There is changes about group feature.
https://github.com/zo0r/react-native-push-notification/blob/dev/CHANGELOG.md#features

**Comment by TrushalRank** [comment]
@Dallas62 , No I didn't try with dev branch. If it was support in release version then will be good. If i will use dev branch then is it feasible to implement in my live app ?

**Comment by Dallas62** [comment]
I will release this version ASAP, expect for one feature which I'm not sure to keep in (scheduled notification trigger `onNotification` in background).

**Comment by TrushalRank** [comment]
Okay I am waiting for group notification feature in release version.
