### ISSUE TITLE
Banner doesn't show when application is in background or closed.

### ISSUE THREAD

**Issue by TrushalRank** [zo0r/react-native-push-notification#1496]
When I receive remote push notification it **doesn't show banner** when application is in background or closed. 

**I can see the application notification icon in notification bar**, but it doesn't show banner when get the notification.

I have already set channel id and follow the guideline of library. so, if any one can help about that then please freely let me know.

Following configuration for push notification in react-native side.

PushNotification.configure({
  onRegister: function (token) {
    console.log("TOKEN:", token);
  },

  onNotification: function (notification) {
    console.log("NOTIFICATION:", notification);
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },

  // Should the initial notification be popped automatically
  // default: true
  popInitialNotification: true,

  requestPermissions: true,
});

Thanks for the help in advance !!

**Comment by Dallas62** [comment]
Hi @TrushalRank 
Without any example / configuration, how do you expect us to help ?

**Comment by TrushalRank** [comment]
@Dallas62 , Yah i understand I put my react native code now. please check and let me know if need any more info ?

**Comment by Dallas62** [comment]
Which settings did you set in `AndroidManifest` ?
You said `I have already set channel id `, what is the value of the Channel ID ?

**Comment by TrushalRank** [comment]
<meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id"/>
<meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
            android:value="@string/default_notification_channel_id"/>
<meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
            android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION"/>

<meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
           android:value="true"/>

<meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
            android:resource="@color/black"/> 
<meta-data
            android:name="com.dieam.reactnativepushnotification.notification_icon"
            android:resource="@mipmap/ic_stat_notification" />
<receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
</receiver>

<service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
   <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
   </intent-filter>
</service>

**Comment by Dallas62** [comment]
What's the value of:
```xml
<meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id"/>
```

**Comment by Dallas62** [comment]
There is probaly more information here:
https://github.com/zo0r/react-native-push-notification/issues/1479

**Comment by TrushalRank** [comment]
@Dallas62 

<string name="default_notification_channel_id" translatable="false">com.reactnativewithspeedhome.default_channel_id</string>

**Comment by Dallas62** [comment]
There is mode information about this issue in #147
Your channel_id is the wrong one.

**Comment by TrushalRank** [comment]
@Dallas62 , I am getting notification in background mode. just not show the banner popup in notification bar. so, is it related issue with channel_id ?

**Comment by Dallas62** [comment]
Yes this issue is related to the wrong channel ID. Issue #1495 is exactly the same.

**Comment by TrushalRank** [comment]
Okay thanks for the help. I will check with that. :)

**Comment by TommyLeong** [comment]
Hi @Dallas62 im quite puzzled here. Have looked into https://github.com/zo0r/react-native-push-notification/issues/1479 and https://github.com/zo0r/react-native-push-notification/issues/1395

Yet the notification banner still not showing while app in background or kill state.
Here's what I have in my **manifest** for the push notification

```
<uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>


...some other codes...
...some other codes...
...some other codes...
...some other codes...


<meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
                android:value="rn-push-notification-channel-id-4-300"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                    android:value="rn-push-notification-channel-id-4-300"/>
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="rn-push-notification-channel-id-4-300"
            tools:replace="android:value" />

        <!-- Change the value to true to enable pop-up for in foreground (remote-only, for local use ignoreInForeground) -->
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="true"/>
        <!-- Change the value to false if you don't want the creation of the default channel -->
        <meta-data  android:name="com.dieam.reactnativepushnotification.channel_create_default"
                    android:value="true"/>
        <!-- Change the resource name to your App's accent color - or any other color you want -->
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@color/white"/> <!-- or @android:color/{name} to use a standard color -->


        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
         <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

```

**Comment by Dallas62** [comment]
Hi @TommyLeong 
Did you looked at the readme, channel management?
I recommend you to create your custom channel then provide it to the notification (`localNotification`, parameter: `channelId`).

**Comment by TommyLeong** [comment]
@Dallas62  I read the readme. I actually didn't want to create any custom channel, hence I suppose default channel `rn-push-notification-channel-id-4-default-300` is created by the library 

**Receiving payload:**
```
{
  "collapseKey": "com.app.id.mocked",
  "data": {
    "click": "https://www.maskedData.com/",
    "cm_title": "maskedData",
    "deeplink": "myapp://profile",
    "impr": "https://www.maskedData.com/",
    "mediaType": "image",
    "message": "maskedData",
    "notificationid": "maskedData",
  },
  "from": "maskedData",
  "messageId": "maskedData",
  "notification": {
    "android": {
      "sound": "default"
    },
    "body": "maskedData",
    "title": "maskedData"
  },
  "sentTime": maskedData,
  "ttl": 24123200
}
```

Also, this is a remote notification coming from backend 
Here's the updated meta-data at Android Manifest (The permissions remain there in  code...  just showing you the **meta-data** part)
```
<meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="true"/>
        <!-- Change the value to false if you don't want the creation of the default channel -->
        <meta-data  android:name="com.dieam.reactnativepushnotification.channel_create_default"
                    android:value="true"/>
        <!-- Change the resource name to your App's accent color - or any other color you want -->
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@color/white"/> <!-- or @android:color/{name} to use a standard color -->


        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
         <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

**Comment by Dallas62** [comment]
Did you set the default channel of Firebase? In AndroidManifest, like the README suggest ?

**Comment by Dallas62** [comment]
Also,
I recommend you to create a custom channel now, the next version will remove auto-channel creation.

**Comment by TommyLeong** [comment]
Sorry missed out he Default channel of Firebase. Appended, but still the same. 

```
<meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="true"/>
        <!-- Change the value to false if you don't want the creation of the default channel -->
        <meta-data  android:name="com.dieam.reactnativepushnotification.channel_create_default"
                    android:value="true"/>
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="rn-push-notification-channel-id-4-300"
            tools:replace="android:value" />
        <!-- Change the resource name to your App's accent color - or any other color you want -->
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@color/white"/> <!-- or @android:color/{name} to use a standard color -->


        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
         <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

Custom channel would means we'll begin to use local notification instead of remote notification right?

**Comment by Dallas62** [comment]
You can create a custom channel with your own ID, then set this `channelId` for your remote need.
If you create a channel with the id: `my-channel-id`
You can use:
```xml
   <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="my-channel-id"
            tools:replace="android:value" />
```

In the Firebase API, you can also provide the `channelId`. (https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support) 

<img width="876" alt="Capture d’écran 2020-09-22 à 10 29 10" src="https://user-images.githubusercontent.com/3429329/93859875-7f6c2100-fcbe-11ea-9f10-d27371185e78.png">


In you case, I guess the `channelId` is wrong, try: 
```
The pattern of channel_id is:

rn-push-notification-channel-id-(importance: default "4")(-soundname, default if playSound "-default")-(vibration, default "300")
By default, 1 channel is created:

rn-push-notification-channel-id-4-default-300 (used for remote notification if none already exist).
```

So use: **rn-push-notification-channel-id-4-default-300**

**Comment by TommyLeong** [comment]
@Dallas62  to update that I have tried creating custom channel too. `createChannel` is performed after `PushNotification.configure({...})`.  Hmm, still seeing the same result for background notification (banner not showing, notification remains in notification tray). 

**Create Channel**
```
PushNotification.createChannel(
      {
        channelId: "myApp-channel-id", // (required)
        channelName: "myApp-channel", // (required)
        channelDescription: "A custom channel to categorise myApp notifications", // (optional) default: undefined.
        soundName: "default", // (optional) See `soundName` parameter of `localNotification` function
        importance: 4, // (optional) default: 4. Int value of the Android notification importance
        vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
      },
      (created) => console.log(`createChannel returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
    );
```

**Android Manifest**
```
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="true"/>
                    
        <!-- Change the value to false if you don't want the creation of the default channel -->
        <meta-data  android:name="com.dieam.reactnativepushnotification.channel_create_default"
            android:value="false"/>
         <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name.myApp-channel-id"
          android:value="YOUR NOTIFICATION CHANNEL NAME FOR SILENT CHANNEL"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description.myApp-channel-id"
              android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION FOR SILENT CHANNEL"/>

        <!-- Change the resource name to your App's accent color - or any other color you want -->
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@color/white"/> <!-- or @android:color/{name} to use a standard color -->


        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
         <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

**Comment by LightningNemesis** [comment]
Does the app receive notifications even when the app is closed from background (By closing from background I mean, swiping it up from recents in android) ?
Still doesn't work for me :(

**Comment by Dallas62** [comment]
Hi @LightningNemesis 
Please refer to the Channel Management, in the README.
https://github.com/zo0r/react-native-push-notification#channel-management-android
**NOTE: Without channel, notifications don't work**
Regards

**Comment by LightningNemesis** [comment]
@Dallas62 I have setup the custom channel as specified in the link shared by you, here's the code for the same:

`PushNotification.channelExists('rn-push-notification-channel', (exists) => {
    if (!exists) {
      PushNotification.createChannel({
        channelId: '1', // (required)
        channelName: 'new_orders', // (required)
        channelDescription: 'A channel to categorise your notifications', // (optional) default: undefined.
        importance: 4,
        vibrate: true,
      });
    }
  });`

Android Manifest:

` <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
        android:value="true"/>

      <meta-data  android:name="com.dieam.reactnativepushnotification.channel_create_default"
        android:value="false"/>
      <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="1"
            tools:replace="android:value" />

       <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name.1"
          android:value="new_orders"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description.1"
              android:value="A channel to categorise your notifications"/>

      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@color/white"/>
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
        <intent-filter>
          <action android:name="android.intent.action.BOOT_COMPLETED" />
          <action android:name="android.intent.action.QUICKBOOT_POWERON" />
          <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
        </intent-filter>
      </receiver>

      <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
      </service>
`

Using this configuration, I am able to receive notifications when the app is in both foreground and background state. But my requirement is that, I need to receive notifications in the QUIT state as well (swiped up from the recents screen, might as well put it as closed from background). 
My notification handler looks like:

`import React, {useState, useEffect} from 'react';
import PushNotification from 'react-native-push-notification';
import messaging from '@react-native-firebase/messaging';

const NotificationRegister = (setNotifToken) => {
  PushNotification.configure({
    onRegister: function (token) {
      setNotifToken(token.token);
      // console.log('notif token is', token);
    },
    onAction: function (notification) {
      console.log('pressed!!!');
      console.log('ACTION:', notification.action);
      console.log('NOTIFICATION:', notification);
    },

    senderID: '1001591202945',
    permissions: {
      alert: true,
      badge: true,
      sound: true,
    },
    popInitialNotification: true,
    requestPermissions: true,
  });
};

const OnNotification = (getNewOrders = null) => {
  const [shouldPrint, setshouldPrint] = useState(0);
  messaging().onMessage((message) => {
    setshouldPrint(1);
  });

  messaging().setBackgroundMessageHandler(async (remoteMessage) => {
    setshouldPrint(1);
    console.log('Message handled in the background!', remoteMessage);
  });
  PushNotification.configure({
    onNotification: (response) => {
      // navRef !== null ? navRef.current?.navigate('Orders') : null;
      console.log('NOTIFICATION:', response);
      if (getNewOrders !== null) getNewOrders();
      if (shouldPrint) {
        NotificationLocal(response);
        setshouldPrint(0);
      }
    },
  });
};

const NotificationLocal = (response = null) => {
  console.log('Local Notification', response);
  PushNotification.localNotification({
    channelId: '2',
    priority: 'high', // (optional) set notification priority, default: high
    largeIcon: 'ic_launcher', // (optional) default: "ic_launcher". Use "" for no large icon.
    smallIcon: 'ic_launcher',
    ignoreInForeground: false,
    autoCancel: false,

    /* iOS and Android properties */
    vibrate: true, // (optional) default: true
    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
    title: response !== null ? response.data.title : 'Open App for more info!',
    message: `You have recieved a new order!`,
    playSound: true,
    soundName: 'notif.mp3',
  });
};

export {NotificationRegister, OnNotification, NotificationLocal};`

As you can see, I have created the background message handler as well -> messaging().setBackgroundMessageHandler
But even that doesn't get triggered in the QUIT state.

Any help would be hugely appreciated...

**Comment by Dallas62** [comment]
Please refer to changelog to remove deprecated methods/configuration entries:
https://github.com/zo0r/react-native-push-notification/blob/master/CHANGELOG.md#600-2020-09-26

And I notice you create a channel with ID = 1, and try to use the channel with ID = 2

**Comment by LightningNemesis** [comment]
@Dallas62 I have rectified the error, it was regarding the incorrect channel id being used. Now I am receiving notifications when the app is in quit state as well, but I am getting this error:

`No task registered for key ReactNativeFirebaseMessagingHeadlessTask`

whereas I was expecting the notification response like this:

`{
   "channelId": "MyChannel", "color": null, "data": {"order_id": "1"}, "finish": [Function finish], "foreground": true, "id": "140395876", "message": "Open fleksa app for more details!", "priority": "high", "sound": null, "tag": null, "title": "New Order 🎉 No.$1", "userInteraction": false, "visibility": "private"
   }`
   
   I am getting this for foreground and background states, but not for QUIT state. Is there a function that is specifically used to give the response for the APP CLOSED condition.
   
   PS: I am using both react-native-push-notification & @react-native-firebase/messaging, I believe that the `No task registered for key ReactNativeFirebaseMessagingHeadlessTask` is related to the usage of both libraries (I'm not sure on this, read it on another forum), but could you please guide on how to get the notification objects data for the QUIT state?
   
   And also, Thanks a ton for the previous help!!! :)
