### ISSUE TITLE
How to access "this" inside the onNotification?

### ISSUE THREAD

**Issue by nbastoWM** [zo0r/react-native-push-notification#15]
At first I had ```PushNotification.configure({``` in ```index.android.js``` outside the class declaration but now I have it inside the ```componentDidMount```, is anything wrong with this?

Now I want to have access to ```this.state``` inside the ```onNotification``` but I don't know how. 

I tryed to add a ```PushNotification.addEventListener``` to an external method but the class doesn't accept it.

**Comment by zo0r** [comment]
Try [bind](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind) its parent, ex:
```
componentDidMount: function() {
    PushNotification.onNotification(function(notification){
          console.log(this.state);
     }.bind(this));
}
```

**Comment by nbastoWM** [comment]
The gives ```unexpected token``` on the line of the bind.

I tried also to bind the main function:

```
PushNotification.configure({
          /* ... */
          onNotification: function(notification){
              console.log(this.state);
          },
          /* ... */
     }.bind(this));
```

or 

```
PushNotification.configure({
          /* ... */
          onNotification: function(notification){
              console.log(this.state);
          },
          /* ... */
     }).bind(this);
```

or even
```
  onNotification ((notification) => {
          . . .
        }).bind(this),
```

But every try returned an error.

**Comment by zo0r** [comment]
Thats a syntax error, the bind must be attached to the function.

**Comment by nbastoWM** [comment]
I didn't understand. Where is the syntax error? Where can I bind the parent? 

Thanks.

**Comment by Traviskn** [comment]
@nbastoWM Try defining your notification handler as a method on your component, then binding the handler:

```javascript
handleNotification: function(notification) {
  console.log(this.state);
}

componentDidMount: function() {
  PushNotification.configure({
    onNotification: this.handleNotification.bind(this)
  });
}
```

**Comment by mklb** [comment]
I know it´s solved but here is a simpler way

```
      onRegister: (token) => {
        this.handleRegister(token);
      },

      // (required) Called when a remote or local notification is opened or received
      onNotification: (notification) => {
        this.handleNotification(notification);
      },
```

**Comment by yusfarhanchepa** [comment]
@mklb  thanks so much.....
