### ISSUE TITLE
[Suggestions] Best way to implement push notification 

### ISSUE THREAD

**Issue by aravi365** [zo0r/react-native-push-notification#1502]
# Question

I would like to know whats the best way to implement notifications so that it's shown whether the app is in foreground, background or even in killed state? I need to send some  messages with data from backend  so that i need to navigate the user when he opens the notification thats popped.

Which is the best approach?
1. Remote notification with `notification` data
2. a Local notification is invoked  by  sending remote notification with `data` from Backend.

**Comment by Dallas62** [comment]
Hi @aravi365 
There is three kinds of notifications:
- notification only (no data) this is to notify the user without specific action in the application, this doesn’t notify the application when killed and background.
- notification with data, this is when you need to notify the user and trigger a specific action with data, when the application is opened by the user. This doesn’t notify the application when killed and background.
- data only notification, the user will not see any notification. This is to notify the application of new data. Basically you can do whatever you want in a limited timeframe. Such as fetching data, schedule a notification or trigger a local notification.

There is no « better way » all depends on what you want to do.

For the case of « opening the application at a specific screen » notification with data seems to be the good choice.

Regards
