### ISSUE TITLE
wrong handlers for the notification actions event docs?

### ISSUE THREAD

**Issue by chequochuu** [zo0r/react-native-push-notification#1503]
# Question
In the documentation https://github.com/zo0r/react-native-push-notification#2-specify-handlers-for-the-notification-actions. It say that we use ```  DeviceEventEmitter.addListener('notificationActionReceived',callback) ``` to add handler. However it's not working. I change it to ```DeviceEventEmitter.addListener('remoteNotificationReceived',callback)``` and it work. It is strange because I use  PushNotification.localNotificationSchedule(). Any idea?

**Comment by Dallas62** [comment]
Hi @chequochuu 
If you want action in your notification, use the version on `dev` branch.
I will release it this weekend and solve problems with actions 😉

**Comment by Dallas62** [comment]
Hi,
This is now available in `4.0.0`.
