### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by js08** [zo0r/react-native-push-notification#1504]
# Question

Hi,

https://github.com/react-native-community/push-notification-ios

If I try to add the below lines in my app delegaet.m and appdelegate.h, I am getting the below error. Can you tell me how to fix it

error

The following build commands failed:
        CompileC /Users/we3211221/Library/Developer/Xcode/DerivedData/sports-gymcaepvfyaejngctaxndccpulmt/Build/Intermediates.noindex/sports.build/Debug-iphonesimulator/sports.build/Objects-normal/x86_64/AppDelegate.o sports/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

https://gist.github.com/js08/a81fa5698eaeff146ae3d11d3988499

app delegate. m

https://gist.github.com/js08/b73653e9a8e82cc88710a0c26306cba0

appdelegate.h

https://gist.github.com/js08/5b72603b8bd93c64d83e587abca52cb1

**Comment by Dallas62** [comment]
Hi @js08 

First of all remove your gist, there is an API Key in it.

The problem come from the copy and paste,
The `application` function is duplicated and contains three dots.

```

application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  ...
  // Define UNUserNotificationCenter
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;

  return YES;
}
```

Regards

**Comment by js08** [comment]
Hi,

I update dmy code, but still I am facing the build error, can you tell me how to fix it 
AppDelegate.m
https://gist.github.com/js08/c1f20f1d55af32a653da2f0c5ab0866d

AppDelegate.h

https://gist.github.com/js08/b165147622da2995e33d48f5d9b6b903

error

https://gist.github.com/js08/0a5665fecb8865f1b0c6c22a11855c48

** BUILD FAILED **


The following build commands failed:
        CompileC /Users/weew/Library/Developer/Xcode/DerivedData/animal-gymcaepvfyaejngctaxndccpulmt/Build/Intermediates.noindex/animal.build/Debug-iphonesimulator/animal.build/Objects-normal/x86_64/AppDelegate.o animal/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by Dallas62** [comment]
Hi,

I think there an error with this:
```
@end
```
This should be at the end of the file.

There is also API KEY in your error logs, remove it ASAP 😉 

Regards,

**Comment by js08** [comment]
Hi

Thanks for quick response, I tried to do configurations for android too, It changed build,gradle and android manifest file. But still, I am facing the issue. Can you tell me how to fix it

android build gradle
https://gist.github.com/js08/33e6f7899090ddbe7ae759849ff43c65

android manifest

https://gist.github.com/js08/7cfdf50d36ab843fc5bde6b2aaffde14

error
https://gist.github.com/js08/406e33815bed146020cbc0fc5dd099c2

BUILD FAILED in 11s

    at checkExecSyncError (child_process.js:630:11)
    at execFileSync (child_process.js:648:15)
reuiuieruirew/Desktop/codebase/ewiuewiuiuew-4/frontendapp/reiireooier/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
reuiuieruirew/Desktop/codebase/ewiuewiuiuew-4/frontendapp/reiireooier/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
reuiuieruirew/Desktop/codebase/ewiuewiuiuew-4/frontendapp/reiireooier/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
reuiuieruirew/Desktop/codebase/ewiuewiuiuew-4/frontendapp/reiir

**Comment by Dallas62** [comment]
Hi @js08 

Sorry for that but I cannot spend time on this kind of issue.
If there is any problem like that, ai suggest you to use StackOverFlow or read again the documentation

Regards

**Comment by js08** [comment]
@Dallas62 I google but not able to find any solutions, can you tell m how to fix it

**Comment by Dallas62** [comment]
```
reuiuieruirew/Desktop/codebase/ewiuewiuiuew-4/frontendapp/reiireooier/android/app/src/main/AndroidManifest.xml:39:9-40:54: AAPT: error: resource color/white
 (aka com.sei.sep.logistics.reiireooier.dev.dev:color/white) not found.
```

The color value is not define.
https://github.com/zo0r/react-native-push-notification/blob/master/example/android/app/src/main/res/values/colors.xml

The example project is here to help you if there is any installation error, also:
https://github.com/zo0r/react-native-push-notification#android-manual-installation

If not using a built in Android color (@android:color/{name}) for the notification_color meta-data item. In android/app/src/main/res/values/colors.xml (Create the file if it doesn't exist).

```xml
<resources>
    <color name="white">#FFF</color>
</resources>
```
