### ISSUE TITLE
Multiple notifications being assigned

### ISSUE THREAD

**Issue by P0SEID0N** [zo0r/react-native-push-notification#1505]
Hey guys,

So I am using this lib for my notifications for an app I am building and what happens is if you close the app completely and open it back up the notifications are created over and over. 

To block this from happening I added in the "id: ID_HERE" and the userInfo: {id:ID_HERE} into the build for my scheduled notification (note these notifications are set by the app when the app starts up and supposed to go off at a later date. I was under the impression that if I used unique IDs for the ID field that it would overwrite a notification with a new instance if it already existed rather than spamming notifications into the scheduled queue.

Here is my scheduled notifications codeblock: 

`sendScheduledNotification(date, title, message, id) {
      PushNotification.localNotificationSchedule({
          id: id,
          date: new Date(Date.now()+(date*1000)),
          title:title,
          message: message,
          playSound: true,
          soundName: 'default',
          userInfo: {id: id}
      });
  }`

Note that ID is a param that is hardset to be a unique integer value.

Here is an example of a notification being created:

`this.notif.sendScheduledNotification(this.state.timeUntilSpawn*3600, "title", "Timer is up!", this.props.id);`

Any help would be awesome, again I was working under the assumption that if I used say 1 as an id value, if I Tried to set another notification with the ID of 1 then it would overwrite or not put the notification in the queue as they need to be unique ids.

Thanks for your help!

**Comment by Dallas62** [comment]
Hi @P0SEID0N 

If you recreate notifications every time, you can clear them before settings them.

I will look into this case, but it's a strange issue.

**Comment by P0SEID0N** [comment]
Hi @Dallas62 attempted to implement your fix and unfortunately found another bug: #1624
