### ISSUE TITLE
delete notifications from the home screen

### ISSUE THREAD

**Issue by js08** [zo0r/react-native-push-notification#1506]
# Question

Hi,

I am trying to implement delete notifications from the home screen, similar to outlook, is it possible to achieve in react native. I googled for an example, but not able to find anything. Can you share some links for how to implement. Providing screenshots below

![image001](https://user-images.githubusercontent.com/1699943/86600959-5f05b380-bf66-11ea-9d7c-3c1887ddfde8.png)

**Comment by Dallas62** [comment]
Hi @js08 

In the Readme ;)

You assign an id to each notification, then you can cancel them with this id.

https://github.com/zo0r/react-native-push-notification#cancelling-notifications

Regards,

**Comment by js08** [comment]
@Dallas62 will it work for android too?

**Comment by Dallas62** [comment]
yes
