### ISSUE TITLE
Notification actions support

### ISSUE THREAD

**Issue by psrustik** [zo0r/react-native-push-notification#151]
Hi! Thanks for this push-notification module.

Are there any plans for Android Notifications Actions?

![notification_drawer](https://cloud.githubusercontent.com/assets/804867/17095678/a7db4dbe-5277-11e6-8cc7-901933049a5d.png)

**Comment by vikeri** [comment]
Implemented here: https://github.com/zo0r/react-native-push-notification/pull/172

**Comment by npomfret** [comment]
This is master now, but not published yet.  Would you be able to help test it before we push a release out?
