### ISSUE TITLE
Notification pop up doesn't show onNotification triggered for remote notifications

### ISSUE THREAD

**Issue by ZishanK** [zo0r/react-native-push-notification#1513]
# Bug

Remote notification doesn't pop up on Android when app is in background/killed.onNotification method triggered though.
Side note: Notification pop up was working back in version 3.1.3 but now i have upgraded the RN version so it stops working.

## Environment info

`react-native info` output:

OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 56.25 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.7.5 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 

Library version: 4.0.0

## Steps To Reproduce

1. Install & setup react-native-push-notification
2. Use Firebase console to send test message = Notification popup showed but onNotification not triggered
3. Use own api to send notification = Notification popup not showed but onNotification triggered

Describe what you expected to happen:

1.Notification pop up when app is in background/exit

## Reproducible sample code

1. npm i --save react-native-push-notification@3.4.0
2. Set up androidmanifest.xml and gradle file as per instruction
3. Set up code as follow:
           PushNotification.configure({
            onRegister: function (token) {
              console.log("TOKEN:", token);
            },
            // (required) Called when a remote or local notification is opened or received
            onNotification: function(notification) {
              console.log("NOTIFICATION:", notification);
              // required on iOS only 
              notification.finish(PushNotificationIOS.FetchResult.NoData);
            },
            // Android only
            senderID: "XXXXXX", //This is hidden to protect my own project 
            // iOS only
            permissions: {
              alert: true,
              badge: true,
              sound: true
            },
            popInitialNotification: true,
            requestPermissions: true
          })

**Comment by Dallas62** [comment]
Hi @ZishanK 
Take a look to this:
https://github.com/zo0r/react-native-push-notification#channel-management-android
Regards

**Comment by ZishanK** [comment]
this is the notifications that receive:
{"data": {"message": "[Activity] - Fixing test notification in upgrade"}, "finish": [Function finish], "foreground": true, "id": "-1307823152", "userInteraction": false}
and for channel, we are not using any custom channel.

**Comment by Dallas62** [comment]
Did you set up the value of:
```
 <meta-data
      android:name="com.google.firebase.messaging.default_notification_channel_id"
      android:value="@string/default_notification_channel_id" />
```

To: rn-push-notification-channel-id-4-default-300

Maybe something is missing / not clear in the documentation.

**Comment by ZishanK** [comment]
tested by adding this-> 
<meta-data
        android:name="com.google.firebase.messaging.default_notification_channel_id"
        android:value="rn-push-notification-channel-id-4-default-300" />
but still no pop ups.

**Comment by ZishanK** [comment]
actually i've added this implementation "com.google.android.gms:play-services-gcm:16.1.0" to android/app/build.gradle to trigger onNotification, without this line, app kills when onNotification triggers.

**Comment by Dallas62** [comment]
Ho!
Didn't notice, the payload you send is not the payload that should be send in this case.
You send data but you should send a notification.
Two solutions:
- Change the payload of your server from `data` to `notification`
- Trigger local notification with values inside `notification.data` when `onNotification` is triggered.

**Comment by ZishanK** [comment]
Wao, thanks a lot man, you really made my day. Stay blessed.

**Comment by ZishanK** [comment]
hi @Dallas62, pop up still not appearing while app is closed/killed. can you please help a little more, thanks.

**Comment by Dallas62** [comment]
Can you provide all informations ?
- Payload send by the server.
- Content of AndroidManifest (at least notification part).
- content of `.configure()`.

**Comment by ZishanK** [comment]
sure,
Payload send by the server:
{"notification": {"message": "[Activity] - Fixing test notification in upgrade"}, "finish": [Function finish], "foreground": true, "id": "-1307823152", "userInteraction": false}

AndroidManifest:
<application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
                <intent-filter>
                    <action android:name="android.intent.action.BOOT_COMPLETED" />
                </intent-filter>
        </receiver>
            <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="true"/>
       <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
            android:value="..."/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
            android:value="...."/>
            <meta-data
        android:name="com.google.firebase.messaging.default_notification_channel_id"
        android:value="rn-push-notification-channel-id-4-300" />
        
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
            android:resource="@color/orange"/>

content of .configure():
PushNotification.configure({
onRegister: function (token) {
console.log("TOKEN:", token);
},
// (required) Called when a remote or local notification is opened or received
onNotification: function(notification) {
console.log("NOTIFICATION:", notification);
// required on iOS only
notification.finish(PushNotificationIOS.FetchResult.NoData);
},
// Android only
senderID: "XXXXXX", //This is hidden to protect my own project
// iOS only
permissions: {
alert: true,
badge: true,
sound: true
},
popInitialNotification: true,
requestPermissions: true
})

**Comment by Dallas62** [comment]
I think this is the `message` key, which is invalid too.
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Notification
Test by renaming it by `body` or `title`

**Comment by RNTop** [comment]
I am facing similar issue with this. but I am getting this issue for local notification.

**Comment by Dallas62** [comment]
Hi @RNTop 
Like said in an other issue, without informations on your case, can't help.
Follow the issue template and provide your information.
https://github.com/zo0r/react-native-push-notification/issues/new?template=bug_report.md

**Comment by ZishanK** [comment]
@Dallas62 renaming body or title also didn't work, any other suggestion ?

**Comment by PaulGoodDay** [comment]
@ZishanK or @Dallas62 are there any updates to this issue?  What is or should be the format of the payload?

**Comment by Dallas62** [comment]
> @Dallas62 renaming body or title also didn't work, any other suggestion ?

Hi @ZishanK 
You can also change the "notification" key to "data", then when `onNotification(notification)` is triggered, you trigger a local notification with the content of `notification.data`.
Check if there is `userInteraction` to avoid loop on user press.

**Comment by ZishanK** [comment]
@PaulGoodDay  in my case this formate below formate was working for local notifications:
"notification": {
       "title": "Title of Your Notification",
       “message”: "Body of Your Notification"
    }
or if doesn't work then try to change 'message' to 'body' but if we change the "notification" key then probably we could not het the notifications. or follow @Dallas62  last comment. thanks

**Comment by PaulGoodDay** [comment]
> @PaulGoodDay in my case below formate was working for local notifications:
> "notification": {
> "title": "Title of Your Notification",
> “message”: "Body of Your Notification"
> }
> or if doesn't work then try to change 'message' to 'body' but if we change the "notification" key then probably we could not het the notifications. or follow @Dallas62 last comment. thanks

We only use Remote Notifications but I will look to try out both yours and @Dallas62 suggestions. Thank you!

**Comment by PaulGoodDay** [comment]
Remote notifications (on release 4.0.0) are working for us with this payload
`{
    data: {
        // app data
    },
    notification: {
        text: [string],
        title: [string]
    }
}`

**Comment by akashamin1394** [comment]
For remote notifications, this payload works for us. It's strange in the docs it is written `message` but in the code, it reads from `alert`

```
"data": {
        "alert": "Test message",
        "id": 1,
        "title": "Test title",
        "color": "white",
        "priority": "high",
        "channelId": "General"
}
```

**Comment by NightFox-06** [comment]
facing same issue.. notification appears on the notification tray but popup doesn't show.

**Comment by RocKer004** [comment]
Hi, any updates about this ? having the same issue here

**Comment by Dallas62** [comment]
Hi @NightFox-06, @RocKer004 
As mentioned as first answer:
https://github.com/zo0r/react-native-push-notification#channel-management-android
Regards,

**Comment by pravinsphinx** [comment]
@Dallas62 Still facing same issue. When I manually enables show as pop up then its working fine.

**Comment by Dallas62** [comment]
@pravinsphinx The library is not maintained anymore.
Please take look at the Readme.

**Comment by developerUnit-cmd** [comment]
> Did you set up the value of:
> 
> ```
>  <meta-data
>       android:name="com.google.firebase.messaging.default_notification_channel_id"
>       android:value="@string/default_notification_channel_id" />
> ```
> 
> To: rn-push-notification-channel-id-4-default-300
> 
> Maybe something is missing / not clear in the documentation.
 

i got error in proccessing after implementing this

**Comment by shujakhalid19** [comment]
Perhaps you've set up for background notifications only, run your app in background and try sending a notification.

**Comment by AhmadFahim12** [comment]
Hi; I'm also facing the same issue although I figured out to pop up notification in foreground state by configuring local notification for android, but incase of background or killed state the notification comes in the notification bar and doesn't popup, anybody has leads on this please me know. Thanks

`export const notificationConfig = () => {
  // Must be outside of any component LifeCycle (such as `componentDidMount`).
  PushNotification.configure({
    // (optional) Called when Token is generated (iOS and Android)
    onRegister: function (token) {
      console.log('FCM_TOKEN:', token);
    },
    // (required) Called when a remote is received or opened, or local notification is opened
    onNotification: function (notification) {
      const {link} = notification.data;
      if (notification.foreground) {
        if (notification.userInteraction) {
          Linking.openURL(link);
        } else {
          PushNotification.localNotification({
            channelId: 'relatable_channel',
            title: notification.title || 'Default Title',
            message: notification.message || 'Default Message',
            userInfo: notification.data,
            importance: Importance.HIGH,
          });
        }
      } else {
        // Handle remote notifications
        Linking.openURL(link);
      }

      notification.finish(PushNotificationIOS.FetchResult.NoData);
    },

    // (optional) Called when Registered Action is pressed and invokeApp is false, if true onNotification will be called (Android)
    onAction: function (notification) {
      console.log('ACTION:', notification.action);
      console.log('NOTIFICATION:12', notification);

      // process the action
    },

    // (optional) Called when the user fails to register for remote notifications. Typically occurs when APNS is having issues, or the device is a simulator. (iOS)
    onRegistrationError: function (err) {
      console.error(err.message, err);
    },

    // IOS ONLY (optional): default: all - Permissions to register.
    permissions: {
      alert: true,
      badge: true,
      sound: true,
    },

    // Should the initial notification be popped automatically
    // default: true
    popInitialNotification: true,

    /**
     * (optional) default: true
     * - Specified if permissions (ios) and token (android and ios) will requested or not,
     * - if not, you must call PushNotificationsHandler.requestPermissions() later
     * - if you are not using remote notification or do not have Firebase installed, use this:
     *     requestPermissions: Platform.OS === 'ios'
     */
    requestPermissions: true,
  });
};`
