### ISSUE TITLE
onNotification, onAction does not trigger on android

### ISSUE THREAD

**Issue by RNTop** [zo0r/react-native-push-notification#1514]
I am using local notification . so when I click one of notifications received, it is opening the app again. but can't trigger notification's data. it's works fine for iOS

**Comment by Dallas62** [comment]
Hi @RNTop 
Can you use the issue template ?
Without information, I can't help you.

**Comment by RNTop** [comment]
what should I provide to you ?

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification/issues/new?template=bug_report.md
