### ISSUE TITLE
onNotification, onAction does not trigger on Android

### ISSUE THREAD

**Issue by RNTop** [zo0r/react-native-push-notification#1515]
# Bug

## Environment info

`react-native info` output:

```bash
 System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz
    Memory: 8.41 GB / 24.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: 21.0.6113669
  IDEs:
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 4.0.0

My AndroidManifest.xml

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="app.perfect.cli">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.USE_FINGERPRINT" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
       <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
       <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
          <intent-filter>
            <action android:name="android.intent.action.BOOT_COMPLETED" />
          </intent-filter>
      </receiver>
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
      <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService" />
      <service
        android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
        android:exported="false">
        <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
      </service>

      <activity
        android:name=".SplashActivity"
        android:label="@string/app_name"
        android:theme="@style/launchScreen">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                android:value="true"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
          android:value="rn-push-notification-channel-id-4-300"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
              android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION FOR SILENT CHANNEL"/>
      <meta-data
        android:name="firebase_crash_collection_enabled"
        android:value="true"
      />
    </application>

</manifest>

**Comment by Dallas62** [comment]
Thanks for this update,
Can you provide the `.configure()` ?

**Comment by RNTop** [comment]
```
 PushNotification.configure({
      onRegister: function (token) {

      },
      onNotification: (notification) => {
        notification.finish(PushNotificationIOS.FetchResult.NoData);
        const ticketId = safeGetOr(null, 'data.id')(notification)
        console.log('[onNotification]', { ticketId, notification })
        if (ticketId) {
        
        }
      },
      onAction:  (notification) =>{
        console.log("ACTION:", notification.action);
        console.log("NOTIFICATION:", notification);

        // process the action
      },
      // ANDROID: GCM or FCM Sender ID
      senderID: 'my senderId',
      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },

      popInitialNotification: true,
      requestPermissions: true,
    });
```

**Comment by RNTop** [comment]
```
PushNotification.localNotification({ id: ticketid, bigText: message, message, visibility: 'public' , actions: '["View"]',});
```

**Comment by Dallas62** [comment]
There is many indentation on your `.configure()` paste,
If bot done already, put it outside of a component.

**Comment by RNTop** [comment]
what do you mean ?
```
 PushNotification.configure({
      onRegister: function (token) {

      },
      onNotification: (notification) => {
        notification.finish(PushNotificationIOS.FetchResult.NoData);
        console.log('[onNotification]', { ticketId, notification })
      },
      onAction:  (notification) =>{
        console.log("ACTION:", notification.action);
        console.log("NOTIFICATION:", notification);

        // process the action
      },
      // ANDROID: GCM or FCM Sender ID
      senderID: 'my senderId',
      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },

      popInitialNotification: true,
      requestPermissions: true,
    });
```
So this should be like this ?

**Comment by RNTop** [comment]
Let me know correct answer. this is working for you exactly ?
If this is right issue, let's close this issue, Meanwhile you can find out the reason. no need to took a long time for this.

**Comment by Dallas62** [comment]
You probably put the method ` PushNotification.configure()` inside a Component.
This method must be placed outside of a Component.

https://github.com/zo0r/react-native-push-notification/blob/master/example/NotificationHandler.js#L46

**Comment by RNTop** [comment]
hmmm. just put outside of Component. but still not working.

**Comment by RNTop** [comment]
and when I click a notification on foreground , it is reopening .

**Comment by RNTop** [comment]
Nobody want to restart like this

**Comment by Dallas62** [comment]
I don't understand the problem, can you provide what happen and what you expect ?

https://github.com/zo0r/react-native-push-notification#local-notifications

```
invokeApp: true, // (optional) This enable click on actions to bring back the application to foreground or stay in background, default: true
```

```
// (optional) Called when Registered Action is pressed and invokeApp is false, if true onNotification will be called (Android)
onAction: function (notification) {
    console.log("ACTION:", notification.action);
    console.log("NOTIFICATION:", notification);

    // process the action
},
```

https://github.com/zo0r/react-native-push-notification#notification-actions

**Comment by RNTop** [comment]
LOG  NotificationHandler: {"os": "android", "token": "dQyFzWqKSDWODCXQEwREw-:APA91bFk8BnopObjxuxbBRIMQtfKHYW6dBYCK-INkHafg6d1C7XrtDLuk0_nz8fkRGfx8mHaiZ3ZqqeX5glVtTbvaOJ2dOGE491K5amBY8F3mXSfl4wHMagYy8ct6zVqiGXoUhfC3PiT"}
 LOG  NotificationHandler: {"os": "android", "token": "dQyFzWqKSDWODCXQEwREw-:APA91bFk8BnopObjxuxbBRIMQtfKHYW6dBYCK-INkHafg6d1C7XrtDLuk0_nz8fkRGfx8mHaiZ3ZqqeX5glVtTbvaOJ2dOGE491K5amBY8F3mXSfl4wHMagYy8ct6zVqiGXoUhfC3PiT"}
 LOG  []
 LOG  []
 LOG  NotificationHandler: {"os": "android", "token": "cmSiyvwORxij4GX-Lih2zV:APA91bHILZGpg18DWNm_RpQAEs5gc_g2V5khD5lx-vlkSEHsJlAP2SuYzy6GQdzSZS2w8IAz5B4YJjgYAiDws51URAWs7aYakcPwxJwcGReH_S1_x_PR1RnxvKcsON7WA6pNPSP_rKGT"}

**Comment by RNTop** [comment]
Main purpose is to navigate to notification screen with triggered data.
So I don't need to use onAction. just it should be engouh with onNotification.
but it's not working.

**Comment by Dallas62** [comment]
But what is not working ?
The example application is working all as expected and the case you describe is already done by others developer.

Can you elaborate on what you are doing and what is not working ?

**Comment by RNTop** [comment]
invokeApp should be false for android ?

**Comment by Dallas62** [comment]
I don't know what you expect, I can't do more.

**Comment by RNTop** [comment]
hmmm, I want to receive the notification data onNotification  when I click a notification

**Comment by Dallas62** [comment]
Did you try the example project without change ?

**Comment by RNTop** [comment]
Sure

**Comment by RNTop** [comment]
![image](https://user-images.githubusercontent.com/51260671/86942039-4b934d80-c10a-11ea-99eb-6335bcb44d92.png)

**Comment by Dallas62** [comment]
Here a live test of exemple project. Every thing is working as expected.
Since you are not providing complete information on what is working or not, I will not spend more time on this.


Local notification Pressed with https://github.com/zo0r/react-native-push-notification/blob/master/example/App.js#L48
<img width="1071" alt="Capture d’écran 2020-07-08 à 18 02 31" src="https://user-images.githubusercontent.com/3429329/86942371-5919f900-c145-11ea-8cbe-29970a888e8e.png">

Scheduled notification Pressed after killing the application with https://github.com/zo0r/react-native-push-notification/blob/master/example/App.js#L62
<img width="1076" alt="Capture d’écran 2020-07-08 à 18 03 21" src="https://user-images.githubusercontent.com/3429329/86942385-5ddead00-c145-11ea-94d6-d1ae6536a7fd.png">

**Comment by RNTop** [comment]
did you get from that logs onNotification ?

**Comment by RNTop** [comment]
I think you 've got those logs with onAction

**Comment by Dallas62** [comment]
Logs are coming from:
https://github.com/zo0r/react-native-push-notification/blob/master/example/NotificationHandler.js#L5

**Comment by RNTop** [comment]
Thanks sir. I think it is related with notification channel id

**Comment by RNTop** [comment]
I can't get any channels

**Comment by RNTop** [comment]
Would you check my AndroidManifest.xml ?
I know you are so tired . Please help me.

**Comment by Dallas62** [comment]
Is it up-to-date ? What is the Android SDK version ?

https://github.com/zo0r/react-native-push-notification#channel-management-android

Your channel name, should be a human-readable text, but will not cause this issue.

```xml
  <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
      android:value="rn-push-notification-channel-id-4-300"/>
```

Does you notification pop-up to the user ?

**Comment by RNTop** [comment]
no, just it should be show notification at top 
![image](https://user-images.githubusercontent.com/51260671/86944479-7206b800-c10d-11ea-8cb3-743df98ef482.png)

**Comment by Dallas62** [comment]
I mean the Android SDK version of the phone you are testing on.

**Comment by RNTop** [comment]
Oh, it's 24

**Comment by Dallas62** [comment]
There is no need of channels in this version, this is why there is no channel.
Do you try on simulator ?
How the user trigger the notification ?

**Comment by RNTop** [comment]
I am using local notification. for example. if my app show a notification to user , user will click the notification. then it should be open another page. so I was expected I can trigger the clicked time

**Comment by Dallas62** [comment]
Can you provide the complete code were you use `PushNotification.configure` ?

**Comment by RNTop** [comment]
![image](https://user-images.githubusercontent.com/51260671/86946236-b8f5ad00-c10f-11ea-8860-31efb539ee06.png)

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.test">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.USE_FINGERPRINT" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
       <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
       <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
          <intent-filter>
            <action android:name="android.intent.action.BOOT_COMPLETED" />
          </intent-filter>
      </receiver>
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
      <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService" />
      <service
        android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
        android:exported="false">
        <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
      </service>

      <activity
        android:name=".SplashActivity"
        android:label="@string/app_name"
        android:theme="@style/launchScreen">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:screenOrientation="portrait"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
     <meta-data  android:name="com.dieam.reactnativepushnotification.channel_create_default"
                  android:value="true"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                  android:value="false"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
                  android:value="rn-push-notification-channel-id-4-300"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                  android:value="Super channel description"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                  android:resource="@android:color/white"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name.rn-push-notification-channel-id-4-300"
                  android:value="Example-Channel silent"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description.rn-push-notification-channel-id-4-300"
                  android:value="Super channel description for silent channel"/>
      <meta-data
        android:name="firebase_crash_collection_enabled"
        android:value="true"
      />
    </application>

</manifest>

```

**Comment by RNTop** [comment]
Would you send your AndroidManifest file ?

**Comment by RNTop** [comment]
Also I am testing the example folder

**Comment by Dallas62** [comment]
The Android Manifest used is: https://github.com/zo0r/react-native-push-notification/blob/master/example/android/app/src/main/AndroidManifest.xml

**Comment by RNTop** [comment]
Ok, Thanks Sir. Just replaced the Manifest. it's working . So the issue I am getting is coming from Manifest setting.
Really Thanks. :)
