### ISSUE TITLE
Unable to pull device token on android 29/30

### ISSUE THREAD

**Issue by spit4520** [zo0r/react-native-push-notification#1521]
# Bug 
I cannot access the device token from outside the onRegister function. I’m trying to access the device token on subsequent loads to confirm that it’s the same as before. The onRegister function is inaccessible after the initial load, even after deleting the app. 

## Environment info

`react-native info` output:

```bash
 Kernel 5.4
Node 14.5.0
Npm 6.14.5
React 16.9.0
React-native: 0.61.5
```

Library version: 4.0

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by Dallas62** [comment]
Hi,
Just request permission, this will trigger onRegistrationToken.

**Comment by webraptor** [comment]
Same issue. Suggestion doesn't work.
