### ISSUE TITLE
on clicking notification in notification tray , the app does not launch

### ISSUE THREAD

**Issue by mohity777** [zo0r/react-native-push-notification#1523]
# Bug

app does not open/launch when click on notification in the notification tray when app is in background or quit state . i am using react-native-push-notification with cloud messaging v6. After uninstalling react-native-push-notification, it is working fine. But i need to use react-native-push-notification to trigger local notification whenever there is a foreground notification.

## Environment info

System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 1003.05 MB / 7.78 GB
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 30
      Build Tools: 28.0.3, 30.0.0
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  Languages:
    Java: 1.8.0_211
    Python: 3.8.3
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

Library version: x.x.x

## Steps To Reproduce

1. put the app in background or quit state
2. send a notification from firebase console
3. click on the notification on the notification tray.
...

Describe what you expected to happen:

1. app gets open/launch.

What is happening

1. on clicking notification, app is not opened or launched. onNotificationOpenedApp and getInitialNotification handlers are not triggered

**Comment by Dallas62** [comment]
Hi @mohity777,
Can you share the AndroidManifest ?
It’s probably a configuration issue

**Comment by mohity777** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.medicaltranscriber">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />


 

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:usesCleartextTraffic="true"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
        
        <meta-data  android:name="com.dieam.reactnativepushnotification.channel_create_default"
                    android:value="false"/>

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
       <meta-data android:name="com.google.firebase.messaging.default_notification_icon"
    android:resource="@drawable/ic_notification" />
     <meta-data
        android:name="com.google.firebase.messaging.default_notification_color"
        android:resource="@color/pink" />
      <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
    <intent-filter>
      <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
  </service>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

**Comment by thegitparticle** [comment]
Hi, did you find a solution for this?

**Comment by mohity777** [comment]
Nope. I shifted back to previous version for now and not using react-native-push-notification. Are u are facing the same issue? Let me know if you find any solution/
