### ISSUE TITLE
Console log received notification in ios not working

### ISSUE THREAD

**Issue by gibrandev** [zo0r/react-native-push-notification#1526]
I will use received notification in foreground for redux, in android console log received notification in foreground is work. But in ios not working. I dont know this bug or not.
## Environment info
```bash
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
    Memory: 1.06 GB / 6.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 4.0.0

**Comment by Dallas62** [comment]
Hi @gibrandev 
For the iOS version of the library, you should look the repository @react-community/push-notification-ios
This is just a wrapper, probably in issues someone has this kind of issue

**Comment by gibrandev** [comment]
@Dallas62 thanks, but i am have new problem. I am always received userInteraction false, if click notification always userInteraction false. Are you know for this?
