### ISSUE TITLE
Android event on click grouped notifications 

### ISSUE THREAD

**Issue by sebastianor** [zo0r/react-native-push-notification#1527]
# Bug

When I click on the notification group, the application opens without any event but when I am clicking on single notification does it works, example in the video below

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11159141/87400093-a3bdca00-c5b8-11ea-8db4-43395967f06e.gif)

## Environment info

`react-native info` output:

```bash
 // paste it here
System:
    OS: macOS 10.15.3
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 19.61 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-24 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_231 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: x.x.x

## Steps To Reproduce

1. Call local notification four times, and wait few seconds until it will be grouped 
2. Click on group of notifications like on video 

Describe what you expected to happen:

1. When I click on group it should be call any of event to make screen changes in my app 

## Reproducible sample code

Sample code is example attached to this repo, I've only changed method to call local notification:
```
  localNotif(soundName) {
    PushNotification.localNotification({

      title: 'Local Notification', // (optional)
      message: 'My Notification Message', // (required)
    });
  }
```

**Comment by Dallas62** [comment]
Hi @sebastianor 
I tried to reproduce this issue, but actually I'm not able to reproduce it.
Can you share a reproducible repository like in your video ?
Thanks

**Comment by sebastianor** [comment]
Hello @Dallas62, 

Thank You for Your response. Here is sample repository https://github.com/sebastianor/react-native-local-push-sample. When You will run this project just press minimum five times "Local Notification (now) " button and wait until all of them disappear. I've testing it on Android Emulator API level 27

**Comment by Dallas62** [comment]
Hi @sebastianor 
Sorry for the delay, I will take a look tomorrow.
Regards

**Comment by Dallas62** [comment]
Hi,
I think you should probably use the `group` and `groupSummary` system.

You can test it by using:
```js

  localNotif(soundName) {
    this.lastId++;
    PushNotification.localNotification({      
      /* iOS and Android properties */
      title: this.lastId % 5 === 0 ? 'Grouped notification' : 'Local Notification', // (optional)
      message: this.lastId % 5 === 0 ? 'My Grouped notification Message' : 'My Notification Message', // (required)
      group: 'com.exemple.MY_GROUP',
      groupSummary: this.lastId % 5 === 0
    });
  }
```

The default grouping functionality of Android doesn't provide any information about the group or other useful information from my research.
https://developer.android.com/training/notify-user/group

**Comment by dqhung311** [comment]
hi @Dallas62  do you have any progress and solution for this issue?  I am using remote notification.

**Comment by Dallas62** [comment]
Hi @dqhung311 
See the latest comment.
