### ISSUE TITLE
This package Notification pop up is not visible when app in background.

### ISSUE THREAD

**Issue by DeepakWSB** [zo0r/react-native-push-notification#1530]
# Question

Please Read Carefully

I have followed the documentation and settled up all things. Now problem is notification is working on background and foreground but In the foreground, this package UI is visible but in the foreground, android default notification UI is visible instead of this package.

so my question is : 
is this package gives the feature to change android default Ui when the app in background or killed state because I tried multiple ways but the foreground is perfect but in the background this package notification does not work?

What is wrong in background: 

1. The Right side image should not expanded ie I want to disable expand view. (Achieved in foreground)
2. upper left corner logo is in grey mode on different-different mobile. (some mobile shows colored and some in grey)

**Comment by android71Francis** [comment]
Hi @Dallas62 , same concern on my side., 
![Screenshot_1594944490](https://user-images.githubusercontent.com/20632207/87734380-102d0900-c805-11ea-81e8-c3b64924855f.png)

Is possible to use the package UI instead of the android notification UI.?
