### ISSUE TITLE
onNotification is not triggering anything when notification arrives (IOS)

### ISSUE THREAD

**Issue by felire** [zo0r/react-native-push-notification#1531]
# Bug

onNotification method (inside PushNotification.configure) is not triggering the actions when a notification arrives. It's triggering when I click in the notification but not when it arrives. So, what could i do?
## Environment info

Last version of thi library and react-native-push-notification-ios

## Steps To Reproduce

Configure and set all, and then:

```
export const configPushNotifications = () => {
  PushNotification.configure({
    onNotification: function (notification) {
      Alert.alert('pressed in noti');
      // process the notification

      // (required) Called when a remote is received or opened, or local notification is opened
      notification.finish(PushNotificationIOS.FetchResult.NoData);
    },
    senderID: senderId,
    permissions: {
      alert: true,
      badge: true,
      sound: true,
    },
    popInitialNotification: true,
    requestPermissions: true,
  });
};
```

`Alert` is only being called when I press on the notification but not when it arrives and I'am in foreground.

Describe what you expected to happen:

I expect that `onNotification` execute when a notification arrives or when I click on a notification.

**Comment by Dallas62** [comment]
Hi @felire 
For iOS please go to this package:
https://github.com/react-native-community/push-notification-ios

Regards
