### ISSUE TITLE
Notification Actions and NativeEventEmitter

### ISSUE THREAD

**Issue by m-fabry-pripares** [zo0r/react-native-push-notification#1532]
# Question
The documentation for Notification Actions links to an [example](https://github.com/zo0r/react-native-push-notification/issues/151) that uses DeviceEventEmitter to listen for 'notificaitionActionReceived' to realize the Notification Actions.
DeviceEventEmitter is now deprecated, and NativeEventEmitter should be used instead.

How do I handle Notification Actions now? An example would be very helpful.

**Comment by Dallas62** [comment]
Hi @m-fabry-pripares 
Do not refer to this issue for the implementation, but only "what it looks like".
To see an example, refer to the example folder 😉
