### ISSUE TITLE
Is there maximum of local schedule push notification?

### ISSUE THREAD

**Issue by daheeahn** [zo0r/react-native-push-notification#1533]
I wonder if there is maximum(limit) of local schedule push notification in Android, iOS.
Because I made a lot of alarms, so at one point the alarm doesn't sound, and I wonder how many limitations there are.
please answer Android, iOS all!

**Comment by Dallas62** [comment]
Hi @daheeahn 
Yes there is limitations, especially on Android with Samsung devices.

Search in google for:

```
java.lang.SecurityException: !@too many alarms 
```

**Comment by daheeahn** [comment]
Hi! Thanks for quick answer.
Then iOS has no limit?

And It will be great if this info is in README!

**Comment by Dallas62** [comment]
iOS also seems to have a limit of 64.

This kind of information is not specific to React Native, we will not copy and paste iOS and Android documentation, then do the same thing for Firebase and APNS documentation.
A search on Google or Stackoverflow can solve this kind of question.

**Comment by daheeahn** [comment]
Ok I will search on Google! 👍 Thanks @Dallas62
