### ISSUE TITLE
Unable to Avoid create default channel

### ISSUE THREAD

**Issue by dubiao** [zo0r/react-native-push-notification#1537]
#Bug

I added the following line in my <application> tag:
`<meta-data  android:name="com.dieam.reactnativepushnotification.channel_create_default"
          android:value="false"/>`

But the defualt channel aways auto created. 
I've uninstalled and reinstall the app.

**Comment by Dallas62** [comment]
Unable to reproduce and doesn't provide information such as version.

Closing...
