### ISSUE TITLE
Android notifications not popping-up in any of its state(background/foreground/killed), although onNotification is calling

### ISSUE THREAD

**Issue by Reenagrg100** [zo0r/react-native-push-notification#1538]
# Bug

<!--
Hey,
I'm using this library in my project for handling notifications on both ios and android. I'm using APNS for ios and FCM for android. Recently, on 7th July I was facing a similar kind of issue, I debugged it and what I found as a fix is that "firebase-messaging" dependency was missing from my android/app/build.gradle file.

## Environment info

react-native:0.62.2
react-native-push-notification:3.5.2
firebase-messaging: 20.2.1 
and SNS
were used.

But after few days, on next Friday my PN stopped working for android in same codebase. Although it was working fine in IOS.
It was very important feature in my project, so I was scratching my head for 4-5 days continuously I was worried if mistakenly I haven't changed anything. So, I tried with every possible solution. Even I tried to re-configured it from scratch in a fresh project separately but situation didn't change. 
So, the situation was something like that If I try to send a notification from FCM console, I was receiving notification but If I uses SNS console, notification was getting called also I was receiving notification payload in callback, but notification was not showing on my android device.
After trying with other solutions I decided to upgrade it's version from 3.5.2 to 4.0.0 which is recently launched 10 days back but still the problem stayed same.

So, after trying 4-5 days, I just did a hit and try by downgrading its version from 4.0.0 to 3.1.9 and what I saw without any further change I received notification on my android device:) I was happy but also astonished after seeing this weird behavior of library and couldn't figure out what all happen in this.

So, If anyone also faced this kind of issues kindly like this bug and I request community to look at this issue on priority and please provide a clear picture about that

**Comment by Dallas62** [comment]
Sorry, but no information on the issue, and this kind of issue as already been answered.

Closing...
