### ISSUE TITLE
[HeadlessJS] Triggering a local notification in headless mode

### ISSUE THREAD

**Issue by mcgomez** [zo0r/react-native-push-notification#1541]
# Bug

I'm trying to trigger a location notification while in a headless task for Android. For context I'm using https://github.com/transistorsoft/react-native-background-geolocation which allows me to setup headless JS tasks and respond to location events. 
*Note: the other aspects of the headless task run just fine.*

In my headless task I run the following:

```js
new Promise(resolve => {
    const data = {
        ...
    }

    PushNotification.localNotification({
      id: 1,
      data,
      ongoing: false,
      userInfo: { id: 1, ...data },
      title: "Alert",
      message: `Test headless notification`,
    })

    resolve()
})
```

## Environment info

`react-native info` output:

```bash
 System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 44.09 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.1, 29.0.2
      System Images: android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6165589
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: 3.5.2

## Steps To Reproduce

1. Set up headlessJS task with `react-native-background-geolocation`
2. Set a local notification to trigger when in headless mode
3. Start the application on a device
4. Close the application to trigger headless mode

Describe what you expected to happen:

1. I expect the local notification to trigger

**Comment by mcgomez** [comment]
I updated to `4.0.0` and I think this is working fine. Closing for now!

**Comment by Dallas62** [comment]
Hi @mcgomez 
Glad to see it's resolved after upgrading, but there was no changes to fix this use case, feel free to reopen if this is happening again
Regards
