### ISSUE TITLE
local push notification in silent mode

### ISSUE THREAD

**Issue by daheeahn** [zo0r/react-native-push-notification#1546]
Is it possible to make an alarm sound and vibrate when local push notification is set to sound: true, vibrate: true even when the phone is in silent mode? (Android and iOS)

This phone is samsung(Android).
I set local push notification.
I expected alarm ring and vibrate when phone is in silent mode.

![image](https://user-images.githubusercontent.com/38369729/87893929-4b853d00-ca7c-11ea-9c48-feffb95581f5.png)

**Comment by daheeahn** [comment]
On my search, iOS doesn't have solution of ringing sound on silent mode if app is not on background or foreground.

However, if the phone is in silent mode when the app is in the background or in the foreground, it seems that an alarm sound can be caused by any action that adjusts the sound in the app.

**Comment by Dallas62** [comment]
Hi @daheeahn 

This library doesn't allow it, but is you want to implement it on your side, you can change:

https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L930
`USAGE_NOTIFICATION` by `USAGE_ALARM`.

https://developer.android.com/reference/android/media/AudioAttributes#USAGE_ALARM

Depends on the version of Android, but there is different kind of volumes (at least: notification, alarm). Each kink of volume is impacted by silent mode differently. Using the `USAGE_ALARM` use the volume of alarms which is not impacted by silent mode (depend on user settings).

**Comment by daheeahn** [comment]
It doesn't work :(

**Comment by daheeahn** [comment]
I found workaround.
https://github.com/zo0r/react-native-push-notification/issues/1584#issuecomment-671381806
