### ISSUE TITLE
Notification custom sound not working some device like poco f1

### ISSUE THREAD

**Issue by abdulbasitha** [zo0r/react-native-push-notification#1547]
Notification Custom Sound Not working Some device like poco f1 
Any Solution.?

**Comment by VEnom42** [comment]
It's working, but you must to turn on the sound for each new channel on device. Channels created with silent mode by default.

**Comment by Akash9923** [comment]
@VEnom42 can you tell how to turn on sound

**Comment by VEnom42** [comment]
There is no way to do it from your application. User needs to turn on the sound manually from the application settings => notifications.

Wow, there is no independent sound switches for each channel in new MIUI version. Just one - allow sound.


<details>
  <summary>Screenshot from pocophone f1</summary>
  
![image](https://user-images.githubusercontent.com/30623613/92138087-24ba7480-ee38-11ea-9274-58e7e2950373.png)
  
</details>

**Comment by Akash9923** [comment]
@VEnom42  okay. Is there any method to activate custom sound from remote

**Comment by VEnom42** [comment]
Probably you need to add your channel id to the manifest like this:
```xml
 <meta-data
      android:name="com.google.firebase.messaging.default_notification_channel_id"
      android:value="@string/default_notification_channel_id" />
```
https://github.com/zo0r/react-native-push-notification#channel-management-android

I only use local notifications, haven't tried remote ones.

**Comment by Akash9923** [comment]
> Probably you need to add your channel id to the manifest like this:
> 
> ```
>  <meta-data
>       android:name="com.google.firebase.messaging.default_notification_channel_id"
>       android:value="@string/default_notification_channel_id" />
> ```
> 
> https://github.com/zo0r/react-native-push-notification#channel-management-android
> 
> I only use local notifications, haven't tried remote ones.

This worked for me with latest update
