### ISSUE TITLE
OnNotification and onAction is not getting fired

### ISSUE THREAD

**Issue by Badal1234** [zo0r/react-native-push-notification#1548]
I have tested local notification with the example provided but when i clicked on Action button nothing is getting fired.
Please anyone help me in this matter.
Thank You

**Comment by Dallas62** [comment]
Hi
Did you test the example project ?
Did you put `.configure()` outside of any component ?
Did you look at the actions documentation?

**Comment by Badal1234** [comment]
Yes, I have tried all that,but it did not work

**Comment by Dallas62** [comment]
Did you test/run the example project?

Since it's working in it, you probably have an issue in your configuration.

**Comment by Mhd-Emad** [comment]
Hi @Badal1234 
Have you set invokeApp attribute to false?

**Comment by VishalVema** [comment]
I am facing the same issue onaction is not getting fired.

**Comment by fikribasa** [comment]
also me, but when i press the notification it fire onNotification event

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md#about-notifications

**Comment by iamamar11** [comment]
for OnAction function to work action attributes need to be included.
`PushNotification.localNotification({
            channelId: "YOUR_CHANNEL_ID",
            title: title, // (optional)
            message: message, // (required)
            vibrate: true,
            actions: ["Yes", "No"],  // Android only
          })`
