### ISSUE TITLE
I can't see background notification data

### ISSUE THREAD

**Issue by yusufsancakk** [zo0r/react-native-push-notification#1550]
Hello, 
I initiate a manual notification in the background with a request from the server. I can see the data when I receive the notification when the application is open, but when the application is closed, there is no data when I click on the notification

I did it by double checking the settings again. the notification receive is OK, but I cannot get the data.

**what i want:** whenI click on the notification, the application should open and open a page according to the data. (not if there is data or not, according to the user id. There is always data in it)

**Comment by Dallas62** [comment]
Hi @yusufsancakk 
Can you provide information ?
You are talking about notification/data and probably logs but there is nothing in the issue.
How can we help you with out:
- Notification payload
- `.configure()`
and probably the code that should handle redirection ?

**Comment by yusufsancakk** [comment]
I send a notification through my server and it contains data. so far it's not about your library. If it's been 1 hour, I create a notification with your library in the background;

`PushNotification.localNotification({
          smallIcon: 'ic_noti_icon',
          title: remoteMessage.data.title,
          message: "Haberin detayını okumak için dokunun",
        });`

I get a notification, but when I click on the notification, I can't see the data. Trying to capture actions like this in ComponentDitMount on App.js page: 

`async componentDidMount(){

    PushNotification.configure({
      
      onRegister: function (token) {
        console.log("TOKEN:", token);
      },

      onNotification: function (notification) {
        console.log("NOTIFICATION:", notification);
      },

      onAction: function (notification) {
        console.log("ACTION:", notification.action);
        console.log("NOTIFICATION:", notification);
      },

      onRegistrationError: function(err) {
        console.error(err.message, err);
      },

      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },

      popInitialNotification: true,

      requestPermissions: true,
      
    });`


If the application is open;
onNotification () works but Action () doesn't work when I click

If the application is closed;
nothing happens when i click all logs are empty

**Comment by Dallas62** [comment]
hi @yusufsancakk 
The problem is that you are trying to catch background task in a component.
You must put `.configure()` and any logic that run in background outside of a component.

`onAction` is called only when the application is in background and `invokeApp` is `false` and also there is actions set, it's not the case in your example.

**Comment by yusufsancakk** [comment]
how can i solve this? When I send a data in the notification and start the application, how do I show that data?

**Comment by Dallas62** [comment]
I don't see any data in your provided code.

**Comment by Dallas62** [comment]
If you need no forward data in the localNotification, you can use:
```js
PushNotification.localNotification({ smallIcon: 'ic_noti_icon', title: remoteMessage.data.title, message: "Haberin detayını okumak için dokunun",  data: remoteMessage.data  });
```

**Comment by yusufsancakk** [comment]
I check the incoming data and send it, but I cannot receive the data. I tried invokeApp. Only the token getToken is working. I can't get actions and data
`[Wed Jul 22 2020 14:49:53.157]  LOG      TOKEN: {"os": "android", "token": "dgNzLtwCTiSj15-zR1d7Ew:APA91bEFfKDJ8SoK5sE_61s0KoiVCVPGWdYJgD1Jcglw8RevNcpuYcQbT3KVcWG6S63UHq6rxptr6cExXcRzjj0FQLODjGPFYjrxrA0MOfqJEonUX-kKvcgsx1u82EgQB5HsvvOe_xgW"}`

**Comment by yusufsancakk** [comment]
I check the incoming data and send it, but I cannot receive the data. I tried invokeApp. Only the token getToken is working. I can't get actions and data
`[Wed Jul 22 2020 14:49:53.157]  LOG      TOKEN: {"os": "android", "token": "dgNzLtwCTiSj15-zR1d7Ew:APA91bEFfKDJ8SoK5sE_61s0KoiVCVPGWdYJgD1Jcglw8RevNcpuYcQbT3KVcWG6S63UHq6rxptr6cExXcRzjj0FQLODjGPFYjrxrA0MOfqJEonUX"}`

**Comment by Dallas62** [comment]
Did you put the `.configure()` outside of the component `App` ?

**Comment by yusufsancakk** [comment]
.configure() in componentDidMount ()

**Comment by Dallas62** [comment]
Don't do that, put it outside of ANY component

**Comment by yusufsancakk** [comment]
Yeah! When I wrote other than App.js, I was able to see the data when the background notification came. But I want to capture the data when I click. Not when the notification arrives

**Comment by Dallas62** [comment]
Then you need to use `PushNotification.getInitialNotification(callback)` to get the notification that open the Application

**Comment by yusufsancakk** [comment]
Yes. I get such an error when I use it

`Possible Unhandled Promise Rejection (id: 4):
TypeError: _reactNativePushNotification.default.getInitialNotification is not a function. (In '_reactNativePushNotification.default.getInitialNotification()', '_reactNativePushNotification.default.getInitialNotification' is undefined)
componentDidMount$`

**Comment by Dallas62** [comment]
Sorry, on this library it's `popInitialNotification`, this was the iOS library method.

**Comment by yusufsancakk** [comment]
so there is no solution for android?

**Comment by yusufsancakk** [comment]
I ran the popInitialNotification function for android but i see 'null' in log

**Comment by Dallas62** [comment]
There is probably an activity that intercept the notification, look in issues, this case has been already reported and sovled.

**Comment by KPS250** [comment]
@yusufsancakk can you try hitting the below API from the postman with the required headers & body. Jut wanted to check if you are passing the payload correctly for Android.

To see how the custom data is nested for different app states like foreground/killed you can refer the below post
[https://medium.com/enappd/firebase-push-notifications-in-react-native-apps-d9f60726ce9c](https://medium.com/enappd/firebase-push-notifications-in-react-native-apps-d9f60726ce9c)

FCM API: [https://fcm.googleapis.com/fcm/send](https://fcm.googleapis.com/fcm/send)

HEADERS:
Authorization: key=YOUR_SERVER_KEY,
Content-Type: application/json

BODY: 
{
 "to" : "YOUR_DEVICE_TOKEN",
 "notification" : {
     "body": "Body of Your Notification",
     "title": "Title of Your Notification"
 },
 "data" : {
     "campaign_id" : 45,
     "body": "Body of Your Notification",
     "title": "Title of Your Notification"
 }
}

**Comment by yusufsancakk** [comment]
@Dallas62 I couldn't find the solved issu. Can you send the link? and it doesn't even work on the first line in a new project

**Comment by Dallas62** [comment]
Check this one:
https://github.com/zo0r/react-native-push-notification/issues/1378#issuecomment-621300329

**Comment by yusufsancakk** [comment]
Solved the problem and to explain;
Splash Screen library prevents sending data to a MainActivity
When editing SplashActivity file as below, the problem is solved and popInitialNotification is working


```
protected void onCreate(Bundle savedInstanceState) {
       super.onCreate(savedInstanceState);
       Intent intent = new Intent(this, MainActivity.class);
       intent.putExtras(getIntent().getExtras()); //added this line
       startActivity(intent);
       finish();
}
```

**Comment by marudy** [comment]
@yusufsancakk thanks for the suggested solution. Can you advice regarding `SplashActivity.java` file ? I don't see this file neither on the native android files of `react-native-responsive-screen` nor on the android RN project itself. Did you create this or ... ? I need just some basic details to get this up and running, thanks :)

**Comment by matanrokach** [comment]
@yusufsancakk you saved my day!! I was looking for this solution for a couple of days!

**Comment by yusufsancakk** [comment]
> @yusufsancakk önerilen çözüm için teşekkürler. `SplashActivity.java`Dosyayla ilgili tavsiye verebilir misiniz ? Bu dosyayı ne yerel android dosyalarında `react-native-splash-screen`ne de android RN projesinin kendisinde görmüyorum . Bunu sen mi yarattın yoksa ... Bunu çalışır hale getirmek için sadece bazı temel ayrıntılara ihtiyacım var, teşekkürler :)

Yes. I created the SplashScreen.java file. You can do this by reading this article: https://medium.com/@appstud/add-a-splash-screen-to-a-react-native-app-810492e773f9

**Comment by yusufsancakk** [comment]
@marudy Yes. I created the SplashScreen.java file. You can do this by reading this article: https://medium.com/@appstud/add-a-splash-screen-to-a-react-native-app-810492e773f9
