### ISSUE TITLE
Notifications not received on Android Release Build

### ISSUE THREAD

**Issue by KPS250** [zo0r/react-native-push-notification#1551]
# Bug
Notifications on working well on Android debug build but not on the release build

## Environment info
"react-native-push-notification": "^4.0.0",

`react-native info` output:
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 50.96 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.0.0 - /usr/local/bin/node
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.2, 28.0.3, 29.0.2
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Steps To Reproduce
1. Create a debug build and test it. It works.
2. Create a Release build and then test it. It doesn't work

Describe what you expected to happen:
1. Notifications must be received on a release build.

**Comment by Dallas62** [comment]
Hi @KPS250 
As you imagine, many developers use this library in production with release built.
I suggest you to look into issues, this should be documented or stackoverflow since it's probably not related to this library.

**Comment by KPS250** [comment]
@Dallas62 I actually had separate dev and prod google services config and release build got built with the wrong config. I got it fixed. Thanks for the help.
