### ISSUE TITLE
Device Token not generated in for Testflight build.

### ISSUE THREAD

**Issue by priyasamyal** [zo0r/react-native-push-notification#1552]
# Bug

 Push Token in successfully  create in Development Profile and working fine. But in Distrbution Testflight Build
Token is not generating. Please Help

I have rechecked all the Certificates are correct.

**Comment by Dallas62** [comment]
Hi @priyasamyal 
This library doesn't implement specific code of iOS, take a look to react-native-community/push-notification-ios.
For your issue, I guess StackOverflow can help you for this.

**Comment by priyasamyal** [comment]
Thanks  for your reply.
