### ISSUE TITLE
[ios] onNotification not being called when receiving notification

### ISSUE THREAD

**Issue by alexbrazier** [zo0r/react-native-push-notification#1553]
# Question

I'm trying to override the push notification message on iOS received from the server, however `onNotification` only seems to be called when clicking the notification, and not when receiving.

As far as I can tell the js doesn't even get initialised on iOS so it always shows the notification message as it was sent. The same push message is working on a native app and allows us to override the message, so it seems the notification message is correct.

Here is an example of the code I've got:

```js
const onNotification = (notification) => {
  PushNotification.localNotification({
    data: notification.data,
    message: 'hello overridden message',
  });
}

PushNotification.configure({
  permissions: {
    alert: true,
    badge: true,
    sound: true,
  },
  popInitialNotification: false,
  requestPermissions: false,
  onNotification,
  onRegister,
})
```

**Comment by Dallas62** [comment]
Hi @alexbrazier 
For iOS issues, please refer to react-native-community/push-notification-ios.
There is no iOS specific code in this library.
Regards

**Comment by mathiasmoeller** [comment]
Might be related to #1501 
Please let me know if you manage to fix it @alexbrazier !
