### ISSUE TITLE
onNotification not being triggered when app is killed

### ISSUE THREAD

**Issue by joshlbaker** [zo0r/react-native-push-notification#1555]
I am experiencing a few issues that I would like some clarity on..

When sending a `notification { ... }` payload from the server, notifications come through but need some customization in order to come through properly. 

**Example payload sent from AWS SNS:**

```
"notification": {
  "title": "Some title",
  "body": "Some message",
  "android_channel_id": "rn-push-notification-channel-id-4-default-300" <-- This one was odd but was the only way I could find to assign it to the appropriate channel
  "color": "#somehex" <-- Had to force this or the icon color in "Brief Notifications" would display as white
},
"data": {
  "route": "some route",
  "routeId": "route id"
}
```

Here is what I referenced to come up with that structure ⬆️ : https://firebase.google.com/docs/cloud-messaging/http-server-ref

With the above payload I am able to receive notifications in all app states (foreground/background/killed) but it was not triggering the `onNotification` which means I am unable to manually do anything when a notification is pressed.

Also, for some reason, the notification banner does not contain the app logo which is present when I `presentLocalNotification`. 

When the payload is changed to a `data`-only payload, I get access to the `onNotification` function, however this causes a few problems.

**Example payload sent from AWS SNS:**

```
"data": {
  "title": "Some title",
  "message": "Some message"
  "route": "some route",
  "routeId": "route id"
}
```

1. In my Android logs I get ```Cannot send to notification centre because there is no 'message' field in: Bundle[{userInteraction=false, id=707734631, data=Bundle[{message=Sample message for Android endpoints}], foreground=false}]```.
2. Once the app is killed, notifications **do not** come through at all.

Here is some extra info:

**AndroidManifest.xml**
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="...">

  <uses-permission android:name="android.permission.INTERNET" />

  <!-- start rn push notification -->
  <uses-permission android:name="android.permission.VIBRATE" />
  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
  <!-- end rn push notification -->

  <!-- file write permissions to save images -->
  <uses-permission android:name="READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="WRITE_EXTERNAL_STORAGE" />

  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/..." android:roundIcon="@mipmap/..." android:allowBackup="false" android:theme="@style/AppTheme">
    <activity android:name=".SplashActivity" android:theme="@style/SplashTheme" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:screenOrientation="portrait">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="..." />
      </intent-filter>
    </activity>

    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:exported="true" android:screenOrientation="portrait" />

    <!-- start rn push notification -->
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
      <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
      </intent-filter>
    </receiver>

    <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService" android:exported="false">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>


    <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_notification" />

    <meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground" android:value="false" />
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_name" android:value="..." />
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_description" android:value="..." />
    <!-- end rn push notification -->
  </application>
</manifest>

```

**notifications.ts**

```
import ApolloClient from 'apollo-client';
import {NormalizedCacheObject} from 'apollo-boost';
import RNPushNotification from 'react-native-push-notification';

const pushTokenCache: NotificationToken = {os: '', token: ''};

export const clearAllNotifications = () => {
  RNPushNotification.cancelAllLocalNotifications();
};

export const unregisterNotifications = () => {
  RNPushNotification.unregister();
  RNPushNotification.abandonPermissions();
};

export const notificationsEnabled = (): Promise<boolean> =>
  new Promise(resolve => {
    RNPushNotification.checkPermissions(({alert}) => resolve(Boolean(alert)));
  });

export const postPushToken = async (apolloClient: ApolloClient<NormalizedCacheObject>) => {
  ...
};

export const deletePushToken = async (apolloClient: ApolloClient<NormalizedCacheObject>) => {
  ...
};

const initializePushNotifications = (callback?: () => {}) => {
  RNPushNotification.configure({
    onRegister(token: NotificationToken) {
      pushTokenCache.os = token.os;
      pushTokenCache.token = token.token;

      callback && callback();
    },

    onNotification(notification: PushNotification) {
      if (notification.userInteraction) {
        ...
      }

      if (!notification.foreground) {
        RNPushNotification.localNotification({
          title: notification.data.title ?? 'Fallback Title',
          message: notification.data.message ?? 'Fallback message',
        });
      }
    },
    popInitialNotification: true,
    requestPermissions: true,
  });
};

export default initializePushNotifications;
```

**App.tsx**
```
import initializePushNotifications from 'services/notifications';
...

const App = () => {
  useEffect(() => {
    initializePushNotifications();
  }, []);

  return (...);
}
```

**Comment by Dallas62** [comment]
Hi @joshlbaker 

First of all, I see you are using `.configure()` inside the component lifecycle which I highly not recommend for killed and background state (`onNotification` will not be called). Move it out of any component.

For your question on the format:
- notification: only display in background/killed
- notification+data: only display and data passed when user press
- data: only trigger `onNotification`

This is the behavior provided by FCM (more information in the FCM documentation).

For the case of:
```
Cannot send to notification centre because there is no 'message' field in: Bundle[{userInteraction=false, id=707734631, data=Bundle[{message=Sample message for Android endpoints}], foreground=false}]
```

This is probably a deprecated log message , this case cannot append anymore.

Best regards,

**Comment by joshlbaker** [comment]
So you would recommend calling `.configure()` in the entry point `index.ts`?

**Comment by Dallas62** [comment]
You can call it in any file you want, but it must be reachable when the index.ts is load.
In background/killed, no component are mounted, so nothing is called.

**Comment by jozueconz** [comment]
I have the same issue here but I'm using Redux to dispatch the payload of the notification so how I can deal with that if the notification is outside of any React component??

This is what I have:

```
const Notifications = () => {
	const dispatch = useDispatch();
	useEffect(() => {
		PushNotification.configure({
			onRegister: ({ token }) => {
				dispatch(setDeviceToken(token));
			},
			onNotification: (notification) => {
				let data;
				if (notification.data) {
					data = notification.data.json_str;
				} else if (notification.json_str) data = notification.json_str;
				if (data) {
					const response = JSON.parse(data);
					dispatch(notificationOpened(response));
				}
				notification.finish(PushNotificationIOS.FetchResult.NoData);
			},
		});
	}, []);
	return null;
};

export default Notifications;
```

**Comment by alanlanglois** [comment]
Same here, the configure is not in a component. 
Works like a charm when the app is not killed (just set in background), but onNotification is not triggered when the app has been killed. 
Seeing the number of issues with "onNotification" I assume there is a problem here :)

**Comment by Dallas62** [comment]
Hi @alanlanglois 
If you close look to `onNotification` issues, the main reason is the configure inside a component, second reason channels, 3rd reason iOS library with an outdated installation guide.
And issues opened without looking at issue history 😉

**Comment by Dallas62** [comment]
The last reason is when the payload doesn't follow Firebase documentation:
https://firebase.google.com/docs/cloud-messaging/android/receive

I translate the table to this library:

App state | Notification | Data | Both
-- | -- | -- | --
Foreground | `onNotification` | `onNotification`| `onNotification`
Background | System tray | `onNotification`| Notification: system trayData: in extras of the intent.

**Comment by alanlanglois** [comment]
Yes but if onNotification is triggered on click when the app is in background, I guess it should also be triggered when the app is killed. I'm positive the configure is not inside component (and inside in the index.ts), I haven't use specifics channels and the problem is just on Android, it works fine on iOS. 
Also I'm not using remote notification, just local scheduled notifications.

**Comment by Dallas62** [comment]
So the problem is different, in your case you expect scheduled notification to trigger `onNotification` when the app is killed.
Unfortunately; in background the app is alive, so `onNotification` can be triggered. But in killed state, `onNotification` will not be triggered for scheduled notification.
The main reason it's not possible is that iOS deprecate this case in the new Notification SDK when there is no user interaction, if we allow it on Android, this could lead to an issue on iOS side. (https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622930-application?language=objc)

**Comment by alanlanglois** [comment]
So if you schedule a notification, there is no way of redirecting your user to the content that scheduled the notification in the first place? Example: I'm start a lesson in the app, don't finish it and leave the app (by killing it) I'll receive a local notification incitating me to continue the lesson, if I click, there is no way to redirect to this particular lesson based on the notification data?

**Comment by Dallas62** [comment]
This case should be handle, there is also to many cases of faillure for `onNotification` as you probably notice, your initial question is far from the current question:

> onNotification is not triggered when the app has been killed.

> if I click

Take a look to #1501

**Comment by alanlanglois** [comment]
Actually not, I'm having the problem on android not iOS and don't receive onNotification when app is killed (but I do when in background), it seems pretty close from the issue description. 
Thanks anyway for the great work.

**Comment by Dallas62** [comment]
The issue is marked as iOS, but the case can happen on Android too since this is on a common part.

**Comment by mr-ryan-james** [comment]
I'm almost 100% certain that this line of code is incorrect: 
https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java#L61

I'm sure you meant  `bundle.putString("message", data.optString("**message**", null));`

**Comment by mr-ryan-james** [comment]
Replying to the original issue: 

In order to get a "message" handler into the bundle, so I didn't get the `Cannot send to notification centre because there is no 'message' field in` error, I had to add an "alert" field in the "data" field:

(this is an example of handling a mixpanel notification, btw, using my own custom `FirebaseMessagingService`)

```
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        Log.i("RNPushNotification", "PushProvidersHandler - onMessageReceived!");
        super.onMessageReceived(remoteMessage);
        if (remoteMessage.getData().containsKey("mp_message")) {
            MixpanelFCMMessagingService.showPushNotification(getApplicationContext(), remoteMessage.toIntent());

            Map<String,String> params = new HashMap<String,String>();
            params.put("title", remoteMessage.getData().get("mp_title"));
            params.put("message", remoteMessage.getData().get("mp_message"));
            params.put("alert", remoteMessage.getData().get("mp_message"));
            Gson gson = new Gson();
            String json = gson.toJson(params);
            remoteMessage.getData().put("data", json);

            mMessageReceivedHandler.handleReceivedMessage(remoteMessage);
        }
```

Notice how it is expecting an 'alert' here, and adds it as as 'message':
https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java#L61

**Comment by joshlbaker** [comment]
@Dallas62 

When I use the `data` payload notifications don't come through when the app is killed.
I get:

```
2020-08-12 12:25:34.846 7807-7807/com.shopify.ping E/RNFirebaseMsgReceiver: Background messages only work if the message priority is set to 'high'
    java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.shopify.ping/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) }: app is in background uid UidRecord{7143eab u0a364 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1604)
        at android.app.ContextImpl.startService(ContextImpl.java:1559)
        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
        at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingReceiver.onReceive(ReactNativeFirebaseMessagingReceiver.java:50)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3525)
        at android.app.ActivityThread.access$1200(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1704)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:205)
        at android.app.ActivityThread.main(ActivityThread.java:6983)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

Any ideas?

**Comment by Dallas62** [comment]
Hi @joshlbaker 
I think the error message is clear, the message or channel doesn't have the good priority.

**Comment by joshlbaker** [comment]
Got it, now I'm getting:
```
2020-08-12 12:33:53.020 8933-8933/com.myappD/RNFirebaseMsgReceiver: broadcast received for message
2020-08-12 12:33:53.059 8933-9080/com.myappV/RNPushNotification: onMessageReceived: Bundle[{data=Bundle[{message=Sample message for Android endpoints}]}]
2020-08-12 12:33:53.063 8933-8933/com.myappV/RNPushNotification: sendNotification: Bundle[{userInteraction=false, id=1844101017, data=Bundle[{message=Sample message for Android endpoints}], foreground=false}]
2020-08-12 12:33:53.066 8933-8933/com.myappD/RNPushNotification: Cannot send to notification centre because there is no 'message' field in: Bundle[{userInteraction=false, id=1844101017, data=Bundle[{message=Sample message for Android endpoints}], foreground=false}]
```

However, it's not popping the notification. I am initializing PN outside of the component and am using the `5.0.1` package

**Comment by Dallas62** [comment]
Did you follow the Firebase format of notifications ?
Looking at the error message, it's not the case.

**Comment by joshlbaker** [comment]
> Did you follow the Firebase format of notifications ?
> Looking at the error message, it's not the case.

I resolved the error per my previous comment. When the app is in killed state the notification does not pop. 
The listener obviously detects the incoming notification but does not present it like it does when the app is open/backgrounded.

**Comment by Dallas62** [comment]
> > Did you follow the Firebase format of notifications ?
> > Looking at the error message, it's not the case.
> 
> I resolved the error per my previous comment. When the app is in killed state the notification does not pop. 
> The listener obviously detects the incoming notification but does not present it like it does when the app is open/backgrounded.
> 

This is exactly why I'm asking you: Do you follow the Firebase format for notification ?

**Comment by bernhardt1** [comment]
@alanlanglois I'm having your exact problem.

 "Works like a charm when the app is not killed (just set in background), but onNotification is not triggered when the app has been killed."

I'm wondering if you found a solution to get the notification data when the app is opened from a killed state?

**Comment by cohen72** [comment]
> Replying to the original issue:
> 
> In order to get a "message" field into the bundle, so I didn't get the `Cannot send to notification centre because there is no 'message' field in` error, I had to add an "alert" field in the "data" field:
> 
> (this is an example of handling a mixpanel notification, btw, using my own custom `FirebaseMessagingService`)
> 
> ```
>     @Override
>     public void onMessageReceived(RemoteMessage remoteMessage) {
>         Log.i("RNPushNotification", "PushProvidersHandler - onMessageReceived!");
>         super.onMessageReceived(remoteMessage);
>         if (remoteMessage.getData().containsKey("mp_message")) {
>             // this next line may be causing double notifications, this is still a WIP
>             MixpanelFCMMessagingService.showPushNotification(getApplicationContext(), remoteMessage.toIntent());
> 
>             Map<String,String> params = new HashMap<String,String>();
>             params.put("title", remoteMessage.getData().get("mp_title"));
>             params.put("message", remoteMessage.getData().get("mp_message"));
>             params.put("alert", remoteMessage.getData().get("mp_message"));
>             Gson gson = new Gson();
>             String json = gson.toJson(params);
>             remoteMessage.getData().put("data", json);
> 
>             mMessageReceivedHandler.handleReceivedMessage(remoteMessage);
>         }
> ```
> 
> Notice how it is expecting an 'alert' here, and adds it as a 'message':
> https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java#L61

I was able to get this working with the help of @mr-ryan-james, but could only get it working updating the `data` with a formatted string. I also deleted the following line, since it was causing two alerts to be displayed: 

` MixpanelFCMMessagingService.showPushNotification(getApplicationContext(), remoteMessage.toIntent());`

This got it working for me, but with a few changes:

```
public class PushProvidersHandler extends RNPushNotificationListenerService {

  @Override
  public void onMessageReceived(RemoteMessage remoteMessage) {
    if (remoteMessage.getData().containsKey("mp_message")) {
      String value = String.format("{'alert': %s}", remoteMessage.getData().get("mp_message"));
      if (remoteMessage.getData().containsKey("mp_title")) {
        value = String.format("{'title': %s, 'alert': %s}", remoteMessage.getData().get("mp_title"), remoteMessage.getData().get("mp_message"));
      }
      remoteMessage.getData().put("data", value);
    }
    super.onMessageReceived(remoteMessage);
  }
}
```

**Comment by andrei-m-code** [comment]
I'm getting this issue now. I definitely send { message: "...", data: { message: "" }} payload.

**Comment by TiavinaRakotobe** [comment]
still getting this issue

**Comment by shafqatbarireporteq** [comment]
still getting this issue. Any solution ? Please share

**Comment by AlbertoMeQ** [comment]
Also getting this issue, just when the notification is tapped from the system tray, otherwise all works fine.

**Comment by chakshit89** [comment]
Hey all folks here by spending over a day I have found a solution , FCM override function OnMessageRecieved will not call when app is killed , so you have to override Onhandleintent function inside your FCM . And from there you can add logic inside that function to show custom notification on the screen .🙂

**Comment by SathishSaminathan** [comment]
Hi @chakshit89 have you fixed this issue?
