### ISSUE TITLE
[Android] onNotification does't trigger

### ISSUE THREAD

**Issue by wanderbon** [zo0r/react-native-push-notification#1558]
# Bug

onNotification does't trigger if app running

Library version: `4.0.0`

## Steps To Reproduce

1. Close app if it running
2. Get two or more pushes
3. Click by one of pushes. App will open. onNotification will trigger.
4. Without closing or minimizing the application click by another push. onNotification will not trigger.

Describe what you expected to happen:

1.  Without closing or minimizing the application click by another push. onNotification will trigger.

## Reproducible sample code

index.js

```
messaging().setBackgroundMessageHandler(async (backgroundMessage) => {
    ...
    const data = Platform.OS === 'ios' ? {
      alertBody: message,
      alertTitle: title,
      deepLink,
      title,
      message,
    } : {
      title,
      message,
      largeIcon: 'icon',
      smallIcon: 'icon_start',
      color: theme.accentPallete,
      deepLink,
    };

    if (NotificationsManager?.localNotification) {
      NotificationsManager.localNotification(data);
    } else if (NotificationsManager?.presentLocalNotification) {
      NotificationsManager.presentLocalNotification(data);
    }
});
```

notificationService.js

```
getNotifcationsManager().configure({
        onNotification: (notification) => {
           if(notification?.deepLink) {
             handleOpenNotification(notification.deepLink);
           }
        }
});
```

**Comment by Dallas62** [comment]
Hi @wanderbon 
Did you look at recent issues ?

This is probably because you use `configure` inside of a component.

**Comment by wanderbon** [comment]
> Hi @wanderbon
> Did you look at recent issues ?

Yes, I do.

> This is probably because you use `configure` inside of a component.

I use configure outside of a component.

**Comment by Dallas62** [comment]
Hi @wanderbon 
Did you console.log onNotification ?
Not sure there is a deepLink at this level of the notification (maybe in .data).

If `configure()` is called outside of a component (lifecycle), there is probably an activity that intercept the notification (splash screen) all information should be in the last 15 issues.

**Comment by matanrokach** [comment]
It might be intercepted by react-native-splash-screen.

Maybe you'll find this comment helpful:
https://github.com/zo0r/react-native-push-notification/issues/1550#issuecomment-662533844

**Comment by wanderbon** [comment]
> Maybe you'll find this comment helpful:
> [#1550 (comment)](https://github.com/zo0r/react-native-push-notification/issues/1550#issuecomment-662533844)

Thanks for your reply.

My current SplashActivity code

```
public class SplashScreenActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                Intent mainIntent = new Intent(SplashScreenActivity.this, MainActivity.class);

                Bundle extras = SplashScreenActivity.this.getIntent().getExtras();
                if (extras != null) {
                    mainIntent.putExtras(extras);
                }

                SplashScreenActivity.this.startActivity(mainIntent);
                SplashScreenActivity.this.finish();
            }
        }, 0);
    }
}
```

but is not working

**Comment by matanrokach** [comment]
@wanderbon 

This is my SplashActivity.java:
`public class SplashActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Intent intent = new Intent(this, MainActivity.class);
        intent.putExtras(getIntent().getExtras());
        startActivity(intent);
        finish();
    }
}`

and it's working.
Maybe you can simplify it a bit? try to compare.

**Comment by wanderbon** [comment]
> Maybe you can simplify it a bit? try to compare.

Unfortunately, does not work
