### ISSUE TITLE
Not displaying remote notification although it is being received in onNotification function

### ISSUE THREAD

**Issue by shyammca55** [zo0r/react-native-push-notification#1559]
Hi folks,
I am using react-native-push-notification npm package and getting local and remote notification in app.But facing problem when displaying remote notification. It is received in onNotification function but not displaying on top of the app. I want it like local notification. Attaching screenshot for more clarification:-

This blow code for remote notification

    PushNotification.configure({
      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },
      senderID: 'XXXXXXXXXX',
      popInitialNotification: true,
      requestPermissions: true,
    
      onNotification: function(notification) {
          console.log('REMOTE NOTIFICATION==>', notification);
      },
     
      onAction: function (notification) {
        console.log("ACTION:", notification.data.action);
        console.log("NOTIFICATION:", notification);
        // process the action
      }
    }); 

And am receiving remote notification successfully in onNotification function but this is not displaying on top of screen like local notification.Payload for remote notification is following:-

```REMOTE NOTIFICATION==>{"data": {"action": "3", "alert": "Congrats! You have received food order. Click to see details", "content-available": "3", "job_id": "5f1a7301a1932d281023e7f4", "message": "Congrats! You have received food order. Click to see details", "sound": "default", "status": "3", "type": "FoodDelivery"}, "finish": [Function finish], "foreground": true, "id": "-1753177126", "userInteraction": false}```

I want to display remote notification like local notification which screenshot is attached below. Any help will be appreciated.

[https://i.stack.imgur.com/1KxGD.png](url)

Thanks

**Comment by Dallas62** [comment]
Hi @shyammca55 
This issue has already been answered, please search in issue history.
Best regards

**Comment by shyammca55** [comment]
> Hi @shyammca55
> This issue has already been answered, please search in issue history.
> Best regards

Hi  Can You share link there are a lot of stuff can you share link?

**Comment by Dallas62** [comment]
#1539
