### ISSUE TITLE
Android - how do I actually show the popup/banner notification? 

### ISSUE THREAD

**Issue by peterpme** [zo0r/react-native-push-notification#156]
Thanks for all the great work you've done for this library! It's been great!

My only question is - do I use something like react-native-system-notification to show the actual pop up?

Whether I'm in the foreground or background, I get the notification. The issue is that nothing appears.

No status bar, nothing in the "notifications" view on android, nada!

Thanks!

**Comment by zo0r** [comment]
The notification is only showed in the notification area when you are in background, are you using the git version or npm (**2.0.1**) version? What is your **RN** version?

No, you don't need to use **react-native-system-notification** to show any notification, also if you want to display the notification in the notification area even in foreground use `RNPushNotification. localNotification()`

**Comment by peterpme** [comment]
Hey thanks for the quick reply!

I'm actually using 1.0.7.

When the app is in the background, I don't get any notification whatsoever. I do however see the onNotification callback being called, just don't see anything.

Thanks again!

**Comment by peterpme** [comment]
@zo0r I'm trying it again this morning and the notification only works in the foreground, not the background for RN 0.27.2 and RN 1.0.7

Thanks again :)

**Comment by hsriskantha** [comment]
Hi @peterme, this change appears to fix this for me: https://github.com/Theodo-UK/react-native-push-notification/pull/1 (However, I'm not sure if it's a generic fix, or one that's specific to us. Also, we're using 2.0.2 with RN 0.30...)

**Comment by peterpme** [comment]
Thanks!

**Comment by juanpasolano** [comment]
I still cannot see the notification in the notification bar. @peterpme did you solved it? What did you do? 
Thanks

**Comment by peterpme** [comment]
Hey @juanpasolano ,

Android notifications work differently. You will see the notification if the phone is locked. It will pop up under the overhead view. Make sure that it's working in this state first, and then slowly try different android push notification scenarios.

[Check this out](https://developer.android.com/guide/topics/ui/notifiers/notifications.html)

**Comment by juanpasolano** [comment]
Thanks for the reply @peterpme, unfortunately there is no notification even when phone is locked. 
The debugger however does get it.
