### ISSUE TITLE
IOS show ImageUrl with Notification 

### ISSUE THREAD

**Issue by girish54321** [zo0r/react-native-push-notification#1560]
# Question
Hi i use `largeIconUrl` for android to show image for Notification and it works nicely 

so is there any way to show image on IOS too 

Thanks 😄

**Comment by Dallas62** [comment]
Hi @girish54321 
The library use https://github.com/react-native-community/push-notification-ios which doesn't support this behaviour actually, feel free to open a PR on the iOS Library 😉 
Best regards

**Comment by girish54321** [comment]
Thanks for the response @Dallas62 

closing the issue 👍🏽

**Comment by rjuevesano** [comment]
@Dallas62 if you don't mind, really need your help. I want to include and show the image in iOS notification but I don't know why it's not showing. It's showing on android using `largeIconUrl`

**Comment by Dallas62** [comment]
Hi @rjuevesano 
The library use https://github.com/react-native-community/push-notification-ios which doesn't support this behaviour actually, feel free to open a PR on the iOS Library 😉
Best regards
