### ISSUE TITLE
[iOS] onNotification being called when app is in background / foreground flag

### ISSUE THREAD

**Issue by NicholasBertazzonAga** [zo0r/react-native-push-notification#1561]
Hi, 
I have a question regarding iOS (and a bug? of userInteraction)...
If the app is in background state, why is the js onNotification being called? Isn't the JS supposed to be quiet?
Also, while the app is in background, the notification I see on the JS console always has the userInteraction true.

Thanks.

**Comment by NichAga** [comment]
I temporary disabled it by editing the native code on AppDelegate.m as so:

```
// Required for the notification event. You must call the completion handler after handling the remote notification.
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  if([[UIApplication sharedApplication] applicationState] != UIApplicationStateBackground){
    [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
  }
}
```

**Comment by NichAga** [comment]
Ok another problem, if I click on the notification in the centre while the app is closed the "foreground" flag is true

**Comment by Dallas62** [comment]
Hi @NichAga 
The behaviour of foreground / background it's normal to get the onNotification trigger in any state. On iOS it's depending on AppDelegate.
For the problem of foreground, are you testing in Debug ?

**Comment by blexxed** [comment]
Hello @Dallas62, issue also happens to me using v6.1.2, `onNotification` is called with payload of `foreground: true` even when app is fully closed in iOS. Is this normal? If yes, how can we check if notif is opened from fully closed app?
