### ISSUE TITLE
NotificationHandler not firing onRegister

### ISSUE THREAD

**Issue by muriloneo** [zo0r/react-native-push-notification#1563]
# Question
My app was working and I just did a release and no FCM tokens are showing.

Can anyone help me?
I'm using the example Class NotifService and NotificationHandler EXACTLY as is.

on my AndroidManifest.xml
<meta-data
    android:name="com.google.firebase.messaging.default_notification_channel_id"
    android:value="rn-push-notification-channel-id-4-default-300"/>

    <meta-data android:name="com.dieam.reactnativepushnotification.channel_create_default" android:value="false" />
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_background" android:value="true" />
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground" android:value="true" />
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_name" android:value="CanalPush" />
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_description" android:value="Canal para Push CSJT" />
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_color" android:resource="@android:color/white" />

    <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_name.rn-push-notification-channel-id-4-300" android:value="Example-Channel silent" />
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_description.rn-push-notification-channel-id-4-300" android:value="Super channel description for silent channel" />

What am I doing wrong?

**Comment by muriloneo** [comment]
My problem is only when I set Emulator to API 28, Target Android 9.0 x86_64

When I run my app on API 28, Target Android 9.0 (Google Play) x86 it does work.

But on real devices I don't get the FCM token, like running on x86_64

**Comment by Dallas62** [comment]
Hi @muriloneo 
Please check issues before, this is already answered question.

**Comment by muriloneo** [comment]
> Hi @muriloneo
> Please check issues before, this is already answered question.

I have not found any new answer for this problem, even the problem on android 9.0 x86_64 specifically.

Can you please, link some or guide me somehow?

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification/issues/678#issuecomment-660791361

This is the same kind of error on Android.

**Comment by Dallas62** [comment]
Also sometimes you need to reboot internet connection to make it works.

**Comment by muriloneo** [comment]
Funny thing that my internet connection just disconnected. I'll try.
Thanks for your link. I'll check the #678.

**Comment by muriloneo** [comment]
no luck.
did almost everything said on this thread but to put a SIM card. Only working with simulator.

Only on x86_64 PIE 9.0 it does not triggers the register, resulting not getting token.

"react-native-push-notification": "^4.0.0"

implementation 'com.google.firebase:firebase-analytics:17.4.0'
implementation project(':react-native-push-notification')

classpath("com.android.tools.build:gradle:3.5.3")
classpath('com.google.gms:google-services:4.3.3')

not calling inside configure inside any Components. 

Same code using AVD with API 28, Target Android 9.0 (Google Play) x86 it does work, but need to work with all.

**Comment by muriloneo** [comment]
one more thing

changed
<meta-data android:name="com.dieam.reactnativepushnotification.channel_create_default" android:value="false" />
to
<meta-data android:name="com.dieam.reactnativepushnotification.channel_create_default" android:value="true" />

Now it does returns me the default channel that was logging empty array.

**Comment by Dallas62** [comment]
You will probably found information on internet, this kind of problem is not directly an issue of the library.

You can try to trigger `.requestPermissions` to for generate the token and look at ADB logs. If still not working, it might be related to Firebase SDK.

**Comment by muriloneo** [comment]
@Dallas62 you say it's not related with this package, but even the example wont work using this specs:
![image](https://user-images.githubusercontent.com/16191560/88833070-18435c00-d1a8-11ea-8e02-876f328cecba.png)

**Comment by Dallas62** [comment]
Yes but if the example application doesn't work, it doesn't mean that the package which is buggy.
It's a wrapper of Firebase Cloud Messaging SDK, this issue can be related to this SDK.

**Comment by alejogo4** [comment]
Can you solve, I'm having the same problem  onRegister not firing, I follow this steps but not is working 

https://github.com/zo0r/react-native-push-notification/issues/697

**Comment by HarshitMadhav** [comment]
Facing the same issue for the first time onRegister was called in my case but not called when I reload or reopen the application after killing in Android.
