### ISSUE TITLE
NotificationHandler and Redux

### ISSUE THREAD

**Issue by infiniteline** [zo0r/react-native-push-notification#1564]
I've upgraded RNPN in my project from version 3 to version 4 and I'm having a hard time wrapping my head around some of the changes. I've set up NotificationService and NotificationHandler as in the example project. I've also set up

`this.notification = new NotificationService(this.onRegister.bind(this), this.onNotification.bind(this));`

in the component constructor of the screen that I want to handle the notification. I've also included

```
NotificationHandler.attachRegister(onRegister);
NotificationHandler.attachNotification(onNotification);
```

in the constructor of NotificationService (just like the example project). I can call the functions in NotificationService to send a local notification and 'onNotification' is fired in NotificationHandler as indicated by a console.log. The problem I'm having is that 'onNotification' that is bound from my screen component is not firing. I use the code in that function to interact with Redux. How do I make this happen? Alternatively, is there someway that I can interact with Redux from within NotificationHandler?

**Comment by Dallas62** [comment]
Hi @infiniteline 

Notification Handler have been made to demonstrate a way to use `.configure()` outside of the component and allow foreground interaction with a component (not perfect but just an idea). Be aware that from version 3 to 4, there is no huge breaking change on API and usage of `.configure()`.
The issue you have is that you want to catch the notification inside the component. But in most cases, it's a bad idea.
On Background / killed state, the component will not be mounted and notifications will not work.

I personnally don't use redux, because it's over engineering in 95% of the time so I'm not able to help you directly. But since it's JS, you can probably call an action without connecting a component. Or at least store the notification received in a global variable / singleton to used it later.

**Comment by infiniteline** [comment]
Thanks for your help @Dallas62. I was unclear about how to access my navigation since `configure()` has to reside outside of a component. However, I looked through the React Navigation documentation and found the method for using navigation outside of props.

**Comment by infiniteline** [comment]
@Dallas62, could you provide an example of how one might create a global within Notification Handler and have it be accessible to a component?

**Comment by daxaxelrod** [comment]
Ah this was helpful. I have a similar use case where I'd like to move a user to the desired subscreen.

**Comment by Ajmal0197** [comment]
USING REDUX WITH NOTIFICATION HANDLER

-->App.js
import { Configure } from './config/NotificationHandler'
const App = () => {

    return (
        <SafeAreaProvider>
            <StatusBar barStyle="dark-content" hidden={false} backgroundColor="#1A1A1A" translucent={true} />
            <Provider store={store} >
                <Configure />
                <View style={{ flex: 1 }} >
                    <AuthLoading />
                </View>
            </Provider>
        </SafeAreaProvider>
    )
}
export default App;


-->Notificationhandler.js
import React, { useEffect } from 'react';
import PushNotificationIOS from "@react-native-community/push-notification-ios";
import PushNotification from 'react-native-push-notification';
import AsyncStorage from '@react-native-community/async-storage';
import NavigationService from '../routing/NavigationService'
import { useDispatch, useSelector, shallowEqual } from 'react-redux';

const Configure = () => {

  const { activeProject } = useSelector(state => ({
    activeProject: state.homeReducer.activeProject,
  }), shallowEqual);
  const dispatch = useDispatch();

  // Must be outside of any component LifeCycle (such as `componentDidMount`).
  PushNotification.configure({

    // (optional) Called when Token is generated (iOS and Android)
    onRegister: function (token) {
      console.log("RNPNonRegistertoken:", token);
      AsyncStorage.setItem('fcmToken', token.token);
    },

    // (required) Called when a remote is received or opened, or local notification is opened
    onNotification: function (notification) {
      console.log("NOTIFICATION:", notification, activeProject);

      // process the notification
      if (notification?.data?.url) {
        NavigationService.navigate('PDFScreen', { Key: 'URL', urlForPDF: notification.data.url })
      } else if (notification.id > 0 && notification.id < 7 && global.notifNavVar) {
        global.localPushID = notification.id
        NavigationService.navigate('AllTimersButton')
      } else if (notification.id == 7 && global.notifNavVarP) {
        NavigationService.navigate('ProjectDetail')
      }

      // (required) Called when a remote is received or opened, or local notification is opened
      notification.finish(PushNotificationIOS.FetchResult.NoData);
    },

    // (optional) Called when Registered Action is pressed and invokeApp is false, if true onNotification will be called (Android)
    onAction: function (notification) {
      console.log("ACTION:", notification.action);
      console.log("NOTIFICATION:", notification);

      // process the action
    },

    // (optional) Called when the user fails to register for remote notifications. Typically occurs when APNS is having issues, or the device is a simulator. (iOS)
    // onRegistrationError: function(err) {
    //  console.error(err.message, err);
    // }, 

    // IOS ONLY (optional): default: all - Permissions to register.
    permissions: {
      alert: true,
      badge: true,
      sound: true,
    },

    largeIcon: "ic_launcher",
    smallIcon: "ic_launcher",

    // Should the initial notification be popped automatically
    // default: true
    popInitialNotification: true,

    /**
     * (optional) default: true
     * - Specified if permissions (ios) and token (android and ios) will requested or not,
     * - if not, you must call PushNotificationsHandler.requestPermissions() later
     * - if you are not using remote notification or do not have Firebase installed, use this:
     *     requestPermissions: Platform.OS === 'ios'
     */
  });

  return null

};

const LocalNotificationSchedule = (id, afterSec, message = '', title = '') => {
  PushNotification.localNotificationSchedule({
    //... You can use all the options from localNotifications
    id: id + '',
    title,
    message, // (required)
    date: new Date(Date.now() + afterSec * 1000), // in n secs
    playSound: true,
    // soundName: 'local_notification_custom_tone.mp3',
    vibrate: true,
    vibration: 180000,
    allowWhileIdle: true,
    visibility: "public",
    // soundName: 'default',
    showWhen: true,
    usesChronometer: true,
    ignoreInForeground: false,
    priority: "max",
  })
}

const CancelLocalNotifications = (id) => {
  PushNotification.cancelLocalNotifications({ id: id + '' })
}

// const LocalNotification = () => {
//   PushNotification.localNotification({
//     id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
//     autoCancel: true,
//     bigText: 'This is local notification demo in React Native app. Only shown, when expanded.',
//     subText: 'Local Notification Demo',
//     title: 'Local Notification Title',
//     message: 'Expand me to see more',
//     vibrate: true,
//     vibration: 300,
//     playSound: true,
//     soundName:'default',
//     actions: '["Yes", "No"]'
//   })
// }

export {
  Configure,
  LocalNotificationSchedule,
  CancelLocalNotifications,
  // LocalNotification
};
