### ISSUE TITLE
I don't receive the notification when I click on the notification banner 

### ISSUE THREAD

**Issue by di1606** [zo0r/react-native-push-notification#1568]
# Question

How can I get the notification data when I click the notification banner? 

this question came to me when I received this content when I clicked on the banner : 

```
onNotification:  {"collapse_key": "com.yxz", "finish": [Function finish], "foreground": false, "from": "1020718514138", "google.delivered_priority": "high", "google.message_id": "0:1596057804479726%661b00cf661b00cf", "google.original_priority": "high", "google.sent_time": 1596057804472, "google.ttl": 2419200}
```
there is no data from the notification. In addition, I have this warning
```
No background message handler has been set. Set a handler via the "setBackgroundMessageHandler" method.`
```
I tried to use the method mentioned in the warning (`setBackgroundMessageHandler`):

```
messaging().setBackgroundMessageHandler((msg) => {
            console.log('setBackgroundMessageHandler: ', msg)
});
```
However, the banner of the notification is not displayed. How can I fix this problem?(retrieves data from the notification)

**Comment by lukebars** [comment]
[5.0.1](https://github.com/zo0r/react-native-push-notification/releases/tag/5.0.1) has some onNotification improvements, you should check that out
