### ISSUE TITLE
iOS App running on iOS 14 crashes every-time new push comes

### ISSUE THREAD

**Issue by saurabh874** [zo0r/react-native-push-notification#1569]
Hi
I am facing one major issue, every-time new push comes app is getting crash only iOS 14.
is there any one have solution please reply.

**Comment by Dallas62** [comment]
Hi @saurabh874 
Wrong repository, look for the iOS one.
Regards

**Comment by saurabh874** [comment]
Hi @Dallas62 
but i am using  this package for notification in react-native.
even i am getting notification from this in all device except for iOS 14 beta version.
push-notification-ios this is just support.

please again have a look ticket.

**Comment by Dallas62** [comment]
Hi @saurabh874 
Even with this library, this is the iOS which is used, if the issue is related to iOS version this probably an issue in the iOS code of the iOS library 😉
Provide logs for more investigation.

**Comment by saurabh874** [comment]
![Screenshot 2020-07-30 at 4 24 01 PM](https://user-images.githubusercontent.com/59818553/88915018-2618e000-d281-11ea-8edb-f400619cb2b6.png)
can you please have a look on image. meanwhile i am sharing more logs.

**Comment by ThanhNghia944** [comment]
same issue @saurabh874  any solution ?

**Comment by saurabh874** [comment]
@ThanhNghia944  nope.
