### ISSUE TITLE
Notification data format for Remote Notifications

### ISSUE THREAD

**Issue by akashamin1394** [zo0r/react-native-push-notification#1570]
# Question

I have been trying to set up the notification data structure for Remote Notifications. I have come up with this structure and it works too. I want to confirm if this should be followed or there are other ways.

Library Version: 4.0.0
Using FCM and the data format is

```
"data": {
            "alert": "Test message",
            "title": "Test title",
            "id": 1,
            "color": "white",
            "priority": "high",
            "channelId": "General",
            "ignoreInForeground": true,
            "allowWhileIdle": true
        }
```

As mentioned in the docs `message` is a mandatory parameter. But when digging into the library code `alert` is required and the notification is shown only if this parameter is present, which basically represents `message`

Also, `ignoreInForeground` flag does not work for remote notifications.

**Comment by Dallas62** [comment]
Hi @akashamin1394 
I don't fully understand your question, and this kind of question about format has already been answered.
You can send data-only message and use the data to trigger the notification:
```js
onNotification(notification) {
if(!notification.userInteraction) {
PushNotification.localNotification(notification.data);
}
}
```

This way, parameters are exactly the same as localNotification and the notification is consider as local so ignoreInForeground works.

**Comment by akashamin1394** [comment]
> Hi @akashamin1394
> I don't fully understand your question, and this kind of question about format has already been answered.
> You can send data-only message and use the data to trigger the notification:
> 
> ```js
> onNotification(notification) {
> if(!notification.userInteraction) {
> PushNotification.localNotification(notification.data);
> }
> }
> ```
> 
> This way, parameters are exactly the same as localNotification and the notification is consider as local so ignoreInForeground works.

Thanks for the reply. I will test this out in all the scenarios, closing the app, killing the app, doze mode.
