### ISSUE TITLE
Dismiss/Swiped away notification event?

### ISSUE THREAD

**Issue by supertiger1234** [zo0r/react-native-push-notification#1575]
Is there anyway to fire an event when the notification gets dismissed?

**Comment by Dallas62** [comment]
Hi @supertiger1234 
Unfortunately you cannot achieve that.

Maybe you can get the list of delivered notifications, those not dismissed. But not sure it's accurate.

You can probably reverse you logic to only interect with notification where the user interact ?

**Comment by supertiger1234** [comment]
Thanks for the reply but I'm not really sure what you mean 😞 i remember in java using a pending intent, maybe i could edit the source and do something about it. Thanks though

**Comment by jawwad22** [comment]
> Thanks for the reply but I'm not really sure what you mean 😞 i remember in java using a pending intent, maybe i could edit the source and do something about it. Thanks though

https://github.com/zo0r/react-native-push-notification/issues/855#issuecomment-690273559

**Comment by supertiger1234** [comment]
hmm could you explain please? I dont know what im looking at. wheres the notification swiped event?

**Comment by Nuthan31** [comment]
Hi @supertiger1234
I had a similar problem. I wanted to handle the dismiss event and update the notification counter. All I have done was used a setTimeOut for 5 seconds(until notification fades away) and called PushNotification.getDeliveredNotifications(deliveredNotifications) array length to get the count.
