### ISSUE TITLE
multiline without bigText?

### ISSUE THREAD

**Issue by supertiger1234** [zo0r/react-native-push-notification#1576]
I want multiline message. bigText works fine but only when the notification is expanded. I think in java/kotlin, its called `MessagingStyle`

Also how do i bold certain things? For example:

**Supertiger**: hi
**Bob**: Hello!

**Comment by DipzShr** [comment]
Hi @supertiger1234 . I also wanted to have similar kind of changes. Then I found this Pull Request. https://github.com/zo0r/react-native-push-notification/pull/1469
I tried it. And it's working fine.

**Comment by Dallas62** [comment]
Hi @DipzShr 
The PR #1469 is about HTML in the notification, are you able to try the result on iOS ?

**Comment by DipzShr** [comment]
Hi @Dallas62 .
I don't think it works on iOS. I can see the change is only for Android.
And I am sorry, I am still using Simulator for iOS. So, I am not even able to test if Notification comes up or not in iOS.
