### ISSUE TITLE
fcmtoken is not generated

### ISSUE THREAD

**Issue by costel21d** [zo0r/react-native-push-notification#1577]
# Question

Hello, 

I have tried to use the example app and the fcmToken is not generated.
bind(this) does't return token when I call onRegister.

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {};

    this.notif = new NotifService(
      this.onRegister.bind(this),
      this.onNotif.bind(this),
    );
  }

  render() { 
...

**Comment by Dallas62** [comment]
Hi @costel21d 

https://github.com/zo0r/react-native-push-notification#usage

**DO NOT USE `.configure()` INSIDE A COMPONENT, EVEN `App`**

Instanciate NotifService is exactly the same thing.
