### ISSUE TITLE
🔥 popInitialNotification only works when app is KILLED, but not in BACKGROUND!

### ISSUE THREAD

**Issue by OmarBasem** [zo0r/react-native-push-notification#1581]
# Bug

 When the app is opened by a notification while killed popInitialNotification gets called normally, but if the app is in the background, it does not fire. This bug is happening on Android. Currently, I am not able to test it on iOS.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 312.16 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 3.7.7 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1 
    react-native: ^0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: 5.0.1

## Steps To Reproduce

1. open a notification while app in the background on Android.

Describe what you expected to happen:

1. popInitialNotification should fire.

## Reproducible sample code

` PushNotification.popInitialNotification((notification) => {
            console.log('Notification opened from background', notification)
        });`

**Comment by Dallas62** [comment]
Hi @OmarBasem 

I'm not sure to understand your issue. I found an issue with the initial notification on Android, but it's not what you described.

`popInitialNotification` is a method you must call to get the initial notification. Initial notification = notification that start the application, not bring in foreground.
Example, use `popInitialNotification` when the App mount to redirect the user.

For other use case, use `onNotification` with `notification.userInteraction` property.

Actually, the initial notification on Android is not the right one when the app comes from background, but comes anyway.

**Comment by Dallas62** [comment]
After more investigations, everything is working as expected. 
The bug I found is more a special case when the Android Intent is reset with `setIntent` in `MainActivity`, so not relevant actually.

**Comment by OmarBasem** [comment]
@Dallas62 I want onNotif to fire when a notification is clicked in background. I have the following code in the constructor of the HomeScreen:
`this.notif = new NotifService(
            this.onRegister.bind(this),
            this.onNotif.bind(this),
        );`

onNotif() fires when the app is killed, but not when in background. 

I know that I can do `const notif = new NotifService(
        onRegister,
        onNotif,
    );` in the background function that i call, and onNotif will fire, but I want onNotif to fire from the HomeScreen Component because I need to dispatch actions into redux, which I cannot do in the background.

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification#usage

**DO NOT USE `.configure()` INSIDE A COMPONENT, EVEN `App`**
It's also true for the code you quote.

More examples are available in previous issues.

**Comment by OmarBasem** [comment]
Why I should not use configure() inside a component? How can I dispatch actions then?

**Comment by OmarBasem** [comment]
@Dallas62 a method inside a constructor will be called only once, I do not understand what is the problem with using configure() inside the constructor, could you please clarify?

**Comment by Dallas62** [comment]
Because components are not instanciated in background / killed state.

React and React Native it's not only about Redux.
A single variable outside the component or a singleton can store the notification, then when the component mount read the variable.

**Comment by Dallas62** [comment]
> @Dallas62 a method inside a constructor will be called only once, I do not understand what is the problem with using configure() inside the constructor, could you please clarify?

It's more about, which code will be called first.

I guess you use the code in the example project ?

Why the code inside the `Reproducible sample code` is about `.popInitialNotification` ? Actually it's working as expected.
Also the example app is working as expected with user interaction and even with the code below inside the constructor.

```jsx

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {};

    this.notif = new NotifService(
      this.onRegister.bind(this),
      this.onNotif.bind(this),
    );
  }
...
```

**Comment by OmarBasem** [comment]
I thought `.popInitialNotification` would be fired from background state as well. I did as you said and used a variable outside the component, then read it when the app comes to foreground and is working properly. Thanks a lot! :)
