### ISSUE TITLE
notification.foreground not accurate?

### ISSUE THREAD

**Issue by infiniteline** [zo0r/react-native-push-notification#1582]
Hey all,

  I'm trying to set up a conditional in my notification handler that is based on whether or not the app was open at the time of `onNotification`. I'm testing this in the Android emulator. When I respond to a notification from my app, `onNotification` fires and I'm logging the notification's `data`, `userInteraction`, and `foreground`. However, these are returning the same thing (undefined, true, and false, respectively) regardless as to whether I click on notification when my app is in the foreground, background, or quit. Should they have the same value across all of these states?

**Comment by Dallas62** [comment]
Hi @infiniteline 

On iOS the value of foreground is not accurate in some case (can't list them) and userInteraction is bases on it.

For Android, this should be OK.

Need more investigation to implement it directly in the iOS package.

**Comment by infiniteline** [comment]
Thanks for your quick response, @Dallas62. I'm not really getting it to work on Android, but if it doesn't work across platforms then I will probably need something else.

The problem I'm trying to get around is that I'm navigating to a screen in response to onNotification. However, if the app is closed, that navigation fires before the apps default navigation takes place and the end result is:
- start
- navigate to notification screen
- unexpected navigation to default screen

Am I setting this up in a completely incorrect way?
