### ISSUE TITLE
local push notification in silent mode (reopen, If anyone knows, please let me know!!)

### ISSUE THREAD

**Issue by daheeahn** [zo0r/react-native-push-notification#1584]
I opened same issue #1546

Thank you for letting me know, but I was sorry for doing what I told you. 
Is there any other way? I'm very desperate. 😇

If anyone knows, please let me know. Thanks!!!!

**Comment by Dallas62** [comment]
Hi @daheeahn 
This is the exact same answer: https://github.com/zo0r/react-native-push-notification/issues/1546#issuecomment-662400770

For iOS, it's not allowed with notification and Apple SDK

**Comment by daheeahn** [comment]
Ok I will try again. Thanks!

**Comment by daheeahn** [comment]
I found workaround.

Below [this](https://github.com/zo0r/react-native-push-notification/blob/2db1e05d9eb2a621a4d2b2b7058a3e0438ab07c3/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L921), I added this codes.

```
        try {
            if (soundUri != null) {
                AudioManager mAudioManager = (AudioManager) context.getSystemService(Context.AUDIO_SERVICE);
                mAudioManager.setStreamVolume(AudioManager.STREAM_MUSIC,
                        (int)(mAudioManager.getStreamMaxVolume(AudioManager.STREAM_MUSIC) * 0.7),
                        AudioManager.FLAG_PLAY_SOUND);

                MediaPlayer mediaPlayer = new MediaPlayer();
                mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
                mediaPlayer.setDataSource(context, soundUri);
                mediaPlayer.prepare();
                mediaPlayer.start();
            }
        } catch (Exception e) {
            Log.d("LOG", e.toString());
        }
```
