### ISSUE TITLE
[Android] Timeout support

### ISSUE THREAD

**Issue by ospfranco** [zo0r/react-native-push-notification#1588]
# Feature Request

## Why it is needed
Android notifications have become a lot more useful in the latest versions, we we're using react-native-firebase which had access to more funcionality, ex:

```javascript
  if (countdownTo != null) {
    notification.android.setUsesChronometer(true)
    notification.android.setWhen(countdownTo.getTime())
  }
  if (timeoutAfter != null) {
    notification.android.setTimeoutAfter(timeoutAfter)
  }
```

the chronometer is not 100% necessary for our use case, but the timeout actually makes a lot of sense for us, we develop a fasting app and once a fasting period has started, there is no point showing the same notification to the user

## Possible implementation

I took a look into the implementation code of Android, but honestly I have no idea, I'm not an android developer, however the flags that need to be set are already documented:

https://developer.android.com/reference/android/app/Notification.Builder#setTimeoutAfter(long)

### Code sample

```javascript
const notification = {
    title,
    message,
    bigText: message,
    channelId: 'BodyFast',
    color: Colors.cyan,
    id: idPrefix ? idPrefix + '_' + String(Math.random()).slice(2) : undefined,
    data,
    importance: 'max',
    date,
    timeoutAfter: 2000 // This would be the extra field to make the notification dissapear after X seconds
  }

  PushNotification.localNotificationSchedule(notification)
```

**Comment by Dallas62** [comment]
Hi @ospfranco 
Both features are available on `dev` branch, can you check if it's ok ?
https://github.com/zo0r/react-native-push-notification/tree/dev

**Comment by ospfranco** [comment]
Hi @Dallas62, thank you very much for adding support for this features, I'm in the middle of a release cycle so I won't have much time until next week, then I can test the changes again, just wanted to mention it so it doesn't look like I forgot about it.

Thanks again!

**Comment by ospfranco** [comment]
Seems to be working, thanks a lot @Dallas62 !
