### ISSUE TITLE
Method missing on types

### ISSUE THREAD

**Issue by danilowoz** [zo0r/react-native-push-notification#1593]
# Question

I don't know where exactly this issue should be addressed since I didn't find the Typescript definition in the repository, but I noticed that some methods are missing in the types which don't deliver the full type-checking application.

Missing methods:
- onAction
- onRegistrationError

I guess the current types are not compatible with the latest version.

Awesome package, by the way, it helps me a lot!

**Comment by Dallas62** [comment]
Hi @danilowoz 
Actually I'm not using TypeScript so I will not maintain types for TypeScript.
But you can find the types here:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native-push-notification

Feel free to make a PR on this repository 😉
