### ISSUE TITLE
Customizable Notification Actions

### ISSUE THREAD

**Issue by mathiasmoeller** [zo0r/react-native-push-notification#1596]
# Feature Request

It would be great if this library would allow you to customize the styling of the notification actions.
Android allows this so maybe the settings just have to be passed on to the native code

## Why it is needed

It would allow you to create a better ux in the notifications. E.g. red buttons for decline actions and green for accept.

## Possible implementation

Here are some examples of how it is done in native Android
https://stackoverflow.com/questions/58178293/notification-coloured-action-button-android-10

**Comment by Dallas62** [comment]
Hi @mathiasmoeller 
I will try to find time on this ASAP, It's a good feature to start some refactor on the API.
I have an idea which should allow smooth transition to the new API without breaking change.

**Comment by hariks789** [comment]
Any update on this @Dallas62 ?

**Comment by nandinicbit1981** [comment]
Any updates on this?

**Comment by hariks789** [comment]
@nandinicbit1981 I created a fork of this repo and modified the code for my need. It is not backward compatible at the moment. I changed actions from Array of strings to Array of objects with additional params. You can refer my fork for the code

**Comment by hariks789** [comment]
@nandinicbit1981 FYI This library is not actively maintained now. Check out [notifee](https://notifee.app/) ,they might have this functionality out of the box.

**Comment by nandinicbit1981** [comment]
Thank you @hariks789 , really appreciate the response. i will checkout your fork
