### ISSUE TITLE
Remote notification crashes the app

### ISSUE THREAD

**Issue by sudonitin** [zo0r/react-native-push-notification#1597]
The docs have neither provided a detailed explanation on how to use the remote notifications with your backend nor have they provided an example.

I followed this [article](https://medium.com/@Jscrambler/implementing-react-native-push-notifications-in-android-apps-7e0234dee7b7), as the repo had just mentioned things about configuration.

**Comment by Dallas62** [comment]
Hi @globefire 
You can follow the format of Firebase and APNS which are the official way to send notification.
Regards

**Comment by globefire** [comment]
@Dallas62 could you please point out some references? 
I want to send push notifications from an admin panel.
Regards

**Comment by Dallas62** [comment]
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html


https://firebase.google.com/docs/cloud-messaging/http-server-ref?hl=en
