### ISSUE TITLE
Checking Notification Permissions Android not working

### ISSUE THREAD

**Issue by TommyLeong** [zo0r/react-native-push-notification#1598]
# Checking Notification Permissions Android not working

I'm trying to get the Android App Notification status with the [check permission method](https://github.com/zo0r/react-native-push-notification#checking-notification-permissions) here. Here's the [code to check permission in Android](https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java)

According the readme file, I did the following..
1. `yarn add react-native-push-notification`
2. I have not performed any manual installation as [stated here ](https://github.com/zo0r/react-native-push-notification#android-manual-installation)
3. I write my code as below
4. Android has no respond, but iOS did come back with expected respond. 

```
import PushNotification from 'react-native-push-notification';
async componentDidMount(){
PushNotification.checkPermission().then((response) => {
      if (response && response.alert !== 0) {
        console.log('hi4')
        console.log(response)
        return; 
      }
      console.log('hi5')
        console.log(response)
    });
}
```

Am I doing anything wrong here to check the App Notification status in Android? 

For iOS, I have this install. 
`yarn add @react-native-community/push-notification-ios`

**Comment by Dallas62** [comment]
Hi @TommyLeong 
As the Readme define that method, this is not supposed to be a promise. Actually only the iOS library allow this.
Regards

**Comment by TommyLeong** [comment]
> Hi @TommyLeong
> As the Readme define that method, this is not supposed to be a promise. Actually only the iOS library allow this.
> Regards

What does that suppose to mean? Is that a known bug for this lib?

**Comment by Dallas62** [comment]
This is not a "bug", this library use callbacks, not promises.

**Comment by TommyLeong** [comment]
> This is not a "bug", this library use callbacks, not promises.

Possible to provide sample code?

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification#checking-notification-permissions

`PushNotification.checkPermissions(callback: Function)` Check permissions

`callback` will be invoked with a `permissions` object:

`alert`: boolean
`badge`: boolean
`sound`: boolean

```js
PushNotification.checkPermissions(function(permissions) {  console.log(permissions); });
```

**Comment by TommyLeong** [comment]
Thanks @Dallas62, finally I get you now. 🙏🏻

**Comment by rameshckr** [comment]
Thanks @Dallas62. I have spent 2 hours, finally its working..

**Comment by johhansantana** [comment]
how does one know if the user has denied it and now the prompt is no longer available in android?
