### ISSUE TITLE
[Android] How to register to a GCM topic?

### ISSUE THREAD

**Issue by vandervidi** [zo0r/react-native-push-notification#16]
It is not clear how can i register a client to a GCM topic. Is it possible?

**Comment by dchdimitrov** [comment]
It is possible. I was not able to find a way in the module itself, but you can do this:
1. Get a registration ID.
2. When you have your ID call GCM and register:
`let url = 'https://iid.googleapis.com/iid/v1/' + token + '/rel/topics/' + topicName;
                fetch(url, {
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': 'key=...........'
                    },
                    method: 'POST'
                })
                    .then(
                        (result) => {
                            if (result.status == 200) {
                                console.log(token.token);
                            } else {
                                console.log('Could not register for notifications!')
                            }
                        }
                    )
                    .catch(() => {
                        console.log('Could not register for notifications!');
                    })`

**Comment by vandervidi** [comment]
Can this be done without using the Authorization key? I prefer not storing the key in the client.
Can this be done in a native way by adding that functionality in the java code?

**Comment by dchdimitrov** [comment]
If you don't want the key to be visible in the JS code I can give you two solutions that come to mind:

1. Create a new native module and to the registration there. "https://facebook.github.io/react-native/docs/native-modules-android.html#content"

2. Store the key in "AsyncStorage" and retrieve it only when you need to use it. This way it will be stored as safely as possible. (keeping the key in DB is a good idea even if you develop a native module)

**Comment by stefanocapitanio** [comment]
@zo0r you did a great job with this module! Did you planned some new features on this module like Topic support? 
I'm implementing Topic support with "option 1", but I think that this module could stay on your module....
What do you think about?

Thanks

**Comment by caffpain** [comment]
Where do i get the values for "'key=...........' " ?

I receive status 400, could not register for notifications
