### ISSUE TITLE
Conditionals to actually run scheduled notification

### ISSUE THREAD

**Issue by luizgallas** [zo0r/react-native-push-notification#1603]
There is any way of creating a conditional to push or not the notification? Something like this:

export default async function scheduleRoutine(routines) {
  routines.forEach((routine) => {
    PushNotification.localNotificationSchedule({
      if (true) {
      // if its true then push, otherwise get out
      }
      title: `Sua rotina: ${routine.name}`,
      message: routine.message,
      vibration: 900,
      invokeApp: true,
      date: new Date(Date.now() + routine.interval * 60000),
      id: JSON.stringify(routine.cod),
      userInfo: {id: JSON.stringify(routine.cod)},
      allowWhileIdle: true,
      repeatType: 'time',
      repeatTime: 'routine.interval * 60000',
    });
    cancelNotification(routine);
  });
}

**Comment by Dallas62** [comment]
Hi,

It's not possible like that, you can try to trigger background tasks with another library then trigger the notification but it might not be accurate.

**Comment by luizgallas** [comment]
I tried using another repo but then i lose the possibility of have my app working while closed.

**Comment by luizgallas** [comment]
What I need is to only push the notification if the current date is between two pre-set schedules. Example: only push if is between 08:00 AM and 01:00 PM. There is any way?

**Comment by Dallas62** [comment]
Why don't you set the notification at a time between this pre-set

**Comment by luizgallas** [comment]
There is any way of triggering an function everytime an local notification is pushed?
