### ISSUE TITLE
How to navigate to respective pages onclick of notification

### ISSUE THREAD

**Issue by Softkeydel** [zo0r/react-native-push-notification#1605]
How to navigate to respective pages on the basis of notification content while clicking on notification? Please help

**Comment by Dallas62** [comment]
Hi,

Please look into other issues, this has been answered many times.

**Comment by Softkeydel** [comment]
@Dallas62 can you give me the reference of the ans. Actually there are lot of questions

**Comment by Dallas62** [comment]
#1390
