### ISSUE TITLE
Actions buttons for notifications sent remotely

### ISSUE THREAD

**Issue by anton-thushara** [zo0r/react-native-push-notification#1609]
Is there any way to specify action buttons for notification that are sent remotely? settings actions: ['Accept', 'Reject'] in notification payload dosent seem to work.

**Comment by Dallas62** [comment]
Hi, you can send data only notification, then pass data to `localNotification`.

Don't forget to check `userInteraction`.

**Comment by anton-thushara** [comment]
thank you, it worked
