### ISSUE TITLE
🐛 Opening notifications on iOS not working properly!!!

### ISSUE THREAD

**Issue by OmarBasem** [zo0r/react-native-push-notification#1612]
# Bug

onNotif() function which should be called when a notification is opened is not working properly on iOS. It is working properly on Android though.
There are 3 weird things happening on iOS:
1. onNotif() function gets called before opening the notification, then gets called again when the notification is opened.
2. The first time when it gets called before opening the notification (although is should not), the message object passed should be the one from calling PushNotification.localNotification, but instead it just gets the message object received from the server as it is without any parsing from PushNotification.localNotification
3. When the function gets called after opening the notification, the message object passed has no data and user interaction is false, it only has message body and title:
`{"badge": undefined, "data": {"id": "0"}, "finish": [Function finish], "foreground": true, "id": "0", "message": "
Some message body", "soundName": undefined, "title": "Some title", "userInteraction": false}`

## Environment info

`react-native info` output:

```bash
 System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.69 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1 
    react-native: ^0.63.2 => 0.63.2 
```

Library version: 5.0.1
"@react-native-community/push-notification-ios": "^1.4.1"

## Steps To Reproduce

- Just receive and open a notification on iOS and you will notice the 3 weird behaviours mentioned above.

Describe what you expected to happen:

- I expected it to work properly as on Android. onNotification() should fire only when the notification is opened and get passed the right message object from PushNotification.localNotification

**Comment by Dallas62** [comment]
Hi,

Please refer to the iOS repository.

**Comment by OmarBasem** [comment]
@Dallas62 you mean the problem is from @react-native-community/push-notification-ios?

**Comment by Dallas62** [comment]
Yes, there is no specific iOS code in this repository,
https://github.com/react-native-community/push-notification-ios/issues/152

**Comment by OmarBasem** [comment]
Okay, thanks!
