### ISSUE TITLE
Android app is reloaded when push notification opened and onNotification is not triggered

### ISSUE THREAD

**Issue by MahmudHasanMenon** [zo0r/react-native-push-notification#1623]
My react-native android app is automatic reload when open local push-notification and sometimes onNotification is not get triggered.
1. when local notification show and i press the notification it reloads the whole app and onNotification is not called
2. sometimes onNotification get called when componentDidmount called without opening any local-push-notification

react-native : 0.61.2
react-native-push-notification: 5.0.1

Note: In react-native 0.63 version i didn't find this issue. in react-native 0.63 version local-push notification working fine.

here is my `AndroidManifest.xml`
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.freelancerid">

  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCEPT_HANDOVER" />
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
  <uses-permission android:name="android.permission.ANSWER_PHONE_CALLS" />
  <uses-permission android:name="android.permission.BODY_SENSORS" />
  <uses-permission android:name="android.permission.CALL_PHONE" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.GET_ACCOUNTS" />
  <uses-permission android:name="android.permission.PROCESS_OUTGOING_CALLS" />
  <uses-permission android:name="android.permission.READ_CALENDAR" />
  <uses-permission android:name="android.permission.READ_CALL_LOG" />
  <uses-permission android:name="android.permission.READ_CONTACTS" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
  <uses-permission android:name="android.permission.READ_PHONE_STATE" />
  <uses-permission android:name="android.permission.READ_SMS" />
  <uses-permission android:name="android.permission.RECEIVE_MMS" />
  <uses-permission android:name="android.permission.RECEIVE_SMS" />
  <uses-permission android:name="android.permission.RECEIVE_WAP_PUSH" />
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.SEND_SMS" />
  <uses-permission android:name="android.permission.USE_SIP" />
  <uses-permission android:name="android.permission.WRITE_CALENDAR" />
  <uses-permission android:name="android.permission.WRITE_CALL_LOG" />
  <uses-permission android:name="android.permission.WRITE_CONTACTS" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="com.android.voicemail.permission.ADD_VOICEMAIL" />
  <uses-permission android:name="android.permission.VIBRATE" />
  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">

      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
                android:value="YOUR NOTIFICATION CHANNEL NAME"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                    android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION"/>

                      
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="false"/>
        
        <meta-data  android:name="com.dieam.reactnativepushnotification.channel_create_default"
                    android:value="true"/>
        
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@color/white"/> 
 
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
 
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

       <activity
            android:name=".SplashActivity"
            android:theme="@style/SplashTheme"
            android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />  
            </intent-filter>
        </activity>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="stateAlwaysHidden|adjustPan"
        android:exported="true">
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
`

**Comment by Dallas62** [comment]
Hi @MahmudHasanMenon 
I suggest you to search in the issues history, this has been discussed recently and it's probably due to the splash screen activity.
Best regards

**Comment by MahmudHasanMenon** [comment]
@Dallas62  thanks a lot.....please help me to find out or give that link where it is discussed?

**Comment by MahmudHasanMenon** [comment]
@Dallas62  [https://github.com/zo0r/react-native-push-notification/issues/1592#issuecomment-675587198] i tried this but my issue is not solved. Please help me and suggest some solution.

**Comment by MahmudHasanMenon** [comment]
this worked for me..... `AndroidManifest.xml`
`<activity
android:name=".MainActivity"
android:launchMode="singleTask"`

**Comment by AdrianBordeianu** [comment]
> this worked for me..... `AndroidManifest.xml` `<activity android:name=".MainActivity" android:launchMode="singleTask"`

not working for me either, still trying to figure this out

when in background/ killed, on Press notification triggers onNotification and everything works fine
when in foreground, onNotification is triggered, but the app reloads so its effect is not applied

Any progress?

**Comment by Srikanth-OneCode** [comment]
> 

Yes same here. Facing the same issue as @AdrianBordeianu

**Comment by AdrianBordeianu** [comment]
<img width="629" alt="Screenshot 2021-12-13 at 16 40 00" src="https://user-images.githubusercontent.com/37770519/145832118-c39eff8c-d104-42e6-ab81-711c94c4c2b3.png">
For me the issue was that I did not add the userInfo object on localNotification, and because of that it didn t have data to navigate with, causing that sort of refresh. Solved it by putting redirect data on userInfo
