### ISSUE TITLE
cannot find symbol InstanceIdResult

### ISSUE THREAD

**Issue by mxmzb** [zo0r/react-native-push-notification#1629]
I'm running into the following error when I compile my app for Android: 

```
some/path/RNPushNotification.java:39: error: cannot find symbol
import com.google.firebase.iid.InstanceIdResult
```

I've very carefully examined the docs, tried multiple variations of it, and couldn't get it to work. I don't need remote notifications, only `localNotificationSchedule()`. I've even tried the same setup as the example app plus an app which I've built a year ago or so and where this library had worked fine.

I'm currently on:
- RN 0.61.5
- react-native-push-notification: 5.1.0

This is what my `AndroidManifest.xml` looks like:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools" package="com.goodtendency">

  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
  <uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove" />

  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:allowBackup="false" android:theme="@style/AppTheme">
    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize" android:windowSoftInputMode="adjustResize">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
      <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
      </intent-filter>
    </receiver>

    <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService" android:exported="false">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>

    <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_name" android:value="GoodTendency"/>

    <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_description" android:value="Good Tendency notification channel"/>

    <!-- Change the value to true to enable pop-up for in foreground (remote-only, for local use ignoreInForeground) -->
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground" android:value="false"/>
    <!-- Change the value to false if you don't want the creation of the default channel -->
    <meta-data android:name="com.dieam.reactnativepushnotification.channel_create_default" android:value="false"/>
    <!-- Change the resource name to your App's accent color - or any other color you want -->
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_color" android:resource="@android:color/white"/>
    <!-- or @android:color/{name} to use a standard color -->

  </application>

</manifest>
```

I appreciate any help and if there is information missing from my setup, let me know what you're looking for and I will add it. Thanks a ton!

**Comment by Dallas62** [comment]
Hi,

```js

/**
   * (optional) default: true
   * - Specified if permissions (ios) and token (android and ios) will requested or not,
   * - if not, you must call PushNotificationsHandler.requestPermissions() later
   * - if you are not using remote notification or do not have Firebase installed, use this:
   *     requestPermissions: Platform.OS === 'ios'
   */
  requestPermissions: true,

```

This should solve your problem,

Regards

**Comment by mxmzb** [comment]
@Dallas62 Sorry, I meant the build process. It's happening when I build the app with Android Studio or when I run `./gradlew assembleDebug` in `./android/` directory. It's before the app even has started.

**Comment by Dallas62** [comment]
Hi @mxmzb,

I think this is because google services are not installed.

Actually it's not possible use this library without it

**Comment by mxmzb** [comment]
Could it be, that the current installation guide is out of syn in this case?

I've also tried to add the lines for google services as described here: https://github.com/zo0r/react-native-push-notification#if-you-use-remote-notifications and still having the same issue

**Comment by mxmzb** [comment]
Okay, it was due to an unrelated line that apparently locked google services package to 12.0.1 which I had in my gradle file from a different package. Thanks a lot!

**Comment by Naishadh8115** [comment]
`import com.google.firebase.iid.InstanceIdResult` Can not find symbol Can any buddy help me to resolve this error.

**Comment by kiritm-nimblechapps** [comment]
HI @mxmzb Can you say, Where I do change to solved the error ?

**Comment by Naishadh8115** [comment]
@kiritm-nimblechapps in my case i have commented below(bold styled) code from project level build.gradle and worked fine 
`
allprojects {
    repositories {
**//        configurations.all {
//            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
//                def requested = details.requested
//                if (requested.group == 'com.google.android.gms') {
//                    details.useVersion '12.0.1'
//                }
//                if (requested.group == 'com.google.firebase') {
//                    details.useVersion '12.0.1'
//                }
//            }
//        }**
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
`

**Comment by kiritm-nimblechapps** [comment]
HI, Please check @Naishadh8115 , What's i need to comment.


```
allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
```

**Comment by Naishadh8115** [comment]
@kiritm-nimblechapps Nothing to comment in you code, There would be some other error. Your case is different from mine.
