### ISSUE TITLE
cancelAllNotifications() doesn't work on Android

### ISSUE THREAD

**Issue by israelidanny** [zo0r/react-native-push-notification#163]
I have an app that uses this module both on Android and iOS. On iOS everything works flawlessly, but on Android `PushNotification.cancelAllLocalNotifications()` doesn't seem to work right. 

After cancelling notifications I still receive them.

**Comment by a-sierra** [comment]
Hi, I think that <PushNotification.cancelAllLocalNotifications()> is intended to clear notifications in status bar, not to actually cancel them.

**Comment by washaq** [comment]
any update on this guys? cancelAllLocalNotification works fine on IOS but not on android

**Comment by israelidanny** [comment]
@a-sierra How do you conclude that? 
On iOS it most definitely cancels notifications.

**Comment by washaq** [comment]
@israelidanny On Ios it work i already tested just call cancelAllLocalNotification and then schedule notification a spacific time on button press for ios only one notification called while in android its called as many time as i press the button means cancelAllLocalNotification only works on ios

**Comment by israelidanny** [comment]
@washaq same result here

**Comment by tsai0606** [comment]
Reading the android documentation on AlarmManager, there lacks the ability to cancel all PendingIntents that are set to the AlarmManager. There needs to be ability keep track of how many notification you have created and remove them one by one.

**Comment by npomfret** [comment]
There's a change in master that should fix this.  Is anyone able to help test before we push a release?

**Comment by carera** [comment]
How can I help?

**Comment by npomfret** [comment]
We already released, but still not too late to help test.  Some new features / fixes went in for android: 

 * cancelLocalNotifications
 * cancelAllLocalNotifications (which is similar but subtly different)
 * setApplicationIconBadgeNumber
 * scheduled notifications should be recovered after a reboot
 * you can now specify a soundName (both iOS and Android)
 * ...and something to do with actions, but am waiting on @varungupta85 to update the docs on this

**Comment by carera** [comment]
Great, I just installed the latest version and I can already confirm that `cancelAllLocalNotifications` now work on android as well.
