### ISSUE TITLE
play custom sound not work on xiaomi

### ISSUE THREAD

**Issue by chequochuu** [zo0r/react-native-push-notification#1634]
# Bug

I use code from the example. When I press "Local Notification with sound (now)"  it doesn't play any sound on my Xiaomi device. When I change to a new Samsung device,  it works. Do you know why and any solution for it?

**Comment by usmansbk** [comment]
The library stopped playing sound on Xiaomi after version 2

**Comment by usmansbk** [comment]
The library stopped playing sound on Xiaomi after version 2

**Comment by usmansbk** [comment]
Actually sound works perfectly on Xiaomi. Just that permission is not enabled by default. Go to app info, under notifications, enable "Allow sound"
