### ISSUE TITLE
I have an issue with updating channel importance

### ISSUE THREAD

**Issue by hoocem** [zo0r/react-native-push-notification#1638]
Hi, I am trying to update the channel importance in android using this function: 

updateChannel(id, importance) {
    PushNotification.createChannel(
      {
        channelId: id, 
        channelName: `Custom channel - Counter: ${id}`, 
        channelDescription: `A custom channel to categorise your custom notifications. Updated at: ${Date.now()}`,default: undefined.
        soundName: 'default', 
        importance: importance, // (optional) default: 4. Int value of the Android notification importance
        vibrate: true, 
      },
      (created) =>
        console.log(`createChannel returned '${created}'`,  ), // (optional) callback returns whether the channel was created, false means it already existed.
    );
  }

but every time I set the importance to lower value(going from 4 to 2 then from 2 to 0 per example) the channel update and the notification behaves as expected, but when I try to increase the importance value (going from 0 to 2 or 2 to 4) the notification behavior stays the same and nothing happens.
Any Idea on how to fix that ?

**Comment by Dallas62** [comment]
Hi,

This is the expected behavior, please refer to the Android documentation about updating channels.

Regards
