### ISSUE TITLE
onRegister does not trigger (I am not using firebase)

### ISSUE THREAD

**Issue by ZahraMirali** [zo0r/react-native-push-notification#1640]
I have set my project according to https://github.com/zo0r/react-native-push-notification/tree/master/example 
but with only 1 difference:  `requestPermissions: Platform.OS === 'ios'`  because I am not using firebase.
I want to try a remote notification using postman (` https://fcm.googleapis.com/fcm/send` ) 
but **onRegister** function isn't calling at all, how can I get **token**?

**Comment by Dallas62** [comment]
Hi,

Not sure to understand, you are not using Firebase but you use Firebase Cloud Messaging (fcm). I don't get it.

**Comment by ZahraMirali** [comment]
requestPermissions: true
