### ISSUE TITLE
LocalNotificationSchedule not working in android

### ISSUE THREAD

**Issue by PeterPham-robo** [zo0r/react-native-push-notification#1643]
# Bug
LocalNotificationSchedule is working perfect in ios but not working in android. My feat is set up times array in Local push notification schedule so i put the function in foreach. Here is my code. Thank for you help 👍 
## Environment info

SET UP CODE: 
_buildAndroidNotification = (
    id: string,
    title: string,
    message: string,
    data: any = {},
    options: any = {},
  ) => {
    return {
      id: id,
      autoCancel: true,
      largeIcon: options.largeIcon || 'ic_launcher',
      smallIcon: options.smallIcon || 'ic_launcher',
      bigText: message || '',
      subText: title || '',
      vibrate: options.vibrate || false,
      vibration: options.vibration || 300,
      priority: options.priority || 'high',
      importance: options.importance || 'high',
      data: data,
    };
  };

  _buildIOSNotification = (
    id: string,
    title: string,
    message: string,
    data: any = {},
    options: any = {},
  ) => {
    return {
      alertAction: options.alertAction || 'view',
      category: options.category || '',
      userInfo: {
        id: id,
        item: data,
      },
      // repeatInterval: 'minute',
    };
  };

  showNotification = (config: {
    id: string;
    title: string;
    message: string;
    data?: any;
    options: Partial<PushNotificationScheduleObject> & {date: Date | string};
  }) => {
    const {id, title, message, data = {}, options} = config;
    PushNotification.localNotificationSchedule({
      ...this._buildAndroidNotification(id, title, message, data, options),
      ...this._buildIOSNotification(id, title, message, data, options),
      ...options,
      title: title || '',
      message: message || '',
      playSound: options.playSound || false,
      soundName: options.soundName || 'default',
      date: options.date,
    });
  };

USE IT:
const localPushNotification = (list: NotificationItem[]) => {
  list.forEach(item => {
    const options = {
      playSound: true,
      vibrate: true,
      date: new Date(item.schedule),
    };
    pushNotificationService.showNotification({
      id: '1',
      title: 'MyPillChart',
      message: 'It’s time to take your pills. Tap here to see your medicine.',
      options: options, // options}
      data: item,
    });
  })
}

**Comment by Dallas62** [comment]
Hi, the ID must be unique. Here, it's always 1.

**Comment by PeterPham-robo** [comment]
@Dallas62 Thanks for your answer. Ị just fixed it but notification still not working!

**Comment by Dallas62** [comment]
Ok, but what is not working, can you describe?
Currently, the Example project is working well.

**Comment by PeterPham-robo** [comment]
Yes, in the code up here, i put the push notification in the array and i take one by one by foreach then notification is not working. But when i gone out the array, push notification one item like this:

 const options = {
      playSound: true,
      vibrate: true,
      date: new Date(array[0].schedule),
    };
    pushNotificationService.showNotification({
      id: item.schedule.toString(),
      title: 'MyPillChart',
      message: 'It’s time to take your pills. Tap here to see your medicine.',
      options: options, // options}
      data: item,
    });
and it working. But the problem is i don't know how to do with the rest of the elements if not foreach

**Comment by johnhwang87** [comment]
I also have the same problem for android. In IOS, localNotificationSchedule works properly in a loop, they will get scheduled properly. In Android, it seems that instead of queuing, it will actually replace the previous one instead of being scheduled together, so once the loop finishes, only the last notification is scheduled.

**Comment by Dallas62** [comment]
Please check channels and also other issues about schedulded notifications.
Regards,

**Comment by mashad6** [comment]
Any solution? I'm facing the same issue.
