### ISSUE TITLE
invokeApp: false is ignored and onAction ist not firing

### ISSUE THREAD

**Issue by legsoft** [zo0r/react-native-push-notification#1644]
I have now tried a lot and researched a lot but nothing helped.

First of all "**onNotification**" did not fire. So I took a look at the example code and adjusted my code so that it works now. But "**onRegister**" and "**onAction**" still don't work although my code doesn't differ much from the example code.

I also tried the event listener "**notificationActionReceived**". But this one doesn't seem to fire either.

Furthermore, the parameter "**invokeApp**" seems to have no effect at all. If it is set to "**false**" the app still comes to the foreground. 

This is how the code from the "**localNotification**" looks like:

```
onNotification(notification) {
    if ('actions' in notification && notification.tag == "yturl")
    {
        //setTimeout(function(notification){Linking.openURL(notification.url);},1000,notification);
    }
    if ('yt' in notification)
    {
       PushNotification.localNotification({
        ticker: notification.title, 
        autoCancel: true,
        largeIcon: "ic_launcher",
        largeIconUrl: "https://www.example.tld/picture.jpg",
        smallIcon: "ic_notification",
        bigText: notification.msg,
        subText: notification.submsg,
        bigPictureUrl: "https://www.example.tld/picture.jpg",
        color: "green",
        vibrate: true,
        vibration: 300,
        tag: "yturl",
        group: "group",
        groupSummary: false,
        ongoing: false,
        priority: "high",
        importance: "high",
        ignoreInForeground: false, onlyAlertOnce: false, 
        actions: '["'+notification.title+'", "No"]', 
        invokeApp: false, 
        alertAction: "view", 
        id: 0, 
        title: notification.title, 
        message:notification.msg,
        userInfo: {}, 
        playSound: false, 
        soundName: "default",

      });

      PushNotification.registerNotificationActions([notification.btn,"No"]);
      DeviceEventEmitter.addListener('notificationActionReceived', function(action){
        console.log ('Notification action received: ' + action);

      });
    }



    if (typeof this._onNotification === 'function') {
      this._onNotification(notification);
    }
  }
```

Also "PushNotification.configure"

```
PushNotification.configure({
      onRegister: this.onRegister.bind(this),
      onNotification: this.onNotification.bind(this),
      onAction: this.onAction.bind(this),
      onRegistrationError: this.onRegistrationError.bind(this),
      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },
      popInitialNotification: false,
      requestPermissions: true,
    });


```

"**PushNotification.configure**" is also not called within a "**component**". Receiving notifications in the background, even if the app is completely closed, works fine. Strange is that when you click on the action of the notification "**onNotification**" fires again and not "**onAction**".

My goal is to call up a URL in the browser for a certain type of notification when the user confirms this with an "**action**". Currently I have a workaround for this which only works if the app is not closed completely because then "**onNotification**" does not fire again because the app must be involved.

**Comment by Dallas62** [comment]
Hi,
First all, what is the version of the library ?
Then, can you provide the AndroidManifest ?

Also, It would be great to provide the full code where `.configure` is called, I see many indent so maybe a problem with the call hierarchy.

**Comment by Dallas62** [comment]
You can remove this, this is not needed in recent version.

```js
      PushNotification.registerNotificationActions([notification.btn,"No"]);
      DeviceEventEmitter.addListener('notificationActionReceived', function(action){
        console.log ('Notification action received: ' + action);

      });
```

**Comment by legsoft** [comment]
Okay I'm sorry my package.json was misconfigured, I thought ist was updated but the package was still on version 3.1.9. I updated now to 5.1.0 and it's working fine now

Thank you very much
