### ISSUE TITLE
Is silent notification trigger Use-Effect?

### ISSUE THREAD

**Issue by c7nasr** [zo0r/react-native-push-notification#1645]
# Is silent notification trigger Use-Effect?

have a question I'll remotely send a SILENT notification to be received from Notification Listener and trigger a service. 

but I saw in docs that if app not running the notification will open the app. is that mean that useEffect will run or not? 

Thanks

**Comment by Dallas62** [comment]
Hi @c7nasr 
The application will start in background, but component will not be mounted, and `useEffect` will not be called because the component is not mounted.
https://github.com/zo0r/react-native-push-notification#usage
**DO NOT USE .configure() INSIDE A COMPONENT, EVEN App**
> If you do, notification handlers will not fire, because they are not loaded. Instead, use .configure() in the app's first file, usually index.js.

**Comment by c7nasr** [comment]
> Hi @c7nasr 
> The application will start in background, but component will not be mounted, and `useEffect` will not be called because the component is not mounted.
> https://github.com/zo0r/react-native-push-notification#usage
> **DO NOT USE .configure() INSIDE A COMPONENT, EVEN App**
> > If you do, notification handlers will not fire, because they are not loaded. Instead, use .configure() in the app's first file, usually index.js.

Thanks for your help
