### ISSUE TITLE
How to change channel name

### ISSUE THREAD

**Issue by mayconbenito** [zo0r/react-native-push-notification#1646]
# I can't change the notification channel name

I tried editing AndroidManifest.xml but it didn't work

`
<meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_name.sync-data"
                  android:value="sync-data"/>
<meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_description.sync-data"
                  android:value="Sync Data"/>
`

![Screenshot_1600178089](https://user-images.githubusercontent.com/28637562/93221340-0ad83600-f744-11ea-9b26-6932e4191b51.png)

**Comment by Dallas62** [comment]
Hi @mayconbenito 
For complex management of the channel name, I recommend you to use the methods described here:
https://github.com/zo0r/react-native-push-notification#channel-management-android

If you want to use only the XML, the channel is updated when a notification is triggered.
