### ISSUE TITLE
Channel name updated when sending local notification

### ISSUE THREAD

**Issue by piotrponikowski** [zo0r/react-native-push-notification#1649]
I have created custom channel: 
```javascript
    PushNotification.createChannel(
      {
        channelId: 'myid',
        channelName: 'Channel Name',
        channelDescription: 'Channel Description',
      },
      created => console.log(create)
    );
```
and then somewhere in my code I created new local notification:
```javascript
    PushNotification.localNotification({
      title: 'Title',
      message: 'Message',
      channelId: 'myid',
    });
```

After this my channel name has been updated back to default value: 'rn-push-notification-channel'

Looks like this is caused by this check:
https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L946
Is it intentional behavior?

Based on source code I was able to find workaround by providing channelName and channelDescription when sending notification, however these attributes are not documented.

```javascript
    PushNotification.localNotification({
      title: 'Title',
      message: 'Message',
      channelId: 'myid',
      channelName: 'Channel Name',
      channelDescription: 'Channel Description',
    });
```

**Comment by Dallas62** [comment]
Hi @piotrponikowski 
This is not the expected behaviour, I will look into it.
Regards,

**Comment by andkom** [comment]
I have same issue

**Comment by CaptBoscho** [comment]
Happening to me, and it triggers 2 notifications with the RNPushNotification.presentLocalNotification

**Comment by Dallas62** [comment]
Hi,
I didn't made update on this issue, but I recommend you to keep creating channels by yourself (like you mentioned):
```js
    PushNotification.createChannel(
      {
        channelId: 'myid',
        channelName: 'Channel Name',
        channelDescription: 'Channel Description',
      },
      created => console.log(create)
    );
```

In order to simplify the library and also avoid some complex edges cases, the following behaviour will be removed:
- Auto creation of channels

This means the creation of the channel must be made before you trigger a notification. And this will solve this issue.

**Comment by Dallas62** [comment]
You can test changes on `dev` branch.

Please refer to the CHANGELOG for update instructions:
https://github.com/zo0r/react-native-push-notification/blob/dev/CHANGELOG.md#unreleased

To install this version:
```
npm install zo0r/react-native-push-notification#dev
```
OR
```
yarn add zo0r/react-native-push-notification#dev
```

Make sure your build cache is cleaned.

**Comment by piotrponikowski** [comment]
I tested with `dev` branch and it works correctly for me - channel name is not overwritten to default name anymore.

Thank you for help!

**Comment by Dallas62** [comment]
Thanks for your feedback !

**Comment by CaptBoscho** [comment]
It works great for me as well- do you know when you'll be releasing ths update?

**Comment by Dallas62** [comment]
I will do hit at this Friday, don't have enough time this week in case of issues.

**Comment by Dallas62** [comment]
Just released 😉
