### ISSUE TITLE
foreground is always set to false in android

### ISSUE THREAD

**Issue by varungupta85** [zo0r/react-native-push-notification#165]
I am using this package for handling local/remote notifications in Android and for me, the `foreground` field is always set to `false` for local notification. I can see that in the code also, it just set to false for local notification. For remote notification, it is set based on some logic. Is it expected? Why is the foreground value not set appropriately for local notification also?

**Comment by varungupta85** [comment]
@npomfret Thanks. I have been using `AppState` in iOS to figure out if the notification was received in the foreground and background and it works great but I have had some issues with using `AppState` in android. It seems to always say `background` for android at least in the emulator. Have you used `AppState` API in android successfully in the past?

**Comment by npomfret** [comment]
Yes, AppState switches to 'background' from 'active' and back again perfectly on Android.  I'm using a physical device run-in 4.1.2
