### ISSUE TITLE
Do I need to configure firebase to use onAction?

### ISSUE THREAD

**Issue by luizgallas** [zo0r/react-native-push-notification#1650]
I am trying to implement action buttons in my scheduled notification but everytime I try to use .configure this error shows up:
Default FirebaseApp is not initialized in this process. Make sure to call FirebaseApp.initializeApp(context) first.
Why do I need to do this if I am only using local notifications?

**Comment by Dallas62** [comment]
Hi,
No you don't need Firebase, please read the Usage part with `requestPermissions`.
