### ISSUE TITLE
notification.finish() on Android

### ISSUE THREAD

**Issue by robertgreso** [zo0r/react-native-push-notification#1652]
# Question

I found in your docs that `notification.finish(PushNotificationIOS.FetchResult.NoData)` is required to be called in `onNotification()` after the notification is handled. 
Want to ask, if its required just on iOS or on Android as well? If also on Android what should be the parameter? `PushNotificationIOS.FetchResult.NoData` as on iOS or something else?

Thank you for clarification!

**Comment by Dallas62** [comment]
Hi,
This is iOS specific, no effect on Android.
Regards

**Comment by robertgreso** [comment]
Thanks so much for such a fast response!
Have a great day!
