### ISSUE TITLE
What is the correct payload to send?

### ISSUE THREAD

**Issue by reactnative103** [zo0r/react-native-push-notification#1653]
Hi Team,

Can you please help me with what is the correct payload to send? 
Because I am getting nothing in 'data' parameter in both the case when app in foreground/background.

Send Payload(via https://www.apnstester.com/fcm/):

{
  "registration_ids":[TOKEN],
  "notification": {
    "title": "up 1.43% on the day",
  },
  "data": {
    "data": {
	"destination": "https://www.youtube.com/watch?v=bBAfSPCfxyg",
	"ext": 1,
	"title": "yo",
	"alert": "hi message"
    }
  }
}

Reference from: https://github.com/zo0r/react-native-push-notification/issues/1628

Background payload response:
{"collapse_key": "com.test.push", "data": {}, "finish": [Function finish], "foreground": false, "from": "6390104477", "google.delivered_priority": "high", "google.message_id": "0:160041759449%130ad430130ad430", "google.original_priority": "high", "google.sent_time": 16004180744, "google.ttl": 2419200, "userInteraction": true}

Foreground payload response:
{"color": null, "data": {}, "finish": [Function finish], "foreground": true, "id": "163610691", "message": "Test message", "sound": null, "title": "YOUR TITLE", "userInteraction": false}

**Comment by Dallas62** [comment]
Hi,
You must follow the Firebase format.
Regards,

**Comment by reactnative103** [comment]
@Dallas62 : Thanks for quick reply.

Can you please share the Firebase format? If shared one is not firebase format.

Please help me for that.

**Comment by Dallas62** [comment]
This is available on the firebase documentation

**Comment by vinagrito-getpocketful** [comment]
@Dallas62 I think this one can be closed

**Comment by AgamGujralSD** [comment]
Hi @reactnative103 Did you find the solution for this? How did you fix this?

**Comment by reactnative103** [comment]
@AgamGujralSD Please check the below url that was help me.

https://firebase.google.com/docs/cloud-messaging/concept-options
