### ISSUE TITLE
How to customize the interval time of repeatType?

### ISSUE THREAD

**Issue by codeamo** [zo0r/react-native-push-notification#1655]
# Question
Hi everyone, is there a way to schedule notifications every weekday (Mon to Fri) or weekends(Sat & Sun)? I see that this library has pre-builtin limited options for scheduling notifications but would like to see how far you can customize this.

**Comment by Dallas62** [comment]
Hi,

You can simply schedule one notification per day on weekday repeated weekly.
And one notification per day for weekend repeated weekly.

This allow you to do what you want.

Regards

**Comment by codeamo** [comment]
hey @Dallas62, what would a simple working example of one notification per day for weekend repeated weekly?
am I supposed to set repeatType to "time" and then use repeatTime to specify the milliseconds between each interval?
also, does that mean after I need to calculate the nearest weekend that comes after the initial schedule date and then use the repeatTime to specify the week interval?
