### ISSUE TITLE
FCM token deactivated

### ISSUE THREAD

**Issue by dan-kuzbass** [zo0r/react-native-push-notification#1656]
Hello everyone. I tried to find my question on the Internet, but I did not find anything similar. Can a FCM token expire? Can a FCM token be deactivated after a prolonged non-use?

**Comment by Dallas62** [comment]
Hi,

Here the answer:

https://stackoverflow.com/questions/41982619/when-does-a-fcm-token-expire

**Comment by dan-kuzbass** [comment]
Ok, but my problem is, I haven't used the device for a long time and it feels like the token has expired because the push notifications have stopped sending. When I reinstall the app, the push notifications start coming. Not sure what could be the matter?

**Comment by Dallas62** [comment]
This is a Firebase problem, not from this library.

**Comment by dan-kuzbass** [comment]
> This is a Firebase problem, not from this library.

Ok, do you know how to deal with problem?

**Comment by tomto1** [comment]
> 
> 
> > This is a Firebase problem, not from this library.
> 
> Ok, do you know how to deal with problem?

Did you manage to solve it? I check token every time on app start but it still get disabled after couple days. And if app is in background i can't get new token.

**Comment by dan-kuzbass** [comment]
No, I have not solved this problem.

**Comment by vinagrito-getpocketful** [comment]
@dan-kuzbass It could help if you post some of your code where we can see the way you register against the push server
