### ISSUE TITLE
Foreground remote notifications sent to default channel. Background sent to proper custom channel

### ISSUE THREAD

**Issue by yvwbimpong** [zo0r/react-native-push-notification#1657]
# Pushnotification sends remote notification to the default channel when app in foreground even when they have been pushed to custom channel. Works fine in background/killed state.

Am I missing some configurations I need to put in place for it to properly be sent to the custom channel when the app is in the foreground and Pushnotification is processing it? If so can i get some pointers for putting them in place?

Here's how things are looking at the moment

```
//creating the channel
this.notif.createOrUpdateChannel({
      channelId: 'new-requests',
      channelName: 'New Requests',
      channelDescription: 'Channel for receiving alerts for new requests',
      soundName: 'newrequestsound',
    });
```

```
//sending remote notification from server
const fcmPayload = {
    notification: {
      title: "Test",
      body: "Background test",
      android_channel_id: "new-requests",
      channel_id: "new-requests",
    },
  };

admin
    .messaging()
    .sendToDevice(fcmToken, fcmPayload, {
      priority: "high",
      timeToLive: 45,
    })
```

```
Environment
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-firebase": "^5.6.0",
    "react-native-push-notification": "^5.1.1",
  },

```

Could really use some help on this.

**Comment by Bimpong** [comment]
@Dallas62 could i get some help here?

**Comment by Dallas62** [comment]
Hi,

Did you set the right value inside the AndroidManifest?
Refer to the readme for this.
