### ISSUE TITLE
onNotification is not getting triggered when i receive local notification

### ISSUE THREAD

**Issue by Dheeeraj** [zo0r/react-native-push-notification#1662]
# Question

Does onNotification trigger when a local notification is recieved?

im able to get local notification data when i click the notification but in my use case i need data as soon as i recieve local notification which is not happening 

any suggestion on how to get the notification data as soon as i recieve a local notification when app is active

**Comment by Dallas62** [comment]
Hi, this question has already been answered multiple times, please search on the history.
Also look at the Firebase documentation:

https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages

**Comment by Dheeeraj** [comment]
@Dallas62 sorry if its too much to ask 
i came across this link but not able to understand the native code. should i be building bridge to receive the notification data or just some settings to be done so that i will recieve  the notification data in onNotification 
i couldnt find any reference on how to do any help is much appreciated
thank you for your time

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification/issues/1431

**Comment by Dheeeraj** [comment]
@Dallas62 i have gone through those issues and article regarding this but my situation is different i am getting the data when i click the notification but not on receive 


// (required) Called when a remote is received or opened, or **local notification is opened**
this is the commented line in configure()  which says that onNotification will only be called when local notification is opened
is there a way to be called onNotification  when i receive  local schedule notification


im using the latest version
"react-native-push-notification": "^5.1.1",
"react-native": "0.61.2",

and also made sure configure is done in index

**Comment by Dallas62** [comment]
Hi,
Unfortunately, it's not possible to get `onNotification` called when a scheduled notification is triggered/received.
