### ISSUE TITLE
Twilio - Can I modify the notification data before showing?

### ISSUE THREAD

**Issue by axeljeremy7** [zo0r/react-native-push-notification#1663]
I am using twilio and the payload i received is:
`"data": {
"channel_title":"0cc332deda83ce6df5a80b4aa18d0e11|2363ce7c6cb4608182",
"twi_body":"0cc332deda83ce6df5a80b4aa18d0e11|2363-ce7c6cb4608182;Augustine Sanders: 90",
"twi_message_id":"RUbb4b9652c1bb03c5af6deee28de02acd",
"channel_sid":"CH05e2a2e60ed0449f94de551fc57a297b",
"twi_message_type":"twilio.channel.new_message",
"message_sid":"IM1fbbef38a12941e581625babbfac631c",
"message_index":"657",
"author":"Augustine Sanders",
"message_id":"IM1fbbef38a12941e581625babbfac631c",
"channel_id":"CH05e2a2e60ed0449f94de551fc57a297b"}`

The notification is parse with title as the name of the app and the body as `twi_body`, since this has this value`0cc332deda83ce6df5a80b4aa18d0e11|2363-ce7c6cb4608182;Augustine Sanders: 90` , I haven't found a way to modify the payload when i received, I would like just this `Augustine Sanders: 90`, but it looks like this package automatically use `twi_body` ad the value body. I want to know if I can modify before showing.

This  is so far with tag or version 3.5.2.  In this version, remote notifications works in foreground and background.

Log of what i  think is getting info
``` LOG  [DEVELOPMENT LOG]
 LOG  onNotification()
 LOG  [typeof] => object
 LOG  [KEYS]
 LOG  ["foreground", "finish", "userInteraction", "id", "data", "message"]
 LOG  [ENTRIES]
 LOG  "foreground": false
 LOG  "finish": undefined
 LOG  "userInteraction": false
 LOG  "id": 442067936
 LOG  "data": {"channel_id":"CH05e2a2e60ed0449f94de551fc57a297b","message_id":"IMc53e9268190a486c9247fce6ae0cefbd","author":"Augustine Sanders","message_index":"668","message_sid":"IMc53e9268190a486c9247fce6ae0cefbd","twi_message_type":"twilio.channel.new_message","channel_sid":"CH05e2a2e60ed0449f94de551fc57a297b","twi_message_id":"RU85bec0cefa21ccf602bf128cf6a5b294","twi_body":"0cc332deda83ce6df5a80b4aa18d0e11|2363-ce7c6cb4608182;Augustine Sanders: 101","channel_title":"0cc332deda83ce6df5a80b4aa18d0e11|2363-ce7c6cb4608182"}
 LOG  "message": 0cc332deda83ce6df5a80b4aa18d0e11|2363-ce7c6cb4608182;Augustine Sanders: 101```

**Comment by Dallas62** [comment]
Hi,

I will look into it, I not a big fan of this implementation with twi_body, let the developers choose what to to look better to me.

What do you observe on iOS?

**Comment by axeljeremy7** [comment]
in ios, works only in foreground, i am still having issue with background notifications.

**Comment by Dallas62** [comment]
You can test changes on `dev` branch.

Please refer to the CHANGELOG for update instructions:
https://github.com/zo0r/react-native-push-notification/blob/dev/CHANGELOG.md#unreleased

To install this version:
```
npm install zo0r/react-native-push-notification#dev
```
OR
```
yarn add zo0r/react-native-push-notification#dev
```

Make sure your build cache is cleaned.

**Comment by axeljeremy7** [comment]
I tested and it doesn't show, and in both cases foregruound and background. I call to show the notification manually and it does not show.

```firebase.messaging().setBackgroundMessageHandler(async remoteMessage => {
  
    report(remoteMessage, 'Remote Message handled in the background!!');
    logInfoInstabug({data: remoteMessage, name: 'setBackgroundMessageHandler()'});
    showTwilioRemoteNotification(remoteMessage.data);
});```

**Comment by junocs** [comment]
I'm able to get Twilio message displayed on notification center, when app is background, by following this [idea](https://github.com/zo0r/react-native-push-notification/issues/1452#issuecomment-640591085). Here is the patch:
```
diff --git a/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java b/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java
index 1c92471..a0315bf 100644
--- a/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java
+++ b/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNReceivedMessageHandler.java
@@ -110,6 +110,15 @@ public class RNReceivedMessageHandler {
         Bundle dataBundle = new Bundle();
         Map<String, String> notificationData = message.getData();
 
+        if (!bundle.containsKey("message")) {
+            String twiMessage = notificationData.get("twi_body");
+            if (twiMessage != null && !twiMessage.isEmpty()) {
+                RNPushNotificationConfig config = new RNPushNotificationConfig(mFirebaseMessagingService.getApplication());
+                bundle.putString("message", twiMessage);
+                bundle.putString("channelId", "notify_channel");
+            }
+        }
+        
         for(Map.Entry<String, String> entry : notificationData.entrySet()) {
             dataBundle.putString(entry.getKey(), entry.getValue());
         }

```
Note that you have to create a channel first in order to get it working properly. In my case, it is `notify_channel`.
```
if (Platform.OS === 'android') {
        PushNotification.createChannel({
          channelId: 'notify_channel',
          channelName: 'Default push notifications channel',
        })
      }
```
Also putting this in the `AndroidManifest.xml`
```
<meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id" />
```
this in `values/strings.xml`
```
<string name="default_notification_channel_id" translatable="false">notify_channel</string>
```

**Comment by Dallas62** [comment]
Hi,

Since twilio send data-only, why don't you trigger a local notification with the corresponding field?
This is more simple than implement specific code for each notification provider.

**Comment by axeljeremy7** [comment]
@Dallas62 for android I am using firebase messaging to get the payload and then show to the user as local notification.

**Comment by axeljeremy7** [comment]
@Dallas62 for ios, i am able to show the notifications but the this time is automatically, so it show both always in foreground and background. I am doing a chat app, and when open a channel the notification still show that's the only issue, did you know if is possible to modify when to trigger the foreground notification in ios?

**Comment by axeljeremy7** [comment]
> Hi,
> 
> Since twilio send data-only, why don't you trigger a local notification with the corresponding field?
> This is more simple than implement specific code for each notification provider.

I am doing this, it works but i think I should edit on java to handle the payload, what is the expected payload for android notifications in this library?

**Comment by Dallas62** [comment]
Hi @axeljeremy7 

This will be not handled by this library. I don't want to handle each notifications provider.

**Comment by axeljeremy7** [comment]
@Dallas62 ok 👌, also  `handleRemotePushNotification` or `handleRemotePushNotification` in java, can you please tell where I should modify the payload so the notification will show?
I am using Twilio and I have no access to server that send the notifications, they have their own payload and I. cannot modify.
https://www.twilio.com/docs/notify/send-notifications?code-sample=code-receiving-a-notification-in-android&code-language=java&code-sdk-version=default
I want to modify in the java code, I understand that you don't want handle each provider.

**Comment by Dallas62** [comment]
There is no need to change the Java side.
Just handle the data-only notification in JS and transform/pass the values to `localNotification`.

**Comment by axeljeremy7** [comment]
@Dallas62 
I have the impression based on two versions ago, that when a remote notification is received, the library automatically
show the notification. In this new version, is the notification automatically appear? or I have to manually create a local notification when onNotification is activated?
```js
  // (required) Called when a remote or local notification is opened or received
  onNotification: handler.onNotification.bind(handler),
```

**Comment by Dallas62** [comment]
Data-only notification are not displayed by the library.
There was a fallback for that and Twilio notification some times ago, but I removed it since that leads to issues in some cases.
