### ISSUE TITLE
Group notification does not display on android 

### ISSUE THREAD

**Issue by RNTop** [zo0r/react-native-push-notification#1664]
# Bug

Group notification does not display on android.
So when I received 4 or more notifications on the android device, it should be grouped. but it is showing all the notifications. 
very very confused...
Also, I have tested the example codes. it does not show notification as well. seems like the dev branch has a problem. 
So I have installed 5.1.1. it works well. but not for the group notification. it should be fixed asap.
Please see the following screenshot.
https://github.com/zo0r/react-native-push-notification/issues/1527
Here, Actually not sure he used which version... 
![Screenshot_1600910584](https://user-images.githubusercontent.com/51260671/94090226-1b8f4880-fde3-11ea-8aac-148dca3e0b3a.png)
Source codes- https://mab.to/XXgOrlVOE
## Environment info

```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz
    Memory: 4.96 GB / 24.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.7.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.1
      System Images: android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom
      Android NDK: 21.0.6113669
  IDEs:
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
```

Library version: 5.1.1

## Reproducible sample code

 ```
PushNotification.localNotification({
                    id: id,
                    message,
                    visibility: 'public',
                    group: "group", // (optional) add group to message,
                    groupSummary: true, // (optional) set this notification to be the group summary for a group of notifications, default: false

                });
```

https://developer.android.com/training/notify-user/group
the group notification should be work like the above sample

**Comment by RNTop** [comment]
https://developer.android.com/training/notify-user/group
the group notification should be work like the above sample

**Comment by Dallas62** [comment]
Please refer to the issue you linked, there is an example on how you must use the group (as the Android documentation describe it).

**Comment by RNTop** [comment]
Would you send the doc kindly, please?
