### ISSUE TITLE
do I need to worry about deleting delivered notification manually for locally scheduled notifications?

### ISSUE THREAD

**Issue by codeamo** [zo0r/react-native-push-notification#1666]
# Question
Hi there, I am scheduling notifications for future use and would like to clarify something. will the delivered notifications or past notifications be automatically deleted from local notification of the device or do I need to manually delete all delivered notifications? I am asking this just in case some users set multiple weekday reminders which could reach the threshold of how many local notifications I can store on the device.

Thanks

**Comment by babyrusa** [comment]
hello what was the answer for this? I'm looking for the answer too. Thank u @codeamo
