### ISSUE TITLE
onNotif does not interact with notifications if the app is closed

### ISSUE THREAD

**Issue by despossivel** [zo0r/react-native-push-notification#1667]
I'm trying to interact with the notification if the app is closed, but when clicking on the notification the app opens, but onNotif is not triggered.

does anyone know tell me something about this?

**Comment by Dallas62** [comment]
Hi @despossivel 
Can you search in issues ?
All kind of cases has been answered.
Regards

**Comment by despossivel** [comment]
hey @Dallas62, even looking like previous questions, none can help me.

And look that I'm reproducing the example

**Comment by Dallas62** [comment]
Ok but there is no information in your issue, such as:
- OS
- Version

**Comment by despossivel** [comment]
Android, version min 21

**Comment by despossivel** [comment]
RN: 0.62
react-native-code-push: 6.2.0

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification/issues?q=is%3Aissue+splashscreen

**Comment by despossivel** [comment]
@Dallas62  I believe this can help me, I will test.

**Comment by despossivel** [comment]
this worked for me   https://github.com/crazycodeboy/react-native-splash-screen/issues/289#issuecomment-428438463
