### ISSUE TITLE
why is APNS-token coming back for ios

### ISSUE THREAD

**Issue by dan-kuzbass** [zo0r/react-native-push-notification#1670]
How do i get the token FCM for IOS if i am working with Firebase only?

My token example for IOS: b0ec2490b3f183bb67563551898a1929efb68d14aec335e7b866fad6adbb51f3

**Comment by dan-kuzbass** [comment]
I cannot receive remote notifications on IOS and I suspect that the token is incorrect

**Comment by Dallas62** [comment]
Hi,

This is the expected behavior.
iOS: APNS token.
Android: Firebase token.

You can use RNFirebase/messaging for full Firebase support.

Regards

**Comment by dan-kuzbass** [comment]
Ok, how do I send a remote notification via firebase using a APNS-token?

**Comment by Dallas62** [comment]
Hi,
Since you don't need to install Firebase on iOS with this library, you can use another library rnfirebase/messaging to get a FCM token.
Or you can dig into the Firebase documentation, you can create FCM token server-side with and APN token: https://developers.google.com/instance-id/reference/server#create_registration_tokens_for_apns_tokens
Perhaps a SDK implement this method.
Regards

**Comment by dan-kuzbass** [comment]
Thanks

**Comment by rarenatoe** [comment]
The expected behavior is understandable, but I think it's a bit much to download @react-native-firebase/app and @react-native-firebase/messaging just for this tiny need. Is there any plan to allow to customize the expected behavior to just return FCM for all kinds of devices?

**Comment by kneza23** [comment]
> The expected behavior is understandable, but I think it's a bit much to download @react-native-firebase/app and @react-native-firebase/messaging just for this tiny need. Is there any plan to allow to customize the expected behavior to just return FCM for all kinds of devices?
> 
> This is all the pods it installed, just so I could call `messaging().getToken()`:
> Installing Firebase (6.34.0)
> Installing FirebaseCore (6.10.4)
> Installing FirebaseCoreDiagnostics (1.7.0)
> Installing FirebaseInstallations (1.7.0)
> Installing FirebaseInstanceID (4.8.0)
> Installing FirebaseMessaging (4.7.1)
> Installing GoogleDataTransport (7.5.1)
> Installing GoogleUtilities (6.7.2)
> Installing PromisesObjC (1.2.11)
> Installing Protobuf (3.13.0)
> Installing RNFBApp (8.4.7)
> Installing RNFBMessaging (7.9.2)
> Installing nanopb (1.30906.0)

I agree. Does anyone know how to bypass @react-native-firebase/messaging for getting FCM token on iOS?
