### ISSUE TITLE
local push notifications not showing on android

### ISSUE THREAD

**Issue by monkin77** [zo0r/react-native-push-notification#1673]
# Bug

So I've been trying to implement this library for local push notifications but I can't see any notification. I dont have any errors on compilation, so I don't know what I'm missing out. 

As referred I have the following function on index.js:
PushNotification.configure({
    
    // (optional) Called when Token is generated (iOS and Android)
    onRegister: function (token) {
      console.log("TOKEN:", token);
    },
    
    // (required) Called when a remote is received or opened, or local notification is opened
    onNotification: function (notification) {
      console.log("NOTIFICATION:", notification);
  
      // process the notification
  
      // (required) Called when a remote is received or opened, or local notification is opened
      notification.finish(PushNotificationIOS.FetchResult.NoData);
    },
  
    // (optional) Called when Registered Action is pressed and invokeApp is false, if true onNotification will be called (Android)
    onAction: function (notification) {
      console.log("ACTION:", notification.action);
      console.log("NOTIFICATION:", notification);
  
      // process the action
    },
    popInitialNotification: true,
    requestPermissions: true,

  });

and on my screen I have a button with the following action:
<Button title='Send Push Notification' onPress={() => {
              PushNotification.localNotification({
                channelId: "general channel",
                title: "My Notification Title", // (optional)
                message: "My Notification Message", // (required)
              });
            }} />

Is there anything more to do that I am missing?

**Comment by Dallas62** [comment]
Did you create the channel ?

**Comment by monkin77** [comment]
I did not. How should I do it?

**Comment by GiotisK** [comment]
> # Bug
> So I've been trying to implement this library for local push notifications but I can't see any notification. I dont have any errors on compilation, so I don't know what I'm missing out.
> 
> As referred I have the following function on index.js:
> PushNotification.configure({
> 
> ```
> // (optional) Called when Token is generated (iOS and Android)
> onRegister: function (token) {
>   console.log("TOKEN:", token);
> },
> 
> // (required) Called when a remote is received or opened, or local notification is opened
> onNotification: function (notification) {
>   console.log("NOTIFICATION:", notification);
> 
>   // process the notification
> 
>   // (required) Called when a remote is received or opened, or local notification is opened
>   notification.finish(PushNotificationIOS.FetchResult.NoData);
> },
> 
> // (optional) Called when Registered Action is pressed and invokeApp is false, if true onNotification will be called (Android)
> onAction: function (notification) {
>   console.log("ACTION:", notification.action);
>   console.log("NOTIFICATION:", notification);
> 
>   // process the action
> },
> popInitialNotification: true,
> requestPermissions: true,
> ```
> 
> });
> 
> and on my screen I have a button with the following action:
> <Button title='Send Push Notification' onPress={() => {
> PushNotification.localNotification({
> channelId: "general channel",
> title: "My Notification Title", // (optional)
> message: "My Notification Message", // (required)
> });
> }} />
> 
> Is there anything more to do that I am missing?

Just set a channelId value. I had the same problem and it was fixed.

**Comment by monkin77** [comment]
Yea I've done that and it worked! Just had to create the channel and use it on localNotification method

**Comment by erickcrus** [comment]
Here localnotification "works" only when app state is closed.

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification#state-of-the-repository
