### ISSUE TITLE
Question: How to get notification title and message when user clicks on notification (while app is in background) and is navigated back to app.

### ISSUE THREAD

**Issue by martin-dutch** [zo0r/react-native-push-notification#1682]
# Question
I am trying to implement personalized notification for users and am using pusher beams to send notifications to those users.
When the app is running in the foreground I receive the notification perfectly and it shows me the content of the notification.

<img width="573" alt="Screenshot 2020-10-01 at 11 34 35" src="https://user-images.githubusercontent.com/60556070/94798838-1715f180-03da-11eb-9dc6-7ca628e469b5.png">

However, when I receive the notification in the background and I click on it from the Android notification list I can't retrieve the title and body of the notification but get this object instead.

<img width="572" alt="Screenshot 2020-10-01 at 11 35 36" src="https://user-images.githubusercontent.com/60556070/94798917-3b71ce00-03da-11eb-911a-2732b0b79cac.png">

My question is, How do I get the title and description of the notification when the user clicks on it from outside the app? (aka from the notification list in android)

I am currently developing and testing on Android.

Cheers

**Comment by Dallas62** [comment]
Hi,

You must add data in your notification, this information can't be retrieved with a normal notification.

Regards

**Comment by martin-dutch** [comment]
Hi @Dallas62 ,

Thanks, that worked.
Amazing job on the library btw.

Cheers
