### ISSUE TITLE
Unable to instantiate RNPushNotificationListenerService service when run test with Detox

### ISSUE THREAD

**Issue by elmotan95** [zo0r/react-native-push-notification#1684]
# Bug

I got an error when running test with detox

<img width="823" alt="image" src="https://user-images.githubusercontent.com/36393703/94983366-3f355a00-056c-11eb-910a-32bc10f1c7c9.png">

The issues lies on `react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationConfig.java`
Line 22 to 29.

I think since `getPackageManager()` return null, it can't find app name (CMIIW).
I change the catch argument from `PackageManager.NameNotFoundException e` to `Exception e`, it can run the test.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 21.94 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0. - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0.1 4.0.1
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library push notification version: 6.1.1
Detox version: 17.5.8
Jest version: 26.1.0

## Steps To Reproduce

1. Build APK for test with `detox build --configuration android.emu.staging.debug`
2. Run test with `detox test --configuration android.emu.staging.debug --jest-report-specs`
...

Describe what you expected to happen:

1. Test should not fail

## Reproducible sample code

-

**Comment by Dallas62** [comment]
Hi @elmotan95 
Thanks for the feedback, I'm not sure how this could be resolved. I can avoid the NullPointerException, but if your E2E testing framework doesn't load this information, this could lead to unexpected behaviour in the testing process.

**Comment by elmotan95** [comment]
I see. Do you have any idea? 
I'll try create new repo to isolate this issue with your example.
