### ISSUE TITLE
bigPictureUrl not working with remote notifications

### ISSUE THREAD

**Issue by mouradkaroudi** [zo0r/react-native-push-notification#1690]
# Bug

When I use bigPictureUrl in LocalNotifcation it's work fine. but when I use it with remote push notification not working !!

## Environment info

System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 6.74 GB / 15.78 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  Languages:
    Java: 12.0.1
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.1 => 0.63.1
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 6.1.1

`    PushNotification.localNotification({
      subText: 'This is a subText', // (optional) default: none
      bigPictureUrl: "http://example.com/image.jpg",
      message: 'My Notification Message', // (required)
    });
`
`{
    "registration_ids":["{ids}"],
    "notification": {  "title": "string", "bigPictureUrl": "http://example.com/image.jpg" }
 }`

**Comment by Dallas62** [comment]
Hi,
This is not a valid Firebase Key for notification. Please refer to the Firebase documentation before sending notification.
Regards

**Comment by Dallas62** [comment]
https://firebase.google.com/docs/cloud-messaging/http-server-ref

**Comment by mouradkaroudi** [comment]
Thank you @Dallas62 for your response.
But this has nothing to do with my question!!
I already setup push notification using firebase and it works perfectly with except for the bigPictureUrl

**Comment by Dallas62** [comment]
This as all to do with your problem.
`bigPuctureUrl` is not a valid key of the Firebase API, please refer to the documentation I linked.
Regards

**Comment by mouradkaroudi** [comment]
Ok.
So how can I pass image url to the request ?
I tried to add ‘imageUrl’ key to ‘data’ key. But still not working !
`data:{imageUrl: ‘’}`

**Comment by Dallas62** [comment]
https://firebase.google.com/docs/cloud-messaging/android/send-image

**Comment by mouradkaroudi** [comment]
@Dallas62 Thank you
