### ISSUE TITLE
Can we change the image size in local notification?

### ISSUE THREAD

**Issue by Aayushi1301** [zo0r/react-native-push-notification#1691]
# Question

I am sending an image url in` bigPictureUrl` but the image gets truncated from edges. Is there a way to increase the height of the image?
![image](https://user-images.githubusercontent.com/39982141/95453346-4bfce800-0988-11eb-9a08-68b029198a86.png)

**Comment by Dallas62** [comment]
Hi @Aayushi1301 
https://itnext.io/android-notification-bigpicturestyle-1f293e6cabaf
Regards
