### ISSUE TITLE
cannot find symbol method getChannelId() 7 android build failed

### ISSUE THREAD

**Issue by Sandipnag** [zo0r/react-native-push-notification#1694]
# Bug

cannot find symbol
            if(remoteNotification.getChannelId() != null) {
                                 ^
  symbol:   method getChannelId()
  location: variable remoteNotification of type Notification

## Environment info

`react-native info` output:

```bash
 "react-native": "0.63.2",
"react-native-push-notification": "^6.1.1",
```

Library version: x.x.x

## Steps To Reproduce

1.npm install --save react-native-push-notification
2. cd android
3. ./gradlew clean

**Comment by ianjsikes** [comment]
What was the solution to this @Sandipnag ? I am running into the same problem

**Comment by Ibrahimkara92** [comment]
Hello
I had the same problem with me
android/build.gradle in 
    ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        kotlinVersion = "1.3.72"

        googlePlayServicesVersion = "+" // default: "+"
        googlePlayServicesIidVersion = "+"
        firebaseMessagingVersion = "+" // default: "+"
    }
before, I had this
ext {
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        kotlinVersion = "1.3.72"

        googlePlayServicesVersion = "16.1.0" // default: "+"
        googlePlayServicesIidVersion = "16.0.1"
        firebaseMessagingVersion = "17.3.4" // default: "+"
    }
fixed issue when making version information +
Good work.
