### ISSUE TITLE
Sending local notifications without text and no badge

### ISSUE THREAD

**Issue by d0xi5** [zo0r/react-native-push-notification#1696]
# Question

Hello to all, thank you for your time and for reading first of all.

I'm working on a project that needs to play sounds while the app is on background, not long sounds, but **ring** shorts sounds, so thats why I thought of notifications. 

Of course, if the phone is on silent mode, it will only vibrate, and if its not on silent mode the sound will play and notify the user something happened on the app. 

This is working fine. **The problem:** I was asked to notify the users with the sound but not with the notification badge on the notifications center.. so, my question: **is there a way of sending local schedule notifications and only play sound, avoiding the notification on the notification center?**

Thank you for taking the time of reading.

**Comment by d0xi5** [comment]
@Dallas62 Is it possible?

**Comment by Dallas62** [comment]
Hi,

Take a look to the Android documentation about importance, this might help you.

**Comment by Dallas62** [comment]
And it's not possible to send a notification without text 😉
