### ISSUE TITLE
localNotificationSchedule but everyweek same day and hour

### ISSUE THREAD

**Issue by mtalhagaoglu** [zo0r/react-native-push-notification#1697]
Hi. I want to send local notification scheduled. For example every week on mondays at 09:00 it will send "good morning!" message. I read the documentation but i didn't quite understand. There is repeatType prop and date prop. as i understand repeatType should be week because it will be triggered every week on mondays but i didn't understand date prop. is it enough to be any monday at 09:00 date object?

```
PushNotification.localNotificationSchedule({
  //... You can use all the options from localNotifications
  message: "good morning", // (required)
  date: new Date(), //any monday at 09:00
  allowWhileIdle: true, // (optional) set notification to work while on doze, default: false,
repeatType: "week"
});
```

**Comment by Dallas62** [comment]
Hi, the date must be the next date you want to see a notification.
Not in the past and not too late in the future.

**Comment by mtalhagaoglu** [comment]
so counter will start from that day and send notification every week after that. thanks

**Comment by kristoff2016** [comment]
this is correct for every day in the morning at 8 AM?

`PushNotification.localNotificationSchedule({
      message: "Good moring",
      date: moment({ hour: 8, minute: 0 }),
      allowWhileIdle: true,
      repeatType: 'day'
    })`
