### ISSUE TITLE
Local Push Notifications not working on android since v-6.0.0

### ISSUE THREAD

**Issue by Shivangi2909** [zo0r/react-native-push-notification#1699]
Local notifications are not working since release of version - 6.0.0. Verified at the same time downgrading to 5.1.1 where it works fine!

**Comment by Dallas62** [comment]
Hi,

Did you at least read the change log with information on the upgrade?

Regards

**Comment by Shivangi2909** [comment]
Yes I did check the logs but I think its not mentioned there that background notifications doesn't work in android in the latest versions. Please can you mention exactly what I am missing so that I can have a look. Thanks!

**Comment by Dallas62** [comment]
You must create a channel to handle notifications.

**Comment by Shivangi2909** [comment]
I tried creating channel separately also to make it work but still had issue.

This way:
`PushNotification.localNotificationSchedule({
        //... You can use all the options from localNotifications
        id: 1,
        channelId: new Date(Date.now() + 5 * 1000) + '', // (required)
        channelName: 'My channel', // (required)
        message: 'My Notification Message', // (required)
        date: new Date(Date.now() + 5 * 1000), // in 60 secs
        allowWhileIdle: true, // (optional) set notification to work while on doze, default: false
        title: 'Sample Notification',
        body: 'Some description added in body',
        number: 10,
        playSound: true, // (optional) default: true
        soundName: 'default',
        importance: 4,
        vibrate: true,
      });`

Also this way:
` PushNotification.createChannel(
      {
        channelId: new Date(Date.now() + 5 * 1000) + '', // (required)
        channelName: 'My channel', // (required)
        channelDescription: 'A channel to categorise your notifications', // (optional) default: undefined.
        soundName: 'default', // (optional) See `soundName` parameter of `localNotification` function
        importance: 4, // (optional) default: 4. Int value of the Android notification importance
        vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
      },
      (created) => console.log(`createChannel returned '${created}'`), // (optional) callback returns whether the channel was created, false means it already existed.
    );`

**Comment by Dallas62** [comment]
If your channel id change every time, I don't know how you expect it to work.
You must define at least one channel with a unique id and the trigger all notifications you need in the right channel.

**Comment by Shivangi2909** [comment]
I checked with a single static id as well but was not working so tried again with the above solution.

**Comment by Shivangi2909** [comment]
I did not test with the example project earlier but just followed the steps.  Checked with example project that's working perfect! Thanks will check for the issue from example.
