### ISSUE TITLE
Notification while idle does not work

### ISSUE THREAD

**Issue by raphaelrupprecht** [zo0r/react-native-push-notification#1700]
# Bug

## Environment info

`react-native info` output:

```bash
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 23.0.1, 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-Q | Android TV Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_211
    Python: 2.7.18
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.1.1

## Steps To Reproduce

1. Checkout example project
2. I only use local notifications, so I need the following changes: 
2.1. remove service from AndroidManifest.xml 2.2 added meta-data element to AndroidManifest.xml for a custom channel id 2.3. outcomment apply plugin: 'com.google.gms.google-services' in build.gradle 2.4. outcomment classpath('com.google.gms:google-services:4.3.3') in the other build.gradle 2.5. requestPermissions: false in NotificationHandler
3. set allowWhileIdle: true in scheduleNotif function
4. connect device by cable and run "react-native run-android"
5. press "Schedule Notification in 30s"
6. immediately run "adb shell dumpsys deviceidle force-idle" to set device in doze mode

Describe what you expected to happen:

1. after 30 seconds the notification should be fired

What actually happens:

1. no notification is fired
2. the notification is retrieved when entering "adb shell dumpsys deviceidle unforce" to exit doze mode

## Reproducible sample code

See steps to reproduce

**Comment by Dallas62** [comment]
Hi,

What about the Android documentation ?
This parameter force the JobSchudler to execute the process while idle, but Android might have different notification management in this mode.

**Comment by raphaelrupprecht** [comment]
Hi Dallas,
thanks for replying. The library uses AlarmManager instead of JobScheduler (like the WorkManager does), right?
The Android API is not 100% clear for me [see here](https://developer.android.com/reference/android/app/AlarmManager#setExactAndAllowWhileIdle(int,%20long,%20android.app.PendingIntent)) 
Maybe this means that the API has certain liberties NOT to schedule at once.
