### ISSUE TITLE
onNotification return INCORRECT userInteraction status

### ISSUE THREAD

**Issue by TommyLeong** [zo0r/react-native-push-notification#1701]
# Bug

Upon receiving a remote notification while app is in the background mode (User can find the app in App Switcher), `onNotification` was triggered with the status of User Interaction TRUE returned. 

```
{ id: undefined,
  foreground: false,
  userInteraction: true,
  message: 'msg',
  data: 
   { 'gcm.message_id': 'masked_data',
     'google.c.a.e': 'masked_data',
     aps: 
      { alert: { body: 'testing', title: 'testing' },
        sound: 'default',
        'content-available': '1' },
     userInteraction: 1,
     'google.c.sender.id': 'testing',
     deeplink: 'myapp://profile',
},
  badge: undefined,
  title: 'testing',
  soundName: undefined,
  finish: [Function: finish] }
```

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 36.86 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-module: 0.19.0
    react-native-cli: 2.0.1
```

**Library Version**
"@react-native-community/push-notification-ios": "^1.5.0",
"react-native-push-notification": "^5.1.1",

## Steps To Reproduce

1. Push remote notification from portal
2. Keep my app in background (User can find the app via App Switcher)
3. App received notification (banner shows up) - Somehow, banner was missing from notification center after showing the alert. I suspect that's why the userInteraction return me as true? Like..something tapped on it? 
4. onNotification method return me incorrect userInteraction
...

Describe what you expected to happen:

Upon receiving remote notification, userInteraction should remain as false.

**Comment by TommyLeong** [comment]
Somehow I'm suspecting this happened because of `'content-available': '1'` which caused the app awake from background to process the notification (it's a data-only notification). 

Any idea from anyone?

**Comment by TommyLeong** [comment]
@Dallas62 the expert maybe? See if you have any idea about this? 🤔

**Comment by TommyLeong** [comment]
Closing this ticket, as I have wrote my logic to handle my use case scenario.

**Comment by ahadtechcarrot** [comment]
@TommyLeong please provide your solution logic code here
