### ISSUE TITLE
App get crashed when click on Local notification , if app is in foreground.

### ISSUE THREAD

**Issue by sargamverma** [zo0r/react-native-push-notification#1702]
# Bug
 scheduling local notification , i got local notifications , when i click on local notifications , App got crashed if application is in foreground.
when app is in background, on click of notification , it invoke the app , and redirect to app , that is working fine.
Please anyone can help .

I am using :
 PushNotification.localNotificationSchedule({
      id: this.props.user.user.userId,
      autoCancel: true,
      userInfo: { 123 },
      title: 'AYWA-Alert',
      message: ' data.',
      date: fireTime,
      foreground: true,
      repeatType:'time',
      subText:"",
      repeatTime:hourDiff,
      vibrate: true,
      invokeApp: true,
      playSound: true,
      soundName: 'default',
    })

React native :  "react-native-push-notification": "^3.1.2",

Thanks!

**Comment by Dallas62** [comment]
Hi,
Your version of the library is too old, and no information about the crash.
Closing.
