### ISSUE TITLE
Timestamp missing in notification banner [Android]

### ISSUE THREAD

**Issue by TommyLeong** [zo0r/react-native-push-notification#1704]
# Bug

Timestamp is missing at Android Notification Banner. At the screenshot below, you'll see timestamp of 1m & 16h is at the top of the notification. 

![image](https://user-images.githubusercontent.com/9990179/96089681-c8984500-0ef9-11eb-8a7f-10dfc9794abc.png)

## Environment info

Tested with Physical Device on Samsung Android 
OS: Android version 10

`react-native info` output:

```bash
   OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 1.43 GB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom_64, android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-module: 0.19.0
    react-native-cli: 2.0.1
```

"react-native-push-notification": "^5.1.1",

## Steps To Reproduce

1. Send notification to mobile
2. Upon receive notification banner, pull down notification tray
3. See notification banner with timestamp
...

## Describe what you expected to happen:

Expect to see timestamp, eg (now, 4m, 6h) 

## Reproducible sample code

The following code is under `.configure`
```
PushNotification.configure({
onNotification: (notification) => {
PushNotification.localNotification({
              showWhen: true,
              title: notification.data.gcm_title,
              message: notification.data.message,
              userInfo: notification.data,
            })
}

```

**Comment by Dallas62** [comment]
Hi,

This is probably because you are missing the parameter: `usesChronometer`.

Regards

**Comment by TommyLeong** [comment]
Hello @Dallas62  thanks for your reply. I actually updated my code to following, yet i still don't get the timestamp appear. 
Do you spot anything missing? 

```
PushNotification.localNotification({
              showWhen: true,
              usesChronometer: true,
              title: notification.data.gcm_title,
              message: notification.data.message,
              userInfo: notification.data,
            })
```

**Comment by Dallas62** [comment]
You can also try to ass the `when` field which is not set by default.

**Comment by TommyLeong** [comment]
Yea, i notice that actually. But can you show me an sample value for `when` field? 
I tried to add `11:30 AM` STRING earlier, didn't work out.

**Comment by TommyLeong** [comment]
@Dallas62 I have managed to get the timestamp appear! So the key is to pass `new Date().getTime()` to `when` field. We do not need the field `usesChronometer`, otherwise the timestamp will keep running like a stopwatch. 

Thanks for your help! (: 

Here's the final look of the code
```
PushNotification.localNotification({
              showWhen: true,  // This is probably no needed, since default value is TRUE.
              when: new Date().getTime(),
              title: notification.data.gcm_title,
              message: notification.data.message,
              userInfo: notification.data,
            })
```
