### ISSUE TITLE
Android scheduled local notifications don't fire if there's a unique custom ID included in configuration

### ISSUE THREAD

**Issue by NathanSaunders01** [zo0r/react-native-push-notification#1707]
If I pass a unique custom ID to my local scheduled notification, it won't fire on Android. The scheduled notifications work fine without the custom ID.

I have configured the PushNotification handler and set up a channel. Here is the configuration for my scheduled notification:

```
    PushNotification.localNotificationSchedule({
      channelId: 'generic',
      vibrate: true,
      largeIcon: '',
      color: 'purple',
      vibration: 300,
      priority: 'high',
      title: 'Is it the ID!',
      message: 'Hello friend',
      date: new Date(Date.now() + 10 * 1000),
      repeatType: 'hour',
      id: '8947534524376',
    });
```

Am I doing something wrong?

"react": "16.13.1",
 "react-native": "0.63.2",
"react-native-push-notification": "^6.1.1",
"@react-native-community/push-notification-ios": "^1.6.0",

**Comment by Dallas62** [comment]
Hi,

Not sure you are respecting the documentation. Not sure this is a valid integer (32bit).

**Comment by codaxe-labs** [comment]
Apologies, it's now working with a smaller number. Thank you for your work on the library and the quick response

**Comment by NathanSaunders01** [comment]
Apologies, it's now working with a smaller number. Thank you for your work on the library and the quick response

**Comment by cbahir** [comment]
I also having same issue, when I set id notification was not trigger but schedule was success.

```
// custom ID logic from library file
const ID = Math.floor(Math.random() * Math.pow(2, 32)).toString();

const NotificationConfig = {
      channelId: 'medicine_channel',
      title: "Time to Take Medicine",
      message: "PCM",
      vibration: 300,
      repeatType: "day",
      repeatTime: 1,
      allowWhileIdle: true,
      playSound: true,
      vibrate: true,
      id: ID,
      date: new Date(Date.now() + 10 * 10000),
  }

PushNotification.localNotificationSchedule(NotificationConfig)
```

After schedule notification get scheduled notification

```
[{"data": null, "date": 2021-09-21T06:47:57.528Z, "id": "4032057797", "message": "PCM", "number": null, "repeatInterval": "day", "soundName": null, "title": "Time to Take Medicine"}]
```

I don't know why this happens, **if i don't give ID into config then notification will trigger at the time. but if i gave ID then it's not trigger but showing it's scheduled**.

**Comment by pandey21197** [comment]
> I also having same issue, when I set id notification was not trigger but schedule was success.
> 
> ```
> // custom ID logic from library file
> const ID = Math.floor(Math.random() * Math.pow(2, 32)).toString();
> 
> const NotificationConfig = {
>       channelId: 'medicine_channel',
>       title: "Time to Take Medicine",
>       message: "PCM",
>       vibration: 300,
>       repeatType: "day",
>       repeatTime: 1,
>       allowWhileIdle: true,
>       playSound: true,
>       vibrate: true,
>       id: ID,
>       date: new Date(Date.now() + 10 * 10000),
>   }
> 
> PushNotification.localNotificationSchedule(NotificationConfig)
> ```
> 
> After schedule notification get scheduled notification
> 
> ```
> [{"data": null, "date": 2021-09-21T06:47:57.528Z, "id": "4032057797", "message": "PCM", "number": null, "repeatInterval": "day", "soundName": null, "title": "Time to Take Medicine"}]
> ```
> 
> I don't know why this happens, **if i don't give ID into config then notification will trigger at the time. but if i gave ID then it's not trigger but showing it's scheduled**.

Thats true!!!! if you remove "ID" local schedule notification will start working: 

Before:
async localScheduledNotification(notificationConfig) {
    const {id, title, message, date, id, dayType} =
      notificationConfig;

    const commonProps = {
      id,
      title,
      message: message,
      date: date,
      allowWhileIdle: true,
      importance: Importance.HIGH,
    };

    const androidProps = {
      channelId: channelId,
      smallIcon: 'ic_launcher_round',
    };

    const initNotification = () => {
      PushNotification.localNotificationSchedule({
        ...commonProps,
        ...(isAndroid ? androidProps : {}),
      });
    };
}

After: (working) !!!!!!!!

async localScheduledNotification(notificationConfig) {
    const {title, message, date, id, dayType, weekPlanDayIncrement} =
      notificationConfig;

    const commonProps = {
      title,
      message: message,
      date: date,
      allowWhileIdle: true,
      importance: Importance.HIGH,
    };

    const androidProps = {
      channelId: channelId,
      smallIcon: 'ic_launcher_round',
    };

    const initNotification = () => {
      PushNotification.localNotificationSchedule({
        ...commonProps,
        ...(isAndroid ? androidProps : {}),
      });
    };

**Comment by chetanbhadarka** [comment]
@pandey21197, if you create custom id as below then it's work.

```
\\ creating custom ID
const ID = Math.floor(Math.random() * Math.pow(2, 30)).toString();
```
