### ISSUE TITLE
React Native - Silent Notification

### ISSUE THREAD

**Issue by ankitaptagline** [zo0r/react-native-push-notification#1710]
Hello there,
I am using your library for the notification. I have setup with Firebase notifications.
**Requirements of the notification are I don't want to display the multiple same types of notification to my notification tray.**

I have tried as per your documentation,
https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md#3-silent-remote-push-notifications

I tried to remove the notification from the notification bar as per the below link, (But not working)
https://github.com/zo0r/react-native-push-notification#cancelling-notifications

I have reviewed the Silent Notification concept. But I am not able to receive the Silent notification event from this package.

Here I am attaching some responses and some piece of code, please review.
Apply this with the Local Notification,
**1.** aps: {
"content-available": 1,
sound: "",
},
**2.** aps: {
"content-available": 1,
sound: "",
},
priority: "high"
**3.** apns: {
headers: {
"apns-collapse-id": "post123",
"collpase_key": "post123"
}
},
priority: "high"

I have applied many solutions but could not be able to understand the Silent notification response and handle my application requirements (Not to display the multiple same types of notification to my notification tray).

**_Can you please help me to get the Silent push notification response from the Application side_** **or** **_How to remove the notification from the notification tray if the notifications have the same type of identifier_**?
**(For Foreground, Background, and Terminated State)**

Looking forward to your response,
Thanks.

**Comment by darksecu** [comment]
were you able to make it work ?

**Comment by ajaybhayani741** [comment]
@darksecu, Nope.

**Comment by ankitaptagline** [comment]
@darksecu,
Yes, by changing the notification payload. :)

**Comment by JakeMotta** [comment]
@ankitaptagline can you post the working payload you ended up using?
