### ISSUE TITLE
cancelAllLocalNotifications has been deprecated from iOS 10.

### ISSUE THREAD

**Issue by MRDANX** [zo0r/react-native-push-notification#1716]
The API of iOS "cancelAllLocalNotifications" has been deprecated from iOS 11, so it doesn't not work from iOS 11 or above.
Instead we need to invoke the new API called "removeAllDeliveredNotifications" of the library @react-native-community/push-notification-ios.

Reference link: https://developer.apple.com/documentation/uikit/uiapplication/1622990-cancelalllocalnotifications?language=objc

**Comment by Dallas62** [comment]
Hi @MRDANX 
Thanks for the report, but this method doesn't fit with the deprecated one:
https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649502-removealldeliverednotifications

`cancelAllLocalNotifications` and `removeAllDeliveredNotifications` are different in term of actions.

**Comment by Dallas62** [comment]
Hi,
Changes should be available on the iOS library.
I will look to apply changes ASAP.
Regards
