### ISSUE TITLE
onNotification getting called before tapping notification

### ISSUE THREAD

**Issue by iamlucnguyen** [zo0r/react-native-push-notification#1717]
For remote push notifications: onNotification is getting called as soon as notification receives before even user taps notification.
For local notifications: It doesn't call onNotification even after tapping it. Any solutions?

**Comment by Dallas62** [comment]
Hi,
Check the example project ? 😃

Both question have an answer in other issues.
Regards

**Comment by iamlucnguyen** [comment]
> Hi,
> Check the example project ? 😃
> 
> Both question have an answer in other issues.
> Regards

It's show notification, but onNotification not fire, only fire when user tap on notification

**Comment by iamlucnguyen** [comment]
I need some trigger callback when local notification received

**Comment by Dallas62** [comment]
> > Hi,
> 
> > Check the example project ? 😃
> 
> > 
> 
> > Both question have an answer in other issues.
> 
> > Regards
> 
> 
> 
> It's show notification, but onNotification not fire, only fire when user tap on notification
> 
> 

This is what the example project does.

**Comment by iamlucnguyen** [comment]
> This is what the example project does.

I mean like this issue https://github.com/zo0r/react-native-push-notification/issues/1024

**Comment by Dallas62** [comment]
> > This is what the example project does.
> 
> 
> 
> I mean like this issue https://github.com/zo0r/react-native-push-notification/issues/1024
> 
> 

This case can't be implemented with local notification.
Only silent notification can trigger `onNotification`.
This is an OS restriction.

**Comment by ZaidQ797** [comment]
Hi I have the same issue,I want to navigate base on the condition but on the notification and OnOpenNotification get called automatically before tapping the notification 
`componentDidMount = async () => {
   fcmService.registerAppWithFCM();
    fcmService.register(this.onNotification, this.onOpenNotification);
  };

  onNotification = (notify, remoteMessage) => {
    console.log('Zaid onNotification: ', notify);
    localNotificationService.configure(this.onOpenNotification);
    const options = {
      soundName: 'default',
      playSound: true, //,
  
    };
    localNotificationService.showNotification(
      0,
      notify.title,
      notify.body,
      notify,
      options,
    );
  };

  onOpenNotification = (notify) => {
    console.log('[App] onOpenNotification: ', notify);
    if (notify.clap === 'yes') {
      alert('hi');
    }
    // if (remoteMessage) {
    // }
  };`

**Comment by ZaidQ797** [comment]
> Hi I have the same issue,I want to navigate base on the condition but on the notification and OnOpenNotification get called automatically before tapping the notification
> 
> ```
> `componentDidMount = async () => {
>    fcmService.registerAppWithFCM();
>     fcmService.register(this.onNotification, this.onOpenNotification);
>   };
> 
>   onNotification = (notify, remoteMessage) => {
>     console.log('Zaid onNotification: ', notify);
>     localNotificationService.configure(this.onOpenNotification);
>     const options = {
>       soundName: 'default',
>       playSound: true, //,
>   
>     };
>     localNotificationService.showNotification(
>       0,
>       notify.title,
>       notify.body,
>       notify,
>       options,
>     );
>   };
> 
>   onOpenNotification = (notify) => {
>     console.log('[App] onOpenNotification: ', notify);
>     if (notify.clap === 'yes') {
>       alert('hi');
>     }
>     // if (remoteMessage) {
>     // }
>   };
> ```

I solved it by removing the service in AndroidManifest which is about open pop in foreground

**Comment by shashipatil** [comment]
I solved it by removing the service in AndroidManifest which is about open pop in foreground

Which service you are talking about?

**Comment by shashipatil** [comment]
> > Hi I have the same issue,I want to navigate base on the condition but on the notification and OnOpenNotification get called automatically before tapping the notification
> > ```
> > `componentDidMount = async () => {
> >    fcmService.registerAppWithFCM();
> >     fcmService.register(this.onNotification, this.onOpenNotification);
> >   };
> > 
> >   onNotification = (notify, remoteMessage) => {
> >     console.log('Zaid onNotification: ', notify);
> >     localNotificationService.configure(this.onOpenNotification);
> >     const options = {
> >       soundName: 'default',
> >       playSound: true, //,
> >   
> >     };
> >     localNotificationService.showNotification(
> >       0,
> >       notify.title,
> >       notify.body,
> >       notify,
> >       options,
> >     );
> >   };
> > 
> >   onOpenNotification = (notify) => {
> >     console.log('[App] onOpenNotification: ', notify);
> >     if (notify.clap === 'yes') {
> >       alert('hi');
> >     }
> >     // if (remoteMessage) {
> >     // }
> >   };
> > ```
> 
> I solved it by removing the service in AndroidManifest which is about open pop in foreground

which service you are talking about?

**Comment by flochtililoch** [comment]
I suppose @ZaidQ797 is talking about `com.dieam.reactnativepushnotification.notification_foreground`. Setting this to false prevents the notification from popping up when the app is in foreground, though.

@Dallas62 The problem seem to be that remote notifications are automatically triggering the `onNotification` handler when the app is in the foreground, before the notification is even tapped. That's a problem because there's no hook available to run code when the notification is actually opened (either by tapping directly from the temporary "toast" UI, or by pulling the notifications system drawer, and tapping on the notification). Any suggestion or configuration I may have missed?

**Comment by Dallas62** [comment]
Hi @flochtililoch
Please refer to the property `userInteraction` of the `notification` object.
Regards

**Comment by flochtililoch** [comment]
@Dallas62 My issue is that there are no subsequent calls to the `onNotification` handler upon pressing the notification. The handler is only called once (with `userInteraction: false`), but never called again when the push notification is tapped.

**Comment by Dallas62** [comment]
Search for closed issues about SplashScreen, probably an issue with your configuration.

**Comment by flochtililoch** [comment]
> Search for closed issues about SplashScreen

There are [18 issues with keyword SplashScreen](https://github.com/zo0r/react-native-push-notification/issues?q=is%3Aissue+SplashScreen+is%3Aclosed) - any additional pointers would be great! 😄 

When the app is running and in the foreground, and the push notification is received, `onNotification` handler is called:
- on Android, immediately upon receiving, but not called when the notification is pressed.
- on iOS, only upon pressing the notification, but not when the notification is received.

What is the expected behavior for both platforms?
Is the handler meant to be called twice, once with `userInteraction: false` and once with `userInteraction: true`?

> probably an issue with your configuration

Which part of the configuration would relate to this behavior?

**Comment by Dallas62** [comment]
Hi @flochtililoch 
If you have different behavior on iOS, please check the iOS repository which I don't maintain. All depends on what you put in the AppDelegate, search on iOS repository issues, you will probably find your answer.

`onNotification` should be called twiced, one time with `userInteraction` to false, then true if pressed.

If the notification doesn't trigger onNotification on press, this might come from the SplashScreen Activity.

I don't have more precision from my phone.

Regards

**Comment by flochtililoch** [comment]
Ok - I found the source of my issue. I have an override of `onNewIntent` in my MainActivity.java, which did not call super. This was key to get `onNotification` handler to be called when the push notification was pressed in the foreground:

```java
    @Override
    public void onNewIntent(final Intent intent) {
        super.onNewIntent(intent); // This is needed
        ...
```

Hopefully that helps others who faced similar issues (#122, #170).

I now realize that this recommendation was submitted in #549 but never merged.

**Comment by Dallas62** [comment]
#549 included in the readme.
https://github.com/zo0r/react-native-push-notification/commit/2e2226da3a1dd72cb1fb140ae9de51444d2f863d
