### ISSUE TITLE
detect local notification event when foreground

### ISSUE THREAD

**Issue by huurray** [zo0r/react-native-push-notification#1721]
Hello!
is there way to detect local notification event when foreground??

when it comes to LocalNotification, PushNotification.configure function can only get the moment when app opend.

how can i get the event even if i'm in foreground status.

please help me!!

```js
  PushNotification.configure({
   // local notification is opened only not recieved
    onNotification: function (notification) {
      notification.finish(PushNotificationIOS.FetchResult.NoData);
    },
    popInitialNotification: true,
    requestPermissions: true,
  });
```

**Comment by michaelVictoriaDev** [comment]
following.. I have also the same issue.

**Comment by matthieugayon** [comment]
I have the same issue here, @huurray have you found a way ? @Dallas62 ?
