### ISSUE TITLE
.createChannel is not a function

### ISSUE THREAD

**Issue by Benzer1406** [zo0r/react-native-push-notification#1723]
Hi,

I have the latest version installed "react-native-push-notification": "^6.1.2" and "@react-native-community/push-notification-ios": "^1.7.1", but when trying to create a channel as written in the README, I always get the error:

![Captura de Tela 2020-10-27 às 19 08 44](https://user-images.githubusercontent.com/33852084/97375084-e6659280-1887-11eb-9fd8-d36ba51be7da.png)

I ran npm install multiple times, rebuild the app, gradle synced, cleaned the project.

When I do a console log of the PushNotification object the createChannel method is not there.

![Captura de Tela 2020-10-27 às 19 06 53](https://user-images.githubusercontent.com/33852084/97375149-0ac16f00-1888-11eb-8e5d-5a9982a282ab.png)
<img width="472" alt="Captura de Tela 2020-10-27 às 19 07 09" src="https://user-images.githubusercontent.com/33852084/97375150-0bf29c00-1888-11eb-83cf-f3af0a0d5a9b.png">

**Comment by Dallas62** [comment]
Hi,
This definitely looks like a cache issue.
Clean you project again
Regards

**Comment by Benzer1406** [comment]
Indeed it was, closing the issue.

**Comment by sachin3018** [comment]
cleared the project cache still facing this issue
