### ISSUE TITLE
Work like an alarm clock

### ISSUE THREAD

**Issue by luizgallas** [zo0r/react-native-push-notification#1726]
There is any way of using this lib for an alarm clock app, repeating sound and vibration until I turn it off?

**Comment by shubhamkes** [comment]
did you get any solution? Even I am looking for something similar

**Comment by luizgallas** [comment]
Unfortunately not, I believe it is not possible with this lib

**Comment by Dallas62** [comment]
Hi,

It's a notification library, not an alarm library.

Regards
