### ISSUE TITLE
LocalNotification on v6.1.1 and v6.1.2 do not work, but changing to v4.0.0 or v5.1.1 it works

### ISSUE THREAD

**Issue by theagilecoder** [zo0r/react-native-push-notification#1727]
# Bug

LocalNotification on v6.1.1 and v6.1.2 do not work but changing the version in package.json to v4.0.0 or v5.1.1 , it works as expected.

This is my super simple app using react native 0.63.3

_/src/services/LocalPushController.js_
```
import PushNotification from 'react-native-push-notification'

PushNotification.configure({
  onRegister: function (token) {
    console.log('TOKEN:', token);
  },
  onNotification: function (notification) {
    console.log('NOTIFICATION:', notification);
  },
  permissions: {
    alert: true,
    badge: true,
    sound: true,
  },
  popInitialNotification: true,
  requestPermissions: Platform.OS === 'ios',
});

export const LocalNotification = () => {
  PushNotification.localNotification({
    autoCancel: true,
    bigText: 'This is local notification demo in React Native app. Only shown, when expanded.',
    subText: 'Local Notification Demo',
    title: 'Local Notification Title',
    message: 'Expand me to see more',
    vibrate: true,
    vibration: 300,
    playSound: true,
    soundName: 'default',
    actions: '["Yes", "No"]'
  });
}
```

_app.js_
```
import React from 'react';
import { LocalNotification } from './src/services/LocalPushController'
import { Text, View, Button, StyleSheet } from 'react-native';

const handleButtonPress = () => {
  LocalNotification()
}

const App = () => {
  return (
    <View style={styles.container}>
      <Text>Press a button to trigger the notification</Text>
      <View style={{ marginTop: 20 }}>
        <Button title={'Local Push Notification'} onPress={handleButtonPress} />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center'
  },
  buttonContainer: {
    marginTop: 20
  }
})

export default App;
```

## Environment info

`react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 9.33 GB / 23.37 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.17.0 - ~/.asdf/installs/nodejs/12.17.0/bin/node
    Yarn: Not Found
    npm: 6.14.4 - ~/.asdf/installs/nodejs/12.17.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: x.x.x

## Steps To Reproduce

1. Create react native project with the above two files to push a simple push notification. Clicking the button doesn't trigger push notification.
2. Change react-native-push-notification version in package.json to 4.0.0 or 5.1.1 and do npm install. Now button triggers local notif successfully.
3. Now change the version again to latest v6.1.2. Now it doesn't work.
...

Describe what you expected to happen:

1. Expected to run using v6.1.2 as it runs on v4.0.0 or v5.1.1
2.

## Reproducible sample code

Provided above

**Comment by Dallas62** [comment]
Hi,

> Expected to run using v6.1.2 as it runs on v4.0.0 or v5.1.1

Major version, means breaking changes. Please read the README, and Changelog. You will also find similar issues closed in the history.

Regards

**Comment by matthieugayon** [comment]
> Major version, means breaking changes. Please read the README, and Changelog. You will also find similar issues closed in the history.

That's not really helpful ... Same here I just cannot have local notifications working with that last version of the lib (6.1.3) (and without Firebase). I followed the readme, the example, tried removing my splashscreen, I'm logging my channel successfuly ... nothing. 

One question, has anybody managed to make it work without Firebase ? What are the exact meta-data tags to include in the manifest so that local notifications can be displayed while the app is in foreground mode ? 

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="...">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
      </activity>

      


      
      <meta-data  android:name="com.dieam.reactnativepushnotification.ignoreInForeground"
                  android:value="false"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                  android:value="true"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                  android:resource="@android:color/white"/>

      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED" />
              <action android:name="android.intent.action.QUICKBOOT_POWERON" />
              <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
          </intent-filter>
      </receiver>
 
    </application>

</manifest>`

MainActivity.java

`package com.cav;

import android.os.Bundle;
import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
import com.zoontek.rnbootsplash.RNBootSplash;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "cav";
  }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected ReactRootView createRootView() {
      return new RNGestureHandlerEnabledRootView(MainActivity.this);
      }
    };
  }

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);
  }
}
`

My notification service imported in App.js
initNotification is called in a useEffect in App.js
Notify is called automatically at some point after the initialization of the view by an async process, well after our useEffect but anyway this should not matter as teh configuration and the channel creation is executed at imports time

`
import PushNotification from 'react-native-push-notification';

import { startupApi } from '../Store'
import helper from '../Utils/category'

const CHANNEL_ID = 'local'

console.log('PushNotification.configure !!!!!!!!!!!!!!');

PushNotification.configure({
  onNotification: function (notification) {
    console.log("NOTIFICATION:", notification);

    if (notification && notification.userInfo) {
      const { userInfo } = notification
      console.log('--- notification data', userInfo)
  
      if (userInfo) {
        const { category, param } = userInfo
  
        if (param) {
          const { setSearch } = cavApi.getState()
          setSearch(param)
        }
    
        if (category) {
          navigate(category)
        }
      }
    }
  },
  permissions: {
    alert: true,
    badge: true,
    sound: true,
  },
  popInitialNotification: true,
  requestPermissions: Platform.OS === 'ios',
});

// create notifcation channel
PushNotification.createChannel(
  {
    channelId: CHANNEL_ID,
    channelName: `CAV`
  }
);

export const initNotification = async () => {
  let userInfo = ''

  PushNotification.getChannels(function (channel_ids) {
    console.log('channel_ids', channel_ids); // ['channel_id_1']
  });

  PushNotification.channelExists(CHANNEL_ID, function (exists) {
    console.log("channel exists", exists); // true/false
  });

  PushNotification.popInitialNotification((notification) => {
    if (notification) {
      userInfo = notification.userInfo
    }
    
    console.log('InitialNotication:', notification)
  });

  const { startupStepCompleted } = startupApi.getState()
  startupStepCompleted('notification', userInfo || {})
}

export const notify = (category, { param, name }) => {
  console.log(`notify ${category} ${param} ${name}`);
  PushNotification.localNotification({
    channelId: CHANNEL_ID,
    title: helper[category].notificationText(name),
    userInfo: { category, param }
  })
}
`

**Comment by Dallas62** [comment]
Hi @matthieugayon 

Your issue is not about the version 6.1.3 or major version.

For Firebase, the library install the `messaging` dependency and I will look to make it optional. Analytics and Google-Services are optional since you made this change:
```js
  requestPermissions: Platform.OS === 'ios',
```

For your issue with the notification:

```js
  /* iOS and Android properties */
  title: "My Notification Title", // (optional)
  message: "My Notification Message", // (required)
```

I suggest you to use `message` property instead of `title`.

Hope this will help you.

Regards,

**Comment by matthieugayon** [comment]
Thank you @Dallas62 for the answer. 

I continued to try out solutions yesterday, but never made it work, I tried the message property too, with no results ( would  using the title property prevents the notification dispatch ? )

Right now my app/build.gradle looks like this

```
dependencies {
    implementation 'com.android.support:multidex:1.0.3'

    implementation project(':react-native-reanimated')
    // implementation project(':react-native-notifications')
    // implementation 'com.google.firebase:firebase-core:16.0.7';
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }

    implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

project.ext.vectoricons = [
    iconFontsDir: '../../app/Fonts',
    iconFontNames: [ '*.ttf' ] 
]

apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

apply plugin: 'com.google.gms.google-services'
```

Do you think one of the reason would be that I don't integrate FCM to my build ? 

Also I'm on RN 0.61.2

**Comment by Sculptor-veD** [comment]
> Thank you @Dallas62 for the answer.
> 
> I continued to try out solutions yesterday, but never made it work, I tried the message property too, with no results ( would using the title property prevents the notification dispatch ? )
> 
> Right now my app/build.gradle looks like this
> 
> ```
> dependencies {
>     implementation 'com.android.support:multidex:1.0.3'
> 
>     implementation project(':react-native-reanimated')
>     // implementation project(':react-native-notifications')
>     // implementation 'com.google.firebase:firebase-core:16.0.7';
>     implementation fileTree(dir: "libs", include: ["*.jar"])
>     implementation "com.facebook.react:react-native:+"  // From node_modules
> 
>     if (enableHermes) {
>         def hermesPath = "../../node_modules/hermes-engine/android/";
>         debugImplementation files(hermesPath + "hermes-debug.aar")
>         releaseImplementation files(hermesPath + "hermes-release.aar")
>     } else {
>         implementation jscFlavor
>     }
> 
>     implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
>     implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
> }
> 
> // Run this once to be able to run the application with BUCK
> // puts all compile dependencies into folder libs for BUCK to use
> task copyDownloadableDepsToLibs(type: Copy) {
>     from configurations.compile
>     into 'libs'
> }
> 
> apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
> 
> project.ext.vectoricons = [
>     iconFontsDir: '../../app/Fonts',
>     iconFontNames: [ '*.ttf' ] 
> ]
> 
> apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
> 
> apply plugin: 'com.google.gms.google-services'
> ```
> 
> Do you think one of the reason would be that I don't integrate FCM to my build ?
> 
> Also I'm on RN 0.61.2

same here, my project doesn't work on V6.x.x , but it works on v4.0.0

**Comment by Dallas62** [comment]
> > Thank you @Dallas62 for the answer.
> 
> > 
> 
> > I continued to try out solutions yesterday, but never made it work, I tried the message property too, with no results ( would using the title property prevents the notification dispatch ? )
> 
> > 
> 
> > Right now my app/build.gradle looks like this
> 
> > 
> 
> > ```
> 
> > dependencies {
> 
> >     implementation 'com.android.support:multidex:1.0.3'
> 
> > 
> 
> >     implementation project(':react-native-reanimated')
> 
> >     // implementation project(':react-native-notifications')
> 
> >     // implementation 'com.google.firebase:firebase-core:16.0.7';
> 
> >     implementation fileTree(dir: "libs", include: ["*.jar"])
> 
> >     implementation "com.facebook.react:react-native:+"  // From node_modules
> 
> > 
> 
> >     if (enableHermes) {
> 
> >         def hermesPath = "../../node_modules/hermes-engine/android/";
> 
> >         debugImplementation files(hermesPath + "hermes-debug.aar")
> 
> >         releaseImplementation files(hermesPath + "hermes-release.aar")
> 
> >     } else {
> 
> >         implementation jscFlavor
> 
> >     }
> 
> > 
> 
> >     implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
> 
> >     implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
> 
> > }
> 
> > 
> 
> > // Run this once to be able to run the application with BUCK
> 
> > // puts all compile dependencies into folder libs for BUCK to use
> 
> > task copyDownloadableDepsToLibs(type: Copy) {
> 
> >     from configurations.compile
> 
> >     into 'libs'
> 
> > }
> 
> > 
> 
> > apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
> 
> > 
> 
> > project.ext.vectoricons = [
> 
> >     iconFontsDir: '../../app/Fonts',
> 
> >     iconFontNames: [ '*.ttf' ] 
> 
> > ]
> 
> > 
> 
> > apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
> 
> > 
> 
> > apply plugin: 'com.google.gms.google-services'
> 
> > ```
> 
> > 
> 
> > Do you think one of the reason would be that I don't integrate FCM to my build ?
> 
> > 
> 
> > Also I'm on RN 0.61.2
> 
> 
> 
> same here, my project doesn't work on V6.x.x , but it works on v4.0.0

Hi @Sculptor-veD 

If this was working in v4 and not v6, it's because you didn't create a channel.

@matthieugayon can you elaborate ? You probably try other solutions but can you list your tests / current code ?

**Comment by matthieugayon** [comment]
@Dallas62 , I'm gonna come up later today with a more thorough report of my code and how I implement the library. In the meantime could you comment on the following points, and tell me if they are absolutely needed to make it work : 

AndroidManifest.xml
```
<meta-data
        android:name="com.dieam.reactnativepushnotification.default_notification_channel_id"
        android:value="my channel id used in fro my created channel"
      />
```
What is this tag used for ? 

app/build.gradle
```
dependencies {
    ...
    implementation 'com.google.firebase:firebase-core:16.0.7';
    ...
}
```
Is implementing firebase mandatory ?

And last point : did you ever make, or heard about local notifications working with v6.1.x on RN < 0.63 ?

**Comment by Dallas62** [comment]
> @Dallas62 , I'm gonna come up later today with a more thorough report of my code and how I implement the library. In the meantime could you comment on the following points, and tell me if they are absolutely needed to make it work :
> 
> AndroidManifest.xml
> 
> ```
> <meta-data
>         android:name="com.dieam.reactnativepushnotification.default_notification_channel_id"
>         android:value="my channel id used in fro my created channel"
>       />
> ```
> 


If your define the `channelId` every time you trigger the local notification, this entry is optional:
```xml
<meta-data
        android:name="com.dieam.reactnativepushnotification.default_notification_channel_id"
        android:value="my channel id used in fro my created channel"
      />
```
It's used to set a default channelId to notifications if none are provided through `localNotification` (channel must exist).


> What is this tag used for ?
> 
> app/build.gradle
> 
> ```
> dependencies {
>     ...
>     implementation 'com.google.firebase:firebase-core:16.0.7';
>     ...
> }
> ```
> 
> Is implementing firebase mandatory ?

https://github.com/zo0r/react-native-push-notification/blob/master/example/android/app/build.gradle#L190

This dependency is not used in the exemple project.
Currently, the messaging dependency is used to provide Java classes when you build the library.

> 
> And last point : did you ever make, or heard about local notifications working with v6.1.x on RN < 0.63 ?

With 60k downloads / week, I would have heard about this specific case "library v6 not working on RN< 0.63" 😉

**Comment by matthieugayon** [comment]
Ok guys, I created a new app RN 0.63, re installed all my dependencies and my code base, and it's working ...

**Comment by Dallas62** [comment]
Do you configure proguard in your previous project ?

**Comment by matthieugayon** [comment]
No
