### ISSUE TITLE
small icon not working only default icon only show up

### ISSUE THREAD

**Issue by mohamed-ikram** [zo0r/react-native-push-notification#1728]
# Bug
small icon not showing up in my app I followed  https://developer.android.com/studio/write/image-asset-studio#access this step and created a small icon

## Environment info

`react-native info` output:System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz
    Memory: 1.56 GB / 7.86 GB
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.0
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs ARM EABI v7a, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_251
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.14.0
    react-native: ^0.63.2 => 0.63.3

Library version: ^6.1.2

## Steps To Reproduce

1.my app notification icon does not show up in the notification tray only the default icon shows up

### notification tray
![Screenshot_2020-10-29-23-06-45-715_com miui home (2)](https://user-images.githubusercontent.com/62332326/97611504-4866f900-1a3c-11eb-98e4-dc331475cba7.jpg)

### Expanded notification
![Screenshot_2020-10-29-23-04-35-950_com vakilsearch crm](https://user-images.githubusercontent.com/62332326/97611523-4dc44380-1a3c-11eb-8656-50b10cdb213b.jpg)

Describe what you expected to happen:

1.i needed to show a small icon

## Reproducible sample code
```
let localNotification={
                /* Android Only Properties */
                channelId:'default-channel-id',
                ticker: 'My Notification Ticker', // (optional)
                autoCancel: true, // (optional) default: true
                largeIcon: "", // (optional) default: "ic_launcher". Use "" for no large icon.
                smallIcon: 'ic_notify', // (optional) default: "ic_notification" with fallback for "ic_launcher"
                bigText: 'My big text that will be shown when notification is expanded', // (optional) default: "message" prop
                color: 'black', // (optional) default: system default
                vibrate: true, // (optional) default: true
                vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
                ongoing: false, // (optional) set whether this is an "ongoing" notification
                invokeApp: true, // (optional) This enable click on actions to bring back the application to foreground or stay in background, default: true
                bigPictureUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRIaEdVDh-oBUNiTpAevO-bPen1sf6v_ldDpOk5fvxzrWrk6HMqjYgcXDDH_lpPGru41o8_nNP0&usqp=CAc',
                // largeIconUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRIaEdVDh-oBUNiTpAevO-bPen1sf6v_ldDpOk5fvxzrWrk6HMqjYgcXDDH_lpPGru41o8_nNP0&usqp=CAc',
               
                /* iOS only properties */
                alertAction: 'view', // (optional) default: view
                category: '', // (optional) default: empty string
                /* iOS and Android properties */
                id: 1, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
                title: 'Local Notification', // (optional)
                message: 'My Notification Message', // (required)
                userInfo: {}, // (optional) default: {} (using null throws a JSON value '<null>' error)
                // playSound: !!soundName, // (optional) default: true
                // soundName: soundName ? soundName : 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
                number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
                // localNotification:true
              }
            PushNotification.localNotification(localNotification);
```

**Comment by Dallas62** [comment]
Hi,

Can you provide more context ?
Such as:
- Where did you put the icon ?
- What's the name of the icon ? 'ic_notify' I guess.

Regards,

**Comment by mohamed-ikram** [comment]
hello @Dallas62 I have included the icon in the android manifest file like this 

`<meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_notify" />
        <meta-data
            android:name="com.applozic.mobicomkit.notification.smallIcon"
            android:resource="@drawable/ic_notify" />`

is there any way to add small icon for push notification

**Comment by Dallas62** [comment]
You should put the icon into the mipmap folder

**Comment by mohamed-ikram** [comment]
Okay I'll check it

**Comment by mohamed-ikram** [comment]
in android manifest file should i add like this
`<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_notify" /> <meta-data android:name="com.applozic.mobicomkit.notification.smallIcon" android:resource="@mipmap/ic_notify" />
`
or need to add  any other configuration for this package

**Comment by Dallas62** [comment]
Is your icon in the right folder ?
(Not the Manifest)

**Comment by mohamed-ikram** [comment]
@Dallas62 thanks for your support yes i have added icon to mipmap folder
![Screenshot (33)](https://user-images.githubusercontent.com/62332326/97677466-4b9fca80-1ab8-11eb-8471-10ffdabbdf7c.png)

**Comment by mohamed-ikram** [comment]
i have created fresh project and added ic_notify.png in the mipmap folder and my android manifest file is like this 

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.example">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

        
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="false"/>
        
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@color/white"/> 
        
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
    </application>

</manifest>`




and local notification is 

````
 localNotif(soundName) {
    this.lastId++;
    PushNotification.localNotification({
      /* Android Only Properties */
      channelId: soundName ? 'sound-channel-id' : 'default-channel-id',
      ticker: 'My Notification Ticker', // (optional)
      autoCancel: true, // (optional) default: true
      largeIcon: 'ic_notify', // (optional) default: "ic_launcher"
      smallIcon: 'ic_notify', // (optional) default: "ic_notification" with fallback for "ic_launcher"
      bigText: 'My big text that will be shown when notification is expanded', // (optional) default: "message" prop
      subText: 'This is a subText', // (optional) default: none
      color: 'red', // (optional) default: system default
      vibrate: true, // (optional) default: true
      vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
      tag: 'some_tag', // (optional) add tag to message
      group: 'group', // (optional) add group to message
      groupSummary: false, // (optional) set this notification to be the group summary for a group of notifications, default: false
      ongoing: false, // (optional) set whether this is an "ongoing" notification
      actions: ['Yes', 'No'], // (Android only) See the doc for notification actions to know more
      invokeApp: true, // (optional) This enable click on actions to bring back the application to foreground or stay in background, default: true
      
      when: null, // (optionnal) Add a timestamp pertaining to the notification (usually the time the event occurred). For apps targeting Build.VERSION_CODES.N and above, this time is not shown anymore by default and must be opted into by using `showWhen`, default: null.
      usesChronometer: false, // (optional) Show the `when` field as a stopwatch. Instead of presenting `when` as a timestamp, the notification will show an automatically updating display of the minutes and seconds since when. Useful when showing an elapsed time (like an ongoing phone call), default: false.
      timeoutAfter: null, // (optional) Specifies a duration in milliseconds after which this notification should be canceled, if it is not already canceled, default: null

      /* iOS only properties */
      alertAction: 'view', // (optional) default: view
      category: '', // (optional) default: empty string
      
      /* iOS and Android properties */
      id: this.lastId, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      title: 'Local Notification', // (optional)
      message: 'My Notification Message', // (required)
      userInfo: { screen: 'home' }, // (optional) default: {} (using null throws a JSON value '<null>' error)
      playSound: !!soundName, // (optional) default: true
      soundName: soundName ? soundName : 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
      number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
    });
  }````

added to res folder
![Screenshot (34)](https://user-images.githubusercontent.com/62332326/97681010-9ec84c00-1abd-11eb-9b15-4c9b7ed73f8c.png)

**Comment by mohamed-ikram** [comment]
@Dallas62 thanks a lot it worked
