### ISSUE TITLE
How to include deeplink to the displayed notifications

### ISSUE THREAD

**Issue by samah2100** [zo0r/react-native-push-notification#173]
I'm using 1.0.7	 version as it support the version I'm using of react native

What I want to do is display a link at the notification message and when the user click on it the application will be open on a certain screen depends on this link (deeplink) How could I do that?

if that is not possible, how could I know if the user click on the notification to open the application?? I'll try then to display the screen defined in received notification object
I read that I could know that if I'm using newer version of react-native-push-notification, but it's important to do that with my current version

**Comment by sungwoncho** [comment]
I noticed you closed this issue. Did you figure out how to open a specific path when a user taps on a notification?

**Comment by samah2100** [comment]
No, I got a work around by sending some variables in notifications and when user tab on the notification I check for those variables and redirect him to the right screen.

however, adding a deeplink to notification body still the better option, I hope someone tell me how to do that

**Comment by im-aditya** [comment]
Anybody knows how to do this ?

**Comment by hsivakum** [comment]
@samah2100 Can you share the workaround please, it might definitely help others 👍
