### ISSUE TITLE
notification.finish(PushNotificationIOS.FetchResult.NoData) app crashed

### ISSUE THREAD

**Issue by treesen** [zo0r/react-native-push-notification#1731]
# Bug

when call notification.finish(PushNotificationIOS.FetchResult.NoData), app crashed
## Environment info
ios

`react-native info` output:

```bash
 // paste it here
```

Library version: "react-native-push-notification": "^6.1.1"

## Steps To Reproduce

 onNotification: function (notification) {
    Event.log("onNotification==> ", notification)
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },
...

Describe what you expected to happen:

1.app not crash

**Comment by Dallas62** [comment]
Not able to reproduce and too few information.

**Comment by BennSandoval** [comment]
Just add NotificationCenter.framework, works for me.

<img width="844" alt="Screen Shot 2020-11-15 at 11 10 44" src="https://user-images.githubusercontent.com/1797588/99191616-5b174880-2733-11eb-918d-49ccad2fa3c6.png">
