### ISSUE TITLE
Specify/determine notification receiver

### ISSUE THREAD

**Issue by DimitarDevP** [zo0r/react-native-push-notification#1732]
How do i control the receiver of these notifications?

I have a `redux store` which contains the data about all my users. Is there a way to read this data with Java? 

Also, is there a way to modify the notification body so that it includes a `UserId` field, then use something like `notification.getUserId()` and only create the notification if it is equal to the `currentUserID` which is obtained from the `redux store`?

**Comment by Dallas62** [comment]
Hi,

I don't understand why you want to read redux store in Java.

You can add data in your notification to get all information you need.

Regards

**Comment by DimitarDevP** [comment]
I posted this in the wrong repo. I have 10 of these react native notifications solutions opened up. My mistake, i am sorry :/.
