### ISSUE TITLE
Prevent foreground notification on iOS

### ISSUE THREAD

**Issue by ericluong** [zo0r/react-native-push-notification#1737]
# Question

I noticed remote notifications sent to an iOS device are displayed on foreground.
Is there a way to prevent that? I just want local notifications to work on foreground.

Is there an equivalent to this Android setting on iOS?
```
<meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                  android:value="false"/>

```

react: 16.8.3
 react-native: 0.59.10
iOS version: 14.1
react-native-push-notification: 6.1.2

Thank you for your help!

**Comment by Dallas62** [comment]
Hi, you will probably find more help on this subject on this repository:
https://github.com/react-native-push-notification-ios/push-notification-ios/
Regards,

**Comment by ericluong** [comment]
Thank you @Dallas62!
I found my answer in this [issue](https://github.com/react-native-push-notification-ios/push-notification-ios/issues/63).
