### ISSUE TITLE
localNotificationSchedule id string or number?

### ISSUE THREAD

**Issue by didrikkvanvik** [zo0r/react-native-push-notification#1741]
# localNotificationSchedule id string or number?

I see in the documentation that the type of `id` in `localNotificationSchedule` is `number`. 
Cancelling a scheduled notification using `cancelLocalNotifications` requires a `id` as a `string`.

That seems contradictory to create a notification using `id` as a `number`, while cancelling the notification requires `id` as a `string`. Shouldn't it just be a `string`?

**Comment by Dallas62** [comment]
Hi,

The value of the id must be a valid unique 32 bit integer specified as string.
If needed, the id might be cast if the type is wrong.

Regards.

**Comment by Frans-L** [comment]
Should the example code be then?

```diff
PushNotification.localNotification({
  ...
  /* iOS and Android properties */
-  id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
+  id: "0", // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
  ...
});
```

**Comment by Dallas62** [comment]
Hi @Frans-L 
The type is cast in the correct type in the library,
Regards,

**Comment by Frans-L** [comment]
Thanks, @Dallas62 for the quick reply!

Should we rewrite the comment to be "//... specified as string or number. The number will be cast string?

It would avoid a lot of confusion :)

**Comment by theneekz** [comment]
either string or number will work as long as it is a 32-bit **signed** int (-2147483648 to 2147483647)
