### ISSUE TITLE
 If I clear the alarm in the background from the status bar, the alarm is not visible until I enter the app.

### ISSUE THREAD

**Issue by daheeahn** [zo0r/react-native-push-notification#1744]
# Bug

** Android **
I made local scheduled notification (repeat every 4 seconds)
But When I remove notification in status bar, notification doesn't show until opening app.

How can I keep the notification popping up even if I clear the notification from the status bar?
I am making a function that keeps ringing even if the alarm is cleared from the status bar until the app enters a specific screen.

## Environment info

Library version: 5.1.1

## Steps To Reproduce
First, show alarm. 
Second, I swipe notification to remove it in status bar.
Then, notification doesn't show.
Third, When I enter the app, notification shows again.

![image](https://user-images.githubusercontent.com/38369729/98774238-f192f380-242d-11eb-8cd7-42e21dccae2d.png)
![image](https://user-images.githubusercontent.com/38369729/98774261-ffe10f80-242d-11eb-89cb-70e69c04ee75.png)
![image](https://user-images.githubusercontent.com/38369729/98774281-0cfdfe80-242e-11eb-9971-e30f00ea2c62.png)
![image](https://user-images.githubusercontent.com/38369729/98774297-14bda300-242e-11eb-82f6-6bf8f21df919.png)

## Reproducible sample code

`
   const scheduleObj: PushNotificationScheduleObject = {
          channelId: 'my channel',
          id: '1',
          date: new Date(),
          autoCancel: false,
          ongoing: false,
          priority: 'max',
          visibility: 'public',
          importance: 'max',
          allowWhileIdle: true,
          title: 'title',
          message: 'message',
          playSound: true,
          soundName: 'default',
          vibrate: true,
          vibration: 2000,
          repeatType: 'time',
          repeatTime: 4000,
          ignoreInForeground: false,
      };
      PushNotification.localNotificationSchedule(scheduleObj);
`

My AndroidManifest.xml

`

      
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                  android:value="true"/>
      
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                  android:resource="@color/white"/>

      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED" />
              <action android:name="android.intent.action.QUICKBOOT_POWERON" />
              <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
          </intent-filter>
      </receiver>

      <service
          android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
          android:exported="false" >
          <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
      </service>
`

Every entering the app, I run this code.

`
    PushNotification.channelExists(pushUtil.channelId, exists => {
      if (!exists) {
        PushNotification.createChannel(
          {
            channelId: pushUtil.channelId, // (required)
            channelName: pushUtil.channelName, // (required)
            channelDescription: pushUtil.channelDescription, // (optional) default: undefined.
            importance: 5, // 5 is max // (optional) default: 4. Int value of the Android notification importance
            soundName: 'no_sound',
          },
          created => llog(`🤹🏻‍♂️ createChannel returned '${created}'`), // (optional) callback returns whether the channel was created, false means it already existed.
        );
      }
    });
`

**Comment by Dallas62** [comment]
Hi,
I'm not sure this is a "bug", but probably how the notification center handle this case.

Or, it's possible you got this issue:
https://github.com/zo0r/react-native-push-notification/issues/1574
But there is no solution to this issue 🙃
