### ISSUE TITLE
the token for device always null in release version and works correctly  in debug mode 

### ISSUE THREAD

**Issue by hagar0459** [zo0r/react-native-push-notification#1746]
i have tried the push notification on android in debug android mode and works correct but in release mode the token always return as null ?
also the permission not appear either in debug mode or release mode

**Comment by Dallas62** [comment]
Hi,

Take a look to this:

https://stackoverflow.com/questions/59852062/fcm-token-not-generating-in-samsung-devices-in-release-version-of-app

Regards
