### ISSUE TITLE
[iOS] userInteraction not behaving as expected

### ISSUE THREAD

**Issue by igrayson** [zo0r/react-native-push-notification#175]
Hi team,

We're going by this definition:

``` js
  userInteraction: false, // BOOLEAN: If the notification was opened by the user from the notification area or not
```

We notice this behavior:
1. When app is running, and in background (`AppState.currentState === 'background'`) ...
   a. ... and app receives a remote PN, `userInteraction === false` (good)
   b. ... and the user taps/swipes on a PN from the lock screen, `userInteraction === false` (**unexpected**)
2. When the app is running, and in the foreground (`AppState.currentState !== 'background'`) ...
   a. ... and app receives a remote push notification, `userInteraction === true` (**unexpected**)
   b. ... and the user taps/swipes a PN from the notification tray (drags open from status bar), `userInteraction === false` (**unexpected**)

Looking at [the implementation](https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L159), it's not clear how this could be expected to work, unless react-native were to provide some `data.foreground`, which it's not.

**Comment by Arkanine** [comment]
Hi there,
I have the same behavior.

**Comment by npomfret** [comment]
Are you seeing this on Android or iOS, or both?

**Comment by igrayson** [comment]
This is iOS only.

**Comment by npomfret** [comment]
Do we know what the iOS behaviour is?  Ideally the Android implementation should mimic it.

**Comment by drukas** [comment]
Any progress on this one?

**Comment by wintlu** [comment]
struggling with this issue

**Comment by AlimovSV** [comment]
+1 waiting the solution

**Comment by eddnav** [comment]
+1 same issue, has anyone found a workaround?

**Comment by jqn** [comment]
+1000 same issue

**Comment by samuelcardoso** [comment]
+1 same issue

**Comment by jmeiss** [comment]
+1 still the same issue

**Comment by tonygriv** [comment]
+1

**Comment by adamawang** [comment]
+1

**Comment by ngandhy** [comment]
+1

**Comment by damvanhuong** [comment]
+1 waiting the solution

**Comment by damvanhuong** [comment]
it's worked for me 
https://stackoverflow.com/questions/34337117/detect-whether-react-native-ios-app-was-opened-via-push-notification
