### ISSUE TITLE
the "ongoing" notification is automatic removed when I close (kill) the app

### ISSUE THREAD

**Issue by elburu** [zo0r/react-native-push-notification#1752]
When I fire a  Ongoing notification and later I close (kill) the app, the notification disappears from notification center

How do I keep this notification alive even when the app is closed?

**Comment by Dallas62** [comment]
Hi,

I suggest you to look at StackOverflow for this question:

https://stackoverflow.com/questions/38941594/keep-an-ongoing-notification-even-when-the-app-is-closed

Regards

**Comment by elburu** [comment]
thanks @Dallas62 , I think I was mixing concepts here because I am newbie in Android:
in one hand there is a Notification and the other hand there is a Sticky Service and they need to work together in order to keep my notification alive

I will asume this package not handle this kind of situation.
