### ISSUE TITLE
the finish method are breaking the app on iOS

### ISSUE THREAD

**Issue by douglasdc** [zo0r/react-native-push-notification#1753]
# Bug
In iOS 14.x the usage of the method finish: `finish(PushNotificationIOS.FetchResult.NoData);` is breaking the APP when local notification is triggered.

Tho thing that solve the issue is not to use the finish method inside configure onNotification, or patching the push-notification-ios and removing the handler of notifications, the notification keeps working, this seems to be something incompatible between the two packages.

## Environment info

`react-native info` output:

```bash
 System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 55.07 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.18.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/Projects/Mobile-App/node_modules/.bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-26 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_241 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.1.1

## Steps To Reproduce

Configure the handler of PushNotificationIOS when local notification is received.

```javascript
{
    onNotification: notification => {
       notification.finish(PushNotificationIOS.FetchResult.NoData);
    }
}
```

**Comment by Dallas62** [comment]
Hi,

No error message provided.

Regards.

**Comment by douglasdc** [comment]
> Hi,
> 
> No error message provided.
> 
> Regards.

Because the error does not occur in this package, but because of it, internal error on push-notification-ios.
I have updated with the print error.

**Comment by tomto1** [comment]
Hi @Dallas62  bug is still crashing app on notification. I tried with push-notification-ios 1.8.0.

**Comment by Dallas62** [comment]
Hi @tomto1 
Without a reproducible example or a error message, I can't help you.
Regards,
