### ISSUE TITLE
Misleading documentation for local notification on Android

### ISSUE THREAD

**Issue by felginep** [zo0r/react-native-push-notification#1754]
The documentation is misleading about how to post local notifications.

- First the function `PushNotification.localNotification ` does not exists for Android. It is named `PushNotification.presentLocalNotification` on Android devices (cf [line](https://github.com/zo0r/react-native-push-notification/blob/f724c3684e4681f1e2a132ada75831a858caeedc/component/index.android.js#L47)).

Posting a local notification results in a conditional function like so:
```
if (Platform.OS === 'ios') {
  PushNotification.localNotification({
    title: title,
    message: body,
  })
} else if (Platform.OS === 'android') {
  PushNotification.presentLocalNotification({
    title:title,
    message: body,
  })
}
```

- Second the `channelId` is **not** mandatory as it will default to the firebase one (cf [line](https://github.com/zo0r/react-native-push-notification/blob/f724c3684e4681f1e2a132ada75831a858caeedc/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L274)). 

The documentation states the channel will be created if the channel does not exists but it's not the case. My recommandation is to avoid passing the channelId parameter, and use the default one.

**Comment by Dallas62** [comment]
Hi @felginep 

Refer to this file:
https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L148
`PushNotification.localNotification` is the right name of the local notification method.

> Second the channelId is not mandatory as it will default to the firebase one (cf line).

This is only true **IF** you are using Firebase.
https://github.com/zo0r/react-native-push-notification#channel-management-android

```
For local notifications, the same kind of option is available:
you can use:
  <meta-data
      android:name="com.dieam.reactnativepushnotification.default_notification_channel_id"
      android:value="@string/default_notification_channel_id" />
If not defined, fallback to the Firebase value defined in the AndroidManifest:
  <meta-data
      android:name="com.google.firebase.messaging.default_notification_channel_id"
      android:value="..." />
If not defined, fallback to the default Firebase channel id fcm_fallback_notification_channel
```

Even if the channelId is set as `fcm_fallback_notification_channel`, if this channel is not created (not created by default) notification will not work. The aim of the **mandatory** `channelId` is to force developers to create at least one channel. If they don't, this fall back to an issue in github "Notification doesn't work...".

Regards,
