### ISSUE TITLE
onNotification triggers immediately without tapping on notification

### ISSUE THREAD

**Issue by Sheleya** [zo0r/react-native-push-notification#1755]
If the app is active, when I receive the notification _onNotification_ method triggers immediately without tapping on notification. 
How can I change this behaviour?
Desired behaviour is next: if app is active and I get the notification, it will not trigger _onNotification_ method until I tap on it.
Please help!

**Comment by Dallas62** [comment]
Hi,

This issue has already been answered.

Regards.

**Comment by Sheleya** [comment]
> Hi,
> 
> This issue has already been answered.
> 
> Regards.

Please send me the link to the following request
