### ISSUE TITLE
onNotification is not called after opening the app with a background notification

### ISSUE THREAD

**Issue by MFrat** [zo0r/react-native-push-notification#1756]
# Question

Everything works just fine when push arrives with app in background, quit and foreground state. But, when push arrives with app in quit state and app opened by notification, all of the next pushes interaction does not trigger onNotificaion.

Flow Example:
1 - Push arrives with app in quit state
2 - User clicks on notification
3 - App opens and onNotification is called
4 - Another push arrives with app in foreground state
5 - User clicks on notification
6 - onNotification is not called.

**Comment by Dallas62** [comment]
Hi @MFrat 
This is the expected behaviour since the initial notification is the one that start the App.
Since it's not possible to get another notification on iOS, the same process is applied on Android to avoid different behaviour.
Regards

**Comment by MFrat** [comment]
Thanks for the explanation, @Dallas62!
Makes total sense.
