### ISSUE TITLE
IOS 14 Firebase remote Notification Content Not Get In Application 

### ISSUE THREAD

**Issue by vickypathak123** [zo0r/react-native-push-notification#1759]
Hello,

I'm working on the One React native project in IOS 13 or below when a notification comes then after clicking on the notification in the application Notification Message properly Come but when I test the application in IOS 14 then this notification receiver not Work or not Getting any notification message inside Application. Please Guide me What is wrong with my code.

Please check my Code mention Below:-

PushNotification.configure({
         
          onNotification: function (notification) {
            console.log('LOCAL NOTIFICATION ==>', notification.message);
            AsyncStorage.setItem('NotificaionQuote', notification.message.body);
            AsyncStorage.setItem(
              'NotificaionAuther',
              notification.message.title,
            );

            notification.finish(PushNotificationIOS.FetchResult.NoData);
          },
          onAction: function (notification) {
            console.log('ACTION:', notification.action);
            console.log('NOTIFICATION:', notification);

        
          },
          popInitialNotification: true,
          requestPermissions: true,
        });

**Comment by Dallas62** [comment]
Hi,

For iOS please look at:

https://github.com/react-native-community/react-native-push-notification-ios

Regards,
