### ISSUE TITLE
Using PushNotification.configure without firebase 

### ISSUE THREAD

**Issue by Fedour57** [zo0r/react-native-push-notification#1763]
# Question

Hello, I would like to call a function when the use click to a notification
I have looked in the other issues to answer this question. And I have seen many responses to this subject.

I need to use PushNotification.configure as well as onNotification: function

The problem and when I use this function I get the following error:

`Default FirebaseApp is not initialized in this process`

I only use local notifications so I don't have to install firebase.
Is there a way to call a function when the user clicks on a notification without using firebase?

Thank you

**Comment by Dallas62** [comment]
Hi,

Already answered and in the readme on `.configure()`.

Regards,

**Comment by Fedour57** [comment]
Thanks for the answer

I have read the readme and if you talk about to not use `.configure` inside a component it's already the case. I use `.configure` inside index.js but same error

I've don't find any correct answer for this question. Do you have the ref please ?

Regards,

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification#usage

```js

  /**
   * (optional) default: true
   * - Specified if permissions (ios) and token (android and ios) will requested or not,
   * - if not, you must call PushNotificationsHandler.requestPermissions() later
   * - if you are not using remote notification or do not have Firebase installed, use this:
   *     requestPermissions: Platform.OS === 'ios'
   */
  requestPermissions: true,

```

**Comment by Fedour57** [comment]
It still does not answer my question. I can't `.configure ()` because of the error `Default FirebaseApp is not initialized in this process`

I'm on Android

I call the whole `.configure()` in `index.js` like this:

```
PushNotification.configure({
  // (optional) Called when Token is generated (iOS and Android)
  onRegister: function (token) {
    console.log("TOKEN:", token);
  },

  // (required) Called when a remote is received or opened, or local notification is opened
  onNotification: function (notification) {
    console.log("NOTIFICATION:", notification);

    // process the notification

    // (required) Called when a remote is received or opened, or local notification is opened
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },

  // (optional) Called when Registered Action is pressed and invokeApp is false, if true onNotification will be called (Android)
  onAction: function (notification) {
    console.log("ACTION:", notification.action);
    console.log("NOTIFICATION:", notification);

    // process the action
  },

  // (optional) Called when the user fails to register for remote notifications. Typically occurs when APNS is having issues, or the device is a simulator. (iOS)
  onRegistrationError: function(err) {
    console.error(err.message, err);
  },

  // IOS ONLY (optional): default: all - Permissions to register.
  permissions: {
    alert: true,
    badge: true,
    sound: true,
  },

  // Should the initial notification be popped automatically
  // default: true
  popInitialNotification: true,

  /**
   * (optional) default: true
   * - Specified if permissions (ios) and token (android and ios) will requested or not,
   * - if not, you must call PushNotificationsHandler.requestPermissions() later
   * - if you are not using remote notification or do not have Firebase installed, use this:
   *     requestPermissions: Platform.OS === 'ios'
   */
  requestPermissions: true,
});
```

But got error  `Default FirebaseApp is not initialized in this process`

**Comment by Dallas62** [comment]
Did you at least read what I wrote ?

Can't be more precise:

```js
   * - if you are not using remote notification or do not have Firebase installed, use this:
   *     requestPermissions: Platform.OS === 'ios'
```

**Comment by Fedour57** [comment]
Ok it's working. Didn't see the answer in the commented code.

Thanks you

**Comment by alinavaie** [comment]
I'm using  requestPermissions: Platform.OS === 'ios', but still giving the same error

**Comment by mBarlescu** [comment]
if we dont request permissions to android user with this workaround. how are they supposed to receive any notifications?

**Comment by DDarkLexs** [comment]
hi, I have the same issue here!
`console.log(1+1)`
