### ISSUE TITLE
Notification not coming after coming online from offline 

### ISSUE THREAD

**Issue by ShaileshPrajapati-BTC** [zo0r/react-native-push-notification#1766]
# Bug

## Environment info
"react-native": "0.62.2 
"react-native-push-notification": "^6.1.2"
OS: Android

`react-native info` output:

```bash
System:
OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
Memory: 461.93 MB / 7.65 GB
Shell: 5.0.3 - /bin/bash
Binaries:
Node: 12.5.0 - /usr/local/bin/node
Yarn: 1.21.1 - /usr/bin/yarn
npm: 6.9.0 - /usr/local/bin/npm
Watchman: Not Found
SDKs:
Android SDK: Not Found
IDEs:
Android Studio: Not Found
Languages:
Java: 11.0.7 - /usr/bin/javac
Python: 2.7.17 - /usr/bin/python
npmPackages:
@react-native-community/cli: Not Found
react: 16.11.0 => 16.11.0
react-native: 0.62.2 => 0.62.2
npmGlobalPackages:
*react-native*: Not Found
```

Library version: 6.1.2

## Steps To Reproduce

1. Sending server notification from rails using below payload
```
{
      notification: {
        title: "titl",
        body: "body",
        sound: 'default',
        vibrate_timings: ['200', '300'],
        notification_priority: 2,
        default_light_settings: true
      },
      data: {collapse_key: SecureRandom.uuid}
    }
```

Expected to happen:

1. When coming online from offline all delivered notification should come instead of the last notification
2. When a user is connected to the internet all notifications working fine.

## Reproducible  steps
1 Disconnect your device from the internet
2 Send more than 5 notification from server or firebase console
3 Connect internet again you will receive an only single notification which is last one

**Comment by Dallas62** [comment]
Hi,

Thanks for this report. Unfortunately, This library is not responsible of Firebase issues.

Regards,

**Comment by ShaileshPrajapati-BTC** [comment]
@Dallas62  Is there any other way to handle this issue. that will help us a lot to fix this 

Thank you

**Comment by Dallas62** [comment]
Hi @ShaileshPrajapati-BTC,

Again, this library will not handle Firebase issue.
Refer to Firebase documentation or StackOverflow.

Regards
