### ISSUE TITLE
Sound in Silent-mode?

### ISSUE THREAD

**Issue by dancixx** [zo0r/react-native-push-notification#1767]
Hi guys.

Is there any way to play notficiation sound when the phones are in silent mode, but use a headset, headphone etc. So if i listening music and get the notification sound to. Now, just get the popup window?

Thanks for helping me.

**Comment by Dallas62** [comment]
Hi @dancixx,

This has been already answered, please use the issue history.

Regards.

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification/issues/1546#issuecomment-662400770
