### ISSUE TITLE
Notification not fired in localNotificationSchedule

### ISSUE THREAD

**Issue by anituetvnu** [zo0r/react-native-push-notification#1768]
# Question
**I follow the instruction to install react native push notification to my app.
here it the index.js**
`import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

// import PushNotificationIOS from '@react-native-community/push-notification-ios';
import PushNotification from 'react-native-push-notification';

// Must be outside of any component LifeCycle (such as `componentDidMount`).
PushNotification.configure({
  // (optional) Called when Token is generated (iOS and Android)
  onRegister: function (token) {
    console.log('TOKEN:', token);
  },

  //   // (required) Called when a remote is received or opened, or local notification is opened
  //   onNotification: function (notification) {
  //     console.log('NOTIFICATION:', notification);

  //     // process the notification

  //     // (required) Called when a remote is received or opened, or local notification is opened
  //     notification.finish(PushNotificationIOS.FetchResult.NoData);
  //   },

  // (optional) Called when Registered Action is pressed and invokeApp is false, if true onNotification will be called (Android)
  onAction: function (notification) {
    console.log('ACTION:', notification.action);
    console.log('NOTIFICATION:', notification);

    // process the action
  },

  // (optional) Called when the user fails to register for remote notifications. Typically occurs when APNS is having issues, or the device is a simulator. (iOS)
  onRegistrationError: function (err) {
    console.error(err.message, err);
  },
});

PushNotification.localNotificationSchedule({
  //... You can use all the options from localNotifications
  message: 'My Notification Message', // (required)
  date: new Date(Date.now() + 20 * 1000), // in 20 secs
  allowWhileIdle: false, // (optional) set notification to work while on doze, default: false
});

AppRegistry.registerComponent(appName, () => App);
`
**here it the log**

`[Fri Dec 04 2020 17:06:39.148]  BUNDLE  ./index.js

[Fri Dec 04 2020 17:06:44.938]  WARN     Require cycle: node_modules\rn-fetch-blob\index.js -> node_modules\rn-fetch-blob\polyfill\index.js -> node_modules\rn-fetch-blob\polyfill\Blob.js -> node_modules\rn-fetch-blob\index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Fri Dec 04 2020 17:06:44.949]  WARN     Require cycle: node_modules\rn-fetch-blob\index.js -> node_modules\rn-fetch-blob\polyfill\index.js -> node_modules\rn-fetch-blob\polyfill\XMLHttpRequest.js -> node_modules\rn-fetch-blob\index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Fri Dec 04 2020 17:06:44.950]  WARN     Require cycle: node_modules\rn-fetch-blob\index.js -> node_modules\rn-fetch-blob\polyfill\index.js -> node_modules\rn-fetch-blob\polyfill\Fetch.js -> node_modules\rn-fetch-blob\index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
[Fri Dec 04 2020 17:06:44.951]  LOG      Running "chat_app" with {"rootTag":181}
[Fri Dec 04 2020 17:06:44.956]  LOG      TOKEN: {"os": "android", "token": "fycpNOH6S9SVEBRa1B6jIH:APA91bHZBriD39PXgRrxriIY3cbwR3zqr4lQ3-EklyYSUBcPgDgTC4Rb4hBbstDKVAxJP3niGMWiNtKDAeuuggkK_QWm2RgaUfQabnSZoafubEteeRNOMFr-EGlIJxStaMVmVYbXGZ2o"}`

I use RN 0.63.3
my device is mi9T
many thanks.

**Comment by Dallas62** [comment]
Hi,

https://github.com/zo0r/react-native-push-notification#channel-management-android

Regards
