### ISSUE TITLE
Navigate from onNotification when app is killed

### ISSUE THREAD

**Issue by SteveTro** [zo0r/react-native-push-notification#1769]
Hello @ all,

i'm currently using the package to display local notifications which i receive via Firebase messaging.
When a notification arrives in Foreground or background i'll update my context api and display a local message.
To use that i expanded the example NotifService to pass the context.

```
export default class NotifService {
  constructor(onRegister, onNotification, context) {
    this.context = context;
    this.createDefaultChannels();

    NotificationHandler.attachRegister(onRegister);
    NotificationHandler.attachNotification(onNotification);
    NotificationHandler.attachContext(context); //Added the context to the NotificationHandler

    [...]
  }
```

```
class NotificationHandler {
   onNotification(notification) {
    if (notification.userInteraction) {
      if (typeof this._onNotification === 'function') {
        this._onNotification(notification.data);
      }
    } else {
      if (this._context) {
        this._context.addNewNotification(notification.data); //update my context with the notification data
      }
    }
  }
```

When someone clicks on the notification _onNotification is called on the Context of my HomeScreen and the user is moved to the certain screen.

The NotifService is initialized in my HomeScreen inside App.js after the context is set

```
static contextType = Context;
  componentDidMount() {
    this.notif = new NotifService(
      this.onRegister.bind(this),
      this.onNotif.bind(this),
      this.context,
    );
    [...]
 }

```

My problem is, that when the app is killed i just can receive the message via the backgroundMessageHandler of firebase in my index.js.

But at this point i dont have a context.
I can initialize a new NotifService without context and the Notification will be shown, but if the notification is pressed context is undefined (because there was no context on initialize)
Because of that the onNotif callback is not called and the user is not navigated to the certain screen.

Someone has an idea how i could archive that?

**Comment by Dallas62** [comment]
Hi,

https://github.com/zo0r/react-native-push-notification#usage

**DO NOT USE `.configure()` INSIDE A COMPONENT, EVEN `App`**

> If you do, notification handlers will not fire, because they are not loaded. Instead, use `.configure()` in the app's first file, usually `index.js`.

Look into issues history for more answers.

Regards.

**Comment by SteveTro** [comment]
> Hi,
> 
> https://github.com/zo0r/react-native-push-notification#usage
> 
> **DO NOT USE `.configure()` INSIDE A COMPONENT, EVEN `App`**
> 
> > If you do, notification handlers will not fire, because they are not loaded. Instead, use `.configure()` in the app's first file, usually `index.js`.
> 
> Look into issues history for more answers.
> 
> Regards.

Like i said, i used the example application where .configure() is outside of Component.
But my question is HOW i should use it in index.js to navigate, because context and navigator are null at this point

**Comment by Dallas62** [comment]
You can store the value you need inside a "global" variable and use it when you need it.

**Comment by SteveTro** [comment]
> You can store the value you need inside a "global" variable and use it when you need it.

Do you have a example? Currently i tried it with the ContextAPI and Asynchronous Storage but the main problem is that the navigation ref is not available in index.js

**Comment by Dallas62** [comment]
```js
class NotificationHandler {
   onNotification(notification) {
    if (notification.userInteraction) {
      if (typeof this._onNotification === 'function') {
        this._onNotification(notification.data);
      }
      else {
        this._notif = notification.data;
      }
    } else {
      if (this._context) {
        this._context.addNewNotification(notification.data); //update my context with the notification data
      }
    }
  }

  get notif() {
     return this._notif;
  }
}

```

Then use `NotificationHandler.notif` when you need data.

This question has already been answered in issues, please use issue history.

**Comment by SteveTro** [comment]
> ```js
> class NotificationHandler {
>    onNotification(notification) {
>     if (notification.userInteraction) {
>       if (typeof this._onNotification === 'function') {
>         this._onNotification(notification.data);
>       }
>       else {
>         this._notif = notification.data;
>       }
>     } else {
>       if (this._context) {
>         this._context.addNewNotification(notification.data); //update my context with the notification data
>       }
>     }
>   }
> 
>   get notif() {
>      return this._notif;
>   }
> }
> ```
> 
> Then use `NotificationHandler.notif` when you need data.
> 
> This question has already been answered in issues, please use issue history.

There is no "this" if the App is killed, because there is no context. Thats what i say.
And i searched in history, back till 2016 there is nothing.

But you don't even try to understand the problem, so you can delete the post anyway.

**Comment by Dallas62** [comment]
> But you don't even try to understand the problem, so you can delete the post anyway.

What I understand is that you are trying to access data provided by a component or component API.

Move your logic outside of the component lifecycle or store the data you need and read it when you need it.

There is many way to do it, but you don't provide enough information based on your code to help you.

```js

let notif_data;

class NotificationHandler {
   onNotification(notification) {
    if (notification.userInteraction) {
      if (typeof this._onNotification === 'function') {
        this._onNotification(notification.data);
      }
    } else {
      if (this._context) {
        this._context.addNewNotification(notification.data); //update my context with the notification data
      }
      else {
        notif_data = notification.data; // Read it later if needed.
      }
    }
  }
}
```

**OR**

```js
const context = new MyContext(); // Load your context here.

class NotificationHandler {
   onNotification(notification) {
    if (notification.userInteraction) {
      if (typeof this._onNotification === 'function') {
        this._onNotification(notification.data);
      }
    } else {
        context.addNewNotification(notification.data); //update my context with the notification data
    }
  }
}
```

**Comment by SteveTro** [comment]
> > But you don't even try to understand the problem, so you can delete the post anyway.
> 
> What I understand is that you are trying to access data provided by a component or component API.
> 
> Move your logic outside of the component lifecycle or store the data you need and read it when you need it.
> 
> There is many way to do it, but you don't provide enough information based on your code to help you.
> 
> ```js
> let notif_data;
> 
> class NotificationHandler {
>    onNotification(notification) {
>     if (notification.userInteraction) {
>       if (typeof this._onNotification === 'function') {
>         this._onNotification(notification.data);
>       }
>     } else {
>       if (this._context) {
>         this._context.addNewNotification(notification.data); //update my context with the notification data
>       }
>       else {
>         notif_data = notification.data; // Read it later if needed.
>       }
>     }
>   }
> }
> ```
> 
> **OR**
> 
> ```js
> const context = new MyContext(); // Load your context here.
> 
> class NotificationHandler {
>    onNotification(notification) {
>     if (notification.userInteraction) {
>       if (typeof this._onNotification === 'function') {
>         this._onNotification(notification.data);
>       }
>     } else {
>         context.addNewNotification(notification.data); //update my context with the notification data
>     }
>   }
> }
> ```

What i try is to archive is to navigate to a certain screen, when a push notification is opend from "killed" state.

My configure() and onNotification is, as you and the example described, outside a component.
As the notification is received in killed app state, there is no context in the notification handler.
Because of this reason i can't call "this", because the context is undefined in killed state.

I already tried few ways, but i cant archive it.

**Comment by nero2009** [comment]
@SteveTro Did you find a solution for this?

**Comment by jailsonpaca** [comment]
I solve with these functions:

----------**for not-foreground notifications**-----------
1)put deep-linking in the navigator:

```
linkingConfig= {
    config: {
        screens: {
          mainStack: {
            screens: {
              homeNavigator: {
                screens: {
                  openCard: "open-card/:id",
                  demoComponents: "demoComponents",
                },
              },
              welcome: "welcome",
            },
          },
        },
      },
      prefixes: ["hippoz://", "hippoz://hippoz/"],
}

<RootNavigator
              ref={navigationRef}
              initialState={initialNavigationState}
              onStateChange={onNavigationStateChange}
              linking={{ ...linkingConfig, }}
/>```

2)put openURL in index.js

```onNotification(notification) {
    console.log("NOTIFICATION:", notification)
    if (notification) {
      const toScreen = notification?.data.toScreen
      Linking.openURL(String(toScreen))
    }
}```

------------**for foreground notifications**------------
1)put effect for foreground notifications:
```
const [alreadyOpened, setAlreadyOpened] = useState<string>("")

useEffect(() => {
    verifyLastNotification(setAlreadyOpened, alreadyOpened)
    return () => {}
  }, [ alreadyOpened])

export const verifyLastNotification = (
  setAlreadyOpened: (v: string) => void,
  alreadyOpened: string,
) =>
  PushNotification.popInitialNotification((notification) => {
    if (notification) { 
      const toScreen = notification?.data.toScreen 
      console.log("Notification clicked: ", toScreen)
      if (!notification?.foreground && toScreen !== alreadyOpened) {
        Linking.openURL(String(toScreen))
        setAlreadyOpened(toScreen)
      }
    }
  })

```

**Comment by skkim-pixel-monster** [comment]
@jailsonpaca 
Linking.openUrl does not work in put deep-linking in the navigator. Could you please share detailed code or settings?
