### ISSUE TITLE
Default location for the small notification icon is in drawables and not in mipmap

### ISSUE THREAD

**Issue by vikeri** [zo0r/react-native-push-notification#177]
When looking for `smallIcon`  the library looks for the `mipmap` type but by default Android Studio puts Notification icons in `drawables` for me. Changing `mipmap` straight to `drawable` in the code would be a breaking change so a suggestion would be to either expose the second parameter in `res.getIdentifier()` to the RN component or to check both places for icons.

**Comment by vikeri** [comment]
I'll provide a PR if you agree with this.

**Comment by JonesN7** [comment]
I agree, this should be changed.

**Comment by JonesN7** [comment]
+1 for this. As far as I know, all image assets except Launcher icons should be located in drawable.

**Comment by dccarmo** [comment]
Just spent 3 hours not knowing why my custom icon wasn't showing up. Thanks for raising the issue.

**Comment by Shannanigans** [comment]
Also ran into this issue. Could not figure out why the ic_launcher default was being used.

**Comment by sa77** [comment]
ran into this issue .. is there any hacky way to fix this until the solution is merged to the release?
