### ISSUE TITLE
Request permission after login

### ISSUE THREAD

**Issue by swlaunch** [zo0r/react-native-push-notification#1771]
# Question

Currently the app asks for notification permission when it starts, but I want this to be asked after user log-in to the app. (This is how the apps like instagram work)
But the problem is that in usage section of Readme, it says `DO NOT USE .configure() INSIDE A COMPONENT, EVEN App`

Is there solution for this?

**Comment by Dallas62** [comment]
Hi @swlaunch,

I suggest you to read the documentation for `.configure()` and `requestPermissions` options.

Best regards,
