### ISSUE TITLE
Is README and /Example contradictive?

### ISSUE THREAD

**Issue by ePoromaa** [zo0r/react-native-push-notification#1772]
# Question

Undet the section **USAGE** the readme states: 
> DO NOT USE .configure() INSIDE A COMPONENT, EVEN App

However, the implementation in the `/example` folder initializes the `NotifService` within the `App` component. Is this not contradicting what the docs say? 

Please excuse me if I'm missing something. My question stems from that I'm having issues with the `onRegister` method not firing and my implementation is based on the one in the `/example` folder with the main difference being that I use functional components and declare navigation in the App functional component using react-navigation.

**Comment by Dallas62** [comment]
Hi @ePoromaa,

In this exemple, `.configure()` is not call inside `App`. The `NotificationService` attach some methods to the `NotificationHandler` to allow you to access `onNotification` or `onRegister`. But `.configure()` is call before the `App` is mount, which allow background notifications.

Regards,=.

**Comment by ePoromaa** [comment]
Ah, of course. My bad.
