### ISSUE TITLE
Failed to post notification on channel "channel_id"

### ISSUE THREAD

**Issue by MR-Shegby** [zo0r/react-native-push-notification#1774]
trying to 

PushNotification.localNotification({
    channelId: 'channel_id',
    ...
  })

and it failed.

in AndroidManifest.xml I put:
<meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="channel_id" /><meta-data android:name="com.dieam.reactnativepushnotification.default_notification_channel_id" android:value="channel_id" />

and it still failed. what do I have to do?

----
build on emulator Pixel_3a_API_30_x86
"react-native-push-notification": "6.1.3"

**Comment by sapna179** [comment]
This error occurred.... as I had added two listener files... I comment one... It worked for me

**Comment by RockinGarg** [comment]
how did this got fixed?
