### ISSUE TITLE
Deleting delivered notifications with PushNotification.cancelLocalNotifications not working

### ISSUE THREAD

**Issue by pdooo** [zo0r/react-native-push-notification#1776]
The only thing that kind of helped me was [this](https://github.com/zo0r/react-native-push-notification/issues/1296#issuecomment-593557272). For some reason after adding `repeatType` in `PushNotification.localNotification` I could remove already delivered notifications sitting in my notifications center. Problem is that I don't want to use `repeatType` because I just want to remove my regular local notifications. 

Here version working with repeatType:

```
PushNotification.localNotification({
        id: id,
        actions: ['Copy', 'Remove'],
        repeatType: 'week',
        invokeApp: false,
        autoCancel: false,
        largeIcon: "ic_launcher",
        smallIcon: "ic_notification",
        channelId: "localNoti",
        title: title, 
        message: url, 
        ongoing: IsOnGoing, 
});
```
```
PushNotification.configure({
    onNotification: function (notification) {
      var link = notification.message;
      PushNotification.cancelLocalNotifications({ id: notification.id; });
    },
    onAction: function (notification) {
      if (notification.action == 'Remove'){
        PushNotification.cancelLocalNotifications({ id: notiID });
        console.log(notiID)
      }
  },
  popInitialNotification: true,
  requestPermissions: Platform.OS === 'ios',
  
})
```

**As soon as I remove `repeatType: 'week'` from `PushNotification.localNotification` it stops working**

**Comment by whenmoon** [comment]
Yes, I am having exact same problem.

**Comment by Dallas62** [comment]
Hi,
You are using the wrong method, `PushNotification.localNotification` doesn't aim to schedule notification. `PushNotification.cancelLocalNotifications` aims to remove scheduled notifications, you can use `PushNotification.clearNotification`.
Regards.

**Comment by joaosouz4dev** [comment]
Hello, @Dallas62, thank u.
How to use this method `PushNotification.clearNotification` ?

**Comment by Dallas62** [comment]
You can use:
https://github.com/zo0r/react-native-push-notification#5-removedeliverednotifications
