### ISSUE TITLE
Convert notification_id type from Integer to Long

### ISSUE THREAD

**Issue by shakawy** [zo0r/react-native-push-notification#1778]
# Feature Request

## Why it is needed
I'm trying to assign `notification_id` a unique value `Date().getTime()` but it always greater than INT length

**Comment by Dallas62** [comment]
Hi @shakawy

I understand the issue with int32, unfortunately, this is not a library restriction:

https://developer.android.com/reference/android/app/PendingIntent#getBroadcast(android.content.Context,%20int,%20android.content.Intent,%20int)

`requestCode` must be a int.

Regards,

**Comment by shakawy** [comment]
Thank you sir
