### ISSUE TITLE
Option to not set the large icon in Android

### ISSUE THREAD

**Issue by vikeri** [zo0r/react-native-push-notification#178]
As defined here:
https://developer.android.com/guide/topics/ui/notifiers/notifications.html#CreateNotification

The `largeIcon` option is not required and hence should not have a forced default.

Will provide PR if this is agreed upon.

**Comment by vikeri** [comment]
Saw that this was already fixed here:
https://github.com/zo0r/react-native-push-notification/pull/40

**Comment by vikeri** [comment]
Why was this closed? Is it fixed in master?

**Comment by npomfret** [comment]
Oops, sorry - thought it was a duplicate

**Comment by Jacse** [comment]
`largeIcon` should definitely not have a forced default. Would love to see this fixed and/or #40 merged.

**Comment by diegocouto** [comment]
If you need a hand to get #40 merged, I'd be glad to help. 😉

**Comment by TaraSinghDanu** [comment]
How to acheive this?
