### ISSUE TITLE
Notification don't pops up in foreground for the first time after that it do

### ISSUE THREAD

**Issue by MuhammadTayyabDev** [zo0r/react-native-push-notification#1781]
# Bug

## Environment info
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz
    Memory: 3.19 GB / 7.92 GB
  Binaries:
    Node: 10.22.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2

Library version: 6.1.3

## Steps To Reproduce

1. You can reproduce it just by installing the latest version(6.1.3) and try to receive the first notification by staying in foreground you will not see a popup (on notification will fire). 
2. Close/minimize the app send a notification to app you will see it.
3. Launch the app again stay in foreground send a notification to app now you will be able to see the pop up in foreground also.

*only at the very first time if you try to receive notifications popup in foreground you wouldn't but soon after after getting a notification in background or killed state you will start seeing popup in foreground too.

Describe what you expected to happen:

1. It should be showing the pop up in foreground state also as it was doing in previous versions.

**Comment by Dallas62** [comment]
Please take a look at channel management part.
Regards.

**Comment by Muhamman78** [comment]
same issue.

**Comment by Muhamman78** [comment]
downgrading works, can you please specify which type of change is required in channel management as I am using default channel.

**Comment by Dallas62** [comment]
Hi @Muhamman78 

There is no default channel, you must create a channel according to the documentation,

Regards,

**Comment by michaelVictoriaDev** [comment]
same issue, already add this in config

foreground appear on the first 

![image](https://user-images.githubusercontent.com/44763288/117399102-55582e00-af32-11eb-8deb-15a1b89061a5.png)

**Comment by potatoengineer** [comment]
@michaelVictoriaDev @Muhamman78 @MuhammadTayyabDev any luck with this issue? I am having the same issue

**Comment by Muhamman78** [comment]
> @michaelVictoriaDev @Muhamman78 @MuhammadTayyabDev any luck with this issue? I am having the same issue

Downgrade the package to version 4.0.0. It worked for me.

**Comment by Dallas62** [comment]
You just have to create a channel, stop downgrading, follow changelog when you upgrade...

**Comment by potatoengineer** [comment]
@Dallas62 I created a channel for localNotification and it's working now but how do I create a channel for remote notifications in the background?

**localNotification**
```
  PushNotification.createChannel(
    {
      channelId: "default_channel_id",
      channelName: "default_channel_id",
    },
  );
  PushNotification.localNotification({
     channelId: "default_channel_id",
     title: notification.title,
     message: notification.message,
  ```
  **Remote notification** not working
  ```
    <meta-data
      android:name="com.google.firebase.messaging.default_notification_channel_id"
      android:value="@string/default_notification_channel_id" />
  ```

**Comment by Dallas62** [comment]
Did you defined the value of `@string/default_notification_channel_id` ?
Also you can target a channel id when using Firebase API or SDK Admin

**Comment by potatoengineer** [comment]
No, I left it as that. So if I want to use the same channel as localNotification do, will this work?
```
  <meta-data
    android:name="com.google.firebase.messaging.default_notification_channel_id"
    android:value="default_channel_id" />
```

**Comment by Dallas62** [comment]
Yes
