### ISSUE TITLE
Can update notification in real time ? (like a stopwatch)

### ISSUE THREAD

**Issue by GaylordP** [zo0r/react-native-push-notification#1782]
Hello and thank you for your library :)

I use [react-native-countdown-circle-timer](https://github.com/vydimitrov/react-countdown-circle-timer/tree/master/packages/mobile#readme) on my application and I want to pair it with react-native-push-notification.

Thanks to your documentation, I arrived at something interesting which displays the remaining time in a notification. This time is updated **in real time** : **perfect**.

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/kfWWo.jpg

But when I quit the application (which is in the background), **the timer stops in the notification**. When I return to the application, the timer (in the circle) went well.

Can you give me any advice for the timer to update in real time in the notification (like a stopwatch) ?

Here is the code that I have simplified as much as possible. thank you so much. :)

    import React from 'react'
    import {
      Animated,
      StyleSheet,
    } from 'react-native'
    import { CountdownCircleTimer } from 'react-native-countdown-circle-timer'
    import PushNotification from 'react-native-push-notification'

    PushNotification.createChannel(
      {
        channelId: "default-channel-id", // (required)
        channelName: `Default channel`, // (required)
        channelDescription: "A default channel", // (optional) default: undefined.
        soundName: "default", // (optional) See `soundName` parameter of `localNotification` function
        importance: 4, // (optional) default: 4. Int value of the Android notification importance
        vibrate: false, // (optional) default: true. Creates the default vibration patten if true.
      },
      (created) => console.log(`createChannel 'default-channel-id' returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
    )

    const pushNotification = (text) => {
      PushNotification.localNotification({
        /* Android Only Properties */
        channelId: 'default-channel-id',
        largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
        smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
        color: 'green',
        vibrate: false,
        ongoing: true,
        invokeApp: true, // (optional) This enable click on actions to bring back the application to foreground or stay in background, default: true

        showWhen: true,
        when: new Date().getTime(),

        /* iOS and Android properties */
        id: 1,
        title: 'Training', // (optional)
        message: 'Rest time : ' + text,
        playSound: false,
        number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero),

        allowWhileIdle: true,
      });
    }

    const Timer = () => {
      return (
        <CountdownCircleTimer
          isPlaying
          duration={10}
          colors="green"
          size={120}
          trailColor="#fff"
        >
          {({ remainingTime }) => {
            pushNotification(remainingTime)

            return <Animated.Text
              style={[
                styles.timer,
              ]}
            >
              {remainingTime}
            </Animated.Text>
          }}
        </CountdownCircleTimer>
      )
    }

    const styles = StyleSheet.create({
      timer: {
        color: '#fff',
        fontSize: 32,
      },
    })

    export default Timer

**Comment by Dallas62** [comment]
Hi,

You can trigger a new notification with the same ID.
Actually, iOS is not working well, you can test with the version on `dev` branch which should solve the issue.

Regards

**Comment by GaylordP** [comment]
Thank you for your reply :)

I put the same ID (# 1) and the notification is changed in real time. However, the problem is that updating it stops when the application is in the background (but the timer continues)

**Comment by Dallas62** [comment]
Are you sure the time continue?
It can be refresh as soon as the app come back to foreground.

If the notification is not trigger in background, two options:
- channel is not created/defined
- the method which trigger the notification is not called

**Comment by GaylordP** [comment]
Hello,

Thanks for your help. After searching, the counter continues, but no action is possible in the background

If anyone has the same problem, I must have used this library to run a timer in the background with notification. I don't know yet if this is the ideal method : https://github.com/ocetnik/react-native-background-timer
