### ISSUE TITLE
How to get FCM token for iOS.

### ISSUE THREAD

**Issue by Anuj-logiciel** [zo0r/react-native-push-notification#1784]
`onRegister` event in iOS is returning APNS token. I want to use FCM token. How can I get FCM token for iOS??

**Comment by Dallas62** [comment]
Hi,

Please use search feature in issues.
Already answered.

Regards

**Comment by Anuj-logiciel** [comment]
It would be really thankful if you would have also mentioned link of the the issue you are referring to search.
Thanks.

**Comment by Dallas62** [comment]
There is just "firebase token" to search, but well: #1670

**Comment by irsyaadbp** [comment]
> There is just "firebase token" to search, but well: #1670

means if I use firebase for android and ios, I can't use this library and have to replace it with something else?
example RNFirebase/messaging

**Comment by Dallas62** [comment]
You can replace or use both together.
Depending on your needs.
Also the Firebase API allow you to import APN token, somewhere in firebase documentation.

**Comment by irsyaadbp** [comment]
> You can replace or use both together.
> Depending on your needs.
> Also the Firebase API allow you to import APN token, somewhere in firebase documentation.

if i use both of them together,
is this the scheme?
I used **@react-native-firebase/messaging** to **get the token**,
and I trigger a **local notification** from **react-native-push-notification** when **@react-native-firebase/messaging**:
1. **onMessage** for foreground listeners
2. **setBackgroundMessageHandler** for background listeners
isn't right?

**Comment by Dallas62** [comment]
You can use this library for channel management and local notification, and rnfirebase for the other features.

**Comment by irsyaadbp** [comment]
> You can use this library for channel management and local notification, and rnfirebase for the other features.

okay, i'll try it

 thank you :D
