### ISSUE TITLE
Custom sound doesn't updated even after recreate channel

### ISSUE THREAD

**Issue by luizgallas** [zo0r/react-native-push-notification#1785]
Env:
    Node: 14.10.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
    Android SDK: 30
    react-native: ^0.63.2 => 0.63.2 
    this lib: 6.1.3

Custom sound doesn't update even deleting current channel and recreating with the new sound. I am keeping the same name for the channel

**Comment by Dallas62** [comment]
Hi @luizgallas
Please refer to the Readme and Android Documentation.
> In the notifications options, you must provide a channel id with channelId: "your-channel-id", if the channel doesn't exist the notification might not e triggered. Once the channel is created, the channel cannot be update. Make sure your channelId is different if you change these options. If you have created a channel in another way, it will apply options of the channel.

Regards,

**Comment by luizgallas** [comment]
I read it, for every notification I created one channel because they have different sounds, the problem is that when I change the sound, delete and recreate the channel the sound still the same.

**Comment by Dallas62** [comment]
So once created, can't be updated...
Even after deletion, please refer to Android Documentation about channels.
Regards,

**Comment by luizgallas** [comment]
Thanks!
