### ISSUE TITLE
Question: Is it possible to produce a silent / hidden notification?

### ISSUE THREAD

**Issue by uripre** [zo0r/react-native-push-notification#1786]
My purpose is to produce a silent & hidden notification, to only trigger onNotification or some other JS function, and not show any indication to the user (a follow up notification might show in some scenarios).

It seems to be supported in Android and iOS:
https://stackoverflow.com/questions/36555653/push-silent-notification-through-gcm-to-android-ios

Is there any such option in `react-native-push-notification`? I see `message` is a required property of the notification passed into `localNotificationSchedule`.

**Comment by Dallas62** [comment]
Hi @uripre,

This kind of notification is not available with local notification.
You can try to look for remote "data-only" notifications or background tasks but there is some restrictions with battery saver.

Regards

**Comment by uripre** [comment]
Got you, thanks for answering @Dallas62 !!
