### ISSUE TITLE
stringified userInfo and actions

### ISSUE THREAD

**Issue by avlonder** [zo0r/react-native-push-notification#1794]
# Question

Is there a reason for the JSON.stringify() applied to userInfo and actions?
I don't think this was the case in earlier versions of the library...?
Anyway, it's kind of confusing, so maybe this could be removed (if possible) or added to the documentation (if not).

**Comment by Dallas62** [comment]
Hi @avlonder 

Actually this is used to store "complex" structures. If this can be made in another way, feel free to send a PR or a link to the react-native module documentation with information 😉

Regards
