### ISSUE TITLE
onNotification Not working when app is killed at foreground

### ISSUE THREAD

**Issue by selvaTecky** [zo0r/react-native-push-notification#1795]
Hi,

The package is really useful for creating push notifications. I have few doubts and questions hope you'll help me on this.

1. onNotifications are executing in foreground without an issue but, if I send push notifications when the app is in killed state that time it is not even executing but onRegister executing without fail. May I know why its functioning like this? 

2. Is it required to pass "data" object in remote push notification? if I don't have any options to pass data what will happen?

**Comment by Dallas62** [comment]
Hi @selvaTecky,

Since this library is not responsible of the Firebase protocol, you can refer to this documentation:

https://firebase.google.com/docs/cloud-messaging/concept-options

Basically:
In killed state, `onNotification` is called only if it's a data-only notification.
Or if the user press the notification.

Regards,

**Comment by selvaTecky** [comment]
Hi @Dallas62 ,

I am sending payload without data only. But while clicking on notifications, onNotification is not getting executed. I have debugged, onRegister only getting executed there I won't get notification payload. Can you give some idea on this?

**Comment by Dallas62** [comment]
Hi,

Your library is too old, but take a look in issues for:
- SplashScreen

Or move `.configure()` outside any component.

Regards,

**Comment by selvaTecky** [comment]
Hi @Dallas62 ,

As per your advice I have updated the package. Currently I am using react-native-push-notification: ^3.3.0. Now onNotification is getting executed but the push notification is not popping up in notification trey. do you have any idea?
 I have shared my payload, kindly take a look.

{
  "foreground": true,
  "userInteraction": false,
  "id": "xxxxxx",
  "data": {
    "name": "Testing Messgae",
    "Title": "Testing",
    "pr": "",
  }
}

**Comment by Dallas62** [comment]
Hi @selvaTecky 

As mentioned before, please refer to:
https://firebase.google.com/docs/cloud-messaging/concept-options#notifications

Regards,

**Comment by selvaTecky** [comment]
Hi @Dallas62 ,

I am totally confused thats why I am asking your support on this. I am using third party cloud messaging. from that I will get payload list that only I can't able to change that payload format. Earlier in 3.0.1 I am getting notification popup but now the notification pop up is not coming. I have shared my Push notification configuration in manifest file. Am I missed anything.

RN Version: 59.9
Push notification Current Version: 3.3.0

      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
              android:value="test-channel"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                  android:value="test-channel-desc"/>
                  
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="false"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                  android:resource="@android:color/white"/>

      






      
          
          
          
              
          
       
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED" />
              <action android:name="android.intent.action.QUICKBOOT_POWERON" />
              <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
          </intent-filter>
      </receiver>

      


          

          

          <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

**Comment by Dallas62** [comment]
You can take a look to this issue: https://github.com/zo0r/react-native-push-notification/issues/1452

**Comment by shafqatbarireporteq** [comment]
any Solution? Please share
