### ISSUE TITLE
onNotification callback not being called on ios at all unless notification is pressed

### ISSUE THREAD

**Issue by jrdn91** [zo0r/react-native-push-notification#1796]
# Question

It doesn't seem like the `onNotification` handler is being called in my app at all whether the app is in the foreground or background unless I press the notification itself.

Previously I used the package around version 3 and the `onNotification` handler would be called if the app was in the foreground or background and I could look at that `foreground` boolean property to determine how to handle the notification.

Has this changed? I'm using PubNub to deliver notifications and would like when notifications come in for a new personal message (DM) coming in to the app to be able to handle showing a new message in my app using some extra data being sent through PubNub but because the `onNotification` handler never gets called unless the user taps the notification the app basically never hears there was a new notification and won't do anything.

I have followed the exact setup guides for this library, the ios library and used the notification service example in the examples here for how to get the config and registration. I can share the code I'm using but it's basically the same as the example setup.

**Comment by Dallas62** [comment]
Hi @jrdn91 

Please look in issues, already answered few hours ago.

Regards,
