### ISSUE TITLE
local push notification between two hours

### ISSUE THREAD

**Issue by volkandogan** [zo0r/react-native-push-notification#1799]
# Question

Hello friend,

I want to use local schedule push notification and succesfully implement it. but i cant find only send notificaitons between two hours such as 14:00 and 16:00. How i make this ? my example code below.
 PushNotification.localNotification({
        id: '1605612934',
        title: "Notification title",
        message: "Notification message",
        repeatType: 'time',
        repeatTime: 3000, // 3 seconds
        fireDate: Date.now();
      });

**Comment by Dallas62** [comment]
Hi @volkandogan 

It's not possible to achieve it like this. You must setup one notification per repetition of the notifications.

For exemple:
- schedule one notification at 14
- schedule another one at 16


Regards

Do not abuse notifications, Android might have a limit on the number of notifications (around 30).

**Comment by volkandogan** [comment]
Hi @Dallas62 
Thank you for answer, but i try with that code and it repeat every 3 seconds :) it works, but actually i want to only repeat between 14.00 and 16.00.

**Comment by Dallas62** [comment]
Hi,

As answered before, it's not possible to achieve this (between two hours). 

Regards,
