### ISSUE TITLE
Android group notification is no working?

### ISSUE THREAD

**Issue by sunnyyants** [zo0r/react-native-push-notification#180]
I am trying to stack the notification using the 'group' field and it seems like I keep receiving separate push notifications instead of seeing like '3 new messages' on our device's push notification center. My package version is 2.0.2 and we are using RN 0.32.

I was trying to use postman to send out an push notification and which is `https://gcm-http.googleapis.com/gcm/send`
And my request body looks like this:
`{ "data": {
    "message":"Hello world!",
    "title": "You got an message!",
    "largeIcon": "app_icon",
    "smallIcon": "pn_logo",
    "group": "group",
    "vibrate": false
  },
  "to" : "${Device token}"
}`

Was there any one faced this problem before? Thank you for any ideas!

**Comment by npomfret** [comment]
Stacking notification isn't supported yet.

**Comment by tsvetann** [comment]
That would be nice add on

**Comment by JonoH** [comment]
What is the "group" field for then @npomfret? This feature is a necessity for Android at least

**Comment by l1br3** [comment]
@JonoH You can set an id so they will be replaced
