### ISSUE TITLE
Clarification on cancelLocalNotifications

### ISSUE THREAD

**Issue by gaillota** [zo0r/react-native-push-notification#1802]
# Question

<img width="866" alt="Screenshot 2021-01-02 at 01 11 44" src="https://user-images.githubusercontent.com/6444106/103446336-d4dda400-4c97-11eb-9737-be93d2a9a043.png">

Could someone please clarify the last `iOS` statement for me ? I'm not sure that's correct English tbh... Thank you in advance

Regards,
Antoine

**Comment by Dallas62** [comment]
Hi @gaillota 

`.cancelLocalNotifications()` use values of `userInfo` (refer to `localNotification` options).
If `userInfo` or `userInfo.id` is not defined, the default value of `userInfo` is `{ id: /* ID of the notification */ }`.

this allow you to use `.cancelLocalNotification({ id: /* ID of the notification */ })`

Feel free to make a PR to improve the documentation 😉 

Regards,
