### ISSUE TITLE
google-service.json in different mode

### ISSUE THREAD

**Issue by irsyaadbp** [zo0r/react-native-push-notification#1811]
# Question
How to use different google-service.json in mode debug in release
i use react-native-config to handle environment

**Comment by Dallas62** [comment]
Hi @irsyaadbp 

This library is not responsible of Firebase configuration, you should find information on StackOverflow, or in your favorite search Engine:
https://blog.bam.tech/developer-news/setup-firebase-on-ios-android-with-multiple-environments

Regards,
