### ISSUE TITLE
How to check if the user already allowed the push notification permission?

### ISSUE THREAD

**Issue by rodrigowpl** [zo0r/react-native-push-notification#1812]
# Question

How to check if the user already allowed the push notification permission?

For example, if I would like to do something like this:

```
const allowed = await PushNotification.alreadyAllowedPermission() // true/false

if (allowed) // do something
```

**Comment by rodrigowpl** [comment]
actually just check and we have this:
```
  PushNotification.checkPermissions((permissions) => {
        permissions.authorizationStatus // 1 = true, 0 = false
      });
```

**Comment by CptFabulouso** [comment]
That's not true, after disabling the notifications in app settings I received `authorizationStatus = 1`. Before that the `authorizationStatus` was 2. What that value means? Can we have some enum mapped to these values?

Note that I was using react-native-firebase before and the notifications permission was already granted by that lib when I received the `2` value after migrating.

**Comment by SeanArmstrong** [comment]
For reference @CptFabulouso - https://developer.apple.com/documentation/usernotifications/unauthorizationstatus

Also documented here - https://github.com/react-native-push-notification/ios#checkpermissions

**Comment by eyale** [comment]
I've found  this values in my JS bundle:
```
UNAuthorizationStatusNotDetermined:0,
UNAuthorizationStatusDenied:1,
UNAuthorizationStatusAuthorized:2,
UNAuthorizationStatusProvisional:3
```
So converted those values into simple object:
```
    const iOSPushNotificationsStatusTypes = {
      notDetermined: 0,
      denied: 1,
      authorized: 2,
      statusProvisional: 3
    }
```
