### ISSUE TITLE
onNotification doesn't work second time when clicking on notification from killed mode 

### ISSUE THREAD

**Issue by Sheleya** [zo0r/react-native-push-notification#1814]
# Bug

I have scheduled two local notifications one after another immediately. App is killed. Waiting when notification center will have two notifications. Pressing on first one will open the app and the onNotification method will trigger (OKAY), but staying in the app after opening, clicking on second notification in the foreground will not trigger the onNotification. 
.configure set in index.js file.
Android-only bug.

## Environment info
react-native: 0.63.3
react-native-push-notification: 6.1.3

## Steps To Reproduce

1. Schedule two notifications one after another
2. Kill the app
3. Click on the first notification
4. Staying in the app click on the second notification

Describe what you expected to happen:
Both onNotification methods should trigger.
But triggers only first.

## Reproducible sample code

```
  PushNotification.configure({
    onRegister: function (token) {},
    onNotification: function (notification) {
      handleNotification(notification);
      notification.finish(PushNotificationIOS.FetchResult.NoData);
    },
    onAction: function (notification) {},
    onRegistrationError: function (err) {
      console.error(err.message, err);
    },
    permissions: {
      alert: true,
      badge: true,
      sound: true,
    },
    popInitialNotification: true,
    requestPermissions: Platform.OS === 'ios',
  });
```

**Comment by Dallas62** [comment]
Hi @Sheleya 
It's the same behaviour as iOS, and it's the expected behaviour. The initial notification is the one that start the application, not the second one.
Regards,

**Comment by Sheleya** [comment]
> Hi @Sheleya
> It's the same behaviour as iOS, and it's the expected behaviour. The initial notification is the one that start the application, not the second one.
> Regards,

No. 
Pressing on second one should also be handled by onNotification. The first notification starts the app and has additional logic handled by onNotification, and pressing the second notification should also be handled by onNotification, but it's not.

**Comment by Dallas62** [comment]
Unable to reproduce, please check the exemple project or issue history, this is probably documented.

**Comment by Sheleya** [comment]
> Unable to reproduce, please check the exemple project or issue history, this is probably documented.

The starting point should be two local notifications in notification center and closed app.
Pressing on first notification should open the app and onNotification method should be triggered, then you should press on second notification in the foreground and the onNotification method should be triggered second time.

Have you reproduced in this way?

**Comment by Dallas62** [comment]
Yes, please take a look to the exemple project.

**Comment by SazzadIp** [comment]
Please check this answer...
https://github.com/zo0r/react-native-push-notification/issues/1501#issuecomment-791312506
