### ISSUE TITLE
App crashs when receives a remote Notification

### ISSUE THREAD

**Issue by alexpxmort** [zo0r/react-native-push-notification#1818]
# Bug

## Environment info

`react-native info` output:
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
      Memory: 1.03 GB / 7.79 GB
    Binaries:
      Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223

```bash
 // paste it here
```

Library version: 3.2.0

## Steps To Reproduce

1.Start the application with react-native app with npx react-native run-android
2.And When the onNotification method is callded the app crashs and stop to working and I got this error message
java.lang.RuntimeException: Unable to instantiate service com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService: java.lang.ClassNotFoundException: Didn't find class "com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
...

Describe what you expected to happen:

1.The App keeps working and not crashes anymore
2.

## Reproducible sample code

AndroidManifest.xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.pontue">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description" android:value="Notificações da Pontue"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name" android:value="Pontue"/>
      <meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="rn-push-notification-channel-id" />
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color" android:resource="@android:color/white"/>

      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
        <intent-filter>
          <action android:name="android.intent.action.BOOT_COMPLETED" />
        </intent-filter>
      </receiver>
      <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>

      <service
        android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
        android:exported="false" >
        <intent-filter>
            <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
      </service>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
            <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
        </intent-filter>
      </activity>
      
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
##################
build.gradle module android
####################
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        firebaseVersion = "17.6.0"
        googlePlayServicesVersion = "16.1.0"
        firebaseMessagingVersion = "17.6.0"

        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath('com.google.gms:google-services:4.3.3')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url 'https://jitpack.io' }
        maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
    }
}

subprojects { subproject ->
    afterEvaluate {
        if ((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                variantFilter { variant ->
                    def names = variant.flavors*.name
                    if (names.contains("reactNative51") || names.contains("reactNative55")) {
                        setIgnore(true)
                    }
                }
            }
        }
    }
}
########################
build.gradle module app
########################
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = true

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.pontue"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 10
        versionName "1.8.1"
        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57_5" // See note below!
        multiDexEnabled true
    }

    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }

    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            shrinkResources enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
         debug {
          minifyEnabled false
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'androidx.multidex:multidex:2.0.1'

    compile project(':react-native-zendesk-chat')
    implementation project(':react-native-push-notification')
    // compile "com.google.android.gms:play-services-gcm:16.1.0"
    // compile "com.google.firebase:firebase-messaging:17.6.0"
    implementation 'com.google.firebase:firebase-analytics:17.3.0'
    // compile (project(':react-native-push-notification')) {
    //     exclude group: "com.google.android.gms", module: "play-services-gcm"
    //     exclude group: "com.google.firebase", module: "firebase-messaging"
    // }
    implementation project(':rn-fetch-blob')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-orientation')
    implementation project(':react-native-keep-awake')
    implementation project(':react-native-video')
    implementation project(':react-native-image-picker')
    implementation project(':@react-native-community_async-storage')
    implementation project(':react-native-vector-icons')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-navigation')
    implementation group: "com.zopim.android", name: "sdk", version: '1.4.8'

}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
######################################
package.json
#######################
{
  "name": "pontue",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "android": "cd ./android && ./gradlew app:assembleDebug && ./gradlew installDebug"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.4.0",
    "axios": "^0.18.1",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-af-video-player": "^0.2.1",
    "react-native-firebase": "^5.5.6",
    "react-native-iap": "^3.3.9",
    "react-native-image-picker": "^0.28.1",
    "react-native-keep-awake": "^4.0.0",
    "react-native-navigation": "^2.27.5",
    "react-native-paper": "^2.15.2",
    "react-native-push-notification": "^3.2.0",
    "react-native-vector-icons": "^6.4.2",
    "react-native-video": "^4.4.1",
    "react-native-zendesk-chat": "^0.3.1",
    "rn-fetch-blob": "^0.10.16"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/runtime": "^7.4.4",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "jetifier": "^1.6.4",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-native-debugger": "^1.1.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
##############
PushNotification code
##################
import PushNotification from 'react-native-push-notification';

import {
	PushNotificationIOS
} from 'react-native';

import {
	getNotificacao,
	setNotificacao,
	removeNotificacao,
	getToken
} from './LocalStorage';

import api from './Api';

const sendData = async (token) => {
	// await removeNotificacao();

	let notificacao = await getNotificacao();
	const apiToken = await getToken();

	//erro de notificacao com token errado para ios - adicionado firebase
	if(token.os === 'ios') notificacao = null
	
	// old user - that had the app before adding push
	if (apiToken && !notificacao) {
		try {

			api.defaults.headers.common['Authorization'] = 'Bearer ' + apiToken

			const notificacao = await api.post('/notificacao/logado', {
				os: token.os,
				token: token.token,
			});

			await setNotificacao(notificacao.data.data.token)	
		} catch (err) {
			console.log(err)
		}
	} else if (!notificacao) {
		try {
			const notificacao = await api.post('/notificacao', {
				os: token.os,
				token: token.token,
			});

			await setNotificacao(notificacao.data.data.token)
		} catch (err) {
			console.log(err)
		}
	}
};

const configurePush = () => {
	
	PushNotification.configure({

		onRegister: async (token) => {
			sendData(token)
		},

		// foreground: false, // BOOLEAN: If the notification was received in foreground or not
		// userInteraction: false, // BOOLEAN: If the notification was opened by the user from the notification area or not
		// message: 'My Notification Message', // STRING: The notification message
		// data: {}, // OBJECT: The push data
		onNotification: async (notification) => {

			// process the notification
			// required on iOS only
			await api.post('/notificacao/debug', {
				notification
			});

			notification.finish(PushNotificationIOS.FetchResult.NoData);
		},

		senderID: "950802847974",

		permissions: {
			alert: true,
			badge: true,
			sound: true
		},

		popInitialNotification: true,
		requestPermissions: true,

	});

};

export {
	configurePush,
	sendData
};

**Comment by Dallas62** [comment]
Hi @alexpxmort 
Do you build the application in release or debug configuration?
This might be related to proguard.

You are also using an old version of the library (3.2.0).
From the error message, you have a Java class which is not existing, you need to check your compilation setup (linking, proguard, cache, ...).
Regards

**Comment by alexpxmort** [comment]
> Hi @alexpxmort
> Do you build the application in release or debug configuration?
> This might be related to proguard.
> 
> You are also using an old version of the library (3.2.0).
> From the error message, you have a Java class which is not existing, you need to check your compilation setup (linking, proguard, cache, ...).
> Regards

I am building  in debug using npx react-native run-android that runs this script cd ./android && ./gradlew app:assembleDebug && ./gradlew installDebug

**Comment by Dallas62** [comment]
From the error message, you have a Java class which is not existing, you need to check your compilation setup (linking, proguard, cache, ...).
Regards,

**Comment by alexpxmort** [comment]
> From the error message, you have a Java class which is not existing, you need to check your compilation setup (linking, proguard, cache, ...).
> Regards,

Thanks I will do this
