### ISSUE TITLE
RNPushNotification is undefined

### ISSUE THREAD

**Issue by nivek91** [zo0r/react-native-push-notification#182]
Hi everyone, I followed all the steps that the tutorial has and I'm getting this error when executing     PushNotification.configure

I attached the code that I'm using.

![image](https://cloud.githubusercontent.com/assets/4519660/18148338/6103ff9e-6faf-11e6-8442-de7c6269f0e0.png)

[Archive.zip](https://github.com/zo0r/react-native-push-notification/files/448374/Archive.zip)

By the way, if I want to use GCM, where should I put the API KEY?

**Comment by corasan** [comment]
I'm getting the same error :(
Also cant make a build

**Comment by corasan** [comment]
I managed to fix it by running rnpm and doing a build.

**Comment by nivek91** [comment]
@corasan thanks, 
have you tried sending a local notification? my code runs ok, but nothing is received, can you post your code?

Thanks

**Comment by npomfret** [comment]
Check your java code - this can happen if `new ReactNativePushNotificationPackage()` is missing from the list in your _MainApplication.java_

**Comment by mikelambert** [comment]
The "RNPushNotification undefined" error appears to have been resolved, right? Can you please close this?
