### ISSUE TITLE
Add Android 11 Bubbles Support

### ISSUE THREAD

**Issue by MadCoderme** [zo0r/react-native-push-notification#1822]
# Feature Request

## Why it is needed

With the latest update of Android, Android 11, Bubbles are available for all apps. This is a cool feature and should be implemented so we, react-native developers can use it

## Possible implementation

As I am really not expert in Java, I have no idea to add it. But I found an article about it and attached it below

### Code sample
[Implemention of Bubbles in Android 11](https://www.raywenderlich.com/18503960-bubbles-conversations-in-android-11-getting-started)

**Comment by fukemy** [comment]
hi any news now?
