### ISSUE TITLE
Android - debug its ok, but release not

### ISSUE THREAD

**Issue by rodrigogaraujo** [zo0r/react-native-push-notification#1823]
# Bug

  Hello, I have a problem because the notifications always arrive when I am in the simulator, but when I am on the real device it does not arrive. Since the notifications are triggered in the firebase console, can rent help me with this?

## Environment info
"react-native": "0.61.5"

`react-native info` output:

```bash
npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.5.0
```

    "react-native-push-notification": "^6.1.3",

## Steps To Reproduce

Debug mode on simulator its ok
Real device release, not.

**Comment by Dallas62** [comment]
Hi @rodrigogaraujo 

You can check your firebase configuration (if one for dev and one for release).
Check "proguard firebase" on your favorite search engine.

Regards,

**Comment by rodrigogaraujo** [comment]
> Hi @rodrigogaraujo
> 
> You can check your firebase configuration (if one for dev and one for release).
> Check "proguard firebase" on your favorite search engine.
> 
> Regards,

Hey man I love you <3 
Save my life kkkkkkk

Solved:

Android/app/proguard-rules.pro
I add this line at the end:

-keep class com.firebase.** { *; }
