### ISSUE TITLE
local notification is not working

### ISSUE THREAD

**Issue by binhduongquang** [zo0r/react-native-push-notification#1824]
I tried to call this on local android but nothing happen.

![Screen Shot 2021-01-14 at 19 45 10](https://user-images.githubusercontent.com/25877583/104592599-06476e00-56a1-11eb-8938-447b9a62af7d.png)

![Screen Shot 2021-01-14 at 19 44 12](https://user-images.githubusercontent.com/25877583/104592487-e1eb9180-56a0-11eb-8391-2ab6ac28be34.png)
![Screen Shot 2021-01-14 at 19 44 34](https://user-images.githubusercontent.com/25877583/104592530-ef088080-56a0-11eb-8584-ad5d30f4a56a.png)

**Comment by Dallas62** [comment]
Hi @binhduongquang 

Please check exemple project,

Regards

**Comment by binhduongquang** [comment]
i setup same example project but it's not working

**Comment by binhduongquang** [comment]
helpppp
