### ISSUE TITLE
Work in Galaxy J2 Prime, but not in MI 9T

### ISSUE THREAD

**Issue by rafhajr** [zo0r/react-native-push-notification#1825]
Hello, I used the Readme to create my Local Notifications, and I try on the Samsung Galaxy J2 Prime and it works very well, but when I try on the Xiaomi Mi 9T, I don't get anything. How do I fix this?

**Comment by Dallas62** [comment]
Hi @rafhajr,

As already answered in previous issues, you must create a channel to trigger notification, please refer to readme or example project.

Regards

**Comment by rafhajr** [comment]
Hello @Dallas62, 

Thanks for the answer. I'm going to create a channel, but why do I need it, how does it work with different devices?

**Comment by Dallas62** [comment]
Hi @rafhajr 

Please refer to the Android documentation:
https://developer.android.com/training/notify-user/channels

Regards,

**Comment by rafhajr** [comment]
Thanks @Dallas62, works for me, i am very appreciate for the help and for the lib.
