### ISSUE TITLE
Remote notifications not working

### ISSUE THREAD

**Issue by ajp8164** [zo0r/react-native-push-notification#1827]
I can't get remote notification working using the Firebase notification composer. Only testing with iOS at the moment. Composing a test message using a registration token generated on the device results in no notification received. When using composer to send a message to a target (not test message) the message "0% of potential users are eligible for this campaign: 0" is shown. Seems strange that the app has a registration token but the Firebase app shows no devices registered.

I'm using an iPhone tethered to my mac. App installs via Xcode. The user request to allow push notifications is presented on first install and iOS is set to allow notifications for the app.

No notification is received regardless of app mode; not running, foreground, and background.

Local and scheduled notifications are working fine.

I checked all the config on the Firebase project, on the Apple dev site for the APNs key, the plist file is setup with the XCode project, project capabilities are setup for push notifications and background mode, and I've configured the app similarly to the iOS example project in this repo. I've recheck the AppDelegate.(hm) and that all looks correct. All the settings seem to be correct. I must be missing something..

Any advise for debugging will be helpful.

**Comment by Dallas62** [comment]
Hi @ajp8164 

The token generated on iOS is not a Firebase Token but an APNS one.
Install RNFirebase for Firebase Token.

Regards,

**Comment by ajp8164** [comment]
Thanks for the quick response!

I am under impression I don't need to install RNFirebase (?)
Also, why would firebase composer show 0 iOS devices registered?

Thanks!

**Comment by Dallas62** [comment]
This library use Firebase only for Android (optional) and wrap the iOS library from react-community which is Apple Push Notification (APN).
You cannot send notification to a device with an APN Token over Firebase.
Use RNFirebase to generate a Firebase Token.

Regards,
