### ISSUE TITLE
Is it possible to output a sound that is not built into the app when the alarm ring?

### ISSUE THREAD

**Issue by daheeahn** [zo0r/react-native-push-notification#1828]
# Feature Request

Is it possible to output a sound that is not built into the app when the alarm ring?
I'm making an alarm app, but the volume of sound I want to put is too big, and I want to manage it remotely.

**Comment by Dallas62** [comment]
Hi @daheeahn 
This will not be handled by the library.
If you are able to download your sound in the mobile, it should be possible to play it.
Regards,
