### ISSUE TITLE
Notification not triggering in android

### ISSUE THREAD

**Issue by donny08** [zo0r/react-native-push-notification#1829]
I'm using
react-native: 0.63.4
 buildToolsVersion = "29.0.2"
 minSdkVersion = 21
 compileSdkVersion = 29
 targetSdkVersion = 29

When I trigger the  **PushNotification.localNotification** method i cannot see the notification alert instead getting error alert as **developer warning for package com.xx.xx failed to post notification on channel fcm_fallback_notification_channel see log for more details**. Also I want to mention that i am using for local notification not remote notification, i didn't add any firebase or google configurations.

**Comment by Dallas62** [comment]
Already answered, please search in issue history.
Regards

**Comment by donny08** [comment]
@Dallas62 can you send me the issue number?

**Comment by NoumanSakhawat** [comment]
@Dallas62 please highlight the issue number

**Comment by Dallas62** [comment]
Hi @donny08 @NoumanSakhawat 

The issue has been answered like 50times, you should get the answer easily.
The answer about why it's not working is also in the readme.

Regards.

**Comment by donny08** [comment]
@Dallas62  After creating a channel and sending notification on that channel id is working for me on android, but createChannel method is not triggering in ios simulator and notification not working. Can suggest any workaround for this problem?

**Comment by Dallas62** [comment]
Channels are only for android, you can look at exemple project.
https://developer.android.com/training/notify-user/channels

**Comment by donny08** [comment]
@Dallas62 Can let me know how to debug for ios notification, so i get actual error
