### ISSUE TITLE
Issue When we have some activity , other than MainActivty as Lauching Activity[say, Splash Screen]

### ISSUE THREAD

**Issue by rimzici** [zo0r/react-native-push-notification#183]
Thanks Team, Wonderful module, met all the needs.
Have request to add an "Action" feature for android. Something similart to "alertAction" in IOS.
So that we can trigger particular activity or intent by specifying in Manifest file. 
Now the issue that I am facing is,
After adding splash screen to my app , instead of MainActivity.java , SplashActivity.java is my Launching Activity. Since  the "getMainActivityClass" method in class "RNPushNotificationHelper.java" is finding Launching Activity
`Intent launchIntent = mContext.getPackageManager().getLaunchIntentForPackage(packageName);`

everytime is click on notification in the tray my Splashscreen activity is triggered. I had to edit the "RNPushNotificationHelper" class to direct to my MainActivity. 
This is not a proper fix , so Is there something that you can do to ,
either, Launch MainActivtiy , by someother way than using " getLaunchIntentForPackage"
or, Support for "Action" in android "localNotification" so that user can configure proper Activity on that action.
Thanks in Advance

**Comment by npomfret** [comment]
This is implemented is master now, but not released yet.  Would you be able to help test it before we push the release?

**Comment by danielreuterwall** [comment]
Is there any fix coming for this or is the solution [here](https://github.com/zo0r/react-native-push-notification/issues/122#issuecomment-247355039) the way to go?
