### ISSUE TITLE
Notification is not getting popup, it appears on the notification tray.

### ISSUE THREAD

**Issue by NightFox-06** [zo0r/react-native-push-notification#1832]
# Bug

Hi,
Notification is not getting popup, it appears on the notification tray.
I have tried with localNotification and also with firebase. In both case popup is not appearing.

## Environment info
"react-native": "0.63.3",
react-native-push-notification": "^7.0.0",
"@react-native-firebase/app": "^10.3.0",
"@react-native-firebase/messaging": "^10.3.1",

buildscript {
    ext {
        googlePlayServicesVersion = "+" // default: "+"
        firebaseMessagingVersion = "+" // default: "+"
        buildToolsVersion = "29.0.2"
        minSdkVersion = 19
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.1.0')
        classpath('com.google.gms:google-services:4.3.4')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

##Component
import React, { Component } from 'react';
import NetInfo from "@react-native-community/netinfo";
import { View, Text, Image } from "react-native";
import PropTypes from 'prop-types';
import { connect } from 'react-redux';
import { compose } from 'redux';
import PushNotification from "react-native-push-notification";
import withAsyncReducer from '../../utils/connectors/withAsyncReducer';
import authReducer from '../../reducers/auth.reducer';
import cartReducer from '../../reducers/cart.reducers';
import { AUTH_INFO_STORE_KEY, CART_STORE_KEY } from './authControl.constants';
import { getAuthInfo, getCartInfo } from './authControl.selectors';
import withActions from '../../utils/connectors/withActions';
import ACTION_HANLDERS from './authControl.actionHandlers';
import AUTH_CONTROL_ACTION_TYPES from './authControl.actionTypes';
import Routes from '../../navigation/Routes';

import MaterialIcons from "react-native-vector-icons/MaterialIcons";
import Logo from '../../assets/logo/LogoDark.png';
import THEME from '../../constants/theme.constants';
import PushNotificationIOS from '@react-native-community/push-notification-ios';
import SplashScreen from '../../screens/SplashScreen';
import { EMPTY_OBJECT } from '../../constants/app.constants';
import { Alert, Platform } from 'react-native';
import Toast from 'react-native-simple-toast';

// Must be outside of any component LifeCycle (such as `componentDidMount`).
PushNotification.configure({
    onRegister: function (token) {
        console.log("TOKEN:", token);
      },
    
    onNotification: function (notification) {
        console.log("NOTIFICATION:", notification);
        notification.finish(PushNotificationIOS.FetchResult.NoData);
    },

    // IOS ONLY (optional): default: all - Permissions to register.
    permissions: {
        alert: true,
        badge: true,
        sound: true,
    },

    popInitialNotification: true,

    requestPermissions: true,
});
class AuthControl extends Component {
    componentDidMount = () => {
        const { onAction } = this.props;
        if (!loggedIn) {
            onAction({ type: AUTH_CONTROL_ACTION_TYPES.SYNC_LOCAL_CART });
        }
    }

    render() {
        const { isConnected, checkAuthInProgress, isCartSyncInProgress, loggedIn, userInfo, address } = this.props;
        if (!isConnected) return (
            <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
                <MaterialIcons name="wifi-off" color={THEME.TEXT_COLOR} size={40} />
                <Text style={{ color: THEME.TEXT_COLOR, fontSize: 20, marginTop: 20 }}>Please check your internet connection.</Text>
                <Image source={Logo} style={{ marginTop: 20, height: 50, width: 200, resizeMode: 'contain' }} />
            </View>
        );

        return (checkAuthInProgress || isCartSyncInProgress) ? <SplashScreen /> : <Routes loggedIn={loggedIn} userInfo={userInfo} address={address} />;
    }
};

AuthControl.propTypes = {
    onAction: PropTypes.func.isRequired,
    checkAuthInProgress: PropTypes.bool,
    isCartSyncInProgress: PropTypes.bool,
    isConnected: PropTypes.bool,
    loggedIn: PropTypes.bool,
    userInfo: PropTypes.object,
    address: PropTypes.object,
};

AuthControl.defaultProps = {
    checkAuthInProgress: true,
    isCartSyncInProgress: true,
    isConnected: false,
    loggedIn: false,
    userInfo: EMPTY_OBJECT,
    address: EMPTY_OBJECT,
};
export default compose(
    withAsyncReducer({ key: AUTH_INFO_STORE_KEY, reducer: authReducer }),
    withAsyncReducer({ key: CART_STORE_KEY, reducer: cartReducer }),
    connect(getAuthInfo),
    connect(getCartInfo),
)(withActions(ACTION_HANLDERS)(AuthControl));

##Local Notification
PushNotification.localNotification({    
      channelId: 300,  
      title: "My Notification Title", // (optional)
      message: "My Notification Message", // (required)
    });

**Comment by ferbsferbs** [comment]
Any updates?
