### ISSUE TITLE
There is no remote notification to the android application.

### ISSUE THREAD

**Issue by Batunet** [zo0r/react-native-push-notification#1833]
Hello, I am developing a project with webview. I have a problem getting Android notifications. I have setup with amazon aws and firebase to get notifications. I can also buy tokens this way.

<img width="778" alt="Ekran Resmi 2021-01-19 00 41 26" src="https://user-images.githubusercontent.com/10937629/105091565-156b5900-5ab1-11eb-9fc3-da23b0b82cb7.png">

I also placed the notification codes in the js index. I'm printing it to the console. When I send a notification from Aws it appears on the console, not just the app. i am testing it on the device i connected with usb Where can I go wrong? phone notification permissions are turned on. It comes to the application when I send a notification locally. But when I send a remote notification, it only writes to console. What could be the reason for not appearing in the app?

<img width="808" alt="Ekran Resmi 2021-01-19 00 42 09" src="https://user-images.githubusercontent.com/10937629/105091646-316efa80-5ab1-11eb-8c2c-1be4c116bf8a.png">

**Comment by sadia-onyxtec** [comment]
@Batunet did you find any solution?
