### ISSUE TITLE
There is no remote notification to the android application

### ISSUE THREAD

**Issue by Havvakksuba** [zo0r/react-native-push-notification#1834]
Hello friends, I am developing a project with webview. I have a problem getting Android notifications. I have setup with amazon aws and firebase to get notifications. I can also buy tokens this way.

<img width="778" alt="Ekran Resmi 2021-01-19 00 41 26" src="https://user-images.githubusercontent.com/41155956/105092473-57e16580-5ab2-11eb-8984-5087234e3255.png">

I also placed the notification codes in the js index. I'm printing it to the console. When I send a notification from Aws it appears on the console, not just the app. i am testing it on the device i connected with usb Where can I go wrong? phone notification permissions are turned on. It comes to the application when I send a notification locally. But when I send a remote notification, it only writes to console. What could be the reason for not appearing in the app?

<img width="808" alt="Ekran Resmi 2021-01-19 00 42 09" src="https://user-images.githubusercontent.com/41155956/105092510-6039a080-5ab2-11eb-81d6-b5ed8ab82931.png">

**Comment by Dallas62** [comment]
Hi @Havvakksuba 

You can take a look to these issues:
https://github.com/zo0r/react-native-push-notification/issues/1712
https://github.com/zo0r/react-native-push-notification/issues/1570

Regards,

**Comment by Havvakksuba** [comment]
I studied them. I created a channel but still the same problem continues.
@Dallas62

**Comment by Dallas62** [comment]
So you probably missed the point of each issue. Data-only notification don't show a notification.

**Comment by Havvakksuba** [comment]
so how can I turn this into a notification message.
@Dallas62

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification/issues/1712#issuecomment-711416006
https://github.com/zo0r/react-native-push-notification/issues/1570#issuecomment-666332166

**Comment by moriax** [comment]
Hello @Dallas62 

I was using @react-native-firebase/messaging until now. It was working perfect on anroid+ios. Even If I set notification+data it triggered the background handler.  
But now I have the requirement that I want to delete messages from the notification bar from within my app. 
(Like each messaging app is doing it, if you open a chat with unreaded messages)
Looks like that its not possible with the rnfirebase/messaging module, so I want to start using the module from here.

1. Would you recommend to either use this module or the rnfirebase module? Or should I combine both?

Because I currently run into the issue, that If i send a push notification with notification+data, its displayed, but If I use PushNotification.getDeliveredNotifications it giving me "0" as the identifier, so Iam not able to remove it with removeDeliveredNotifications.
I saw that the identifier is only filled correct If i create a local notification.
(Thats also the case if i only use react-native-push-notification module !)
Looks like the id from the message sent from firebase is a string but the notification needs an integer..

This leads to my next question.. I saw in another thread that you recommended to create a data only push notification and then create a local notification displayed to the user.  Is this a solution, you would recommend also for an app with high volumne of push notifications like a chat app ?

Specially in IOS I think this is called silent notification which should not guarnteed to deliver.. ?

Or you think I should send different mesages to IOS/Android ? IOS containing Notification and android only data ?


Sorry If that is not the right thread to talk about.. But somehow it fits to the background problematic..

**Comment by irsyaadbp** [comment]
> Hello @Dallas62
> 
> I was using @react-native-firebase/messaging until now. It was working perfect on anroid+ios. Even If I set notification+data it triggered the background handler.
> But now I have the requirement that I want to delete messages from the notification bar from within my app.
> (Like each messaging app is doing it, if you open a chat with unreaded messages)
> Looks like that its not possible with the rnfirebase/messaging module, so I want to start using the module from here.
> 
> 1. Would you recommend to either use this module or the rnfirebase module? Or should I combine both?
> 
> Because I currently run into the issue, that If i send a push notification with notification+data, its displayed, but If I use PushNotification.getDeliveredNotifications it giving me "0" as the identifier, so Iam not able to remove it with removeDeliveredNotifications.
> I saw that the identifier is only filled correct If i create a local notification.
> (Thats also the case if i only use react-native-push-notification module !)
> Looks like the id from the message sent from firebase is a string but the notification needs an integer..
> 
> This leads to my next question.. I saw in another thread that you recommended to create a data only push notification and then create a local notification displayed to the user. Is this a solution, you would recommend also for an app with high volumne of push notifications like a chat app ?
> 
> Specially in IOS I think this is called silent notification which should not guarnteed to deliver.. ?
> 
> Or you think I should send different mesages to IOS/Android ? IOS containing Notification and android only data ?
> 
> Sorry If that is not the right thread to talk about.. But somehow it fits to the background problematic..

Hello @moriax, can i know how how do you do to implement @react-native-firebase/messaging with react-native-push-navigation in android + ios ?
is it @react-native-firebase/messaging just use for get FCM token? then to bring up a notification is it required to **call a local notification** when **onMessage** and **setBackgroundMessageHandler** ? or this action is unnecessary? cause now i just implement react-native-push-notification in android without @react-native-firebase/messaging and without call local notif it's works, but i want to implement in ios too

**Comment by irsyaadbp** [comment]
> [#1712 (comment)](https://github.com/zo0r/react-native-push-notification/issues/1712#issuecomment-711416006)
> [#1570 (comment)](https://github.com/zo0r/react-native-push-notification/issues/1570#issuecomment-666332166)

Hello @Dallas62 , 
I am very confused to implement push notifications on Android + IOS
Now I've implemented remote notifications on Android as per the documentation in README, without react-native-firebase / messaging, and without calling local notifications like the comments you mentioned, and it works.
So now I want to implement it on IOS, I see that to implement firebase on IOS it needs some configuration, especially the FCM token, with additional libraries such as react-native-firebase / messaging. If I implement this, do I have to call the local notification manual in onNotification like the comment you mentioned or I don't need it? If this action is needed is this action only needed on IOS or Android as well? remembering now without me calling local notification I can bring up the push notification on android according to the documentation in README about remote notification

thank you

**Comment by Dallas62** [comment]
Hi,

You can use only rnfirebase/messaging if you don't need local notification.
You can add this library on Android for channel management.

Regards

**Comment by irsyaadbp** [comment]
> Hi,
> 
> You can use only rnfirebase/messaging if you don't need local notification.
> You can add this library on Android for channel management.
> 
> Regards

I have no problem calling local notifications
but right now I only use react-native-push-notification and don't call local notification when onNotification and notification are about to appear.
So, when I implement react-native-firebase / messaging do I have to manually call local notifications in onNotification?

**Comment by irsyaadbp** [comment]
> I don't understand your point, you are listing multiple issues (get fcm token, aws?)
> 
> Remote notifications are working with RNFirebase/messaging and without this library if you respect the Firebase Payload format.
> If you need need to work with Firebase, use RNFirebase/messaging.
> Use this library only if there is some functionality missing.
> 
> The only needs is: you must respect the Firebase Format Payload.
> 
> If your notification payload is data-only notification, your are not respecting the Firebase Format and you will need to send a local notification for your needs

now i just implement react-native-push-notification and i configure remote notification with firebase based on documentation in README
![image](https://user-images.githubusercontent.com/23293993/105575895-907a8b00-5da1-11eb-81b1-49d18d656d2b.png)
and its work to show notification in android without call local notification in **onNotification** like comment you mentioned https://github.com/zo0r/react-native-push-notification/issues/1570#issuecomment-666332166 .
Then i want to implement this package on IOS too, i must use RNFirebase/messaging to implement firebase on IOS, then i saw this comment https://github.com/zo0r/react-native-push-notification/issues/1570#issuecomment-666332166 which is where it requires to call a local notification when onNotification to show notification in device. well the question is, is this local notification called when the platform is iOS or Android is also needed?

**Comment by Dallas62** [comment]
If you don't need local Notification and want firebase on iOS, use RNFirebase/messaging. Cannot be more clear 😉

**Comment by irsyaadbp** [comment]
> If you don't need local Notification and want firebase on iOS, use RNFirebase/messaging. Cannot be more clear 😉

i am no problem with local notification on iOS, but if i implement react-native-push-notification with RNFirebase/messaging

that means the code in onNotification is:

![image](https://user-images.githubusercontent.com/23293993/105576587-624b7a00-5da6-11eb-84a1-1c565d076a08.png)

**Comment by Dallas62** [comment]
If you use RNFirebase/messaging you don't need this library for handling notifications.

**Comment by irsyaadbp** [comment]
hmm okay thank you

> If you use RNFirebase/messaging you don't need this library for handling notifications.

**Comment by Havvakksuba** [comment]
When I clicked on the notification, I created a deeplink to direct it and placed it in the code.
But when I click on the notification I received in the foreground, it does not direct. Just click on the notification in the background and on exit.

` messaging().onNotificationOpenedApp(remoteMessage => {
      console.log('onNotificationOpenedApp :', remoteMessage.data);
      if (remoteMessage.data.deeplink) {
        if (remoteMessage.data.deeplink.slice(0, 18) === "https://..../") {
          const deep = remoteMessage.data.deeplink;
          const encoded = encodeURIComponent(deep);
          Linking.openURL('demo://app.../' + encoded)
        } else {
          Linking.openURL(remoteMessage.data.deeplink)
        }
      }
    });`

In this section, when I use the deeplink, it redirects as soon as the notification arrives.

`messaging().onMessage(async remoteMessage => {
        console.log('onMessage: ', remoteMessage)
        if (remoteMessage.data.deeplink.slice(0, 18) === "https://.../") {
          const deep = remoteMessage.data.deeplink;
          const encoded = encodeURIComponent(deep);
          Linking.openURL(demo://app.../' + encoded)
        } else {
          Linking.openURL(remoteMessage.data.deeplink)
        }
    });`

What should I use?

**Comment by Dallas62** [comment]
Hi @Havvakksuba 

I'm not the maintainer of RNFirebase/messaging 😉

Regards

**Comment by GuleriaAshish** [comment]
Do we need to install @react-native-firebase/messaging library in our project in order to use React-native-push-notifications library in our android project? 
As we can see below:
**In your android/build.gradle

ext {
    googlePlayServicesVersion = "<Your play services version>" // default: "+"
    firebaseMessagingVersion = "<Your Firebase version>" // default: "+"

    // Other settings
    compileSdkVersion = <Your compile SDK version> // default: 23
    buildToolsVersion = "<Your build tools version>" // default: "23.0.1"
    targetSdkVersion = <Your target SDK version> // default: 23
    supportLibVersion = "<Your support lib version>" // default: 23.1.1
}**

It is confusing me , as previously there was no need to add firebaseMessagingVersion. Please suggest.
