### ISSUE TITLE
Does the device token changes? how do i keep track of that in remote notification

### ISSUE THREAD

**Issue by kaneki666** [zo0r/react-native-push-notification#1838]
import React, {Component, useEffect, useState} from 'react';
import {
  TextInput,
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  Alert,
  Button,
} from 'react-native';
import PushNotification from 'react-native-push-notification';

const App = () => {
  useEffect(() => {
    // Push notifications setup (recommend extracting into separate file)
    PushNotification.configure({
      onRegister: function (token) {
        console.log('TOKEN:', token);
      },
      // onNotification is called when a notification is to be emitted
      onNotification: (notification) => console.log(notification),

      onAction: function (notification) {
        console.log('ACTION:', notification.action);
        console.log('NOTIFICATION:', notification);

        // process the action
      },

      // Permissions to register for iOS
      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },
      popInitialNotification: true,
    });
  }, []);

  return (
    <View style={styles.container}>
      <Button
        title="send"
        onPress={() =>
          PushNotification.localNotification({
            title: 'Cold Weather Alert',
            message: `It's degrees outside.`,
            playSound: true,
            soundName: 'default',
          })
        }
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  button: {
    borderWidth: 1,
    borderColor: '#000000',
    margin: 5,
    padding: 5,
    width: '70%',
    backgroundColor: '#DDDDDD',
    borderRadius: 5,
  },
  textField: {
    borderWidth: 1,
    borderColor: '#AAAAAA',
    margin: 5,
    padding: 5,
    width: '70%',
  },
  spacer: {
    height: 10,
  },
  title: {
    fontWeight: 'bold',
    fontSize: 20,
    textAlign: 'center',
  },
});

export default App;

**Comment by kaneki666** [comment]
i figured it out! sorry nvm

**Comment by allindeveloper** [comment]
Hi @kaneki666 
Please how did you figure this out, i'm having a similar issue

**Comment by kaneki666** [comment]
i have made a dispatch action and every time user opens the app i save it and make a api req and save it in db..

  PushNotification.configure({
    onRegister: function (token) {
      const tokenData = {
        username: userData.userinfo.username,
        deviceToken: token.token,
      };
      save_Mobile_Token(tokenData);
    },
    onNotification: function (notification) {
      if (notification.userInteraction) {
        // onAction replacement here

        navigation.navigate('GameJoin', {
          gameID: notification.data.gameID,
          name: userData.userinfo.username,
        });
      }
    },
    onAction: function (notification) {
      console.log('ACTION:', notification);
    },
    onRegistrationError: function (err) {
      console.error(err.message, err);
    },
    permissions: {
      alert: true,
      badge: true,
      sound: true,
    },
    popInitialNotification: true,
    requestPermissions: true,
  });
