### ISSUE TITLE
How to properly use groupSummary

### ISSUE THREAD

**Issue by xsephtion** [zo0r/react-native-push-notification#1839]
# Question
groupSummary doesn't seem to work for me. When I receive notifications using PushNotification.localNotification, the notification doesn't get grouped like :

![Screen Shot 2021-01-22 at 10 52 44 AM](https://user-images.githubusercontent.com/17312653/105440220-2c709d80-5ca1-11eb-81c3-b17ba7fbe9d4.png)

Here's my code for reference:

`
PushNotification.localNotification({
    /* Android Only Properties */
    channelId: "channel_here",
    showWhen: true, // (optional) default: true
    autoCancel: true, // (optional) default: true
    largeIcon: message.icon, // (optional) default: "ic_launcher". Use "" for no large icon.
    largeIconUrl: message.icon, // (optional) default: undefined
    smallIcon: "ic_notification", 
    bigText: message.text
    vibrate: true, 
    vibration: 300, 
    tag: message.title,
    group: "group_notif", // (optional) add group to message
    groupSummary: true, // (optional) set this notification to be the group summary for a group of notifications, default: false
    ongoing: false,
    priority: "high", 
    ignoreInForeground: false,
    onlyAlertOnce: false, // (optional) alert will open only once with sound and notify, default: false
    when: null, 
    usesChronometer: false, 
    timeoutAfter: null, 
    invokeApp: true,
    /* iOS only properties */
    category: "", // (optional) default: empty string
  
    /* iOS and Android properties */
    title: message.type == "group" ? message.title + " (Group)": message.title, // (optional)
    message: "Message: "+message.message, // (required)
    userInfo: {}, // (optional) default: {} (using null throws a JSON value '<null>' error)
    playSound: false, // (optional) default: true
    soundName: "default", // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
    number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
  });
`

My version is 7.1.1.

How can I achieve the same effect or notification grouping same as the image above?

**Comment by Dallas62** [comment]
Hi @xsephtion 

You can take a look to this issue:
https://github.com/zo0r/react-native-push-notification/issues/1527#issuecomment-693385260

Regards,

**Comment by xsephtion** [comment]
Thank you for your comment but however this doesn't solved the issue that I was trying to fix. I resolved the issue by using two channels referring to:  https://github.com/zo0r/react-native-push-notification/issues/1591#issuecomment-671777121

Thank you,
