### ISSUE TITLE
onNotification callback not being called with Local notifications

### ISSUE THREAD

**Issue by nivek91** [zo0r/react-native-push-notification#184]
Here is my code:
I followed the steps, I'm sending a local notification and I'm not getting any callback, I'm missing anything?

I have attached the code:

Thanks
`

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Image,
  TextInput,
  ScrollView,
  ListView
} from 'react-native';

import PushNotification from 'react-native-push-notification';

class AwesomeQueues extends Component {
  constructor(props) {

```
super(props);

const ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1 !== r2});
this.state = {
  text: '',
  dataSource: ds.cloneWithRows([
    'John', 'Joel', 'James', 'Jimmy', 'Jackson', 'Jillian', 'Julie', 'Devin','Devin','Devin','Devin','Devin','Devin'
  ])
};

PushNotification.configure({

// (optional) Called when Token is generated (iOS and Android)
onRegister: function(token) {
    console.log( 'TOKEN:', token );
},

// (required) Called when a remote or local notification is opened or received
onNotification: function(notification) {
    console.log( 'NOTIFICATION:', notification );
},


popInitialNotification: true,
```

});

  }

  getMoviesFromApiAsync() {
    return fetch('http://facebook.github.io/react-native/movies.json')
      .then((response) => response.json())
      .then((responseJson) => {
        console.log('test');
        console.log(responseJson.movies);
        PushNotification.localNotification({
    /\* Android Only Properties */
    id: 0, // (optional) default: Autogenerated Unique ID
    ticker: "My Notification Ticker", // (optional)
    autoCancel: true, // (optional) default: true
    largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
    smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
    bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
    subText: "This is a subText", // (optional) default: none
    color: "red", // (optional) default: system default
    vibrate: true, // (optional) default: true
    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
    tag: 'some_tag', // (optional) add tag to message
    group: "group" // (optional) add group to message

});

```
    return responseJson.movies;
  })
  .catch((error) => {
    console.error(error);
  });
```

  }

  render() {
    let pic = {
      uri: 'https://upload.wikimedia.org/wikipedia/commons/d/de/Bananavarieties.jpg'
    };
    this.getMoviesFromApiAsync();
    return (
      <View style={{flex: 1}}>
        <ScrollView style={{flex: 1, backgroundColor: 'powderblue'}}>

<TextInput
          style={{height: 40}}
          placeholder="Type here to translate!"
          onChangeText={(text) => this.setState({text})}
        />
        <Text style={{padding: 10, fontSize: 42}}>
          {this.state.text.split(' ').map((word) => word && '🍕').join(' ')}
        </Text>

```
    </ScrollView>
    <View style={{flex: 2, backgroundColor: 'skyblue'}}>
    <ListView
      dataSource={this.state.dataSource}
      renderRow={(rowData) => <Text>{rowData}</Text>}
    />
    </View>
    <ScrollView style={{flex: 3, backgroundColor: 'steelblue'}}>
```

<Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.android.js
        </Text>
        <Text style={[styles.red, styles.big]}>
          Double tap R on your keyboard to reload,{'\n'}
          Shake or press menu button for dev menu
        </Text>
              <Image source={pic} style={{width: 193, height: 110}}/>
        </ScrollView>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  big: {
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 25,
  },
  red: {
    color: 'red',
  },
});

AppRegistry.registerComponent('AwesomeQueues', () => AwesomeQueues);
`
[Archive.zip](https://github.com/zo0r/react-native-push-notification/files/449870/Archive.zip)

**Comment by npomfret** [comment]
Do you see the notification appearing in the notification centre?

**Comment by nivek91** [comment]
@npomfret I dont see any notification at all. Nothing happens, No error, no notification.

**Comment by npomfret** [comment]
Did it register ok?  Do you see output from the line `console.log( 'TOKEN:', token );`?

Is there any logging in Android Studio?  Set the log level to debug and don't put any filters on.

Have you tried stepping in with the debugger?  Start with the JS code, and if it looks like it working a then the java code.

**Comment by jsdario** [comment]
In this case https://github.com/zo0r/react-native-push-notification/issues/231 notification log shows on the console **only** when opening the app from the notice. Log never appears when notification is received.

Also I realized that `onRegister` is not firing or at least not logging any messege, but I am only using local or local scheduled notifications.

**Comment by nonameolsson** [comment]
Any update on this? I'm still experiencing the same problem

**Comment by nonameolsson** [comment]
Whats up with the status on this one? I'm having the same problem.
