### ISSUE TITLE
onRegister is not called after an iOS iCloud restore

### ISSUE THREAD

**Issue by plus-** [zo0r/react-native-push-notification#1850]
# Bug

I restored my environment after changing phones using iCloud backup. The notification granted permissions were transferred as part of the backup.

However the onRegister is never called when the application is restored this way (user never has to accept notifications on the new phone), I had to uninstall/reinstall the app for the onRegister to trigger again when accepting notifications in order to generate my token.

**Comment by Dallas62** [comment]
Hi @plus- 
For iOS issue, please refer to this repository:
https://github.com/react-native-push-notification-ios/push-notification-ios
Regards,
