### ISSUE TITLE
Documentation vs Example Mismatch - PushNotification.configure()

### ISSUE THREAD

**Issue by Rubicon-Charge** [zo0r/react-native-push-notification#1851]
# Question

The documentation in the Readme says:
```
DO NOT USE .configure() INSIDE A COMPONENT, EVEN App
If you do, notification handlers will not fire, because they are not loaded. Instead, use .configure() in the app's first file, usually index.js.
```

The example does not adhere to this, which makes it difficult to know what is correct - the readme, or the example.  Based on this being added to the Readme in July 2020 but the example Index.js not being updated since April 2020, I assume the Readme is the recommended practice.

Would be great to have the example app updated to reflect this, or clarification on this in general.  Based on the Readme, it would make me think the example wouldn't work at all with it not calling configure in Index.js.

**Comment by Dallas62** [comment]
Hi @Rubicon-Charge
Already answered in another issue. `.configure()` is called outside of any component in the exemple project.
But there is an helper to attach a method in case the application is running in foreground mode.
Regards

**Comment by snios** [comment]
> Hi @Rubicon-Charge
> Already answered in another issue. `.configure()` is called outside of any component in the exemple project.
> But there is an helper to attach a method in case the application is running in foreground mode.
> Regards

This answer does not make the example vs documentation any more right thogh. What issue are you refering to? A link would be helpful. Thanks

**Comment by Dallas62** [comment]
Hi @snios 
Which part of:
`DO NOT USE .configure() INSIDE A COMPONENT, EVEN App. If you do, notification handlers will not fire` is not clear in the sentence ?
Regards,
