### ISSUE TITLE
Know if user delete notification

### ISSUE THREAD

**Issue by 15matias15** [zo0r/react-native-push-notification#1854]
# Question
Hey guys, for Android, is it possible to know when the user delete the notification? like delete my notification or push on "Clear All"

Thanks

**Comment by Dallas62** [comment]
Hi @15matias15 
You can list all the notifications in the notification center:
`getDeliveredNotifications`, if the notification doesn't exist, the notification is deleted.
You must track all send notifications to acheive this.
Regards,

**Comment by 15matias15** [comment]
Thanks @Dallas62

**Comment by Ruzen1** [comment]
@15matias15  hey bro, can you please share the code of using getDeliveredNotifications, am not errors.
Your help is highly appreciated.
