### ISSUE TITLE
How to create custom notification layout for android and ios ?

### ISSUE THREAD

**Issue by gaurav0044** [zo0r/react-native-push-notification#1856]
# Feature Request

**Comment by gaurav0044** [comment]
@Dallas62  please describe something before closing 

> # Feature Request

**Comment by Dallas62** [comment]
Hi @gaurav0044 
Please write a full description of your problem/question/feature request (I don't know there) before opening an issue.
Regards,

**Comment by gaurav0044** [comment]
> Hi @gaurav0044
> Please write a full description of your problem/question/feature request (I don't know there) before opening an issue.
> Regards,
Alright @Dallas62  , 
please have a look in this image i want this type of notification layout. how can i draw this type of layout ? [https://i.stack.imgur.com/whr1B.png](url)
