### ISSUE TITLE
 How can I get the date of the scheduled notifications

### ISSUE THREAD

**Issue by Breners** [zo0r/react-native-push-notification#1857]
I know that I need to pass a callback within PushNotification.getScheduledLocalNotifications (callback);

but I'm not sure how to do this

```
export const showNotification = () => { 
  const not = PushNotification.getScheduledLocalNotifications();

  console.log("Scheduled: ", not);
}

```

**Comment by Dallas62** [comment]
Hi @Breners 
You can refer to the exemple project:
https://github.com/zo0r/react-native-push-notification/blob/master/example/NotifService.js#L170

https://github.com/zo0r/react-native-push-notification/blob/master/example/App.js#L111

Regards,
