### ISSUE TITLE
Remote Notification doesn't come when I am browsing app..

### ISSUE THREAD

**Issue by kaneki666** [zo0r/react-native-push-notification#1859]
it might be silly question ...is it the mechanism that notification wont come when I am in the app...but local notification come when I am in the app..

if I am not in the app remote notification comes nicely

**Comment by Dallas62** [comment]
Hi @kaneki666 
On which OS do you have this behavior ?
Regards,

**Comment by kaneki666** [comment]
> Hi @kaneki666
> On which OS do you have this behavior ?
> Regards,

i am getting this in android! pixel 2..
i am sending notification from firebase by topic..it comes if I aim not in app

**Comment by Dallas62** [comment]
Hi @kaneki666 
You probably missed the creation of a channel,
Please look at the Channel Management part of the readme.
Regards,

**Comment by kaneki666** [comment]
> Hi @kaneki666
> You probably missed the creation of a channel,
> Please look at the Channel Management part of the readme.
> Regards,


this is my code..am 
I missing anything
/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import PushNotification from 'react-native-push-notification';
import {GoogleSignin} from '@react-native-community/google-signin';
import {AddDeviceTokenAction} from './src/redux/actions/AddDeviceTokenAction';
import {store} from './src/redux/store';

GoogleSignin.configure({
  webClientId:
    '528367867426-v2lasmi2fig2n0bih9p0m4v70qhovh7j.apps.googleusercontent.com',
});

PushNotification.configure({
  onRegister: function (token) {
    console.log('TOKEN:', token);

    store.dispatch(AddDeviceTokenAction(token.token));
  },
  onNotification: function (notification) {
    console.log('NOTIFICATION:', notification);
  },
  onAction: function (notification) {
    console.log('ACTION:', notification.action);
    console.log('NOTIFICATION:', notification);
  },
  onRegistrationError: function (err) {
    console.error(err.message, err);
  },
  permissions: {
    alert: true,
    badge: true,
    sound: true,
  },
  popInitialNotification: true,
  requestPermissions: true,
});

PushNotification.subscribeToTopic('demo');
AppRegistry.registerComponent(appName, () => App);

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification#channel-management-android

**Comment by kaneki666** [comment]
ok i have created a channel named firebasechannel...but my notification going to fallback fcm and its not showing still when i am in app...how to redirect the notification to firebasechannel i have created.

this the log when i check channel exist and i get notification so notification coming but not showing
["firebasechannel"]
[Tue Feb 09 2021 13:51:52.338]  LOG      NOTIFICATION: {"channelId": "fcm_fallback_notification_channel", "color": null, "data": {}, "finish": [Function finish], "foreground": true, "id": "1554061909", "message": "s", "priority": "high", "sound": null, "tag": "campaign_collapse_key_3838549984594835704", "title": "s", "userInteraction": false, "visibility": "private"}
my manifest file
     <manifest xmlns:android="http://schemas.android.com/apk/res/android" 
  package="co.miaki.samplestickerappp">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
            android:value="false"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
            android:resource="@color/white"/> 
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon"
         android:resource="@drawable/notification_icon" />
        <meta-data android:name="com.google.firebase.messaging.fcm_fallback_notification_channel"
         android:resource="@drawable/notification_icon" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
         android:exported="true"
        android:windowSoftInputMode="adjustResize">
        
      </activity>
      <activity
      android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
      android:theme="@style/BootTheme"
      android:launchMode="singleTask">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>


thank you for you help appreciate it

**Comment by Dallas62** [comment]
So you must precise the channel ID when you send your notification.
https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support
**Tableau 2b.**
- `android_channel_id`

**Comment by kaneki666** [comment]
> So you must precise the channel ID when you send your notification.
> https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support
> **Tableau 2b.**
> 
> * `android_channel_id`

I have sent to this channel stilll not showing...this is the log u can see channel created and notification channel

 ["firebasechannel"]
[Tue Feb 09 2021 14:15:11.747]  LOG      TOKEN: {"os": "android", "token": "dIZuUlfZRZWOp6bWci7etS:APA91bElLI2KzmWVDwYxDXq60qiqgCKWygPdWLWdcrqaZoO-uvHfczjIrCk4ZTcUYzdQeObZvY23BvZWiwkW49jShy7w2zhNIXLdYzTid1pAQjj69MluD03y6Y6BeeQzSKHCJ0Ew2wp_"}
[Tue Feb 09 2021 14:15:18.906]  LOG      NOTIFICATION: {"channelId": "firebasechannel", "color": null, "data": {}, "finish": [Function finish], "foreground": true, "id": "-2019934703", "message": "d", "priority": "high", "sound": null, "tag": "campaign_collapse_key_5912904394951762529", "title": "d", "userInteraction": false, "visibility": "private"}

**Comment by Dallas62** [comment]
What is your notification payload ?

**Comment by kaneki666** [comment]
ok i am noting a difference in notification...iam not sure what i am doing i am sending notification from firebase console same approach..one is coming when i am not in app..this the log then
LOG NOTIFICATION: {"channelId": "firebasechannel", "color": null, "data": {}, "finish": [Function finish], "foreground": true, "id": "-2019934703", "message": "d", "priority": "high", "sound": null, "tag": "campaign_collapse_key_5912904394951762529", "title": "d", "userInteraction": false, "visibility": "private"}
another is when  am not in app this is the log
NOTIFICATION: {"data": {"1": "2", "collapse_key": "co.miaki.samplestickerappp", "from": "/topics/firebasechannel", "google.delivered_priority": "high", "google.message_id": "0:1612859326479433%278582f5278582f5", "google.original_priority": "high", "google.sent_time": 1612859326256, "google.ttl": 2419200}, "finish": [Function finish], "foreground": false, "userInteraction": true}


i am really sorry i am new to this

**Comment by Dallas62** [comment]
I don't how you are sending your second notification, but your are sending a data-only notification (second time). data-only notification doesn't appear to the user.

https://firebase.google.com/docs/cloud-messaging/concept-options
https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md#about-notifications

**Comment by kaneki666** [comment]
can u watch this? i have recorded whole process!
https://drive.google.com/file/d/1kGCjIok-KQR1Hc64QzCMu8ja36u7RH2H/view?usp=sharing

**Comment by Dallas62** [comment]
You set ignore foreground in your AndroidManifest:

```xml
<meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground" android:value="false" />
```

Change it to true.

**Comment by kaneki666** [comment]
> You set ignore foreground in your AndroidManifest:
> 
> ```
> <meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground" android:value="false" />
> ```
> 
> Change it to true.

brother i love you! thank you very much! appreciate he help
