### ISSUE TITLE
Is this possible to handle data on android if getNotification is null ?

### ISSUE THREAD

**Issue by ederwan** [zo0r/react-native-push-notification#1862]
Hi everyone,
It's not realy a bug but i want to handle Ios and android notification with one notification but it's doesn't work now with this library on android.
For example if title isn't in remoteMessage.getNotification(), it should be a good id to look in data this way:
remoteMessage.getData().get(title).
I don't think i can create something to update the remoteMessage before passing it to your lib. Or is it possible to create a merge request with this features for handling notification the same way on ios and android.
Thank for reading

**Comment by Dallas62** [comment]
Hi @ederwan 
This feature has been removed because there is too many edge cases (multiple providers).
You can send data-only notification then trigger a local notification with data information.
Regards

**Comment by ederwan** [comment]
Thank for the fast reply, but how i get this data in Js code for creating a localNotif ?

**Comment by ederwan** [comment]
Perfect, thank a lot, it work like a charm, have a good day ;)
