### ISSUE TITLE
How i can manipulate data from getScheduledLocalNotifications

### ISSUE THREAD

**Issue by Breners** [zo0r/react-native-push-notification#1863]
I have this method and i wanna manipulate my array of result

```
const Notification = (res) => {
    let result = [];
    showNotification(notif => notif.map(res => { 
      result.push(res.date);
      console.log(result);
    }))
  };
```

Method showNotification

```
export const showNotification = (callback) => { 
  PushNotification.getScheduledLocalNotifications(callback);
}

```

So, the i want remove result from this scope and put outside showNotification, how its possible?

**Comment by Dallas62** [comment]
Hi @Breners 
This repository is not about programming question / support.
This kind of question is a question for StackOverflow.
Regards,
https://stackoverflow.com/questions/22519784/how-do-i-convert-an-existing-callback-api-to-promises

**Comment by theneekz** [comment]
If anyone else ends up here, you can wrap the method in a promise and use it asynchronously

In notifications.js:
`export async function getScheduledLocalNotifications() {
  return new Promise((res) =>
    PushNotification.getScheduledLocalNotifications((arrOfNotifications) => {
      res(arrOfNotifications);
    }),
  );
}`

In your component:
`
import {getScheduledLocalNotifications} from 'notifications.js'
const arrOfNotifications = await getScheduledLocalNotifications();
`
