### ISSUE TITLE
Notification sound is not coming while app is in background

### ISSUE THREAD

**Issue by souvick007** [zo0r/react-native-push-notification#1868]
when the app is in background notification sound is not sounding in ios
I am using react-native-push-notification version 3.1.9

**Comment by Dallas62** [comment]
Hi @souvick007

This version is no more maintained.
Please upgrade your version.

Regards

**Comment by souvick007** [comment]
Hi Dallas62 thanks for the reply
I have upgraded the react-native-push-notification version to 7.2.1 and also @react-native-community/push-notification-ios version to 1.8.0 ,but still I am not able to hear sound of notification when the app is on background.
the push notification sound is coming when the app is in foreground but no sound for push notification when the app is in background

**Comment by Dallas62** [comment]
Hi @souvick007 

You can look at exemple project or take a look to the iOS repository which is responsible of the iOS version:
@react-native-community/push-notification-ios

Regards,

**Comment by LaVielle** [comment]
@souvick007 I assume that you're talking about remote Push Notifications not ringing/vibrating when coming in background/quit states.
I had the same issue and figured that I need to **specify the sound I want from the backend where I send the Push Notification**.

So my JSON payload looks like this:
```JSON
{
   "message":{
      "notification":{
         "title":"Hi",
         "body":"OMG It works!"
      },
      "apns":{
         "headers":{
            "apns-priority":"10"
         },
         "payload":{
            "aps":{
               "sound":"default"
            }
         }
      }
   }
}
```
_(I use Customer.io to send my Push Notifications, your payload might look slightly different if you use a different service)_

This is the SO answer that helped me: [https://stackoverflow.com/a/50117140/9957187](https://stackoverflow.com/a/50117140/9957187)

**Comment by anhdo9797** [comment]
> Hi Dallas62 thanks for the reply
> I have upgraded the react-native-push-notification version to 7.2.1 and also @react-native-community/push-notification-ios version to 1.8.0 ,but still I am not able to hear sound of notification when the app is on background.
> the push notification sound is coming when the app is in foreground but no sound for push notification when the app is in background

same issue

**Comment by pritamleocoders** [comment]
same issue
