### ISSUE TITLE
Custom sound doesn't work on local notification (Android)

### ISSUE THREAD

**Issue by Raserad** [zo0r/react-native-push-notification#1869]
Hi everyone& I've configured this library by documentation, here is my code:
`
PushNotification.configure({
      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },
      popInitialNotification: true,
      requestPermissions: true,

      onNotification: function (notification) {
        store.dispatch(processAction(notification.data));
        notification.finish(PushNotificationIOS.FetchResult.NoData);
      },
    });

    PushNotification.createChannel(
      {
        channelId: 'notification-id',
        channelName: 'Notification name',
        importance: 4,
      },
      (created) => console.log(`createChannel returned '${created}'`),
    );
`

And I try to send the local scheduled notification:
`
PushNotification.localNotificationSchedule({
      channelId: 'notification-id',
      message: 'Hello test',
      soundName: 'sound.mp3',
      date: new Date(Date.now() + 6000),
    });
`

I have this sound.mp3 in my [project_root]/android/app/src/main/res/raw folder. But notification is showing, but not playing any sound. Why is it?
@pedro @jgarber @idris @peterp @cancan101

**Comment by Dallas62** [comment]
Hi @Raserad
Custom sound must be placed on the channel on Android.
Also, channel cannot be updated, make sure you test on another channel.
Regards,

**Comment by Raserad** [comment]
> Hi @Raserad
> Custom sound must be placed on the channel on Android.
> Also, the channel cannot be updated, make sure you test on another channel.
> Regards,

But I want to implement an alarm and I have to be able to add custom sound to the notification.

**Comment by Raserad** [comment]
> Hi @Raserad
> Custom sound must be placed on the channel on Android.
> Also, channel cannot be updated, make sure you test on another channel.
> Regards,

And how many channels can I create in android? Do you know it?
