### ISSUE TITLE
Id of localNotificationSchedule

### ISSUE THREAD

**Issue by Raserad** [zo0r/react-native-push-notification#1870]
How to get generated id from localNotificationSchedule?
And what id can i pass into localNotificationSchedule?
I tried to pass Date.now(), new Date().getTime(), after that notification isn't shown, but without that notification is shown as usual.
@pedro @jgarber @idris @peterp @cancan101

**Comment by Dallas62** [comment]
Hi @Raserad 

Just respect the contract:
```js
id: 0, // (optional) Valid unique 32 bit integer. default: Autogenerated Unique ID
```
(Auto cast to string if needed)

Regards,

**Comment by zabojad** [comment]
@Dallas62 should thus be `id: "0",` as a string seems to be expected...

**Comment by theneekz** [comment]
either string or number will work as long as it is a 32-bit unsigned int (-2147483648 to 2147483647)
