### ISSUE TITLE
When there are two or more notifications, clicking on old notifcation runs onNotification with data from newest notification.

### ISSUE THREAD

**Issue by aslampr07** [zo0r/react-native-push-notification#1871]
# Question

In Android, I can't figure out why, but when multiple notifications came in and when I click on the oldest notification, the onNotification function's data object contains the data from the newest notification. instead of the data from the notification that I have clicked. This occurred both in Foreground and Background Notification.

Here is my configure function.

```
    PushNotification.configure({
      onRegister: async (token) => {
        console.log('TOKEN:', token);
      },
      onNotification: async (notification)=>{
            console.log(notification.data);
      }
      senderID: 'XXXXXXXXXX',
      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },
      popInitialNotification: true,
      requestPermissions: true,
    });
```

I have no idea why is this happening, this issue was tested in Android 10 and Android 7.

**Comment by Dallas62** [comment]
Hi @aslampr07 

Are you sure of that ?
Did click on a group of notification or did you click on a single notification ?
Data are stick to the intent of the notification, there is probably an issue in your implementation.

Please provide a reproducible exemple if you are sure it's a bug from the library, also check with the exemple project.

Regards
