### ISSUE TITLE
ongoing notification in iOS is getting cleared

### ISSUE THREAD

**Issue by deepakverma4** [zo0r/react-native-push-notification#1872]
# Bug

'
I'm generating one ongoing notification in iOS  14.4  using 

```
 PushNotification.localNotification({
      ongoing: true,// (optional) set whether this is an "ongoing" notification
      priority: 'high',
      id: '9999', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      title: 'Ongoing meeting', // (optional)
      message: 'Test message ', // (required)
      userInfo: {}, // (optional) default: {} (using null throws a JSON value '<null>' error)
      playSound: false, // (optional) default: true
      autoCancel: false,
      vibrate: false,
      usesChronometer: false,
      
    });
``` 
But as soon as user clicks or press clear button it is getting cleared

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.2
    CPU: (8) arm64 Apple M1
    Memory: 145.59 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.7.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 7.4.3 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version:3.5.2

## Steps To Reproduce

1. create one ongoing local notification 
2. click on notification / press clear button

Describe what you expected to happen:

1. Ongoing  notification should not be cleared

**Comment by Dallas62** [comment]
Hi @deepakverma4 

First of all, you are using an old version of the library which is not maintained.
Secondly, this repository is not about iOS issue, refer to the react-native-community package.
You are using an Android-only property (`ongoing`)

Regards

**Comment by Dallas62** [comment]
Hi @deepakverma4 

First of all, you are using an old version of the library which is not maintained.
Secondly, this repository is not about iOS issue, refer to the react-native-community package.
You are using an Android-only property (`ongoing`)

Regards

**Comment by deepakverma4** [comment]
@Dallas62 I've updated my library version to latest. still i'm facing same issue, can you please  tell me how can i create non cancellable push notification  in iOS?

**Comment by Dallas62** [comment]
>Hi @deepakverma4
>
> First of all, you are using an old version of the library which is not maintained.
> Secondly, this repository is not about iOS issue, refer to the react-native-community package.
> You are using an Android-only property (ongoing)
>
>Regards

Still a valid answer.
