### ISSUE TITLE
Custom Sound for Remote Notification on iOS

### ISSUE THREAD

**Issue by timotiusfit** [zo0r/react-native-push-notification#1873]
Hello, I have a question. 

Is there any way to set a custom sound when received remote notification on iOS? As I read the docs, the custom sound can only be set for local notification. Thanks for any answer.

**Comment by Dallas62** [comment]
Hi @timotiusfit 
Please refer to the official Apple documentation for that:
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification

Regards,
