### ISSUE TITLE
iOS redirect to page on click

### ISSUE THREAD

**Issue by BogdanHossu** [zo0r/react-native-push-notification#1874]
# Question

Hello, I am struggling for quite some time in making a way of redirecting the user to a specific page based on what notification he received and clicked. I do not have any issues with Android, the following implemented solution works for me but not in iOS.  Since is not recommended to not use configure inside of a component, I tried to make my solution go around to work with react-router.

```
onNotification: notification => {
    if (isNil(notification)) {
      return;
    }

    // if app is in foreground, the notification it won't be shown
    if (notification.foreground) {
      DeviceEventEmitter.emit('key-foreground', notification);
      return;
    }

    // process the notification
    DeviceEventEmitter.emit('key-notification-clicked', notification);

    // (required) Called when a remote is received or opened, or local notification is opened
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },
```

Than in my router component, I am trying to set the redirect url based on the notification data.

```
useEffect(() => {
    const handleNotificationClick = ({ type, data }) => {
      const itemId = get(data, 'item.id');

      const notificationTypes = [
         'type1',
         'type2',
      ];

      if (indexOf(notificationTypes, type) > -1) {
        setRedirectUrl(`/item/${itemId}`);
        return;
      }

      setRedirectUrl('/dashboard');
    };

    DeviceEventEmitter.addListener(
      'key-notification-clicked',,
      handleNotificationClick,
    );

    return () => DeviceEventEmitter.removeListener('key-notification-clicked',);
  }, []);
```

As mentioned, this works in Android without any issues but not on iOS. Am I missing something? I am completely stuck for a week and I have not find any solution.

Thank you in advance for possible help!

**Comment by jignesh-joshi** [comment]
I am facing the same issue. In Android every case redirection is working fine in iOS when user is in foreground or background it is working but when the user app is in a killed state user is unable to redirect to application-specific screen I am using raect-native@0.68.4
