### ISSUE TITLE
Is this library provide Android Notification badge?

### ISSUE THREAD

**Issue by axeljeremy7** [zo0r/react-native-push-notification#1875]
# Question
Is this library provide Android Notification badge?

I remember two versions ago, that this appear but now it is not appearing, I would like know if this is still possible for local and remote notifications.
https://developer.android.com/training/notify-user/badges

![](https://developer.android.com/images/ui/notifications/badges-open_2x.png)

**Comment by Dallas62** [comment]
Hi @axeljeremy7,
You must provide a number in the notification.
It's not working without it.
Regards

**Comment by axeljeremy7** [comment]
@Dallas62 I put the number when I create the local notification but it never shows, and the same for remote.

**Comment by Dallas62** [comment]
@axeljeremy7 You should probably remove: `groupSummary: true`.

https://stackoverflow.com/questions/55720426/why-notification-badge-in-android-o-does-not-show-when-setgroupsummary-is-set

>  It seems that setGroupSummary should be added on Group Notification and setShowBadge should be on the Child Notification

**Comment by axeljeremy7** [comment]
@Dallas62 thanks, that works. Although the badge does grouping for one channel at a time, it does not show two different channels or more but only show the recently message of the channel and its group, and the notifications are set always to 999.

**Comment by axeljeremy7** [comment]
@Dallas62 I discovered that the badge only appear for notifications send after the phone is locked but when is foreground or background the badge does not increment or appear.
