### ISSUE TITLE
abandonPermissions not working in Android

### ISSUE THREAD

**Issue by toanpv-2417** [zo0r/react-native-push-notification#1876]
i want to use this method when expired token or logout app but it only works in ios and can't work in Android

**Comment by filipef101** [comment]
It works on android

**Comment by toanpv-2417** [comment]
> It works on android

can u show me code about the using abandonPermissions method , it does not work in Android with my project

**Comment by filipef101** [comment]
It has a native implementation. What exactly doesn't work for you?
It is not meant to revoke the push notification permission, not sure if that is what you were expecting. It is to stop receiving notifications, ex logout, what it does is delete the notification token. Then on login or whatever you call request permissions, that will generate a new token.

**Comment by filipef101** [comment]
So, how exactly does it not work for you? what is the behavior expected?

**Comment by toanpv-2417** [comment]
@filipef101  i run abandonPermissions method when expired token but it not work immediately and app still receive notification . If i reload app or kill & restart app ,  that method actually runs and app can unregister notification . This status only exist in Android
