### ISSUE TITLE
Scheduled Local Notification how to trigger event when Notification arrived in Foreground

### ISSUE THREAD

**Issue by abdymm** [zo0r/react-native-push-notification#1877]
How we can trigger some event, for local notification when the notification arrived (before user tap it) because right now i see on `onNotification` its only   Called when a remote is received or opened, or local notification is opened
is there a way to call the `onNotification` method when Local Notification is **received** in **Foreground**? so i can trigger some UI changes

Thanks

*on rnfirebase this like `onMessage` event 

cc: @Dallas62

**Comment by Dallas62** [comment]
Hi @abdymm 

Already answered in issues. And not possible with localNotification.

Regards,

**Comment by abdymm** [comment]
i see, thanks @Dallas62
