### ISSUE TITLE
iOS - Local Scheduled Notification not triggering onNotification in background

### ISSUE THREAD

**Issue by JakeMotta** [zo0r/react-native-push-notification#1879]
Browsed many of the other issues, but didn't quite see a clear answer / directly relevant case, so I figured I'd ask.

react-native: 0.61.5
react-native-push-notification: 7.2.1

My app has _react-native-push-notifications_ configured and working (mostly) as intended, with my local notifications triggering in the foreground as expected. I have a server that is using _node-pushnotifications_, and those are working as intended as well.

The remote notifications (from my server) are properly triggering my app (onNotification) in the background, and I'm able to execute some logic as a result. However, this is not the case when using _localNotificationSchedule,_ which is only triggering _onNotification_ when the app is in the foreground, when I need it to also trigger in the background. 

Just to be clear, I am getting local notifications in the background, they just aren't triggering the _onNotification_ function. It is possible to use localNotifications to trigger _onNotification_ in the background, right?

I feel like I've read into this a bit too much the past few days, and have over-confused myself. Any advice would be appreciated.

Some code snippets I've tried (using NotifService & Push Notification library). Both triggering _onNotification_ in foreground, but not in background.

![image](https://user-images.githubusercontent.com/1768585/108473792-5935b780-7243-11eb-9b3b-12bbb422110b.png)
![image](https://user-images.githubusercontent.com/1768585/108473801-5cc93e80-7243-11eb-8b3b-f9c9ac72db84.png)

**Comment by Dallas62** [comment]
Hi @JakeMotta 

> However, this is not the case when using localNotificationSchedule, which is only triggering onNotification when the app is in the foreground, when I need it to also trigger in the background.

This is not possible with the library, and it's not the aim of a local notification to trigger "background-task".

Please take a look to:
https://github.com/transistorsoft/react-native-background-fetch
https://github.com/jamesisaac/react-native-background-task

Regards,

**Comment by Dallas62** [comment]
Same as #1877

**Comment by JakeMotta** [comment]
> Hi @JakeMotta
> 
> > However, this is not the case when using localNotificationSchedule, which is only triggering onNotification when the app is in the foreground, when I need it to also trigger in the background.
> 
> This is not possible with the library, and it's not the aim of a local notification to trigger "background-task".
> 
> Please take a look to:
> https://github.com/transistorsoft/react-native-background-fetch
> https://github.com/jamesisaac/react-native-background-task
> 
> Regards,

Glad to know. I was starting to lose my mind thinking everyone was getting this to work except me... Thanks for the prompt reply!
