### ISSUE TITLE
iOS - onNotification not triggered when app is opened by tapping a local notification

### ISSUE THREAD

**Issue by zabojad** [zo0r/react-native-push-notification#1883]
# Bug

On iOS, if I:
1- schedule a local notification,
2- put the app in background and wait for the notification to appear, then open the notification,
=> onNotification will be correctly called.

Now, if I:
1- schedule a local notification,
2- close the app and wait for the notification to appear, then open the notification,
=> onNotification will **not** be called at app startup.

`react-native info` output:

```bash
$ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 114.61 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.1.0 - ~/.nvm/versions/node/v14.1.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.1.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 18, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.2, 29.0.3, 30.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: 20.1.5948944
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242-release - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: 7.2.0

## Steps To Reproduce

1. schedule a local notif for 30 secs later
2. close the  app completely
3. Wait for the notif to show up and tap it to open the app.
4. app opens but onNotification is not called...

Describe what you expected to happen:
1. schedule a local notif for 30 secs later
2. close the  app completely
3. Wait for the notif to show up and tap it to open the app.
4. app opens and onNotification is called with notification object...

**Comment by Dallas62** [comment]
Hi @zabojad 

Please check the iOS installation AND the iOS repository (issues).
This is not the right repository.

Regards.

**Comment by zabojad** [comment]
@Dallas62 I checked the iOS repo and tried `PushNotificationIOS.getInitialNotification();`. It works but there is something not clear here about the difference of behavior of the `onNotification` callback between iOS and Android.

In my opinion, this call:

```js
PushNotification.configure({
    onNotification: function(n){
    }, 
    // ...
});
```
should actually implement `PushNotificationIOS.getInitialNotification();`...
@Dallas62 don't you think?
`
