### ISSUE TITLE
Help: Do I need to use react-native-firebase to get remote notifications to work

### ISSUE THREAD

**Issue by nero2009** [zo0r/react-native-push-notification#1885]
# Question

**For Android** 
Hi everyone, Please do I need to use another library like [react-native-firebase](https://github.com/invertase/react-native-firebase) alongside zo0r/react-native-push-notification to be able to receive remote notifications?

Right now without using  [react-native-firebase](https://github.com/invertase/react-native-firebase) I can send test notifications from [firebase console](https://console.firebase.google.com/) and I receive them on my app but I dont receive notifications send from my backend/server.

**Comment by Dallas62** [comment]
Hi @nero2009 

No RNFirebase is not required for remote notifications.

Now, why it's not working: I don't know, there is no information about what you are doing.

Regards,

https://github.com/zo0r/react-native-push-notification#channel-management-android

**Comment by nero2009** [comment]
This is my android manifest and push notification configure function. Also where do I call the `PushNotification.createChannel()` function

AndroidManifest.xml

`
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.smarthealthmobile">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <permission
        android:name="com.myapp.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
    <uses-permission android:name="com.myapp.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>


    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/myapp"
      android:roundIcon="@mipmap/myapp_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                  android:value="true"/>
      
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                  android:resource="@android:color/white"/> 
      
      <meta-data
                  android:name="com.google.firebase.messaging.default_notification_channel_id"
                  android:value="fcm_fallback_notification_channel" />

      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED" />
              <action android:name="android.intent.action.QUICKBOOT_POWERON" />
              <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
          </intent-filter>
      </receiver>

      <service
          android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
          android:exported="false" >
          <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
      </service>
    </application>

</manifest>

`


```
import React, { useState, useEffect, createContext } from 'react'
import { Alert } from 'react-native'
import PushNotificationIOS from '@react-native-community/push-notification-ios'
import PushNotification from 'react-native-push-notification'

export function NotificationsServiceProvider({ children }) {
	const configure = () => {
		PushNotification.configure({
			onRegister: async function(tokenData) {
				const userID = await getUserID()
				const { token } = await getDeviceToken()

				if (tokenData.token !== token) {
					await addDeviceToken(userID, tokenData)
				}
			},

			onNotification: function(notification) {
				console.log('NOTIFICATION:', notification)

				notification.finish(PushNotificationIOS.FetchResult.NoData)
				
			},

			onRegistrationError: function(err) {
				console.error('PUSH Notification registration failed', err)
	
			},
			senderID: 'my-sender-id',

			permissions: {
				alert: true,
				badge: true,
				sound: true,
			},

			popInitialNotification: true,
			requestPermissions: true,
		})
	}

	return (
		<NotificationsContext.Provider value={{ configure }}>
			{children}
		</NotificationsContext.Provider>
	)
}
```

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification#usage

**DO NOT USE .configure() INSIDE A COMPONENT, EVEN App**

> If you do, notification handlers will not fire, because they are not loaded. Instead, use .configure() in the app's first file, usually index.js.

Regards

**Comment by nero2009** [comment]
Sorry, I have moved the `.configure()` outside a component. it is now a service being initialized in the react native `App.js` file but I still dont get remote notifications from my server.
The only time I get a notification is when I send a test notification from firebase console using the token. @Dallas62

**Comment by Dallas62** [comment]
Hi @nero2009 
Since it's working with test-notification, this is not an issue with the library but probably the way you trigger your notification.
Since I don't have information to reproduce your case, I can't help.
Regards,

**Comment by nero2009** [comment]
Thanks @Dallas62 for the help
I will continue investigating

**Comment by sgtpsibin** [comment]
hi @nero2009, i'm having a same issue. Did you find out anything?
