### ISSUE TITLE
Token generated not working for iOS

### ISSUE THREAD

**Issue by Gabsys** [zo0r/react-native-push-notification#1889]
I've been trying to debug on why my iOS device is not receiving test notification sent from Firebase Console.

My latest finding was that the token generated with PushNotification - `onRegister:` wasn't working. 
I was able to receive notification when I used token generated by firebase messaging itself - `messaging().getToken()`. 

Does anyone faces the same issue?

**Comment by Dallas62** [comment]
Hi @Gabsys
Already answered.
The token on iOS is an APNS token, Firebase is not install with this library on iOS (or the RNC library).
Regards

**Comment by Gabsys** [comment]
Oh ok, thank you.
