### ISSUE TITLE
Add maintainers?

### ISSUE THREAD

**Issue by vikeri** [zo0r/react-native-push-notification#189]
This is obviously a very important React Native library and its popularity will probably increase as RN adoption rises. A suggestion is to add some additional maintainers to help with merging PR's and responding to issues.

**Comment by zo0r** [comment]
I'm open to add maintainers :wink:

@npomfret cc

**Comment by npomfret** [comment]
There are lots of outstanding pull requests here, I'm sure some of them have merit and I guess the rest just need closing.  If the current maintainers don't have time go through them then yeah, more maintainers are needed.
