### ISSUE TITLE
About getScheduledLocalNotifications() method why mixed order

### ISSUE THREAD

**Issue by Fatih5959** [zo0r/react-native-push-notification#1890]
# Question

Hi,

[PushNotification.getScheduledLocalNotifications(callback)](https://github.com/zo0r/react-native-push-notification#6-getscheduledlocalnotifications)
using this method gives me an array. But why does it give a mixed order ?

![imageQuestions](https://user-images.githubusercontent.com/79709414/109320194-ceffdb80-7860-11eb-877a-894da8dd5feb.PNG)

**Comment by Dallas62** [comment]
Hi @Fatih5959 
The ID doesn't mean it's the first issue to trigger.
Feel free to sort the notification based on your need (id, date, ...)
Regards,
