### ISSUE TITLE
About notification badge on Xiaomi devices.

### ISSUE THREAD

**Issue by MarcosWillianR** [zo0r/react-native-push-notification#1891]
# Question

Hey, i see on ShortcutBadger library has an additional step to set notification badge on Xiaomi devices, how can implement that?

Thanks.

**Comment by Dallas62** [comment]
Hi @MarcosWillianR 
You will probably found answers in issues.
https://github.com/zo0r/react-native-push-notification/issues?q=is%3Aissue+Shortcutbadger
or in this reporistory: https://github.com/leolin310148/ShortcutBadger
Regards,

**Comment by MarcosWillianR** [comment]
Thanks @Dallas62
