### ISSUE TITLE
Not receiving notifications on android versions < 10

### ISSUE THREAD

**Issue by redefiningtheweb** [zo0r/react-native-push-notification#1892]
Hi, I am currently facing an issue with the older versions of android ( below android 10 ) and remote notifications ( firebase ). On devices that are running below android 10, I am not receiving notifications however the token is generating. I have searched the issues already but could not find anything helpful. It will be great if someone can help. Thanks.

**Comment by Dallas62** [comment]
Hi @redefiningtheweb 
Please read "Channel Management" part if the readme.
Regards

**Comment by redefiningtheweb** [comment]
Thanks for the quick response, setting the firebase default channel worked.

**Comment by allindeveloper** [comment]
Hi @redefiningtheweb 
Could you please assist with a code snippet on how you were able to resolve this. i am facing a similar challenge
Thanks.
