### ISSUE TITLE
All of a sudden, sound and vibrate arent working when they were before...what changed?

### ISSUE THREAD

**Issue by jamesdmurphy51** [zo0r/react-native-push-notification#1893]
# Bug
All of a sudden, sound and vibrate arent working when they were before

## Environment info
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 6.95 GB / 15.89 GB
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 26, 28, 29
      Build Tools: 23.0.1, 26.0.1, 27.0.3, 28.0.3, 29.0.1, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: Not Found
  Languages:
    Java: 11.0.10 - /c/Program Files/AdoptOpenJDK/jdk-11.0.10.9-hotspot/bin/javac
    Python: 2.7.16 - /c/Python27/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: x.x.x
0.63.3

## Steps To Reproduce

Describe what you expected to happen:

1. Sound to play
2. Vibrate

## Reproducible sample code

```
export const showNotification = () => {
  PushNotification.localNotification({
    title: 'Timer Expired',
    message: 'Perhaps set your timer for another hour?',
    //playSound: true, // (optional) default: true
    soundName: 'sound.mp3',

    //android only properties
    channelId: 'myChannel',
    largeIcon: 'ic_notification',
    smallIcon: 'ic_notification',
    //vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
    vibration: 3000, //why not working?
    priority: 'high',

  });
```

**Comment by Dallas62** [comment]
Hi @jamesdmurphy51 
Not able to reproduce.
Please check your configuration and Channels.
Regards,

**Comment by jamesdmurphy51** [comment]
Hi - thats odd.

I didnt change anything and it was working 2 days ago.  Notification still fires but it no longer makes sound or vibrates....I didnt even upgrade any libraries.
Ironic thing is that a second thing changed....but for the positive!!!  Previously the notification icon was not showing and now it is.
Crazy world of React Native lol
________________________________

**Comment by kemicofa** [comment]
+1 getting the same issue.

**Comment by Dallas62** [comment]
Hi @kemicofa
As replied:
Please check your configuration and Channels.
Regards,
