### ISSUE TITLE
Android Channel Confusion

### ISSUE THREAD

**Issue by Rehubbard** [zo0r/react-native-push-notification#1895]
# Question

I am attempting to get basic remote notifications working on Android with FCM. No local notifications or anything extra, just remote push notifications from Firebase. I believe one of the issues I am facing is channels.

**What does my channel configuration need to be?**

The docs say: "If you want to use a different default channel for remote notification, refer to the documentation of Firebase" and shows this `AndroidManifest.xml` config:
`<meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id" />`

Is this what I need to add to my `AndroidManifest.xml`? If so, do I need to put anything in my `res/values/strings.xml`?

I've seen other things in the CHANGELOG and Github issues mentioning different config for channels, so I just wanted to confirm. I'm not creating any channels or anything. I just wanted to use notifications out of the box. Thanks in advance!

**Comment by Dallas62** [comment]
Hi @Rehubbard 

First of all, you MUST create a channel to receive notification:
https://github.com/zo0r/react-native-push-notification#channel-management-android
Without channel, Android Notification won't work.

Example:
```js
  PushNotification.createChannel(
    {
      channelId: "channel-id", // (required)
      channelName: "My channel", // (required)
      channelDescription: "A channel to categorise your notifications", // (optional) default: undefined.
      playSound: false, // (optional) default: true
      soundName: "default", // (optional) See `soundName` parameter of `localNotification` function
      importance: 4, // (optional) default: 4. Int value of the Android notification importance
      vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
    },
    (created) => console.log(`createChannel returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
  );
```

Then, you can assign the default channel inside your `AndroidManifest.xml`, using:
```xml
  <meta-data
      android:name="com.google.firebase.messaging.default_notification_channel_id"
      android:value="@string/default_notification_channel_id" />
```
**OR**
```xml
  <meta-data
      android:name="com.google.firebase.messaging.default_notification_channel_id"
      android:value="channel-id" />
```

If you use the first one, you will have to define the value inside `strings.xml`.

Regards,

**Comment by Rehubbard** [comment]
Thanks for the helpful response. This clears up alot of guesswork I was doing as I'm new to android channels. I appreciate it.

One more question, does the server side need to specify a channel id or anything?

Reading this [documentation here](https://firebase.google.com/docs/cloud-messaging/http-server-ref) seems like the default value in the AndroidManifest.xml will be used if nothing is specified for the channel on the server side. Does that sound right?

**Comment by Dallas62** [comment]
That means you can specify the channel id in the notification payload, if not this will use the default channel defined in the application (AndroidManifest).
If the channel doesn't exist, no notification appear.

**Comment by gazedash** [comment]
```
PushNotification.localNotification({
  /* Android Only Properties */
  channelId: "your-channel-id", // =======>(required) channelId, if the channel doesn't exist, it will be created with options passed above (importance, vibration, sound) <======. 
```

if this is not the case, I think readme should be updated

https://github.com/zo0r/react-native-push-notification#local-notifications

**Comment by Dallas62** [comment]
It's now updated
