### ISSUE TITLE
Issue with repeating notifications on iOS

### ISSUE THREAD

**Issue by twalkerjr22** [zo0r/react-native-push-notification#1898]
Im currently having issues with setting repeat notifications. Here is my code:

`var trigger = new Date();
  trigger.setDate(trigger.getDate()+1);
  trigger.setHours(7);
  trigger.setMinutes(0);
  trigger.setMilliseconds(0);
  PushNotification.localNotificationSchedule({
    message: "Your Daily Schedule is Ready.", // (required)
    date: trigger,
    allowWhileIdle: false, // (optional) set notification to work while on doze, default: false
    repeatType: "day", // (optional) Repeating interval. Check 'Repeating Notifications' section for more info.
  });`

It works on correctly the first time but the "repeat" doesn't seem to be working as the notifications dont work on the next days.

**Comment by Dallas62** [comment]
Hi @twalkerjr22 
Has replied in an answer issue where you said: "having same issue", this is not the right repository to report iOS issue.
Regards
