### ISSUE TITLE
Typescript error, 'title' doesn't exist on type 'ReceivedNotification`

### ISSUE THREAD

**Issue by rawatnaresh** [zo0r/react-native-push-notification#1899]
I'm trying to access the notification `title` received on the `onNotification` handler but it throws an error

![Screen Shot 2021-03-03 at 12 11 56](https://user-images.githubusercontent.com/29520305/109763085-a8072800-7c19-11eb-90dc-8c25f5be506b.png)

Although there's a `title` in the `notification` object

```js
    onNotification: function (notification) {
      console.log('Notification', notification);
      notification.finish(PushNotificationIOS.FetchResult.NoData);
    },
```

```js
// notification received
{
  "channelId":"fcm_fallback_notification_channel",
  "color":null,
  "data":{
    
  },
  "finish":[
    "Function finish"
  ],
  "foreground":true,
  "id":"-460472664",
  "message":"This is Message",
  "priority":"high",
  "sound":null,
  "tag":"campaign_collapse_key_5016357315119796141",
  "title":"This is Title",
  "userInteraction":false,
  "visibility":"private"
}
```
Also, the [Docs](https://github.com/zo0r/react-native-push-notification#handling-notifications) only specifies 4 fields whereas the data I'm getting is different

**Comment by Dallas62** [comment]
Hi @rawatnaresh 
There is no official type for this library.
Please refer to the documentation.
Regards,
