### ISSUE TITLE
[IOS] onRegister is not being called

### ISSUE THREAD

**Issue by osungjin** [zo0r/react-native-push-notification#190]
I'm using RN0.30.0 and react-native-push-notification 2.0.2.

If Running android called onRegister. But IOS doesn't call the onRegister.
So, I didn't get a token.

**Comment by yuvalsegev11** [comment]
@osungjin can you share with us the solution?

**Comment by Hitabis** [comment]
@osungjin Yes, please share the solution.
It is not working for me on iOS 10 and react-native 0.33.

**Comment by yuvalsegev11** [comment]
update: solution for me was to install google play services from the SDK manager
