### ISSUE TITLE
iOS repeatType - only "day"

### ISSUE THREAD

**Issue by daheeahn** [zo0r/react-native-push-notification#1901]
Why is ios repeatType only day left? I'm using minutes, but it suddenly disappears and I'm embarrassed.
I would appreciate it if you could make it again :)

react-native-push-notification: 7.2.1
@react-native-community/push-notification-ios: 1.8.0

**Comment by daheeahn** [comment]
https://github.com/react-native-push-notification-ios/push-notification-ios

Is it correct that it disappeared because it was removed from this library? Then it’s really sad

**Comment by Dallas62** [comment]
Hi @daheeahn 
Yes, this disappeared from the iOS library, only this option available:

> repeats : Sets notification to repeat daily. Must be used with fireDate.

Regards

**Comment by daheeahn** [comment]
Thanks.
