### ISSUE TITLE
Why not getting as much info as we can with getDeliveredNotifications on android

### ISSUE THREAD

**Issue by bennyscetbun** [zo0r/react-native-push-notification#1906]
Hi all,
I was wondering if there was a good reason for this:
https://github.com/zo0r/react-native-push-notification/blob/a9083c81ac668a26fcc8a112000d7563a02399a5/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L736

We could get much more information like the big_text for example. (i am sure that we could also get the "user_info")

So why aren't we getting them on android?

PS: it s not consistent with what getDeliveredNotifications returns in IOS anymore by the way.

**Comment by Dallas62** [comment]
Hi @bennyscetbun 
When this change was made, `userInfo` on Android wasn't available.
Now it's ok to be integrated.
PR are welcome, or I will take a look later 😉 
Regards,

**Comment by bennyscetbun** [comment]
Thanks for the quick answer.
If i do a pr and to avoid wasting time.
Do you prefer to stick to the facebook dataset or should we put as much data as we can? (Like when you create notification)

**Comment by Dallas62** [comment]
Oh wait, I was looking at the wrong function. I thought it was `getScheduledLocalNotifications `. 
I'm not sure if we can retrieve data of delivered notifications, didn't test.
Original implementation is #909
We can probably extract `userInfo` from extras, bu not sure there is more useful information.

**Comment by s-fletcher** [comment]
@Dallas62 regarding `getScheduledLocalNotifications` not returning `userInfo`, it seems to already do so. It's just not documented in the types or readme. 

https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L546

**Comment by litinskii** [comment]
+1 to add userInfo to getDeliveredNotifications

**Comment by McDreamy** [comment]
does it work for delivered local notification for getDeliveredNotifications in android?

**Comment by bennyscetbun** [comment]
Sadly on android we could get just a little bit more of information but not the all the userInfo like in IOs. I thought we would be able to do so. I was wrong.
I am closing the issue for now
