### ISSUE TITLE
Android Crash on Remote Notifications

### ISSUE THREAD

**Issue by mkaya93** [zo0r/react-native-push-notification#1907]
# Bug
I'm trying to use this library to handle remote notifications. It works on iOS without a problem but on Android when I'm getting a remote notification it's giving an error and application crashes. 

.MainApplication cannot be cast to com.facebook.react.ReactApplication
at com.dieam.reactnativepushnotification.modules.RNReceivedMessageHandler$1.run(RNReceivedMessageHandler.java:94)

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Memory: 17.34 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: ~0.61.4 => 0.61.5
```

Library version: 5.1.1

## Steps To Reproduce

1. Put application to the background
2. Send Remote notification

**Comment by Dallas62** [comment]
Hi @mkaya93 
Probably because your `MainApplication` is not a `ReactApplication` ? (just by reading the error message)
Like: https://github.com/zo0r/react-native-push-notification/blob/master/example/android/app/src/main/java/com/example/MainApplication.java#L14
Regards,

**Comment by mkaya93** [comment]
@Dallas62 It is ReactApplication.

**Comment by Dallas62** [comment]
You are probably right, I cannot reproduce your issues.
I'm just mentioning the error message which is:
`.MainApplication cannot be cast to com.facebook.react.ReactApplication`

Which means, `MainApplicaiton` is not an instance of `com.facebook.react.ReactApplication`.

Provide a reproducible project if you need more help.
Regards,
