### ISSUE TITLE
I couldn't run Push Notification

### ISSUE THREAD

**Issue by mahiraltinkaya** [zo0r/react-native-push-notification#1915]
# Question

I watched a few videos and followed the documentation carefully, but still couldn't get it to work. I know I was the wrong one. I don't know where I went wrong. I am sharing the steps I did below I would be grateful if you could help. I can buy tokens but localnotification doesn't work. There is only 1 button in my application and I did a clean installation.

"I am using RN.0.63.4 and Xiaomi Redmi 9 node pro physical device on adb connect

```
android/build.gradle
```
![image](https://user-images.githubusercontent.com/25014707/111610803-cad63680-87ec-11eb-9a60-7fd70528829a.png)

```
android/app/src/main/AndroidManifest.xml
```
![image](https://user-images.githubusercontent.com/25014707/111611092-2274a200-87ed-11eb-83c1-9660d4b32bed.png)
![image](https://user-images.githubusercontent.com/25014707/111611173-34eedb80-87ed-11eb-8f8b-bc5494f34c2a.png)
![image](https://user-images.githubusercontent.com/25014707/111611238-489a4200-87ed-11eb-9991-4513e6a4e227.png)

![image](https://user-images.githubusercontent.com/25014707/111611574-ac246f80-87ed-11eb-893e-8206a2722b1f.png)
![image](https://user-images.githubusercontent.com/25014707/111611748-d6762d00-87ed-11eb-873b-292497e842e0.png)

![image](https://user-images.githubusercontent.com/25014707/111612899-ffe38880-87ee-11eb-9e89-50df8862d4ca.png)

![image](https://user-images.githubusercontent.com/25014707/111612745-d4f93480-87ee-11eb-923c-fac463d2f5d9.png)
![image](https://user-images.githubusercontent.com/25014707/111612834-f0fcd600-87ee-11eb-9aad-346a09f76615.png)

**Comment by Dallas62** [comment]
Hi @mahiraltinkaya 

Please refer to the Readme.
To get notification on Android, you MUST create a channel.
https://github.com/zo0r/react-native-push-notification#channel-management-android

```js
PushNotification.localNotification({
  /* Android Only Properties */
  channelId: "your-channel-id", // (required) channelId, if the channel doesn't exist, it will be created with options passed above (importance, vibration, sound). Once the channel is created, the channel will not be update. Make sure your channelId is different if you change these options. If you have created a custom channel, it will apply options of the channel.
//... other options
});
```

Regards
