### ISSUE TITLE
Android 10 & 11 local notifications doesn't show

### ISSUE THREAD

**Issue by mocanSergiu666** [zo0r/react-native-push-notification#1917]
On emulators and physical devices with Android10+ the local notifications triggered with PushNotification.localNotification() don't show on the top of the screen, just go to the system tray. I also checked on emulator with Android 8 and it works fine.
Any ideas? :)
_____________________________________

package.json
================================
"react-native": "^0.63.4",
"react-native-push-notification": "^7.2.2",

AndroidManifest.xml
================================
.....
`<uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
  <permission
    android:name="${applicationId}.permission.C2D_MESSAGE"
    android:protectionLevel="signature" />
  <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
  <uses-permission android:name="android.permission.VIBRATE" />
  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.WAKE_LOCK" />`
.....
   `<meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_name"
      android:value="YOUR NOTIFICATION CHANNEL NAME"/>
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_channel_description"
      android:value="YOUR NOTIFICATION CHANNEL DESCRIPTION"/>
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_color"
      android:resource="@android:color/white"/>
    
    <receiver
      android:name="com.google.android.gms.gcm.GcmReceiver"
      android:exported="true"
      android:permission="com.google.android.c2dm.permission.SEND" >
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <category android:name="${applicationId}" />
      </intent-filter>
    </receiver>
    
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
      <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
      </intent-filter>
    </receiver>
    <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
    
    <service
      android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm"
      android:exported="false" >
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
      </intent-filter>
    </service>
    
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground"
      android:value="true" />
    <meta-data android:name="com.dieam.reactnativepushnotification.channel_create_default"
      android:value="true" />
    <meta-data
      android:name="com.google.firebase.messaging.default_notification_channel_id"
      android:value="push-notifications-channel" />
    <receiver
      android:name="com.google.android.gms.gcm.GcmReceiver"
      android:exported="true"
      android:permission="com.google.android.c2dm.permission.SEND" >
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <category android:name="com.simpals.studii" />
      </intent-filter>
    </receiver>
    <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService" />
    <service
      android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm"
      android:exported="false" >
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
      </intent-filter>
    </service>
    <service
      android:name=".java.MyFirebaseMessagingService"
      android:exported="false">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>`

settings.gradle
================================
.....
include ':react-native-push-notification'
project(':react-native-push-notification').projectDir = file('../node_modules/react-native-push-notification/android')
include ':app'

Configuration
================================
import PushNotification from 'react-native-push-notification';
import {registerToPushNotifications} from '..';

export const configureNotifications = () => {
  PushNotification.configure({
    onNotification: notification => {
      console.log('onNotification:', notification);
    },
    onAction: notification => {
      console.log('onAction:', notification);
    },
    permissions: {
      alert: true,
      badge: true,
      sound: true,
    },
    senderID: 'bla-bla-bla',
    popInitialNotification: true,
    requestPermissions: true,
  });

  PushNotification.createChannel({
    channelId: 'push-notifications-channel',
    channelName: 'Push notifications channel',
    channelDescription: 'Push notifications channel',
    playSound: true,
    soundName: 'default',
    importance: 4,
    vibrate: true,
  });
};

Trigger
================================
const triggerNotification = () => {
    PushNotification.localNotification({
      channelId: 'push-notifications-channel',
      channelName: 'Push notifications channel',
      foreground: true,
      ignoreInForeground: false,
      invokeApp: true,
      visibility: 'private',
      priority: 'high',
      vibrate: true,
      vibration: 500,
      playSound: true,
      soundName: 'default',
      autoCancel: true,
      title: 'Title',
      message: 'Message',
      bigText: 'Big text',
      subText: 'Sub text',
    });
  };

**Comment by Dallas62** [comment]
Hi @mocanSergiu666 
Please refer to the Channel Management, in the README.
https://github.com/zo0r/react-native-push-notification#channel-management-android
**NOTE: Without channel, notifications don't work**
Regards

**Comment by mocanSergiu666** [comment]
> Hi @mocanSergiu666
> Please refer to the Channel Management, in the README.
> https://github.com/zo0r/react-native-push-notification#channel-management-android
> **NOTE: Without channel, notifications don't work**
> Regards

Hi, I just want to mention that the notification doesn't show on the top of the screen, but in general it appears in the system tray. so it means that it goes through the channel and the problem is not in the channel. Maybe my configuration isn't quite correct.....

**Comment by Dallas62** [comment]
I think there is a lot of deprecated configuration in you Android Manifest, check the CHANGELOG (v6) to clean it.
Also `senderID` isn't need in `.configure`

**Comment by mocanSergiu666** [comment]
I changed the configuration to look like this:
_______________________________________

.....
`<uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.VIBRATE" />
  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />`
.....
`<receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
      <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
        <action android:name="android.intent.action.QUICKBOOT_POWERON" />
        <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
      </intent-filter>
    </receiver>
    <service
      android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
      android:exported="false" >
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground"
      android:value="false" />
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_color"
      android:resource="@android:color/white"/>`

but the notification still doesn't show up, it just vibrates and goes to system tray :(
I took the configuration from the example on github [(here)](https://github.com/zo0r/react-native-push-notification/tree/master/example) Is that example outdated?

**Comment by Dallas62** [comment]
Hi @mocanSergiu666 
As mentioned before,
Refer to the Channel Management, in the README.
https://github.com/zo0r/react-native-push-notification#channel-management-android
**NOTE: Without channel, notifications don't work**

I don't see any creation of a channel in your code.

Regards

**Comment by Dallas62** [comment]
You can recreate the channel by changing the `channelId`.

It's look like a channel issue. If you misconfigured your channel the first time, this can occure.
https://github.com/zo0r/react-native-push-notification#channel-management-android
> Once the channel is created, the channel cannot be update

**Comment by tgreco** [comment]
I am very confused on the channel usage too. 
Can someone provide more information on mocanSergiu666's question?

**Comment by Dallas62** [comment]
Same answer

**Comment by moh3n9595** [comment]
It's not about the channel! the channel exists with high importance and everything work in lower android versions
