### ISSUE TITLE
cancelLocalNotifications not working

### ISSUE THREAD

**Issue by davidvajda** [zo0r/react-native-push-notification#1918]
Hi, i'm new to RN and I'm trying to do simple reminder app. I'm not able to cancel notification from its actions. This is how notification is created:

```
PushNotification.localNotificationSchedule({
  id: id.toString(),
  number: 0,
  userInfo: {
    id: id.toString(),
  },
  channelId: 'channel-@' + id,
  title: title,
  message: text,
  ongoing: ongoing,
  date: new Date(dateFrom),
  allowWhileIdle: true,
  actions: ['Complete'],
  playSound: true,
  invokeApp: false,
  autoCancel: false,
  data: {
    id: id.toString(),
  },
});
```
id returns simple integer based on previous notifications - 1 or 2 or 3 etc.

I have one 'Complete' action with this code in index.js

```
onAction: function (notification) {
    finishNote(notification.data.id)
  },
```
and with pushing the 'complete'button i'm calling this function from external file:

```
export default function finishNote(notificationId) {
    PushNotification.cancelLocalNotifications({id: notificationId.toString()})
}
```
After pushing the 'complete' button nothing happens, i've tried

PushNotification.cancelAllLocalNotifications()

And this works, however, I need to cancel specific ones.

Am I doing something wrong? Older issues with parseInt did not help.

**Comment by davidvajda** [comment]
I changed it according to previous issues: 
    ```
PushNotification.localNotification({
      id: parseInt(Math.random()*1000000000, 10).toString(),
      channelId: 'channel-@' + id,
      title: title,
      message: text,
      ongoing: ongoing,
      allowWhileIdle: true,
      actions: ['Complete'],
      playSound: false,
      invokeApp: false,
      autoCancel: false,
    });
```
and canceling with:
```
export default function finishNote(notificationId) {
    PushNotification.cancelLocalNotifications({id: parseInt("845715191", 10).toString()})
}
```
Still not working

**Comment by davidvajda** [comment]
Alright I was able to delete the notification with deleting the channel instead.

**Comment by Dallas62** [comment]
Hi,

Delete the channel is not the solution. Did you try with a fixed id?

Also, do you want to remove a delivered notification or cancel a scheduled notification ?

There is a specific method for this:

https://github.com/zo0r/react-native-push-notification#5-removedeliverednotifications

Regards,

**Comment by SeveHo** [comment]
Hi @Dallas62 I have the same problem with **scheduled** notifications. Do you mean that I have to use `removeDeliveredNotifications` for them even though they where not delivered yet?
