### ISSUE TITLE
Support FCM and other platform?

### ISSUE THREAD

**Issue by bns-frankpoon** [zo0r/react-native-push-notification#192]
I'm new to react native without any mobile developing experience. The plugin and usage are really useful. However, google is now upgrading from gcm to fcm. Will this plugin support it later? At the same time, is it possible to support other push notification service, such as aws push notification? Thanks

**Comment by jrmcdona** [comment]
@bns-frankpoon  were you able to figure this out?   I am look at using this with Azure notification hub.
Thanks

**Comment by sibelius** [comment]
@bns-frankpoon use https://github.com/evollu/react-native-fcm for FCM

**Comment by bns-frankpoon** [comment]
How about aws push notification ?

**Comment by milkers** [comment]
@bns-frankpoon , using aws sns [seems fine](https://github.com/zo0r/react-native-push-notification/issues/290#issuecomment-283325483) for me now. You can use this module but for android please create a new project using firebase console and use the old-style server api key generated for you.
