### ISSUE TITLE
group and groupSummary aren't working

### ISSUE THREAD

**Issue by orcuntuna** [zo0r/react-native-push-notification#1922]
# Bug

group and groupSummary properties are not working. I work on messaging application and I need group messages on the notification. 

`PushNotification.localNotification({
            ...data,
            title: notification.title,
            message: notification.body,
            group: 'com.myapp.messages',
            groupSummary: true,
});`

## Environment info

`react-native info` output:

```bash
 System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 1.54 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.5 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 25, 26, 28, 29, 30
      Build Tools: 25.0.3, 26.0.2, 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.3/12C33 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: 7.2.3

**Comment by Dallas62** [comment]
Hi @orcuntuna 
This issue has been answered in issues, please search before posting.
https://github.com/zo0r/react-native-push-notification/issues/1527#issuecomment-693385260
Also, version 1.6.1, looks pretty old.
Regards,

**Comment by orcuntuna** [comment]
> Hi @orcuntuna
> This issue has been answered in issues, please search before posting.
> [#1527 (comment)](https://github.com/zo0r/react-native-push-notification/issues/1527#issuecomment-693385260)
> Also, version 1.6.1, looks pretty old.
> Regards,

Sorry, my library version ios 7.2.3. I tried #1527 but not working. Already android group 5+ message. I don't need. I found a picture on Google.

https://i.stack.imgur.com/MZ5lA.png

**Comment by Dallas62** [comment]
You need to create 5 notifications + one group summary notification.
Like the exemple here: https://github.com/zo0r/react-native-push-notification/issues/1527#issuecomment-693385260
Where the modulo is the groupSummary notification.

https://developer.android.com/training/notify-user/group

**Comment by orcuntuna** [comment]
> You need to create 5 notifications + one group summary notification.
> Like the exemple here: [#1527 (comment)](https://github.com/zo0r/react-native-push-notification/issues/1527#issuecomment-693385260)
> Where the modulo is the groupSummary notification.
> 
> https://developer.android.com/training/notify-user/group

How can make it like this? Is this not a group feature?

https://i.stack.imgur.com/MZ5lA.png

**Comment by Dallas62** [comment]
```js
PushNotification.localNotification({      
      title: 'Local Notification',
      message: 'My Notification Message',
      group: 'com.exemple.MY_GROUP',
      groupSummary: false
    });
PushNotification.localNotification({      
      title: 'Local Notification',
      message: 'My Notification Message',
      group: 'com.exemple.MY_GROUP',
      groupSummary: false
    });
PushNotification.localNotification({      
      title: 'Local Notification',
      message: 'My Notification Message',
      group: 'com.exemple.MY_GROUP',
      groupSummary: false
    });
PushNotification.localNotification({      
      title: 'Local Notification',
      message: 'My Notification Message',
      group: 'com.exemple.MY_GROUP',
      groupSummary: false
    });
PushNotification.localNotification({      
      title: 'Local Notification',
      message: 'My Notification Message',
      group: 'com.exemple.MY_GROUP',
      groupSummary: false
    });
PushNotification.localNotification({      
      title:  'Grouped notification', // (optional)
      message:  'My Grouped notification Message\nLine 1\nLine 2\n...', // (required)
      group: 'com.exemple.MY_GROUP',
      groupSummary: true
    });
```
