### ISSUE TITLE
[iOS] App is in killed (swipe up) state, recieved remote notification and on useEffect calling popInitialNotification unable to recieve notification id and unable to finish

### ISSUE THREAD

**Issue by pktippa** [zo0r/react-native-push-notification#1932]
# Bug

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 67.60 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.0 => 0.64.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.1.3

## Steps To Reproduce

0. Push notification service using AWS SNS -> APNS_SANDBOX
1. Run app using `./node_modules/.bin/react-native run-ios`
2. Killed app by swiping up.
3. Triggered a Push notification for iOS APNS_SANDBOX using AWS SNS Javascript SDK.
4. Received a notification and clicked on notification.
5. Able to recieve notification on useEffect of Root React component.

```js
useEffect(() => {
    PushNotification.popInitialNotification((notification) => {
       if (notification) {
          // do something with notification
           notification.finish(PushNotificationIOS.FetchResult.NoData);
        }
    });
});
...
6. If I put the app in the background and bring it to the foreground the `popInitialNotification` callback with `notification` is available again.!

Describe what you expected to happen:

1. Once calling `finish` expected not to trigger the callback for  `popInitialNotification` with same notification

## Reproducible sample code

<!--
 Please add minimal runnable repro as explained above so that the bug can be tested in isolation.
 Use the example project to reproduce it.
-->

**Comment by Dallas62** [comment]
Hi @pktippa 
The initial notification is the one that start the application.
Since the first one opened the application, it will be the initial notification until the application is killed.

Please use `onNotification` instead.
Regards

**Comment by pktippa** [comment]
@Dallas62 since I am facing the issue of not able to reach `onNotification` for an app killed state same as https://github.com/zo0r/react-native-push-notification/issues/1677 

Could you please help me with a working example for receiving and handling notification for React Native iOS on app killed state.?

**Comment by Dallas62** [comment]
As mentioned on the linked issue:
Please refer to the iOS library for this:
https://github.com/react-native-community/push-notification-ios

This depend on what you defined in AppDelegate.
Regards
