### ISSUE TITLE
Is the cancelLocalNotification({id: id}) applicable in ScheduledNotification ?  

### ISSUE THREAD

**Issue by abhineetsharmathegreat** [zo0r/react-native-push-notification#1933]
# Question
Is the cancelLocalNotification method only available for LocalNotification, because in ScheduledNotification there is no such type of method to cancel a particular scheduled notification with the help of its id. Also, is there some sort of way to edit the properties of a notification. Thank You for Your Kind Help!

**Comment by Dallas62** [comment]
Hi @abhineetsharmathegreat 
Yes, it works for scheduled notifications.
Regards

**Comment by abhineetsharmathegreat** [comment]
Thanks @Dallas62 , is there some way to edit the properties of a scheduled notification or we have to cancel the first and then again schedule a notification with the edited properties.
Thanks

**Comment by Dallas62** [comment]
Hi @abhineetsharmathegreat 
You can reuse the same id to replace a notification.
This should avoid delete then recreate.
Regards
