### ISSUE TITLE
remote notifications not received after app killed

### ISSUE THREAD

**Issue by MoronovArt** [zo0r/react-native-push-notification#1936]
Hi, all!!!
Notifications come well if the application is open or minimized, but if it is killed then they stop coming, and come only after opening the application.
I need your help @Dallas62

**Comment by Dallas62** [comment]
Hi @MoronovArt 
Please search in issue history.
Answered many times.
Regards.

**Comment by MoronovArt** [comment]
I can't find a solution, can you help me? @Dallas62

**Comment by Dallas62** [comment]
Create a channel, refer to the readme.

**Comment by MoronovArt** [comment]
I created a channel and I use it to send messages.

**Comment by MoronovArt** [comment]
Messages come to the device if the application is minimized or open. This is the release mode on the device. But if I kill the application they stop coming, and only come after restarting. @Dallas62

**Comment by Dallas62** [comment]
As you may notice, without filling the issue template and provide a reproducible exemple.
I can't help you more.
