### ISSUE TITLE
How to avoid infinite loop when localNotification inside onNotification

### ISSUE THREAD

**Issue by AlexHodovas** [zo0r/react-native-push-notification#1937]
Hi 

Sorry for asking a lot of questions.

But I do not understand 
how to overcome an infinite loop in this situation.

```
onNotification: function (notification) {
  if (notification) {

    if (notification.foreground && IS_IOS) {
        PushNotification.localNotification({
          title: "title",
          message: "message",
          id: 0,
        });
    }

  }

  if (IS_IOS) notification.finish(PushNotificationIOS.FetchResult.NoData);
},

```
The documentations says 
```
You can overcome this by marking local notifications' data.
 ```
 but how "marking local notifications' data"
 can anybody send some code 
 or change my
 
 Thanks

**Comment by Dallas62** [comment]
Hi @AlexHodovas
Please refer to the readme:
https://github.com/zo0r/react-native-push-notification#handling-notifications
```json
{
    foreground: false, // BOOLEAN: If the notification was received in foreground or not
    userInteraction: false, // BOOLEAN: If the notification was opened by the user from the notification area or not
    message: 'My Notification Message', // STRING: The notification message
    data: {}, // OBJECT: The push data or the defined userInfo in local notifications
}
```

**Comment by kyawthetkt** [comment]
For my issue,this snippet solved it as stated here https://github.com/zo0r/react-native-push-notification/issues/445#issuecomment-306389575

> if ( !notification.userInteraction ) {
>      PushNotification.localNotification({
>           title: "title",
>           message: "message",
>           id: 0,
>         });
>   }
