### ISSUE TITLE
Is there a limit on the number of sounds that we can use in Schedule Notification

### ISSUE THREAD

**Issue by abhineetsharmathegreat** [zo0r/react-native-push-notification#1938]
# Question
I have 5 sounds in my res/raw folder and I am playing the sound according to user's choice. Is there a limit on it because when I am running my app it only plays the first sound.

- arabic.mp3
- french.mp3
- english.mp3
- german.mp3
- spanish.mp3

and my code is like this: 
`this.notif.scheduleNotification(this.state.count, this.state.language, this.state.date, this.state.name)`

I am passing french.mp3 in place of this.state.language then also it plays the first sound that is arabic.mp3.

Any help is most welcomed.
Regards

**Comment by Dallas62** [comment]
Hi @abhineetsharmathegreat 
There is only one sound by channel.
Please refer to the channel management part of the Readme.

**Comment by abhineetsharmathegreat** [comment]
Thanks @Dallas62 Very Much For Your Kind Cooperation and Help
