### ISSUE TITLE
Is there a way to execute a piece of code in the background when a scheduledNotification pops up on the phone?

### ISSUE THREAD

**Issue by abhineetsharmathegreat** [zo0r/react-native-push-notification#1945]
# Question

I am using this library to pop up a scheduledNotification and I want to execute a piece of code when the notification pops up on the device. Is there any way to do it? Here is what I want to do:

- Show a scheduledNotification to the user.
- Just when the notification pops up I want to execute this code:
```
Tts.speak('You have a notification');
```

- Note: (I don't want it to be executed when the user clicks the notification. I want to automatically execute this code regardless of any actions).

**Thanks Very Much for your kind Help and Cooperation.**

**Comment by Dallas62** [comment]
Hi @abhineetsharmathegreat,
This question has been already answered.
Not possible with local notifications, and logic should not be based on notification.
If the user disable notification or power saving, logic is not working.
Regards
