### ISSUE TITLE
onNotificaiton method get fire when the app is in background but notification NOT coming in notification list.

### ISSUE THREAD

**Issue by imsaurabhdixit** [zo0r/react-native-push-notification#1949]
In my case notification is coming from connectycube and even my onNotificaiton method get fire when the app is in background but notification didn't popup and not coming in notification list.
This is what i am getting in onNotification:
{
data:
badge: "1"
dialog_id: "60574552ca8bf468829098f5"
message: "You have 4 new messages"
user_id: "3791768"
proto: Object
finish: ƒ finish()
foreground: false
id: "-414371205"
userInteraction: false
}

**Comment by Dallas62** [comment]
Hi @imsaurabhdixit 
We are not supporting notification from multiple providers.
Feel free to bind data to the corresponding method of this library or ask to the provider to create/complete a SDK.
Regards,
