### ISSUE TITLE
PushNotification.localNotification not working on ios10

### ISSUE THREAD

**Issue by sibelius** [zo0r/react-native-push-notification#195]

**Comment by npomfret** [comment]
Can you provide more detail?

**Comment by pontusab** [comment]
@sibelius It works for me in iOS 10 with `"react-native-push-notification": "2.1.0"`

**Comment by sibelius** [comment]
I'll try to update it, I'm using 2.0.2 tks

**Comment by sibelius** [comment]
This code do not show a local notification on ios 10, I'm using xcode 8, RN33, RNPN: 2.1.0

```js
PushNotification.localNotification({
        message: "my local push",
      });
```

it works fine on android

**Comment by npomfret** [comment]
Are there any error messages?

**Comment by sibelius** [comment]
There are no error, this happens when my is in foreground, could this be the problem?

**Comment by edencakir** [comment]
Same here, any solutions?

**Comment by edencakir** [comment]
OK, for my case, the problem was not setting header search path _RECURSIVE_

**Comment by npomfret** [comment]
I'm not having any issues with iOS 10, RN 0.33 and RNPN 2.1.1 so far.

**Comment by steve-gray** [comment]
I've got the header set to recursive, but local notifications not working. Scheduled notifications work fine though. Very odd.....

**Comment by edencakir** [comment]
@steve-gray did you set listeners for 'notification' ?

**Comment by sibelius** [comment]
@edencakir which listeners are u talking about? Could u post some code?

**Comment by edencakir** [comment]
In component will mount: `PushNotificationIOS.addEventListener('localNotification', this._onLocalNotification);`

class method: 
`_onLocalNotification(notification){
    console.log(notification);
    AlertIOS.alert(
      'Time to practice!',
      notification.getMessage(),
      [{
        text: 'Dismiss',
        onPress: null,
      }]
    );
  }`

**Comment by npomfret** [comment]
You are using PushNotificationIOS?  That's all _wrapped_ by this project, you shouldn't need to use it directly.

**Comment by edencakir** [comment]
@npomfret Ah yes I know, sorry for misleading, that was for testing React Native docs notifications. Developers should follow Usage section of Readme.md document. Thanks for the heads up!

**Comment by Brockify** [comment]
Any solutions to this?

**Comment by Brockify** [comment]
Displays perfectly on ios 9.3, but doesn't display on ios 10.0

**Comment by sibelius** [comment]
this could help this package as well: https://github.com/evollu/react-native-fcm/issues/117#issue-178342730

**Comment by npomfret** [comment]
@Brockify can you please give as much detail as possible.  I can confirm that this project works on iOS 10 as well as 9, but there's are so many places it could go wrong it's difficult to diagnose issues without detail.

The most common problems are:

 * it's not linked correctly - the RCTPushNotification project is missing from Xcode, or the binary isn't linked.
 * the capabilities aren't set up correctly in Xcode
 * the remote push notifications being sent aren't in the correct format
 * it doesn't work at all in an iOS simulator, you have to test on physical devices

**Comment by kencana-voilaah** [comment]
encountering the same issue on physical device, put a log on didReceiveLocalNotification, i can see the notification. there is no error thrown, but still can't see the notification on the device. works great on android though. still trying to find out the solution for this.

set the capabilities accordingly as well.

**Comment by kencana-voilaah** [comment]
Ah, please ignore me. I just read another thread that the notification in ios will only be shown when it's running at foreground. Was expecting it to behave the same way as android. Sorry for the false alarm

**Comment by npomfret** [comment]
@sibelius have you resolved your issue?  Can we close this?

**Comment by sibelius** [comment]
yep

**Comment by dwilt** [comment]
I'm having this issue currently. I am trying to fire a local notification and I see can that `onNotification` is being called and the notification data is being logged to the console via:
```js
onNotification: notification => {
    console.log('NOTIFICATION:', notification);
},
```
but no actual notification is fired. This happens both when the app is foregrounded and backgrounded. And actually, the console doesn't log until I come back into the app because (I'm assuming) the js thread is paused while in the background. Any thoughts?

**Comment by felangga** [comment]
same problem :((

**Comment by Swapnilchavan18** [comment]
anybody got solution?

**Comment by varungupta85** [comment]
@Swapnilchavan18 @felangga I think different people have had different issues in the code due to which the notification were not showing up on the phone. Unless you share more information about your specific use case, how you are scheduling the notification, how have you tried to debug the problem, are you seeing any error logs etc., I doubt if anyone can help resolve the problem.

**Comment by Swapnilchavan18** [comment]
Oh sorry it worked when app is in background but did not worked when app is in foreground.

**Comment by varungupta85** [comment]
You will not see a notification if the app is in the foreground on iOS. That is expected behaviour.

**Comment by Swapnilchavan18** [comment]
ok Thanks. @varungupta85

**Comment by narek11** [comment]
same thing

**Comment by delia-m** [comment]
@varungupta85 Could you please attach some info about this? 
(link or something.. I would like to see what expected behaviour in ios)
