### ISSUE TITLE
Type definitions are missing fields

### ISSUE THREAD

**Issue by mariovillamizar** [zo0r/react-native-push-notification#1953]
I'm using typescript and I noticed that some definitions are not complete. For example, ReceivedNotification is missing the field title, and PushNotificationPermissions is missing fields authorizationStatus and lockScreen.

**Comment by Dallas62** [comment]
Hi @mariovillamizar 
Already answered, this repository doesn't include types and I'm not the maintainer of theses types.
Feel free to make a PR on the right repository.
Regards,
