### ISSUE TITLE
No banner shows up on Android even see the payload in the log

### ISSUE THREAD

**Issue by selfcreator** [zo0r/react-native-push-notification#1958]
Could see this in console:
```
NotificationHandler: {"data": {"message": "Sample message for Android endpoints"}, "finish": [Function finish], "foreground": true, "id": "-306621741", "userInteraction": false}
```
But no banner when the app is in the background on Android.
Does anyone know why?

**Comment by selfcreator** [comment]
@Dallas62 any insights from you?

**Comment by Dallas62** [comment]
Hi,
Yiu are sending data-only notification, so there is no "banner".
Regards

**Comment by selfcreator** [comment]
> Hi,
> You are sending data-only notification, so there is no "banner".
> Regards

So how can I send noisy notification?

**Comment by Dallas62** [comment]
Please refer to the FireBase notification

**Comment by selfcreator** [comment]
Thanks @Dallas62, I checked the documentation about the firebase notification, indeed it was a data notification...
For anyone may encounter this in the future, please refer to: https://firebase.google.com/docs/cloud-messaging/send-message#notification-message
BTW, I used AWS SNS for testing the android push notification, and the default data template doesn't work well...
