### ISSUE TITLE
Push Notification on Release

### ISSUE THREAD

**Issue by areebshakeel** [zo0r/react-native-push-notification#1963]
Push Notifications not showing on release Build Android and iOS both

**Comment by Dallas62** [comment]
Hi,
Please search in issue history.
Regards

**Comment by areebshakeel** [comment]
> Hi,
> Please search in issue history.
> Regards

where i can see the search history

**Comment by Dallas62** [comment]
Here:
https://github.com/zo0r/react-native-push-notification/issues
