### ISSUE TITLE
[Android] Scheduled notifications delayed 

### ISSUE THREAD

**Issue by samouds** [zo0r/react-native-push-notification#1964]
Hello,

Some of our android users receive the scheduled local notification like 45 minutes later. iOS works great in the other hand.

Don't know why, if someone has any idea please.

**Comment by Dallas62** [comment]
Hi @samouds 

Please take a look to pinned issues, it's the same case. Battery Saver can affect scheduled behavior.

Regards,

**Comment by samouds** [comment]
Thanks @Dallas62 

The battery saver is disabled and still have the same problem

**Comment by Dallas62** [comment]
Without more information, I can't investigate.
Not reproducible on my Android phone or simulator.

Android/Manufacturers have many protections to kill application / background job, due to a lot of abuse in apps.

**Comment by Dallas62** [comment]
If you need precision, I suggest you to implement notification on server-side, it's probably the only way to make it works with precision.
