### ISSUE TITLE
Update channel sound/vibration

### ISSUE THREAD

**Issue by Srijita-Basak** [zo0r/react-native-push-notification#1966]
# Question
Is it possible to update sound and vibration after a channel is already created? I can see it's working the first time but after the channel is created unable to update the sound/vibration again. Is there a way out so that the channel updates the sound/vibration based on  playSound/vibrate set to true/false in local notification?

**Comment by Dallas62** [comment]
Hi @Srijita-Basak
The answer is in the Readme, and is: No.
Once created, it's not possible to update this parameter.
Regards
