### ISSUE TITLE
No push notification banner on Android when App is in the foreground

### ISSUE THREAD

**Issue by potatoengineer** [zo0r/react-native-push-notification#1968]
# Question
I am getting notifications but it stays in the drawer as a dot but I would like to get the full banner even when the app is in the foreground. Is there a way to do this?

```
        if (notification.foreground) {
          PushNotification.localNotification({
            id: notification.id
            title: notification.title,
            message: notification.message,
          });
        }
```

**Comment by Dallas62** [comment]
Hi @potatoengineer
Please search in issue history, already answered a lot.
