### ISSUE TITLE
Cancelling scheduled notification

### ISSUE THREAD

**Issue by abeikverdi** [zo0r/react-native-push-notification#197]
I have a `PushNotification.localNotificationSchedule` thats scheduled for a notification some time in future. How can I cancel that?

**Comment by vikeri** [comment]
It's being worked on in this PR: https://github.com/zo0r/react-native-push-notification/pull/172

**Comment by npomfret** [comment]
@abeikverdi  I've committed to master - would you like to give it a test?

**Comment by vikeri** [comment]
@npomfret I can confirm that it works for me

**Comment by npomfret** [comment]
Thanks

**Comment by npomfret** [comment]
@zo0r i think master is good for an npm release

**Comment by zo0r** [comment]
@npomfret just pushed it! **2.1.1**

Thank you for all your collaboration!

**Comment by npomfret** [comment]
Some docs are still missing but we'll get them updated soon.

**Comment by abeikverdi** [comment]
It works perfectly. Thanks for the quick update.
Cheers!
