### ISSUE TITLE
notification UserInteraction is not working in android 

### ISSUE THREAD

**Issue by prasanthvenkatachalam** [zo0r/react-native-push-notification#1976]
In android if i tap on notification , it just opens the app. I cant able to get notification.userInteraction. its not listening . In IOS i am getting true or false response when i tap the notification but not in android. Help needed for handling user Interaction in Android

**PushNotification.configure({
  onRegister: function (token) {
    console.log("TOKEN:", token);
  },
 
  onNotification: function (notification) {
    console.log("NOTIFICATION:", notification);
    if (notification.data.user_id && id == 0) {
      id = notification.data.user_id;
    }

    if (notification.userInteraction) {
      if (notification.title) {
        console.log("[notification.userInteraction] ");
        let link = "test://chat/" + `${id}`;
        Linking.openURL(link);
        id = 0;
      }
    }

    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },**

**Comment by Dallas62** [comment]
Hi,

Search for splashscreen in issue history.

Regards

**Comment by prasanthvenkatachalam** [comment]
Thanks, It worked

**Comment by prasanthvenkatachalam** [comment]
Solution :  

#3964

change in SplashActivity.java  
public class SplashActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);

        Intent intent = new Intent(this, MainActivity.class);
        intent.putExtras(getIntent().getExtras()); <----------------------------added this line in my project 
        startActivity(intent);
        finish();
    }
}

**Comment by Yandamuri** [comment]
@prasanthvenkatachalam I did changes as you mentioned. But still app is not reloading when tapped on notification. Notification just closes when tapped.

Same thing is happening in iOS as well. 

Can you please let me know what am I missing here?
