### ISSUE TITLE
Device Token incorrect with APNs

### ISSUE THREAD

**Issue by linhtv97** [zo0r/react-native-push-notification#1977]
# Bug

## Environment info

`react-native info` output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 78.14 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 24, 25, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 4.2
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.14.0 => 16.14.0 
    react-native: ^0.63.3 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

After register, I have a device Token that is an APNs token  but when using I have error `{"reason": "BadDeviceToken"}`

Command: 
`curl -v \ -d '{"aps":{"alert":"message","badge":42}}' \ -H "apns-topic: com.echopf.app" \ -H "apns-priority: 10" \ --http2 \ --cert-type P12 --cert Certificates2.p12 \ https://api.development.push.apple.com/3/device/48c9b35cf91b360052bbc8a55b803ce420993e0af57893f94fb9806de4dbd3d9`

Result form api
`https://api.development.push.apple.com/3/device/48c9b35cf91b360052bbc8a55b803ce420993e0af57893f94fb9806de4dbd3d9
*   Trying 17.188.138.71...
* TCP_NODELAY set
* Connected to api.development.push.apple.com (17.188.138.71) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=api.development.push.apple.com; OU=management:idms.group.533599; O=Apple Inc.; ST=California; C=US
*  start date: Feb  8 21:41:22 2021 GMT
*  expire date: Mar 10 21:41:22 2022 GMT
*  subjectAltName: host "api.development.push.apple.com" matched cert's "api.development.push.apple.com"
*  issuer: CN=Apple Public Server RSA CA 12 - G1; O=Apple Inc.; ST=California; C=US
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fe1ed80c400)
> POST /3/device/48c9b35cf91b360052bbc8a55b803ce420993e0af57893f94fb9806de4dbd3d9 HTTP/2
> Host: api.development.push.apple.com
> User-Agent: curl/7.64.1
> Accept: */*
> apns-topic: com.echopf.app
> apns-priority: 10
> Content-Length: 38
> Content-Type: application/x-www-form-urlencoded
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 1000)!
* We are completely uploaded and fine
< HTTP/2 400 
< apns-id: 10BEA640-6F78-272F-8F61-CB72C86BC644
< 
* Connection #0 to host api.development.push.apple.com left intact
{"reason":"BadDeviceToken"}* Closing connection 0`

**Comment by Dallas62** [comment]
Hi @linhtv97 
I suggest you to recheck your configuration and look at the iOS repository.
Regards
