### ISSUE TITLE
Why is GCM Sender ID marked as optional? 

### ISSUE THREAD

**Issue by sattaman** [zo0r/react-native-push-notification#198]
In case anyone else has issues, the senderID does seem to be required for android push notifications. Not sure why it is marked as optional? 

```
// ANDROID ONLY: (optional) GCM Sender ID.
senderID: "YOUR GCM SENDER ID",
```

**Comment by zo0r** [comment]
Sometimes you only want to use **local notifications**. if you want remote push notifications on android you must to enter your **Sender ID**

**Comment by npomfret** [comment]
I'll adjust the docs, agree that its not obvious.
