### ISSUE TITLE
Can i use localNotification without Firebase?

### ISSUE THREAD

**Issue by kea0811** [zo0r/react-native-push-notification#1982]
# Question
Can i use localNotification without Firebase?

**Comment by garrettmaring** [comment]
And what about `localNotificationSchedule`? Even when not using remote notifications (just local scheduled), I get a **Default FIrebaseApp is not initialized in this...** error

**Comment by Dallas62** [comment]
Please read the Readme, especially the `.configure()` part fully.
Regards
