### ISSUE TITLE
Suddently I got this error "cannot find symbol import com.google.firebase.iid.FirebaseInstanceId;" in RNPushNotification.java file

### ISSUE THREAD

**Issue by endlesstech** [zo0r/react-native-push-notification#1984]
# Bug

## Environment info

`react-native info` output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by m4tkv** [comment]
+

**Comment by kea0811** [comment]
are you trying to use it without firebase?

**Comment by vlsimctco** [comment]
Duplicate of https://github.com/zo0r/react-native-push-notification/issues/1979

**Comment by endlesstech** [comment]
I using firebase. Do I need to install firebase messaging?

**Comment by Dallas62** [comment]
Duplicate of #1979
