### ISSUE TITLE
Android - Not receiving Background notification after updating to latest version(7.3.0) 

### ISSUE THREAD

**Issue by jganga1841** [zo0r/react-native-push-notification#1994]
# Question

**Comment by Dallas62** [comment]
# Answer

**Comment by jganga1841** [comment]
Android - Not receiving Background notification after updating to latest version(7.3.0)

**Comment by Dallas62** [comment]
If i closed the issue, it's because there is no description.
No details and no reproduction example.
Updating from which version? Local or remote notification ?
What is the configuration ?
...
