### ISSUE TITLE
App crash after upgrading with v7.3.0

### ISSUE THREAD

**Issue by YURYSAKALOU** [zo0r/react-native-push-notification#1996]
try to build with 7.2.3 but failed suddenly. so upgraded with 7.0.3. built successfully but app is crashed

**Comment by Dallas62** [comment]
Hi @YURYSAKALOU 
Please search in issue history...
![image](https://user-images.githubusercontent.com/3429329/117999955-ab1f4280-b345-11eb-8432-5263c96475eb.png)
Regards
