### ISSUE TITLE
TypeError : null is not an object (evaluating 'RNPushNotification.requestPermissions')

### ISSUE THREAD

**Issue by MrAngelos6** [zo0r/react-native-push-notification#1997]
# Bug
Hello, i just upgraded the version from 4.0.0 to 7.3.0 cause of #1979 . Now the builld is working but when i start the app, i have this error :

![image](https://user-images.githubusercontent.com/13665765/118002441-e589df00-b347-11eb-9c1a-ebece0087ef7.png)

## Environment info

System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 5.82 GB / 15.93 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7322048

Library version: 7.3.0

## Steps To Reproduce

1. npx react-native run-android
2. When app starts error occured

Describe what you expected to happen:

1. No Error and app starts

## Reproducible sample code
```
import messaging, { firebase } from '@react-native-firebase/messaging';
import test from '@react-native-firebase/app';
import { Alert } from 'react-native';
// import PushNotificationIOS from '@react-native-community/push-notification-ios';
// import PushNotification from 'react-native-push-notification';
import PushNotificationIOS from '@react-native-community/push-notification-ios';
import NotificationHandler from '../utils/NotificationHandler';
import PushNotification from 'react-native-push-notification';
import Axios from 'axios';

PushNotification.configure({
    onNotification: function(notification) {
      // If it was opened do some work
      if (notification.data && notification.data.openedInForeground) {
        switch (notification.data.type) {
          case 'NewPrivateMessage':
            NotificationHandler.handlePrivateConversation(notification);
            break;
          case 'NewEventConversation':
            NotificationHandler.handleEventConversation(notification);
            break;
          default:
            break;
        }
        return;
      }
      notification.finish(PushNotificationIOS.FetchResult.NoData);
    },
    // IOS ONLY (optional): default: all - Permissions to register.
    permissions: {
      alert: true,
      badge: true,
      sound: true,
    },
    // Should the initial notification be popped automatically
    // default: true
    popInitialNotification: true,
    /**
     * (optional) default: true
     * - Specified if permissions (ios) and token (android and ios) will requested or not,
     * - if not, you must call PushNotificationsHandler.requestPermissions() later
     * - if you are not using remote notification or do not have Firebase installed, use this:
     *     requestPermissions: Platform.OS === 'ios'
     */
    requestPermissions: true,
  });

export default class NotificationService {

    static configureNotification() {
        messaging().onMessage(async remoteMessage => {
            const { data: { body, title, ...userInfo } } = remoteMessage;
            PushNotification.localNotification({ title, message: body, userInfo });
        });
    }

    static configureBackgroundNotification() {
        messaging().setBackgroundMessageHandler(async remoteMessage => {
            const { data: { body, title, ...userInfo } } = remoteMessage;
            PushNotification.localNotification({ title, message: body, userInfo });
        });
    }
}
```
Thanks for your help 😄

**Comment by Dallas62** [comment]
Hi @MrAngelos6 
Did you clean your project ?
This issue should not be related to a change from 4.x.x to 7.x.x.

**Comment by tpravallika23** [comment]
Hi,
Even I am facing the same issue after upgrading from 3.5.2 to 7.3.1.

Build is successful, but when i start the app, getting below warning:
![warning](https://user-images.githubusercontent.com/84119493/118087119-b2e0f480-b3e2-11eb-9d7e-d29f0b074171.png)

Environment::
Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Sample code::
PushNotification.checkPermissions();

**Comment by Dallas62** [comment]
Hi @tpravallika23 
The API didn't change on this part, this must be a compilation / rebuild issue.
Make sure to clean both JS and Gradle cache

**Comment by andresordonezfm** [comment]
Yes! I had the same problem and I restarted the machine and now everything is fine

**Comment by MrAngelos6** [comment]
@Dallas62 Thank you so much ! You are my hero ^^
