### ISSUE TITLE
Add changelog or release tag

### ISSUE THREAD

**Issue by sibelius** [zo0r/react-native-push-notification#200]
it would be very helpful to have a changelog.md or a release tag to describe what features are added or if there is any breaking change

**Comment by rodrigobdz** [comment]
Are there any plans to solve this issue? @zo0r

**Comment by rodrigobdz** [comment]
@sibelius what's the reason for closing the issue? It seems to be still unsolved.

**Comment by sibelius** [comment]
It is been an year already.

**Comment by rodrigobdz** [comment]
If you closed it because you don't want to receive further notifications you can always unsubscribe this thread. But you are closing an issue for the wrong reason.
