### ISSUE TITLE
No channel id passed, notifications may not work.

### ISSUE THREAD

**Issue by darryl-tan** [zo0r/react-native-push-notification#2000]
hi bro, I have  this warn  "No channel id passed, notifications may not work."
 here is my  function,where is chnnelID, I just want to use localnotification ,how can i solve this promble?
 
 const showNotification = (title,message)=>{
    PushNotification.localNotification({
        title:title,
        message:message,
        
    })
    
}

**Comment by darryl-tan** [comment]
if I  add this:
const showNotification = (title,message,channelId)=>{
    PushNotification.localNotification({
        
        title:title,
        message:message,
        channelId: 1,
    })
}
there is no warn ,but it didn't work at all

**Comment by Dallas62** [comment]
Please check channel management of the readme.
Regarss
