### ISSUE TITLE
PushNotification.localNotification  about chinnelId

### ISSUE THREAD

**Issue by darryl-tan** [zo0r/react-native-push-notification#2001]
when i run this function, it warn me  **No channel id passed, notifications may not work.**
`const showNotification = (title,message)=>{
     PushNotification.localNotification({
       title:title,
       message:message,
      
 })
}`
when i run this function , app did'm't do anything,no warn and no error
`const showNotification = ()=>{
    PushNotification.localNotification({
        
        title:"title",
        message:"message",
        channelId: "1",
    })
}`
what can I do

**Comment by Dallas62** [comment]
Already answered !
https://github.com/zo0r/react-native-push-notification/issues/2000#issuecomment-840360101
Regards
