### ISSUE TITLE
Notification small icon always showing gray box in android

### ISSUE THREAD

**Issue by endlesstech** [zo0r/react-native-push-notification#2007]
# Question
How to change the notification small icon with my app logo? I already added ic_notification in the mipmap folders. But, still showing gray box in the notification

**Comment by eduduardo** [comment]
same as https://github.com/zo0r/react-native-push-notification/issues/730, please close.

You can find the solution on this issue:

https://github.com/zo0r/react-native-push-notification/issues/730#issuecomment-485795534
