### ISSUE TITLE
Notification actions for remotely sent notfications

### ISSUE THREAD

**Issue by sajitkhadka** [zo0r/react-native-push-notification#2009]
# Question

Isn't there a way to define notification action to make it interactive for remotely sent notifications? I am working with android, so not sure if it works with ios or not. For local notification we can add for eg,
PushNotification.localNotification({
    actions: '["accept", "reject"]',
  });
which works perfectly.
But I don't see a way to do the same for remotely sent notifications. In app foreground as a workaround I can just create custom notification as soon as I receive notification from backend with whatever actions I want. But I can't see a way to do that when the app is backend. What am I missing?

**Comment by Dallas62** [comment]
Hi,
Send data only-notification and trigger a local notification with all needed parameters.
Regards

**Comment by sajitkhadka** [comment]
wow! it works.. never thought of that. thank you so much.

**Comment by daonamutc1** [comment]
> Hi,
> Send data only-notification and trigger a local notification with all needed parameters.
> Regards

Hi, I do follow your answer. On Android it work very well, but on IOS I can't receive notification
Here my payload:
"data": {
        "create_notification": true,
        "data": {
            "channel_id": 5,
            "res_model": "mail.channel"
        },
        "notification": {
            "title": "Notification title",
            "body": "line 6",
            "id": 6
        }
    }
Can you help me. Thanks
