### ISSUE TITLE
Obtain GCM Sender ID without Firebase

### ISSUE THREAD

**Issue by luisfuertes** [zo0r/react-native-push-notification#201]
I am trying to get the GCM Sender ID on my project, but only can download the google-services.json file.

Somebody know how can i get the GCM Sender ID now?

**Comment by npomfret** [comment]
It's the `project_number` in your  google-services.json  file.

**Comment by luisfuertes** [comment]
Thanks for answer!

**Comment by luisfuertes** [comment]
And know if can i receive notifications with this component, sent from Firebase?

**Comment by milkers** [comment]
You can also check [this](https://github.com/zo0r/react-native-push-notification/issues/77#issuecomment-258966208) to obtain a GCM Sender ID.
