### ISSUE TITLE
createChannel keeps returning 'false'

### ISSUE THREAD

**Issue by icy-meteor** [zo0r/react-native-push-notification#2011]
I am trying to run a react-native app on a physical android device. It has remote notifications with FCM. During the first install, createChannel works correctly and the notifications works as expected.
But createChannel starts returning false randomly when the app is uninstalled and installed again.

It is very inconsistent in nature.

Any idea what would the reason be?

**Comment by Dallas62** [comment]
Hi,
Android can keep channel settings between installations.
Regards

**Comment by MrAngelos6** [comment]
@icy-meteor createChannel returns false if the channel already exists, try to use getChannels() or channelExists() to test 👍

**Comment by icy-meteor** [comment]
Oh I didn't know this. Couldn't find it anywhere in documentation either.
This is really helpful, thank you @MrAngelos6 and @Dallas62.
