### ISSUE TITLE
Notifications not working on 7.3.1

### ISSUE THREAD

**Issue by AmadeusDeadDmytro** [zo0r/react-native-push-notification#2014]
# Bug

[TypeError: null is not an object (evaluating 'RNPushNotification.requestPermissions')] - i get this error after launching app, and then any notification not work

## Environment info

`react-native info` output:
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 4.09 GB / 15.95 GB
  Binaries:
    Node: 12.20.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.5.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7351085
    Visual Studio: 16.8.30804.86 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_211 - /c/Program Files/Java/jdk1.8.0_211/bin/javac
    Python: 2.7.15 - /c/Python27/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 7.3.1

**Comment by Dallas62** [comment]
Please search in issue history.
Regards.
