### ISSUE TITLE
Console prints error when a network request is called within onRegister on the configure method

### ISSUE THREAD

**Issue by Miyagee** [zo0r/react-native-push-notification#2019]
It seems that the `PushNotification.configure` method `onRegister` logs out:

```bash
  ERROR    undefined
  ERROR    [Error: Network Error]
```

when a network request is run within the method. The errors are not logged as fast as I remove the network call from the `onRegister` method. The request itself works fine and it seems that the notifications work fine as well so it does not seem to affect the behavior of the app. 

## Environment info

`react-native info` output:

```bash
"react-native-push-notification": "7.3.1"
```

## Steps To Reproduce

1. `configure` with `onRegister` that runs a network request. 

## Reproducible sample code

```js
PushNotification.configure({
  onRegister: async ({ token }) => {
    axios.post("some_url", {token}, {});
  },

  onNotification: (notification) => {console.log(notification) },
});
```

**Comment by Dallas62** [comment]
Hi @Miyagee 
We are not responsible of the axios code you put inside the `onRegister` method.
Please check your request / axios code.
Regards
