### ISSUE TITLE
Miss important payload when notification is clicked

### ISSUE THREAD

**Issue by pewh** [zo0r/react-native-push-notification#202]
I testing GCM by send this payload to GCM server:
```
{ "data": {
    "message": "foo",
    "tag": "bar"
  },
  "tag": "baz",
  "registration_ids": ['key inside']
}
```

then I inspect props from onNotification callback:
```
PushNotification.configure({
  ...,
  onNotification (props) { console.log(props)
})
```

then I get:
```
{
collapse_key: "do_not_collapse",
foreground: true,
google.message_id:"0:1474099613515209%60885dbcf9fd7ecd",
google.sent_time:1474099613509,
message:"foo",
tag:"bar",
userInteraction:false
}
```

but when I click notification, I get this in console:
```
{
foreground: false,
message:"foo",
userInteraction:true
}
```

my question is: how to get `tag` property (or other custom property) when notification is clicked? Thanks

**Comment by npomfret** [comment]
Its a bit confusing.  There are 2 types of notification, silent and non-silent.  The trick is not to use a message field at the root. Do something like this:

```
{
      "to": "token",
      "time_to_live": 86400,
      "collapse_key": "key",
      "delay_while_idle": false,
      "data": {
        "payload": {"message": "message", "tag": "bar"}
      }
    }
```

This will trigger a "silent" notification which will not appear in the notification centre but will trigger some code in your app.  From there you can use the data in it (the payload) to send a local notification using this api - the local notification will appear in the notification centre if you use the 'message' field, but you can also specify things like vibration, sound, colour, icon etc.

**Comment by pewh** [comment]
Thanks @npomfret, it's work! :beers:

**Comment by cinder92** [comment]
i'm facing the same issue but in iOS ....

+1

**Comment by jaisonveneri** [comment]
Hello @cinder92 ,

Were you able to receive message data on notification open in IOS?

Thanks!
