### ISSUE TITLE
custom notification sound does not play in android version 7

### ISSUE THREAD

**Issue by vandana87** [zo0r/react-native-push-notification#2021]
I am using react native push notification for sending custom notification with sound in my application.

It is working fine above android version 7 but the notification received in android 7 does not have the custom sound which is mentioned in channel.

Is it because I am not able to create the channels in android 7.

below is my service.js class where I am creating the channels

import React,{ useState } from 'react';
import PushNotification from 'react-native-push-notification';
 import NotificationHandler from './NotificationHandler'

export default class NotifService {
  constructor(onRegister, onNotification) {
    this.lastId = 0;
    this.lastChannelCounter = 0;

    this.channels = [
      {
          "id": "channel1",
          "sound": "channel1",
          "vibration": [150, 545]
      },
      {
          "id": "channel2",
          "sound": "channel2",
          "vibration": [150, 545, 545, 545]
      },
      {
          "id": "channel3",
          "sound": "channel3",
          "vibration": [150, 545, 545, 545, 545, 545, 545, 545]
      },
      {
          "id": "channel4",
          "sound": "channel4",
          "vibration": [150, 150, 150, 150]
      },
      {
          "id": "channel5",
          "sound": "channel5",
          "vibration": [150, 150, 150, 150, 150, 150, 150, 150]
      },
      {
          "id": "channel6",
          "sound": "channel6",
          "vibration": [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150]
      },
      {
          "id": "channel7",
          "sound": "channel7",
          "vibration": [180, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300]
      },
      {
          "id": "channel8",
          "sound": "channel8",
          "vibration": [180, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300]
      },
      {
          "id": "channel9",
          "sound": "channel9",
          "vibration": [180, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300]
      },
      {
          "id": "channel10",
          "sound": "channel10",
          "vibration": [180, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300, 621, 121, 134, 300, 289, 123, 134, 300]
      },
      {
          "id": "channel11",
          "sound": "channel11",
          "vibration": [150, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,100]
      },
      {
          "id": "channel12",
          "sound": "channel12",
          "vibration": [150, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
      },
      {
          "id": "channel13",
          "sound": "channel13",
          "vibration": [150, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
      },
      {
          "id": "channel14",
          "sound": "channel14",
          "vibration": [150, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100]
      },
      {
          "id": "silent",
          "sound": "silent",
          "vibration": [0]
      },
      {
          "id": "vibrate",
          "sound": "silent",
          "vibration": [2000, 5000, 500, 500]
      }
    ];
  
    this.channels.map((item,index) =>
    
    PushNotification.createChannel(
       {
        channelId: item.id, // (required)
        channelName: item.id, // (required)
        channelDescription: item.id, // (optional) default: undefined.
        soundName: item.sound+'.wav', // (optional) See `soundName` parameter of `localNotification` function
        importance: 4, // (optional) default: 4. Int value of the Android notification importance
        vibrate: true, // (optional) default: true. Creates the default vibration patten if true.
        vibration:item.vibration
      },
      (created) => console.log(`createChannel '${item.id}' returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
    )

    
    ); 

    NotificationHandler.attachRegister(onRegister);
    NotificationHandler.attachNotification(onNotification);

    // Clear badge number at start
    PushNotification.getApplicationIconBadgeNumber(function (number) {
      if (number > 0) {
        PushNotification.setApplicationIconBadgeNumber(0);
      }
    });
    
    PushNotification.getChannels(function(channels) {
      console.log(channels);
    });
  }

  popInitialNotification() {
    PushNotification.popInitialNotification((notification) => console.log('InitialNotication:', notification));
  }

  checkPermission(cbk) {
    return PushNotification.checkPermissions(cbk);
  }

  requestPermissions() {
    return PushNotification.requestPermissions();
  }

  cancelNotif() {
    PushNotification.cancelLocalNotifications({id: '' + this.lastId});
  }

  cancelAll() {
    PushNotification.cancelAllLocalNotifications();
  }

  abandonPermissions() {
    PushNotification.abandonPermissions();
  }

  getScheduledLocalNotifications(callback) {
    PushNotification.getScheduledLocalNotifications(callback);
  }

  getDeliveredNotifications(callback) {
    PushNotification.getDeliveredNotifications(callback);
  }
}
can anyone please advise how can I make custom sound work in android version less than 7.

Note: I am not able to see the channels when I open the app Info >>manage notification in android 7,but created channels can be seen in above android version 7

**Comment by Dallas62** [comment]
Hi @vandana87 
Probably because version below Android 7 doesn't support channels.
You have to use local notification directly with the right sound (not only the channel).
Regards
