### ISSUE TITLE
Error in background state notification and problems with default app settings

### ISSUE THREAD

**Issue by heavell7870** [zo0r/react-native-push-notification#2023]
If app is in background I receive default firebase notification without app logo and if I pass this channel id I didn't get any notification even in localNotification  `rn-push-notification-channel-id-4-300`

and also phones like xiaomi have some permission which is not allowed by default for showing pop up's playing sound and vibration how can I get these permissions?

My androidmanifies.xml

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  package="com.zhiffy.amazon.flipkart.olx.quikr">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:usesCleartextTraffic="true" tools:targetApi="28"
      android:requestLegacyExternalStorage="true"
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <meta-data
      android:name="com.google.firebase.messaging.default_notification_channel_id"
      android:value="@string/default_notification_channel_id" />
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground" android:value="false"/>
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
        <intent-filter>
            <action android:name="android.intent.action.BOOT_COMPLETED" />
            <action android:name="android.intent.action.QUICKBOOT_POWERON" />
            <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
        </intent-filter>
      </receiver>
      <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
      <activity
        android:name=".SplashActivity"
        android:theme="@style/SplashTheme"
        android:label="@string/app_name">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
`

index.js

`PushNotification.configure({
  onNotification: function(notification) {
    
    LocalNotification(notification)
    console.log('LOCAL NOTIFICATION ==>', notification)
  },
  senderID:'**********',
  popInitialNotification: true,
  requestPermissions: true
})`

**Comment by Dallas62** [comment]
Please read the Readme, specially the channel management part.

**Comment by heavell7870** [comment]
yeah read it 10 times but everywhere it asks for channel id which I don't have
@Dallas62

**Comment by heavell7870** [comment]
It's asking for channel it to create a channel which I don't have any idea

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification#channel-management-android

**Comment by heavell7870** [comment]
@Dallas62  can I use any string here ?

` channelId: "channel-id", // (required)`

**Comment by Dallas62** [comment]
Yes

**Comment by heavell7870** [comment]
@Dallas62 by the way if I send notification from firebase console I didn't get app logo 
how can I add that?
