### ISSUE TITLE
onNotificationOpenedApp() never called when taping notification tray on foreground, it calls getInitialNotification() with remote message null.

### ISSUE THREAD

**Issue by ravi123saxena** [zo0r/react-native-push-notification#2024]
Hi All,

The notification tray popup never calls the onNotificationOpenedApp() . By default it calls getInitialNotification() with remotemessage null. 

constructor(props){
    super(props)
    LogBox.ignoreAllLogs();
    console.reportErrorsAsExceptions = false;
    this.notif = new NotifService(
      this.onRegister.bind(this),
      this.onNotif.bind(this),
    );
  }

  componentDidMount () {
    AppState.addEventListener('change', this._handleAppStateChange);
    messaging().setBackgroundMessageHandler(async remoteMessage => {
      console.log('Message handled in the background!', remoteMessage);
    });
    
    messaging().onNotificationOpenedApp(remoteMessage => {
      console.log(
        'Notification caused app to open from background state:',
        remoteMessage.notification,
      );
    });

    // Check whether an initial notification is available
    messaging()
      .getInitialNotification()
      .then(remoteMessage => {
        if (remoteMessage) {
          console.log(
            'Notification caused app to open from quit state:',
            remoteMessage.notification,
          );
        }
    
      });
  }
  componentWillUnmount() {
  
    AppState.removeEventListener('change', this._handleAppStateChange);
  }

  onRegister(token) {
    this.setState({registerToken: token.token, fcmRegistered: true});
  }

  
  onNotif(notif) {
   // Alert.alert(notif.title, notif.message);
   this.notif.localNotif(notif.title, notif.message);
    
    });
   
  }

 <meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground"

        android:value="false"/>

        

        <meta-data android:name="com.dieam.reactnativepushnotification.notification_color"

        android:resource="@color/white"/> 

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">

          <intent-filter>

            <action android:name="android.intent.action.BOOT_COMPLETED" />

            <action android:name="android.intent.action.QUICKBOOT_POWERON" />

            <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>

          </intent-filter>
        </receiver>
        <service
          android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
          android:exported="false" >
          <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
        </service>
    </application>
</manifest>

Please help.

**Comment by Dallas62** [comment]
Hi @ravi123saxena 
This repository is not the RNFirebase repository.
Regards

**Comment by ravi123saxena** [comment]
so which method will be called on tap on notification tray in forground

**Comment by ravi123saxena** [comment]
onNotification is called before tapping on notification tray. i need any method should call when tap event on notification would be happen.

**Comment by Dallas62** [comment]
@ravi123saxena Please read the documentation and my comment.

**Comment by MIrsyad** [comment]
@ravi123saxena when notification getting tap or click, on notification will trigger with notification.userinteraction set to true
