### ISSUE TITLE
Random message for scheduled local notifications

### ISSUE THREAD

**Issue by Balthazar33** [zo0r/react-native-push-notification#2035]
# Question

Is there a way to show a different message every time for scheduled local notifications?

I have a set of messages stored in an array and I would like to show any one of them every time a notification is triggered.

I've tried this 

```
const messages = [...];

function getRandom() {
            return Math.floor(Math.random() * (10);
 }

PushNotification.localNotificationSchedule({
            //... You can use all the options from localNotifications
            channelId: "my-channel",
            message: messages[getRandom()], // (required)
            date: new Date(Date.now() + 60 * 1000), // in 60 secs
        
        
        });
```
But this calls the same message every time.
        
I think this does not work because `PushNotification.localNotificationSchedule` is called only once.
       
Is there a way to achieve this ?

**Comment by Dallas62** [comment]
Hi,
You can schedule multiple notifications with a differents messages.
Regards

**Comment by Balthazar33** [comment]
This is brilliant. Thanks!

**Comment by wojniemiec** [comment]
This doesn't solve the problem, if I want to schedule a notification once a day with random message, do I need to schedule new notification every day? I would like to have an option to set a "messageFn" that would be evaluated just before sending scheduled local notification. Is that possible or is there a good workaround for that?

**Comment by Dallas62** [comment]
Hi @wojniemiec 
I already provide a workaround. Notification is not at JavaScript Runtime, this case cannot be support actually.
Please make some that look like random. The user doesn't know the message until it appears.

**Comment by Dallas62** [comment]
It would be an Android-only feature which is not wanted. Also Android battery saver kill schedulded notification too often (pinned issue).
If you really want random messages and "forever" you can use remote notification which is trigger every day with a different message.
