### ISSUE TITLE
Remote notifications stopped triggering onNotification after version upgrade

### ISSUE THREAD

**Issue by schlafnie** [zo0r/react-native-push-notification#2045]
We recently upgraded the package from version 3.1.2 to version 7.2.3. Local notifications from our server keep working but remote Android notifications sent by external service (MoEngage) do not trigger `onNotification` anymore so we cannot pass the payload to their sdk. Is there any change that should have been done to handle external notifications?

**Comment by Dallas62** [comment]
Please follow the CHANGELOG.
Regards
