### ISSUE TITLE
Issued when setting in new Android/IOS

### ISSUE THREAD

**Issue by TechGuyVN** [zo0r/react-native-push-notification#205]
Hi,
I have problem when config plugin in android.
my config in Android manifest like that:

> ```
>  <permission android:name="com.mydemo.permission.C2D_MESSAGE"
>        android:protectionLevel="signature" />
> <uses-permission android:name="com.mydemo.permission.C2D_MESSAGE" />
> <uses-permission android:name="android.permission.VIBRATE" />
> <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
> 
> <uses-sdk
>     android:minSdkVersion="16"
>     android:targetSdkVersion="22" />
> 
> <application
>   android:name=".MainApplication"
>   android:allowBackup="true"
>   android:label="@string/app_name"
>   android:icon="@mipmap/ic_launcher"
>   android:theme="@style/AppTheme">
>   <activity
>     android:name=".MainActivity"
>     android:label="@string/app_name"
>     android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
>     <receiver
>          android:name="com.google.android.gms.gcm.GcmReceiver"
>          android:exported="true"
>          android:permission="com.google.android.c2dm.permission.SEND" >
>          <intent-filter>
>              <action android:name="com.google.android.c2dm.intent.RECEIVE" />
>              <category android:name="com.mydemo" />
>          </intent-filter>
>      </receiver>
> 
>      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
>      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
>          <intent-filter>
>              <action android:name="android.intent.action.BOOT_COMPLETED" />
>          </intent-filter>
>      </receiver>
>      <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
>      <service
>          android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
>          android:exported="false" >
>          <intent-filter>
>              <action android:name="com.google.android.c2dm.intent.RECEIVE" />
>          </intent-filter>
>      </service>
> 
>     <intent-filter>
>         <action android:name="android.intent.action.MAIN" />
>         <category android:name="android.intent.category.LAUNCHER" />
>     </intent-filter>
>   </activity>
>   <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
> </application>
> <meta-data android:name="com.parse.push.gcm_sender_id"
>    android:value="@string/senderId" />
> ```

I use this plugin in my code like that:

```
  componentDidMount() {
    AppState.addEventListener('change', this.handleAppStateChange);
    const {dispatch} = this.props;
    console.log("tera: begin setup Notifications");
    PushNotification.configure({

        // (optional) Called when Token is generated (iOS and Android)
        onRegister: function(token) {
            console.log( 'tera TOKEN:', token );
            registerInstallation({
                   "deviceType": Platform.OS === 'ios' ? "ios" : "android",
                   "deviceToken": token,
                   "channels": ["global"],
                   "pushType":pushType
                   });
        },

        // (required) Called when a remote or local notification is opened or received
        onNotification: function(notification) {
            console.log( 'tera NOTIFICATION:', notification );
        },

        // ANDROID ONLY: GCM Sender ID (optional - not required for local notifications, but is need to receive remote push notifications)
        senderID: PARSE_CLOUD_GCD_SENDER_ID,

        // IOS ONLY (optional): default: all - Permissions to register.
        permissions: {
            alert: true,
            badge: true,
            sound: true
        },

        // Should the initial notification be popped automatically
        // default: true
        popInitialNotification: true,

        /**
          * (optional) default: true
          * - Specified if permissions (ios) and token (android and ios) will requested or not,
          * - if not, you must call PushNotificationsHandler.requestPermissions() later
          */
        requestPermissions: true,
    });


```

when i debug on simulator android, it dont return any token, when watch logcat i notice this error:

> W/ActivityManager( 1573): Unable to start service Intent { cmp=com.mydemo/com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService (has extras) } U=0: not found

I re-checked source and everything config ok, source include.

Please help me solve this case.

**Comment by npomfret** [comment]
Have you _linked_ it correctly using `react-native link`?
