### ISSUE TITLE
Custom sound is not getting played while only 'default' sound getting played after mentioning custom soundName also

### ISSUE THREAD

**Issue by AmeyKhoje** [zo0r/react-native-push-notification#2050]
StackOverflow: https://stackoverflow.com/questions/67981994/custom-sound-is-not-getting-played-after-added-in-configuration-also-in-react-na

I have used custom sound for notification but every time default sound is getting played. I have also mentioned soundName in config and added sound file in 'raw' folder. But it is not working.

How can i solve this??
Code:
           
              `PushNotification.localNotification({

			/* Android Only Properties */
			channelId: 'default-channel-id',
			autoCancel: true, 
			largeIcon: 'ic_launcher', 
			smallIcon: 'ic_launcher', 
			color: 'red', 
			vibrate: true, 
			vibration: 300, 
			tag: 'some_tag', 
			group: 'group',
			groupSummary: false, 
			ongoing: false,
			actions: null,
			invokeApp: true,
			when: null,
			usesChronometer: false,
			timeoutAfter: null,

			/* iOS only properties */
			category: '',

			/* iOS and Android properties */
			id: this.lastId,
			title: config.title,
			message: config.message,
			userInfo: {screen: 'home'},
			playSound: true,
			soundName: 'sound_one.mp3',
			number: 10,
		});`
react-native-push-notification: 7.3.1
react-native: 0.64.1

**Comment by Dallas62** [comment]
Hi,

Sounds are stick to channels.

Regards

**Comment by AmeyKhoje** [comment]
Then what should I need to do. I have also added soundName in createChannel method. But it still plays default sound

**Comment by Dallas62** [comment]
You can take a look to the exemple project which include a custom sound.
Once a channel is created, you cannot change the sound. Make sure the channel wan't created with default sound.
Since there is a working exemple of custom sound in this project and your given exemple is not enough to reproduce, cannot help you more.

**Comment by AmeyKhoje** [comment]
My issue is solved. Thanks!
I just needed to create two channels with different id and sound name and then call different channel based on requirements.

**Comment by adamozen** [comment]
> My issue is solved. Thanks! I just needed to create two channels with different id and sound name and then call different channel based on requirements.

how do u create two channel try looking around but found nothing. Doc only giving example of only one channel..can u giv an example please?
