### ISSUE TITLE
handleschedulenotification not working for next day notification (24 hours)

### ISSUE THREAD

**Issue by DutaAndrei1** [zo0r/react-native-push-notification#2052]
Hi,

I have a device control app. If I turn on a device (I press the ON button) today, I want to receive a reminder on the next day at the same hour. So, the time should be 24 hours, but I don't receive the notification. If I set the time to one minute for example, it works. I am using this line: date: new Date(Date.now()+60 * 1000 * 60 * 24). If I leave only 60 * 1000 (1 minute) it works, but if I scale it to 24 hours, it doesn't work. Probably the app gets automatically killed after some time. How I can receive the notification only once, on the next day ? 
Thank you!

**Comment by Dallas62** [comment]
Hi,

Look at pinned issues, unfortunately battery saver might stop notifications for the next day.
Disable it or send remote notification 🤷‍♂️

Regards

**Comment by DutaAndrei1** [comment]
Thanks,

I opened the app and the notification scheduled from yesterday appeared. I found that my phone has individual battery saver setting for every app. For my app, it was set on 'economy(recommended)'. I switched to 'no restrictions' and I hope it will work.
