### ISSUE TITLE
"popInitialNotification" always return "undefined"

### ISSUE THREAD

**Issue by anishtr4** [zo0r/react-native-push-notification#2057]
# Bug
popInitialNotification method always return 'undefined' for local notification. I have tried in both scenarios while the app in background and while the app is closed . Tried both localNotificationSchedule, localNotification methods.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.2
    CPU: (8) x64 Apple M1
    Memory: 86.55 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62 => 0.62.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: x.x.x

## Steps To Reproduce

1. Initiate a local notification
2. Local notification received while app is close
3. Tap on the local notification received
4. PushNotification.popInitialNotification event triggered but returned with 'undefined'.
...

Describe what you expected to happen:

1.PushNotification.popInitialNotification event should return with local notification details which user clicked.
2.

**Comment by Dallas62** [comment]
Take time to search in issue history

**Comment by anishtr4** [comment]
@Dallas62 
Would you mind sharing issue link. I have tried few of fix form issues history  none of them did’t work.

**Comment by Dallas62** [comment]
For Android you can look at: https://github.com/zo0r/react-native-push-notification/issues?q=is%3Aissue+splashscreen
and https://github.com/zo0r/react-native-push-notification#android-manual-installation

> If your app has an @Override on onNewIntent in MainActivity.java ensure that function includes a super call on onNewIntent (if your MainActivity.java does not have an @Override for onNewIntent skip this):
```java
    @Override
    public void onNewIntent(Intent intent) {
        ...
        super.onNewIntent(intent);
        ...
    }
```

For iOS:
There is your issue opened and this one: https://github.com/react-native-push-notification-ios/push-notification-ios/issues/24

**Comment by anishtr4** [comment]
@Dallas62 , Does this “popInitialNotification” method works for local notifications as well or just for remote notification??

**Comment by Dallas62** [comment]
It's working only from killed state, but yes for all kind of notifications

**Comment by garrettmaring** [comment]
@Dallas62 I've searched through lot of history and still struggling to handle, on iOS, notifications from a killed state.

I've seen a couple random things saying to disabled remote debugging and to build the product in release mode, strange that those would interfere with notifications but I did that.

Given my understanding of `popInitialNotification`, I thought things would just work out of the box. That is, `onNotification` would be called from a killed state. That isn't happening.

So, I see `popInitialNotification` to false and added my own handler inside the top-most component with a `useEffect(() => { PN.popInitialNotification(handler) }, []`. That also doesn't work.

I've tried some other things and started messing around with PNIOS.getInitialNotification with no luck. I don't want to use an iOS only handler anyway though.

From the history of this problem, where would you advise that I look to get notification handling from killed state working on iOS/Android?

**Comment by vr1Ravi** [comment]
Hey @Dallas62, I am new to this package. what i understood is popInitialNotification method is for a situation when your app is killed and you tap on notification. I impleted the logic but the current behaviour is sometimes i am getting notification as an object in a callback but sometime undefined. Now when I am gettting an object, My app is open and i get the notification then killing the app and tapping on notification redirects to desired screen. Second case when app is already killed and notification came, in this case tapping on notification getting undefined and hence no redirection. Could you please help I've been stuck on this for like 5 days.
