### ISSUE TITLE
Add Multiple callback for onNotification.

### ISSUE THREAD

**Issue by ankit5174** [zo0r/react-native-push-notification#2059]
# Question

Can we add multiple callback of onNotification. I need the on notification call back so that i can integrate the deep linking linking using react navigation. Following this tutorial which uses rnfirebase but i am trying to replace it with this library cause it gives feature like userInteraction even when app is in forground which is missing in rnFirebase.

**Comment by Dallas62** [comment]
Hi @ankit5174 
I don't understand you needs.
Up to you to call multiple handler if needed, only one callback is available.
Regards

**Comment by ankit5174** [comment]
If you look at below snippet, its uses 
`const unsubscribeNotification = messaging().onNotificationOpenedApp( 
`
to listen to on user interaction with the notification. Using the react native push notification library i can register for a single callback. But actually i want to listen at multiple places.

 https://gist.github.com/naishe/fbc0ca0a3fa81da1872c96902d4c3140#file-app-tsx ,

**Comment by heavell7870** [comment]
@Dallas62  need help 

how to send large icon in fcm remote notification bcs whenever I send any notification from cloud function I didnt see icon in right side if app is not running but I see if app is running 

so can u help me how to set large icon
