### ISSUE TITLE
Support HTML tags on bigText field for android

### ISSUE THREAD

**Issue by silencer07** [zo0r/react-native-push-notification#2060]
Title says it all. However this PR has been here since last year but no one is merging::

https://github.com/zo0r/react-native-push-notification/pull/1469

requesting for merge, hopefully for next release

**Comment by silencer07** [comment]
cc: @Dallas62

**Comment by odemiral** [comment]
@Dallas62 +1 for this feature, would be great to be able to put body of the text with multiple lines.
