### ISSUE TITLE
vibrate:false is ignored in "vibrate mode"

### ISSUE THREAD

**Issue by daheeahn** [zo0r/react-native-push-notification#2061]
react-native: 0.63.4
react-native-push-notification: 7.3.1

I created 2 channel

```
      PushNotification.createChannel(
        {
          channelId: 'channel a',
          channelName:  'channel a',
          channelDescription: 'description a',
          vibrate: true,
        },
        (created: boolean) => {},
      );

      PushNotification.createChannel(
        {
          channelId: 'channel b',
          channelName:  'channel b',
          channelDescription: 'description b',
          vibrate: false,
        },
        (created: boolean) => {},
      );
```

I made push

```
...
PushNotification.localNotificationSchedule({
    channelId: 'channel a',
    id: 1,
    date: new Date(JSON.parse(obj.date)),
    autoCancel: false,
    ongoing: false,
    allowWhileIdle: true,
    userInfo: obj,
    title,
    message,
    playSound,
    soundName,
    volume: _volume,
    vibrate: true,
    vibration: 2000,
    repeatType,
    repeatTime,
    ignoreInForeground: false,
});

...
PushNotification.localNotificationSchedule({
    channelId: 'channel b',
    id: 2,
    date: new Date(JSON.parse(obj.date)),
    autoCancel: false,
    ongoing: false,
    allowWhileIdle: true,
    userInfo: obj,
    title,
    message,
    playSound,
    soundName,
    volume: _volume,
    vibrate: false, // Changed it to false because it was written as true
    vibration: 2000,
    repeatType,
    repeatTime,
    ignoreInForeground: false,
});
```

[My test device (Android Galaxy S9) setting]
-> Vibrate Mode
-> When I created a push with ids 1 and 2
id(1) - not vibrate (normal)
id(2) - vibrate (abnormal - I expected no vibrate in vibrate mode)

I created 'channel b' with vibrate false, why does id 2 push vibrate in vibrate mode? How can I solve this?

**Comment by Dallas62** [comment]
hi @daheeahn 

Make sure the `channel b` wasn't created with `vibrate: true` then changed to `vibrate: false`.
Update a channel is not possible.

Regards

**Comment by daheeahn** [comment]
@Dallas62 I didn't understand.
'channel b' created with vibrate: false.
and I removed app and reinstalled.
How can I do?

**Comment by Dallas62** [comment]
Can you check **in phone setting**s if the created channel is with vibration disabled ?
We need to make sure channels are correctly configured.

**Comment by daheeahn** [comment]
FYI, If the push made with the b-channel is in sound mode, it doesn't vibrate as I expected. But in vibrate mode, it vibrates.

**Comment by daheeahn** [comment]
![alarm1](https://user-images.githubusercontent.com/38369729/122760104-b1ee8d00-d2d5-11eb-8241-63fb667e403b.jpeg)
![alarm2](https://user-images.githubusercontent.com/38369729/122760113-b4e97d80-d2d5-11eb-9384-cab957f329d6.jpeg)

Channel a, b in order

**Comment by Dallas62** [comment]
Hi @daheeahn 
If everything is right, I suggest you to set `vibrate: false` in your `PushNotification.localNotificationSchedule` call.
If vibrate is ignore, it's probably an issue (behavour?) of Android...
The library create the channel correctly and apply all parameters send by your application. After that it's Android which handle the notification.
Regards

**Comment by daheeahn** [comment]
Oh, I changed the vibrate of push with `id: 2` to `false` because it was written as `true` by mistake.

**Comment by daheeahn** [comment]
It's a very simple test, can you try it yourself on your Android device? I think I typed everything well as provided by the library.

**Comment by Dallas62** [comment]
I can check, but I don't think I can do something with it... All data are passed to the Android SDK, then it does the work... If the channel is at vibrate false (in system display like your screenshot), the library is doing the job...

**Comment by Dallas62** [comment]
I'm confused, but can you fix your exemple ?
You said notification with id 1 is not vibrating, but in your exemple it's suppose to vibrate.
And the id 2 is vibrating when you don't expect it.
I suspect a channel swap

**Comment by daheeahn** [comment]
When the push with id 2 is in `sound mode` or `silent mode`, it doesn't vibrate as I want it to. But in `vibrating mode`, it vibrates. I think it should not vibrate even in `vibrate mode`, but I don't know why it vibrates only in `vibrate mode`.
And the channel was not confused.

**Comment by Dallas62** [comment]
Ok, but reading your initial post, channel b (notification id 2) is all no vibration.
