### ISSUE TITLE
Open particular 'react-navigation' route when click on notification

### ISSUE THREAD

**Issue by AmeyKhoje** [zo0r/react-native-push-notification#2062]
I want to open particular route of my app when user click notification and app is closed. How can i do this with this package ?

RootNavigation.navigate("AlarmManager",{ from: "Noti" })

I have used this methis inside my onNotification function but it works only when app is running. Not when app is closed.

**Comment by Dallas62** [comment]
Please use the issue history,
Regards

**Comment by dangnguyen1004** [comment]
very bad support

> Please use the issue history, Regards
