### ISSUE TITLE
Failing on Creating Channel

### ISSUE THREAD

**Issue by JackyKeng** [zo0r/react-native-push-notification#2069]
Hi, I'm trying to integrate Firebase Cloud Messaging with `react-native-push-notification`. I had follow those steps from `react-native-push-notification` but  I keep failing on creating new channel. Based on docs it mentioned that if return `false` means the channel is exists. But when I try to list all the channels `PushNotifications.getChannels`, I'm getting empty array.

react-native-push-notification: "^7.3.0"

**Comment by Dallas62** [comment]
Hi,
Channels depends on the version of your Android.
Please read the Android documentation about channels and provide a reproducible exemple if you need more information.
Regards

**Comment by JackyKeng** [comment]
Looks like its because of the Android version, which I'm currently testing is on Android 6.
I had used another device Android version more than 8, which support channel works fine now. 
Thanks for quick response.
