### ISSUE TITLE
Actions button with icon

### ISSUE THREAD

**Issue by viveKing21** [zo0r/react-native-push-notification#2075]
I made a music player and want to give the option to play and pause option from the notification center.

How can i achieve this?? is it available on current version??

IF NOT PLEASE ADD IT

**Comment by Dallas62** [comment]
IT'S NOT AVAILABLE! PLEASE MAKE A PR!!
Regards

**Comment by viveKing21** [comment]
Oh alright, Thanks for replying tho

**Comment by Yandamuri** [comment]
@Dallas62 Are there any chances that adding action button is available in future?
