### ISSUE TITLE
Firebase Notification Auto Appear

### ISSUE THREAD

**Issue by mtalhagaoglu** [zo0r/react-native-push-notification#2078]
Hi.

I am sending notification from firebase console but even i do nothing with it, it appears in notification bar. I don't want this. I want to use localNotifcation and edit some behaviour on notification. After all of these process i can show the user, not before. Is there any  settting for not to show automatically any received notification?

**Comment by Dallas62** [comment]
Hi @mtalhagaoglu 
Start reading the documentation about Firebase Notification.
Regards

**Comment by mtalhagaoglu** [comment]
I read that. In my olding project i was sending all the information in data and process them in app. But this behavior restricts me sometimes.

**Comment by Dallas62** [comment]
Ok, so you probably notice that Firebase console send notification and not data-only notification ?

**Comment by mtalhagaoglu** [comment]
yes i know. i am asking is there any way to disable show up even if its a "notification" message. if not i am okey with "only data" message
