### ISSUE TITLE
How to show React Native Push Notification when app is closed

### ISSUE THREAD

**Issue by whitesnow1120** [zo0r/react-native-push-notification#2079]
I built react native app using react-native-push-notification.

The logic to show notification is like below.

I used "onSnapshot" function in react-native to check the firestore data is changed or not.

If changed, I showed local notification in the app.

```
...
const ref = firestore().collection('players');
return ref.onSnapshot(querySnapshot => {
    querySnapshot.forEach(doc => {
        ....
        // called push notification
        PushNotification.localNotification({
            channelId,
            title,
            message,
            bigText,
        });
    });
});
...
```
When the app is in the foreground or background, it works well. (Android and iOS)

What I want is to show this push notification when the app is closed.

I saw some blogs but until now, I couldn't find the solution.

Any help is appreciated.

Thanks.

**Comment by shrutiraoniit25** [comment]
hey hi did you find any solution for this

**Comment by whitesnow1120** [comment]
Hi @shrutiraoniit25 I used react-native-push-notification when the app is in foreground.
For other cases such as background or terminated, I used fcm instead of it.

**Comment by lorenz068** [comment]
BackgroundFetch is a solution if you are at 15min of precision
https://medium.com/@alihaghani/background-tasks-and-local-push-notifications-with-react-native-d63fc7fff9b
