### ISSUE TITLE
undefined is not an object (evaluating push notifications.getIntialNotification

### ISSUE THREAD

**Issue by LoseTheQuit** [zo0r/react-native-push-notification#209]
I believe I've added all the correct lines of code to get to this point. I wonder what the problem is. 

Does any one have any idea how to fix this?

  componentDidMount: function() {
    PushNotification.configure({

I have it setup like this.

**Comment by npomfret** [comment]
Sounds like a missing import maybe?

**Comment by LoseTheQuit** [comment]
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
 
this one maybe?

**Comment by shafips** [comment]
I have this same issue :(

**Comment by Jazz747** [comment]
Same here, installed everything correctly and still getting it :/

**Comment by flaviosbert** [comment]
Same here!

**Comment by aduispace** [comment]
Same issue, but with a r.presentLocalNotification problem

**Comment by nazywamsiepawel** [comment]
+1

**Comment by diego-cesa** [comment]
+1

**Comment by Arnaslt** [comment]
same here

**Comment by Couiljer** [comment]
If anyone made the same as me, I fixed the undefined issue by adding  `var PushNotification = require('react-native-push-notification');` instead of the line I originally wrote `import {PushNotification} from 'react-native-push-notification'`

**Comment by jinaddavid** [comment]
am having the same issue, undefined is not an object (evaluating push notifications.getIntialNotification

any solution please ?

**Comment by matheusbtrevisan** [comment]
@Couiljer i have to use `import PushNotification from 'react-native-push-notification'` only

**Comment by KthProg** [comment]
Importing it without the brackets fixes the issue for me.
