### ISSUE TITLE
All Notifications triggers at one time

### ISSUE THREAD

**Issue by arjundalal** [zo0r/react-native-push-notification#2090]
Hello Team,
i have schedule 3 notifications for 3 different time. For eg the time are 10:00 AM , 03:00 PM and  08:00 PM. I want to send notifications for this 3 time on daily basic, for that i uses repeatType= 'day' property in notification object. 
First time it will work properly but on next day it will fire all schedule notifications at one time i.e. on (10:00 AM).

can any one help me to solve this issue.
Thanks in Advance.

**Comment by Dallas62** [comment]
Hi,
For Android, if you want precision, use remote notification. Android saving mode fuck all background processes which can lead to this kind of issue.
Also check your date to be sure you are in the future.
Regards

**Comment by arjundalal** [comment]
Hello Team,
My Dates are same but time are different. i want to send 3 notification on each date for different time.

Regards,
