### ISSUE TITLE
All Repeat Notifications fire at one time in day

### ISSUE THREAD

**Issue by arjundalal** [zo0r/react-native-push-notification#2094]
Hello,
I have schedule two notification on same date for different time using different channel ID.
My notification dates are: - **2021-07-17T07:15:00.656Z** and **2021-07-17T07:00:00.291Z**.
it will work fine on same day, but when i move date to next day all notification fire at one time.
**My notification set code is :-**
PushNotification.localNotificationSchedule({
        channelId: this.channelID, 
        title: title,
        largeIcon: 'ic_launcher',
        smallIcon: 'ic_launcher',
        message: message,
        userInfo: {}, 
        playSound: true,
        soundName: 'default',
        date: date,
        allowWhileIdle: true,
        priority: 'high',
        repeatType: 'day',
        repeatTime: 1,
      });

can any one please help me to solve this issue i am struct on this issue.
please help me
Thanks in advance

**Comment by shrutiraoniit25** [comment]
so when you fire on the same day does it get fired when the app is closed or when the app is in background or foreground mode

**Comment by pankajsoftyoi** [comment]
i am also facing same issue,
i am passing every day date till 30 days and after 2 days, it still trigger previous days notification.
 is there any solution for this?

```
PushNotification.localNotificationSchedule({
      channelId: 'cannel_id',
      title: 'app_title',
      message: 'message_value',
      date,
    });
```
