### ISSUE TITLE
Notification not show first time after close and restart or place app in background then it's work.

### ISSUE THREAD

**Issue by vickypathak123** [zo0r/react-native-push-notification#2097]
I'm use firebase for notification and show notification in app. IN background app work like charm but first time when app installed it's not work after that it's work second time.

![Screenshot 2021-07-19 at 1 43 00 PM](https://user-images.githubusercontent.com/56220272/126126196-5e8ab6e6-dc2e-45d5-9004-f66621a63577.png)

**Comment by arunahuja94** [comment]
@vickypathak123 happened with me too, though i was able to resolve this by setting the default channel id in android manifest 
![IMG_20210727_114911.jpg](https://user-images.githubusercontent.com/78036151/127105447-4b6c3d84-95a5-4365-a07d-02db01213886.jpg)

**Comment by ale-rinaldi** [comment]
![Uploading IMG_20210820_144452.jpg…]()

**Comment by ale-rinaldi** [comment]
![IMG_20210820_144452](https://user-images.githubusercontent.com/4801469/130235180-9943b0bb-5b53-40eb-9100-70a7516d162e.jpg)

**Comment by ale-rinaldi** [comment]
![IMG_20210820_144720](https://user-images.githubusercontent.com/4801469/130235411-671b21b7-3b18-4da7-b033-65103c0bd9b8.jpg)
