### ISSUE TITLE
Change the the type of id to string/number.

### ISSUE THREAD

**Issue by Abhishek12345679** [zo0r/react-native-push-notification#2103]
# Feature Request
Make the types of both the `id` of `string` type
```javascript
PushNotification.localNotificationSchedule({id:0}) // here, the type of id is number
```
whereas in the 
```js
PushNotification.cancelLocalNotifications({ id: "0" }) // here, the type of id is string
```

There is inconsistency in creating the notification with a numeric id and then cancelling it with a string id.

## Why it is needed

It is need for the sake of consistency and to reduce confusion.
In my own use-case, I generate a uuid in the server with a string type as most uuids are. Thus, converting the uuid to `number` type is really buggy.

## Possible implementation

Converting the id type in `localNotificationSchedule({id:0})` to a string type

### Code sample

Sorry for this, but i am not well versed the native development.

**Comment by Dallas62** [comment]
Hi,

The main issue to this FR, is that Android Notification Center expect integer.. (int32)

**Comment by Abhishek12345679** [comment]
But in that case shouldn't 
```js
PushNotification.cancelLocalNotifications({ id: "123" })
```
also take in an integer value ?

**Comment by Dallas62** [comment]
Probably, I'm not available to look at the code
