### ISSUE TITLE
Remote notification via Parse Server not showing pop-up on Android

### ISSUE THREAD

**Issue by eberperetto** [zo0r/react-native-push-notification#2104]
# Bug

Remote notifications that are sent directly with Firebase console are correctly received and the pop-up is always shown (foreground and background, using emulator and real device as well). However, when sending them using Parse Server, the pop-up never shows, even though the "onNotification" function always gets the notification object. This is what the notification object looks like on this function when sent via Parse Server:

```json
{"data": {"data": "{\"title\":\"Mets Score!\",\"message\":\"The Mets scored! The game is now 1-1.\"}", "push_id": "kNQNh2ZU9o", "time": "2021-07-26T19:49:36.986Z"}, "finish": [Function finish], "foreground": true, "id": "839695094", "userInteraction": false}
```

This is what the object received form Firebase console looks like, for reference:
```json
{"channelId": "guideChannel", "color": null, "data": {}, "finish": [Function finish], "foreground": true, "id": "-92456815", "message": "The Mets scored! The game is now 1-1.", "priority": "high", "smallIcon": "ic_notification", "sound": null, "tag": "campaign_collapse_key_7812495880914110515", "title": "Mets Score!", "userInteraction": false, "visibility": "private"}
```

I am fully aware that many others have opened similar issues and already tested every combination of solutions, but it seems strange that the pop-up is called when using Firebase directly and not by using other services. Also, since the goal of this implementation is to publish a public quick guide/tutorial on how to use Parse Server and this library, I would prefer not to manually send a local notification as suggested on the README.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 536.36 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.15.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 22, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.0, 29.0.0, 29.0.2, 30.0.0, 30.0.0, 30.0.1, 30.0.2
      System Images: android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_171 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 7.4.0

## Steps To Reproduce

1. Create a react native project using yanr and react-native version 0.64
2. Install `react-native-push-notification`, `parse` and `@react-native-async-storage/async-storage` and configure
3. Run `yarn android`
4. Send a remote notification using Parse Server (either via dashboard or Cloud Code using `Parse.Push`)
5. The notification is received on console but no pop-up is shown

Describe what you expected to happen:

1. When receiving the notification, the app should show a pop-up

## Reproducible sample code

Here is a [repository](https://github.com/eberperetto/react-native-push-notification-parse-server-popup-bug) containing an example project with the currently used configuration.

**Comment by Dallas62** [comment]
Hi,

Please read the Firebase documentation about notifications type.

Regards
