### ISSUE TITLE
I was useing localNotificationSchedule,where can I find callback well the push is finish

### ISSUE THREAD

**Issue by darryl-tan** [zo0r/react-native-push-notification#2108]
notification.finish is not for localNotificationSchedule until I touch the info,
I want to findout the callback ,eg: now is 9:00 , localNotificationSchedule will work at 10:00, when it alert,I want to do something after alert. pls help me , tks

**Comment by zeeshan112233** [comment]
Were you able to figure this out ?

**Comment by ginery** [comment]
someone figure it out?
