### ISSUE TITLE
How to get an alert Message after clicking on local notification?

### ISSUE THREAD

**Issue by swaroopa94** [zo0r/react-native-push-notification#211]
Hi,

I am working this moudule to get my notifications.
But, In android when the app is in background i dont receive notification so i used the localnotification() method as following:

` if(this.state.appstate=='background'){

```
      PushNotification.localNotification({
       message:notification.body, 
      date: new Date(Date.now() + (60 * 1000)) 
      });

     }`
```

After using this I am getting my notification.
But the main function of this notification is to accept or deny the request sent by the other user.
So when I click on my local notification, its taking to my app but I want to show an alert message to accept or deny my request after taking into the app.

Can you please help to how to do that?

**Comment by railscard** [comment]
You can configure PushNotification to run some code when notification has been pressed, for example:
```
PushNotification.configure({
  onNotification: (notificationData) => {
    Alert.alert('Notification pressed!');
  }
}
```
You also can provide some extra data by defining a `userInfo` property when sending a localNotification, but it works only for iOS
