### ISSUE TITLE
How to receive local notification data when app is in foreground.

### ISSUE THREAD

**Issue by shafqatjamil** [zo0r/react-native-push-notification#2116]
Hi, I am scheduling the local notifications on ios. Notifications are triggering on time correctly even app is in foreground. I want to show notification only when app is in background or killed. If app is in foreground I want to show in app notification but I could not find anyway to do it with this package.

**Comment by shafqatjamil** [comment]
According to app documentation " If your app is running in the foreground, notifications are delivered directly to your app. You can then decide whether to handle the notification quietly or alert the user."

**Comment by Dallas62** [comment]
Hi,
Data-only notification are not compatible with local notification.
You can only achieve data-obly notification with a remote notification.
Regards
