### ISSUE TITLE
OnNotification method is not called after application was reopened by clicking push message. 

### ISSUE THREAD

**Issue by malgorzatatanska** [zo0r/react-native-push-notification#2119]
"react-native-push-notification": "^8.0.0",

Steps to reproduce (Android)

1. Application is in the background - onNotification method is triggered when clicking push,
2.  Kill the app.
2. Push notification was sent from firebase.  
3. OnNotification is triggered. 
4. Put the app in the background
4. Push notification was sent from firebase.
5. OnNotification metod was not triggered 

From this time when I receive push in the background or in the foreground onNotification method is not called. 

When I kill the app and open again by clicking application's icon everything works fine. OnNotification is called in background and foreground. But again when I receive push when app is closes/killed, first onNotification is called but every next push do not trigger onNotification method. 

It’s like by clicking push when app is closed, it is not correctly loaded or something. 

Has anyone had this problem? 
Really i have no idea what i'm doing wrong.

Index.js file:

```
import { AppRegistry } from "react-native";
import { name as appName } from "./app.json";
import Root from "./src/Root";
import PushNotification from "react-native-push-notification";
import { Importance } from "react-native-push-notification";
import messaging from "@react-native-firebase/messaging";
import * as Sentry from "@sentry/react-native";

PushNotification.createChannel(
    {
        channelId: "chat-channel", // (required)
        channelName: "chat channel", // (required)
        importance: Importance.HIGH, // (optional) default: Importance.HIGH. Int value of the Android notification importance
    },
    created => console.log(`createChannel returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
);

messaging().setBackgroundMessageHandler(async remoteMessage => {
    PushNotification.localNotification({
        title: "My Notification Title", // (optional)
        message: "My Notification Message", // (required)
        channelId: "chat-channel",
    });
});

PushNotification.configure({
    onRegister: function (token) {
        console.log("TOKEN:", token);
    },

    onNotification: function (notification) {
        console.log("NOTIFICATION:", notification);

        if (notification.userInteraction) {
            console.log("powiadomienie zosalo klikniete plik js");
        }
    },

    onAction: function (notification) {
        console.log("ACTION:", notification.action);
        console.log("NOTIFICATION:", notification);
    },

    onRegistrationError: function (err) {
        console.error(err.message, err);
    },

    // IOS ONLY (optional): default: all - Permissions to register.
    permissions: {
        alert: true,
        badge: true,
        sound: true,
    },

    popInitialNotification: true,
    requestPermissions: true,
});

AppRegistry.registerComponent(appName, () => Root);
```

Thanks for help.

**Comment by malgorzatatanska** [comment]
Ok i solved the problem. It was connected with SplashActivity. When i added launchMode="singleTask" in AndroidManifest everything started working.

**Comment by ivangonzalezg** [comment]
Hi @malgorzatatanska can you share your manifest? I'm facing the same error
