### ISSUE TITLE
How to get remote notification event when app is in foreground

### ISSUE THREAD

**Issue by jitenderchand1** [zo0r/react-native-push-notification#212]
How to catch remote notification when app is in foreground. Is there any event for this.

**Comment by hugomosh** [comment]
Is the same method **onNotification**

´´´
PushNotification.configure({

    // (optional) Called when Token is generated (iOS and Android)
    onRegister: function(token) {
        console.log( 'TOKEN:', token );
    },

    // (required) Called when a remote or local notification is opened or received
    onNotification: function(notification) {
        console.log( 'NOTIFICATION:', notification );
    },
´´´

**Comment by drpiou** [comment]
`onNotification` is called when the app is opened, but not when it was closed and the notification clicked on android...
