### ISSUE TITLE
Notification not showing app icon in notification bar instead showing different Icon

### ISSUE THREAD

**Issue by jitenderchand1** [zo0r/react-native-push-notification#213]
App Icon not showing in notification bar instead showing some different icon. When I use localNotification then it show the app icon but there is one more small icon. How to get rid of it.

![screen shot 2016-09-22 at 11 14 33 am](https://cloud.githubusercontent.com/assets/19687185/18738065/d4c8bb38-80b5-11e6-958e-d5e6aa237bd5.png)

**Comment by jesseditson** [comment]
In the JSON you send to gcm, include an "icon" key in the "notification" hash, and include a white-masked icon in your app under `res/(mdpi|hdpi|ldpi|etc...)`.

FWIW, this library is unrelated to showing icons in the notification bar, so this issue can probably be resolved.

Relevant android docs are here: https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar.html good luck!
