### ISSUE TITLE
onRegister is not triggered if requestPermissions = false

### ISSUE THREAD

**Issue by dzpt** [zo0r/react-native-push-notification#2132]
If i set `requestPermissions: true`, `onRegister` and `onRegistrationError` will be called everytime i open the app.
It won't happen if `requestPermissions: false`

Tested on ios real device (iPhone XR)
```
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-push-notification@8.0.1
```
might related to #1052 error

**Comment by wmcbain** [comment]
Isn't that a feature? You would have to make a later call to `requestPermissions` if you set `requestPermissions: false` in the config.
