### ISSUE TITLE
Android appcompat bad dependency

### ISSUE THREAD

**Issue by cristianoccazinsp** [zo0r/react-native-push-notification#2134]
# Bug

Sorry for skipping the template, but this is pretty critical and just a config issue.

This library requires appcompat:1.+, as seen here:
```
+--- project :react-native-push-notification
|    +--- androidx.appcompat:appcompat:1.+ -> 1.4.0-alpha03 (*)
```

Now, because of this, ` 1.4.0-alpha03 (*)` is being downloaded. This version does not work with RN 0.65 (and possibly others) and ends up crashing text fields.

Please make sure to either not set the appcompat:appcompat dependency, or use a more restrictive one.

**Comment by cristianoccazinsp** [comment]
Also, for anyone having issues with this, update your build.gradle and set a fixed version:

```
implementation ("androidx.appcompat:appcompat:1.3.1") {
        version {
            strictly '1.3.1'
        }
    }
```
(or w/e version works for you)

**Comment by Dallas62** [comment]
Hi @cristianoccazinsp 
I do not understand how you can get this.

```gradle
dependencies {
    // Use either AndroidX library names or old/support library names based on major version of support lib
    def supportLibVersion = safeExtGet('supportLibVersion', '27.1.1')
    def supportLibMajorVersion = supportLibVersion.split('\\.')[0] as int
    def appCompatLibName =  (supportLibMajorVersion < 20) ? "androidx.appcompat:appcompat" : "com.android.support:appcompat-v7"

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation "$appCompatLibName:$supportLibVersion"
    implementation 'com.facebook.react:react-native:+'
    implementation 'me.leolin:ShortcutBadger:1.1.22@aar'
    implementation "com.google.firebase:firebase-messaging:${safeExtGet('firebaseMessagingVersion', '21.1.0')}"
}

```

You probably have `supportLibVersion` define.

**Comment by cristianoccazinsp** [comment]
Hmm, looks like you are correct. The 1.+ comes from the `supportLibVersion` variable rather than from this package itself. My bad, thanks for clarifying it!
