### ISSUE TITLE
Android cancelLocalNotification not working

### ISSUE THREAD

**Issue by oguzhan10** [zo0r/react-native-push-notification#2135]
Hello, 

When I am trying to cancel notification.

`PushNotification.cancelLocalNotification(id);` I also used this
`PushNotification.cancelLocalNotification({id:id});`

I get this error.

`TypeError: _reactNativePushNotification.default.cancelLocalNotification is not a function. (In '_reactNativePushNotification.default.cancelLocalNotification(id)', '_reactNativePushNotification.default.cancelLocalNotification' is undefined)`

`TypeError: _reactNativePushNotification.default.cancelLocalNotification is not a function. (In '_reactNativePushNotification.default.cancelLocalNotification({
        id: id
      })', '_reactNativePushNotification.default.cancelLocalNotification' is undefined)`

npm version 6,14,9
node version v15.2
"react-native-push-notification": "^7.0.0"
"react-native": "0.63.4",

When I create a schedule.
`
 PushNotification.localNotificationSchedule({
        channelId:"channel", // (required)
        title:"title",
        invokeApp: true,
        date: date, 
        id: uu, //uuid string
        message: "message", 
        allowWhileIdle:false,
      });
`
Android Studio properties
`
android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"

    defaultConfig {
        applicationId "com.example.myapplication"
        minSdkVersion 23
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"
    }
`

**Comment by Dallas62** [comment]
Hi,
Please upgrade your dependencies and clean the cache.
Regards

**Comment by oguzhan10** [comment]
@Dallas62 I upgrade  to  "react-native-push-notification": "^7.4.0", But still getting error.

**Comment by Dallas62** [comment]
So check the documentation to the tag 7.4.0, or upgrade the dependency to the latest version.
CHANGELOG will provably help you to find the issue.
Regards

**Comment by serdargun** [comment]
@oguzhan10 Did you solve the problem?

**Comment by Dallas62** [comment]
Hi @serdargun 
As written,
Please use the readme of YOUR version (navigate with the tag).
OR upgrade to the latest version.
Also refer to the CHANGELOG.
Regards

**Comment by serdargun** [comment]
Hi @Dallas62 
I am already using the latest version.

**Comment by Dallas62** [comment]
If so, clear your cache or provide a full description of your issue.
