### ISSUE TITLE
onNotification can't trigger with Firebase remote notification on background.

### ISSUE THREAD

**Issue by Fanthall** [zo0r/react-native-push-notification#2137]
# Bug
I try to detect remote notifications and save them on localstorage but when I try to send notification while app is on background can't print the anything on log screen. Is there any solution for this. 
Device: Android

**Comment by Dallas62** [comment]
Please take a look at TROUBLESHOOTING or provide a reproducible exemple.
Everything work as expected on exemple project.
Regards
