### ISSUE TITLE
How to group remote notifications in Android

### ISSUE THREAD

**Issue by rakesho-vel** [zo0r/react-native-push-notification#2138]
# Question
I have implemented React Native Push notifications in my react native app, and i was checking how the notifications are grouped in a channel. The way currently happens is:
On Android 8-10, app groups the notifications as soon as second notification arrives, 
But in Android 10+, it takes at least 4 messages to do so.

I looked into the code in [ReactNativePushNotification module](https://github.com/zo0r/react-native-push-notification/blob/fcc229dceb5dfe24f3a011d1c3bf9f82a0b5badc/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L301) to see how grouping works and it seems, library takes group parameter from the notification payload but even if i am passing the `group` parameter, library is not respecting that.

There is another parameter i found in React Native firebase documentation - `collapse_key` ([Firebase Doc](https://firebase.google.com/docs/cloud-messaging/http-server-ref)) which does the same job, but there is no code to use this key in the RN library.

Did anyone implemented the grouping behavior for remote push notifications? Any help would be much appreciated.

**Comment by andidev** [comment]
Group is not supported for remote notifications. colapse_key does something different if you read the docs.
You need to send data messages and create local notifications yourself to allow grouping. Or is grouping not working for local notifications as well?

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification/issues?q=is%3Aissue+group+summary

**Comment by rakesho-vel** [comment]
Oh i miss read the collapse_key :), No i did not try handling the notifications locally, will try that and see. Thanks for the details.
