### ISSUE TITLE
notification_foreground = true does not respect notification.android.tag on Android in foreground

### ISSUE THREAD

**Issue by andidev** [zo0r/react-native-push-notification#2139]
So I set the setting in AndroidManifest.xml
```xml
<meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground" android:value="true"/>
```

The I put my app in foreground and send messages with firebase admin with a tag
```js
 await firebase.messaging().send({
        notification: {
            title: 'Hej Anders!',
            body: 'Ser du mig???',
        },
        token: '******',
        android: {
            priority: 'high',
            notification: {
                channel_id: 'DELIVERY_NOTIFICATIONS',
                tag: 'DELIVERY',
            },
        },
    });
```

If my app is in background notifications are not stacked and they overwrite each other. 
After sending two notifications calling `PushNotification.getDeliveredNotifications` shows correctly one notification:
<img src="https://user-images.githubusercontent.com/571389/132664065-93f0db8a-fae4-45c9-bb46-eaf7babcda11.jpg" width=25% height=25%>

If my app is in foreground notifications gets stacked and there are multiple notifications in the notification bar. So tag is not respected. 
After sending two notifications calling `PushNotification.getDeliveredNotifications` shows incorrectly two notification:

<img src="https://user-images.githubusercontent.com/571389/132664239-dc7d28ad-514b-4d4e-b189-84376cfa83c7.jpg" width=25% height=25%>

However when creating a local notification in foreground with PushNotification.localNotification like this the tag seems to be respected and only one notification is visible no matter how many times PushNotification.localNotification is called. 
```js
PushNotification.localNotification({
    channelId: 'DELIVERY_NOTIFICATIONS',
    id: '123',
    tag: 'DELIVERY',
    title: "My Notification Title", // (optional)
    message: "My Notification Message", // (required)
    autoCancel: true, // Remove when user press notification
});
```
I would expect same behavior in the remote notification foreground case as well. I checked the code and did not find the reason. Both remote and local notification logic ends up calling `RNPushNotificationHelper .sendToNotificationCentre`. So I dont see why it is happening.

**Comment by Dallas62** [comment]
Hi @andidev 
It's not overided because there is different id.
Check #1947
Actually I'm not able to reproduce this case (identifier: 0).
A reproducible exemple is welcome.
Regards

**Comment by andidev** [comment]
@Dallas62 
I created a fresh new project and it behavious the same way. You can find it here:
https://github.com/andidev/notificationbug
just replace the `google-services.json` file and create a new app and then send remove notifications when app is in foregeound to it with tag set to somthing. The notificaitons will stack.

This is how i send the notifications: 
```js
import firebaseAdmin from 'firebase-admin';

const firebaseAdmin = firebaseAdmin.initializeApp({
        credential: firebaseAdmin.credential.cert(firebaseConfigProd),
        databaseURL: 'xxx',
    }, 'driversapp');

await firebase.messaging().send({
    notification: {
        title: 'Test!',
        body: 'Teasdasstar',
    },
    // token: 'cgnPEKT6QaGUxSJmAJB0xdk:APA91bHk4Zd1V8SheznpWExJQPY_ZaAlG-eMe_L_4F-FbnxGVnW-wjciIn-ZINKO-vRlTpYfL9zh2kaH8X91ZKcZlmLWBy0GCGNe3FWzSXV_cFlBKZILfnS515ZCypB_A06I0zmXwhWM',
    token: 'dUzaaJARQ4uKuKJiEyFg9I:APA91bF25Z4SA8VfGl9N4lITahxDqUbqTEk6mEW7YLlaoA1H4L27v28GS5gzOporWQoJsyAiSJAOug_Et16ZLVLm_J_F1VzLZmJ5S7tOiAIYWdkwEsHReU_4hg5hZBXlawq_xjIMYG4a',
    android: {
        priority: 'high',
        notification: {
            channel_id: 'DELIVERY_NOTIFICATIONS',
            tag: 'DELIVERY',
        },
    },
});

```


Also what do you mean with this?
```
Actually I'm not able to reproduce this case (identifier: 0).
```
When sending remote notifications identifier always seems to be set to 0. Even when tag is not set. Tag seems to get autogenerated to some random value but identifier stays 0. And that is ok since tag is the ones that should tell if notification should be stacked or not.

Maybe you misunderstood me the first case I mentioned in issue with image was a correct scenario when app is in background.
The second case when app is in foreground and sending two remote notifications is the bug.

**Comment by Dallas62** [comment]
If a notification has the same ID (here 0) they are replaced. If not, it's two different notifications.

**Comment by andidev** [comment]
Well that is not the case when receiving remote notifications when tag is not set. This is when I send 2 remote notifications:
<img src="https://user-images.githubusercontent.com/571389/132701261-06e589a2-a991-470a-a2d9-c9a4d5149b17.jpg" height="25%" width="25%" />

**Comment by andidev** [comment]
> If a notification has the same ID (here 0) they are replaced. If not, it's two different notifications.

And if this is the case then when receiving remote notifications when app is in foreground and tag is the same as an already received notification the new notification should look up the identifier of current notifications with same tag and reuse that identifier so it does not create two notifications since tag is the same.

**Comment by andidev** [comment]
Ah ok I get it. Tag is not implemented in the local notification case.
It works for me in the local notification case because I set id to '123' every time. But tag is ignored.
In the remote background case it works because then it is android it self handling the notifications and there the tag is respected and works. And the identifier 0 for non tag remote notification is the same since it is handled by android it self I guess.

@Dallas62 
So this issue should be tag is not correctly implemented for local notifications on android. Or is this intensional?
