### ISSUE TITLE
head-up notification when app is killed or in background through google FCM

### ISSUE THREAD

**Issue by jitenderchand1** [zo0r/react-native-push-notification#214]

**Comment by jitenderchand1** [comment]
I have tried following code in notification builder but it did not work

.setDefaults(Notification.DEFAULT_ALL)

**Comment by med1994** [comment]
hi bro go to settings and active the notification access for your appl

**Comment by prajwalmw** [comment]
@med1994 This worked for me. Need to go to settings and select banners under all categories. This was manually bt how can we do it programmatically for all the devices.
