### ISSUE TITLE
cancelLocalNotification does not cancel a notification with tag

### ISSUE THREAD

**Issue by andidev** [zo0r/react-native-push-notification#2140]
Create a local notification with tag
```js
PushNotification.localNotification({                        
    channelId: 'DELIVERY',                                 
    id: '123',                                             
    tag: 'DELIVERY',                                       
    title: "Title",                                        
    message: "Message"                                    
});                                                                
```

Try to cancel it with the id as documented:
```js
PushNotification.cancelLocalNotification('123');   
```

It does not get cancelled. If I dont add a tag to the notification using cancelLocalNotification works.

**Comment by Dallas62** [comment]
Hi @andidev 

For delivered notification, you can use:

```js
PushNotification. clearNotification(tag, id);
```

Regards

**Comment by andidev** [comment]
I tried that as well byt it throws an error unfortunately.

**Comment by KoreanThinker** [comment]
@andidev Did you solved?

**Comment by andidev** [comment]
@KoreanThinker unfortunately not. I had to switch to switch to notifee which in turn also have some similar cancelation bug 😂

**Comment by cynde** [comment]
use cancelLocalNotifications({id: 1})
