### ISSUE TITLE
iOS Scheduled Local Notification Vibrates But Doesn't Appear

### ISSUE THREAD

**Issue by tgreco** [zo0r/react-native-push-notification#2142]
# Bug

Scheduling a local notification and I can hear it vibrate when it goes off. But it doesn't show up in the notifications list nor does the onNotification callback fire.

## Environment info

Running on iOS real device.
"@react-native-community/push-notification-ios": "^1.10.0",
"react-native-push-notification": "^8.1.0",
"react-native": "^0.63.2",

...

Describe what you expected to happen:

Expected the notification to appear.

## Reproducible sample code

```
// Cancel previous notifications
    PushNotification.cancelAllLocalNotifications();

    const scheduleDate = new Date(Date.now() + ((minutesAfterDate * 60) * 1000));
    console.log('Scheduled date: ' + scheduleDate.toString());

    // Schedule it
    PushNotification.localNotificationSchedule({
      message: message,
      date: scheduleDate,
      allowWhileIdle: true,
      playSound: true,
      userInfo: { },
    });

    PushNotification.localNotificationSchedule({
      message: message,
      date: scheduleDate,
      allowWhileIdle: true,
      playSound: true,
      userInfo: { },
      repeatType: 'day'
    });

    PushNotification.getScheduledLocalNotifications((notifications) =>
    {
      console.log(notifications);
    });
```

**Comment by Dallas62** [comment]
Hi @tgreco 
Please search in issue history or in the exemple project.
All cases already answered a lot of times.
Regards

**Comment by Dallas62** [comment]
Also it's for iOS, so please take a look to the iOS repository.

**Comment by tgreco** [comment]
> Also it's for iOS, so please take a look to the iOS repository.

@Dallas62 I checked the iOS example and my code to schedule a local notification is almost identical. 


> Hi @tgreco
> Please search in issue history or in the exemple project.
> All cases already answered a lot of times.
> Regards

I searched the other issues and did not find a single one with the same issue as this. 
Please link me since you already found it!

**Comment by tgreco** [comment]
For anyone else running into this @Dallas62 won't help you.
The issue was there was no title parameter in my notification.
Passing in a title makes it appear in the notifications list.
