### ISSUE TITLE
android app not called 'onNotification' after using 'BackHandler.exitApp()'

### ISSUE THREAD

**Issue by kwangjaeyoo** [zo0r/react-native-push-notification#2144]
After using BackHandler.exitApp() the app is moved into the background and onNotification callback is not triggered anymore.

**Comment by kwangjaeyoo** [comment]
example source is same issue 

Closed app with back key is not receive 'onNotification'

**Comment by kwangjaeyoo** [comment]
component/index.js 

106 line  "isPopInitialNotification" value is true after BackHandler.exitApp()

  const handlePopInitialNotification = (state) => {
    if('active' !== state) {
      return;
    }

    if (options.popInitialNotification === undefined || options.popInitialNotification === true) {
      this.popInitialNotification(function(firstNotification) {

        if(this.isPopInitialNotification) {
          return; // return this line !!
        }
        
        this.isPopInitialNotification = true;
        
        if (!firstNotification || false === firstNotification.userInteraction) {
          return; 
        }
        
        this._onNotification(firstNotification, true);
      }.bind(this));
    }
  }

**Comment by Dallas62** [comment]
Hi @kwangjaeyoo 
If the application is not killed, this is the expected behavior.
The Initial Notification is the one that start the application.  Not all the notification that bring back to foreground the app.
Regards
