### ISSUE TITLE
onNotification Clicked

### ISSUE THREAD

**Issue by mdrajibsk8** [zo0r/react-native-push-notification#2145]
PushNotification.configure({
        onNotification: function(notification) {
            const { data } = notification;
            console.log("notification received >>>>>>>>>>>>>>>")
        }
      ]});

this onNotification is called when a notification arrived and it is also called when notification is clicked. So basically I can't find a way to handle notification clicked. After clicking on the notification it will go to a specific screen however, with this I don't think it is possible because it automatically going to that specific screen after receiving notification. What I want is after clicking on notification it will happen. Please help me with this. 

"react": "17.0.2",
"react-native": "0.64.2",
"react-native-push-notification": "^8.1.0",

**Comment by Dallas62** [comment]
Please search in issue history,
Answered a loooot of times.
Regards
