### ISSUE TITLE
Execution failed for task ':app:checkDebugDuplicateClasses'. Not worked .Buildtime error 

### ISSUE THREAD

**Issue by joy-mollick** [zo0r/react-native-push-notification#2146]
Not compatible with firebase packages or any other packages . All time give error ,no working solution found. Some comments say change  implementation 'com.google.firebase:firebase-analytics:19.0.1' some comments say change that ,some comments say change this , some comments say change your all things .But I want to say plz change this package or fix these errors of library or just close this package . I struggled so much but not getting working example. I think package should be changed .

**Comment by Dallas62** [comment]
Also, without information, we can't investigate.
Regards

**Comment by joy-mollick** [comment]
Duplicate class com.google.android.gms.internal.firebase_messaging.zzf found in modules classes.jar (com.google.firebase:firebase-iid:20.0.2) and classes.jar (com.google.firebase:firebase-messaging:22.0.0)

Here is issue ,now plz investigate .Fix this issue

**Comment by Dallas62** [comment]
Hi,
I'm not available for now, AND it's actually YOUR issue, first time reported.
YOU have to investigate!
if you have this issue, it's probably caused by YOUR graddle configuration.
And as mentioned you should search in issue history (of both repository) to search similar issue (or stackoverflow).
Regards

**Comment by joy-mollick** [comment]
There are so such issues and strugglers with this problem available but there is also no solution . When I use implementation 'com.google.firebase:firebase-analytics:19.0.1' there is no build problem ,but not shown notification on android >9 .But If I used 17.3.0 version as recomended . Then it gives error , is this my build.gradle problem ????? I am using latest firebase project and latest push notification also .

**Comment by BogdanHossu** [comment]
@joy-mollick how is your build.gradle looks like? I had the same issue and it was because i defined firebaseMessagingVersion to + instead of the default version 21.1.0.
