### ISSUE TITLE
Specific time in week repeatType

### ISSUE THREAD

**Issue by ilyasbat** [zo0r/react-native-push-notification#2147]
Is that possible? 

```
 PushNotification.localNotificationSchedule({
      date: date,

      channelId: ANDROID_CHANNEL_NAME,
      id: id, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      vibrate: true,
      vibration: 300,
      title: title, // (optional)
      message: message, // (required)
      userInfo: {screen: 'blabla'},
      soundName: 'bell.mp3', 
      repeatType: 'week',
      allowWhileIdle: true,
    });
```
I use these codes but the time is not set. 00:00 appears as the notification time. Can't I set weekly notifications at different times on the same day?

**Comment by Dallas62** [comment]
Hi,

The time of the notification is the one defined in `date`. It cannot be different on each repetition.

Regards

**Comment by ilyasbat** [comment]
Thanks. I decide to schedule again after every notification.

**Comment by Dallas62** [comment]
Take care of the number of notification you define, in iOS it's 64, and on Samsung too if I remember correctly.
If this exceed, notifications will not trigger (even if set sooner than other) or it will never trigger a notification (depend on manufacturers).

**Comment by Dallas62** [comment]
Take care of the number of notification you define, in iOS it's 64, and on Samsung too if I remember correctly.
If this exceed, notifications will not trigger (even if set sooner than other) or it will never trigger a notification (depend on manufacturers).

**Comment by ilyasbat** [comment]
A scheduled notification is canceled automatically. If an old notification was not canceled. I cancel so i think no problem in this situation. Totally 40 notifications set.

**Comment by cynde** [comment]
> Thanks. I decide to schedule again after every notification.

Hi how do you schedule again after every notification? Because I need to do it too but cannot find a way since onNotification() in index.js only called if a notification is clicked.

**Comment by zeeshan112233** [comment]
Hi, @cynde  did you manage to figure this out? I also need to do something on a notification received without clicking it.

**Comment by cynde** [comment]
@zeeshan112233 hi. still don't find it. I managed to use other way without using react-native-push-notification's feature.

**Comment by anhquan291** [comment]
> @zeeshan112233 hi. still don't find it. I managed to use other way without using react-native-push-notification's feature.

Hi @cynde. Could you please share the way you handle this issue? Really appreciate that. Thanks
