### ISSUE TITLE
Stick notification to the foreground for a specified duration

### ISSUE THREAD

**Issue by nfmshow** [zo0r/react-native-push-notification#2149]
Hi, first I would like to thank you for this library. Its really awesome.

I want to know if its possible to have a local notification stick to the foreground for a specified duration of time. (e.g A whatsapp call notification)

When I set the 'ongoing' property as 'true', it sticks to the notification tray but only stays on the foreground for about 3-5 seconds.

**Comment by danilhendrasr** [comment]
Hi did you manage to find a solution or workaround for this? I'm facing a similar issue and can't really figure out the solution/workaround.

**Comment by nfmshow** [comment]
No. I haven't found any solution to it.

**Comment by Olha-Khomlyak** [comment]
As option, `repeatType:"time"` and  `repeatTime:"milisec"` options  can be used to reopen notification. Not exactly "ongoing" but does the work.
