### ISSUE TITLE
Android notification action reply input not returning reply_text

### ISSUE THREAD

**Issue by gshenar** [zo0r/react-native-push-notification#2152]
# Bug

When pushing a notification on Android with a reply action, I am not getting the reply_text back. The notification pops up on the device with the reply action, I can enter a message and click send, but the notification that the application receives, has no "reply_text" field with the message that was typed in. 

On iOS this working fine, I see the reply_text field and can handle it accordingly. Any idea why this could be broken?

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 681.73 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: * => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version:     "react-native-push-notification": "^8.1.0",

## Steps To Reproduce

1. Send a notification
``` 
PushNotification.localNotification({ title, message, userInfo, actions: ["ReplyInput"], reply_palceholderText: "placeholder", reply_button_text: "Reply" })
```
2. Notification received on device
3. Press the reply button and submit a message
4. Notification handler triggers on device and returns notification without a "reply_text" field, but has everything else

Describe what you expected to happen:

1.  Expected to get reply_text in the notification object with the message I typed in (works in iOS)

**Comment by TongManhCong** [comment]
reason in file RNPushNotificationAcions can't get text in remoteInput => can't callback to js. 

**Fix:**
In filepath: _"node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java"_

**edit** 
      Intent actionIntent = new Intent(context, RNPushNotificationActions.class);
**to**
      Intent actionIntent = new Intent(context, com.dieam.reactnativepushnotification.modules.RNPushNotificationActions.class);

and 

**edit** 
      int flags = Build.VERSION.SDK_INT >= Build.VERSION_CODES.M ? PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE : PendingIntent.FLAG_UPDATE_CURRENT;
**to**
      int flags = PendingIntent.FLAG_UPDATE_CURRENT;

**Comment by redexp** [comment]
@TongManhCong thanks! For me, edit flags was enough

**Comment by redexp** [comment]
Downgrade to `8.0.1` also fixes issue

**Comment by cristianoccazinsp** [comment]
@redexp @TongManhCong what happens if you replace `PendingIntent.FLAG_IMMUTABLE` with `PendingIntent.FLAG_MUTABLE` instead? Does that also fix the issue?  If so, that should be the actual change so it works with all SDKs.

**Comment by ammarahm-ed** [comment]
@chrisspankroy The intent becomes mutable, meaning the values can be changed added to the intent which is required for the reply input to send data on user action.

**Comment by Dallas62** [comment]
> Changing it to mutable should fix it I believe.

```
                    int flags = Build.VERSION.SDK_INT >= Build.VERSION_CODES.M ? PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_MUTABLE : PendingIntent.FLAG_UPDATE_CURRENT;
                                                                                                                                  ^
  symbol:   variable FLAG_MUTABLE
  location: class PendingIntent
```

Nope 🙃

**Comment by Dallas62** [comment]
It's working if we use the API version 31, but not with API 30.
![image](https://user-images.githubusercontent.com/3429329/140481690-41eff28c-57fc-40d0-aa52-3264a83fcca3.png)
The only way to avoid this is to force developer to upgrade to target API 31, and also remove some `targetCompatibility JavaVersion.VERSION_1_8`

**Comment by Dallas62** [comment]
I wondering if someone can test this version:
```
yarn add zo0r/react-native-push-notification#dev
```

The CHANGELOG is available here: https://github.com/zo0r/react-native-push-notification/blob/dev/CHANGELOG.md#unreleased

**Comment by cristianoccazinsp** [comment]
Next RN version will also force SDK 31. So it’s a good idea to get ready for it.

For our app, android 12 was full of UI issues that could only be corrected using SDK 31.

**Comment by BradSmith252** [comment]
Awesome post! Thanks for posting such informative stuff. Really I’m so excited to read such depth article on push notifications.
