### ISSUE TITLE
I need to reject a remote notification. How?

### ISSUE THREAD

**Issue by eleonne** [zo0r/react-native-push-notification#2156]
# Question

So, I want my app to trigger test notifications for certain users. Its like a test before the real thing.

I thought I could do that by handling the onNotification event, but this event triggers AFTER the notification is created. I would like to prevent the notification if I send a flag in the data property

Something like

```
onNotification:` function (notification) {
    if (notification.data.isTest === 'Yes')
        // Do nothing
},

```

**Comment by Dallas62** [comment]
Hi,
Send data-only notification, and trigger a local notification if conditions are met.
Regards
