### ISSUE TITLE
local push notification not working when app is terminated and using another app

### ISSUE THREAD

**Issue by yjb94** [zo0r/react-native-push-notification#2157]
# Bug
local push notification not working when app is terminated and using another app.

## Environment info

`react-native info` output:
```bash
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 42.70 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: ^7.4.0

## Steps To Reproduce

1. swipe-up and close(terminate) the app.
2. run another app(any other app)
3. send push from server
4. push notification will never arrive

if you skip `2. running another app`, local notification will arrive fine.
my app has a back-end server which sends fcm in silent way(data only). and I use that data and send a local push notification.
any solutions?

**Comment by Dallas62** [comment]
Please search in issues, if this is an issue from the library we probably noticed it before.
Regards

**Comment by abbasmoosavi** [comment]
set "priority": "high" in data message notification
