### ISSUE TITLE
Building to android emulator failing.

### ISSUE THREAD

**Issue by mildfuzz** [zo0r/react-native-push-notification#2160]
I am seeing the following error when running `react-native run-android`

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl2072621848.tmp/base.apk (at Binary XML file line #80): com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present
```

Does this mean anything to anyone?

**Comment by phillipkey** [comment]
`requires that an explicit value for android:exported be defined when intent filters are present`

I'd try adding `android:exported="false"` in the service tag.

**Comment by mildfuzz** [comment]
This is what the `app/android/app/src/main/AndroidManifest.xml:39` looks like now

![image](https://user-images.githubusercontent.com/196705/134761803-4c928241-774a-4098-8829-3a884f9abed1.png)

**Comment by yuvraj-scalex** [comment]
Set android:exported="true" or android:exported="false" to activity tag under AndroidManifest.xml file.

**Comment by jimmysafe** [comment]
@mildfuzz did you find a solution to this? 
I am still having this issue: i have tried to add `android:exported="false"` both in debug and main manifest file but i still get the error.

**Comment by kabus202** [comment]
@jimmysafe found any solution yet? facing the same issue

**Comment by qadirali876** [comment]
Having same issue 
 * What went wrong:
Execution failed for task ':app:installDebug'.
> java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl1858654457.tmp/base.apk (at Binary XML file line #39): com.stepout.MainActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present
```

**Comment by dibyopra** [comment]
any solution ?

**Comment by qadirali876** [comment]
YES

**Comment by qadirali876** [comment]
add the following code in activity file

 android:exported="true"

**Comment by aryalprakash** [comment]
adding `android:exported="true"` on receiver worked for me.

`<receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">` should be
`<receiver android:exported="false" android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver"> `

**Comment by ankitOnecode** [comment]
I have tried both the way by adding false and true but still getting the same error.

* What went wrong:
Execution failed for task ':app:installDebug'.
> java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl82705364.tmp/base.apk (at Binary XML file line #361): com.freshchat.consumer.sdk.receiver.FreshchatReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present
