### ISSUE TITLE
onNotification is not trigger when press in a notification after app killed

### ISSUE THREAD

**Issue by finn1310** [zo0r/react-native-push-notification#2161]
I want to navigate to special screen when press in a notification. It's working in foreground, background. However, when app killed is not working.
## Steps:
1. Open app, push localNotification. Notification is shown in "Notification Center".
2. Kill app.
3. Press in that notification then only reopen app but onNotification is not working.

**Comment by Dallas62** [comment]
Please search in issue history !
Regards
