### ISSUE TITLE
Question about localNotification on Android

### ISSUE THREAD

**Issue by guaaak** [zo0r/react-native-push-notification#2162]
Hi team,

I set up everything correctly on android, but the local push notification is not working. Is there any clue of this issue?
I created channel at beginning of app.
Also tried to use firebase to send notification and it worked.

Thanks!

**Comment by Dallas62** [comment]
Hi,
If it's not working is probably because you missed a mandatory parameter or not calling the method.
Regards

**Comment by anggaprytn** [comment]
> Hi,
> 
> ```
> const handleNotification = () => {
>         PushNotification.localNotification({
>             channelId: 'channel-id',
>             title: 'test',
>             message: 'My Notification Message',
>         });
>     };
> ```
> 
> Here is the function for push local notification, and I used a Pressable to trigger this function. Everything works fine on ios simulator but there are no responses on android after pressing the button.

Which version RNPN are you using?

**Comment by guaaak** [comment]
I'm current using "react-native-push-notification": "^8.1.0", but I tried like 8.0.1 and 7.x.x something. They are also not working for me...

**Comment by anggaprytn** [comment]
rig

> I'm current using "react-native-push-notification": "^8.1.0", but I tried like 8.0.1 and 7.x.x something. They are also not working for me...

I'm using "react-native-push-notification": "^3.1.9" its work, and i add this PR #2112 full screen intent, work fine

**Comment by Dallas62** [comment]
Did you at least create the channel?

**Comment by guaaak** [comment]
Yes, I created a channal

**Comment by Dallas62** [comment]
Can you share all the code used to trigger the notification ?
The example project is working fine, it's probably something you missed.

**Comment by guaaak** [comment]
Code for creating channel:
```
const createNotificationChannel = () => {
        PushNotification.createChannel(
            {
                channelId: 'channel-id', // (required)
                channelName: 'My channel', // (required)
                channelDescription:
                    'A channel to categorise your notifications', // (optional) default: undefined.
                playSound: false, // (optional) default: true
                soundName: 'default', // (optional) See `soundName` parameter of `localNotification` function
                importance: Importance.HIGH, // (optional) default: Importance.HIGH. Int value of the Android notification importance
                vibrate: true, // (optional) default: true. Creates the default vibration pattern if true.
            },
            created => console.log(`createChannel returned '${created}'`), // (optional) callback returns whether the channel was created, false means it already existed.
        );
    };
```
code in index.js
```
PushNotification.configure({
    onNotification: function (notification) {
        console.log('NOTIFICATION:', notification);
    },
    requestPermissions: true,
});
```

and the above is code for triggering notification, and the function is called on a <Pressable> onPress

**Comment by binobose** [comment]
The same is happening for me as well, I just tried with all the settings as given and followed everything step by step, still nothing happening on Android. Local notifications not showing up at all. No console logs as well. Please advise.

**Comment by Dallas62** [comment]
Did you change the value of:
```
        <!-- Change the value to true to enable pop-up for in foreground on receiving remote notifications (for prevent duplicating while showing local notifications set this to false) -->
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="false"/>
```

To `true` ?

Again `I set up everything correctly on android` doesn't mean everything is set as you want.
A reproducible exemple might help!
Regards.

**Comment by binobose** [comment]
Yes made it to true already.

This is my manifest

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.###">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:screenOrientation="portrait"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustPan">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                  android:value="true"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                  android:resource="@color/white"/>
      <meta-data
          android:name="com.dieam.reactnativepushnotification.default_notification_channel_id"
          android:value="@string/default_notification_channel_id" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED" />
              <action android:name="android.intent.action.QUICKBOOT_POWERON" />
              <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
          </intent-filter>
      </receiver>
        <!-- <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service> -->
    </application>
</manifest>
```
I have copied the NotifService.js and the NotificationHandler.js from the example repo and called the methods exactly as given in the document. As I am working on a functional component, only the object definition in constructor had to be changed as below. Would that make any difference?

  ```
const [state, setState] = useState([])

  const onRegister = token => {
    setState({registerToken: token.token, fcmRegistered: true})
  }

  const onNotif = notif => {
    Alert.alert(notif.title, notif.message)
  }

  const notif = useMemo(() => {
    return new NotifService(onRegister, onNotif)
  }, [])
```

and then I invoked the local notification method on a TouchableOpacity as

`onPress={() => { notif.localNotif()}}`

What else needs to be done from my end? I am using the latest versions.

**Comment by Dallas62** [comment]
I don't understand why everybody want to put no-component features inside a component. You can use a global variable to store the service, this will avoid lifecycle issue and double calls and allow background process in some cases.

To investigate, you can add some extra `console.log` in localNotif, to see if the method is called. If yes, you can look in the Android Log with `adb logcat`, there is probably a message in case of issue.

**Comment by binobose** [comment]
Tried console in localNotif and its showing, but in logcat its showing this error
`2021-10-02 16:06:58.806 348-8203/? E/FMQ: grantorIdx must be less than 3`

**Comment by bulby97** [comment]
@binobose did you find a solution ? Having the same issue

**Comment by binobose** [comment]
> @binobose did you find a solution ? Having the same issue

@bulby97 Infact when I tried it in a real device it worked. I made an apk and installed it in my mobile, it worked without any issue. Just give it a try.
