### ISSUE TITLE
Custom Sound not playing on iOS

### ISSUE THREAD

**Issue by faryalzuberi** [zo0r/react-native-push-notification#2163]
# Bug

Custom sound is playing on Android but not on iOS.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 422.20 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^4.14.0 => 4.14.0 
    react: 16.13.1 => 16.13.1 
    react-native: ^0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    react-native: Not Found
```

Library version: 7.3.2

## Steps To Reproduce

1. Place sound file in project root.
![image](https://user-images.githubusercontent.com/31623560/134893666-0c5a9099-42aa-49d5-8229-8d2c42ca09a5.png)

2. Ensure the tone is added under "Copy Bundle Resources"

![image](https://user-images.githubusercontent.com/31623560/134898067-e18bb2e8-9c56-48cf-8baa-237713645446.png)

Describe what you expected to happen:

1. When the local push notification pops up, the default sound plays on iOS whereas, on Android it works correctly and the custom sound is played. Changing the soundName variable to include the .mp3 extension as suggested on the closed GitHub issue also does not work. https://github.com/zo0r/react-native-push-notification/issues/1435

Note: if the custom sound file is imported and played using the following code snippet it plays. Hence, it is not an iOS issue.

```
import SoundPlayer from 'react-native-sound-player';

SoundPlayer.playSoundFile('tone1', 'mp3');
```

## Reproducible sample code

```
 PushNotification.createChannel(
    {
      channelId: channelId, // (required)
      channelName: channelName, // (required)
      channelDescription: 'A channel to categorise your notifications', // (optional) default: undefined.
      soundName: 'tone1', 
      playSound: true, 
      importance: 4,
      vibrate: true, 
    },
    (created) => console.log(`createChannel returned '${created}'`),
  );
```

**Comment by Dallas62** [comment]
Hi @faryalzuberi 

The name of this part is self explaining:
[Channel Management (Android)](https://github.com/zo0r/react-native-push-notification#channel-management-android)

Please refer to the exemple project where a working iOS exemple is provided.
Regards
