### ISSUE TITLE
What's Tag for the notifications?

### ISSUE THREAD

**Issue by viveKing21** [zo0r/react-native-push-notification#2164]
There's a option for tag attribute...

```
PushNotification.localNotification({
     ....,
     tag: null,
     ...
})
```

what is it for??

actually I want to send remotely, but in case if device is offline, I'll send schedule notification

but I want to override schedule (if it's already showing) with the remote one (FCM)

I found Tag payload with notification can help to override notification with same tag...
but it's not working with this package

FCM tag :- 

_Identifier used to replace existing notifications in the notification drawer.

If not specified, each request creates a new notification.

If specified and a notification with the same tag is already being shown, the new notification replaces the existing one in the notification drawer._

see -->
https://firebase.google.com/docs/cloud-messaging/http-server-ref 

I am not able to do it with tag, but id working instead

is tag same as id in this package???

**Comment by Dallas62** [comment]
Hi,

No `tag` is another concept close to id.

Search in Android documentation for more information.

Regards
