### ISSUE TITLE
on Android 11, push notification is not received when app is killed (not running)

### ISSUE THREAD

**Issue by yasir-syed** [zo0r/react-native-push-notification#2166]
Recently started getting an issue in push notification (esp. Vivo and Nexus), **Push notification is not received when app is not running (killed state)**, as soon as we launch the app, all the notifications appear, its still working fine on Redmi phones and iOS that notification is received in all three states (foreground, launched and in background, not launched or killed).
It appears that this issue started coming on **Android 11**, no user on these devices reported such an issue.

**Comment by yasir-syed** [comment]
@Dallas62 any idea?

**Comment by Dallas62** [comment]
Hi @yasir-syed 
`Push notification is not received when app is not running (killed state)` is not a full description of your issue.
Issue history should help you.
Regards
