### ISSUE TITLE
iOS onNotification for Remote Notification Actions ("Categories") Not Working If App Closed

### ISSUE THREAD

**Issue by Tristan10** [zo0r/react-native-push-notification#2169]
react-native-push-notification: 7.3.1
@react-native-community/push-notification-ios: 1.8.0

I am using a combination of react-native-push-notification and react-native-firebase/messaging (https://rnfirebase.io/messaging/usage) to handle push notifications in my React Native app. The main use of the push notifications is for chat messages. 

**Here is my current structure (modified for brevity):**

    import { AppRegistry, AppState, Platform } from 'react-native';
    // Additional imports here
    
    if (Platform.OS === 'android') {
        PushNotification.createChannel({
            channelId: 'pm-default',
            channelName: 'PartyMe Default'
        });
    }
    
    
    messaging().setBackgroundMessageHandler(async remoteMessage => {
        console.log(remoteMessage);
        if (remoteMessage && remoteMessage.data) {
            switch (remoteMessage.data.type) {
                case NOTIFICATION_TYPES.FRIEND:
                    PushNotification.localNotification({
                        channelId: 'pm-default',
                        group: remoteMessage.data.referenceid,
                        id: remoteMessage.data.devicenotificationid,
                        userInfo: {
                            id: remoteMessage.data.devicenotificationid,
                            ...remoteMessage.data
                        },
                        message: remoteMessage.data.body,
                        title: remoteMessage.data.title,
                        actions: ['Accept', 'Decline'],
                        category: 'invitation',
                        data: remoteMessage.data,
                        invokeApp: false
                    });
                    break;
                case NOTIFICATION_TYPES.INVITE:
                    PushNotification.localNotification({
                        channelId: 'pm-default',
                        group: remoteMessage.data.referenceid,
                        id: remoteMessage.data.devicenotificationid,
                        userInfo: {
                            id: remoteMessage.data.devicenotificationid,
                            ...remoteMessage.data
                        },
                        message: remoteMessage.data.body,
                        title: remoteMessage.data.title,
                        actions: ['Accept', 'Decline'],
                        category: 'invitation',
                        data: remoteMessage.data,
                        invokeApp: false
                    });
                    break;
                case NOTIFICATION_TYPES.MESSAGE:
                    PushNotification.localNotification({
                        channelId: 'pm-default',
                        group: remoteMessage.data.referenceid,
                        id: remoteMessage.data.devicenotificationid,
                        userInfo: {
                            id: remoteMessage.data.devicenotificationid,
                            ...remoteMessage.data
                        },
                        message: remoteMessage.data.body,
                        title: remoteMessage.data.title,
                        actions: ['ReplyInput', 'Mark Read'],
                        reply_placeholder_text: 'Write reply',
                        reply_button_text: 'Reply',
                        category: 'reply',
                        data: remoteMessage.data,
                        invokeApp: false,
                        autoCancel: true,
                        ongoing: false
                    });
                    break;
            }
        }
        return Promise.resolve();
    });
    
    if (Platform.OS === 'ios') {
        PushNotificationIOS.setNotificationCategories([
            {
                id: 'reply',
                actions: [
                    { id: 'text', title: 'Text Input', textInput: { buttonTitle: 'Reply' } },
                    { id: 'read', title: 'Mark Read' }
                ]
            },
            {
                id: 'invitation',
                actions: [
                    { id: 'accept', title: 'Accept' },
                    { id: 'decline', title: 'Decline' }
                ]
            }
        ]);
    }
    
    PushNotification.configure({
        // This is hit in the following cases:
        // Android - Notification clicked while app is in any state
        // IOS - Any notification action (click, action, etc)
        onNotification: (message) => {
            // Handle the above cases
            message.finish(PushNotificationIOS.FetchResult.NoData);
        },
        onAction: (message) => {
            //Handle the different actions (android)
        }
    });
    
    
    AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));

**Push notifications Payload (sent via firebase admin messaging):**

    {
      token: oReceiver.devicetoken,
      data: {
    	referencetype: "user",
    	referenceid: senderid,
    	referencename: oSender.displayname,
    	receiverid: receiverid,
    	type: "friend",
    	notificationid: notification.id,
    	title: "Friend Request",
    	body: oSender.displayname + " invited you to be friends."
      },
      android: {
    	priority: 'high'
      },
      apns: {
    	payload: {
    	  aps: {
    		'content-available': 1
    	  }
    	},
    	headers: {
    	  'apns-push-type': 'background',
    	  'apns-priority': '5',
    	  'apns-topic': 'llc.attebyte.partyme'
    	}
      }
    }

**The problem:** Everything works correctly on Android. On iOS, notifications were working correctly for a few of my test users but as my userbase expanded I got more reports of them not receiving any push notifications. I assume the issue is because of this note in the Apple Docs:

> The system treats background notifications as low priority: you can use them to refresh your app’s content, but the system doesn’t guarantee their delivery. In addition, the system may throttle the delivery of background notifications if the total number becomes excessive. The number of background notifications allowed by the system depends on current conditions, but don’t try to send more than two or three per hour.

Since the notifications are used for chat, there could be a large number of data-only notifications with the content-available flag. It seems weird that this structure works correctly for a few users, but some have never received a single notification. (I have verified they have them turned on.)

**My Current Workaround:** I updated the payload to send a notification + data type push notification for iOS. I rely on the system to display the notification. Unfortunately, the notification actions do not work when the app is in the quit state. When clicking "Reply", or "Accept"/"Decline" in the notification, no function in the index.js is called.

Is there a proper way to handle notification actions on iOS when the app is quit? Android requires data-only messages since there is no "category" equivalent to set up notification actions. They have to be created locally. The iOS categories still work with "notification" type notifications, but I can't figure out how to perform the action. NOTE: For the users receiving notifications, the notification actions work correctly in all app states with the data-only background to local notification flow.

I would be fine with getting either data-only messages working reliably, or figuring out how to handle the actions from notification type messages.

**Comment by Vladislava9009** [comment]
The same issue

**Comment by Dallas62** [comment]
For iOS issues, please use the right repository:
https://github.com/react-native-push-notification/ios
Regards
