### ISSUE TITLE
How get notification event when app is killed or in background

### ISSUE THREAD

**Issue by jitenderchand1** [zo0r/react-native-push-notification#217]
When my app is killed or in background and notification arrives then I want to set some key in storage. So that when user open my app I can show different list.

onNotification event is not working when app is killed or in background

**Comment by ddobby94** [comment]
+1

**Comment by abdurrahmanekr** [comment]
Hi @jitenderchand1 **RNPushNotificationListenerService > onMessageReceived** its worked ! [this commit](https://github.com/Detaysoft/react-native-push-notification/commit/7cf94d441c93c6b7b4faa4692575572b911084be) simple sqlite save
