### ISSUE TITLE
type of id

### ISSUE THREAD

**Issue by voxspox** [zo0r/react-native-push-notification#2170]
# Bug

Library version: 2021-10-05

## Steps To Reproduce

In the docs I can read this:
```
  id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
```
I'm a bit confused about the type of `id` here. The value is `number` while the description say `string`. `getScheduledLocalNotifications` returns also `string`.

In `@types/react-native-push-notification` in `class PushNotificationScheduledLocalObject` says `id: number`

**Comment by Dallas62** [comment]
Hi,

This repository is not responsible of types. Please refer to the repository which store types.

Regards.

**Comment by voxspox** [comment]
@Dallas62 first this module should be clear about the type

**Comment by Dallas62** [comment]
Hi, the correct type is defined in the readme.
Regards
