### ISSUE TITLE
Error - Push authorization request failed

### ISSUE THREAD

**Issue by MauriceNino** [zo0r/react-native-push-notification#2173]
I am working on a react-native project and lately push notifications don't work anymore. 
I have tried upgrading to the latest version of both `react-native-push-notification` and `@react-native-community/push-notification-ios`, but the issue persists.

```ts
// PushNotification.configure called in index.js
PushNotification.configure({
	popInitialNotification: true,
	permissions: {
		alert: true,
		badge: true,
		sound: true,
	},
	requestPermissions: Platform.OS === 'ios',
});

// Somewhere in my component in a useEffect hook I call this:
const {alert} = await PushNotification.requestPermissions(); 

// And it throws the following error
// Error: Error - Push authorization request failed.
```

A quick google research found absolutely nothing about this topic, just the code that generates this error message: https://github.com/react-native-push-notification/ios/blob/master/ios/RNCPushNotificationIOS.m

What's weird is, that the push notifications worked until recently, so naturally I went back in git commit history to find the commit that broke it - but I didn't find a commit that does work anymore (and I made sure to delete the entire node_modules folder before reinstalling). So it seems like something else broke it. I also tested it on another machine, and it does also break there.

Does anyone have any insight on what exactly produces this error, or can give me some hints on how to resolve it?

**Comment by Dallas62** [comment]
Hi @MauriceNino 
You will probably find more information in the repository you linked.
This repository and maintainers here are not responsible/maintainer of the linked repository.
Regards
