### ISSUE TITLE
How to retain notification when app is swipe closed

### ISSUE THREAD

**Issue by Yandamuri** [zo0r/react-native-push-notification#2177]
# Question

Notification is getting removed when app is swipe closed.

Is it possible to retain the notification when app is swipe closed?

**Comment by Perfecto-always** [comment]
I have set ongoing to true while invoking the notification but it is not retained when I remove the app from recents tray

**Comment by ammarahm-ed** [comment]
@Perfecto-always try notifee. I have switched and it works great especially with newer android version 12 and up.

**Comment by Perfecto-always** [comment]
I tried notifee and the issue remains same, the notification doesn't retain when closing the app.

Only time it retain is when I use the `actions` button. After that if I try to close the app after the above step the notification persist.
