### ISSUE TITLE
Is there a way to display a persistent floating notification?

### ISSUE THREAD

**Issue by danilhendrasr** [zo0r/react-native-push-notification#2179]
# Question
Hi, first of all, thank you for the amazing library that you guys created and maintained.

I'm currently trying to implement a persistent floating notification like the following picture:
![images (9)](https://user-images.githubusercontent.com/45989466/137514883-de6fb4f7-586d-4961-82f6-3a1e15994048.jpeg)

I've been digging around the internet for several days and couldn't find the answer if it's possible. I've tried using the `onGoing` params provided by this library but I realized it only persists the notification on the system's notification center, not when when the notification is floating.

I noticed Discord is able to do this with their call notification, so I'm thinking there's got to be a way. But I'm pretty much clueless about the native world, so forgive me if I'm asking something obvious here. My question is, is this behavior achievable by this library? and how? Or do I need to use another library?

**Comment by swcloud1** [comment]
I know this is an old post, but were you ever able to find a fix for this? I'm running into the exact same issue. Any help would be appreciated.

Edit: Nevermind I found the answer [here](https://stackoverflow.com/a/45516069)
