### ISSUE TITLE
Badge icon is not showing in Vivo

### ISSUE THREAD

**Issue by MplussoftTechnologies** [zo0r/react-native-push-notification#2181]
Hi,
Thanks for sharing the library. I have tried to implement it in my application. For some phones, it's working fine but for Vivo badge count is not visible.

Other applications e.g. Facebook, message, etc show the badge count on the same phone.

Any help would be greatly appreciated.
Thanks.

**Comment by siddhiEcosmob** [comment]
@MplussoftTechnologies Have you got the solution for this issue? I'm also facing the same issue in vivo phones badge count is not visible.
