### ISSUE TITLE
Android : localNotificationSchedule with one channel but multiple sounds

### ISSUE THREAD

**Issue by samouds** [zo0r/react-native-push-notification#2186]
Hello,

I have a question, can I schedule multiple notifications with different sounds on the same channel or I need one channel for each sound ?

Thanks

**Comment by Dallas62** [comment]
Hi @samouds 
The channel documentation can be found on Android documentation.
In short, once settings are set (vibration, sound) you cannot change them.
A channel = a sound.

Regards

**Comment by samouds** [comment]
Thanks
