### ISSUE TITLE
on press localNotificaton don't work on android 

### ISSUE THREAD

**Issue by IsmetGlumcevic** [zo0r/react-native-push-notification#2188]
When calling localNotificationSchedule in context provider it works, when calling localNotificationSchedule onPress inside component it doesn't work on android. Ios work well.

MacBook air m1
react-native: 0.64
react-native-push-notification: 8.1.1
react-native-community/push-notification-ios: 1.10.1

index.js

       PushNotification.configure({
             onRegister: function (token) {
                 console.log('TOKEN:', token);
             },
             onNotification: function (notification) {
                console.log('onnn', notification);
                 notification.finish(PushNotificationIOS.FetchResult.NoData);
          },

      permissions: {
        alert: true,
        badge: true,
       sound: true,
       },
      popInitialNotification: true,
       requestPermissions: Platform.OS === 'ios',
      });
      PushNotification.createChannel(
      {
        channelId: 'local-notifications', // (required)
       channelName: 'Local-notifications channel', // (required)
       channelDescription: 'A channel to categorise your notifications', // (optional) default: undefined.
       soundName: 'default', // (optional) See `soundName` parameter of `localNotification` function
       importance: Importance.HIGH, 
       vibrate: true, // (optional) default: true. Creates the default vibration pattern if true.
       },
        created => console.log(`createChannel returned '${created}'`), 
        );`

Contex provider:

       useEffect(() => {
       PushNotification.localNotificationSchedule({
       id: '12333',
       channelId: 'local-notifications',
       title: 'Hat er sein Ziel erreicht 1',
       message: 'poruka',
        repeatType: 'minute',
       date: new Date(),
       });
      }, []);

component 

     const setupNotification = (id, mess, name) => {
          PushNotification.localNotificationSchedule({
           id: id,
           channelId: `local-notifications`,
            title: name,
            message: mess,
           repeatType: 'minute',
             date: new Date(),
        });
      };

          <TouchableOpacity
                  style={FormStyles.button}
                  onPress={() => savePlane()}>
                  <Text style={FormStyles.buttonText}>Einen Plan machen</Text>
         </TouchableOpacity>

**Comment by Dallas62** [comment]
Hi @IsmetGlumcevic 
Please take time to read the README (`onNewIntent`), take a look on the exemple project. Or search for previous issue.
https://github.com/zo0r/react-native-push-notification/issues/1592
Regards

**Comment by IsmetGlumcevic** [comment]
I call this function inside another two functions, there is a lot of code, on ios work well, all parameters all there.

**Comment by IsmetGlumcevic** [comment]
My id looks like 49ty-34rt-44hr-09tu, i need to encode and decode id, now i have a problem my id is always undefined when opening notification.

**Comment by IsmetGlumcevic** [comment]
when opening notification id on ios work only when setting userInfo: {id: '...'},

**Comment by IsmetGlumcevic** [comment]
I have id: '45id-45rr-33hf-34wd', which format can I put in id? I try with dot, comma.... There is function:

     let newId;
     id.split('').map((item, index) => {
      if (id.length - 1 > index) {
        newId += item.charCodeAt() + ',';
      } else {
        newId += item.charCodeAt();
      }
     });

**Comment by Dallas62** [comment]
The fornat/type is described in the readme.

**Comment by trindadematheus** [comment]
here dont working too

onPress call:
```javascript
async function handleComplete() {
  console.log('test')
  PushNotification.localNotification({
    channelId: 'default-channel',
    title: 'testnotify',
    message: 'test'
  })
}
```

my config: 
```javascript
PushNotification.configure({
  permissions: {
    alert: true,
    badge: true,
    sound: true,
  },
  requestPermissions: false,
});
```

**Comment by marcosfreitas** [comment]
@IsmetGlumcevic did you found a solution?
