### ISSUE TITLE
onNotification is triggered but popup is not shown on android

### ISSUE THREAD

**Issue by UmerQur3shi** [zo0r/react-native-push-notification#2189]
Hey, I'm getting this notification from connectycube on android
{"data": {"message": "adsadasdsad", "sound": "default"}, "finish": [Function finish], "foreground": true, "id": "338258801", "userInteraction": false}

The onNotification method is triggered but the popup for notification is not shown, I've done everything according to the given example but still not able to show the popup on notification, please help.

**Comment by UmerQur3shi** [comment]
@Dallas62 why did you close it without answering? :(

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md

**Comment by UmerQur3shi** [comment]
@Dallas62 I just created a channel before PushNotification.configure() and it's working now, Please tell me is it the right way to do it or do I have to create a channel after configuring the PushNotification and do we need to create more than one channel? what I've done to make it work is pasted below...
const setUpPushNotification = () => {
    PushNotification.createChannel(
        {
            channelId: "fcm_default_channel",
            channelName: "push_notification",
        }
    )
    PushNotification.configure({all the configuration code})
}

Without doing PushNotification.createChannel(), I don't get the notification popup when the app is in foreground but the popup appears when the app is in background, your response will be appreciated.

**Comment by Dallas62** [comment]
Hi,
Has written in the Readme, channel must be created before sending a notification.
It's an Android requirement.
The fcm default channel might be created by the Firebase Sdk in some cases. Highly recommend to handle it yourself.
Regards
