### ISSUE TITLE
Can't receive notifications when app is closed or in background

### ISSUE THREAD

**Issue by ddobby94** [zo0r/react-native-push-notification#219]
manifest file:

```
<uses-permission android:name="android.permission.WAKE_LOCK" />
<permission
        android:name="co.my.packagename.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
<uses-permission android:name="co.my.packagename.C2D_MESSAGE" />
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
<uses-permission android:name="android.permission.VIBRATE" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
```

in the application:
         `<meta-data
                android:name="com.google.android.gms.version"
                android:value="@integer/google_play_services_version" />`

```
    `<receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
        <intent-filter>
            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            <category android:name="co.my.packagename" />
        </intent-filter>
    </receiver>`

    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
        <intent-filter>
            <action android:name="android.intent.action.BOOT_COMPLETED" />
        </intent-filter>
    </receiver>


    <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>

    <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
        <intent-filter>
            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        </intent-filter>
    </service>
```

settings.gradle:

`include ':app'
...
include ':react-native-push-notification'
project(':react-native-push-notification').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-push-notification/android')`

build.gradle:

```
dependencies {
    classpath 'com.android.tools.build:gradle:1.2.0'

}
```

`

app/build.gradle
`
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile 'com.android.support:support-v4:19.1.+'
   ...
    compile project(':react-native-push-notification')

```
compile ('com.google.android.gms:play-services-gcm:8.1.0')
```

}

Mainapp.java 

import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;

`@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          ...
          new ReactNativePushNotificationPackage()
      );
    }
  };
`

**Comment by ddobby94** [comment]
bump

**Comment by npomfret** [comment]
What does 'bump' mean?

**Comment by timhonders** [comment]
It seems i have the same problem.

When the app is on the forground an a push message is send from the server onNotification is triggred.
But when the app is on the background there is no notification

**Comment by timhonders** [comment]
I fixed my problem i used an FCM implementation to send the notification.

This plugin can't handle the new mesage structure on the background

**Comment by ddobby94** [comment]
@timhonders could you link the proper fcm implementation method?

**Comment by timhonders** [comment]
It is actually a quickly build GCM implementation is used for testing and successfully received push notification in the background.

I hope it can help u



`class Push {

    public $gcm_url = 'https://android.googleapis.com/gcm/send';

    public $api_key = '';

    private $messages;

    public function __construct($apiKey){

        $this->api_key = $apiKey;

    }

    public function add($message){
        $this->messages[] = $message;
    }

    public function send(){
        $i = 0;
        while (count($this->messages) > 0) {
            echo 'Response: ' . $this->sendMessage($this->messages[$i]);
            unset($this->messages[$i]);
            $i++;
        }
    }

    private function sendMessage($message){

        $headers = array("Content-Type:" . "application/json", "Authorization:" . "key=".$this->api_key);

        $ch = curl_init();

        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_URL, $this->gcm_url);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($message));

        $response = curl_exec($ch);
        curl_close($ch);

        return $response;
    }

}`

`       $apiKey = '';
        $token = '';
 
        $message_data = array(
            'message' => 'Message',
            'tickerText' => 'Ticker text',
            'contentTitle' => 'contentTitle',
            'contentText' => 'contentText',
            'sound' => '',
            'vibrate' => true
        );
        
        $data = array(
            'collapse_key' => 'test',
            'data' => $message_data,
            'registration_ids' => [$token]
        );
        
        echo '<pre>';
        print_r($data);
        
        $push = new Push($apiKey);
        $push->add($data);
        $push->send();
        
        
        die;`

**Comment by ddobby94** [comment]
Sukisuki

**Comment by ddobby94** [comment]
@timhonders Nope it did not work, I'm already using the proper gcm implementation method in the back-end.

**Comment by timhonders** [comment]
@ddobby94 dit u try running adb logcat on a command line

that's the way is noticed my problem

**Comment by npomfret** [comment]
My app receives GCM push notifications when it is in the background, tested on Android 4.1 and 5.1.

It doesn't receive push notifications when its not running though.  Although, I'm not sure that feature is supported yet.

**Comment by Luzgan** [comment]
I thought that this is initial notification for - first notification from which you opened your app. Anyway it doesn't work for me as well this is what I dig up from logcat

_Unable to start service Intent { act=com.google.firebase.MESSAGING_EVENT pkg=com.* (has extras) } U=0: not found_

So now the questions is - was it never supported or google change couple things with recent move gcm to firebase?

**Comment by oddball** [comment]
Neither I get notifications when the app is closed. I get them when the app is in the foreground or in the background, but not when it is closed.

When the app is closed, adb logcat spits out:

11-02 20:05:10.578 11769 11769 W GCM-DMM : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.CENSORED (has extras) }

**Comment by cinder92** [comment]
+1

**Comment by allvintage** [comment]
> Neither I get notifications when the app is closed. I get them when the app is in the foreground or in the background, but not when it is closed.
> 
> When the app is closed, adb logcat spits out:
> 
> 11-02 20:05:10.578 11769 11769 W GCM-DMM : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.CENSORED (has extras) }

Same for me. Obviously Android receives the broadcast, even when app process is completely killed, but when React Native is killed, this module can't create a local notification. Anybody know a way how to start the app again, when a broadcast is received upon a completely closed app?

**Comment by npomfret** [comment]
This is supported now - but you have to structure your app in a certain way.  There's a little about it in the trouble shooting guide.  But basically you need to make sure that your push notification code gets run on startup as a direct side-effect of importing the root _index.android.js_ file.  

For reasons I don't understand, your app will get started when a remote push notification arrives, but non of the react-native life cycle stuff will run. So you need to be able to process your push notification without a ui, without any react-native stuff.

**Comment by oddball** [comment]
Hi npomfret! I do import a file similar to https://gist.github.com/npomfret/2566cc84ada1a807d201b8146e1fa25e
in my index.android.js, so that is not the problem in my case.

**Comment by allvintage** [comment]
Hi @npomfret thanks for this info! I tried to implement it, but I can't see how the app is being started at all. I put some console.logs all over my index.android.js file, then swiped the app away through task manager and then send myself a push. But in adb logcat I can't see any of these custom log messages being called.

**Comment by npomfret** [comment]
That sounds like a problem with your manifest.  I'm not quite sure what the magic line is that enables this feature, but I'm pretty sure I just followed the instructions

**Comment by allvintage** [comment]
Sorry, obviously I was running an old version of this module. Updated all my stuff and now the console.logs show up. Thank you! Got some work to do now ;)

**Comment by allvintage** [comment]
Done! Push Notifications are showing up, even when app is completely closed. Just had to update to the current version of this module, react and react-native and then import and place PushNotification.configure directly inside the index.android.js (even before the component class), similar to the link @oddball posted.

**Comment by sloanwolf** [comment]
Are there any complete examples of how to put `PushNotification.configure` in index file outside of RN component `class Index extends Component`?

I have tested configuring PushNotification outside of RN index component and can register and receive remote notification when app is killed but how do I now interact with my RN component code? Mainly navigate somewhere when banner notification is tapped.

I think this is a pretty standard use-case and should have a clear example somewhere. Thanks.

**Comment by Ryanthegiantlion** [comment]
I am assuming that this is being caused by a notification event firing before an onNotification handler has been configured?

Would it be worth adding a simple queue so that the push configure can be deferred until needed by the app?

**Comment by joaovpmamede** [comment]
I can see the notification when the app is closed but as soon as I click on it and open the app the `onNotification` doesn't fire again.
I have everything set like the instructions.

@npomfret do you got it working?

**Comment by rohan-sethi** [comment]
@joaovpmamede Hi mate, so did you got it working? Which approach are you following ? Any clean ?

**Comment by joaovpmamede** [comment]
@rohan-sethi nop, still fighting with it.

**Comment by sloanwolf** [comment]
@rohan-sethi @joaovpmamede not sure how you guys have your app setup but for me I have an Index and Main (navigator) component. Index is logged out, Main is when logged in.

Index:
```
let _pushNotificationToken = null;

PushNotification.configure({
  onRegister(token) {
    _pushNotificationToken = token;
  },

  senderID: "__ID__",
  popInitialNotification: false,
  requestPermissions: true,
});

class Index extends Component {
render() {
    return (
      <Navigator
        sceneStyle={styles.scene}
        ref={(navigator) => { this.navigator = navigator; }}
        renderScene={this.renderScene.bind(this)}
        initialRoute={{
          title: 'Title',
          component: Main,
          passProps: {
            _pushNotificationToken: _pushNotificationToken,
          }
        }} />
    );
  }
}
```

Then in Main component:

```
class Main extends Component {
componentWillMount(){
    PushNotification.configure({
      // (optional) Called when Token is generated (iOS and Android)
      onRegister: this._onRegister,

      // (required) Called when a remote or local notification is opened or received
      onNotification: this._onNotification, // <-- Your regular onNotification function

      // ANDROID ONLY: GCM Sender ID (optional - not required for local notifications, but is need to receive remote push notifications) 
      senderID: "__ID__",

      // Should the initial notification be popped automatically
      popInitialNotification: true,
      //requestPermissions: true,
    });
  }

_onRegister(data){
    console.log('[GCM][_onRegister]', this.props._pushNotificationToken);
    
    API.request('user', 'put', {
  		user: {
  		  device_token: this.props._pushNotificationToken.token,
        device_token_type: 'android',
  		}
  	}, (response) => {
      // Do nothing
  	});
  }
}
```

For my purposes I was able to set it up this way to get notification when app is killed, background or foreground and get the onNotification in my main component for routing purposes. The main thing was using @allvintage's advice for `PushNotification.configure` OUTSIDE the Index component class. I then track the token and use actually register inside my other component, but you should be able to use it inside Index if you need to as well.

**Comment by joaovpmamede** [comment]
@sloanwolf I have everything working and I do receive the initial notification when the app is killed, but what happens when you click on the notification? Do you get a "second" notification object on your `onNotification` handler?

**Comment by sloanwolf** [comment]
@joaovpmamede yes `onNotification` gets run twice when app is in background (while debugging in Chrome). Second notification `userInteraction:true` is set in the payload.

When app is killed the payload has `userInteraction:true` set, because it was tapped.

Watching `adb logcat` when app is killed I see the following:

Initial GCM notification received:

```
03-21 18:29:49.640 15503 15557 V RNPushNotification: onMessageReceived: Bundle[{google.sent_time=1490146194589, thread_id=1234, category=NEW_MESSAGE, title=android, google.message_id=0:1234, message=asdsad}]
03-21 18:29:50.311 15503 15503 V RNPushNotification: sendNotification: Bundle[{google.sent_time=1490146194589, thread_id=1234, userInteraction=false, id=-1234, category=NEW_MESSAGE, title=android, google.message_id=0:1234, message=asdsad, foreground=false}]
```

Then when I tap it I get the same payload but with `userInteraction:true` in JS.

**Comment by joaovpmamede** [comment]
@sloanwolf I get two different behaviours when the app is killed.
If I don't click immediately on the notification I don't get the second `onNotification` with `userInteraction: true` but if do everything works accordingly.
It's as if the notification is lost after some seconds.

**Comment by rohan-sethi** [comment]
Does it matter if I'm using local notification?

**Comment by Oize** [comment]
I'm reading this topic for a few days already and completely stuck.
Can someone please explain me, where should i place `PushNotification.configure` to get onNotification called when app is closed or in a background?
Here is my index.android.js:
```
import {AppRegistry} from 'react-native'
import App from './build/index'

AppRegistry.registerComponent('MyApp', () => App)
```

If i place it here, then how can i access `onRegister`'s result?
Or i should add it into my index.tsx (i'm using TypeScript btw), which looks like:
```
import * as React from 'react'
import {Provider} from 'react-redux'

import App from './components/App'
import createStore from './store/Store'

export default class Wrapper extends React.Component<{}, {}> {
  private store = createStore()

  render() {
    return (
      <Provider store={this.store}>
        <App />
      </Provider>
    )
  }
}
```
I'm currently trying to implement something like @sloanwolf's example but without any effect.

**Comment by BobiKing** [comment]
This turned out to be very simple.  PushNotification.configure goes into componentDidMount inside your index.js. 
This will generate a unique device token that you can copy from the console log and use in the server code to send notification to this specific device. 

The trick is to add PushNotification.localNotification() inside onNotification, so that once a remote notif is received, it is converted into local one. Unfortunately, the documentation doesn't make this part clear but a remote notif won't go into the device notifs centre unless it's converted to local. 

```
componentDidMount(){
PushNotification.configure({
      // (optional) Called when Token is generated (iOS and Android)
      onRegister: function(token) {
         // alert('TOKEN:' + JSON.stringify(token) );
          console.log(token);
      },
      onNotification: function(notification) {
          console.log( 'NOTIFICATION:', notification );
          //alert(JSON.stringify(notification));

        PushNotification.localNotification({
          title: notification['gcm.notification.title'],
          message: notification['gcm.notification.body'], // (required)
          subText: notification['gcm.notification.subText'],
          tag: notification['gcm.notification.tag'],
          group: notification['gcm.notification.group'],
        });
      },
      senderID: "your_fcm_senderID",
      popInitialNotification: true,
      requestPermissions: true,
    });
    
  }
```

**Comment by ComicScrip** [comment]
Finally solved the sh*t out of this ! 
I know it's probalbly very hacky but it works. Modify the content of node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java as follow : 

```java
package com.dieam.reactnativepushnotification.modules;

import android.app.Activity;
import android.app.Application;
import android.app.NotificationManager;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.Bundle;

import com.dieam.reactnativepushnotification.helpers.ApplicationBadgeHelper;
import com.facebook.react.bridge.ActivityEventListener;
import com.facebook.react.bridge.Arguments;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.bridge.WritableMap;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;

public class RNPushNotification extends ReactContextBaseJavaModule implements ActivityEventListener {
    public static final String LOG_TAG = "RNPushNotification";// all logging should use this tag

    private RNPushNotificationHelper mRNPushNotificationHelper;
    private final Random mRandomNumberGenerator = new Random(System.currentTimeMillis());
    private RNPushNotificationJsDelivery mJsDelivery;

    private Bundle savedBundle = null;

    public RNPushNotification(ReactApplicationContext reactContext) {
        super(reactContext);

        reactContext.addActivityEventListener(this);

        Application applicationContext = (Application) reactContext.getApplicationContext();
        // The @ReactNative methods use this
        mRNPushNotificationHelper = new RNPushNotificationHelper(applicationContext);
        // This is used to delivery callbacks to JS
        mJsDelivery = new RNPushNotificationJsDelivery(reactContext);

        registerNotificationsRegistration();
    }

    @Override
    public String getName() {
        return "RNPushNotification";
    }

    @Override
    public Map<String, Object> getConstants() {
        final Map<String, Object> constants = new HashMap<>();

        return constants;
    }

    public void onNewIntent(Intent intent) {
        if(intent.hasExtra("google.message_id")){
            Bundle bundle = intent.getExtras();
            bundle.putBoolean("foreground", false);
            intent.putExtra("notification", bundle);
            this.savedBundle =  bundle;
            mJsDelivery.notifyNotification(bundle);
        }

        if (intent.hasExtra("notification")) {
            Bundle bundle = intent.getBundleExtra("notification");
            bundle.putBoolean("foreground", false);
            intent.putExtra("notification", bundle);
            mJsDelivery.notifyNotification(bundle);
        }
    }

    private void registerNotificationsRegistration() {
        IntentFilter intentFilter = new IntentFilter(getReactApplicationContext().getPackageName() + ".RNPushNotificationRegisteredToken");

        getReactApplicationContext().registerReceiver(new BroadcastReceiver() {
            @Override
            public void onReceive(Context context, Intent intent) {
                String token = intent.getStringExtra("token");
                WritableMap params = Arguments.createMap();
                params.putString("deviceToken", token);

                mJsDelivery.sendEvent("remoteNotificationsRegistered", params);
            }
        }, intentFilter);
    }

    private void registerNotificationsReceiveNotificationActions(ReadableArray actions) {
        IntentFilter intentFilter = new IntentFilter();
        // Add filter for each actions.
        for (int i = 0; i < actions.size(); i++) {
            String action = actions.getString(i);
            intentFilter.addAction(getReactApplicationContext().getPackageName() + "." + action);
        }
        getReactApplicationContext().registerReceiver(new BroadcastReceiver() {
            @Override
            public void onReceive(Context context, Intent intent) {
                Bundle bundle = intent.getBundleExtra("notification");

                // Notify the action.
                mJsDelivery.notifyNotificationAction(bundle);

                // Dismiss the notification popup.
                NotificationManager manager = (NotificationManager) context.getSystemService(context.NOTIFICATION_SERVICE);
                int notificationID = Integer.parseInt(bundle.getString("id"));
                manager.cancel(notificationID);
            }
        }, intentFilter);
    }

    @ReactMethod
    public void requestPermissions(String senderID) {
        ReactContext reactContext = getReactApplicationContext();

        Intent GCMService = new Intent(reactContext, RNPushNotificationRegistrationService.class);

        GCMService.putExtra("senderID", senderID);
        reactContext.startService(GCMService);
    }

    @ReactMethod
    public void presentLocalNotification(ReadableMap details) {
        Bundle bundle = Arguments.toBundle(details);
        // If notification ID is not provided by the user, generate one at random
        if (bundle.getString("id") == null) {
            bundle.putString("id", String.valueOf(mRandomNumberGenerator.nextInt()));
        }
        mRNPushNotificationHelper.sendToNotificationCentre(bundle);
    }

    @ReactMethod
    public void scheduleLocalNotification(ReadableMap details) {
        Bundle bundle = Arguments.toBundle(details);
        // If notification ID is not provided by the user, generate one at random
        if (bundle.getString("id") == null) {
            bundle.putString("id", String.valueOf(mRandomNumberGenerator.nextInt()));
        }
        mRNPushNotificationHelper.sendNotificationScheduled(bundle);
    }

    @ReactMethod
    public void getInitialNotification(Promise promise) {
        WritableMap params = Arguments.createMap();
        Activity activity = getCurrentActivity();
        if (activity != null) {
            Intent intent = activity.getIntent();
            Bundle bundle = null;

            if (intent.hasExtra("notification")) {
                bundle = intent.getBundleExtra("notification");
            } else if (intent.hasExtra("google.message_id")) {
                bundle = intent.getExtras();
            }

            if (this.savedBundle != null){
                bundle = savedBundle;
                this.savedBundle = null;
            }

            if (bundle != null) {
                bundle.putBoolean("foreground", false);
                String bundleString = mJsDelivery.convertJSON(bundle);
                params.putString("dataJSON", bundleString);
            }
        }
        promise.resolve(params);
    }

    @ReactMethod
    public void setApplicationIconBadgeNumber(int number) {
        ApplicationBadgeHelper.INSTANCE.setApplicationIconBadgeNumber(getReactApplicationContext(), number);
    }

    // removed @Override temporarily just to get it working on different versions of RN
    public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
        onActivityResult(requestCode, resultCode, data);
    }

    // removed @Override temporarily just to get it working on different versions of RN
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        // Ignored, required to implement ActivityEventListener for RN 0.33
    }

    @ReactMethod
    /**
     * Cancels all scheduled local notifications, and removes all entries from the notification
     * centre.
     *
     * We're attempting to keep feature parity with the RN iOS implementation in
     * <a href="https://github.com/facebook/react-native/blob/master/Libraries/PushNotificationIOS/RCTPushNotificationManager.m#L289">RCTPushNotificationManager</a>.
     *
     * @see <a href="https://facebook.github.io/react-native/docs/pushnotificationios.html">RN docs</a>
     */
    public void cancelAllLocalNotifications() {
        mRNPushNotificationHelper.cancelAllScheduledNotifications();
        mRNPushNotificationHelper.clearNotifications();
    }

    @ReactMethod
    /**
     * Cancel scheduled notifications, and removes notifications from the notification centre.
     *
     * Note - as we are trying to achieve feature parity with iOS, this method cannot be used
     * to remove specific alerts from the notification centre.
     *
     * @see <a href="https://facebook.github.io/react-native/docs/pushnotificationios.html">RN docs</a>
     */
    public void cancelLocalNotifications(ReadableMap userInfo) {
        mRNPushNotificationHelper.cancelScheduledNotification(userInfo);
    }

    @ReactMethod
    public void registerNotificationActions(ReadableArray actions) {
        registerNotificationsReceiveNotificationActions(actions);
    }
}


```

Maybe I'll do a proper PR when I have time.

**Comment by eplua** [comment]
@ComicScrip Thank you very much. It finally works!!

**Comment by ahmad2smile** [comment]
I had the same problem when I was testing PN. Logcat error:

`Cannot send to notification centre because there is no 'message' field in: Bundle`

Just added `message` field and it worked.

**Comment by dandre-hound** [comment]
We just added a little snippet in `RNReceivedMessageHandler.java` and applied it on every install using patch-package:
```
...
bundle.putParcelable("data", dataBundle);

if (!bundle.containsKey("title") && dataBundle.containsKey("title")) {
    bundle.putString("title", dataBundle.getString("title"));
}
if (!bundle.containsKey("message") && dataBundle.containsKey("message")) {
    bundle.putString("message", dataBundle.getString("message"));
}
```

**Comment by Inovotice-Technology** [comment]
@ComicScrip @joaovpmamede @ahmad2smile I can see the notification when the app is closed, I used react-native-push-notification. when i closed app the functions that make the notification call didn't work.
are there solutions ?.
