### ISSUE TITLE
PushNotification.invokeApp(notification) doesn't work with foreground notification

### ISSUE THREAD

**Issue by waryiar** [zo0r/react-native-push-notification#2190]
# Bug

`PushNotification.invokeApp(notification)` doesn't work when trying to open application with notification received in foreground.

## Environment

react-native : 0.66.0
react-native-push-notification : 8.1.1

## Steps to reproduce

1. Send local notification with `invokeApp: false` and make sure that it is received in app's foreground.
   My example notification:

```
{
  "actions": ["Example action"],
  "channelId": "default_channel",
  "id": "378637047",
  "invokeApp": false,
  "message": "Example message",
  "title": "Example title",
  "userInfo": {
    "type": "EXAMPLE_EVENT",
    ...
  },
  "vibrate": true,
  "vibration": 1000
}
```

2. Close (kill) application.
3. Tap on "Example action" in received notification.

**Actual result:** onAction method is called, notification disappears from notification drawer, app is not invoked.
**Expected result:** app is invoked.

When I open the app myself after that, I see in my logs that onAction was called and then onNotification with the same notification was called as well, which to me means that everything works except app invocation. It works if notification is opened in the same app state as it was received.

**Comment by quantiantechnologies** [comment]
+1
