### ISSUE TITLE
Working fine in background but for foreground the onNotification is triggered but the notification is not received

### ISSUE THREAD

**Issue by UmerQur3shi** [zo0r/react-native-push-notification#2191]
Hello,
It's working fine when the app is minimized (in background) but in foreground I'm not getting the notifications, only the onNotification event is triggered and I'm getting this result in console...
NOTIFICATION: {"channelId": "fcm_default_channel", "color": null, "data": {}, "finish": [Function finish], "foreground": true, "id": "-173549014", "message": "asasasasas", "priority": "high", "smallIcon": "ic_notification", "sound": null, "tag": "campaign_collapse_key_4089739413130270292", "title": "sas", "userInteraction": false, "visibility": "private"}

Here is my AndroidManifest.xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.pushnotificationtest">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>

      
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="true"/>
        
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@color/white"/> 

        <meta-data  android:name="com.google.firebase.messaging.default_notification_channel_id"
                    android:value="@string/default_notification_channel_id" />

        <meta-data  android:name="com.dieam.reactnativepushnotification.default_notification_channel_id"
                    android:value="@string/default_notification_channel_id" />

        
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

    </application>
</manifest>

**Comment by TayyabaAslam3317** [comment]
@UmerQur3shi how did you fix the issue?

**Comment by UmerQur3shi** [comment]
> @UmerQur3shi how did you fix the issue?

@TayyabaAslam3317 by sending a local notification in onNotification event if the app is in foreground. I would suggest you to use notifee instead as this library is not being maintained anymore so there are other issues as well. If you still have any queries/issues, feel free to ping me.

**Comment by Jamal-ReachFirst** [comment]
@TayyabaAslam3317, how you handle background notification using notifee + fcm, it generates two notifications, and if i remove the notifee.display() form background handler then I can't handle the notification in background
