### ISSUE TITLE
How to use repeat notification for specific Week days in Local Notification ?

### ISSUE THREAD

**Issue by ApWin** [zo0r/react-native-push-notification#2192]
# Question

First of all , Thank you for Authors, Contributors of this package ) You are saving my time ))

Now in the documentation if We set repeatType as a "Week" and repeatTime as 7. 
Notification repeated on every day. But I want repeat my local notification on the specific day. 
How can i resolve that  ?

ex:  Monday, Tuesday, Friday or Only Saturday and Sunday

**Comment by AndersonVanzo** [comment]
@ApWin hey, did you find any solution to this?

**Comment by ritshpatidar** [comment]
@ApWin , @AndersonVanzo Hi Guys, I have an idea, not implemented yet, but it should work. Here it is:

Create multiple schedule notifications, for each day(eg. Sunday, Tuesday etc), having these parameters -

For Sunday:
date: "date of next sunday"
repeatType: 'day'
repeatTime: 7

For Tuesday:
date: "date of next tuesday"
repeatType: 'day'
repeatTime: 7

Edit:
Or you can create multiple notifications with repeatType = week.

I hope I was able to explain.
