### ISSUE TITLE
Update notification title or body of a remote notification from the client-side

### ISSUE THREAD

**Issue by tahins** [zo0r/react-native-push-notification#2197]
I have a scenario where I get a remote push notification via Firebase but I don't want to show the title or the message that the remote notification contains. I want to change them based on the custom data which came with the notification payload and then show the notification to the users. 

Is there any way to achieve that reliably in both Android and iOS?

**Comment by rossicler-hostalky** [comment]
Did you find a solution for this?

**Comment by svaishnani** [comment]
@tahins @rossicler-hostalky 

Have you found any solution?

I have same issue i want to modified push notification body before display so for that i used nsnotification service extension but it's not working using this library.

so you have any solution then help us.

Thank you.
