### ISSUE TITLE
Notification permissions

### ISSUE THREAD

**Issue by Brentlok** [zo0r/react-native-push-notification#2200]
# Question

Can someone answer me how to enable app permission for floating windows, and sound notifications?
![IMG_20211119_163857.jpg](https://user-images.githubusercontent.com/48803618/142649705-bf491ad4-3767-42b2-9e7d-c4d911b372f2.jpg)![Screenshot_2021-11-19-16-39-04-216_com.android.settings.jpg](https://user-images.githubusercontent.com/48803618/142649726-181dad55-a84b-4dc0-8a0f-b3c6fb5aa08b.jpg)

**Comment by levepic** [comment]
Why did you close this? Found the solution? Having the same problem

**Comment by Brentlok** [comment]
I switched to [notifee](https://notifee.app/)
