### ISSUE TITLE
Error The registration token is not a valid FCM registration token IOS

### ISSUE THREAD

**Issue by luigbren** [zo0r/react-native-push-notification#2201]
Good morning, I am having problems when sending a push notification in IOS (Iphone 13 pro max) both from my app and also from the console.firebase.google, when running my app I get the token but apparently it is an invalid token, any solution?

```
App 3689 output:    { code: 'messaging/invalid-argument',
App 3689 output:      message:
App 3689 output:       'The registration token is not a valid FCM registration token' },
```

**Comment by Dallas62** [comment]
Please take time to search in issue history.
Regards
