### ISSUE TITLE
Galaxy Flip / Galaxy Folder onNotification not responding Issue

### ISSUE THREAD

**Issue by chowh** [zo0r/react-native-push-notification#2203]
Hi.

First of all, this library really helped me to finish my project. Thank you for developers.

We have strange issue with push notification.

[Situation]
"onNotification" is not working on "Samsung Galaxy Flip or Folder".

[App Behavior] 
(1) Normal (Not foldable phones) **WORKS**
- App is on background.
- Receive push notification.
- Click notification.
- App starts.
- "onNotification" behavior works.

(2) Foldable phones (Samsung Galaxy Flip / Folder) **WORKS**
- App is once launched and phone is not folded. (Remaining un-folded, App is on background or terminated)
- Receive push notification.
- Click notification.
- App starts / resumes.
- "onNotification" behavior works.

(3) Foldable phones (Samsung Galaxy Flip / Folder) **NOT WORKING**
- No matter app is once launched or not, Phone has been folded.
- Receive push notification.
- Click notification.
- App starts / resumes.
- "onNotification" not responding.

[Guess]
- Action "Folding the phone" only disables onNotification so i believe this issue is related on "Folding".

[Code example]
- This is my App.js file.

....
`
var PushNotification = require('react-native-push-notification');
....
PushNotification.configure({
    // (required) Called when a remote is received or opened, or local notification is opened
    onNotification: async function (notification) {
    setTimeout(async () => {
      if (notification.data.type === 'CHAT') {
        let session = await AsyncStorage.getItem('session');
        if (session) {
          
          // chatCheckAlert(session, notification.data.roomId);
            console.log("CHAT NOTI :: " + notification.data.roomId);
            const createResult = await chattingRoomApi.getChattingRoom(notification.data.roomId);
            console.log("RSLT :: ", createResult);
            navigationRef.navigate('TabNavigator',{ screen : 'Chat', params:{ }})
            navigationRef.navigate('TabNavigator', {
              screen: 'Chat',
              params: {
                screen: 'MessagePannelScreen',
                params: {
                  chattingRoom: createResult.data,
                  create: 'N'
                },
              },
            });
        } else {
          CustomAlert('로그인 후 재시도해주세요');
          return;
        }
      }else if (notification.data.type === 'CM') {
        let session = await AsyncStorage.getItem('session');
        if (session) {
            commentAlert({title: '새로운 알림'}, session, parseInt(notification.data.boardId));
        } else {
          CustomAlert('로그인 후 재시도해주세요');
        }
      } 
      else if (notification.data.type === 'PL') {
        console.log("PL 1", Platform.OS);
        let session = await AsyncStorage.getItem('session');
        if (session) {
            plLoginAlert({title: 'Password Less 로그인 시도?', body: `${notification.data.awsPublicIP} 에서 Password Less 로그인이 시도되었습니다.`}, session, notification.data.qrcode, notification.data.awsPublicIP);
        } else {
          CustomAlert('로그인 후 재시도해주세요');
          return;
        }
      }
      notification.finish(PushNotification.FetchResult.NoData);
    }, 1500)
    },
    
    // // (optional) Called when Registered Action is pressed and invokeApp is false, if true onNotification will be called (Android)
    onAction: function (notification) {
      setTimeout(async () => {
        if (notification.data.type === 'CHAT') {
          let session = await AsyncStorage.getItem('session');
          if (session) {
            
            // chatCheckAlert(session, notification.data.roomId);
              console.log("CHAT NOTI :: " + notification.data.roomId);
              const createResult = await chattingRoomApi.getChattingRoom(notification.data.roomId);
              console.log("RSLT :: ", createResult);
              navigationRef.navigate('TabNavigator',{ screen : 'Chat', params:{ }})
              navigationRef.navigate('TabNavigator', {
                screen: 'Chat',
                params: {
                  screen: 'MessagePannelScreen',
                  params: {
                    chattingRoom: createResult.data,
                    create: 'N'
                  },
                },
              });
          } else {
            CustomAlert('로그인 후 재시도해주세요');
            return;
          }
        }else if (notification.data.type === 'CM') {
          let session = await AsyncStorage.getItem('session');
          if (session) {
              commentAlert({title: '새로운 알림'}, session, parseInt(notification.data.boardId));
          } else {
            CustomAlert('로그인 후 재시도해주세요');
          }
        } 
        else if (notification.data.type === 'PL') {
          console.log("PL 1", Platform.OS);
          let session = await AsyncStorage.getItem('session');
          if (session) {
              plLoginAlert({title: 'Password Less 로그인 시도?', body: `${notification.data.awsPublicIP} 에서 Password Less 로그인이 시도되었습니다.`}, session, notification.data.qrcode, notification.data.awsPublicIP);
          } else {
            CustomAlert('로그인 후 재시도해주세요');
            return;
          }
        }
        notification.finish(PushNotification.FetchResult.NoData);
      }, 1500)
    },

    // (optional) Called when the user fails to register for remote notifications. Typically occurs when APNS is having issues, or the device is a simulator. (iOS)
    onRegistrationError: function (err) {
      console.error(err.message, err);
    },

    // IOS ONLY (optional): default: all - Permissions to register.
    permissions: {
      alert: true,
      badge: true,
      sound: true,
    },

    // Should the initial notification be popped automatically
    // default: true
    popInitialNotification: true,

    /**
     * (optional) default: true
     * - Specified if permissions (ios) and token (android and ios) will requested or not,
     * - if not, you must call PushNotificationsHandler.requestPermissions() later
     * - if you are not using remote notification or do not have Firebase installed, use this:
     *     requestPermissions: Platform.OS === 'ios'
     */
    requestPermissions: true,
  });
....
`

**Comment by kushalshah-invx** [comment]
Hey @chowh ,
Did you find any solution? I am facing the same issue.
