### ISSUE TITLE
Strange behaviour on android and IOS in onNotification

### ISSUE THREAD

**Issue by YulianLozynskyi** [zo0r/react-native-push-notification#2206]
Hi, thanks for your work. I have a question regarding remote push messages. So basically I've added configure() into the index.js and some strange behavior I see in remote notifications. 
I leave onNotification as it is, without any changes and handling of notifications and i still somehow get silent remote notifications but i don't see them in console (IOS), but i see them (in console) when i open them. On android on contrary, i see notification right away in console but not visually and nothing happens (in console) when i click on it. What can cause such strange behaviour? I've done everything step by step as you write in a readme.
And another question: in onNotification method there is a comment "process notification", what is should mean basically? i should trigger local notification there or what? Thanks in advance

**Comment by YulianLozynskyi** [comment]
Soooo, for the future smart asses like me, firstly you should dive into bright world of how push notifications work and everything will work (I mean silent, noisy and local push notifications). I've configured my backend accordingly and now I get proper noisy notifications after device was registered. But i have another issue, maybe it's platform specific but: when i get remote noisy notification on IOS i don't see it console, only when i opened it and on ANDROID i see notification when it arrives but nothing happens when i open it?

**Comment by ghost** [comment]
anyone have the answer?

**Comment by vishalc-jft** [comment]
Hi, even i have a similar issue. Whenever I push notifications from my backend for android I sometimes get 2 notifications, one is silent and the other one as alerting. But sometimes it goes back to normal behaviour. I have observed quite a few trends. Below are the listed scenarios.

- Whenever the app is in foreground, it is behaving normally.
- Whenever the app is in background, i get 2 notifications and this scenario turns out to be working sometimes.

Anybody has any leads for this?

**Comment by akshayhalasangiremitbee** [comment]
> Hi, even i have a similar issue. Whenever I push notifications from my backend for android I sometimes get 2 notifications, one is silent and the other one as alerting. But sometimes it goes back to normal behaviour. I have observed quite a few trends. Below are the listed scenarios.
> 
> * Whenever the app is in foreground, it is behaving normally.
> * Whenever the app is in background, i get 2 notifications and this scenario turns out to be working sometimes.
> 
> Anybody has any leads for this?

Hey Please check if you're creating a local push notification. I had the same issue and I was able to fix it by removing the local push notification
