### ISSUE TITLE
Question: What is the suggested way to navigate your app to the right view when using onNotification?

### ISSUE THREAD

**Issue by logileifs** [zo0r/react-native-push-notification#221]
I tried calling `navigator.push({route})` inside the onNotification event but I had no access to the navigator from there. Has someone figured out a simple way to overcome this ?

**Comment by logileifs** [comment]
Never mind, I figured this one out myself

**Comment by habibridho** [comment]
@logileifs Hi, could you share how you do that?

**Comment by logileifs** [comment]
@habibridho sure. What worked for me is to call `PushNotification.configure` on `componentDidMount` in my main component (where all the routing is done). I created a [gist](https://gist.github.com/logileifs/5d7698a2e9d5c9a5f9f76d4721e2aa77) which you can use as a base. It works both on android and ios. If you are having any problems with this, just let me know.
