### ISSUE TITLE
Can I get a token except from the onRegister call ?

### ISSUE THREAD

**Issue by ksetrin** [zo0r/react-native-push-notification#2210]
# Question

I want to get token later in the code.
So I have different ways
1. Save token to AsyncStorage and get in ant place
2. Wrap `PushNotification.configure` in a service or store or something else and keep token as property

But it would be most convenient to get it anywhere simply by calling the method like `PushNotification.getToken()`
May be I missed something and the method existed?

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification#state-of-the-repository

**Comment by levepic** [comment]
See https://github.com/zo0r/react-native-push-notification/issues/2215 for solution
