### ISSUE TITLE
remote for ios not working 

### ISSUE THREAD

**Issue by sunset1234321** [zo0r/react-native-push-notification#2211]
android receive remote push perfectly,

however for ios

- I have add the APN keys to firebase
- and then i get the token from 
```
PushNotification.configure({
  // (optional) Called when Token is generated (iOS and Android)
  onRegister: function (token) {
  (THIS TOKEN!!!!!)  console.log("TOKEN:", token);
  },
```
- but seems my ios still doesn't receive the remote push

**Comment by GoldMyr1994** [comment]
I had the same problem. Digging in the iussue i realized that the token given by this library cannot be used to notify ios.
I had to install @react-native-firebase/messaging that has a method getToken that returns a token for ios.

`import messaging from '@react-native-firebase/messaging';`
`messaging().getToken().then(token => ....);`


This is the issue that i found https://github.com/zo0r/react-native-push-notification/issues/2185#issuecomment-962940018

**Comment by Dallas62** [comment]
Thanks @GoldMyr1994
