### ISSUE TITLE
index.d.ts/Class-PushnotificationObject/repeatType 

### ISSUE THREAD

**Issue by EyesMice** [zo0r/react-native-push-notification#2213]
I am currently working on an application that requires cheduled pushnotifications.
One of those push notifications need to repeat every month.
According to the documentation, this should easily be doable using a {repeatType: 'month'}.

When I try to do this however, the only repeatType:  optiosn that are available are: week, day, hour and time.

Looking at the index.d.ts file I find that the repeatType property in the Push notificationObject class is written in the following way:
  **repeatType?: 'week' | 'day' | 'hour' | 'minute' | 'time' | undefined;**

As you can see 'month' is not present as a option.
Changing the property in the following way fixes the problem:
  **repeatType?: 'week' | 'day' | 'hour' | 'minute' | 'time' | 'month' | undefined;**

I hope that you will be able to fix this bug in the near future.

Many greetings,
EyesMice

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification/issues/1593#issuecomment-672791633
