### ISSUE TITLE
Detected multiple Kitlin Daemon

### ISSUE THREAD

**Issue by trickyc0d3r** [zo0r/react-native-push-notification#2218]
Task :react-native-push-notifications:verifyReleaseResources FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-push-notifications:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/399bf21213f2a312ba3613f0500e9447/transformed/appcompat-1.0.2/res/values-v26/values-v26.xml:5:5-8:13: AAPT: error: resource android:attr/colorError not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/399bf21213f2a312ba3613f0500e9447/transformed/appcompat-1.0.2/res/values-v26/values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/399bf21213f2a312ba3613f0500e9447/transformed/appcompat-1.0.2/res/values-v26/values-v26.xml:13:5-16:13: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/399bf21213f2a312ba3613f0500e9447/transformed/appcompat-1.0.2/res/values-v28/values-v28.xml:5:5-8:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/399bf21213f2a312ba3613f0500e9447/transformed/appcompat-1.0.2/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/7cea517640aaefbc2344a1862ae1f1e9/transformed/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontStyle not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/7cea517640aaefbc2344a1862ae1f1e9/transformed/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/font not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/7cea517640aaefbc2344a1862ae1f1e9/transformed/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontWeight not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/7cea517640aaefbc2344a1862ae1f1e9/transformed/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/fontVariationSettings not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/7cea517640aaefbc2344a1862ae1f1e9/transformed/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/7cea517640aaefbc2344a1862ae1f1e9/transformed/core-1.1.0/res/values/values.xml:174:5-210:25: AAPT: error: resource android:attr/startX not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/7cea517640aaefbc2344a1862ae1f1e9/transformed/core-1.1.0/res/values/values.xml:174:5-210:25: AAPT: error: resource android:attr/startY not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/7cea517640aaefbc2344a1862ae1f1e9/transformed/core-1.1.0/res/values/values.xml:174:5-210:25: AAPT: error: resource android:attr/endX not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/7cea517640aaefbc2344a1862ae1f1e9/transformed/core-1.1.0/res/values/values.xml:174:5-210:25: AAPT: error: resource android:attr/endY not found.
         
     ERROR:/Users/trickyc0d3r/.gradle/caches/transforms-3/7cea517640aaefbc2344a1862ae1f1e9/transformed/core-1.1.0/res/values/values.xml:211:5-217:25: AAPT: error: resource android:attr/offset not found.
         
`What should I do, to avoid this error?`

**Comment by Dallas62** [comment]
Search on issues ?
https://github.com/zo0r/react-native-push-notification/issues?q=verifyReleaseResources
Regards
