### ISSUE TITLE
Notification does not show when app is closed

### ISSUE THREAD

**Issue by weihangChen** [zo0r/react-native-push-notification#2221]
Notification is working fine when the app is at foreground and background, but when it is turned off. It does not receive any notification. Tested on both android and iOS

**Comment by ayushmng** [comment]
Same here, have you solved this issue, @weihangChen ?

**Comment by weihangChen** [comment]
@ayushmng , use this lib instead, all aspects of notification are working for my app
https://github.com/wix/react-native-notifications

**Comment by Archimondee** [comment]
> @ayushmng , use this lib instead, all aspects of notification are working for my app https://github.com/wix/react-native-notifications

Sorry, is that lib receive notification when app is closed ?

**Comment by weihangChen** [comment]
yes, app receives notification when it is closed

**Comment by Archimondee** [comment]
> yes, app receives notification when it is closed

it look like scheduled notification not implemented in that library.

**Comment by Dallas62** [comment]
If there is no notification in background, consider re-read the documentation (README, TROUBLESHOOTING, ...) check the example project which work as expected (local, remote).
Also check this note: https://github.com/zo0r/react-native-push-notification#state-of-the-repository

**Comment by ragsav** [comment]
The example does not work as expected if gradle version is 7.0
