### ISSUE TITLE
IOS : Local notification not working when application is in background or inactivity

### ISSUE THREAD

**Issue by srithar21** [zo0r/react-native-push-notification#2222]
# Bug

Hi Team,

In iOS device, local notification was not triggering when application in background or inactivity state.

Can you please help me to set any code?

## Environment info

iOS 15.1.1 device - iPhone 12

Library version:     "react-native-push-notification": "^8.1.0"

## Steps To Reproduce
 
 PushNotification.localNotification({
      message: 'You’ve been signed out due to inactivity.',
      autoCancel: true,
    });

1.  Above notification will be trigger after 5 mins of inactivity.

Describe what you expected to happen:

1. Same Notification will be trigger only when application comes to the foreground.

## Reproducible sample code

 PushNotification.localNotification({
      message: 'You’ve been signed out due to inactivity.',
      autoCancel: true,
    });

**Comment by Dallas62** [comment]
Hi,
You should probably look if your inactivity code is running.
I'm 100% sure that the localNotification method is not called.
Regards

**Comment by MariusCatanoiu** [comment]
You need to use PushNotification.localNotificationSchedule
