### ISSUE TITLE
Not able to get notification on ANDROID of my React-native project below is my payload for notification.

### ISSUE THREAD

**Issue by kantipudikesava** [zo0r/react-native-push-notification#2223]
My Data payload :-
{
  sentTime: 1641573035787,
  data: {
    title: 'Android Test Push',
    sound: 'default',
    alert: 'Test Push Salesforce.',
    _sid: 'SFMC',
    _m: 'NTQ6MTE0OjA',
    _mt: '1',
    _r: '017ca96c-95dd-4b6f-8195-4480c0990ce6',
    _h: 'MWwjqR2+RH/Ri9kIPJ6L+gAAAAAA'
  },
  messageId: '0:1641573035810575%e3e00047f9fd7ecd',
  ttl: 2419200,
  from: '1002423925039'
}
1. I can able to see remote message log.
2. Push notification pop-up not coming in android.

Please help me with this how to get notification in ANDROID. Thank you.

**Comment by Dallas62** [comment]
Please take a look to TROUBLE SHOOTING file.
Regards
