### ISSUE TITLE
bypass DND mode for notifications

### ISSUE THREAD

**Issue by digitlninja** [zo0r/react-native-push-notification#2226]
Hey, I need a way to bypass DND mode for notifications. IOS has an API for this, but i can't seem to find a conclusive answer for android and react-native yet. due to the nature of our app (security), we need to be able to still send notifications that get received even if the device is set to do not disturb mode.

This is urgent! Thanks so much 🙏🏼

**Comment by Dallas62** [comment]
Hi,
Not possible with the library.
Regards
