### ISSUE TITLE
Android custom sound not working only default sound is coming.

### ISSUE THREAD

**Issue by GurjantSinghAffle** [zo0r/react-native-push-notification#2239]
# Bug

## Environment info

`react-native info` output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by GurjantSinghAffle** [comment]
"react-native-push-notification": "^7.3.1",
    "react": "17.0.2",
     "react-native": "0.63.2"
<img width="1238" alt="Screenshot 2022-02-28 at 4 28 16 PM" src="https://user-images.githubuserc
<img width="843" alt="Screenshot 2022-02-28 at 4 27 41 PM" src="https://user-images.githubusercontent.com/61281021/155971664-25029476-a5d6-418c-b98f-f1a70b5d13d5.png">
ontent.com/61281021/155971643-d798c0bb-c81c-4780-b85b-4c0e30fe254b.png">
,
<img width="1240" alt="Screenshot 2022-02-28 at 4 29 24 PM" src="https://user-images.githubusercontent.com/61281021/155971832-114f6bd8-1919-4421-9f09-e0627a255509.png">

**Comment by Dallas62** [comment]
Sounds are stick to channel on Android,
Regards

**Comment by GurjantSinghAffle** [comment]
<img width="1271" alt="Screenshot 2022-02-28 at 4 59 45 PM" src="https://user-images.githubusercontent.com/61281021/155976081-fddbe885-4cef-40d8-a14d-4081fa5fd97d.png">
I have followed the procedure given in the package. but its not working.

**Comment by GurjantSinghAffle** [comment]
also, use the file name in the string with extension type and without.but not working

**Comment by codoffer** [comment]
Please check your server payload. It should mention sound:"default" in the notification set.

**Comment by Balthazar33** [comment]
> also, use the file name in the string with extension type and without.but not working

@GurjantSinghAffle 
For local notifications (android), try
`soundName: android.resource://<your-package-name-in-manifest>/raw/<file-name-without-extension>`
Example:
`soundName: android.resource://com.myapp/raw/my_sound`
