### ISSUE TITLE
google.sent_time expected String but value was a java.lang.Long The default value <null> was returned

### ISSUE THREAD

**Issue by the-simian** [zo0r/react-native-push-notification#224]
```
10-07 00:58:27.587 13079-13157/com.appname W/Bundle: Key google.sent_time expected String but value was a java.lang.Long.  The default value <null> was returned.
10-07 00:58:27.587 13079-13157/com.appname W/Bundle: Attempt to cast generated internal exception:
   java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
      at android.os.BaseBundle.getString(BaseBundle.java:923)
      at com.google.android.gms.gcm.zza.zzad(Unknown Source)
      at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
      at com.google.android.gms.gcm.GcmListenerService.zzn(Unknown Source)
      at com.google.android.gms.gcm.GcmListenerService.zzm(Unknown Source)
      at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
      at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

I'm currently experiencing this error when sending a message from FCM, and using this module with the latest version of react-native `0.34.1` and this module at `2.1.1`

And in my build.gradle:

```
    compile project(':react-native-push-notification')
    compile ('com.google.android.gms:play-services-gcm:9.4.0') {
       force = true;
    }
    compile('com.google.firebase:firebase-core:9.4.0')
    compile('com.google.firebase:firebase-messaging:9.4.0')
```

I see this problem occurring as well  in other libs: https://github.com/rpush/rpush/issues/292 such as in rpush as of 2 days ago

The error appears to basically be identical. this is just by using the FCM messaging tool in firebase console, sending some test messages.

I also noticed this also https://github.com/morinel/gcmpush/issues/45 , no sure if there is a relationship, but it appears to be the same type and property.

I also found a thread here, that states the property might be added by google play services
https://bugs.chromium.org/p/chromium/issues/detail?id=639313

**Comment by the-simian** [comment]
I should add that this doesn't appear to break the module functionality - it still sends the notificaiton

**Comment by Chramar** [comment]
Is this problem fixed? I'm facing it right now and cannot find a solution

**Comment by TangerEye** [comment]
in package.json it says `"react-native-push-notifications": "^3.0.10"`

**Comment by Gp2mv3** [comment]
What's the output of `npm list react-native-push-notification` ?

**Comment by TangerEye** [comment]
It's `react-native-push-notifications@3.0.10`
