### ISSUE TITLE
onNotification is getting triggered as soon as notification is received in IOS

### ISSUE THREAD

**Issue by ajitdas123** [zo0r/react-native-push-notification#2240]
# Bug

`onNotification` Event handler is getting fired as soon an notification is received on IOS. 
Also, when user click on the notification, `onNotification` getting triggered but the data object doesn't have value.

But in android its working fine, when notification is recived, it doesnt get triggered. When user click on it, then only the `onNotification` is getting triggered and it also contain all the data.

## Environment info
Library version: 8.1.1

## Reproducible sample code

```
  PushNotification.configure({
            onNotification: function (notification) {
                if (!notification?.data) {
                    return;
                }
                console.log('[ON OPEN NOTIFICATION]', notification);
                onOpenNotification(Platform.OS === 'ios' ? notification.data : notification.data.data);
                if (Platform.OS === 'ios') {
                    notification.finish(PushNotificationIOS.FetchResult.NoData);
                }
            },

        });

```

**Comment by ajitdas123** [comment]
@Dallas62  Hello Dallas, Why did you close this? And any pointer why the event is getting fired without user interaction? 

And if that is the intended behavior, how to handle the user click event on IOS?

**Comment by Dallas62** [comment]
Hi @ajitdas123,
First of all, did you take time to read the documentation ?
Secondly, How do you think we can reproduce your issue since we don't have any reproducible "payload" of the notification ?

**Comment by ajitdas123** [comment]
@Dallas62, Yes I did the documentation and I have implemented it several times before, but older versions

As for how to reproduce, If you are aware, it's the same code base as given in the configuration under readme, I just removed the additional functions 
https://github.com/zo0r/react-native-push-notification#usage

And for IOS Configuration its the same thing as given in the example 

https://github.com/zo0r/react-native-push-notification/blob/master/example/ios/example/AppDelegate.m 

If you need any specific information, please tell i will be happy to share 
Thanks,

**Comment by Dallas62** [comment]
You can take a look at https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md

**Comment by Dallas62** [comment]
And https://github.com/zo0r/react-native-push-notification#state-of-the-repository

**Comment by ajitdas123** [comment]
@Dallas62 If you didn't know, you should let the community to help, there might be people who had faced similar issues and found a solution rather than showing some obvious documentation and showing the state of the repo. Thanks for being so helpful Mr Sponsor

**Comment by Dallas62** [comment]
As I already said, without the notification Payload, no one can help you.

**Comment by kaushikipandey** [comment]
> @Dallas62 Hello Dallas, Why did you close this? And any pointer why the event is getting fired without user interaction?
> 
> And if that is the intended behavior, how to handle the user click event on IOS?

hye @ajitdas123 ! Actually i want to trigger this function immediately after receiving a notification without user click...but unfortunately, it is getting triggered when i am clicking on notification. could you please give a suggestion how it can be done?

**Comment by ajitdas123** [comment]
@kaushikipandey  I am not sure,  But give this a try hopefully, this will help. 

On `onNotification`  inside  `PushNotification.configure` set `notification.userInteraction=true` 


So the function sould be something like this 

```
     onNotification: function (notification) {
             notification.userInteraction=true;  //<-- Add this here
             // More of your logics 
            },

```

**Comment by hkfreddy** [comment]
> @kaushikipandey I am not sure, But give this a try hopefully, this will help.
> 
> On `onNotification` inside `PushNotification.configure` set `notification.userInteraction=true`
> 
> So the function sould be something like this
> 
> ```
>      onNotification: function (notification) {
>              notification.userInteraction=true;  //<-- Add this here
>              // More of your logics 
>             },
> ```

I faced the same issue in iOS
I think the `userInteraction` value is to indicate whether the notification is pressed or not
So, instead of assigning a value to the property, 
you can check it to handle logic being called when notification is received or being pressed

```
PushNotification.configure({
    onNotification: function (notification) {

        if (notification.userInteraction) {
            //Being called when user pressed the notification
        }
        else{
            //Being called when the notification is received
        }
        notification.finish(PushNotificationIOS.FetchResult.NoData);
    },

});
```

But like what you said, the `data` object is empty when user press the notification
It should be a bug and I hope there is workground or fix to handle this....

**Comment by hkfreddy** [comment]
I just found that there is no `data` field in `PushNotification.localNotification`
and I'm using `data: remoteMessage.data`
If I use `userInfo: remoteMessage.data` instead,
the `data` field works fine when user press the notification
This should fix the problem, hope this help.

Cheers
