### ISSUE TITLE
userInteraction gives true in case of app killed

### ISSUE THREAD

**Issue by ghost** [zo0r/react-native-push-notification#2241]
So the case here when push notification arrives and app is in killed state. So rather tapping on notification banner, user press app icon instead. But still `userInteraction` gives `true`. But as per documentation it is written that it will `true` only if user taps on notification.

**Comment by Dallas62** [comment]
Hi,

Without an exemple, it's impossible to help you.

Regards

**Comment by ghost** [comment]
@Dallas62 : Here is my payload. I have killed the app, send notification. Open app via app icon and not by tapping notification banner.

`PNS BANNER ACTION HANDLER FOR FOREGROUND: {"action": undefined, "badge": undefined, "data": {"gcm.message_id": "1647498743299402", "google.c.a.e": "1", "google.c.fid": "fgltHtH8iEQxifAu2DIf-8", "google.c.sender.id": "633629696678", "remote": true, "url": "myapp://data/128636", "userInteraction": 1}, "finish": [Function finish], "foreground": false, "id": undefined, "message": "My App Body 12021", "reply_text": undefined, "soundName": "default", "subtitle": undefined, "title": "My App Notification title 12021", "userInteraction": true}`

You can see `"userInteraction": true` still.

My code: 

`  PushNotification.configure({
    onNotification: function (notification) {
      console.debug("PNS BANNER ACTION HANDLER FOR FOREGROUND:", notification);
      if (
        notification.userInteraction === true &&
        notification.foreground === true
      ) {
        handleAppRedirection(notification);
      }
      notification.finish(PushNotificationIOS.FetchResult.NoData);
    },
  });`

**Comment by daonamutc1** [comment]
I have the same problem

**Comment by leofusinato** [comment]
I had the same problem, but after updating the library to ^7.4.0 version, it fixed the problem.

**Comment by daonamutc1** [comment]
> 

I am using 8.1.1

**Comment by daonamutc1** [comment]
> I had the same problem, but after updating the library to ^7.4.0 version, it fixed the problem.


I am using 8.1.1, but still problem

**Comment by daonamutc1** [comment]
With IOS I check additional notification.action,
If notification.action has a value then it is the action tagging the notification

**Comment by yberstad** [comment]
Apologies for joining the discussion a bit late, but I'm currently facing this issue on iOS. 

While I haven't found a consistent way to reproduce it, it occurs quite frequently. Has anyone else experienced this problem? Better yet, has anyone managed to resolve it? I'm currently using the latest version of the package, though I know it's no longer maintained. 

I'm therefore considering switching to `expo-notifications` and would love to hear if anyone has experience with its implementation. Any insights or advice would be greatly appreciated!
