### ISSUE TITLE
push notifications and receiving FCM

### ISSUE THREAD

**Issue by code-by** [zo0r/react-native-push-notification#2244]
I'd like to generate local push notifications and also receive and display notifications receiving from FCM also. Do I need install `@react-native-firebase` also so my App will get notifications from FCM?

**Comment by irsyaadbp** [comment]
yes you must install ``@react-native-firebase/app`` and ``@react-native-firebase/messaging``
then you can call local notif when onMessage
![image](https://user-images.githubusercontent.com/23293993/165019708-c72a16c6-9d5e-43ca-a081-e3115525a2d7.png)
