### ISSUE TITLE
onRegister, get on iOS FCM Token

### ISSUE THREAD

**Issue by MinaSamir11** [zo0r/react-native-push-notification#2249]
# Feature Request

## Why it is needed
  it's needed because not to use multiple libraries to getFCM Token on iOS platform. 
-  resolving this issue requires is to install firebase messaging to get from FCM token, so instead of installing another lib is to implement native iOS genrate FCM token

+ onRegister, get on iOS FCM Token not APNs token since most RN  apps dealing with firebase to handle all platform notification.

## Possible implementation
 implement onRegister func, to build Token with APNs or FCM, therefore build FCM in native iOS according to flag.

**Comment by Dallas62** [comment]
Hi,

It's the wanted feature.
Use rn-firebase if you want firebase-only, see the state of repository on the readme.

Regards
