### ISSUE TITLE
I would like to volunteer to be a maintainer of this project!

### ISSUE THREAD

**Issue by Narmical** [zo0r/react-native-push-notification#2250]
I saw you were looking for maintainers of this library. I use this in a few of my projects and would like to volunteer. Let me know what additional questions you might have.

**Comment by Dallas62** [comment]
Hi @Narmical 

You have to join @zo0r by mail (available on his profil). He is the only one with rights to add you as maintainer.

There is no specific enrollment things.

I will support your request if needed 😉

**Comment by Narmical** [comment]
I don't se @zo0r 's email listed on his profile... only his twitter 🤔

**Comment by Dallas62** [comment]
Hi @Narmical 

Just send it to you by mail.
