### ISSUE TITLE
[question] how to work this library with notification fullscreen?

### ISSUE THREAD

**Issue by charleston10** [zo0r/react-native-push-notification#2252]
I have a question regarding the behavior of the library in the following scenario:

I need to show a full screen notification to a user, this notification will be like an IncomingCall
And it should show even with the app closed

I will send a push notification for this to happen

I have doubt if it is possible to make this scenario work

<table>
<tr>
<td>
<image src="https://user-images.githubusercontent.com/3097207/161326963-be881582-1646-4af4-b5f6-70d7ef570e5d.PNG" />
</td>
<td>
<image src="https://user-images.githubusercontent.com/3097207/161327063-6635ab84-48ce-4f7b-b1d3-85913e7d6b3b.PNG" />
</td>
</tr>
</table>

**Comment by Dallas62** [comment]
Hi @charleston10 

This library can not do that, you are probably looking for something like: react-native-callkeep

Regards
