### ISSUE TITLE
Question) How can I schedule the alarm for each day of the week?

### ISSUE THREAD

**Issue by Yummy-sk** [zo0r/react-native-push-notification#2255]
# Question

Hello, I would like to create an alarm app using react-native-push-notification.

Currently, I think it is possible to use `addnotificationRequest` to notify you about a specific day, but I am wondering how to schedule for a specific day.

For example, if a user has set up an alarm to go off on Monday, Tuesday, Thursday, Sunday, I wonder how to schedule it using `addNotificationRequest`

**Comment by diegobugs** [comment]
@Yummy-sk 
I have done something with scheduled notifications, but, is about notification and not with alarm, not sure if it is what you need.
![reminder local](https://user-images.githubusercontent.com/18753861/161991432-43023ff6-bdb6-48a4-97f9-eac1fe97aaed.jpeg)

Code is here: https://github.com/diegobugs/quoteapp/blob/develop/src/screens/AddReminderScreen/AddReminderScreen.tsx
