### ISSUE TITLE
onNotification is not triggered when the app is opened from background state on notification click

### ISSUE THREAD

**Issue by UmerQur3shi** [zo0r/react-native-push-notification#2259]
Hey @Dallas62 ,
I've implemented localNotificationSchedule in my app and it's working as expected when the app is active or in killed state, but onNotification in not triggered when the app is opened from background state. I've seen the older issues to fix the problem and there was a solution to edit SplashActivity.java which fixed it for some users but I can't see any SplashActivity.java in my project, please help.
Note: Push Notification is configured properly and is called in index.js not in any component. And it's working fine when the app is in killed state, only in background app state the onNotification is not triggered.

**Comment by UmerQur3shi** [comment]
@Dallas62  ?

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification#state-of-the-repository
