### ISSUE TITLE
Manifest merger failed : android:exported needs to be explicitly specified for <receiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined.

### ISSUE THREAD

**Issue by ashish293** [zo0r/react-native-push-notification#2261]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.medicinereminder">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
            android:value="false"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
            android:resource="@android:color/white"/>
    </application>
</manifest>

There is some issue with android sdk 12

**Comment by andrewtremblay** [comment]
See this other issue. 
https://github.com/zo0r/react-native-push-notification/issues/2220
Add `android:exported="false"` to your `<receiver>`s:
```
<receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" android:exported="false" />
etc...
```

**Comment by joaovitorqueiroz** [comment]
can you make work this library on android 12?

**Comment by sheggietyn** [comment]
Having this same issues any solution yet ?

**Comment by ashish293** [comment]
> See this other issue. #2220 Add `android:exported="false"` to your `<receiver>`s:
> 
> ```
> <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" android:exported="false" />
> etc...
> ```

**Comment by Neal-Tran-FEDL1** [comment]
Can you tell me what is the difference between android:exported="false" and android:exported="true". I am newbie, thank you

**Comment by andrewtremblay** [comment]
@edricnguyen-fed12 More information can be found in the android developer documentation https://developer.android.com/guide/topics/manifest/activity-element#exported

Historically you did not need to explicitly set this element to false. System constraints changed in Android 12. You can read more about them here: 
https://developer.android.com/about/versions/12/behavior-changes-12#exported

**Comment by bsdaoquang** [comment]
> See this other issue. #2220 Add `android:exported="false"` to your `<receiver>`s:
> 
> ```
> <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" android:exported="false" />
> etc...
> ```

thank so much, it work with me

**Comment by shahmir2000** [comment]
@bsdaoquang  it not working

**Comment by dominhgiangbboy** [comment]
> See this other issue. #2220 Add `android:exported="false"` to your `<receiver>`s:
> 
> ```
> <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" android:exported="false" />
> etc...
> ```

Work for me thanks you!

**Comment by denialfarizi1** [comment]
> See this other issue. #2220 Add `android:exported="false"` to your `<receiver>`s:
> 
> ```
> <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" android:exported="false" />
> etc...
> ```

work for me or you can add `android:exported="true"` to your `<receiver>`

**Comment by ravindra3003** [comment]
what is the difference between android:exported="true" and android:exported="false"? please anyone can help me to understand why I need to true or false android:exported?

**Comment by iamandiradu** [comment]
@ravindra3003 Here's the documentation explaining
https://developer.android.com/guide/topics/manifest/activity-element#exported

**Comment by adam-socal** [comment]
**This is still not working after adding android:exported="true" to my ```<activity>``` I really need to get this working as I have to update my app with new features. Can someone please help me with this?** 

**build.gradle**
```
buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 28
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "21.4.7075529"
        googlePlayServicesAuthVersion = "19.2.0" // <--- use this version or newer
        // these three are required for react-native-maps
        supportLibVersion   = "30.0.2"
        playServicesVersion = "17.0.0"
        androidMapsUtilsVersion = "2.3.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.2")
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.1'
```
**main/AndroidManifest.xml**
```
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:screenOrientation="portrait"
        android:exported="true">


        <intent-filter android:autoVerify="true">
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
        <intent-filter >
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:host="ousa.page.link" android:scheme="https"/>
        </intent-filter>
      </activity>
    </application>
    <!-- added this queries tag to solve the issue of YT app not found above Android 11 when playing a YT video -->
    <queries>
      <intent>
        <action android:name="com.google.android.youtube.api.service.START" />
      </intent>
    </queries>
</manifest>
```

**Comment by ravindra3003** [comment]
@adamodusa first open your project in android studio click on android/app/src/main/AndroidManifest.xml and click on 'Merged Manifest' and scroll down if appear any android:exported error then solve **for example** Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details. My_App.app main manifest (this file)

**Add android:exported "true" or "false"**

still, no luck then debug with USB on the android v12 phone or virtual device you can easily see the issue in your cmd. (where you need to add). 
If you have any confusion let me know I will explain again.

**Comment by adam-socal** [comment]
@ravindra3003  Thanks for the help. I ran the simulator and it gave me the error path. node_modules/react-native-trackplayer/android/src/main/AndroidManifest.xml.  My problem was I did not know this AndroidManifest.xl was in the node_modules .  I found the ```<reciever>``` tag there and added ```android:exported="false"``` and it worked. 

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.guichaguri.trackplayer">

    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

    <application>

        <!-- The main service, handles playback, playlists and media buttons -->
        <service android:name=".service.MusicService" android:enabled="true" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </service>

        <!-- A receiver that will receive media buttons. Required on pre-lollipop devices -->
        <receiver android:name="androidx.media.session.MediaButtonReceiver" android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </receiver>
    </application>

</manifest>

```

**Comment by mustafazeb381-123** [comment]
> See this other issue. #2220 Add `android:exported="false"` to your `<receiver>`s:
> 
> ```
> <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" android:exported="false" />
> etc...
> ```

that help me sir thanx for helping

**Comment by basit112** [comment]
I am getting the same error after adding [exported ](android:exported="") line 

```
 Error:
	android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined.
```

**Comment by basit112** [comment]
```
<activity
            android:name=".MainActivity"
            android:exported="true"
            tools:node="merge">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <provider
            android:name="androidx.work.impl.WorkManagerInitializer"
            android:authorities="${applicationId}.workmanager-init"
            android:exported="false" />
```


i am still getting error on this

**Comment by chandu-abhi** [comment]
check this one : 

<receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver" android:exported="false">

**Comment by chandu-abhi** [comment]
check this one : 
<receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver" android:exported="false">
