### ISSUE TITLE
scheduled notifications seem to get canceled after next day

### ISSUE THREAD

**Issue by siddheshR12** [zo0r/react-native-push-notification#2263]
Hi,

1) I had scheduled 1 hourly notification, which works fine for the same day, it was working till morning 10am next day but after that it just stopped, didn't get any notification.
this is the code for hourly notification
```
let scheduleDate = dayjs()
    .add(1, "hour")
    .toDate();

PushNotification.localNotificationSchedule({
    ...defaulNotificationProps,
    title, // (optional)
    message, // (required)
    date: scheduleDate,
    repeatType: "hour",
    /* Android Only Properties */
    repeatTime: 1
  });
```
Is there any problem with the repeattype and repeat time

2) also had scheduled a weekly notification on friday every week, scheduled it on Thursday, it was showing to be scheduled in 
```
PushNotification.getScheduledLocalNotifications
```
but didn't trigger on Friday that is today it was set for 4pm or day=5 and hour=16

here's the code for it

```
let scheduleDate = dayjs()
          .set("day", day)
          .set("hour", hour)
          .set("minute", 0)
          .set("second", 0)
          .toDate();
          
PushNotification.localNotificationSchedule({
    ...defaulNotificationProps,
    title, // (optional)
    message, // (required)
    date: scheduleDate,
    repeatType: "week",
    /* Android Only Properties */
    repeatTime: 1
  });
```
again, are the repeatType and repeatTime props proper? or have I done any mistake in calling them, coz the getScheduledLocalNotifications shows the notification is set at proper time

Or is it some problem with android 12, my target sdk version is 29 but i was testing on android 12, device Poco x3 MiUI.
react native version is above 0.62.2

Thank you

**Comment by Dallas62** [comment]
Hi,
https://dontkillmyapp.com/
Regards

**Comment by siddheshR12** [comment]
thank you
