### ISSUE TITLE
gguwbashs@gnmro.tk

### ISSUE THREAD

**Issue by scshiv29-dev** [zo0r/react-native-push-notification#2264]
# Bug

## Environment info

`react-native info` output:

```bash
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 7.59 GB / 15.95 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 26, 27, 29, 30, 31
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 31.0.0, 33.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: 16.10.31424.327 (Visual Studio Community 2019)
  Languages:
    Java: 15.0.2
    Python: 3.10.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: x.x.x

## Steps To Reproduce

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction    
   > Android resource linking failed
     ERROR:E:\PROJECT\React Native\Gita\android\app\build\intermediates\packaged_manifests\debug\AndroidManifest.xml:21: AAPT: error: unexpected element <receiver> found in <manifest>.

     ERROR:E:\PROJECT\React Native\Gita\android\app\build\intermediates\packaged_manifests\debug\AndroidManifest.xml:22: AAPT: error: unexpected element <receiver> found in <manifest>.

     ERROR:E:\PROJECT\React Native\Gita\android\app\build\intermediates\packaged_manifests\debug\AndroidManifest.xml:23: AAPT: error: unexpected element <receiver> found in <manifest>.

**Comment by Dallas62** [comment]
Hi,
Please recheck your AndroidManifest.xml
Not a library issue.
Regards

**Comment by scshiv29-dev** [comment]
@Dallas62  the issue is from the code i pasted from the library documentation

**Comment by Dallas62** [comment]
Yes, from the code you pasted. Not from the library.
Check your configuration according to the exemple project.
You probably made a mistake.

**Comment by scshiv29-dev** [comment]
@Dallas62  sir

**Comment by scshiv29-dev** [comment]
@Dallas62  sir 
`
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>
        `
        this is the code where m getting an error and its from the documentation . I've tried almost all the solutions i could find but the issue still persist.
         If you could please help me fix this i would mean a lot 
         thanks.

**Comment by Dallas62** [comment]
You can paste the part of the code, but it's not a problem with this particular code. It's an issue of where you pasted it.

```sh
error: unexpected element <receiver> found in <manifest>.
```

Please, re-read the documentation.

```xml

In your android/app/src/main/AndroidManifest.xml

    .....
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <application ....>
        <!-- Change the value to true to enable pop-up for in foreground on receiving remote notifications (for prevent duplicating while showing local notifications set this to false) -->
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="false"/>
        <!-- Change the resource name to your App's accent color - or any other color you want -->
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@color/white"/> <!-- or @android:color/{name} to use a standard color -->

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
     .....

```
