### ISSUE TITLE
RNCPushNotificationIOS didReceiveRemoteNotification triggered on iOS side but not in the JS bundle side when app was killed 

### ISSUE THREAD

**Issue by jeremymZen148** [zo0r/react-native-push-notification#2267]
Hello 

we have a specific use case when an external app is triggering at the same time deep link and push notification.
When the app is killed (only if it was killed) on iOS side we are able to debug and see that RNCPushNotificationIOS didReceiveRemoteNotification is triggered but on JS side nothing,  nothing triggered..
I found a workaround is to add a delay of 1.5 sec on iOS side in `- (void)application:(UIApplication *)application
        didReceiveRemoteNotification:(NSDictionary *)userInfo
        fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler` : 

  
`double delayInSeconds = 1.5;
    dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, (int64_t)(delayInSeconds * NSEC_PER_SEC)); // 1
    dispatch_after(popTime, dispatch_get_main_queue(), ^(void){ // 2
      [RNCPushNotificationIOS didReceiveRemoteNotification:notification fetchCompletionHandler:completionHandler];
    });`
and its working but its not very smooth and clean.

I suspect that the RNCPushNotificationIOS bridge or JS module are not totally initialized at that moment, there is a way to know if the package has not been initialized and to apply the delay only for that specific use case?

**Comment by hypnocill** [comment]
Did you find a better solution to this @jeremymZen148

**Comment by jeremymZen148** [comment]
No

**Comment by ysshir** [comment]
Is there an alternative solution for this issue?
I set 5sec delay, but when I'm using another application, such as Pokémon Go, I sometimes don't receive notifications.
