### ISSUE TITLE
Cannot see notification on IOS.

### ISSUE THREAD

**Issue by nicolabortignon** [zo0r/react-native-push-notification#227]
I can see local notification on Android.

I receive the callback **onNotification** on iOS, but I cannot see any notifications on my iSimulator. 
Running ios10, xocde 8.

No **onRegister** events are received, neither on iOS or Android simulators. 
anyone else with this problem ? 

1) Do you know if I need a developer certificate to run this on a physical device? 
2) Why I'm not getting a token back on on Register?
3) anyone else having the same problem ?

**Comment by Brockify** [comment]
+1

**Comment by npomfret** [comment]
Are you testing remote or local notifications?  Remote push notifications do not work on a simulator.

1) I am not sure, but I believe for local notifications you do not need an account, but this is something you can probably check with some googling.

2)  iOS

Have you checked that your AppDelegate.m has the necessary addition code that's described in the readme?

Is the iOS push notification project linked into your project correctly?

Are you seeing any error messages when the app starts?

2) Android

Have you followed the instructions in the readme?  Is you manifest file correct?  I've observed that making changes to the manifest aren't picked up by android studio sometimes.  You need to kill the app and force a rebuild.

Have you entered working CGM sender id?  Where did you get it from?

**Comment by nicolabortignon** [comment]
(here is the repo with my project, in case you want to have a look :  https://github.com/nicolabortignon/RNSelfy )

1) I searched that and it seams that with xcode 8 you cannot test local notification on the iSimulator. And in order to test push notification on a device you need the enrolled certificate (was wondering if anyone can confirm)

2) yes, I followed all the steps, AppDelegate has been updated as well as the linking.
No error during bootstrap. Every time i trigger a local notification I receive correctly an onNotification events, so I believe the 'loop' is closed correctly, just no visual clue on the iSimulator, which seams to confirm point 1.

3) Yep, followed all the steps. I generated a GCM account on firebase, download the json and use the projectID as the GCM sender id (as found in one of the issues in this repo)

**Comment by npomfret** [comment]
1) yes that sounds accurate.  Local notification work on an iOS simulator, but push notifications don't.

Have you updated your manifest file?  If you look at logcat  in android studio, and file for "RNPushNotification", do you see anything after the notification is sent?

**Comment by Brockify** [comment]
I also see the notification from onNotification and have followed everything, but am not able to see a local notification

**Comment by npomfret** [comment]
What do you mean 'see'?  Do you mean you can't visually 'see' an alert in the notification centre.  Or you don't see `onNotification` being called?

Is your app running in the foreground or background?

**Comment by nicolabortignon** [comment]
For the record, 
I cannot see the visual notification on iSimulator (and I'm sending a Local Notification).
I can see the onNotification being called, and the notification object being sent correctly. 

no difference if the app is in background or foreground.

**Comment by npomfret** [comment]
I think it's working, you don't 'see' notifications if the app is running. Local notifications should show if the app is running in the background.  What happens if you do this when your app starts:

```
    PushNotification.localNotificationSchedule({
      message: "hello",
      date: new Date(Date.now() + (10 * 1000))
    });
```

And then quickly background the app

**Comment by semiautomatix** [comment]
I'm sure I'm using the correct Sender ID, but no luck :(

**Comment by npomfret** [comment]
SenderId is only required to received Android remote push notifications.  This topic is about iOS.

**Comment by semiautomatix** [comment]
@npomfret sorry, I was redirected here from the Android thread "onRegister callback is never called, both on Android and iOS #206"

But, as per that thread I believe I've finally got it working! So thanks :)

**Comment by klinkov** [comment]
Same issue, no visual for remote notification

**Comment by witalobenicio** [comment]
@npomfret how can we show a notification in iOS when the app is active? Like Whatsapp for example (it shows a top notification that appears to be inside the app)

**Comment by witalobenicio** [comment]
@nicolabortignon Could you please show me how you've configured your project to receive notifications from iOS? I get onRegister called with the token being returned, but I'm not able to get `'onNotification'` called.
I tried to use this site to send a notification to iOS: https://www.pushwatch.com/apns/
