### ISSUE TITLE
There is not userInfo field in method GetDeliveredNotifications

### ISSUE THREAD

**Issue by alexTamilouski** [zo0r/react-native-push-notification#2271]
# Question
Hello!
I created a local push notification and I want to have data inside.
      PushNotification.createChannel(
        {
          channelId: '11223344', // (required)
          channelName: 'My channel', // (required)
          channelDescription: 'A channel to categorise your notifications' // (optional) default: undefined.
        },
        created => console.log(`createChannel returned '${created}'`) // (optional) callback returns whether the channel was created, false means it already existed.
      );
      PushNotification.localNotification({
        /* Android Only Properties */
        channelId: '11223344', // (required) channelId, if the channel doesn't exist, notification will not trigger.
        largeIcon: 'ic_launcher', // (optional) default: "ic_launcher". Use "" for no large icon.
        largeIconUrl: 'https://www.example.tld/picture.jpg', // (optional) default: undefined
        bigText:
          'My big text that will be shown when notification is expanded. Styling can be done using HTML tags(see android docs for details)', // (optional) default: "message" prop
        subText: 'This is a subText', // (optional) default: none
        color: 'red', // (optional) default: system default
        category: 'Invites', // (optional) default: empty string

        /* iOS and Android properties */
        id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        title: 'My Notification Title', // (optional)
        message: 'My Notification Message', // (required)
        **userInfo: {contentId: 1111} // (optional) default: {} (using null throws a JSON value '<null>' error)**
      });
      
      I can see my data when I process notifications, but the optional field userInfo in the method getDeliveredNotifications is absent.
     Did I do something wrong or does it look like a bug?

**Comment by saif-o99** [comment]
it is a bug

**Comment by zahid502** [comment]
I'm facing this issue. Need to be fixed.

**Comment by hoyoungmoon** [comment]
i solved this issue by adding `addExtras` in NotifiationCompat.Builder. It's my .patch file

```
diff --git a/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java b/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
index 248ff08..cf4263c 100644
--- a/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
+++ b/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
@@ -276,13 +276,16 @@ public class RNPushNotificationHelper {
                 channel_id = this.config.getNotificationDefaultChannelId();
             }
             
+            Bundle extras = new Bundle();
+            extras.putString("userInfo", bundle.getString("userInfo"));
             NotificationCompat.Builder notification = new NotificationCompat.Builder(context, channel_id)
                     .setContentTitle(title)
                     .setTicker(bundle.getString("ticker"))
                     .setVisibility(visibility)
                     .setPriority(priority)
                     .setAutoCancel(bundle.getBoolean("autoCancel", true))
-                    .setOnlyAlertOnce(bundle.getBoolean("onlyAlertOnce", false));
+                    .setOnlyAlertOnce(bundle.getBoolean("onlyAlertOnce", false))
+                    .addExtras(extras);
             
             if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) { // API 24 and higher
                 // Restore showing timestamp on Android 7+
@@ -737,6 +740,7 @@ public class RNPushNotificationHelper {
         notif.putString("identifier", "" + notification.getId());
         notif.putString("title", extras.getString(Notification.EXTRA_TITLE));
         notif.putString("body", extras.getString(Notification.EXTRA_TEXT));
+        notif.putString("userInfo", extras.getString("userInfo"));
         notif.putString("tag", notification.getTag());
         notif.putString("group", original.getGroup());
         result.pushMap(notif);
@@ -959,3 +963,4 @@ public class RNPushNotificationHelper {
         return false;
     }
 }
+
diff --git a/node_modules/react-native-push-notification/index.js b/node_modules/react-native-push-notification/index.js
index 716ea0e..d9cd5fe 100644
--- a/node_modules/react-native-push-notification/index.js
+++ b/node_modules/react-native-push-notification/index.js
@@ -551,8 +551,28 @@ Notifications.removeAllDeliveredNotifications = function() {
   return this.callNative('removeAllDeliveredNotifications', arguments);
 }
 
-Notifications.getDeliveredNotifications = function() {
-  return this.callNative('getDeliveredNotifications', arguments);
+Notifications.getDeliveredNotifications = function(callback) {
+  const mapNotifications = (notifications) => {
+    let mappedNotifications = [];
+    if(notifications?.length > 0) {
+      mappedNotifications = notifications.map(notif => {
+        try {
+          notif.userInfo = JSON.parse(notif.userInfo);
+        } catch(e) { }
+        return ({
+          ...notif,
+          userInfo: notif.userInfo,
+        })
+      })
+    }
+    callback(mappedNotifications);
+  }
+
+  if(Platform.OS === 'ios'){
+    return this.callNative('getDeliveredNotifications', arguments);
+  } else {
+    return this.callNative('getDeliveredNotifications', [mapNotifications]);
+  }
 }
 
 Notifications.getScheduledLocalNotifications = function(callback) {

```

**Comment by DenisPostnikov** [comment]
> i solved this issue by adding `addExtras` in NotifiationCompat.Builder. It's my .patch file
> 
> ```
> diff --git a/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java b/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
> index 248ff08..cf4263c 100644
> --- a/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
> +++ b/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java
> @@ -276,13 +276,16 @@ public class RNPushNotificationHelper {
>                  channel_id = this.config.getNotificationDefaultChannelId();
>              }
>              
> +            Bundle extras = new Bundle();
> +            extras.putString("userInfo", bundle.getString("userInfo"));
>              NotificationCompat.Builder notification = new NotificationCompat.Builder(context, channel_id)
>                      .setContentTitle(title)
>                      .setTicker(bundle.getString("ticker"))
>                      .setVisibility(visibility)
>                      .setPriority(priority)
>                      .setAutoCancel(bundle.getBoolean("autoCancel", true))
> -                    .setOnlyAlertOnce(bundle.getBoolean("onlyAlertOnce", false));
> +                    .setOnlyAlertOnce(bundle.getBoolean("onlyAlertOnce", false))
> +                    .addExtras(extras);
>              
>              if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) { // API 24 and higher
>                  // Restore showing timestamp on Android 7+
> @@ -737,6 +740,7 @@ public class RNPushNotificationHelper {
>          notif.putString("identifier", "" + notification.getId());
>          notif.putString("title", extras.getString(Notification.EXTRA_TITLE));
>          notif.putString("body", extras.getString(Notification.EXTRA_TEXT));
> +        notif.putString("userInfo", extras.getString("userInfo"));
>          notif.putString("tag", notification.getTag());
>          notif.putString("group", original.getGroup());
>          result.pushMap(notif);
> @@ -959,3 +963,4 @@ public class RNPushNotificationHelper {
>          return false;
>      }
>  }
> +
> diff --git a/node_modules/react-native-push-notification/index.js b/node_modules/react-native-push-notification/index.js
> index 716ea0e..d9cd5fe 100644
> --- a/node_modules/react-native-push-notification/index.js
> +++ b/node_modules/react-native-push-notification/index.js
> @@ -551,8 +551,28 @@ Notifications.removeAllDeliveredNotifications = function() {
>    return this.callNative('removeAllDeliveredNotifications', arguments);
>  }
>  
> -Notifications.getDeliveredNotifications = function() {
> -  return this.callNative('getDeliveredNotifications', arguments);
> +Notifications.getDeliveredNotifications = function(callback) {
> +  const mapNotifications = (notifications) => {
> +    let mappedNotifications = [];
> +    if(notifications?.length > 0) {
> +      mappedNotifications = notifications.map(notif => {
> +        try {
> +          notif.userInfo = JSON.parse(notif.userInfo);
> +        } catch(e) { }
> +        return ({
> +          ...notif,
> +          userInfo: notif.userInfo,
> +        })
> +      })
> +    }
> +    callback(mappedNotifications);
> +  }
> +
> +  if(Platform.OS === 'ios'){
> +    return this.callNative('getDeliveredNotifications', arguments);
> +  } else {
> +    return this.callNative('getDeliveredNotifications', [mapNotifications]);
> +  }
>  }
>  
>  Notifications.getScheduledLocalNotifications = function(callback) {
> ```

I see userInfo field, but value is null. Do you see value?
