### ISSUE TITLE
A problem occurred configuring project ':react-native-push-notification' Expo Bare Workflow

### ISSUE THREAD

**Issue by daastrading** [zo0r/react-native-push-notification#2272]
**I got this error after Upgrading The Gradle Plugin to 7.2.0 And Gradle Version 7.4.2.**

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-push-notification'.
> Could not load compiled classes for build file 'E:\Application\daastradingapp\node_modules\react-native-push-notification\android\build.gradle' from cache.
```

Iam using Expo Bare Workflow.

Now I cannot build my project using : expo run:android or npm run android How to fix it ? Any help would be appreciated. Thank You

**Comment by mavine4512** [comment]
I am also getting the same issue, React native 0.74.1 node -v 18.18.0 compileSdkVersion = 34, targetSdkVersion = 34 kotlinVersion = "1.9.22":

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-push-notification'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
