### ISSUE TITLE
Library not found for -lRNCPushNotificationIOS in xcode

### ISSUE THREAD

**Issue by alfatayah** [zo0r/react-native-push-notification#2278]
# Bug
   When building an app in Xcode error appears  "Library not found for -lRNCPushNotificationIOS"

## Environment info
      "react-native": "^0.63.3",
      "react": "^16.13.1",

Library version:  "react-native-push-notification": "^7.4.0",

## Steps To Reproduce
1. Im upgrade library from "react-native-push-notification": "^5.1.0" to "^7.4.0",
2. Run pod install —repo-update before building app in xcode

## Screenshot
![image](https://user-images.githubusercontent.com/23058601/176075798-da96e411-a1cc-420a-9b0b-d7f839e589b0.png)

Library not found for -lRNCPushNotificationIOS in Xcode

**Comment by alfatayah** [comment]
.

**Comment by sebastianhoeck** [comment]
I have the same issue, do you have a solution for this?

**Comment by alfatayah** [comment]
> I have the same issue, do you have a solution for this?

I'm upgrading react native push notification  to the latest update => 8.1.1 then if you are using "@react-native-community/push-notification-ios" upgrade too for the latest update
