### ISSUE TITLE
Local notifications fail to adjust when timezone shifts in users device

### ISSUE THREAD

**Issue by ctx-nelias-NeliasClick** [zo0r/react-native-push-notification#2283]
# Question
Hello, 
When the timezone shifts because of travel in a user's device, the local app notifications will continue to come through according to the original timezone they were set in, is there any solution for this ?

**Comment by churchnotesapp** [comment]
Any update on this?

**Comment by lp-noel** [comment]
Encountering the same issue, any guidance?
