### ISSUE TITLE
Failing to Send Notification with ReplyInput Action on Android

### ISSUE THREAD

**Issue by n-mullins** [zo0r/react-native-push-notification#2284]
After upgrading my targetSdkVersion and compileSdkVersion to 31 (Android 12), I am getting the following error when attempting to schedule any notification that includes a "ReplyInput" action on an Android 12 device

![179281355-3846200a-7bcf-4566-9d08-5f7054b348ae](https://user-images.githubusercontent.com/37455885/183527857-e07a7fa5-a4ac-42ca-b705-25acb3ed85a6.png)

For reference, I am on the latest version of the package (8.1.1) and have included a screenshot of my react-native dependencies and build.gradle file below

<img width="440" alt="Screen Shot 2022-08-08 at 6 00 39 PM" src="https://user-images.githubusercontent.com/37455885/183528725-a9479a4f-7264-4eee-8086-8d8aa71e3c4b.png">

<img width="454" alt="Screen Shot 2022-08-08 at 6 04 30 PM" src="https://user-images.githubusercontent.com/37455885/183529261-a824425a-032c-4f13-b016-21c83529b243.png">

**Comment by n-mullins** [comment]
Problem seems to have been a local issue and has resolved itself after a system restart. Closing out this issue.

**Comment by tahasiddiqui1** [comment]
Hi @n-mullins could you tell us how did you solve this issue in android 12?
