### ISSUE TITLE
duplicate notification in custom sound

### ISSUE THREAD

**Issue by mahdiyeh1994** [zo0r/react-native-push-notification#2285]
# Question

I'm using react-native-push-notification and firebase for receiving notifications in my app.
I receive duplicate notifications when the app is both in the foreground and background.
Does it possible duplicate messages received because the back-end sends a notification message in the 'notification' object of the data property? If yes, please inform me how I can prevent multiple receives without back-end changes?

Also, The application has 6 custom sounds, the user can choose one and change the notification sound. Because of this, I wrote createChannel for each sound. And when the notification is sent, based on its sound, there is a condition in which channelId will be played. if this is the reason for the duplicate message, what else can I do?

P.S. I don't have GCM in my AndroidManifest.xml.

**Comment by nahidmbstu** [comment]
same problem . Duplicate notification for scheduled notifications.
