### ISSUE TITLE
Scheduled Notification not coming when an app is killed.

### ISSUE THREAD

**Issue by scrapecoder** [zo0r/react-native-push-notification#2294]
# Bug

Scheduled notification not working when an app is killed. it's only working for foreground & background states and also custom sound and default sound not playing.
I added `noti_sound.wav` to `android/app/src/main/res/raw` and using it as `soundName: noti_sound.wav`.

## Environment info

`react-native info` output:

```bash
"react-native": "0.68.1",
"react-native-push-notification": "^8.1.1",
```

Library version: 8.1.1

`PushNotification.localNotificationSchedule({
    channelId: 'channelId',
    message: 'My Notification Message' + notiDate, // (required)
    date: new Date(notiDate),
    playSound: true,
    soundName: 'PushNotification.localNotificationSchedule({
    channelId: 'superAppChannel',
    message: 'My Notification Message' + notiDate, // (required)
    date: new Date(notiDate),
    playSound: true,
    soundName: 'noti_sound.wav',
    vibrate: true,
    repeatType: 'day',
  });,
    vibrate: true,
    repeatType: 'day',
  });`

**Comment by BrandonMA** [comment]
Did you find any solution for this? Or did you move to another library?

**Comment by Thanos2610** [comment]
Not working perfectly in debug mode but t's working fine in release mode.

**Comment by scrapecoder** [comment]
@BrandonMA  working fine in release mode. You have to test it in to release mode.

**Comment by Aure77** [comment]
> Did you find any solution for this? Or did you move to another library?

Please read doc: https://github.com/zo0r/react-native-push-notification#notification-while-idle
Seems to be related to DOZE behavior with scheduled notification.

**Comment by govindavashishtha** [comment]
I'm also facing the same issue, it is happening in both Android and iOS.
I tried logging the array from `PushNotification.getScheduledLocalNotifications(callback)` function, and it returned an empty array after app is restarted.

**Comment by Redant-gowshik** [comment]
I am also facing the same issue
