### ISSUE TITLE
Opaque Android Error

### ISSUE THREAD

**Issue by jgretz** [zo0r/react-native-push-notification#23]
I have installed the NPM package, and followed the instructions in the readme. As soon as a boot the app, I get the error below (found in logcat, it never actually hits my code). 

I've googled for a bit, but found no real solutions. If I remove the package from the compile the app builds and runs fine:

java.lang.NoSuchMethodError: No static method zzy(Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzx; or its super classes (declaration of 'com.google.android.gms.common.internal.zzx' appears in /data/app/com.softwriters.pod-1/base.apk)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at com.google.android.gms.measurement.internal.zzt.zzaU(Unknown Source)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at com.google.android.gms.measurement.AppMeasurementContentProvider.onCreate(Unknown Source)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-07 13:45:41.927  3595  3595 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-07 13:45:41.932  1287  1730 W ActivityManager:   Force finishing activity app/.MainActivity

**Comment by pewh** [comment]
Had you figured out why that error happened?

**Comment by jgretz** [comment]
Somewhat.

I ended up using Android Studio in a similar way I use Xcode. In Android Studio, there is a sync gradle button, which once I ran it took care of this issue
