### ISSUE TITLE
How to restore notifications?

### ISSUE THREAD

**Issue by Arkanine** [zo0r/react-native-push-notification#230]
Please help me to figure out how to restore notifications after disabling  - PushNotification.cancelAllLocalNotifications()?

**Comment by npomfret** [comment]
PushNotification.cancelAllLocalNotifications doesn't 'disable', it effectively deletes them I believe.  There is no way to disable  notifications.

**Comment by Arkanine** [comment]
For now it's clear, thank you @npomfret!
