### ISSUE TITLE
Android onNotification fired only when notification received but not when open or click notification

### ISSUE THREAD

**Issue by N0urhan-Adel** [zo0r/react-native-push-notification#2306]
# Question

need to detect notification click to open specific screen , but onNotification method not fired when click on notification, it is only fired when notification received.

**Comment by Hari-krish-v** [comment]
I'm also facing the same issue listener only works when the notification arrives after that it is not working. The issue strikes only when we directly navigate to a screen from notification and click another notification from the screen.
Note : I am using splash activity on my project
