### ISSUE TITLE
onNotification not fired when tapped notification it is only fire when notification received ?

### ISSUE THREAD

**Issue by N0urhan-Adel** [zo0r/react-native-push-notification#2309]
Please help :( why onNotification not fired when tapped notification?

**Comment by marcosfreitas** [comment]
I'm stuck with this same problem.

**Comment by dooamindshine** [comment]
I am also facing same problem in IOS, when you tap on local notification onNotification is not fired

**Comment by sofia-bahamonde** [comment]
+1

**Comment by dodokw** [comment]
same here +2

**Comment by chenkuangkuang** [comment]
same here +3
