### ISSUE TITLE
Can I run code when notification appears?

### ISSUE THREAD

**Issue by jsdario** [zo0r/react-native-push-notification#231]
In my case, and I have only tested with scheduled notifications, it seems that `onNotification` only fires when I open the app from the notification. I want to trigger some actions when the app is killed or on the background following a certain schedule.

**Comment by npomfret** [comment]
Is this a change in behaviour that you have observed as a result of the changes that were made?

**Comment by jsdario** [comment]
I am pretty new to this project, so I guess not.

**Comment by jsdario** [comment]
Sorry – I do not understand why this issue has been closed, can anyone briefly answer please?

**Comment by npomfret** [comment]
Oops, sorry - pressed the wrong button.

**Comment by npomfret** [comment]
I don't believe what you are after is supported.

Scheduled notifications result in a call to onNotification only if they happen while the app is running.  Otherwise they appear as an alter in the notification centre. 

I think if you want to run periodic scheduled tasks this isn't the right way to do it.

**Comment by npomfret** [comment]
Also, the change thats in master that is currently being tested will allow you rot run code when a notification arrives even if the app isn't running at all.  It only works on Android though

**Comment by jsdario** [comment]
I am looking only for android possibilities in this moment. Also will develop cloud tasks in the future, but for the moment only local. I am running a bit short of time, but no doubt the `AlarmManager` looks good.

**Comment by robinmitra** [comment]
@npomfret I'm using latest code from master. When I select a notification action, nothing happens and the notification stays, if the app is not running in background. If, however, the app runs in the background, selecting a notification action does in fact work and the notification gets removed. 

So, I guess currently code doesn't run if app isn't running in the background.

**Comment by npomfret** [comment]
The change that wen't into master means that code can run when a push notification is delivered and the app isn't running.  It only works on Android and you need to set your push notifications up outside of the react lifecycle.  Its not easy to explain, I think we need to add some docs to the readme.

Basically, you need to make sure the `configure` method is called as a side effect of importing your code, and not inside a react lifecycle method.

**Comment by jsdario** [comment]
Sounds great, could we see a little example? I think I can try to figure it out, but still do not grasp the "as a side effect of importing your code".

**Comment by jsdario** [comment]
Hi again,

I already configured such method as a "side effect" but any code I place under "onNotification" is solely ran if I open the app through clicking on the notification center (Android). Do I have to configure it any differently?

**Comment by jsdario** [comment]
Update here.

Thanks for creating the `TroubleShooting.md` guide. I wanted to trigger JS code with a dead app but directly from a scheduled notification, which seems not to be possible.

Is there a way to achieve this? If so, I am open to PR.

**Comment by npomfret** [comment]
I don't know if opening a terminated app from a scheduled notification is possible. @varungupta85 may have some ideas

**Comment by varungupta85** [comment]
@jsdario I just tested what happens if I click on a scheduled local notification when the app has been terminated and it just launched my app. It is possible that the `onNotification` may not be called in such scenarios. I didn't have time to test that piece. You should look into using `popInitialNotification` to check if you can access the local notification from there when the app is cold launched from a notification which is what it is supposed to do I guess.

**Comment by jsdario** [comment]
I'll be closing since we have had no updates in a long time.

**Comment by nonameolsson** [comment]
Hi! It seems like this is stlil an issue. Has there been any progress on this? #170 check my latest comment in that thread please. 
And keep up the good work! @zo0r
