### ISSUE TITLE
When app is killed, tapping on certain push notification should not launch the app.

### ISSUE THREAD

**Issue by yasir-syed** [zo0r/react-native-push-notification#2313]
Hi, I have a strange requirement, when app is killed (not running) and a push notification is received, i do not want the app to launch, but notification should dismiss on tap. And this behaviour is not required for every notification, but few particular notification.
I am using Firebase notifications.

"@react-native-community/push-notification-ios": "^1.8.0",
"@react-native-firebase/app": "^10.5.0",
"@react-native-firebase/messaging": "^10.5.1", 
 "react": "16.9.0",
"react-native": "0.61.5",
"react-native-push-notification": "^7.3.0",

**Comment by Dallas62** [comment]
Hi,

Please look at the Readme for alternative libraries.

I do not maintain this library anymore.

Regards

**Comment by yasir-syed** [comment]
OK Thanx
