### ISSUE TITLE
How to Stop Miscellaneous channel in React-native for React-native Push Notification Using Firebase

### ISSUE THREAD

**Issue by dev-the-developer09** [zo0r/react-native-push-notification#2319]
# Question
Hello guys Can Anyone help to find how to stop Miscellaneous Channel in in notification setting 
Becouse this channel is showing me Twise Pop-up when I Send Pop-up in  app when my app is in quit state .
I am using React-natiuve-push-notification And Sending Notification via Firebase

**Comment by msaadqureshi** [comment]
> # Question
> Hello guys Can Anyone help to find how to stop Miscellaneous Channel in in notification setting Becouse this channel is showing me Twise Pop-up when I Send Pop-up in app when my app is in quit state . I am using React-natiuve-push-notification And Sending Notification via Firebase

i have same issue, did you find the solution share please

**Comment by DinoZenka** [comment]
> > # Question
> > Hello guys Can Anyone help to find how to stop Miscellaneous Channel in in notification setting Becouse this channel is showing me Twise Pop-up when I Send Pop-up in app when my app is in quit state . I am using React-natiuve-push-notification And Sending Notification via Firebase
> 
> i have same issue, did you find the solution share please

same trouble, did you found a solution?
