### ISSUE TITLE
How to use this with Firebase and azure notification hubs

### ISSUE THREAD

**Issue by manjeet-dobble** [zo0r/react-native-push-notification#232]
Can I use this plugin with Firebase and azure notification, is anyone done that in past?

**Comment by jeveloper** [comment]
works fine with azure notifications
you need FCM for firebase, this is for google messaging

**Comment by manjeet-dobble** [comment]
It is working fine with firebase and azure, no need to do addition setup

**Comment by zarmeen92** [comment]
@manjeet-dobble  can you show some sample steps of using Azure push notification , where to register Azure notification hub string and tagname e.t.c?

**Comment by Kabijoy** [comment]
@manjeet-dobble can you show some sample steps of using Azure push notification , where to register Azure notification connection string and tagname e.t.c?

**Comment by jeveloper** [comment]
@Kabijoy  i suggest you follow Azure documentation, its a bit cumbersome but they do cover all the steps.

**Comment by Kabijoy** [comment]
@jeveloper thank you for your suggeestion.. I set up all from api side.. I need to know how we connect in ios side..

**Comment by keung7251** [comment]
@manjeet-dobble can you show some sample steps of using Azure push notification , where to register Azure notification connection string and tagname e.t.c?

**Comment by sarahmarciano** [comment]
@manjeet-dobble I am also interested to use this package with Azure. Did you reached any conclusion that you can share here?

**Comment by sarahmarciano** [comment]
@jeveloper did you test that?
if someone can help me with that I will be grateful
