### ISSUE TITLE
PushNotification.abandonPermissions() not working properly

### ISSUE THREAD

**Issue by samudini** [zo0r/react-native-push-notification#2320]
# Bug

I am using "react-native-push-notification": "^7.3.1"
I need to block push notifications when logout.
I have used 
PushNotification.abandonPermissions();

But the problem is when I log in again it returns the same token
onRegister: async (token) => {
}
Because of that, I didn't receive any firebase push notifications
Device used -  Samsung j7 (Android  8.1.0 

## Environment info

"react-native-push-notification": "^7.3.1"

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by JoseVov** [comment]
I'm also calling the `abandonPermissions` method and I'm unsure about what should happen. The `authorizationStatus` value is returned as `0 (not determined` when the `checkPermissions` function is called. I was expecting that value as denied or something like that.
