### ISSUE TITLE
build failed  Manifest merger failed 

### ISSUE THREAD

**Issue by piincher** [zo0r/react-native-push-notification#2321]
I just intalled react native push notification follow all the recommandations to setup it .
when i do npm run android  build failed .

 Manifest merger failed : android:exported needs to be explicitly specified for element <receiver#com.dieam.reactnativepushnotification.modules .RNPushNotificationBootEventReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

    "react": "18.1.0",
   
    "react-native": "0.70.2",
 
    "react-native-push-notification": "^8.1.1",

**Comment by alexandrecoulay** [comment]
#https://github.com/zo0r/react-native-push-notification/issues/2220

**Comment by alexandrecoulay** [comment]
You can use this configuration if you prefere :
Don't forget add the `<color name="white">#000000</color>` in `values/colors.xml` or any other color as you want.

` 
<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/ic_launcher_round" />
        <meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground" android:value="false"/>
        <meta-data android:name="com.dieam.reactnativepushnotification.notification_color" android:resource="@color/white"/>

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver" android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>

        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService" android:exported="false" >
          <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
        </service>`

**Comment by Anuskhan** [comment]
<receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver"  android:enabled="true"
    android:exported="false" >
