### ISSUE TITLE
On Click Action button not working in react native push notification.

### ISSUE THREAD

**Issue by ashishmangukiya** [zo0r/react-native-push-notification#2337]
# Bug

When app is running in background(not killed) and if i receive any push notification and if i try to click on any action button (Yes, No) then I do come back to app through .invokeApp() but if the app is not running in background(killed) then Nothing happens on click action buttons.

Library version: react-native-push-notification : 8.1.1

Describe what you expected to happen:

1. when I click on any action button then it should redirect me to respected navigation page or home page.

**Comment by ashishmangukiya** [comment]
Because on below code, getting failed when click on action buttons (killed app).
   
mReactInstanceManager.addReactInstanceEventListener(new ReactInstanceManager.ReactInstanceEventListener() {
                        public void onReactContextInitialized(ReactContext context) {
                            handleRemotePushNotification((ReactApplicationContext) context, bundle);
                            mReactInstanceManager.removeReactInstanceEventListener(this);
                        }
                    });

**'com.facebook.react.ReactInstanceManager.ReactInstanceEventListener' is deprecated**

**Comment by bakirnewfire** [comment]
The same problem is in our production app. Nothing happens when the app is killed and you press on a notification. Ios works just fine

**Comment by aotaduy** [comment]
Got same error, but I'm not using action buttons, it happened after updating targetSdkVersion to 31

**Comment by hetansh-Tatvasoft** [comment]
@aotaduy I also got same error yesterday, but I've updated _targetSdkVersion to 31_ few releases back
not sure what sure what triggered it this time...☹️
