### ISSUE TITLE
Updating AppIconBadgeCount when app is not active (#android)

### ISSUE THREAD

**Issue by manjeet-dobble** [zo0r/react-native-push-notification#234]
Is there a way to update applicationBadgeIconCount when app is not active (neither in foreground nor in background)

**Comment by npomfret** [comment]
With iOS you can send a push notification and set the application badge number in there.

With Android, you will be able to once the current master is released.  It make it possible to run code when a push notification is received even if your app isn't running.

**Comment by manjeet-dobble** [comment]
Thanks will be waiting for that nice update

**Comment by klinkov** [comment]
Any progress?

**Comment by npomfret** [comment]
I believe this is supported, on both iOS and Android.  Can we close?

**Comment by klinkov** [comment]
Can you post gist with code example, pls?

**Comment by npomfret** [comment]
Just follow the docs... `PushNotification.setApplicationIconBadgeNumber`

**Comment by klinkov** [comment]
Work with iOS, not in Android

```
    "react": "15.4.1",
    "react-native": "0.38.0",
    "react-native-push-notification": "2.2.1",
```

Test code

```
function resetBadge() {
    AsyncStorage.setItem('pendingNotifications', JSON.stringify([]));
    PushNotification.setApplicationIconBadgeNumber(10);
    console.log('BADGE RESET');
}
```

**Comment by npomfret** [comment]
Do you see an exception in logcat?  It doesn't work on all android devices.

**Comment by klinkov** [comment]
Android 4.4.2 - dont work
There is no exception in logicat

**Comment by klinkov** [comment]
Android 6.0.0 emulator - dont work
iOS 10 emulator - work

**Comment by npomfret** [comment]
It's likely that it won't work at all on an emulator (though I'm not 100% sure on that).  Try it on a physical device.

Also, make sure you're not filtering out the exception in logcat by accident.

**Comment by klinkov** [comment]
Did't work on stock Android or MIUI.

**Comment by manjeet-dobble** [comment]
working fine

**Comment by klinkov** [comment]
@manjeet-dobble can you provide code example and your react, react-native, react-native-push-notification version and Android device + version info, pls?

**Comment by manjeet-dobble** [comment]
@klinkov actually my code is almost same as yours, but I am unable to update its count dynamically

**Comment by klinkov** [comment]
What about other, android, device and packages versions?

**Comment by JonoH** [comment]
Cannot get this working on any android device. RN 0.39, plugin version 2.2.1

**Comment by JonoH** [comment]
Ok can get it working but only while the app is in the foreground. Number doesn't change when app is in the background or closed.

**Comment by robertherber** [comment]
Also looking for a solution to this. On iOS [a scheduled notification without message](http://stackoverflow.com/questions/8734078/ios-badge-number-live-update) is the way to do it, but I get an error when sending null as message here. No idea how it's usually done on Android.

I would actually prefer a separate method for it - how about introducing a scheduleApplicationIconBadgeNumberUpdate that takes a time and number?
