### ISSUE TITLE
Problem with IOS token

### ISSUE THREAD

**Issue by agrass** [zo0r/react-native-push-notification#235]
Hi, I'm perfect with Android, but with IOS I don't know why when I try to send a notification using the token generated,  it says `invalid token` in Firebase Cloud Messaging. What could be wrong?

I'm working with RN 0.26.2 and RNPN 1.0.7

Thanks!

**Comment by damathryx** [comment]
@agrass  I got the same problem? how did you solved this?

**Comment by mohamed-alashry** [comment]
did you found any solution?

**Comment by agrass** [comment]
Hi @mohamed-alashry @damathryx! sorry for the delay in the response. Now I'm using react-native-fcm

**Comment by theohdv** [comment]
The token fetch by react-native-push-notification is not good if you are using Firebase Cloud Messaging. Take a look here: https://stackoverflow.com/a/44000335

**Comment by damathryx** [comment]
@theohdv I am experiencing this problem. How can I solve this? I have no knowledge in objective C.

**Comment by theohdv** [comment]
To get the FCM token you can use this library [react-native-firebase](https://github.com/invertase/react-native-firebase). There is a `getToken()` method which fetch FCM token.

**Comment by damathryx** [comment]
@theohdv  thanks, i just went with agrass solution use react-native-fcm and im getting the correct token now.

**Comment by Aleksefo** [comment]
Was struggling with this for weeks, recreating projects and certificates trying to fix the issue. Turns out it's just the library is broken since 2016.

**Comment by opolyo01** [comment]
react-native-firebase needs newer RN version, so probably need apn for ios and firebase tokens for android.  I am ending up using two separate libraries on server side.

**Comment by iamisathya** [comment]
Same issue

**Comment by Dallas62** [comment]
Hi,
This is the expected behaviour since Firebase is not the official notification provider for iOS, Firebase for android.
The token is the APN one, you will need rnfirebase to get the Firebase token for iOS.
