### ISSUE TITLE
JSON value '12' of type NSString cannot be converted to NSNumber

### ISSUE THREAD

**Issue by rajatgupta1993** [zo0r/react-native-push-notification#236]
I am facing this error in iOS, I have completed the whole setup and on running the code on iPhone device I am getting this error .

**Comment by npomfret** [comment]
I don't think this has anything to do with this repository

**Comment by wookiem** [comment]
@rajatgupta1993 Were you able to resolve this?  I'm seeing the same issue.

**Comment by plonkus** [comment]
I get this error too in iOS when I pass a local notification with the "number" (android only) field.

However, I may be doing something wrong because I'm also not seeing the number attribute get passed back on Android :)

**Comment by wookiem** [comment]
The documentation for `Set application badge number` for IOS is incorrect.

It currently says:
`PushNotification.setApplicationIconBadgeNumber(number: number)`

It should say:
`PushNotification.setApplicationIconBadgeNumber(number)`
