### ISSUE TITLE
Scheduled notification set for tomorrow is not coming

### ISSUE THREAD

**Issue by lutfullo777** [zo0r/react-native-push-notification#2362]
# Question

  This is my code:
     **PushNotification**.localNotificationSchedule({
            channelId: 'channelId,
            message: "Notificataion is come",
            largeIcon: 'ic_launcher_foreground',
            smallIcon: 'ic_small_icon',
            title: "Notification",
            date: new Date(Date.now() + 24x3600x1000),
            allowWhileIdle: true,
          });

but working for today

 I don't use repeatType: "day".

**Comment by Shivampurbia** [comment]
PushNotification.localNotificationSchedule({
            channelId: 'hello',
            message: "Medicine alarm!!", // (required)
            date: new Date(Date.now() + reminderTime),
            allowWhileIdle: true, // (optional) set notification to work while on doze, default: false
            repeatType: 'day',
    
        });

you would need to add  repeatType: 'day', otherwise it won't work.
i have tested this by changing the date to tommorow it will send you the notification on the exact time.
