### ISSUE TITLE
No callback is fired after requestPermissions

### ISSUE THREAD

**Issue by ck86** [zo0r/react-native-push-notification#237]
I am running the following code in `componentDidMount()` of my main component:

``` js
PushNotification.configure({
    onError: console.log.bind(console, 'onError:'),
    onRegister: console.log.bind(console, 'onRegister:'),
    onNotification: console.log.bind(console, 'onNotification:'),
    senderID: '...',
    permissions: {
        alert: true,
        badge: true,
        sound: true
    },
    popInitialNotification: false,
    requestPermissions: true
});
```

And nothing happened.

Here is my AndroidManifest.xml:

``` XML
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.example"
          android:versionCode="1"
          android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <permission
            android:name="${applicationId}.permission.C2D_MESSAGE"
            android:protectionLevel="signature"/>
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <uses-sdk
            android:minSdkVersion="16"
            android:targetSdkVersion="23"/>

    <application
            android:name=".MainApplication"
            android:allowBackup="true"
            android:label="@string/app_name"
            android:icon="@mipmap/ic_launcher"
            android:theme="@style/AppTheme">
        <activity
                android:name=".MainActivity"
                android:label="@string/app_name"
                android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity"/>
        <receiver
                android:name="com.google.android.gms.gcm.GcmReceiver"
                android:exported="true"
                android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                <category android:name="${applicationId}"/>
            </intent-filter>
        </receiver>

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher"/>
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
        <service
                android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
                android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
            </intent-filter>
        </service>
    </application>

</manifest>
```

I also logged all functions in node_modules/react-native-push-notification/index.js:

```
Notifications.configure [Object]
index.js:32 Notifications.callNative ["addEventListener", Array[2]]
index.js:32 Notifications.callNative ["addEventListener", Array[2]]
index.js:32 Notifications.callNative ["addEventListener", Array[2]]
index.js:32 Notifications.callNative ["addEventListener", Array[2]]
index.js:241 Notifications._requestPermissions []
index.js:32 Notifications.callNative ["requestPermissions", Array[1]]
```

And I tried to log some actions in `node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java` and "figured" out that in `registerNotificationsRegistration()` the `onReceive` method of the `BoardcastReceiver()` is never called.

Did I missed something?

**Comment by knapeto** [comment]
I have same problem. Did you solved it?

**Comment by ck86** [comment]
Nope :/ 
Anybody?

**Comment by varungupta85** [comment]
Are you running this on device or simulator? Do you have the necessary setup required to be able to invoke the `onRegister` mainly a valid GCM_SENDER_ID in case of Android. I am not sure what is required for iOS because I don't use this package for iOS.

**Comment by ck86** [comment]
@varungupta85 yes I'm running this on a nexus 5 and yes I'm pretty sure that I'm using a valid sender id because the same project is working. it's jsut on my dev environment.

**Comment by varungupta85** [comment]
@ck86 Do you mean to say that the same project is working in prod environment and not working in dev environment? Please clarify what you meant by same project is working?

**Comment by ck86** [comment]
@varungupta85 I meant my dev environment with my MacBook. The same project on another MacBook is working. So I guess that something is missing OS-related or SDK-related.

**Comment by pauwlsky** [comment]
Also having the same issue on Android. Cannot get permissions notifications to fire at all actually.

**Comment by gabriel** [comment]
Unless I'm missing something, I don't even see onError being registered as an event listener

**Comment by ck86** [comment]
@gabriel what do you mean?

```js
PushNotification.configure({
    onError: console.log.bind(console, 'onError:'), // <---
    ...
});
```

**Comment by gabriel** [comment]
There is no `addEventListener('registrationError'` for iOS.

**Comment by pauwlsky** [comment]
Also having the same issue for requesting permissions on Android, and somewhat confused about the need to request permissions if we've already written them into AndroidManifest.xml, since notifications aren't dangerous permissions is it even required to prompt the user for permissions? 

http://stackoverflow.com/questions/37294076/push-notifications-gcm-permission-at-runtime

**Comment by ck86** [comment]
@varungupta85 no ideas what could be possibly missing?

**Comment by cinder92** [comment]
same issue here in react-native 0.36.1 and v 2.0.2 of this plugin :s

**Comment by varungupta85** [comment]
@ck86 Like you mentioned, the problem is with your dev setup and I wouldn't know what may be missing. But I think if you run the app on your device using Android Studio in debug mode and put some breakpoints in the code where the 'register' event is fired in the Java code, you may get some hints. As far as setup is concerned, make sure that you have the google play-services-gcm library installed. Android Studio should tell you if it is not installed. The library is specified in the android/app/build.gradle file.

**Comment by ck86** [comment]
OK I don't know why they told me to use the API Key for the senderID, but the solution was to use the project number of the GC-project. May be you could add a hint in your to your [documentation](https://github.com/zo0r/react-native-push-notification#usage). :)
