### ISSUE TITLE
Pushnotification listener not working while using multiple services ( OneSignal and react-native-push-notification)

### ISSUE THREAD

**Issue by arun-rajs** [zo0r/react-native-push-notification#2379]
Hello There,

In one of our RN project , we are using OneSignal as the push-notification sevice for app related feature.
In the other hand we have chat implementation which is based on a third party package called 'QuickBlox' (https://docs.quickblox.com/docs/react-native-push-notifications) and they need 'react-native-push-notification' to implement push-notification for offline messages. 
the issue is : When adding 'react-native-push-notification', we are not getting the listener even from firebase console.

Question: Is there any issue if we try multiple push-notification listeners in one single app ?

We have the firebase google json in place.

"react-native": "0.71.4",
"react-native-push-notification": "^8.1.1",
"quickblox-react-native-sdk": "^0.9.4"

Thanks in advance

**Comment by shivapasunuri** [comment]
Hey Arjun have you ever faced these push notifications not working for some devices and not for some devices? after building the apk and actually testing on the physical devices?
