### ISSUE TITLE
notification() is not triggered when we clear the instance and app in background

### ISSUE THREAD

**Issue by swaroopa94** [zo0r/react-native-push-notification#238]
Hi
I am using  your module here when i receive a notification i am just showing a simple alert.
And its Working fine in foreground and in background also it is showing the alert.

But when i clear the instance and app is in background then when i send a notification,and click on the received notification then my app is opening but its not showing the alert.

Can You help me to solve this.

**Comment by sagark1510** [comment]
Which version you are using??

**Comment by swaroopa94** [comment]
"react-native-push-notification": "^1.0.7",
 "react-native": "^0.25.1",
