### ISSUE TITLE
Foreground onNotification behaviour on iOS

### ISSUE THREAD

**Issue by abdymm** [zo0r/react-native-push-notification#2389]
# Question

Hi guys, just want to know the correct behavior when the app is in **FOREGROUND**, on the `onNotification` currently on **Android** the `onNotification` will be triggered when a notification is received and the user taps it, but on **iOS** its triggered only when the user taps the notification, is this expected behaviour?

**Comment by trevor-mobileup** [comment]
We are also experiencing this issue. I understand it's unlikely to see this get fixed/looked into at this point, but I am commenting and getting this activity in the hopes that someone on the library has found a workaround. Migrating is a big ask for our legacy app, and we're hoping for a band-aid solution until then.

**Comment by trevor-mobileup** [comment]
@abdymm Through other issues we found the following two lines that we added to our AppDelegate.mm:

`NSDictionary *userInfo = notification.request.content.userInfo;
  [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo];`
  
  We added these to willPresentNotification like so: 
  
![image](https://github.com/zo0r/react-native-push-notification/assets/75629192/195095a3-1837-4af7-9e0f-5efaba9f2c6c)


Though our issue now is that the userInteraction property doesn't seem to be set properly on the notification object in the onNotification callback. Separate issue though, hope the above helps
