### ISSUE TITLE
Notifications firing in background on IOS emulator, but not on real IOS device

### ISSUE THREAD

**Issue by em222iv** [zo0r/react-native-push-notification#245]
There seems to be some other issues touching on the issue but none with an answer that works for me. 

On an IOS emulator the push notifications are working with the app running in the background, however, when on an actual device the events does not trigger until you open the app again.

**Comment by GramosBegolli** [comment]
+1

**Comment by amohit1315** [comment]
any solutions yet???

**Comment by Dallas62** [comment]
Hi;
This issue is not related to this repository.
Feel free to open an issue if it's still needed on @react-native-community/push-notification-ios.
