### ISSUE TITLE
Android- schedule local notification, foreground is always false

### ISSUE THREAD

**Issue by sumesh1993** [zo0r/react-native-push-notification#246]
In android when app is in foreground, still notification banner appears and onNotification is not called.

but in iOS
when app is in foreground, onNotification event is fired.

How can we replicate the iOS behaviour in android??

**Comment by simonayzman** [comment]
I'm having the same issue.

**Comment by npomfret** [comment]
It's a regression I think, see https://github.com/zo0r/react-native-push-notification/issues/267
