### ISSUE TITLE
Android empty bottom right square

### ISSUE THREAD

**Issue by robmoorman** [zo0r/react-native-push-notification#249]
On Android (tested on 4.x, 5.x and 6.x emulator as well as real device) I see an empty gray square in all received notifications (remote or local). It seems like an empty badge or something, however none of these settings are used.

![screen shot 2016-10-24 at 13 51 12](https://cloud.githubusercontent.com/assets/529396/19644609/faefcc6c-99f0-11e6-9b78-813fc3786370.png)

By default the _ic_launcher.png_ is used, this icon seems to be fine.

**Versions:**
"react": "15.3.2"
"react-native": "0.35.0"
"react-native-push-notification": "2.1.1"

**Configuration:**

``` javascript
PushNotification.configure({
  onRegister: (token) => {
    dispatch(actions.device.sendDeviceToken(token))
  },
  onNotification: (notification) => {
    console.log(notification)
  },
  senderID: Config.googleSenderId,
  permissions: {
    alert: true,
    badge: true,
    sound: true,
  },
  popInitialNotification: true,
  requestPermissions: false,
})
```

**Log statement of received notification:**

```
{
  foreground: false,
  userInteraction: true,
  id: "143778939",
  message: "Test local push notification"
}
```

**Comment by semiautomatix** [comment]
Actually, I'm also getting this, thought it was a problem with my image. Maybe not?

**Comment by jdmunro** [comment]
I am also experiencing this.

**Comment by Cynigo** [comment]
Me too.

**Comment by simPod** [comment]
https://github.com/zo0r/react-native-push-notification/issues/99

**Comment by ArcadeRenegade** [comment]
Thank you @jawinn
