### ISSUE TITLE
ios notification permission popup rejection event

### ISSUE THREAD

**Issue by abeikverdi** [zo0r/react-native-push-notification#250]
How do I know if the user rejected the notification permission that pops up automatically in ios?

**Comment by benthewhite** [comment]
We've been sorting out exactly this problem. `PushNotification.requestPermissions()` returns a promise so you can use this to see what the returns result is. It resolves to an object of enabled bits including `alert` so if that is 1 then the user picked allow, if it is 0 then the user effectively picked deny. For our code we use something like this...

```js
PushNotification.requestPermissions().then(res => {
  if (!res.alert) {
    // They picked deny :(
  } else {
   // They picked allow :D
  }
});
```

**Comment by amelzer** [comment]
@benthewhite How did you avoid the `cannot call requestPermissions twice before the first has returned` issue?

**Comment by benthewhite** [comment]
I just cached the promise whilst its running and return that or create a new request if not.

```js

var requestPromise = null;

function requestPerms() {
  if (requestPromise) return requestPromise;

  requestPromise = PushNotification.requestPermissions().then(res => {
    requestPromise = null;
    return res;
  }, err => {
    requestPromise = null;
  });
  
  return requestPromise;
}


// Doing the actual request
requestPerms().then(res => {
  if (!res.alert) {
    // They picked deny :(
  } else {
   // They picked allow :D
  }
});


```

**Comment by amelzer** [comment]
@benthewhite 
Shame, doesn't work for me. I cannot call `requestPermissions()` at all without running into this error.
What does your configuration object look like?

**Comment by eujern** [comment]
I'm running into the same issue with that error.

**Comment by Twinski** [comment]
You should set "requestPermissions" to FALSE in your config. It's set on TRUE by default. So if you do PushNotification.configure({ .. }); & PushNotification.requestPermissions(); it will try to fire it twice hence the error.

**Comment by ckim16** [comment]
I set requestPermissions to `false` but I still get that error every time I refresh my app.

```
class PushConfig extends Component {
  componentDidMount() {
    PushNotification.configure({
      // (optional) Called when Token is generated (iOS and Android)
      onRegister: (token) => {
        this.props.registerDevice(this.props.username, token);
      },

      // (required) Called when a remote or local notification is opened or received
      onNotification: (notification) => {
        console.log('notification', notification);
      },

      requestPermissions: false
    });
  }

  render() {
    return null;
  }
}

function mapDispatchToProps(dispatch) {
  return bindActionCreators({ registerDevice }, dispatch);
}

export default connect(null, mapDispatchToProps)(PushConfig);

```
and I ask for a permissions when authenticated in my singin component like
```
componentWillUpdate(nextProps) {
    if (nextProps.authenticated) {
      PushNotification.requestPermissions();
      Actions.next();
    }
  }
```
and `PushConfig` is mounted in the next component after authentication.

Any thoughts?

**Comment by tywoodpav** [comment]
@ckim16 Was this ever resolved?

**Comment by ckim16** [comment]
@tywoodpav Unfortunately, No. I just dismiss the error and manually reload myself currently.

**Comment by ThinkSalat** [comment]
@benjackwhite How do you call .then on sometihng that returns null without getting an error like "Cannot read property 'then' of null"
