### ISSUE TITLE
custom sounds in iOS 10

### ISSUE THREAD

**Issue by npomfret** [zo0r/react-native-push-notification#254]
Has anyone managed to get custom sounds working in iOS 10?  I remember them working fine in 9, but I only get the default notification sound now.  I've tested my sound file using react-native-audioplayer and it seem fine.

**Comment by benthewhite** [comment]
Same problem here. Seemed to work okay before but has just stopped playing custom sounds since iOS 10.

**Comment by codyhazelwood** [comment]
I had it working for 1 build but rebuilt the app and it's gone again.  Custom sounds are working fine in Android.  This is actually a show stopper for releasing my updated app, so I'm trying to dig into it.

**Comment by codyhazelwood** [comment]
It's a bug in iOS.  Completely removing the app and reinstalling it fixes it.  Apparently restarting the device fixes it, too, but I haven't tried that.

[Helpful StackOverflow Question](http://stackoverflow.com/questions/39400703/ios10-custom-push-notification-sound-not-playing)

**Comment by benthewhite** [comment]
Nice find. I just tried exactly that and it works... unlike iOS 10 ;)

**Comment by npomfret** [comment]
Mine came back after rebooting the device.  I think it's a bug in iOS 10
