### ISSUE TITLE
Press on notif not fire onNotification

### ISSUE THREAD

**Issue by justineraze** [zo0r/react-native-push-notification#256]
Hello, 
I never go in OnNotification when I press my notice. Similarly I never get the notifs when my application is closed any idea why?

Thank you for your help

**Comment by npomfret** [comment]
It's a regression I think, see https://github.com/zo0r/react-native-push-notification/issues/267

**Comment by nonameolsson** [comment]
Any progress on this @justineraze ? I have still the same problem, check my comment in #170
