### ISSUE TITLE
Notification banner/icon doesn't show

### ISSUE THREAD

**Issue by woniesong92** [zo0r/react-native-push-notification#257]
I checked that the notifications are coming to the device, but it's not showing the notifications in the system tray or in the banner (Android 6.0).

```
    onNotification: function(notification) {
      console.log( 'NOTIFICATION:', notification )
    },
```

Do you have any idea?

**Comment by jenshandersson** [comment]
Same problem here. It was working fine earlier, must have been caused by updating react-native-push-notification or gcm version. Backend is same as before.

**Comment by booboothefool** [comment]
Same problem here.

**Comment by GeoffreyPlitt** [comment]
Is my #331 the same?

**Comment by jenshandersson** [comment]
@GeoffreyPlitt I think it is. I downgraded react-native-push-notification to 2.1.0 and that seems to have worked for me. Try that maybe?

**Comment by GeoffreyPlitt** [comment]
Downgraded to 2.1.0, no change.

Does anyone have a minimal app that uses this lib that works?

**Comment by swaroopa94** [comment]
Hi @GeoffreyPlitt 
I am having the same problem did you solve?

**Comment by GeoffreyPlitt** [comment]
No, we switched to OneSignal

**Comment by agrawalsurabhi89** [comment]
Any updates on this, i m using 3.0.1 version of this library but i m not seeing notification in the system tray but onNotification() is getting called. Any idea?
