### ISSUE TITLE
Feature Request: Repeating iOS notifications

### ISSUE THREAD

**Issue by Looveh** [zo0r/react-native-push-notification#258]
A PR with this feature in React Native has now been merged into [master](https://github.com/facebook/react-native/pull/10337) so it's very likely that `PushNotificationIOS` will support repeating notifications starting with `v0.37.0`. 

Since this is (arguably) a key feature we should start preparing for it to be ready when `v0.37.0` of RN is released.

**Comment by vikeri** [comment]
Can confirm that this is now merged into 0.37: https://github.com/facebook/react-native/releases/tag/v0.37.0

**Comment by hdchan** [comment]
has this library been updated to utilize the feature on iOS?

**Comment by susahosh** [comment]
I have the same question. The comment from @vikeri confirming merge seems to be almost a year old, yet this ticket is still open. Also the documentation in the home page say iOS will be supported soon. Thus, leading to confusion on the iOS support.

**Comment by lucask42** [comment]
+1 are repeated notifications supported on iOS now?

**Comment by RustamIbragimov** [comment]
Is it supported now?

**Comment by sourcesoft** [comment]
I tested and it's working in iOS.

**Comment by jeveloper** [comment]
@zo0r Jorge , please merge this , its all good

**Comment by NickDelfino** [comment]
Does this now work? If so, are there any docs explaining usage? Thanks!

**Comment by jeveloper** [comment]
hey @NickDelfino  
Android doesn't support 'monthly' repeat type 

Use these properties:

 repeatType: 'day', 
repeatTime: 

// (Android only) Repeating interval. Could be one of `week`, `day`, `hour`, `minute, `time`. If specified as time, it should be accompanied by one more parameter 'repeatTime` which should the number of milliseconds between each interval

**Comment by NickDelfino** [comment]
@jeveloper Thanks for the reply! Is this still only on Android for the time being? I see that there has been lots of movement about the iOS feature. Seems like it works but is not pushed to the main branch for consumer use. Thanks again!

**Comment by jeveloper** [comment]
hey @NickDelfino  It definitely works well on ios (including month) 
Here is a snippet of mine:

date: moment().seconds(0).minute(0).hour(20).toDate(),
      repeatType: 'day' 

just an example of scheduling a local notification

**Comment by joaom182** [comment]
❤️

**Comment by abarisic86** [comment]
There is a PR that enables requested feature: https://github.com/zo0r/react-native-push-notification/pull/381
Please go there and add 👍 so that it draws a bit of attention.
