### ISSUE TITLE
Better documentation for cancelLocalNotifications() on Android

### ISSUE THREAD

**Issue by danleveille** [zo0r/react-native-push-notification#259]
The documentation states that `userInfo` is iOS only, however, it states that you can use a `userInfo` dictionary as an argument for `cancelLocalNotifications()`.

Could someone whose more familiar with this library update the documentation to clarify:

- What does the argument for `cancelLocalNotifications` actually do (if anything) on Android?
- How do you cancel individual scheduled local notifications on Android? (What parameters can you use to match notifications?)

**Comment by kenma9123** [comment]
Anyone can shed some light?

**Comment by sticknor** [comment]
Hi, 
I was able to finally find success with this cancelLocalNotifications method. 


The README leads us to believe that the following will work for android:
PushNotification.localNotificationSchedule({ userInfo: { id: '123'} });
PushNotification.cancelLocalNotifications({ id: '123' });

But it does not....

Instead, do this:
PushNotification.localNotificationSchedule({ id: '123' });
PushNotification.cancelLocalNotifications({ id: '123' });

**Comment by kenma9123** [comment]
I tried this `PushNotification.cancelLocalNotifications({ id: '123' });` but nothin works. Still can't remove a specific notification. So I end up doing the PR #336

**Comment by j-nolan** [comment]
@sticknor 's solution did the trick for me (Android). Thanks!

I'd like to add that the key we pass through the `details` object **must** be called `id`:

```
// Does NOT work
PushNotification.localNotificationSchedule({ key: '123' }); // key, or anything else than id
PushNotification.cancelLocalNotifications({ key: '123' });

// Works
PushNotification.localNotificationSchedule({ id: '123' }); // id
PushNotification.cancelLocalNotifications({ id: '123' });
```

I think the documentation for this method should avoid the keyword `userInfo` because it suggests the matching will be performed using the `userInfo.id` property of existing notifications. Moreover, users can be mislead into believing any key can be used for matching. In reality only the `id` property can be used for matching.

If that makes sense I'd be happy to open a PR to change it. @npomfret

**Comment by npomfret** [comment]
Yeah, lost of people find the readme a bit confusing - if you think you can improve please do

**Comment by KatSick** [comment]
Confirm it working. But only with string type of property ID

**Comment by GantMan** [comment]
Given I was in a situation where there were no give unique ids, and I didn't understand the 2 ways of cancelling for iOS and Android, I hope this helps others looking at this like:

https://github.com/zo0r/react-native-push-notification/pull/336 and https://github.com/zo0r/react-native-push-notification/pull/371

Add/remove local notifications:
![image](https://user-images.githubusercontent.com/997157/27008098-c0eab50c-4e2e-11e7-9c7e-1b73663c1496.png)

And that helper I'm using is here:

![image](https://user-images.githubusercontent.com/997157/27008116-e6ec5382-4e2e-11e7-8d8a-e9652570da5a.png)
