### ISSUE TITLE
Missing addEventListener for 'registrationError' on iOS

### ISSUE THREAD

**Issue by gabriel** [zo0r/react-native-push-notification#261]
There is a registrationError event type: https://facebook.github.io/react-native/docs/pushnotificationios.html#addeventlistener

Missing from:
https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L83

**Comment by gabriel** [comment]
To temporarily workaround this you can do:

```js
PushNotification.callNative('addEventListener', ['registrationError', (err) => {
  this.props.onPushError(err)
}])
```

**Comment by iMaciah** [comment]
Did you find a fix for this?
