### ISSUE TITLE
Build Fail - support-annotations:24.0.0

### ISSUE THREAD

**Issue by sloanwolf** [zo0r/react-native-push-notification#265]
RN: 0.36
RNPN: 2.2.0 / git master (tried both, think they are the same anyways)
Android: 23.0.1

```
-> react-native run-android
> A problem occurred configuring project ':react-native-push-notification'.
   > Could not find support-annotations.jar (com.android.support:support-annotations:24.0.0).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/support-annotations/24.0.0/support-annotations-24.0.0.jar
```

```
-> ./gradlew installDebug --debug
[DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.CachingModuleComponentRepository] Detected non-existence of artifact 'support-annotations.jar (com.android.support:support-annotations:24.0.0)' in resolver cache
```

Tried a ton of things but nothing is working. Android Support Library says obsolete now but can't really find any info on if that's a problem or where the annotations.jar moved to or what. The jar exists on my system, the stackoverflow answers I've seen suggest copying the file but some stuff doesn't really match up. So wondering if anybody else has run into this exact issue?

Seems to always try and use 24.0.0 but can't find where it's requiring that as a dependency and still doesn't work if I use 24.0.0 SDK.

I should also note that if I comment out all the react-native-push-notification lines it builds fine.

Cheers.

**Comment by sloanwolf** [comment]
Finally got it to build by updating this libs build.gradle to:

```
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.facebook.react:react-native:+'
    compile 'com.google.android.gms:play-services-gcm:+'
    compile 'me.leolin:ShortcutBadger:1.1.8@aar'
}
```

**Comment by varungupta85** [comment]
You should probably keep the `targetSdkVersion` to 22. I am not sure if changing the `targetSdkVersion` to higher than 22 within this module would affect the `targetSdkVersion` of the whole project but if it is set for the whole project, then you have some problems with the permissions. Especially you may begin to see the `Draw over other apps` dialog box. You can get some more info here https://github.com/facebook/react-native/pull/10479

**Comment by sloanwolf** [comment]
I have corrected that, thanks.

I still get a Fatal Exception when it tries to perform register code I think.

Using `com.android.support:appcompat-v7:24.2.1`
```
11-06 20:37:01.965 16163 16338 E AndroidRuntime: java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.google.android.gms.iid.zzd' appears
```

When I try `com.android.support:support-v4:23.4.0` it doesn't build with the original build error.

Can someone provide an example gradle config they are using successfully. I've done `react-native upgrade` when I moved to 0.36, I ran into issues using react-native-gcm so I've moved to this. Been at this for a week.

**Comment by npomfret** [comment]
Mine is working with

    compileSdkVersion 23

and

    compile "com.android.support:appcompat-v7:23.0.1"

and

    compile('com.google.android.gms:play-services-gcm:9.4.0') {
        force = true;
    }

**Comment by sloanwolf** [comment]
@npomfret @varungupta85 Thanks for the help.

I figured it was probably my Android environment, looks like I had to uninstall/reinstall SDK 23 due to it containing a bug. Everything works now.
