### ISSUE TITLE
Local Notifications not working on iOS

### ISSUE THREAD

**Issue by b8ne** [zo0r/react-native-push-notification#268]
Notifications are working fine on Android, but nothing is working on iOS.
I am getting a warning when notification should be firing "didReceiveNetworkIncrementalData with no listeners registered".
Note that although I have set up as per specs, I am using a Pusher library to handle external notifications.

**Comment by yogieputra8** [comment]
Are you using it with real device/ iPhone?

**Comment by b8ne** [comment]
Hey @yogieputra8  yep on a real phone.

**Comment by b8ne** [comment]
Does anyone actually have this working on iOS?
I found that this package is in fact working correctly, however it is react natives implementation that is failing to display the local notification.
Rather than using ```[RCTPushNotificationManager didReceiveLocalNotification:notification];``` ive implemented my own method to display local notifications and now its working.
Will close now but would be interested to know if anyone has an explanation.

**Comment by npomfret** [comment]
Its working fine for me on both iOS and android.  But a lot of people seem to be struggling with it.

**Comment by hdchan** [comment]
Can someone post sample code to demonstrate how to implement this library?
