### ISSUE TITLE
Doesn't receive push notification when app is inactive for Android

### ISSUE THREAD

**Issue by nidzovito** [zo0r/react-native-push-notification#272]
I don't get any push notification when app is inactive.
Any idea?

**Comment by benthewhite** [comment]
It's a regression in 2.2.0 See https://github.com/zo0r/react-native-push-notification/issues/267

**Comment by georgi-kovachev** [comment]
hi @benthewhite currently I am using 2.1.1, not 2.2.0.
Are you receiving 'remote notification' when is closed / inactive?
I haven't got anything in Android, but it shows in iOS though.

**Comment by TriangleIL** [comment]
On 2.1.1 I was receiving notifications on Android - however, what I wasn't able to do was seem them in the JS while the app was backgrounded in the ` onNotification: function(notification)` method.  It sounds like there is some bridge code to listen for these notifications and push them to the JS code in Android, but I haven't found an example of that yet.

**Comment by rcarvalho** [comment]
Just curious if you were able to find out how to call onNotification for Android. Mine is not being called. Also, when my app is backgrounded and I click on the notification it brings my app up in a weird state with the splash screen. This behavior is different than when I just click on the app after backgrounding. In that case, it starts up where I left off in the app.

**Comment by rizkisunaryo** [comment]
I got the same issue with 3.0.0
What is the problem?
Is there any fix?
