### ISSUE TITLE
How to use with firebase notifications

### ISSUE THREAD

**Issue by esganzerla** [zo0r/react-native-push-notification#274]
Hi, I tried looking everywhere but I could find how to make it work with firebase notifications.

Can anyone guide me how to do it?

Thanks a lot!

PS: I'm doing it for android.

**Comment by adeelibr** [comment]
Have a look at this library https://github.com/evollu/react-native-fcm

**Comment by jsdario** [comment]
I am using them already, FCM is backwards compatible with GCM.

**Comment by jsdario** [comment]
Update: I am unable to register FCM to use APN directly on iOS. I will post the solution as soon as I find one.

**Comment by MattyK14** [comment]
+1

**Comment by fredbt** [comment]
@jsdario any updates on using FCM to talk to talk to APN to use this library?

**Comment by jsdario** [comment]
No @fredbt, sorry. I continued using APN with this lbrary, or moved to `react-native-firebase` in iOS.

**Comment by fredbt** [comment]
@jsdario thanks for the answer. Would you prefer react-native-firebase over react-native-fcm?

Thanks!

**Comment by jsdario** [comment]
If you are not using more firebase services maybe [react-native-fcm](https://github.com/evollu/react-native-fcm). I was using many, so in order to avoid linking extra libraries it made sense choose [react-native-firebase](https://github.com/invertase/react-native-firebase) instead.
