### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by jqn** [zo0r/react-native-push-notification#279]
I just installed react-native-push-notification and I'm getting this error on RN 0.37

![simulator screen shot nov 10 2016 4 07 45 pm](https://cloud.githubusercontent.com/assets/9710893/20198058/d5171384-a75f-11e6-8f6f-54c831f7eb3b.png)

**Comment by cinder92** [comment]
you need to write "react-native link" and then restart your server

**Comment by rknell** [comment]
what worked for me was following the iOS Push Notifications setup guide on the react native website. There are some libraries you need to link in your xcode project before everything will be chipper

**Comment by jqn** [comment]
I ran react-native link in the command line but the error continued. I'll try reviewing the setup guide to see if I missed something.

**Comment by npomfret** [comment]
Check your java code has the necessary lines in it that load up this module

**Comment by klinkov** [comment]
![iphone 6 - iphone 6 ios 9 0 13a344 2016-11-19 23-47-27](https://cloud.githubusercontent.com/assets/211417/20458317/a288c502-aeb2-11e6-8670-684bcf0a9efc.png)
Got same issue only for iOS, android work well

**Comment by klinkov** [comment]
Ok, i solve it. Follow the white rabbit :)
[https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking](url)
For Android check https://github.com/zo0r/react-native-push-notification#android-manual-installation

**Comment by dereksweet** [comment]
Just for people coming here the facebook.github.io link above is broken, pointing to totally different place. Here is the same link but should work: [https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking)

**Comment by dguilak** [comment]
For me, `react-native-push-notification` wasn't automatically linked for iOS when I ran `react-native link`:

```
[money-app] react-native link                                                                                                          13:04:53  ☁  master ☂ ⚡ ✭
rnpm-install info Android module react-native-fbsdk is already linked
rnpm-install info iOS module react-native-fbsdk is already linked
rnpm-install info Linking react-native-push-notification android dependency
rnpm-install info Android module react-native-push-notification has been successfully linked
rnpm-install info Android module react-native-svg is already linked
rnpm-install info iOS module react-native-svg is already linked
```

For some reason, it only linked Android. 

But following the instructions that @dereksweet provided seemed to resolve the issue.

**Comment by faxioman** [comment]
Not linked for me too

**Comment by EdmundMai** [comment]
same here

**Comment by kevando** [comment]
Yeah `react-native link` didn't work for me either. [I followed these instructions and](https://facebook.github.io/react-native/docs/pushnotificationios.html)

```
    Add the following to your Project: node_modules/react-native/Libraries/PushNotificationIOS/RCTPushNotification.xcodeproj
    Add the following to Link Binary With Libraries: libRCTPushNotification.a
    Add the following to your Header Search Paths: $(SRCROOT)/../node_modules/react-native/Libraries/PushNotificationIOS and set the search to recursive
```

**Comment by iiitmahesh** [comment]
Same Issue Here ...! Any update or workaround for this??

**Comment by ward-dotdev** [comment]
Manual linking didn't fix it for me on RR 0.44. In fresh project with RR 0.46 no problem though

**Comment by markymc** [comment]
In case it helps any one - For me calling `react-native unlink react-native-push-notification` followed by `react-native link` worked.

**Comment by hdchan** [comment]
I'm getting this error as well, despite properly following the linking instructions. Any working solutions?

**Comment by jacklj** [comment]
Manual linking worked for me - you have to follow the instructions [here](https://facebook.github.io/react-native/docs/pushnotificationios.html#content)

**Comment by gamsim** [comment]
I had to manually link using Xcode.

react-native link cmd didn't work. As per all other comments follow https://facebook.github.io/react-native/docs/pushnotificationios.html#content

**Comment by LennardSennep** [comment]
I have linked it manually for 8 times today already and it is still not working... Any help would be appreciated.

**Comment by 8of** [comment]
For those CocoaPods users the [link](https://github.com/zo0r/react-native-push-notification/issues/160#issuecomment-383601653) might be useful.
At least I hope it is.
