### ISSUE TITLE
requestPermissions callback ?

### ISSUE THREAD

**Issue by JonathanWi** [zo0r/react-native-push-notification#28]
Hey there!

It appears that `requestPermissions` doesn't have a callback, which means I'm not able to know wether or not the prompt has been taped! Any idea on how I could do? 

Cheers!

**Comment by zo0r** [comment]
Use `PushNotification.checkPermissions(callback: Function)` to check permissions in **iOS**

**Comment by PurnimaNaik** [comment]
@JonathanWi 

To listen to the user's decision.

PushNotification.requestPermissions().then((response: any) => {
  if (response && response.alert !== 0) {
    // Allow
    return; 
  }
  // Decline
});
