### ISSUE TITLE
Example for setApplicationIconBadgeNumber would be super nice.

### ISSUE THREAD

**Issue by almadsen** [zo0r/react-native-push-notification#282]
So this isn't really an issue, but I can not for my life figure out how to get the icon badge to work.
I've tried a few things with the PushNotification.setApplicationIconBadgeNumber but with no result.

So a small example how to make it work would be super nice and much appreciated.

// I'm primarily interested in iOS

**Comment by npomfret** [comment]
There's no need to use this library if you're only using iOS.  Just use the PushNotificationIOS library bundled with react-native.  It doesn't add any value for iOS.

WRT setting the badge number... there's no trick to it really.  Are you seeing any error messages?  Are you using a real device? I don't think it will work on a simulator.

**Comment by almadsen** [comment]
Well, I'm thinking I'll get around to Android after iOS is in place so I'll stick around with this for a while longer ;-)

But Yes I'm using a real iPhone, and putting in:

PushNotification.setApplicationIconBadgeNumber({
    number: 1
});

**Comment by npomfret** [comment]
Try `PushNotification.setApplicationIconBadgeNumber(1);`

**Comment by almadsen** [comment]
Ah there we go, but way didn't I try that ;-)

**Comment by fenglu09** [comment]
Not working on Android.
