### ISSUE TITLE
iOS: JSON value ... of type NSMutableDictionary cannot be converted to NSString

### ISSUE THREAD

**Issue by jamealg** [zo0r/react-native-push-notification#283]
I'm using React Native 0.31 testing on a real iPhone 5S. I have no problem getting a registration token but my application errors as soon as it receives a notification from APNS. I created a brand new RN0.31 project with this plugin and received the same error. Using PushNotificationsIOS directly the same push notification came through successfully. 

![image](https://cloud.githubusercontent.com/assets/7450294/20238703/56aac9c6-a8bf-11e6-965f-6c8672659e5b.jpg)

**Comment by krzysztofp** [comment]
Same issue here

**Comment by wangyangzi** [comment]
Same issue here

**Comment by angelofrancisco** [comment]
Same issue here, still no way to work around this?

**Comment by jamealg** [comment]
I never did find a workaround except to split out my push notifications code and use this library for Android and the default PushNotificationIOS library for iOS.

**Comment by brascene** [comment]
Any update on this?

**Comment by noahprince22** [comment]
Anybody here find a work around?

**Comment by cation-project** [comment]
If you show me the code snippets related to sending or configuring the push notification, I might be able to help! @jpaas
