### ISSUE TITLE
How to return the value of PushNotification.getApplicationIconBadgeNumber?

### ISSUE THREAD

**Issue by almadsen** [zo0r/react-native-push-notification#284]
I'm trying to return the value of PushNotification.getApplicationIconBadgeNumber.
If I do:

PushNotification.getApplicationIconBadgeNumber(function(numBadges) {
    console.log('NUMBER OF BADGES: '+numBadges);
});

I get the value in to console, bu if I do:

var numberOfBadges = PushNotification.getApplicationIconBadgeNumber(function(numBadges) {
    return numBadges;
});
console.log('NUMBER OF BADGES: '+ numberOfBadges);

I get NUMBER OF BADGES: undefined

So what am I doing wrong here?

**Comment by justim** [comment]
This is not possible the way you want to do this. You can't return anything from a callback function. If you want to use the `numBadges` somewhere outside of the callback, you need to assign it to something outside of the callback, like:

```js
var context = this;
PushNotification.getApplicationIconBadgeNumber(function(numBadges) {
    this.setState({
        numberOfBadges: numBadges,
    });

    // or:
    context.numberOfBadges = numBadges;

    // or you do all your logic that you need the `numBadges`
    // for right inside the callback
});
```

After that you can use `this.state.numberOfBadges` or the `context.numberOfBadges` in some other place.

_Note: this all has to do with the `getApplicationIconBadgeNumber` method being async._
