### ISSUE TITLE
Is there a tutorial?

### ISSUE THREAD

**Issue by forki** [zo0r/react-native-push-notification#291]
I'm trying to set up react-native-push-notification in my react native app, but don't know where to start. Is there a good tutorial out there? If so ou might want to link to that from the readme.

**Comment by narek11** [comment]
@forki via github code search I found this project https://github.com/BarberHour/barber-hour
have a look

**Comment by binbinplay** [comment]
@narek11 Can you help me?? https://github.com/zo0r/react-native-push-notification/issues/293

**Comment by narek11** [comment]
@binbinplay I currently implementing my project and just got this module successfully integrated into my app but have sent and received any push notifications so far. Will ping you once I am able to do so.
I use pubnub integrated with google gcm. You can try it.
