### ISSUE TITLE
2.2.1  iOS not receiving push notification

### ISSUE THREAD

**Issue by teyou** [zo0r/react-native-push-notification#292]
RN: 0.34.1

After updated to 2.2.1 I'm unable to receive remote push notification no matter app is in foreground, background or killed.

Was wondering if anyone have the same issue?

**Comment by witalobenicio** [comment]
@teyou how did you solve?

**Comment by teyou** [comment]
@witalobenicio can check this troubleshoot document
https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md

**Comment by witalobenicio** [comment]
@teyou I'm able to receiving push notifications, but I can't show them in iOS if the app is on foreground.
