### ISSUE TITLE
onNotification userInteraction and foreground

### ISSUE THREAD

**Issue by maxdub** [zo0r/react-native-push-notification#296]
Hey! This is a general question about the functionality of the userInteraction  and foreground values that gets returned on the onNotification function. 

It is documented that - "If the notification was opened by the user from the notification area or not"

https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L198
Here the return value seems to be just the opposite of wether or not the app is in the foreground.
Isn't it possible to be in the foreground and also have a userInteraction at the same time? Is this intended? If it is, is there a way to monitor if the user clicks on the notification while the app is running?

Thanks for your time !

**Comment by npomfret** [comment]
This is a good question.  Do you know how it works on iOS?  The purpose of this project is to replicate the behaviour on Android, so maybe this is a bug

**Comment by maxdub** [comment]
I'm currently working on a project using version 2.1.1 on IOS (haven't gotten around to testing android just yet). I've tested it on a device and simulator and the foreground functionality works as intended so userInteraction can never be true when open. Mostly why i was curious if there was another way to detect user interaction in the foreground or if there was another intention behind how it was suppose to be used.

**Comment by npomfret** [comment]
Let's find out the iOS behaviour

**Comment by simonayzman** [comment]
Yeah, I was wondering about this, too. There are a ton of cases, namely iOS/Android, app in foreground/background/killed, screen on/off, tap notification/just open app.
