### ISSUE TITLE
iOS onNotification handler issue

### ISSUE THREAD

**Issue by Arkanine** [zo0r/react-native-push-notification#297]
Hello,
I faced with strange behavior, when onNotification handler start to produce fake notifications every second after receiving real notification.
I reproduce this bug on iOS (looks like everything is fine with Android):
React 15.3.0
RN 0.32.1
![screen shot 2016-11-28 at 20 36 00](https://cloud.githubusercontent.com/assets/5641601/20681240/64e0470c-b5ab-11e6-9654-7112d10f1220.png)

This id my code:

    handleNotifications() {
        PushNotification.configure({
            onRegister: (device_token) => {
                console.log(device_token);

                this.setState({ deviceToken: device_token });
            },
            onNotification: (notification) => {
                console.log(notification);
            },
            permissions: {
                alert: true,
                badge: true,
                sound: true
            },
            popInitialNotification: true,
            requestPermissions: true,
            senderID: "598771966573"
        });
    }

Please help me to figure out what can be the cause of this bug.

**Comment by jorge627** [comment]
Hello

@Arkanine Please, could you tell me if you fixed this ?
