### ISSUE TITLE
Ability to show only most recent notification in tray (Android)

### ISSUE THREAD

**Issue by Ryanthegiantlion** [zo0r/react-native-push-notification#298]
I have a messaging app which can send several push notifications in a minute. Is there any way to collapse these on android so that only the most recent notification will show?

**Comment by npomfret** [comment]
Not yet, the stacking feature for android push notifications isn't supported yet.

**Comment by l1br3** [comment]
This issue is quite old but I achieved this by setting an `id` parameter in my `data` payload.
