### ISSUE TITLE
[Android] default ic_notification should be a drawable 

### ISSUE THREAD

**Issue by damusnet** [zo0r/react-native-push-notification#300]
On Android Studio, when you add a notification icon through "File > New > Image Asset", and select "Notification Icons", it adds it as a `drawable` ressource. However, `react-native-push-notification` [defaults](https://github.com/zo0r/react-native-push-notification/blob/263a63e6ec4b1e417cf1ce5775994c66d942e48d/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L195) to a `mipmap`.

![image](https://cloud.githubusercontent.com/assets/433409/20830458/d84d41e0-b880-11e6-8ecd-b849f5d3deb3.png)

This should either be documented, or changed according to Android Studio.

**Comment by vikeri** [comment]
Duplicate of https://github.com/zo0r/react-native-push-notification/issues/177?

**Comment by damusnet** [comment]
Ah, yes, absolutely. Sorry for the oversight.
