### ISSUE TITLE
[Android] Notification doesn't appear in System center in released app

### ISSUE THREAD

**Issue by amelzer** [zo0r/react-native-push-notification#301]
So I've got the following problem:

Android notifications work even when the app is in background. They show up in the notification center and the callback is called (I update the badge number)
But it only works when running the app with "react-native run-android" or running it from Android Studio.
The app got published in the Play Store and the version I download there only updates the badge number but does not show up in the notification center, nor does it produce a notification sound.

I have no idea how I can debug this. Does anybody experience the same problem or has any hints on how to debug this?

**Comment by rhysowen** [comment]
Are you running your app from an emulator or an actual device?

**Comment by amelzer** [comment]
As I said it is the app installed from the play store and it runs on an actual device.
Am 04.12.2016 20:30 schrieb Rhys Owen <notifications@github.com>:Are you running your app from an emulator or an actual device?

**Comment by klinkov** [comment]
Same issue, but i don't see remote notificaton with "react-native run-android" too

**Comment by amelzer** [comment]
@klinkov You have to make sure it runs on the actual device AND the the notification payload has a "message" attribute

**Comment by klinkov** [comment]
yeah, i see incoming JSON it in console.log, but no system notification
i fix it with create PushNotification.localNotificationSchedule in onNotification event, it work but it hack :)

**Comment by LuisUrrutia** [comment]
same problem, with released version
