### ISSUE TITLE
PushNotification.cancelLocalNotifications broken

### ISSUE THREAD

**Issue by mlostekk** [zo0r/react-native-push-notification#302]
It seems that 

    PushNotification.cancelLocalNotifications({ id: '123' });

is broken. I am setting up a local notification like this

        PushNotification.localNotificationSchedule({
            /* Android Only Properties */
            id: '123', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
            ticker: message, // (optional)
            autoCancel: true, // (optional) default: true
            largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
            smallIcon: "ic_launcher", // (optional) default: "ic_notification" with fallback for "ic_launcher"
            bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
            subText: "This is a subText", // (optional) default: none
            color: "red", // (optional) default: system default
            vibrate: true, // (optional) default: true
            vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
            tag: 'some_tag', // (optional) add tag to message
            group: "group", // (optional) add group to message
            ongoing: false, // (optional) set whether this is an "ongoing" notification

            /* iOS only properties */
            //alertAction: // (optional) default: view
            //category: // (optional) default: null
            //userInfo: // (optional) default: null (object containing additional notification data)

            /* iOS and Android properties */
            title: "My Notification Title", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
            message: message, // (required)
            playSound: false, // (optional) default: true
            soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
            number: '123', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)

            /* date, only with scheduled notifications */
            date: date
        });

and on iOS the notification is sent and not cancelled.

Is there anything else to consider?

I am on v2.2.1.

(Its working fine on Android)

**Comment by rhysowen** [comment]
To get this to work, you need to pass through the `userInfo` dictionary into`localNotificationSchedule`.

For example,

```js
PushNotification.localNotificationSchedule({
   ...
   userInfo: { id: '123' }
   ...
});
```

and..

```js
PushNotification.cancelLocalNotifications({ id: '123' });
```

This is required for iOS.

For more information, check the the [PushNotificationIOS](https://facebook.github.io/react-native/docs/pushnotificationios.html) API as this library simply provides a wrapper around it.

Also, `scheduleLocalNotification` now supports `repeatInterval`, however this library doesn't as of yet. There is however, a PR #288 for it.

**Comment by mlostekk** [comment]
perfect. thank you!

**Comment by 2ducanhpham** [comment]
PushNotification.cancelLocalNotifications({ id: '123' }); not working ios & android
PushNotification.cancelAllLocalNotifications() not working android

I used React native 0.40, react-native-push-notification 2.2.1
