### ISSUE TITLE
onNotification() not triggered on iOS once the notification is displayed or pressed

### ISSUE THREAD

**Issue by abeikverdi** [zo0r/react-native-push-notification#304]
I dont get the log when the notification is displayed nor when I press the notification.

```
// (required) Called when a remote or local notification is opened or received
    onNotification: function(notification) {
        console.log( 'NOTIFICATION:', notification );
    },
```

Is there something that im doing wrong or its just a bug?

**Comment by booboothefool** [comment]
@abeikverdi Same here... but it works on Android, yeah?

**Comment by edmondcang** [comment]
it works not for me on android too (though i've never tried it on iOS)
in my situation, when the app runs on background, it is not triggered. It works only when the app runs on foreground

**Comment by JonoH** [comment]
Running iOS 10, RN 0.39, and v2.2.1 of the plugin. onNotification() not being triggered. Works on Android

**Comment by RWOverdijk** [comment]
👍  has anyone found a solution to this?

**Comment by jmeiss** [comment]
Same issue for me. Works great on Android but not on iOS. `onNotification` is triggered only when the app is back on the foreground.

**Comment by shrutic** [comment]
@jmeiss For me the onNotification works on iOS when in background and foreground ( I had to go the Swift route to get it to work in iOS when app is killed). For Android, however it works only when app is in foreground, but now when app is in background / killed

**Comment by bacancy-swaroopa** [comment]
@shrutic Hi Can you tell me how to handle in iOS when the app is killed state I mean what is that swift route to get it work?

**Comment by 94wogus** [comment]
@abeikverdi same here!! is there anyone who find solution?

**Comment by Dallas62** [comment]
Hi @94wogus 
this Library doesn't implement specific code for iOS.
Please refer to https://github.com/react-native-community/push-notification-ios
