### ISSUE TITLE
Must call isn't `finish` method (as of RN 0.38)

### ISSUE THREAD

**Issue by jsdario** [zo0r/react-native-push-notification#305]
On the `Trouble-Shooting.md` guide we can read the following:

> After you have processed the notification you must call isn't `finish` method (as of RN 0.38).

My app crashes after receiving a silent push remote notification. It prompts the error `Yeti has stopped`. However the code seems to run as expected. I cannot figure out why the error is, as the stack trace is rather opaque:

```
W/PackageManager( 1277): Failure retrieving resources for com.netbeast.yeti.debug: Resource ID #0x0
```

What does it mean? May it help me solve the bug? Do you have any further references about that `finish` method?

**Comment by npomfret** [comment]
Sorry, that documentation is dependent on a PR that hasn't been merged yet. https://github.com/zo0r/react-native-push-notification/pull/277

**Comment by jsdario** [comment]
Thanks for the clarification @npomfret. Just reviewed the PR. It seems that in Android it is only a no-op.

I guess that the crash I am experiencing has other reasons, then >.<

**Comment by jsdario** [comment]
Any updates on this? I am moving now to iOS and I am struggling to handle notifications on the background. I wonder if it is because of this.

**Comment by npomfret** [comment]
This is needed, but even with it I'm still struggling.  See this discussion: https://github.com/facebook/react-native/issues/11162

**Comment by jsdario** [comment]
Oh, let me know if I can be useful. I read through the issue, but sorry to say my knowledge / time does not reach that far. Are you calling `finish` anywhere in any production apps?

**Comment by npomfret** [comment]
I am, but I still don't think it's working exactly correctly.  

When the OS kills the app (which happens a lot, basically as soon as a couple of other apps get opened) a push notification can trigger it to start again.  What I'm seeing is that 1 or 2 notifications work, but then they stop.  Still trying to work out why.

**Comment by jsdario** [comment]
After some research I realised that when an app is terminated no longer works on the background. Do not know if it is your case :/

**Comment by npomfret** [comment]
If an iOS app is terminated by the user it will no longer work.  But if the OS terminates it in order to free up memory for another app then the OS will also relaunch it when a notification arrives.  This is the case I'm concerned with - I'm not able to get it working reliably.
