### ISSUE TITLE
getScheduledLocalNotifications()

### ISSUE THREAD

**Issue by GCour** [zo0r/react-native-push-notification#306]
React Native PushNotificationIOS has this function included, would it be possible to add this feature too? It would be nice to see all local scheduled notifications.

https://facebook.github.io/react-native/docs/pushnotificationios.html

**Comment by Subalee** [comment]
Just for clarity, it's this [method](https://facebook.github.io/react-native/docs/pushnotificationios.html#getscheduledlocalnotifications) 

This wrapper is built on top of PushNotificationIOS. Thus if you import the PushNotificationsIOS you will see all scheduled notification, even those scheduled with this library.

However, for android there is no way for getting scheduled notifications which kinda sucks to be honest.

**Comment by midimurphdesigns** [comment]
How do you do this on android? PushNotificationsIOS.getScheduledLocalNotifications() is working great on IOS but I'm not sure how to do this for android devices.
