### ISSUE TITLE
Navigator this.props.navigator.pop is not working, React Native

### ISSUE THREAD

**Issue by swaroopa94** [zo0r/react-native-push-notification#307]
I am working on react native application.

In that I implemented react native gifted messenger for chat.

My Issue is:

I am in background and i got a push notifications when user send the messages. suppose I got 10 messages.
After clicking on the notification I am redirecting to chat page in that i have a back button when clicking on that I wrote:

`this.props.navigator.pop();`
But when I click on that my screen is not poping and not going to back screen.
Here is the code when i get a notification:
`onNotification:(notification)=>{
      console.log( 'NOTIFICATION:',notification);
      if(this.state.appstate =='background'){

          this.props.navigator.push({
          component:Chat,
          passProps:{fromUserId:userId,toUserId:oponentUserId}
        })

        }
    }`

I need When clicking on the notification in the panel i have to open the app and got to the chat screen.

What can be done to solve this problem ?

**Comment by swaroopa94** [comment]
Here When I get a notification in background, the onNotification() method is called when notification arrives and it is called again when I Click on the notification resulting in pushing to chat screen twice.

**Comment by gregogalante** [comment]
I have the same problem too

**Comment by zhaiyjgithub** [comment]
same issue.

**Comment by adwait-audetemi** [comment]
Were you able to fix this?
