### ISSUE TITLE
Document Permissions Required for LocalNotificiations vs GCM

### ISSUE THREAD

**Issue by cancan101** [zo0r/react-native-push-notification#31]
In order to send/receive local notifications, only a subset of the permissions are needed.

**Comment by npomfret** [comment]
Could you submit a PR?

**Comment by jdmunro** [comment]
Does anyone have a list of the difference? I'm currently only interested in local notifications.

**Comment by npomfret** [comment]
I don't I'm afraid, but if you find out that would be useful information for the trouble shooting guide.  Could you update us with what you discover?
