### ISSUE TITLE
getToken() ? 

### ISSUE THREAD

**Issue by Crash--** [zo0r/react-native-push-notification#312]
Hi, 

The plugin works great for the case when the app is used only by one user per device since the onRegister() function is only called once. 

In my app, I can logout and login with another account, but the onRegister function is not called anymore (since the device is already registered). 

Is there a way to get the deviceToken from the `PushNotification` object? 
If not, I certainly can store the device Token in AsyncStorage, but if the token changes from APN, does it call onRegister() function ?

**Comment by varungupta85** [comment]
@Crash-- I think you can just call the `requestPermissions` method whenever the user signs in which should get a new device token and call the `onRegister` handler.

**Comment by braco** [comment]
@varungupta85 - requestPermissions doesn't fire onRegister for me.

**Comment by npomfret** [comment]
I think this is detailed in the trouble shooting guide.  If not it should be

**Comment by jose920405** [comment]
@braco 

And for this case?

https://github.com/zo0r/react-native-push-notification/issues/943
