### ISSUE TITLE
InvalidRegistration - Android - Play Store only

### ISSUE THREAD

**Issue by kjprice** [zo0r/react-native-push-notification#313]
First of all. Thanks for this project, it has saved me a lot of time!

I have this installed and push notifications are working on iOS. Additionally, push notifications *are* working for android when running the device locally (on a real device through usb to dev server). Once I publish the app and download it, however, push notifications no longer work. I am getting the error message "InvalidRegistration".

I am saving the registration tokens to our database and can confirm that I am getting fresh tokens from the device. I understand that there may be some growing pains with transition from GCM to Firebase, but I don't think that is anything that we need to figure out - that *should* GCM should handle that transition, I would think.

Interesting to note that when I go to the **Firebase** console and send a notification to all devices, the devices *do* receive the notifications. I don't know where the disconnect is, but I think it has to do with firebase not liking the registration tokens from production.

Has anyone experienced anything similar? Any tips?

I think this is similar to #215 but my problem is only when downloading the app from the play store.

**Comment by kjprice** [comment]
This is great. The problem was that we are storing the registration ids in a mysql database in a field defined as varchar(128). I'm finding these registration ids, for android, can be 154 characters in length...so the database was cutting off characters from the registration id! Changing the field to varchar(256) seems to be fine now.

**Comment by npomfret** [comment]
Can we close the ticket then?
