### ISSUE TITLE
Remote push notification

### ISSUE THREAD

**Issue by GCour** [zo0r/react-native-push-notification#316]
I've successfully managed the local notifications part, but how do I start with remote notifications? What do I need? It's so unclear in the documentation..

Thanks in advance

**Comment by npomfret** [comment]
You need to read up separately on iOS and Android. For android search for Google Cloud Messaging.  For iOS you can read the RN docs and search for Apple Push Notification Service

**Comment by nilaybrahmbhatt** [comment]
@npomfret  can i use firebase for both??

**Comment by npomfret** [comment]
I've not used firebase so I don't know I'm afraid.
