### ISSUE TITLE
getStringExtra on null Intent

### ISSUE THREAD

**Issue by diegocstn** [zo0r/react-native-push-notification#317]
Hi, 
if for whatever reason `intent` is null in the registration Service, the app crash.
https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationRegistrationService.java#L19
Maybe is safer to extract the senderID in the `try-catch` block?
If it helps I can submit a PR!

**Comment by npomfret** [comment]
Do you have a stack trace?

**Comment by dieguitoweb** [comment]
Sure! From Crashlytics:
[stacktrace.txt](https://github.com/zo0r/react-native-push-notification/files/663314/stacktrace.txt)

**Comment by npomfret** [comment]
Does it always happen for you?  Or just on some devices?

**Comment by dieguitoweb** [comment]
Nope and I was not able to reproduce the issue, it happens with different devices and apps with no obvious reason

**Comment by npomfret** [comment]
Hmm, its super strange.  The OS is passing a null intent for some reason.  I've made a small change to master, can you change your package.json to give it a test.  It won't fix the problem (I've no idea what could be causing it), but it should prevent your app from crashing.
