### ISSUE TITLE
undefined is not an object (evaluating 'RNPushNotification.presentLocalNotification')

### ISSUE THREAD

**Issue by Dynamique-Zak** [zo0r/react-native-push-notification#318]
Hello,

I setup react-native-push-notification according the Readme, but when i use the localNotification like this:

```javascript
var PushNotification = require('react-native-push-notification');

PushNotification.localNotification({
   message: 'My notification message'
});
```

I have this error:
```
undefined is not an object (evaluating 'RNPushNotification.presentLocalNotification')
```

Have you some idea about this ?

My react native version: 0.36

**Comment by npomfret** [comment]
sounds like you've not _linked_ you're project correctly.  Please recheck the readme and the trouble shooting guide.

**Comment by jurgenphotek** [comment]
I was having this problem just a minute ago. i did `react-native link` and the output said the notification lib was linked.. but I needed to modify MainActivity anyway.

**Comment by Dynamique-Zak** [comment]
Always the same :/
I just recheck readme and trouble shooting guide, i do react-native link, and in settings.gradle :
```
include ':react-native-push-notification'
project(':react-native-push-notification').projectDir = file('../node_modules/react-native-push-notification/android')
```

in build.gradle:
```
    compile project(':react-native-push-notification')
    compile ('com.google.android.gms:play-services-gcm:+') {
        force = true;
    }
```

In the MainApplication.java the package is imported
``` 
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
```
and i verified that package has been added in react package list 
```
  protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new ReactNativePushNotificationPackage()
      );
    }
```
Also, i run the application in my physical devise and i sure that this package are correctly linked.

**Comment by npomfret** [comment]
Did you also check your manifest file?

**Comment by Dynamique-Zak** [comment]
Yes, here is my manifest file:

``` java
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.myapp"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.GET_TASKS" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>

    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <permission
       android:name="com.myapp.permission.C2D_MESSAGE"
       android:protectionLevel="signature" />
    <uses-permission android:name="com.myapp.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">

      <receiver
          android:name="com.google.android.gms.gcm.GcmReceiver"
          android:exported="true"
          android:permission="com.google.android.c2dm.permission.SEND" >
          <intent-filter>
              <action android:name="com.google.android.c2dm.intent.RECEIVE" />
              <category android:name="com.myapp" />
          </intent-filter>
      </receiver>
      
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
         <intent-filter>
             <action android:name="android.intent.action.BOOT_COMPLETED" />
         </intent-filter>
      </receiver>
      <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
      <service
        android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
        android:exported="false" >
        <intent-filter>
          <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        </intent-filter>
      </service>
      <service android:name="com.mapbox.mapboxsdk.telemetry.TelemetryService"/>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

      <meta-data
       android:name="com.google.android.geo.API_KEY"
       android:value="--mykey--" />
    </application>

</manifest>
```

Just a question in passing, if i want use only local notification, do i still to set GCM part in manifest file ?

**Comment by edmondcang** [comment]
i had the same issue. Fixed after running `react-native run-android` in the terminal.

**Comment by flaviosbert** [comment]
Apparently i have the same problem, with a different message: undefined is not an object (evaluating RNPushNotification.getInitialNotification)

Any ideas?

**Comment by j-nolan** [comment]
@flaviosbert I just had that issue and it appeared `react-native link` did not link the dependency because it was not listed as a dependency in `package.json`.

To fix this, [make sure you install the package with the `--save` flag](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#step-1):
```
npm install --save react-native-push-notification
react-native link
```

@npomfret  If you accept pull requests, I'd be happy to make one to update the documentation with the npm `--save` flag

**Comment by npomfret** [comment]
I can merge PRs.  I don't have much time to test, but a change to the docs won't need testing.  Thanks for your input

**Comment by nicolaselmir** [comment]
I have the same issue

**Comment by nazywamsiepawel** [comment]
I'm struggling with the same here. I have ran the npm install with --save flag, react-native link and connected everything manually as well. 

Did you manage to get it to work eventually @nicolaselmir @Dynamique-Zak ? If yes, what was the problem?

**Comment by vijayperlakota** [comment]
**react-native link** and ** react-native run-* ** should solve the issue.
I did this when I had faced the same issue.

**Comment by amywtlin** [comment]
Can confirm running `react-native run-android` after `react-native link` command solves the issue

**Comment by Neavend** [comment]
Just had the same issue, it was because `react-native link` did not add `new ReactNativePushNotificationPackage()` in `MainApplication.java`, adding it manually made it work.

**Comment by Hanzig** [comment]
I had the same issue. After couple of hours of troubleshooting, I realised that I had a redundant package which was being imported right after 

`import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;`

Make sure all packages imported in MainApplicaiton.java are being used and do exist in the project.

**Comment by Dynamique-Zak** [comment]
Hey ! With long delay, i'll close this issue, sorry for the wait, but it's only recently that I've been able to test your suggestions, 
Thanks !

**Comment by BobAleena** [comment]
After running react-native link, I received this error: 
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/iid/zzb;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/iid/zzb;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
    
:app:transformClassesWithDexForDebug FAILED

**Comment by PoojaVM** [comment]
Facing the same issue s @BobAleena . Got any solution?

**Comment by jinaddavid** [comment]
Am having the same issue "undefined is not an object (evaluating RNPushNotification.getInitialNotification)"

Please any solution ?

**Comment by PoojaVM** [comment]
The issue I faced- "undefined is not an object (evaluating RNPushNotification.getInitialNotification)".
The reason- I was trying to integrate the library while using expo for running project which is not supported. You will have to eject your project using "react-native init". Doing so worked for me. 
Strange thing is no one has mentioned that it will not work with expo as a lot of people use expo for development of their mobile apps.

**Comment by lilyyang88** [comment]
I'm using expo ejected app , also got this error, Is that true this package not supporting expo apps? Any idea? Tried all the ways mentioned above, still got the error.

**Comment by KthProg** [comment]
If I run using `react-native run-android` I get an error about permissions. Not sure if it's related, but I get the above errors if I run using `exp start`. Either way I get errors, it does seem as though Expo is not supported even after ejecting the app.

**Comment by pranjalnarola** [comment]
I'm having same issue "undefined is not an object (evaluating 'rnonesignal');"
Any solution ??? plz reply.

**Comment by bosz** [comment]
`react-native run-android` solves this for me too like @edmondcang suggested.
