### ISSUE TITLE
Detect Notification interaction on Android not working?

### ISSUE THREAD

**Issue by MossP** [zo0r/react-native-push-notification#319]
On iOS my `handleNotification()` get called when the app has been brought to the foreground via a click on the notification. This does not seem to happen on Android though. Should I be going another route for this instead?

The notification is getting to the device ok. It just doesn't trigger the handler when tapped.

Version 2.2.1
RN 0.35

```
  componentDidMount(){
    PushNotification.configure({
    onRegister: (token) => {
        console.log( 'TOKEN:', token );
        this.handlePushRegistration(token);
    },
    onNotification: (notification) =>  {
        console.log( 'NOTIFICATION:', notification );
        this.handleNotification(notification);
    },
    senderID: "xxxxx", // I have entered the ID here
    permissions: {
        alert: true,
        badge: true,
        sound: true
    },
    popInitialNotification: true,
    requestPermissions: false,
  });

  handleNotification(notification){
    // never gets called on Android but works on iOS
  }
```

**Comment by MossP** [comment]
Possible duplicate of https://github.com/zo0r/react-native-push-notification/issues/272

**Comment by valeryq** [comment]
Same behavior, when application in foreground it works as expected.
But if application in background:
- onNotification called when message received in background and after that I initiate localNotification.
- When user tap on notification in notification center -> application launch, but onNotification not triggered.

@mikelambert @zo0r @npomfret

**Comment by sckoh** [comment]
the problem occurs due to the variable
hasPoppedInitialNotification is set to true after the app is initialized.
so when android go into background and opened through notification click again, 
the popInitialNotification function will not be called
