### ISSUE TITLE
Use conventional folder naming so that rnpm works

### ISSUE THREAD

**Issue by cancan101** [zo0r/react-native-push-notification#32]
see: https://github.com/rnpm/rnpm/issues/116#issuecomment-200069248

**Comment by grabbou** [comment]
Few examples:
https://github.com/Microsoft/react-native-code-push/tree/master/android
https://github.com/idehub/react-native-billing/tree/master/android

**Comment by zo0r** [comment]
@cancan101  I just renamed the folder to **"android"** https://github.com/zo0r/react-native-push-notification/commit/dfded5d36a0dcfe946a32e208b67c4e397eb9127
