### ISSUE TITLE
react-native-push-notification:processReleaseResources FAILED

### ISSUE THREAD

**Issue by umaire313** [zo0r/react-native-push-notification#320]
i followed this link fir notification (react-native)
https://github.com/zo0r/react-native-push-notification

after did complete setting for android

when i run command react-native run-android

i got this error

:react-native-push-notification:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-push-notification:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.E
xecException: Process 'command 'C:\AndroidStudio\Sdk\build-tools\23.0.1\aapt.exe
'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

**Comment by npomfret** [comment]
So, did you try adding the --stacktrace, --info or --debug options?

**Comment by ericvillemure** [comment]
I get the same issue ahd here is a more precise error log:
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.1\res\drawable\abc_textfield_search_material.xml:18:87-138 : No resour
ce found that matches the given name (at 'drawable' with value '@drawable/abc_textfield_search_activated_mtrl_alpha').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.1.1\res\drawable\abc_textfield_search_material.xml:19:89-140 : No resour
ce found that matches the given name (at 'drawable' with value '@drawable/abc_textfield_search_activated_mtrl_alpha').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_icon_dark.xml:5:27-80
: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_disabled').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_icon_dark.xml:8:27-79
: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_pressed').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_icon_dark.xml:11:27-79
 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_focused').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_icon_dark.xml:13:27-78
 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_dark_normal').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_icon_light.xml:5:27-81
 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_disabled').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_icon_light.xml:8:27-80
 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_pressed').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_icon_light.xml:11:27-8
0 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_focused').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_icon_light.xml:13:27-7
9 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon_light_normal').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_text_dark.xml:7:27-80
: No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_disabled').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_text_dark.xml:10:27-79
 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_pressed').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_text_dark.xml:13:27-79
 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_focused').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_text_dark.xml:15:27-78
 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_dark_normal').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_text_light.xml:5:27-81
 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_disabled').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_text_light.xml:8:27-80
 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_pressed').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_text_light.xml:11:27-8
0 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_focused').
...\example\node_modules\react-native-push-notification\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.6.1\res\drawable\common_google_signin_btn_text_light.xml:13:27-7
9 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text_light_normal').

:react-native-push-notification:processReleaseResources FAILED

**Comment by baotoan1905** [comment]
Same issue, any ideas guys ?

**Comment by toolaugh** [comment]
..\react-native-starter-app\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.
2.0\res\drawable\common_google_signin_btn_icon_dark_normal.xml:3:29-91 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_icon
_dark_normal_background').
..\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.
2.0\res\drawable\common_google_signin_btn_icon_light_normal.xml:3:29-92 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_ico
n_light_normal_background').
..\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.
2.0\res\drawable\common_google_signin_btn_text_dark_normal.xml:3:29-91 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_text
_dark_normal_background').
..\node_modules\react-native-device-info\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\10.
2.0\res\drawable\common_google_signin_btn_text_light_normal.xml:3:29-92 : No resource found that matches the given name (at 'drawable' with value '@drawable/common_google_signin_btn_tex
t_light_normal_background').

**Comment by ericvillemure** [comment]
Don't know if this will help you but thix fixed a similar issue for me.  https://stackoverflow.com/a/41314222/301682

**Comment by lcnogueira** [comment]
Had the same problem on windows and [this](https://stackoverflow.com/questions/30943180/no-resource-found-errors-for-supportappcompat-v722-0-0-on-android-studio/33337655#33337655) worked for me 👍

**Comment by nguyenvanphuc2203** [comment]
same issue

**Comment by Boris-Vladimirovich** [comment]
Same issue. Any ideas? I've tried solutions with max heap size, but it doesn't help me.
