### ISSUE TITLE
When i send from firebase console message nothing happend...

### ISSUE THREAD

**Issue by kfir91** [zo0r/react-native-push-notification#322]
I opened project in firebase and set the file google-services.json in app directory...
i set SENDER ID on the configure
and when i send message in firebase console - Compose message nothing happend...

what i need to do?

i working with android and RN > 0.30

**Comment by jk94** [comment]
i've got the same problem but only when my app is 'active'. When my app is in background the notification shows up.
In both app states the onNotification function is not running.

**Comment by anray** [comment]
@kfir91 @jk94 
Please advise if  PushNotification.configure({onRegister}) fires in your apps. 
It doesn't in my.
What configuration differences are for Firebase in difference to GCM?

**Comment by anray** [comment]
The problem was that I ignored to include entries in manifest.
Now it is firing! But each time app starts.
Is it correct to run register method each time app starts?

**Comment by anray** [comment]
I agree with @kfir91 that push notification doesn't arrive when app is "dead"(not in background)
Pushes only arrive when app is in background (not foreground)

**Comment by anray** [comment]
Ok, so finally I can conclude that push notifications arrive in "dead" and background mode but do not arrive in foreground (method onNotification doesn't fire).
In my case notifications in "dead" mode didn't arrive because firmware of my Redmi Note 3 has extra autorun configurations. I had to add app to autorun inclusions.

**Comment by zalesky** [comment]
@anray Did you try to send a messages from this https://console.firebase.google.com/project/<YourAppName>/notification/compose form and all is working?  
I got a token from trigger onRegister. And when send a message from that form - nothing is happen. Tried to do it with connected by usb device and app on it in background or active. Nothing arrive even if in firebase console status is Completed

**Comment by zalesky** [comment]
I was expected that remote notifications will be displayed on a screen, lol)

**Comment by vvavepacket** [comment]
@zalesky, i encountering same issue as yours, im firing using firebase console.. i can see my token on my mobile device,, but nothing is received, the onNotification is not called on my mobile device. have u solved your issue?

**Comment by zalesky** [comment]
@vvavepacket, it works for me, try to set debugger to your onNotification function and it must fire

**Comment by vvavepacket** [comment]
@what was your issue before why the function is not fired before? I set a debugger on the onNotification, but it is not fired. Does the token contains a colon symbol like yours?

![image](https://user-images.githubusercontent.com/8295642/29123864-24f034d4-7ce5-11e7-9a2f-d8da7ce7e22f.png)

**Comment by vvavepacket** [comment]
I tried firing a local notification and it worked... but remote notifications from firebase doesn't work.. May I see a copy of your AndroidManifest.xml?

**Comment by vvavepacket** [comment]
@zalesky i tried this service:

http://pushtry.com/

it worked,, but why is that when I tried firebase console, it doesnt work?

**Comment by AdrienKuhn** [comment]
I have the same issue here. 

The onRegister function is called and I have a token for my device, but nothing happend when I send a message from the Firebase console.

I tried with 2 different devices, with the app in the foreground and in the background.

**Comment by wwwdata** [comment]
@AdrienKuhn got the same issue here. Setup iOS first, everything worked. Got onRegister and onNotification callbacks. On Android, I also get a device token with the onRegister callback but when I send a notification via the firebase console, nothing arrives... Not in the foreground, not in the background, just nothing. 

Did you manage to solve the problem?

**Comment by AdrienKuhn** [comment]
@wwwdata I was able to bypass Firebase with a curl command:

```
curl -X POST \\n  https://android.googleapis.com/gcm/send \\n  -H 'authorization: key={authorization_key}' \\n  -H 'cache-control: no-cache' \\n  -H 'content-type: application/json' \\n  -d '{       \n  "registration_ids":["{registration_id}"],\n  "data": {\n    "body": "Hello World"\n  }\n}'
```

**Comment by avinashwigroup** [comment]
I cannot send push notifications from firebase to a single device.  The token received onRegistration is actually the token from APNS and not firebase. 

Does anyone know how to do it ?

**Comment by zedtux** [comment]
I'm in the same boat. I have a working iOS push notification version and want to make the same with Android.

The `onRegistration()` is never fired, no matter what I'm doing. Also is some articles, like [this one](https://medium.com/@anum.amin/react-native-integrating-push-notifications-using-fcm-349fff071591), they're talking about `firebase.messaging().hasPermission()`. I'm wondering if this package's documentation is up-to-date 🤔.
