### ISSUE TITLE
Notification is not appearing on some Huwaei devices when the application is totally killed.

### ISSUE THREAD

**Issue by Moussawi7** [zo0r/react-native-push-notification#325]
I successfully installed the plugin on my project, and it 's working excellent on S4(4.4.2) and S6(5.1.1).
unfortunately, push notification is not appearing on some android devices like Huwaei G8(5.1.0) and HTC(5.1.1) when the application is totally killed.
Any advice?!.

React-Native Version: 0.37
react-native-push-notification Version: 2.2.1

**Comment by harmaa** [comment]
I had similar problems with Huawei Honor 5C. Fixed it by switching the device's power saving mode to a less constraining one.

**Comment by Moussawi7** [comment]
@harmaa ,
I just tried to change power saving option with no success, but i noticed that if i put the application within "protected apps", push notifications will receive successfully.

**Comment by Moussawi7** [comment]
I found this:
for Huawei, application should be added to protected apps.
this plugin solve the issue:
https://www.npmjs.com/package/react-native-huawei-protected-apps

**Comment by jaisonveneri** [comment]
@Moussawi7,

The same happen in Xiaomi MIUI.

**Comment by npomfret** [comment]
Do you have a stack trace?
