### ISSUE TITLE
Android Push Notification - App in Background create two messages simultaneously

### ISSUE THREAD

**Issue by 2ducanhpham** [zo0r/react-native-push-notification#334]
Please help me!

**Comment by npomfret** [comment]
You need to provide some detail

**Comment by hussainahmad** [comment]
@npomfret I am using Demo Example for android, When APP is in foreground it receive one notification which is right but when app is background or app is close I am receiving  two notification, I simply using `provided github example` .

**Comment by kristacoblentz** [comment]
This is happening to me too. 

`pushNotificationHelper.sendToNotificationCentre(bundle);`
is getting called from both RNPushNotificationListenerServiceGcm (line 118) & RNPushNotificationListenerService (line 135), making the push delivered twice on a remote notification, making it duplicated in the phone notification center.

**Comment by ragozin-n** [comment]
Same issue

**Comment by KhubaibQaiser** [comment]
Any progress on this so far? Because it's happening to me as well.

**Comment by schumannd** [comment]
After applying the fix from [this comment](lasspath 'com.google.gms:google-services:+') to the crash on push message bug described in that issue, I am now experiencing this bug as well. All messages are received twice.

**Comment by nbolender** [comment]
@schumannd does removing that block make it impossible to schedule local notifications? The docs are a bit unclear as to what to put in your manifest if you are using both FCM and scheduled local notifications.
