### ISSUE TITLE
Repeating local notification does fire every 5 seconds

### ISSUE THREAD

**Issue by kenma9123** [zo0r/react-native-push-notification#335]
UPDATE:
I have found the solution: You have to include `fireDate` so the notifier know where it begins.
```diff
PushNotification.localNotification({
  id: '1605612934',
  title: "Notification title",
  message: "Notification message",
  repeatType: 'time',
  repeatTime: 30000, // 30 seconds
+ fireDate: Date.now()
});
```

-------

The repeating local schedule does not work. It fires every 5 seconds whatever I put into the `repeatTime` property. Here's my notification details. Which should fire every 30 seconds as a test.

```
PushNotification.localNotification({
  id: '1605612934',
  title: "Notification title",
  message: "Notification message",
  repeatType: 'time',
  repeatTime: 30000 // 30 seconds
});
```

The adb logcat says it when you take the difference of the two time intervals.
```
 RNPushNotification: NotificationPublisher: Prepare To Publish: 1605612934, Now Time: 1484569339572
 RNPushNotification: NotificationPublisher: Prepare To Publish: 1605612934, Now Time: 1484569344592
```

Android SDK version: 23
ReactJS version: 0.40.0

Anything I'm doing wrong?

**Comment by lukewlms** [comment]
In case you found this Googling and  you're seeing this in the modern version of this lib (without fireDate):

Make sure `date` is not set in the past.

In iOS if you set a past date with recurring, it will only show future reminders; however, Android will try to "catch up" and show every "missed" notification (which in our case was thousands).

Set ONLY future dates when setting up a repeated notification.
