### ISSUE TITLE
WAKE_LOCK Permission

### ISSUE THREAD

**Issue by cancan101** [zo0r/react-native-push-notification#34]
Why is the `WAKE_LOCK` permission requested? I don't see this: http://developer.android.com/reference/android/os/PowerManager.WakeLock.html being used.

**Comment by deanmcpherson** [comment]
+1

**Comment by zo0r** [comment]
Removed: https://github.com/zo0r/react-native-push-notification/commit/42682e885154b3fdf9332d261e825617578985fa

**Comment by tberghuis** [comment]
It looks like WAKE_LOCK was re-added to the readme. Can someone explain in which scenarios that this permission is to be enabled and why it is needed?
