### ISSUE TITLE
Discussion: More maintainers

### ISSUE THREAD

**Issue by Looveh** [zo0r/react-native-push-notification#343]
Notifications are a core part of mobile app development and currently this repo is (arguably) the best alternative out there for both local and push notifications. Needless to say the pull for this repo is huge - just at this moment there's:

- 10k downloads in the last month from `npm`
- 117 open issues
- 15 open pull requests

I'd like to open a discussion on whether there should be more maintainers for this repo that can handle the large throughput of issues and PR's that is necessary to keep this repo being as good as it is. What's your opinions?

**Comment by stueynet** [comment]
I strongly agree

**Comment by npomfret** [comment]
Hi

I'm a maintainer on here.  I've not had a chance to work on much lately, apologies.  

Some PR in the past have been quite poorly documented and have taken an unreasonable amount of time to test.   If people could test pending PRs in their own forks and comment on them that would be really helpful. Merging a PR just isn't a quick task on this project (typically) and so I think it puts people off looking at them.

IMO PR's should contain a the motivation for the change, what the change is, and crucially how to test it - **what's the expected change in behaviour**?.  

If other people could test PR's and comment on them, then the maintainers could simply merge (if there are no complications).

**Comment by npomfret** [comment]
There are actually loads on maintainers on here.  I guess people just don't have the time as (from experience) these PR's can take ages to test.  I think the best solution is for people to test each others before a contributor gets involved.  I've added some docs: https://github.com/zo0r/react-native-push-notification/blob/master/submitting-a-pull-request.md
