### ISSUE TITLE
iOS LocalNotification doesn't shown

### ISSUE THREAD

**Issue by anhtuank7c** [zo0r/react-native-push-notification#344]
My LocalNotification work well on Android, but on iOS doesn't shown notification.
It did send once, and then it doesn't shown anymore.
Clip: [https://www.youtube.com/watch?v=p3YX_g52mGw](https://www.youtube.com/watch?v=p3YX_g52mGw)
I still get onNotification event as bellow image.
![screen shot 2017-01-24 at 9 02 28 am](https://cloud.githubusercontent.com/assets/3163410/22231099/ea79d952-e213-11e6-97c9-bcc44eeba3ff.png)
I did follow this tutorial to config iOS project: https://facebook.github.io/react-native/docs/pushnotificationios.html#content

Here is my source code: https://github.com/anhtuank7c/Clock/blob/master/src/components/Timer.js#L67

**Comment by rsage28** [comment]
I'm seeing the same issue. The notification doesn't show up on iOS, but the onNotification callback is getting called.

**Comment by anhtuank7c** [comment]
Finally i know notification will work on ios when app state is background, when app state is active will not show. You have too use alert or something similar.
