### ISSUE TITLE
iOS silent remote push notification when app is killed

### ISSUE THREAD

**Issue by chiformihai** [zo0r/react-native-push-notification#345]
Everything works ok when the app is in background or has been killed by the OS, but is there any chance of showing a notification when the app is killed by the user? 
**The phone does vibrate**, so the silent remote push notification is received, but there's not visual notification

React native version: 0.37.0

**Comment by npomfret** [comment]
Not on iOS, but yes on Android.  Please check the trouble shooting guide.

**Comment by chiformihai** [comment]
On Android everything works well.
I've read the troubleshooting, but it doesn't specify this particular case (or maybe I don't understand, sorry if so), though I've seen this in some other issues. Is this the issue: _(iOS) The OS can penalise your app for not calling the completion handler and will stop (or delay) sending notifications to your app. This will be supported from RN-0.38_ ? If so, an upgrade to RN 0.38 will solve it?
I would use the _noisy remote push notifications_, but the problem is **userInteraction** is always **true** on iOS and that is why I went for **mixed** (plus the flexibility that it gives you).
So is there any solution to show the notification when the app is killed by the user?
Would a possible solution be to send _alert: {title: 'someTitle', body: 'someBody'}_ in notification's payload on the server, and in client's _didReceiveRemoteNotification_ manipulate somehow the notification, so that if app's state is anything but _inactive_ then remove that _alert_ property, so it will act as a _silent push notification_ ?

**Comment by npomfret** [comment]
I think there's a problem with the user interaction flag, I've heard other complaining.  Though I'm not sure what it's supposed to represent.

In iOS, if the user kills the app then no notifications will be delivered, no matter what.

**Comment by npomfret** [comment]
... my advice, and what has worked well for me is to only send silent notifications, and if you want noisy ones then use a local notification in your app.  If the server can detect that a silent notification hasn't been delivered (after a while) you can assume the app has been killed and send them a noise one.  I think this is the approach that What'sApp takes.

**Comment by chiformihai** [comment]
But the problem is on the server the success callback is called after sending the notification, because it is sent to the device. The phone vibrates, just that the notifications does not appear.

**Comment by noambonnie** [comment]
@npomfret  - Is there anything special that needs to happen for onNotification to be called when the app is not started? I'm trying to create a local notification based on data I get from a silent notification. But on iOS when the app is not running (e.g. after device restart) nothing is being invoked.
