### ISSUE TITLE
onNotification isn't getting called in iOS when app is closed. Everything working great in Android.

### ISSUE THREAD

**Issue by booboothefool** [zo0r/react-native-push-notification#348]
Have push notifications getting to my iPhone, but when I press them, my app just hangs and onNotification never gets called.

On Android, everything working as expected.

Any advice?

**Comment by booboothefool** [comment]
Strange... this is only happening in production for me. Dev works great.

**Comment by antonkulyk** [comment]
Same thing in the dev mode

**Comment by booboothefool** [comment]
This seems to happen under some very specific conditions for me.

I noticed it might have something to do with react-native-router-flux and a drawer. 

By the time I call Actions.drawer() to route to the drawer component, my app freezes up. 

So if I set the Notifications.configure({...}) earlier, I can see the `onNotification` happening, but it freezes when it's time to route. 

Android - works
iOS dev - works
iOS prod without drawer - works
iOS prod with drawer - freezes (where I really need it to work!)

**Comment by yelkamel** [comment]
Same for me, it's work on android but not on iOS, I didn't get the onNotification open.

**Comment by faxioman** [comment]
Same for me

**Comment by faxioman** [comment]
Oopps ... I missed adding the code in appdelegate.m as described here: https://facebook.github.io/react-native/docs/pushnotificationios.html

**Comment by booboothefool** [comment]
I got it working too. My issue is I'm trying to use https://github.com/geektimecoil/react-native-onesignal at the same time, and it was sort of fighting with this library. 

When I moved `react-native-one-signal` out of my `componentDidMount`, and left `react-native-push-notification`, my app stopped locking up, and `onNotification` is being called properly. 

It actually calls OneSignal's `onNotificationOpened` AND this lib's `onNotification`, which is actually fine because I use them for different purposes (this lib = messaging notifications, OneSignal = general notifications).

**Comment by npomfret** [comment]
Can we close this then?

**Comment by faxioman** [comment]
Yes ... @booboothefool?

**Comment by zaidraddad94** [comment]
match this with ur AppDelegate.m 
https://github.com/zo0r/react-native-push-notification/blob/master/example/ios/example/AppDelegate.m
