### ISSUE TITLE
onRegister not being called iOS

### ISSUE THREAD

**Issue by tonyneel923** [zo0r/react-native-push-notification#349]
The permission window pops up by my callback is never hit and I need my token for my push service. Any thoughts? Thanks!

**Comment by tonyneel923** [comment]
Needed to add react native code for pushios in my appdelegate.m

**Comment by RWOverdijk** [comment]
@tonyneel923 Thanks for commenting what was missing for you. I removed it and didn't think to add it again until I read your comment. Thanks :)
