### ISSUE TITLE
the implementation of function didReceiveRemoteNotification:userInfo is missing

### ISSUE THREAD

**Issue by roysG** [zo0r/react-native-push-notification#350]
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler
{
  [RCTPushNotificationManager didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}

**Comment by sbalay** [comment]
Having the same issue here. This is probably an issue for React Native and not this package though

**Comment by npomfret** [comment]
You have to add that function to your `AppDelegate.m`.

**Comment by sbalay** [comment]
The problem in my case is that I was using an old version of react native, and reading the latest docs.
In version 0.37 the code to add to AppDelegate is different: http://facebook.github.io/react-native/releases/0.37/docs/pushnotificationios.html

**Comment by npomfret** [comment]
Can we close this?
