### ISSUE TITLE
Notification appears twice when foreground is false

### ISSUE THREAD

**Issue by Meshz** [zo0r/react-native-push-notification#351]
I am sending remote notifications from my server to an Android app. When the app is in background or killed, and thus notification.foreground is false, the notification appears twice but onNotification only fires once. When the app is opened on device, and thus notification.foreground is true, the notification appears only once and onNotification fires once. Any idea what's going wrong?

Thank you for your help and, ofc, that awesome plugin! 👍

**Comment by Meshz** [comment]
Solved it by not calling localNotification when foreground is false. Also, had to use `sound` instead of `playSound` and `vibration` instead of `vibrate` when sending from server. HTH.

**Comment by adnbsr** [comment]
It does not solve existing problem. No matter what if `foreground` is false, plugin sends a notification to notification center extraly
