### ISSUE TITLE
I cant get Android GCM push to work when app is killed.

### ISSUE THREAD

**Issue by oddball** [zo0r/react-native-push-notification#360]
I cant get Android GCM push to work when app is killed.

It works fine when app is running or in background (except that I dont get the icon to show up in the notification).

I do have something like https://gist.github.com/npomfret/2566cc84ada1a807d201b8146e1fa25e implemented ( if that is needed, is really should be in the README)

Using a file debug_android_gcm_push.py that looks as below
```python
# -*- coding: utf-8 -*-
import argparse
import requests
import json

parser = argparse.ArgumentParser(description='test android GCM react-native-push-notification')
parser.add_argument('--pushToken', dest="pushToken", required=True, help='Push Token to the Android App')
parser.add_argument('--key', dest="GCMKey", required=True, help='Google GCM Key')
args = parser.parse_args()

data = {
    "to": args.pushToken,
    "time_to_live": 86400,
    "collapse_key": "new_message",
    "delay_while_idle": False,
    "notification": {
        "title": "title",
        "body": "this is a noisy test",
        "message": "this is a mixed test 14:03:29.676",
        'icon': 'ic_launcher',
        "color": "#18d821",
        "sound": "default"
    }
}

headers = {
    'Content-Type': 'application/json',
    'Authorization': 'key=' + args.GCMKey
}

url = 'https://gcm-http.googleapis.com/gcm/send'

r = requests.post(url, headers=headers, data=json.dumps(data))
print r.status_code
print r.content
```

When app is running, doing
```
python debug_android_gcm_push.py --pushToken APP_TOKEN --key MY_KEY
adb logcat *:S ReactNative:V ReactNativeJS:V RNPushNotification:V
```
Shows that the notifications arrives.

When app is killed, doing
```
python debug_android_gcm_push.py --pushToken APP_TOKEN --key MY_KEY

```
results in
```
200
{"multicast_id":72807798750713,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:14866614386875f5ea0a28f5ea0a2"}]}
```
and adb logcat shows

```
02-09 18:30:39.114  2553  2553 E FirebaseInstanceId: Failed to resolve target intent service, skipping classname enforcement
02-09 18:30:39.115   915  3631 W ActivityManager: Unable to start service Intent { act=com.google.firebase.MESSAGING_EVENT pkg=com.MYAPP (has extras) } U=0: not found
02-09 18:30:39.115  2553  2553 E FirebaseInstanceId: Error while delivering the message: ServiceIntent not found.
```

Using:
"react-native": "0.41.2",

android/app/build.gradle:
```
    ...
    compile ('com.google.android.gms:play-services-gcm:10.0.1') {
        force = true;
    }
    ...
 ```

Not sure what is wrong, any help would be appreciated.

**Comment by oddball** [comment]
This issue is suffering from demonstration sickness. Just showed it to someone, and it worked?! Closing it for the time being. I may reopen it if it start to behaving deterministically.

**Comment by joaovpmamede** [comment]
@oddball can you confirm this:

> I get two different behaviours when the app is killed.
If I don't click immediately on the notification I don't get the second onNotification with `userInteraction: true` but if do everything works accordingly.
It's as if the notification is lost after some seconds.

Do you get the onNotification after clicking on the "notification center"?
