### ISSUE TITLE
android: RNPushNotification not listed in "NativeModules"

### ISSUE THREAD

**Issue by flaviosbert** [zo0r/react-native-push-notification#361]
Error: undefined is not an object (evaluating RNPushNotification.getInitialNotification)

I'm using android. Tried linking it automatically and manually, Apparently all the instructions on the readme were followed.

Debugging the error, looks like the package RNPushNotification is not contained in NativeModules. If I disable the option for initialNotification, the error appears on other method.

Looks like something is still wrong at the setup, but I can't find it.

**Comment by LeoAref** [comment]
@flaviosbert Did you manage to fix that error? I'm getting it and couldn't figure out what's the problem!

**Comment by flavordaaave** [comment]
I got the same issue (RN 0.42.0, react-native-push-notification@2.2.1).

**Comment by flaviosbert** [comment]
@LeoAref and @flavordaaave  I couldn't get it to work and switched to react-native-fcm.

However I got a suggestion that might work for you, in other issue.

Take a look: https://github.com/zo0r/react-native-push-notification/issues/318
