### ISSUE TITLE
onRegister token null IOS, Android ok

### ISSUE THREAD

**Issue by 2ducanhpham** [zo0r/react-native-push-notification#363]
Platform: IOS, react native v0.40, push notify lastest
onRegister = (token) => {
token is null
}
but used
    PushNotificationIOS.addEventListener('register', this._onRegistered); => token ok

Plese help me!

**Comment by recepkocur** [comment]
try this PushNotificationIOS.addEventListener('register', this._onRegistered.bind(this));

**Comment by recepkocur** [comment]
try this;

...
componentWillMount() {
    PushNotificationIOS.addEventListener('register', this._onRegistered.bind(this));
    PushNotificationIOS.addEventListener('registrationError', this._onRegistrationError.bind(this));
    PushNotificationIOS.addEventListener('notification', this._onRemoteNotification.bind(this));
    PushNotificationIOS.requestPermissions();
  }

  componentWillUnmount() {
    PushNotificationIOS.removeEventListener('register', this._onRegistered.bind(this));
    PushNotificationIOS.removeEventListener('registrationError', this._onRegistrationError.bind(this));
    PushNotificationIOS.removeEventListener('notification', this._onRemoteNotification.bind(this));
  }

  _onRegistered(deviceToken) {
    // deviceToken
  }
...

**Comment by mikhi** [comment]
+1 same for me. Please help!

**Comment by mikhi** [comment]
@zo0r please help us with this issue. I have the same issue described #584 [https://github.com/zo0r/react-native-push-notification/issues/584](url)

Many thanks,
Mihai

**Comment by mikhi** [comment]
@2ducanhpham did you managed to get the token on iOS devices?

**Comment by mikhi** [comment]
Hi @2ducanhpham, thanks for your reply. I have managed to get the token for iOS and Android devices, but I have a little issue: when I run for the first time the application ( after I installed it) the token is null. If I close the app and reopen it again the token is generated.
Any ideas how to deal with this issue? Maybe I have to leasen some event when the token is generated? What’s the best approach in this case?

Many thanks,
Mikhi

**Comment by tonygriv** [comment]
In XCode Capabilities tab you should turn on Push notifications

**Comment by RobertStuff** [comment]
hi good day.. mikhi. how did you manage to get the ios token?

**Comment by mikhi** [comment]
Hi @RobertStuff,
In my case, the aplication requires to be logged in.  That’s being said, when a user logged into the app, I try to generate the token and store it to the Storage (local db), then redirect to other screen using the react Navigation package. If the token is null I redirect the user back to the initial screen, and believe it or not, the token is now generated. 

I hope this will help you

**Comment by RobertStuff** [comment]
Hi @mikhi 
I'll try it later.. thanks with your prompt reply..

**Comment by RobertStuff** [comment]
I don't know for some reason.. I try to login but token is still null and app is not showing any errors.

**Comment by RobertStuff** [comment]
I also have tried PushNotificationIOS but still no luck.

**Comment by mikhi** [comment]
With iOS the whole job is tricky... I have few questions:
1. Do you test in real device
2. Have you configured the push notification service on Apple site? Take a look here:
https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AddingCapabilities/AddingCapabilities.html#//apple_ref/doc/uid/TP40012582-CH26-SW6

**Comment by RobertStuff** [comment]
Yup already do all of that. I guess Reactotron couldn't show the token. Its already working when i do console.log Thanks for your help really appreciate it..

**Comment by muhammadhaseebsohail** [comment]
i am getting this error on Android , 
anyone here can suggest me what i need to do?

this is what i am caliing out 

constructor(props){
......
       PushNotification.configure({

            onRegister: function(token) {
               alert( 'TOKEN:', token );

                AsyncStorage.setItem('DeviceToken', JSON.stringify(token), () => {


                });
            },
....

**Comment by RobertStuff** [comment]
@muhammadhaseebsohail 

What is the error the you are getting?

**Comment by RobertStuff** [comment]
Whenever I install new build the app ask for permission.. Or check you manifest..
