### ISSUE TITLE
App crash when I try to open, Maybe is my AndroidManifest.xml?

### ISSUE THREAD

**Issue by KarlosQ** [zo0r/react-native-push-notification#364]
In the tutorial AndroidManifest.xml the ${applicationId} is the name of my package ?

Example:

`<uses-permission android:name="com.example.permission.C2D_MESSAGE" /> `

instead 

`<uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />`

In build.gradle I try with

 `compile "com.google.android.gms:play-services-gcm:+"`

 and with   
 
```
compile ('com.google.android.gms:play-services-gcm:10.0.1') {
        force = true;
}
```
but the app ever crash with the alert: 'Unfortunately, Example has stopped'.

What am I doing wrong?

**Comment by Deboracgs** [comment]
Yes, change the idapplication for you project name, example 'com.example'

**Comment by igorsantos07** [comment]
This should be obvious in the readme... It only says "copy over this there".

**Comment by KarlosQ** [comment]
Yes, but my app crash because I have a conflict with react-native-maps

**Comment by jukben** [comment]
@KarlosQ I've probably run into the same problem, how did you resolve it, please?
