### ISSUE TITLE
module installation causes compile issues

### ISSUE THREAD

**Issue by vlivanov** [zo0r/react-native-push-notification#369]
/${ProjectPath}/node_modules/react-native-push-notification/android/build/intermediates/exploded-aar/com.facebook.react/react-native/0.40.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.Dialog'.

/${ProjectPath}/node_modules/react-native-push-notification/android/build/intermediates/exploded-aar/com.facebook.react/react-native/0.40.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.Dialog'.

/${ProjectPath}/node_modules/react-native-push-notification/android/build/intermediates/exploded-aar/com.facebook.react/react-native/0.40.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.DialogWhenLarge'.

/${ProjectPath}/node_modules/react-native-push-notification/android/build/intermediates/exploded-aar/com.facebook.react/react-native/0.40.0/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Light.NoActionBar'.

/${ProjectPath}/node_modules/react-native-push-notification/android/build/intermediates/exploded-aar/com.facebook.react/react-native/0.40.0/res/values/values.xml:77:21-36 : No resource found that matches the given name: attr 'windowActionBar'.

MacOS 10.6, React native 0.40, gradle build.

This is actually fixed with the following change to build.gradle of the module:
android {
    compileSdkVersion 24
    ...

   lintOptions {
        abortOnError false
    }
    ...
}

dependencies {
     ...
     compile 'com.android.support:appcompat-v7:24.1.1'
     ...
}

I can submit a PR, but it is apparently 5 minutes fix, if ignore issues with lint.

**Comment by ophite** [comment]
+1
