### ISSUE TITLE
Duplicated notification when using PushNotification.localNotificationSchedule

### ISSUE THREAD

**Issue by xuho** [zo0r/react-native-push-notification#370]
I want to schedule my notifications with specified time, and I'm using localNotificationSchedule method to do this, but when app push notification, it was double push.
Excepted, the "foreground" value dose not working although I set it false.
Here is my code to push notification.
`notifications = this.state.notifications;`
        `var date = new Date(Date.now());`
        `for (var i = 0; i < notifications.length; i++) {`
            `if (notifications[i].isEnable) {`
                `var hour = Number(notifications[i].time.split(':')[0]);`
                `var min = Number(notifications[i].time.split(':')[1]);`
                `date.setHours(hour);`
                `date.setMinutes(min);`
                `date.setSeconds(0);`
                `PushNotification.localNotificationSchedule({`
                    `foreground: false, title: "title here",`
                    `message: "message here",` 
                    `playSound: true, `
                    `soundName: 'sound.wav',`
                    `date: date,`
                    `repeatType: 'day'`
                `});`
           ` }`
       ` }`

**Comment by 2ducanhpham** [comment]
Why is it duplicated?

**Comment by ammichael** [comment]
Why is this closed? I also have this issue, though it doesn't happen to all users. Is there any fix?

**Comment by hannojg** [comment]
Same

**Comment by ViniciusGularte** [comment]
sorry to resurrect this, but i'm having the same problem, did you find a way to solve it?
