### ISSUE TITLE
onNotification method called only when the notification is opened

### ISSUE THREAD

**Issue by lbaiao** [zo0r/react-native-push-notification#373]
When I try to use the onNotification method, its callback function is called only when the notification is opened. I would like to execute the callback when the notification is received. How can I do it?

**Comment by npomfret** [comment]
I think it depends on the type of notification you send.  Have a look at the trouble shooting guide, specifically the bit about "silent" notifications.

**Comment by nonameolsson** [comment]
@lbaiao 
Did you solve this? I need to run some actions on `onNotification` for local notifications. But it's not triggered if I don't press it.

**Comment by nonameolsson** [comment]
Hi! I have the issue as @lbaiao , please check my last comment in #170
