### ISSUE TITLE
Do I need to send the token to GCM before my push servers

### ISSUE THREAD

**Issue by robcalcroft** [zo0r/react-native-push-notification#376]
In the `onRegister` on Android, can I give that token straight to my push servers? Or do I need to send that token to GCM to get a `regid`, I'm confused on the process?

**Comment by robcalcroft** [comment]
@zo0r ?

**Comment by yachaka** [comment]
@robcalcroft You can use that token on the push servers directly.

**Comment by robcalcroft** [comment]
Cool thanks

**Comment by jose2007kj** [comment]
sir @robcalcroft , @yachaka  to impliment push notification from my php server ? is below code right approch?.
```

onRegister: function(token) {
        console.log( 'TOKEN:', token );
        can i send this token to my server
    },
```

**Comment by robcalcroft** [comment]
Yeh you can use that token to send messages to the device form your push servers
