### ISSUE TITLE
how to get payload data from notification object

### ISSUE THREAD

**Issue by adriancuco** [zo0r/react-native-push-notification#377]
Hi,
I am trying to pass a custom parameter (paylod), to remote push notification as follows:
{
"aps":
{
"alert": "News!",
"sound": "default"
"myurl" : "https://raywenderlich.com",
}
}

But when raised   PushNotification.configure at componentDidMount, I am unable to see the data:

componentDidMount() {
    PushNotification.configure({
      onNotification: function(notification) {
    
           console.log(notification.data);
        
       
      },
    });
  }

Please advise

Thanks a lot

React Native version: 0.41
Platform: iOS
Operating System: MacOS

**Comment by jqn** [comment]
Plus one

**Comment by nullpointer07** [comment]
any fixes yet for this?

**Comment by nazywamsiepawel** [comment]
+1

**Comment by Diego-F-Aguirre** [comment]
Any word on this?

**Comment by danilValeev** [comment]
Unfortunately, without this feature the library is unusable(

**Comment by ianpogi5** [comment]
anyone knows why this doesn't work?

**Comment by exAspArk** [comment]
> you need to pass aditional parameter outside of "aps"

Right. However, even in this case, the package returns an empty `data` object.

I suspect that the issue might be in the [react-native-push-notification-ios](https://github.com/react-native-community/react-native-push-notification-ios) package. `PushNotificationIOS.getData` returns `this._data` which is not being filled out for remote notifications:

https://github.com/react-native-community/react-native-push-notification-ios/blob/684c4bb516883dcaf28a75ca49d4ff6a7f27239e/js/index.js#L338-L345
