### ISSUE TITLE
send payload on local notification?

### ISSUE THREAD

**Issue by n06rin** [zo0r/react-native-push-notification#384]
At usage example described 'data' field of notification object: [https://github.com/zo0r/react-native-push-notification#handling-notifications](https://github.com/zo0r/react-native-push-notification#handling-notifications)

But I don't see how to use it with local notifications.
Is there any possibilities to send some data with local notification?

**Comment by Octaner** [comment]
+1 The same problem. How to send some data in local notifications for android and ios?

**Comment by joaovpmamede** [comment]
I have the same problem on Android.
Tried setting the notification like this:

```
onNotification(notification) {
    const { foreground, userInteraction, message, data, ...rest } = notification;
    console.log('NOTIFICATION:', notification);

    if (foreground && !userInteraction) {
       PushNotification.localNotification({ ...rest, data, message });
    }
    ...
}
```

**Comment by yeeegem** [comment]
I have the same problem

**Comment by robcalcroft** [comment]
You can use `userInfo` for iOS

**Comment by AlimovSV** [comment]
@joaovpmamede For some reason `data` in `localNotification` params should be a json string.

**Comment by joaovpmamede** [comment]
@AlimovSV thank you so much. Got this working at last :)

Now I just need to find a way to get the notification object when the app is closed and I click on a notification.
I do get the object when I receive the push notification though.

**Comment by effectivecui** [comment]
send by 
```
PushNotification.localNotification({
    //..........
    data: JSON.stringify({type: 'news', content: 'news one title'})
})
```
Parse by
```
PushNotification.configure({
    onNotification: function(notification) {
        let json = notification.data;
        console.log(json.type);
    },

});
```
