### ISSUE TITLE
[Feature Request] Use UNUserNotificationCenter in iOS 10

### ISSUE THREAD

**Issue by gperdomor** [zo0r/react-native-push-notification#389]
The new UNUserNotificationCenter has a method to remove the notification from the notification center...

Check this `https://developer.apple.com/reference/usernotifications/unusernotificationcenter/1649502-removealldeliverednotifications`

**Comment by rrichardson** [comment]
It would also be good to handle notifications via this delegate method as part of the UNUserNotificationCenter

```
optional func userNotificationCenter(_ center: UNUserNotificationCenter, 
                         willPresent notification: UNNotification, 
               withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void)
```

This delegate method gives the user more control over how to handle a notification when the app is in the foreground.  This would fix https://github.com/zo0r/react-native-push-notification/issues/275
