### ISSUE TITLE
Android onNotification placement

### ISSUE THREAD

**Issue by quangas** [zo0r/react-native-push-notification#390]
Where are you supposed to place this piece of configuration code for onNotification? Where have people been putting this onNotification?

For onRegister, I have placed it after the Login screen, and the token appears to be registering and working fine.

However for onNotification, I have tried to put it in a few locations but none seem to work. I register the device token, and when I publish a notification to the device, nothing happens.

**Comment by quangas** [comment]
Ended up putting it in the index.android.js

**Comment by iiitmahesh** [comment]
@quangas Can U share your piece of code..!

**Comment by hanishs17** [comment]
https://github.com/zo0r/react-native-push-notification/issues/445

Please Help me in this issue.
thanks
