### ISSUE TITLE
Notification not showing while app is open

### ISSUE THREAD

**Issue by avishayil** [zo0r/react-native-push-notification#4]
I noticed that no notification is being shown when the app is open.
I'm working on Android so I don't know yet about iPhone.
How can I change this?
Thanks!

**Comment by zo0r** [comment]
By default if the app is open no notification is shown.

You can use `onNotification` to get the received notification, check `foreground` for `true` (to prevent duplicated notifications) and show it using `PushNotification.localNotification(details: Object)`.

**Comment by avishayil** [comment]
Working, thanks.

**Comment by rochapablo** [comment]
I'm following what @zo0r said, but nothing it's been shown.

**Comment by hugomosh** [comment]
Yes, not working anymore. I do `PushNotification.localNotification` and it loops. Not sure how to send a parameter to avoid the eternal loop. But not showing either way, until I close the app I get one notification.

**Comment by khrizt** [comment]
It works for me. No eternal loop.

**Comment by zedtux** [comment]
`PushNotification.localNotification` is not showing notification while in the app, like @rochapablo. This bug is present since at least year, based on the comments age, what could we do @zo0r ?

**Comment by olgaababic** [comment]
The bug is still present

**Comment by MarioGPortilla** [comment]
Same for me, bug still happening

**Comment by Dallas62** [comment]
You must create a channel.
Regards
