### ISSUE TITLE
Local Notification does appear when app is in foreground.

### ISSUE THREAD

**Issue by imbudhiraja** [zo0r/react-native-push-notification#400]
Hi Guys ! 
I'm having a issue with local notifications when app is in foreground. 
In foreground local notification does appear but when i go to background same notification comes.
Plz help me with this issue.

**Comment by npomfret** [comment]
I understand that's correct behaviour, they don't appear if your app is in the foreground.

**Comment by atebit** [comment]
In terms of UX, why would you want it to?

**Comment by reimertz** [comment]
@atebit I think it makes sense for Apple to require app makers to visualize changes within the app.

Probably because apple wants notifications to be strictly exclusive from the app you are currently using. If you see a notification, you'd know it's something external happening. 

💵 My two cents 💵

**Comment by atebit** [comment]
@reimertz, you explained my point even more. Sorry, my comment was a bit rhetorical I suppose.

This is the intended functionality.

**Comment by imbudhiraja** [comment]
@reimertz @atebit @npomfret thanks. But can we do this as these are my application needs?

**Comment by dandelany** [comment]
I agree that the intended behaviour should be to *not display* a notification when your app is in the foreground. However, I think that at the very least, the `onNotification` callback *should* be fired when the app is in the foreground, even though a notification is not displayed (currently it does not fire). This is how the competing library wix/react-native-notifications handles things.

Example use case: Let's say you want to remind a user to open your app and do something every ~X days. An easy way to do this is to initially use `localNotificationSchedule` to schedule a notification for X days from now, and then schedule a new one inside your `onNotification` callback. This way, the user gets reminded in the future, and the act of opening the notification schedules the next one. However, if the app happens to be in the foreground at the time, the callback won't be called, and the next one won't be scheduled. The only way I can think to schedule it is to have a timer or an `AppState` callback which checks some internal state to see if the last notification time is in the past, and schedules a new one if so - this is kind of messy and would be much simpler if the same callback just fired in either case (foreground or background). Firing the callback *also* gives users the opportunity to display an `alert` or something in foreground mode if they really need to.

**Comment by lucask42** [comment]
I'm using scheduled, repeating local notifications and in my case I want to suppress the pop up of the notification without cancelling subsequent notifications.  It'd be ok if `onNotification` still fired automatically as long as `notification.foreground` works - it is currently always false for me.

onNotification only fires when the user presses on a notification.

**Comment by wmlutz** [comment]
I'm running into the same problem and have a case for why the UX makes sense.

Inside of my app is an inbox/chat function and a calendar/schedule. If the user has the app open (foreground) and is looking at their calendar when they receive an incoming chat message, I'd like them to see that notification. Similar to getting a text message from one person when your current view is texting with someone else.

**Comment by tarvainentero** [comment]
Is this still the same in newer versions? If app is in foreground when a scheduled local notification fires then callback func "onNotification(notification)" does not get called?
