### ISSUE TITLE
PushNotification.localNotificationSchedule isn't working on Android

### ISSUE THREAD

**Issue by dfoverdx** [zo0r/react-native-push-notification#407]
I'm running the following:

        PushNotification.configure({
            permissions: {
                alert: true,
                badge: true,
                sound: true
            },
            popInitialNotification: true,
            onNotification: function(notification) {
                console.log( 'NOTIFICATION:', notification );
            },
        });

    // ...

        var message = "foo";
        PushNotification.localNotificationSchedule({
            message: message,
            date: new Date(Date.now() + (60 * 1000)),
        });

I've confirmed that `date` is correct.  I've debugged into the java code in react-native-push-notification to confirm that the date received in java is correct.  In `sendNotificationScheduledCore()`, `getAlarmManager().setExact(...)` doesn't seem to be doing what it's supposed to.

Local notifications that aren't scheduled work fine.

**Comment by diegocouto** [comment]
Hi, @dfoverdx!

Have you updated your `AndroidManifest.xml` as [stated here](https://github.com/zo0r/react-native-push-notification#android-manual-installation)? 

I'd also recommend you take a look on #355, there are some links with demo repos which might help you. 😄

**Comment by MattyK14** [comment]
Works fine for me setting it a minute from the current time

**Comment by dfoverdx** [comment]
@diegocouto Ah, updating the manifest is probably my issue (can't check right now because the rest of my project is completely b0rked on Android).  I had thought `react-native link` took care of all of that.  Thanks!

**Comment by lukewlms** [comment]
Recommend closing this as OP's problem is likely solved just with the current docs.
