### ISSUE TITLE
Can i use this library for fcm instead of gcm ?

### ISSUE THREAD

**Issue by phanngoc** [zo0r/react-native-push-notification#409]

**Comment by MattyK14** [comment]
+1

**Comment by chadwilken** [comment]
We hit this as well, I had to do a few things. First I had to go to the Google Play Console, select the app and then go to Services and APIs under development tools. You will see Firebase Cloud Messaging (FCM) with an option to Link Sender ID. Click this and put in the sender ID from your Firebase settings. Then you have to make sure to use the format
```
{
"GCM": "{ \"notification\": { \"text\": \"test message\" } }"
}
```
Credit for the format goes to [this guy](http://stackoverflow.com/a/38626398/531479). This fixed it for our app.

**Comment by dinithminura** [comment]
I have used FCM instead of GCM with this library for android app. It was success for app in foreground and background state, but not in app kill state. Any idea about the app kill state with FCM ?

**Comment by urska19** [comment]
I managed to do it with FCM. I followed the instructions as they are and instead of GCM keys I put in FCM keys and that was it.

**Comment by waterdoo** [comment]
@urska19 in app/build.gradle, did you import what the default instructions say,

compile ('com.google.android.gms:play-services-gcm:8.1.0') {
      force = true;
}

Or did you change it to use a firebase cloud messaging package?

**Comment by urska19** [comment]
@waterdoo yes, I imported what the instruction said and just changed the version, so that it matched to the version of `play-services-maps` that I already had. This is what I have
`compile 'com.google.android.gms:play-services-gcm:10.0.1'`

**Comment by L3V147H4N** [comment]
I followed both instructions in this repo and in the FCM docs and still nothing, I think I'm missing something but don't what or how to test what's wrong

Did you also followed the instructions from FCM, adding `com.google.gms.google-services` ??

**Comment by L3V147H4N** [comment]
I tried https://pushtry.com/ and both notifications work but the one from FCM doesn't trigger the `onNotification`, not when received nor when opened, the one from GCM works fine

**Comment by urska19** [comment]
@L3V147H4N In function `PushNotification.configure` instead of `"YOUR GCM SENDER ID"` I put sender Id from FCM project. Everything else is as written in `Android manual Installation`, except version of `com.google.android.gms:play-services-gcm:11.0.2`, which is the same as other `play-services` services that I use. 
I hope this helps.

**Comment by L3V147H4N** [comment]
@urska19 thanks for the reply, I already turn to [react-native-fcm](https://github.com/evollu/react-native-fcm) and it's seems to be working fine
