### ISSUE TITLE
Resuming android application from background.

### ISSUE THREAD

**Issue by Lastin** [zo0r/react-native-push-notification#412]
Hey, I hope it's not duplicate, but I couldn't find the issue similar to mine.

The app starts from "scratch" when opening notification when app is in the background.
I just want the notification to just focus the app from background.

**Current behaviour:**
Start App > Home Screen > Login Screen > Target view.

**Intended behaviour:** 
Focus app > Target view.

Thank you :)

**Comment by reyalpsirc** [comment]
Any news on this?

**Comment by Lastin** [comment]
I have switched from this package to https://github.com/wix/react-native-notifications.
This package seems to be not maintained for quite a while.
If you choose to do the same, be prepared that there may be some notification behavioural differences (way it opens, discards other notifications etc.) betweeb the packages.

But you can search my issues, there should be information how to overcome those differences and get identical behaviour with a small facade. Or just ask me if you run into any trouble, I will try and help.

**Comment by reyalpsirc** [comment]
Thanks, I did the same recently and it worked as expected after the change for me (and after following the needed extra changes for Android because of the Title and Description not appearing on the notification).
