### ISSUE TITLE
onNotification method can't trig

### ISSUE THREAD

**Issue by ronniesir** [zo0r/react-native-push-notification#413]
PushNotification.localNotification({
                /* Android Only Properties */
                id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
                autoCancel: true, // (optional) default: true

                /* iOS and Android properties */
                title: notificationTitle,
                message: notificationText, // (required)
                actions: '["check"]',  // (Android only) See the doc for notification actions to know more
                data: data,
            });
  PushNotification.configure({

        // (optional) Called when Token is generated (iOS and Android)
        onRegister: function (token) {
            alert('TOKEN:', token);
        },

        // (required) Called when a remote or local notification is opened or received
        onNotification: function (notification) {
            alert(11)
        },

        // ANDROID ONLY: GCM Sender ID (optional - not required for local notifications, but is need to receive remote push notifications)
        senderID: "YOUR GCM SENDER ID",

        permissions: {
            alert: true,
            badge: true,
            sound: true
        },
        popInitialNotification: false,

        /**
         * (optional) default: true
         * - Specified if permissions (ios) and token (android and ios) will requested or not,
         * - if not, you must call PushNotificationsHandler.requestPermissions() later
         */
        requestPermissions: true,
    });

**Comment by mobinni** [comment]
I have the same problem

**Comment by mobinni** [comment]
update: I fixed this by adding the right methods to my app delegate from the facebook tutorial

**Comment by sagark1510** [comment]
@mobinni can you paste the code or reference link here?

**Comment by lulzimfazlija** [comment]
has anyone being able to make it working on Android the push notification with this library? onNotification is never called for me, I am using Firebase FCM and wrapping into ComponentDidMount all the code, onRegister is fired can get token but never able to receive push notification from remote, firebase!

Pls if you could post some code referenceS!

**Comment by karlmosenbacher** [comment]
@lulzimfazlija have you solved it?
