### ISSUE TITLE
What is popInitialNotification for?

### ISSUE THREAD

**Issue by cstoddart** [zo0r/react-native-push-notification#416]
This line in the documentation is very confusing. I don't know what it means to 'pop' a notification, and the comments are not helpful.

  `// Should the initial notification be popped automatically
    // default: true
    popInitialNotification: true,`

What is this for? My best guess is that setting popInitialNotification to true would result in missing the first notification, but I don't see why that would be the default.

**Comment by Kim-Andersen** [comment]
+1

**Comment by RWOverdijk** [comment]
@cstoddart It's when your app starts. It "pops" it so your onNotification handler gets called. This confused me too, initially. Turns out this is what you want when recovering your app.
