### ISSUE TITLE
Use along other SDKs

### ISSUE THREAD

**Issue by jsdario** [zo0r/react-native-push-notification#417]
Hi,

I have recently added Intercom's Android sdk with this one. It works just fine, except that the notification appears twice in the tray. Is there a way to prevent one (this module) or the other (intercom's sdk) from populating a notification?

Thanks in advance

**Comment by jaimecorrea** [comment]
Same issue here, any news or workaround about this?

**Comment by Blurzschyter** [comment]
Same issues with me also. I used this library to do local notification and react-native-onesignal library for push notification. When I sent push notification message, my android device display the notification twice. Appreciate if anybody can help us with this issues.

**Comment by ChrisKipers** [comment]
I think this might be fixed now. I'm using Rn:0.58.6, react-native-push-notification:3.1.3 and react-native-onesignal:3.2.14 and haven't had this issue.
