### ISSUE TITLE
update notification message and subText 

### ISSUE THREAD

**Issue by haroonob** [zo0r/react-native-push-notification#418]
Good day 
Is there any way to update existing notification message. I want to  show download progress in push notification

**Comment by haroonob** [comment]
Please reply

**Comment by npomfret** [comment]
I don't believe that's supported.  You could try resending it with the same id maybe?  Otherwise you'd have to remove the existing notification and replace it with a new one.

**Comment by varungupta85** [comment]
@haroonob You may want to check out the ongoing notifications at least for Android for showing download progress. You may or may not need to add some extra support to the package for it to work properly.

https://unitid.nl/androidpatterns/uap_pattern/status-bar-ongoing-notifications
https://developer.android.com/reference/android/app/Notification.Builder.html#setOngoing(boolean)

HTH

**Comment by tokland** [comment]
@npomfret Cancelling a notification and sending the updated one is not practical, visually is very noticeable. On the other hand, using the same ID as you proposed worked for me (Android), thanks.

**Comment by aftabaminzoobiapps** [comment]
Hello I want to update notification state update.
