### ISSUE TITLE
How can I use Parse

### ISSUE THREAD

**Issue by hamidhadi** [zo0r/react-native-push-notification#419]
How can I integrate my project with Parse?

**Comment by iSamuelBarney** [comment]
Yes, please any help with parseplat would be awesome, any guides or info of anyone doing parse with this push plugin would be epic.

**Comment by iSamuelBarney** [comment]
@hamidhadi I got this working with the rest API but I'm sure if your using the SDK it's far easier.. if you want the details on how I did this with the rest API just let me know

**Comment by Angelk90** [comment]
@iSamuelBarney: Have you used parse + react-native-push-notification on android?
If so, can I ask you how did you do it?

**Comment by hamidhadi** [comment]
@iSamuelBarney @Angelk90 
Finally, I used [OneSignal](https://onesignal.com) for my project.
If you want to use parse you can find some information [here](http://docs.parseplatform.org/js/guide/).
