### ISSUE TITLE
[Android] Cancel remote notifications

### ISSUE THREAD

**Issue by jvsiren** [zo0r/react-native-push-notification#42]
Is it possible to somehow clear or dismiss remote notifications for android? PushNotification.cancelAllLocalNotifications() seems to only cancels the local notifications, not the ones from server.

**Comment by PeterKow** [comment]
what about calling `unregister `?

https://github.com/zo0r/react-native-push-notification/blob/5b80fe4ed5669696c0147c2d8b24955ada067923/index.js#L94

**Comment by jvsiren** [comment]
Actually it was fixed by PushNotification.cancelAllLocalNotifications(). I had forgot to call it when app is opened for first time (only called it when AppState becomes active, i.e. opening app from background). My mistake.

**Comment by AdamLee321** [comment]
Did cancelAllLocalNotifications() clear your remote notifications in Android?
