### ISSUE TITLE
Android: Scheduling local notifications for today alerts many at the same time

### ISSUE THREAD

**Issue by austin-sprawls** [zo0r/react-native-push-notification#422]
Whenever I schedule multiple local notifications for today's date on Android, anytime a notification comes through, so do all other notifications that were scheduled before that time.

For example, let's say I schedule local notifications for today at 10am, 12pm and 3pm. If the time that I scheduled them was 11:45am, then the notification that triggers at 12pm also triggers the 10am notification at the same time.

This doesn't happen if I schedule the notifications for tomorrow or any other days in advance.

**Comment by mitesh-mutha** [comment]
@austin-sprawls Reading about the issue, I guess there is some problem with having scheduled a notification at a time in the past. Maybe you can avoid scheduling a past notification and see if that helps for now.

**Comment by ithustle** [comment]
Anythings?
