### ISSUE TITLE
What is the ticker prop of localNotification()?

### ISSUE THREAD

**Issue by jomla97** [zo0r/react-native-push-notification#423]
I'm looking for a task that will be run, like setInterval, but in the background. If the ticker prop is not what I'm looking for, I'm wondering does the notification content update if it uses a state that is being changed in the background?

**Comment by nonameolsson** [comment]
Did you figure this out?

**Comment by jomla97** [comment]
@nonameolsson Unfortunately not. I was making a stopwatch sort of thing and wanted the time to be displayed live in the ongoing notification. But since this wasn't critical to the functionality I gave up on it. I'd be happy to hear of a solution if you find one.
