### ISSUE TITLE
PushNotificationIOS docs ios 10 deprecations

### ISSUE THREAD

**Issue by kyangy** [zo0r/react-native-push-notification#424]
Unfortunately, the docs on https://facebook.github.io/react-native/docs/pushnotificationios.html#content is throwing warnings saying UIUserNotificationSettings/UILocalNotification is deprecated in ios 10 and to use UNNotificationSettings. What is the correct setup in AppDelegate.m for push notifications to work with ios 10 without any warnings?

**Comment by saudpunjwani101** [comment]
yeah how did u setup?

**Comment by jtibbertsma** [comment]
How is there no answer to this question anywhere on the internet? Nobody implemented push notifications with react-native in the past year?

**Comment by msluther** [comment]
Has anyone gotten this to work without warnings?
In addition, is there path forward for `react-native-push-notification` as it seems like `PushNotificationIOS` will get removed/deprecated from react-native (https://docs.google.com/spreadsheets/d/18xkWNZ7E9LgDoVfFO91_vIjWVwLOYWASsGE8Ng12nX8/edit#gid=0)

**Comment by dmackinn** [comment]
@msluther Looks like there a recommendation to move PushNotificationIOS into this repo:
https://github.com/zo0r/react-native-push-notification/issues/914

I personally would love to see this happen if @zo0r agrees to it.
