### ISSUE TITLE
JSON value '<null>' of type NSNull cannot be converted to NSNumber

### ISSUE THREAD

**Issue by a-koka** [zo0r/react-native-push-notification#426]
Setting a scheduled notification works fine the first time. To update notification time, I'm using the following snippet and it fails with the error shown in the screenshot.

```
    PushNotification.cancelAllLocalNotifications()
    PushNotification.localNotificationSchedule({
      message: 'My notification message.',
      date,
      repeatType: 'day'
    });
```

PS. I'm using the `master` branch.

![image](https://cloud.githubusercontent.com/assets/16167317/25603454/cb73e0fe-2eb0-11e7-818b-9fd4c802b6ff.png)

**Comment by Jude229** [comment]
[Hello @a-koka check this](https://github.com/zo0r/react-native-push-notification/pull/310#issuecomment-299783743)

I make it short in your notification options add ```number : anyNumberYouWantIGuess```

**Comment by Jude229** [comment]
@razerduy 
Hello, sorry I have no idea 😅  and no working project right now to try things. But I got one question, do you really want to use the badge number ? If you don't it seems that it was made optional on the master... If you do, please let me know when you find the solution 😄

**Comment by razerduy** [comment]
@Jude229 
I means how to clear number when app re-actived. Because when i re-active app, the number of icon still show. Maybe i have to find other lib.... :))

**Comment by a-koka** [comment]
Although the badge number is documented as optional, it is indeed needed. The documentation also says that it needs to be a non-zero number represented as a string but using 0 works well for me. No issues with badges showing up when using 0.

Regarding an old badge showing up, they do offer `PushNotification.setApplicationIconBadgeNumber(number: number)` which I haven't tried yet. I had to reset my simulator to get rid of the badge. Uninstalling and re-installing the app didn't help.

Authors, do we need a PR to update documentation around this?

**Comment by pigflymoon** [comment]
I came into this issue too and tried to debug it and found that /node_modules/react-native-push-notification/index.js 
`const iosDetails = {
			fireDate: details.date.toISOString(),
			alertBody: details.message,
			soundName: soundName,
			applicationIconBadgeNumber: parseInt(details.number, 10),
			userInfo: details.userInfo,
			repeatInterval: details.repeatType
		}`
so in my js I didn't set number for local notification
` PushNotification.localNotificationSchedule({
                message: "My Notification Message",
                date: date,

            });`
so when code execute `parseInt(undefined, 10),` it will cause an error so I guess that's why finally come out this issue. 
Then I tried to add a line of code to check number value as this:
`	
          if(!details.number){
			details.number = 0;
		}

		const iosDetails = {
			fireDate: details.date.toISOString(),
			alertBody: details.message,
			soundName: soundName,
			applicationIconBadgeNumber: parseInt(details.number, 10),
			userInfo: details.userInfo,
			repeatInterval: details.repeatType
		}
`
Then solve this issue.
So please have a look if my tips is all  right. Thanks @zo0r

**Comment by GantMan** [comment]
setting number fixed a bug I had in production builds (did not break in local builds)

**Comment by tanyajajodia** [comment]
@razerduy @a-koka 
I tried `PushNotification.setApplicationIconBadgeNumber(number)` to clear out the old badge number and it worked fine.

**Comment by anjanaNewput** [comment]
I am having the same issue, none of the work around working for me. I am able to receive schedule notification but still get the error  JSON value '<null>' of type NSNull cannot be converted to NSNumber
Please help me.

**Comment by sahilpatel16** [comment]
Notifications are only showing up when the app is in background. That's why local instant notifications are not working.

**Comment by Dallas62** [comment]
I fixed the README and example application.
