### ISSUE TITLE
unable to link to ios with "react-native link"

### ISSUE THREAD

**Issue by u-kan** [zo0r/react-native-push-notification#428]
## environment

react-native: 0.43
react-native-push-ntofication: 2.2.1
xcode 8.3.2

## what I did

I  run ```react-native link``` and it successfully link to android but not to ios accrodgin to log.

```

➜  client git:(master) ✗ react-native link react-native-push-notification

^[Scanning 718 folders for symlinks in /Users/kanuchi34/Projects/onocolo/client/node_modules (5ms)
rnpm-install info Android module react-native-push-notification is already linked

```

Is this expected behavior?

**Comment by cfs5403** [comment]
Got the same problem. 
`rnpm-install info Linking react-native-push-notification android dependency 
rnpm-install info Android module react-native-push-notification has been successfully linked 

`

**Comment by npomfret** [comment]
What's in your package.json?

**Comment by cfs5403** [comment]
`{
  "name": "TestApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "prop-types": "^15.5.8",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-native-busy-indicator": "^1.1.0",
    "react-native-button": "^1.8.2",
    "react-native-checkbox": "^1.1.0",
    "react-native-datepicker": "^1.4.7",
    "react-native-experimental-navigation": "^0.26.10",
    "react-native-material-design-searchbar": "^1.1.2",
    "react-native-push-notification": "^3.0.0",
    "react-native-router-flux": "3.38.0",
    "react-native-segmented-control-tab": "^3.0.1",
    "react-native-vector-icons": "^4.0.1",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-logger": "^3.0.1",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "16.0.0-alpha.6",
    "remote-redux-devtools": "^0.5.7"
  },
  "jest": {
    "preset": "react-native"
  }
}`

**Comment by KanUchida** [comment]
thanks for reply!!

this is my package.json

```
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "axios": "^0.15.2",
    "immutable": "^3.8.1",
    "moment": "^2.17.0",
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.3",
    "react-native-android-keyboard-adjust": "^0.1.4",
    "react-native-camera": "0.8.0",
    "react-native-check-box": "^1.0.4",
    "react-native-collapsible": "^0.8.0",
    "react-native-datepicker": "^1.4.5",
    "react-native-fbsdk": "^0.5.0",
    "react-native-fetch-blob": "^0.10.2",
    "react-native-fs": "^2.3.2",
    "react-native-geocoder": "^0.4.8",
    "react-native-image-picker": "^0.26.3",
    "react-native-image-progress": "^0.6.0",
    "react-native-keyboard-aware-scroll-view": "^0.2.8",
    "react-native-keyboard-spacer": "^0.3.1",
    "react-native-map": "0.0.1",
    "react-native-maps": "^0.13.0",
    "react-native-media-editor": "https://github.com/KanUchida/rn-mediaeditor.git",
    "react-native-modalbox": "^1.3.9",
    "react-native-orientation": "git+https://github.com/yamill/react-native-orientation.git",
    "react-native-photo-view": "^1.2.0",
    "react-native-progress": "^3.2.0",
    "react-native-push-notification": "^2.2.1",
    "react-native-router-flux": "3.38.0",
    "react-native-scrollable-tab-view": "^0.7.0",
    "react-native-swiper": "^1.5.4",
    "react-native-twitter": "^0.1.0",
    "react-native-vector-icons": "^4.0.0",
    "react-native-video": "^1.0.0",
    "react-redux": "^4.4.6",
    "redux": "^3.6.0",
    "redux-actions": "^1.1.0",
    "redux-form": "^6.4.3",
    "redux-logger": "^2.7.4",
    "redux-persist": "^4.0.0-beta1",
    "redux-saga": "^0.13.0",
    "tcomb-form-native": "^0.6.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "devDependencies": {
    "babel-jest": "17.0.2",
    "babel-preset-react-native": "1.9.0",
    "eslint": "^3.11.1",
    "eslint-config-airbnb": "^13.0.0",
    "eslint-config-rallycoding": "^3.1.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^6.8.0",
    "eslint-plugin-react-native": "^2.2.0",
    "jest": "17.0.3",
    "react-test-renderer": "15.4.1",
    "remote-redux-devtools": "^0.5.4"
  }
}
```

**Comment by waterdoo** [comment]
+1, I'm on RN 0.39.2

**Comment by ftcvlad** [comment]
same

react-native: 0.47
react-native-push-ntofication: 3.0.0
xcode 8.3.3

**Comment by anzhehong** [comment]
So what's the conclusion for linking ios module?
