### ISSUE TITLE
IOS notification press event

### ISSUE THREAD

**Issue by korkinet** [zo0r/react-native-push-notification#43]
I am sorry as this is less an issue as a cry for help :)
in android I have the 'sysNotificationClick' I can listen to, is there an equivalent one for IOS?
I need to open my app on specific pages according to the notifications I receive. and I am a bit dumbfounded as to how to do it...

thanks.

**Comment by zo0r** [comment]
Use `onNotification` to handle both iOS and Android press event also checking for `foreground`.

**Comment by datalin** [comment]
@zo0r I am failing to understand how to use onNotification and foreground check to detect if it is a click or not, will you please elaborate.

**Comment by datalin** [comment]
Okk, i think i figured it out, thanks for the tips.
