### ISSUE TITLE
Local notifications not working

### ISSUE THREAD

**Issue by RWOverdijk** [zo0r/react-native-push-notification#430]
I'm testing on iOS. Using the code from the example:

```js
PushNotification.localNotification({
  ticker : "My Notification Ticker", // (optional)
  bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
  subText: "This is a subText", // (optional) default: none
  message: "My Notification Message", // (required)
});
```

onNotification does get called, but there's not banner. I'm trying to recreate the whatsapp effect, where messages from a different chat from the one you're looking at cause a local push notification.

**Comment by syardumi** [comment]
The local notification only causes onNotification to fire. On iOS, you'll have to create the alert yourself using RN's Alert API and the values from the notification object you specified above.

**Comment by RWOverdijk** [comment]
Someone replied to this issue, but now the comment is gone? It was a good answer:

> The local notification only causes onNotification to fire. On iOS, you'll have to create the alert yourself using RN's Alert API and the values from the notification object you specified above.

That's good information. I'm looking into using this: https://github.com/testshallpass/react-native-dropdownalert :)

Alerts are cool, but banners are cooler :D Thanks @syardumi
