### ISSUE TITLE
Crash on Android -  FATAL EXCEPTION: main ...  java.lang.ClassCastException: com.mybundle.MainApplication cannot be cast to com.facebook.react.ReactApplication

### ISSUE THREAD

**Issue by voyage11** [zo0r/react-native-push-notification#432]
The library works fine on iOS but it crashed on Android.

 V/RNPushNotification: onMessageReceived: Bundle[{scheme=app.scheme, badge=1, notification=Bundle[{body=this is a push notification message., title=Push Notification Title}], collapse_key=com.mybundle}]

05-15 12:45:46.667 31469-31469/com.mybundle E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.mybundle, PID: 31469
                                                                           java.lang.ClassCastException: com.mybundle.MainApplication cannot be cast to com.facebook.react.ReactApplication
                                                                               at com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService$1.run(RNPushNotificationListenerService.java:59)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5437)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by r1cebank** [comment]
I am having the same issue, i am not a very experienced android developer. Any help is appreciated.

**Comment by npomfret** [comment]
You class `com.mybundle.MainApplication` isn't of the right type.  Not sure how that's possible.  Can you pass the code here?

**Comment by voyage11** [comment]
I am using https://expo.io/ and Detaching to ExpoKit since I would need to use some native libraries for iOS and Android.  It crashed at this line

`ReactInstanceManager mReactInstanceManager = ((ReactApplication) getApplication()).getReactNativeHost().getReactInstanceManager();
`

in RNPushNotificationListenerService.java

Another issue that might be related: https://github.com/zo0r/react-native-push-notification/issues/260
mentioned the `getReactInstanceManager()`

I have been trying to fix the issue myself for at least 3 days (with trials and errors) before I posted the issue. I am not Android developer. 

Hope that someone would be able to lead me to the right direction to fix the crash.

**Comment by voyage11** [comment]
This is my MainApplication.Java

```
package com. mybundle;

import android.support.multidex.MultiDexApplication;

import com.facebook.react.ReactPackage;
import com.react.rnspinkit.RNSpinkitPackage;
import com.horcrux.svg.RNSvgPackage;
import com.imagepicker.ImagePickerPackage;
import com.oblador.keychain.KeychainPackage;
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
import io.branch.rnbranch.*;
import io.branch.referral.Branch;
import com.kevinejohn.RNMixpanel.*;
import com.aakashns.reactnativedialogs.ReactNativeDialogsPackage;

import java.util.Arrays;
import java.util.List;

// Needed for `react-native link`
// import com.facebook.react.ReactApplication;

public class MainApplication extends MultiDexApplication {

  // Needed for `react-native link`
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // Add your own packages here!
        // TODO: add cool native modules

        // Needed for `react-native link`
        // new MainReactPackage()
        new RNBranchPackage(),
        new RNSpinkitPackage(),
        new RNSvgPackage(),
        new ImagePickerPackage(),
        new KeychainPackage(),
        new ReactNativePushNotificationPackage(),
        new RNMixpanel(),
        new ReactNativeDialogsPackage()
    );
  }

  @Override
  public void onCreate() {
      super.onCreate();
      // initialize the Branch object
      Branch.getAutoInstance(this);
  }

}

```

**Comment by npomfret** [comment]
You `MainApplication` is not correct.  If you create a new react native project (with `react-native init AwesomeProject`) you'll see what it *should* look like.  Basically you need to implement `ReactApplication`, the `getPackages` method need to be moved inside an anonymous inner `ReactNativeHost`:

```
public class MainApplication extends MultiDexApplication implements ReactApplication {

...

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
                    ... you dependencies go here
            );
        }
    };

```

**Comment by r1cebank** [comment]
Here is mine, it is already using ReactApplication, it still giving me the same issue
```java
public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new RNSpinkitPackage(),
           new MainReactPackage(),
            new RNSharePackage(),
            new RNViewShotPackage(),
            new RNGeocoderPackage(),
            new LinearGradientPackage(),
            new ImagePickerPackage(),
            new PickerPackage(),
            new ReactNativePushNotificationPackage(),
            new RNDeviceInfo(),
            new ReactVideoPackage(),
            new VectorIconsPackage(),
            new RNSpinkitPackage(),
            new ReactNativeI18n(),
            new GoogleAnalyticsBridgePackage(),
            new RCTCameraPackage()
      );
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}
```

**Comment by voyage11** [comment]
I honestly don't know if my implementation is correct or otherwise. I have tried the implementation like

`public class MainApplication extends MultiDexApplication implements ReactApplication
`
with 

`new MainReactPackage(),`

the android app couldn't even run. 

At least with the implementation that I showed above, it could run. I can login using the app and do other stuff with the app. I could even receive the push notification via `onMessageReceived` but it crashed afterwards.

The above implementation I used is following: 
https://github.com/expo/expo/blob/master/exponent-view-template/android/app/src/main/java/detach/app/template/pkg/name/MainApplication.java

for the detached expo app.

**Comment by voyage11** [comment]
@r1cebank Are you using expo as well?

**Comment by npomfret** [comment]
@r1cebank you cannot be getting the same error as @voyage11 - maybe submit a new issue with your won stack trace

**Comment by r1cebank** [comment]
@voyage11 I am not using expo, i used react-native init @npomfret i am currently check to see if the crashing is caused by other causes, if i find anything i will create a new issue. Thanks

**Comment by voyage11** [comment]
I just posted an issue on the expo repository. Hope that someone knows something about this crash.

**Comment by r1cebank** [comment]
@voyage11 my crash is caused by something else. thanks for the help

**Comment by voyage11** [comment]
For anyone who has the similar crash. Check out version 2.1.1  instead of the latest version. V 2.1.1 will not crash your app.

Personally, I forked the repo, checked out the commit related to V 2.1.1, created a branch and made a small change for my own project, you may see here: https://github.com/voyage11/react-native-push-notification/tree/fixAndroidCrash

**Comment by gchenz47** [comment]
I am using Expo detached and trying to implement the react-native-push-notification in both android and ios. I got the same issue on android which crashing my app once received remote notification from firebase with error: 
`java.lang.ClassCastException: com.myapp.MainApplication cannot be cast to com.facebook.react.ReactApplication`
I am not an expert in Java, but I got it working by modifying the android java code in MainApplication, here is my code:


```
package host.exp.exponent;


import com.facebook.react.ReactPackage;

import java.util.Arrays;
import java.util.List;

import expolib_v1.okhttp3.OkHttpClient;

// Needed for `react-native link`
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactApplication;
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;
import com.dooboolab.RNIap.RNIapPackage;

public class MainApplication extends ExpoApplication implements ReactApplication{

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }


  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
            new ReactNativePushNotificationPackage(),
            new RNIapPackage()
    );
  }
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
              new ReactNativePushNotificationPackage(),
              new RNIapPackage()
      );
    }
  };
  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }


  @Override
  public String gcmSenderId() {
    return getString(R.string.gcm_defaultSenderId);
  }

  @Override
  public boolean shouldUseInternetKernel() {
    return BuildVariantConstants.USE_INTERNET_KERNEL;
  }

  public static OkHttpClient.Builder okHttpClientBuilder(OkHttpClient.Builder builder) {
    // Customize/override OkHttp client here
    return builder;
  }
}
```

Now i can receive remote notification from firebase.

**Comment by KthProg** [comment]
I did the above and it fixed the crashes, however when I get a notification the app just goes to the main view instead of going through my handler.

**Comment by boliveira** [comment]
This is wrong... It shouldn't rely on the Application class implementing ReactApplication interface...
In react native, you are not required to implement ReactApplication interface on the Application class. You can just create a ReactRootView and a ReactInstanceManager independently.
This assumption is wrong...

**Comment by KthProg** [comment]
You need to look into how Expo is generating the application then. It has its own tool and syntax for detaching the project. I don't think React Native should be recommending using Expo anymore in all honesty.

**Comment by boliveira** [comment]
I am not using Expo. I just have one activity that instantiates a ReactRootView. I solved it by forking this repo and adding a way to set the ReactInstanceManager used by the activity.

**Comment by bogrees** [comment]
@gchenz47, thank you for posting your solution, I was able to keep the app from crashing in the scenario where a cloud message push notification is received within the app while running.

@KthProg, I completely agree with you, ExpoKit is bug-prone and very brittle at this point.  I am looking forward to when the OTA update module is separated from it, and a truly bare workflow can be used.  I will be migrating off of it immediately when that happens.

**Comment by sirmong** [comment]
@gchenz47 thanx for solution! You helped much!
