### ISSUE TITLE
how i can open specific app view when i tap on received notification  

### ISSUE THREAD

**Issue by azamkth** [zo0r/react-native-push-notification#434]

**Comment by hanishs17** [comment]
I am also looking for the same. Please help if anybody is aware about it.

Thanks

**Comment by npomfret** [comment]
You can't.  Only the app that the notification belongs to can be opened.

**Comment by syardumi** [comment]
I'm pretty sure @azamkth is asking how to "deep link" into the app the notification came from, not how to open a different app than the notification came from. I have the same question. I don't see any provision in the library for getting to an app's specific view when tapping the notification.

**Comment by icandeveloper** [comment]
Also looking to achieve this.

Would love to send the user to a specific view inside the app based on the notification.

**Comment by andrewcaulfield** [comment]
Also looking to achieve this.

Would love to send the user to a specific view inside the app based on the notification.

**Comment by matamicen** [comment]
@syardumi @Papav3r Hi guys, did you solve thise issue? I mean if you receive a DeepLink in push, it opens in that deeplink? it works for us the deeplink in a WhatsApp message or any other place, but we don't know How to this library handle a deepLink.

@Dallas62 any help ? :)


Thanks!!
