### ISSUE TITLE
can I use this in China?

### ISSUE THREAD

**Issue by JoeyCurry** [zo0r/react-native-push-notification#437]
I find this used google-service(gms),and as you know ,In China,most google-services can not be uesd,so I want to know can I use this in China?

----------------------------------------------------------------------------------------------------
这个项目使用了谷歌服务(gms)，这个在中国能用吗，能收到消息吗？

**Comment by lhr000lhr** [comment]
不能涩

**Comment by creditcoder** [comment]
Still no solution?

**Comment by joshua-smith4** [comment]
I have this same question. Does this library support backends other than firebase (Huawei, Baidu, etc)?
