### ISSUE TITLE
Android: Schedule notifications is not precise

### ISSUE THREAD

**Issue by filipemonteiroth** [zo0r/react-native-push-notification#443]
Hey, 

I don't know if you guys have this problem, But in my case, when I schedule a notification, sometimes it works, sometimes it doesn't. I mean, sometimes I have the notification 10 minutes later than it was supposed to be, sometimes it doesn't event fires. What should I do to fix this?

**Comment by varun-acintyo** [comment]
I am using my own fork so I am not sure what all commits have gone on but your issue sounds like a problem with the AlarmManager set call. You need to make sure it is using setExact instead of a simple set in rnpushnotificationhelper class

**Comment by filipemonteiroth** [comment]
How do I make sure i'm using setExact?
