### ISSUE TITLE
Calling on PushNotification.clearAllNotifications crashes on Android.

### ISSUE THREAD

**Issue by codebymikey** [zo0r/react-native-push-notification#444]
Looking into the git history of the code involved, `PushNotification.clearAllNotifications()` was moved to `PushNotification.cancelAllLocalNotifications()` .

But the code still references `clearAllNotifications` [here](https://github.com/zo0r/react-native-push-notification/blob/6a4f70fa3754e511a7dfad4c86ae58db169e3c79/index.js#L317) and [here](https://github.com/zo0r/react-native-push-notification/blob/ea241589b613c60edcca9a27c61b62fa6bdd447a/component/index.android.js#L107).

The code reference should probably be removed to avoid any future confusion.

**Comment by bachlx-bitmark** [comment]
Look like this function is not exist in native code(java class).
Can you help to fix this?

**Comment by desis123** [comment]
Use PushNotification.cancelAllLocalNotifications()
instead of clearAllNotifications .,. That did my job

**Comment by natasha08n** [comment]
You might know and can help. How to clear all notifications from Notification Center on android when one notification is opened?
