### ISSUE TITLE
Android: C++ Exception in NativeModules

### ISSUE THREAD

**Issue by a-koka** [zo0r/react-native-push-notification#446]
Adding the following to my `build.gradle` dependencies throws a C++ exception as noticed in the image.

    compile ('com.google.android.gms:play-services-gcm:8.1.0') {
        force = true;
    }

I have not been able to make notifications work at all on Android. FWIW, I'm testing on a simulator.

![screen shot 2017-06-03 at 4 43 46 pm](https://cloud.githubusercontent.com/assets/16167317/26757746/3eb903ac-487c-11e7-839d-7fe072bb0cbc.png)

**Comment by guerjon** [comment]
Any Solution? i get exactly the same error.

**Comment by a-koka** [comment]
The docs need to be updated to specify that this step is needed only if you want remote notifications. As a matter of fact, all you need is the following permission in your `manifest.xml` for local notifications to work.

    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />

I used [this](https://github.com/sheshbabu/RNLocalScheduledNotificationDemo) to help me get a baseline use case working and built my app from there.

Hope this helps.

**Comment by awchang56** [comment]
i had this problem except it said Java exception in NativeModules. Deleting 
```
compile ('com.google.android.gms:play-services-gcm:8.1.0') {
    force = true;
}
``` 
from build.gradle resolved the error as well.
