### ISSUE TITLE
[Android] Is there any way to open the app when a notification action is pressed? 

### ISSUE THREAD

**Issue by anchpop** [zo0r/react-native-push-notification#447]
I'd like to have a notification with two actions, one of which causes the app to open. The Google Guides tool has this functionality (an action called "Options" opens a page of the app). Is there any way to accomplish this?

**Comment by yianyue** [comment]
We used Linking from React Native as a workaround

**Comment by lluis-sancho** [comment]
@yianyue could you explain, how do you do the workaround?
Thanks.

**Comment by rcidt** [comment]
Hey @lluis-sancho, thanks for letting us know your solution. Where did you declare the `app_schema_name`?
