### ISSUE TITLE
Local notification is seen on simulator but not on real device.

### ISSUE THREAD

**Issue by nikhildaga** [zo0r/react-native-push-notification#448]
```
export default class App extends Component {
  componentDidMount() {
    setTimeout(() => {
      PushNotification.localNotification({
        message: 'My Notification Message', // (required)
      });
    }, 10000);
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
      </View>
    );
  }
}
```

This code works find on simulator and displays a local notification. However, it doesn't show anything on real device. Any idea what's causing this?

**Comment by iBicha** [comment]
It can be a permission issue

**Comment by EyalSi** [comment]
did you add the configuration (look at the readme for full code)

PushNotification.configure({

    // (optional) Called when Token is generated (iOS and Android)
    onRegister: function(token) {
...

**Comment by nikhildaga** [comment]
@iBicha : I verified that it isn't. I also tried by changing app id.

@EyalSi : Yes, I did. 

I have created a repo : https://github.com/nikhildaga/pn  . On reload , I see notification in simulator but not on device. If you get time, can you please verify whether you experience the same? Thank you!

**Comment by itinance** [comment]
[iOS] For me a popup appears when the app runs on real device in background, as expected. When the app runs in foreground, i still get the onNotification-event but nothing appears. 
Is it supposed to implement the notification-view by ourselfs or did i missed something?

I've configured with `popInitialNotification: true`

**Comment by enoch232** [comment]
Same issue.

**Comment by JonoH** [comment]
Yup. Same issue.

**Comment by pigflymoon** [comment]
Me too.

**Comment by pigflymoon** [comment]
I solved it as follows:
add notification configuration 
 PushNotification.configure({
            onNotification: function(notification) {
                console.log( 'NOTIFICATION:', notification );
            },
        });

**Comment by jeanpaulsio** [comment]
@nikhildaga - were you able to get this solved? having the same issue of being able to see it on my simulator but not on a real device

**Comment by fmoessle** [comment]
same problem here

**Comment by edudel** [comment]
mine it vibrates, but it does not show the notification popup, interesting eh?
any ideas ?

**Comment by shakedlokits** [comment]
I have the same issue

**Comment by zhengtong0898** [comment]
same issue.

**Comment by orhanberamus** [comment]
same problem

**Comment by QaseemLodhi** [comment]
Notification show in simulator but not in ipod. Any suggestion?

**Comment by haresh4d** [comment]
Any Solutions to this?

**Comment by dabhitapan** [comment]
any updates on this issue?

**Comment by goldylucks** [comment]
?

**Comment by Desintegrator** [comment]
same issue

**Comment by kendistiller** [comment]
Nothing on this?
