### ISSUE TITLE
IOS GCM Support

### ISSUE THREAD

**Issue by Riglerr** [zo0r/react-native-push-notification#45]
Does this module support the use of  [GCM](https://developers.google.com/cloud-messaging/ios/start) with IOS?
If not, is there any intended support for this in the future?

**Comment by zo0r** [comment]
It's not planned at moment.

**Comment by cmcewen** [comment]
@Riglerr this package will allow you to get GCM push tokens on iOS: https://www.npmjs.com/package/react-native-gcm-ios
