### ISSUE TITLE
support get local notification when the app was killed on android

### ISSUE THREAD

**Issue by zerophilip** [zo0r/react-native-push-notification#450]
Hi, guys, I have a problem is when the app was killed, I can't get any notifications. How can I get localNotificationSchedule when the app get killed?? thank you.

**Comment by zerophilip** [comment]
And I tried use react native background job[https://www.npmjs.com/package/react-native-background-job](url) to run localNotificationSchedule, but still not work

**Comment by varungupta85** [comment]
That should work out of the box without using other packages. Make sure that the notifications are scheduled. On which OS are you observing this problem?

**Comment by zerophilip** [comment]
thank you for reply, varugnpta85, on IOS, it works, but on android, when I killed the app, than I can't receive any notification.

**Comment by zerophilip** [comment]
What should I do..

**Comment by varungupta85** [comment]
Share your code for Android to schedule the local notifications.

**Comment by zerophilip** [comment]
var idString  = id.toString();

//var date1 = new Date(this.state.date)
//this.getDate(this.state.date);
        PushNotification.localNotificationSchedule({

 userInteraction: true,
   foreground: false,
   message: this.state.text,
   date: this.state.date,
   userInfo: {
             id: idString
           },
   //id: idString,
   repeatType: repeatSelection[selected-1],

        });

**Comment by varungupta85** [comment]
Can you confirm that the `this.state.date` is an instance of `Date` object and not the epoch time in milliseconds? Also `userInteraction` and `foreground` are not required.

**Comment by varungupta85** [comment]
I am also assuming that the scheduled notification shows up correctly if you don't close the app.

**Comment by zerophilip** [comment]
Thank you for reply, varugnpta85, I am sure that the date is an instance of Date object. And the scheduled notification shows up correctly when the app was not killed.

**Comment by zerophilip** [comment]
I find I got a error on android 


RNPushNotification failed to process intent Intent { cmp=com.rerereminder/com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService (has extras) }

maybe this error make me can't show up the notification when the app was killed?

**Comment by jablkopp** [comment]
@zerophilip did you solve your problem? I also can't manage to make `localNotificationSchedule` work after I close (kill) my app. It works in foreground and background fine, but when I kill app I don't receive local notifications anymore on Android.

**Comment by nabinkumarn** [comment]
@zerophilip  @krzysztofjablonski  Has this been solved? I am still facing this issue in latest version? Are there any alternative for this?

**Comment by bernhardt1** [comment]
@krzysztofjablonski @zerophilip  @nabinkumarn 

any luck solving this one? Or possibly a workaround?

**Comment by nabinkumarn** [comment]
@bernhardt1 this is due to mobile OS battery optimization. Once you disable battery optimization, it works fine. You need to prompt user to disable battery optimization for your app. That is the only workaround I found. [https://github.com/zo0r/react-native-push-notification/issues/996#issuecomment-461019756](here)
