### ISSUE TITLE
iOS background onNotification is received, but call gets stuck while calling async code

### ISSUE THREAD

**Issue by eddnav** [zo0r/react-native-push-notification#451]
Code executing is brought to a halt when an `AsyncStorage` call is reached, with either await/async or callbacks, it never finishes unless I open the app. What could be happening?

**Comment by afiller** [comment]
Were you able to solve your issue? I have a similar one and I'm looking for solutions.

**Comment by eddnav** [comment]
In the end I just skipped on doing any background processing in iOS, it's a mess how it's handled and it's so limited, and in any case, I can't rely on notifications being received either in Android or iOS for my purposes, so I modified the behavior of my app altogether...

**Comment by afiller** [comment]
:-/ That's sad and I think I will do it so as well. With Android it is working quite well, but for iOS I will fall back to regular notifications without background handling.

**Comment by noambonnie** [comment]
@afiller I'm close to giving up as well - My problem is with BG processing when the app is killed/not started (it's fine if it's running in the BG).

But I want to modify the notification when received. For example, "You have 1 new message" changed to "You have 2 new messages" when the second notification arrives. Is it something you need? Do you have any idea how to go about it without background handling and creating a local notification?
