### ISSUE TITLE
Pressing on the notification will open a determined scene?

### ISSUE THREAD

**Issue by Pacn91** [zo0r/react-native-push-notification#455]
Hi,

It's possible when pressing the notification to open one determined scene? I'm using react navigation.
Thank you!

**Comment by jurajkrivda** [comment]
Sure it is possible. You have to import your navigation handler to the onNotification callback

**Comment by Pacn91** [comment]
Hi @jurajkrivda , 

If you could provide a simple working example that'd be AWESOME!
Thanks

**Comment by jurajkrivda** [comment]
You should pass a navigator to the push notification configuration:

```

const fc = ({ navigation }) => {	
	PushNotification.configure({
		onNotification: notification => {
			if (notification.userInteraction) {
				navigation.navigate(...) // your scene
			}
		}
	})
}
```

**Comment by Pacn91** [comment]
Thank you very much!!
