### ISSUE TITLE
repeatType and repeatInterval not working

### ISSUE THREAD

**Issue by sumesh1993** [zo0r/react-native-push-notification#456]
@npomfret @zo0r 

react-native-cli: 1.0.0
react-native: 0.43.4
ios- 10.3
```
PushNotification.localNotificationSchedule({
          message: 'Test message',
          date: new Date(),
          largeIcon: '',
          smallIcon: "ic_notification",
          color: "#3591EC",
          userInfo: {id:1},
          userInfoAndroid: {id:1},
          repeatType:'minute',
          repeatInterval:'minute',

      });
```
Notification appears just once for the scheduled time, but never repeats. I have tried 'day' as well
Please help and let me knw if any further info is required from my end ?

**Comment by abarisic86** [comment]
There is a PR that enables requested feature: https://github.com/zo0r/react-native-push-notification/pull/381
Please go there and add 👍 so that it draws a bit of attention.
