### ISSUE TITLE
Identifying whether remote push notification was triggered from not running state

### ISSUE THREAD

**Issue by rcarvalho** [zo0r/react-native-push-notification#459]
There are 3 states that a remote push notification can be triggered:

1) Application is active
2) Application is backgrounded
3) Application is not running

I am able to keep a state of whether my application is backgrounded or not. So, 1 and 2 are taken care of. However, for 3, my application thinks that it is active. But, I would like to be able to detect this. I currently am going to use this hack, but it would be nice if somehow I could get this information via my notification.

My Hack - In my AppContainer constructor I'm putting the following:
`this.applicationState = 'Started'`
`
setTimeout(function(){
  this.applicationState = 'Active'
}, 5000)
`

Now, I know that my applicationState will be 'Started' if I received the notification when the application was not running. Yes, this interferes with me handling active notifications, but for our app, we don't care about notifications while the app is active, anyway. So, this is my hack, but it would be nice if we had a more reliable baked in solution.

I did some Google searching and there is something for PushNotificationIOS:
https://stackoverflow.com/questions/34337117/detect-whether-react-native-ios-app-was-opened-via-push-notification

**Comment by blankg** [comment]
Similar api is also available here, take a look at the popInitialNotification method.
PushNotification.popInitialNotification((notification)=>{
            if (notification) {
                //do something...
            }
        });

**Comment by rcarvalho** [comment]
I searched the whole repository and was not able to find it. Where are you looking? I did see that popInitialNotification is a boolean on the configuration. But, I didn't see anything for a callback method called popInitialNotification.

**Comment by blankg** [comment]
https://github.com/zo0r/react-native-push-notification/blob/master/index.js#L299
Note that the popInitialNotification boolean in the configuration should be set to false (this means it will not pop the notification automatically but only when you call popInitialNotification).

**Comment by shrutic** [comment]
@blankg from the code it seems like the popInitialNotification calls "getInitialNotification" native method that I see is implemented in Android but not in iOS. So does this feature not work for iOS?
