### ISSUE TITLE
onNotification is not fired on iOS

### ISSUE THREAD

**Issue by jsphkhan** [zo0r/react-native-push-notification#46]
I am trying to trigger a local notification which is happening. But when I click/tap on the notification message then the onNotification() callback handler is not invoked.

**Comment by tanguyantoine** [comment]
you probably should do this

```javascript
PushNotificationIOS.addEventListener('localNotification', this._onNotification);
```

instead of
```javascript
PushNotificationIOS.addEventListener('notification', this._onNotification);
```

Hope it helps.

I will do a pull request to update the documentation

**Comment by jsphkhan** [comment]
Thanks for looking into it. I actually tried with localNotification event type and it is working now. 
Although I did not understand the purpose of popInitialNotification() . If you have some spare time, an explanation would certainly help me. 
Thanks once again.

**Comment by tanguyantoine** [comment]
I did not used `popInitialNotification()` for the moment, sorry.

**Comment by pewh** [comment]
It's work on iOS. But how can I make it work at Android? `PushNotificationIOS` is only support for iOS.

**Comment by tanguyantoine** [comment]
yes the functionnality is in progress #12

**Comment by npomfret** [comment]
@jsphkhan do you still have this issue?  if so, have you tried the latest release?  if not, can we close it?

**Comment by npomfret** [comment]
Close due to inactivity
