### ISSUE TITLE
[ios] onRegister not being called when running from Hockeyapp build ( works fine when debugging from Xcode)

### ISSUE THREAD

**Issue by shrutic** [zo0r/react-native-push-notification#463]
When I am testing my react-native code by running my Xcode pointing to a physical device, I can see the onRegister codepath being hit.

But When I checkin my code into hockeyapp and install the build on a physical device, I do not see the onRegister codepath being hit. 

```
       PushNotification.configure({
            // (required) Called when a remote or local notification is opened or received
            onNotification: (notification) => {
                console.log( 'NOTIFICATION:', notification );
            },
            onRegister: (tokenObject) => {
                let body = {
                    deviceType: Platform.OS,
                    registrationId: null,
                    tags: '',
                    token: tokenObject.token,
                    uid: userId,
                };
                // CAll to my custom backend to store the token and make call to Azure notification hub 
                // I can see this call to my custom backend in Charles when debugging, but not from 
               // hockeyapp build. 
            },
            senderID: ServerUtil.FireBaseSenderId,
        });
```

Any thoughts on why the onRegister isnt working for Hockeyapp build, but works fine when I debug from Xcode?

I made sure I have the entitlements enabled, I have the AppDelegate methods updated to correspond to PushNotificationIOS.

**Comment by shrutic** [comment]
The entitlements file that sets the aps-environment was not checked in. I discovered this problem, by going to Xcode -> Window ->Devices and selecting my device on which the hockeyapp build was installed.Then I tapped on the triangle inside a rectangle icon at the left hand bottom side of the window. This will show continuous stream of NSLog. In this I searched for my app name and found this warning thrown by the OS

<Notice>: No valid 'aps-environment' entitlement string found for application '<application id>': (null). Notifications will not be delivered. 

Then I went to Xcode and toggled the Push notification toggle in the capabilities and then saw the change to <App name>.entitlements file that adds the aps-environment key.

**Comment by Amila17** [comment]
@shrutic Hi, I have been using the react-native-push-notification library for local notifications and it works great. However, I am trying to configure it to work with remote notifications and I have setup Azure Notification Hub to work with APNS to test notifications. Doing a test notification from Azure Portal does not seem to work (the app does not receive the notification). Am I missing something during the setup process of the app?

Additionally, when the onRegister method is called, a token is generated. I am assuming this token will be used to register the device with Azure Notification Hub. Is that correct?

Thanks.

**Comment by sarahmarciano** [comment]
@Amila17 I am also trying to use this package with azure notifications hub did you find what was wrong?
