### ISSUE TITLE
Navigation to another screen when clicked on Notification

### ISSUE THREAD

**Issue by chandrasekhar-nyros** [zo0r/react-native-push-notification#466]
Hi 

I want redirect from one screen to another screen when clicked on received push notification please help me any one

Thanks in advance

**Comment by adriaferre** [comment]
In the `onNotification` function you have to do a navigator.push() or .replace() at the screen you want.

For example:
`
var PushNotification = require('react-native-push-notification');

PushNotification.configure({
    onNotification: function(notification) {
        navigator.pop();
    }
});
`

**Comment by Dhimanswadia** [comment]
@adriaferre is the method of access of  iOS payload different than android? I have navigation to the right screen working on android but in iOS it just directs me to the screen i was on when i tap the notification. Thanks.

**Comment by mopitz199** [comment]
@adriaferre I was trying using your code and it haven't worked. The object "navigator" where did you get it? and where is some doc about it? I can't found anything. Thanks :)

**Comment by adriaferre** [comment]
@mopitz199 The object "navigator" was the old way in react native to navigate between screens. Now is like this => https://facebook.github.io/react-native/docs/navigation.html

**Comment by adriaferre** [comment]
@ycman0307 navigator was the old way in react to navigate between screens. I don't know how works react now.

Hope this can help you.
