### ISSUE TITLE
register to google

### ISSUE THREAD

**Issue by imane12** [zo0r/react-native-push-notification#47]
how to register to google to obtain the android id? I could not find any function to call registration.

**Comment by zo0r** [comment]
GCM: https://developers.google.com/cloud-messaging/android/start

**Comment by imane12** [comment]
Thank you for your response, but what we mean is how to use your plugin to register to google and obtain an android id.
We have a sender id and we created a google project, but in your plugin we can see their is a function named unregister but their is no function to register.

However, if you can guide us to a declared guide how to use your plugin, wiki lack a lot of infos.

Best regards!

**Comment by zo0r** [comment]
@imane12 https://github.com/zo0r/react-native-push-notification/issues/53#issuecomment-214459941
