### ISSUE TITLE
Android: Issue when clicking notification on tray. payload data VS payload notification

### ISSUE THREAD

**Issue by jayspirits** [zo0r/react-native-push-notification#473]
First i tried sending push notification using data payload. Everything works fine. But i decided to use the notification payload because its easy to group like every time I receive a new notification and if its relative to the other it will just replace the old one unlike payload data its stacking on the notification tray.
My issue is that when i use the notification payload, every time i clicked the notification from the tray its not launching my app. Its like nothing happened.

**Comment by rawrmaan** [comment]
Your problem is outside the scope of this package.
