### ISSUE TITLE
localNotificationSchedule is firing inmidiatly

### ISSUE THREAD

**Issue by josehernandezv** [zo0r/react-native-push-notification#475]
If I use the code like in the example 
date: new Date(Date.now() + (60 * 1000))
It works perfectly but if I try to create a date with some parameters it fires the notification inmidiatly, the date is well formed. 
Here is a screenshot of my code

![image](https://user-images.githubusercontent.com/28166305/27972191-acd43874-6312-11e7-91c3-d7b0ea648b52.png)

**Comment by germanst** [comment]
Maybe the device where you're testing it has a different hour than your local system. Take into account that Date.now() gets the system hour, not the device's hour (even if you're using a virtual device). When YouTube set a schedule notification in the past the notification appears inmediatly

**Comment by germanst** [comment]
Maybe the device where you're testing could has a different hour than your local system. Take into account that Date.now() gets the system hour, not the device's hour (even if you're using a virtual device). When your set a schedule notification in the past the notification appears inmediatly

**Comment by joaom182** [comment]
Same issue here. I have a lot of future dateTime to schedule.. and all are firing immediately. On param `date` i'm using a `UTC Datetime`...

**Comment by marcelodesouza** [comment]
Hi @joaom182 
Did you find the solution?

**Comment by imsinghdurgesg** [comment]
I am facing the same problem,did anyone got the solution?

**Comment by faisal3413** [comment]
I'm also having the same issue only in android. iOS working fine. I tested on multiple devices and simulators.

**Comment by imsinghdurgesg** [comment]
Hi @marcelodesouza in scheduleLoaclNotification method , date can not be past day date otherwise it will fire immediately , so you have to put a logic if date is past day then just add 7 day with same time(hour,minute...) . It will work, as it worked for me.

**Comment by tinpt123** [comment]
you can use format: ` new Date("July 31, 2019 16:00:00") `
