### ISSUE TITLE
userInteraction always returns true on iOS

### ISSUE THREAD

**Issue by jmeiss** [zo0r/react-native-push-notification#476]
Hi guys,

I'm facing an issue since few days that I don't understand.

Here is the content of the notification I'm pushing via AWS SNS:
```
{
"APNS_SANDBOX":"{\"aps\":{\"alert\":{\"title\":\"My App\", \"body\":\"Body notif\",\"payload\":{\"type\":\"new_post\"}},\"sound\":\"default\", \"content-available\":\"1\"}}"
}
```

`onNotification` is triggered when I receive the notification and a second time when I open the notification. Which is the expected behaviour.

`foreground` is always `false`, which is the expected behaviour when the app is on background or when I click on the notification. It's `true` when the app is on foreground.

The problem is when I want to check `userInteraction`. The value is always `true` wether I receive the notification or click on it.

I tried different scenario but `userInteraction` is always `true`.

Is it normal? Am I the only one having this behaviour?
If someone has an idea on what I'm doing wrong, I would love to hear from him.

Thanks for your help.

**Comment by sckoh** [comment]
I have the same problem too. 
The problem lies on 
https://github.com/zo0r/react-native-push-notification/blob/master/index.js
line 220 

if the notification is received in background, the userInteraction will always be true

**Comment by johnwnowlin** [comment]
So what is the fix?

**Comment by tonygriv** [comment]
I got the same issue when added content-available=1, because without this parameter onNotification doesn't trigger in background, but I need triggering in background. But one more problem appeared with userInteraction always true.

Do somebody have a solution?

**Comment by ngandhy** [comment]
+1

**Comment by wumke** [comment]
+1

**Comment by harshalbid271** [comment]
+1

**Comment by colaskirschoff** [comment]
From this [post](https://stackoverflow.com/questions/32061897/ios-push-notification-how-to-detect-if-the-user-tapped-on-notification-when-the/35475659#35475659) I was able to trigger the method `onNotification` only when user taps on notification, by checking that the app state is inactive (which is not true when notification is received but not tapped). You just need to update your `AppDelegate.m` as follows:
<img width="832" alt="image" src="https://user-images.githubusercontent.com/9667205/46812682-815ca400-cd75-11e8-98d4-d53633eb4192.png">

If you need to run jobs even when user does not tap the notification you might want to add a `didReceiveRemoteNotification` method with `userTapped` as a parameter in `RCTPushNotificationManager.m` library, to fix what happens line 220 in https://github.com/zo0r/react-native-push-notification/blob/master/index.js

**Comment by appriseevi** [comment]
@colaskirschoff what about the case when the screen in locked. You tap on the notification, then you enter the passcode or faceID. In this case the didReceiveRemoteNotification:inactive will not be called!
