### ISSUE TITLE
set state not working in onNotification??

### ISSUE THREAD

**Issue by yogeshmoradiya121** [zo0r/react-native-push-notification#477]
onNotification: function(notification) {
        console.log( 'NOTIFICATION:', notification );
        this.setState({noti_pop: notification});
    },

it shows an error.

**Comment by mojocakes** [comment]
What error do you get?
This might be because you're now in a new function and "this" no longer refers to the component.
Try this:

```
var _this = this;
onNotification: function(notification) {
  console.log( 'NOTIFICATION:', notification );
  _this.setState({noti_pop: notification});
},
```

**Comment by aspidvip** [comment]
not work

**Comment by cavebring** [comment]
See example here: https://github.com/zo0r/react-native-push-notification/blob/master/example/App.js

**Comment by KPS250** [comment]
Try this...
```
 onNotification: function (notification) {      
    this.setState({noti_pop: notification});
  }
 }.bind(this),
```
