### ISSUE TITLE
largeIcon not displayed android

### ISSUE THREAD

**Issue by manuTro** [zo0r/react-native-push-notification#479]
Hi, I cannot make largeIcone works.. I changed the ic_launcher.png with my icons (with differents dimensions), but the large icons doesn't appear. did I miss something?
Thanks

**Comment by EnKrypt** [comment]
Kind of sad that it's been 2 years and there have been no answers to this.

The issue is present today as well.

**Comment by TaraSinghDanu** [comment]
I am still facing the issue.

**Comment by TaraSinghDanu** [comment]
I tried this:
PushNotification.localNotification({
largeIconUrl: 'https://img.icons8.com/search'
})
PushNotification.configure({
// (required) Called when a remote or local notification is opened or received
onNotification: async (notification) => {
console.log('NotificationCAlleddddddddddedddddddddd ==>', notification)
const { foreground, userInteraction, data } = notification;
// if (foreground) {
// console.log('foregroundNOTIFICATION ==>', notification)
// }
// if (userInteraction) {
// onNotificationOpen(notification)
// }
onNotificationOpen(notification)
},
// Should the initial notification be popped automatically
// default: true
popInitialNotification: true,
})

but not working.
