### ISSUE TITLE
iOS popInitialNotification always has has notification=null

### ISSUE THREAD

**Issue by shrutic** [zo0r/react-native-push-notification#481]
react-native: 0.43.3
react-native-push-notification: 3.0.0

I have the react-native-push-notification working for iOS when the app is in background/foreground.
But if I have a notification when the app is killed, the popInitialNotification function always has the notification value set to null.

Below is my configure method, based on this [comment](https://github.com/zo0r/react-native-push-notification/issues/161#issuecomment-238413023)

```
public static startConfiguration(userId: string) {
            if (PushNotification !== null) {
                PushNotification.configure({
                    // (required) Called when a remote or local notification is opened or received
                    onNotification: (notification) => {
                        console.log('Notification received');
                        PushNotificationManager.handleNotificationReceived(notification);
                    },
                    onRegister: (tokenObject) => {
                        PushNotification.popInitialNotification((notification) => {
                            if (notification) {
                                PushNotificationManager.handleNotificationReceived(notification);
                            }
                        });
                    },
                    popInitialNotification: false,
                    senderID: ServerUtil.FireBaseSenderId,
                });
            }
    }
```

I see that the popInitialNotification is called everytime, including when launching a killed app from a notification, but every single time the notification is null.

Any thoughts on what I am missing?

**Comment by varungupta85** [comment]
Should the `popInitialNotification` be set to `true`?

**Comment by shrutic** [comment]
I tried that too. That didn't work either :(

Shruti

**Comment by shrutic** [comment]
I finally had to accomdate it in my native iOS code where inside my didFinishLaunchingWithOptions, I check if the launchOptions[.remoteNotifitcation] is non -null and derive the necessary information from it

```
 if let userInfo = launchOptions?[.remoteNotification] as? [NSObject : AnyObject] {
            requiredData = (userInfo as NSDictionary)["requiredKey"] as? String ?? ""
        }
```
I am then passing down the required data as props to the Root component that I initialize in the didFinishLaunchingWithOptions method

**Comment by Clcll** [comment]
@shrutic Did you solve the problem ? thx

**Comment by anhhh11** [comment]
You should try
https://stackoverflow.com/questions/34337117/detect-whether-react-native-ios-app-was-opened-via-push-notification/38191351#38191351
