### ISSUE TITLE
Push notification receive remotely Android with property localNotification and not.

### ISSUE THREAD

**Issue by Angelk90** [zo0r/react-native-push-notification#483]
To receive push notifications from the server use this code: https://github.com/zo0r/react-native-push-notification#usage
By setting up the senderID, I get notification, but I want to set properties that I use in local notifications and not.

I list the prorities I can not set:

1) Put the icon at the time of receiving the push notification.
What size should I have, in which folder I have to put and mainly how the sect the icon.

2) How can I place a Large notification icon, an image taken from an http url. 
Example: https://batch-doc.s3.amazonaws.com/Push/BigIcon.png

3) bigText, subText, actions, do not know how to set them up, should I send them server side?
How do I manage my actions?

4) The ability to reply to a message: https://s3.amazonaws.com/codementor_content/2016-Aug/direct+reply+notification.png

5) The ability to show an image in the push as: https://i2.wp.com/applearner.com/wp-content/uploads/2016/08/Screen-Shot-2016-08-24-at-2.33.42-PM.png

**Comment by abhideepmallick** [comment]
@Angelk90 did you get a workaround/solution for this?

**Comment by Angelk90** [comment]
@abhideepmallick: 
Only for the first:
You have to create a white color icon all the other transparent, mipmap-hdpi, mipmap-mdpi and all others, called "ic_notification.png".

The other questions remained unresolved.

**Comment by abhideepmallick** [comment]
@Angelk90 could you set the notification icon according to the white icon? In my case the icons work for `PushNotification.localNotification` but not for the ones received from the server. They are still small white boxes. Did you fix the same?

**Comment by Angelk90** [comment]
@abhideepmallick: I speak of the white icon, see example: https://i.ytimg.com/vi/S1s8uavzbGw/maxresdefault.jpg
The white pencil in the status bar.

Terms as long as functions are:
The design must be completely white, all the rest transparent.
Standard res sizes, those indicated above.
Example: https://user-images.githubusercontent.com/20476002/28571097-900a4412-7141-11e7-8147-dfa1dbfe0da6.png

As you see very difficult to see, the design, but with a proper image program you can see it.
To me, that's how it works.

**Comment by abhideepmallick** [comment]
Here is the code for remote notifications:

My implementation of the notification from server is as follows: 

```
_setupNotifications(endpoint, authKey) {
    PushNotification.configure({
      onRegister: (token) => {
        this._sendPushToken(token, authKey, endpoint)
      },
      onNotification: (notification) => {
        let data = {}
        let message_category = ''
        if (Platform.OS === 'ios') {
          message_category = notification.data.message_category
          let badge = notification.badge || 0
          this._setBadgeNumber(badge)
          data.badge = badge
          data.title = notification.message.title
          data.body = notification.message.body
          if (typeof notification.data.transaction_id !== 'undefined') {
            data.transaction_id = notification.data.transaction_id
          }
        } else {
          message_category = notification.message_category
          data.title = notification.title
          data.body = notification.body
          if (typeof notification.transaction_id !== 'undefined') {
            data.transaction_id = notification.transaction_id
          }
        }

        var messageAlert = function(title: string, body: string) {
          Alert.alert(
            title,
            body,
            [
              {text: I18n.t('ok'), onPress: () => console.log('OK Pressed')},
            ]
          )
        }

        switch (message_category) {
          case "bookingRequest" :
            if (notification.foreground === true) {
              let transactionId = data.transaction_id
              messageAlert(data.title, data.body)
              this.eventEmitter.emit('bookingRequest', {transactionId: transactionId, notification: notification})
            }
            break
          case "bookingCancelled" :
            if (notification.foreground === true) {
              let transactionId = data.transaction_id
              messageAlert(data.title, data.body)
              this.eventEmitter.emit('bookingCancelled', {transactionId: transactionId, notification: notification})
            }
            break
          case "bookingRejected" :
            if (notification.foreground === true) {
              let transactionId = data.transaction_id
              messageAlert(data.title, data.body)
              this.eventEmitter.emit('bookingRejected', {transactionId: transactionId, notification: notification})
            }
            break
          case "bookingApproved":
            if (notification.foreground === true) {
              let transactionId = data.transaction_id
              messageAlert(data.title, data.body)
              this.eventEmitter.emit('bookingApproved', {transactionId: transactionId, notification: notification})
            }
            break
          case "bookingOwnerAlert": 
            if (notification.foreground === true) {
              let transactionId = data.transaction_id
              messageAlert(data.title, data.body)
              this.eventEmitter.emit('bookingOwnerAlert', {transactionId: transactionId, notification: notification})
            }
            break
          case "bookingAlert": 
            if (notification.foreground === true) {
              let transactionId = data.transaction_id
              messageAlert(data.title, data.body)
              this.eventEmitter.emit('bookingAlert', {transactionId: transactionId, notification: notification})
            }
            break
          case "newMessage":
            if (notification.foreground === true) {
              let transactionId = data.transaction_id
              messageAlert(data.title, data.body)
              this.eventEmitter.emit('newMessage', {transactionId: transactionId, notification: notification})
            }
            break
        }
      },
      senderID: "XXXXXXXXXXX",
      popInitialNotification: true,
      requestPermissions: true,
    })
  }
```

I can't set the large or small icons anywhere. So, only small boxes show up.

**Comment by itneste** [comment]
open the ic_notification.png in photoshop,transparent the background.white icon will be show.put this picture in drawable,mipmap-hdpi, mipmap-mdpi and all others。
like this
![ic_notification](https://user-images.githubusercontent.com/6678553/32646203-6a5cf2f2-c626-11e7-90dc-dd3d0dbfb8ed.png)
