### ISSUE TITLE
Android: "file or directory '[...]/react-native-push-notification/android/libs', not found"

### ISSUE THREAD

**Issue by danleveille** [zo0r/react-native-push-notification#484]
When I build my React Native project for Android, I get the following error, several times:

>file or directory '/Users/danl/AwesomeProject/node_modules/react-native-push-notification/android/libs', not found

Is this directory supposed to exist?

**Comment by stonecold123** [comment]
I have the same problem. @danleveille did you solve it?

**Comment by danleveille** [comment]
@stonecold123 To be honest, I can't remember if I fixed it. Sorry! I must have forgotten about it because I just had a few users of my app complaining about push notifications are no longer working on Android. Will update you if I find something, but my next version won't be for a while.

**Comment by muratozgul** [comment]
Any update?

**Comment by araujobarret** [comment]
+1

**Comment by EvanSays** [comment]
+1

**Comment by kamrulislam** [comment]
+1
