### ISSUE TITLE
Disable/enable notification

### ISSUE THREAD

**Issue by manuTro** [zo0r/react-native-push-notification#485]
Is it possible to disable and enable notification?

**Comment by elios264** [comment]
any news on this?

**Comment by kyaroru** [comment]
yes it is possible now on this commit of our forked repo : https://github.com/surialabs/react-native-push-notification/commit/39d7adbb7bf1b620167ca7cc0491366b8ce716fc

For Android & iOS
- To enable, fire `requestPermissions()`, and to disabled fire `abandonPermission()`

**Comment by danielsGit** [comment]
abandonePermissions method don't block the remote notification on Android. What should I do to block the remote notification in specified page?

**Comment by gluons** [comment]
@github-actions Don't close.  
I want to know how to disable remote notification. (like Daniels' question)  
I use this local notification with [React Native Firebase](https://rnfirebase.io/).

**Comment by Dallas62** [comment]
From README:

Abandon Permissions

PushNotification.abandonPermissions() Revokes the current token and unregister for all remote notifications received via APNS or FCM.

**Comment by gluons** [comment]
> abandonePermissions method don't block the remote notification on Android.

As @danielsGit said. It seems `abandonPermissions` may not disable remote notification on Android.  
It shows duplicate notifications on my device.

// Maybe I'll try it again on new fresh RN project.

**Comment by Dallas62** [comment]
Yeah, this was true last year
Look at #1425

**Comment by RyanCao7** [comment]
Abandoning and then re-registering for notifications is a truly hacky workaround to being able to intercept push notifications before they are displayed on the device. There _ought_ to be a handler which fires _before_ a notification ever reaches the device, and allows for re-routing (or simply not displaying) that particular notification. Any chance we can get this going?

**Comment by jimzqw** [comment]
I also need this. How do we manage notifications by having a way to disable and re-enable? I was following the doc and tried cancelLocalNotification but got _reactnativepushnotification.default.cancellocalnotification is not a function

**Comment by oguzhan10** [comment]
@jimzqw did you find any solution for your question? Because I am also stuck on this problem.

**Comment by waqaramjad** [comment]
is there any update ?

**Comment by aristotles** [comment]
This still is an issue.

**Comment by jimzqw** [comment]
My solution for now is unsub and resub based on your needs. Like if I don't want users to get notification on a certain page I will unsubscribe user, and resubscribe when they exit that page.
