### ISSUE TITLE
Android background not receiving notificatio object

### ISSUE THREAD

**Issue by MarkoVk95** [zo0r/react-native-push-notification#486]
I dont receive the notification and the onNotification object.It will jut bring to front my app and thats it,it works fine on foreground tho.

**Comment by felixjamestin** [comment]
@MarkoVk95 were you able to solve this? I have the same issue.

**Comment by sitompul** [comment]
@MarkoVk95 @felixjamestin if you guys have a solution or using other package, please do share your knowledge, im having this trouble as well
