### ISSUE TITLE
Dynamic large icon

### ISSUE THREAD

**Issue by zorosun** [zo0r/react-native-push-notification#488]
is it possible to set large icon from image url or image file when I got it from server?

**Comment by GertjanReynaert** [comment]
I'm trying to achieve this large image behaviour in the notification, but it doesn't seem like this library supports it: https://developer.android.com/training/notify-user/expanded#image-style

**Comment by TaraSinghDanu** [comment]
I tried this:
PushNotification.localNotification({
largeIconUrl: 'https://img.icons8.com/search'
})
PushNotification.configure({
// (required) Called when a remote or local notification is opened or received
onNotification: async (notification) => {
console.log('NotificationCAlleddddddddddedddddddddd ==>', notification)
const { foreground, userInteraction, data } = notification;
// if (foreground) {
// console.log('foregroundNOTIFICATION ==>', notification)
// }
// if (userInteraction) {
// onNotificationOpen(notification)
// }
onNotificationOpen(notification)
},
// Should the initial notification be popped automatically
// default: true
popInitialNotification: true,
})

but not working.
