### ISSUE TITLE
Android: onNotification method wont fire when received remote notificatio

### ISSUE THREAD

**Issue by avdept** [zo0r/react-native-push-notification#490]
This is related to https://github.com/zo0r/react-native-push-notification/issues/373
When android receives remote notification, onNotification method wont fire until you explicitly click on notification. Any ideas how to get it fire, once notification was received ?

**Comment by rcarvalho** [comment]
So, on iOS, that's how it is supposed to work. You don't receive the notification until you actually click the notification itself. I think the thing you may be looking for is called a data notification where you pass in data and not alert into the notification you send from your server. I believe alert triggers a visual alert and the data is a silent alert. I could be wrong, but that is my understanding.

Are you actually receiving the notification on Android when you click the notification? I am not. I can only get it to work on iOS.

**Comment by fredbt** [comment]
My scenario is the following (testing only on Android for now):

- the server pushes a notification through GCM.

- if the app is in the **foreground**, it receives the notification, and onNotification is called twice:
   --- when the notification arrives
   --- upon click
 Means: all good here!

- However, if the app is in the **background**, onNotification is *not* called. And it's not called **even when I click the notification**!

Is this expected to happen?

**Comment by omarcarreon** [comment]
Hi, I had the same problem. Check and try using my fix https://github.com/zo0r/react-native-push-notification/issues/495#issuecomment-319377505
