### ISSUE TITLE
Foreground equal true when receive notification in background

### ISSUE THREAD

**Issue by theohdv** [zo0r/react-native-push-notification#494]
Everything was working fine until I tried my application on a 4.2.2 Android device (Samsung GT-S7580). When I receive notification when my application is in background (not killed), the foreground property is equal to `true` .

RN: 0.45.1
RN push notification: 3.0.0

Is it a known issue ?

**Comment by GHACCT** [comment]
I had the same issue on the same Android version. 

Samsung Galaxy S3 on Genymotion emulation  
RN: 0.40
react-native-push-notification: 2.2.1

**Comment by theohdv** [comment]
@GHACCT can you try to increase the android version but to keep the same device model (to see if it is link to android).
