### ISSUE TITLE
Push notification not sound in Android

### ISSUE THREAD

**Issue by kelvinsinsua** [zo0r/react-native-push-notification#496]
Hi, i work with remote notifications and it's work fine, the notification is received and show all the parameters. but when i received the notification this not sound. 

my Js code : 

`PushNotification.configure({

	    // (optional) Called when Token is generated (iOS and Android)
	    onRegister: function(token) {
					var json = JSON.stringify(token);
					fetch( "http://api.nukondo.com"+"/api/registerToken", {
									method: 'POST',
									headers: {
										"Content-Type" : "application/json",
										'Authorization' : 'Bearer '+token1
									},
									body: json
								})
								.then((response) =>{
									return response.json();
							 }).then((res)=>{
								 this.setState({configure: true})

						}).catch(e=>{
		})
	    },

	    // (required) Called when a remote or local notification is opened or received
	    onNotification: function(notification) {
	        console.log( 'NOTIFICATION:', notification );
					Actions.notifications();
	    },

	    // ANDROID ONLY: GCM Sender ID (optional - not required for local notifications, but is need to receive remote push notifications)
	    senderID: "39921937113",

	    // IOS ONLY (optional): default: all - Permissions to register.
	    permissions: {
	        alert: true,
	        badge: true,
	        sound: true
	    },

	    // Should the initial notification be popped automatically
	    // default: true
	    popInitialNotification: true,

	    /**
	      * (optional) default: true
	      * - Specified if permissions (ios) and token (android and ios) will requested or not,
	      * - if not, you must call PushNotificationsHandler.requestPermissions() later
	      */
	    requestPermissions: true,
	});`

My server code: 

`$fields = array(
                "time_to_live" => 86400,
                "collapse_key" => "new_message",
                "delay_while_idle" => false,
                'to' => $token,
                'notification' => ['body'=>$message,'title'=>$title, 'color' => "#2ca9d9", "vibrate" => "true",   "vibration" => 300,"playSound" => true,"sound"=> "default"]
            );
            $headers = array(
                'Authorization:key=XXXXXXXXXXXXXX',
                'Content-Type: application/json'
            );
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));
            $result = curl_exec($ch);
            if ($result === FALSE) {
                die('Curl failed: ' . curl_error($ch));
            }
            curl_close($ch);`

**Comment by roysG** [comment]
any update?

**Comment by Yashpk789987** [comment]
I am facing same issue. Is it solved??
