### ISSUE TITLE
iOS support for repeat property

### ISSUE THREAD

**Issue by b-asaf** [zo0r/react-native-push-notification#499]
How can I set repeat interval in ios to be a custom time and not 1 minute.
currently my code is:
`
PushNotification.localNotificationSchedule({ message: 'Test message', date: new Date(Date.now() + (60 * 1000)), repeatType: 'minute', number: 0, userInfo: { id: new Date(Date.now()), }, });
`

**Comment by assafb81** [comment]
any update?

**Comment by rogerkerse** [comment]
It seems like a dead project. This issue was present over a year ago https://github.com/zo0r/react-native-push-notification/issues/258

**Comment by assafb81** [comment]
@rogerkerse - I know it is supported, I ask about customize repeat period. for example send notification every 8 minutes?

**Comment by abarisic86** [comment]
There is a PR that enables requested feature: https://github.com/zo0r/react-native-push-notification/pull/381
Please go there and add 👍 so that it draws a bit of attention.

**Comment by rodrigowpl** [comment]
Any update on this?

**Comment by rynatk** [comment]
@rodrigowpl 
It appears that this functionality is not supported in the core PushNotificationIOS module:
https://facebook.github.io/react-native/docs/pushnotificationios

https://github.com/zo0r/react-native-push-notification/pull/310 is the PR that added the functionality that currently exists in this library, and the author explicitly state `repeatInterval === time` is not supported on iOS.

IMO foremost the docs need to be updated to reflect this.
Idk the best route to approach for a solution for the library itself.

**Comment by Jacky9425** [comment]
Due to having multiple threads of these related issue, is the `repeatType` in IOS of this library able to set to "time" and add in extra parameter `repeatTime` features available now in this master branch of the library?

**Comment by Jacky9425** [comment]
So far I'm debugging with `react-native-push-notification version 3.1.9`. And the result so far is that IOS devices will only able to fire repeating notification under repeatType == "minute", "time" param is not working yet (TESTING ENV: IOS simulator).

**Comment by Jacky9425** [comment]
somehow, i managed to repeat notification by seconds in IOS, by `setInterval` containing the `localNotificationSchedule()`. Its not best practice but it does repeatedly sending out local notif even i kill the app (swipe up)

**Comment by erdenayozkanl** [comment]
how can I repeatedly push on repeatType ='minute', is not working to me ?

**Comment by Jacky9425** [comment]
Works fine for me so far

**Comment by erdenayozkanl** [comment]
Can you Please Show me the usage just repeatType for iOS? I would greatful. 

Sincerely,
Erdenay Özkanlı
