### ISSUE TITLE
onRegister not called (Android)

### ISSUE THREAD

**Issue by anativ** [zo0r/react-native-push-notification#5]
I took the sample code
`
onRegister: function(token) {
        console.log( 'TOKEN:', token );
    },
`
But onRegister is not called on Android
How do I get the device token?

**Comment by freemanon** [comment]
Had the same problem, fixed it by entering the App ID in the `senderID` field. See here to obtain a senderID: http://dev.tapjoy.com/faq/how-to-find-sender-id-and-api-key-for-gcm/

**Comment by anativ** [comment]
Works!
Thanks

**Comment by npomfret** [comment]
Thanks for this info.  It would be good to have this in the docs.
