### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by hdchan** [zo0r/react-native-push-notification#501]
![simulator screen shot aug 2 2017 6 09 40 pm](https://user-images.githubusercontent.com/4207605/28897215-b3d7910c-77ad-11e7-812c-ac690062d92a.png)

I know this is a duplicate issue...but I've followed all the instructions out there. Manually linked the library, but still does not work for iOS.

**Comment by alexkendall** [comment]
Getting the same error

**Comment by addieljuarez** [comment]
I could solve it with this.
https://facebook.github.io/react-native/docs/pushnotificationios.html#content

**Comment by mmkulmala** [comment]
Hi! Getting same error and tried pushnotificationios fix in: https://facebook.github.io/react-native/docs/pushnotificationios.html#content.
Still getting same error: Native module cannot be null.

**Comment by AhsanWani** [comment]
+ 1

**Comment by fzf** [comment]
Getting the same error with an ExpoKit ejection

**Comment by diego-cesa** [comment]
1

**Comment by lustigdev** [comment]
@mmkulmala If you haven't fixed the issue yet, make sure you close the packager, uninstall the app, and try again.

**Comment by umkhan65** [comment]
migrating from 3.1.9 to 2.2.1 worked for me
