### ISSUE TITLE
iOS onNotification called twice when click notification of killed app

### ISSUE THREAD

**Issue by sckoh** [zo0r/react-native-push-notification#504]
platform: iOS
version: 3.0.0
appState: killed

onNotication is called twice when I click the notification.

when the app is start, I receive 2 onNotfication called which are from:
1. popInitialNotification
`NOTIFICATION: Object {foreground: false, userInteraction: true, message: "Enter your message", data: Object, badge: 1…}`

2. PushNotificationIOS "notification" event
`NOTIFICATION: Object {foreground: true, userInteraction: false, message: "Enter your message", data: Object, badge: 1…}`

**Comment by DovletAmanov** [comment]
same issue +1

**Comment by ysshir** [comment]
same issue +1

I'm calling  `localNotification` in onNotification with condition `notification.userInteraction === false`.

if the app is inactive status (killed process) and recieve remote notification, and opening the app via pressing the notification, then 
 onNotification (notification.userInteraction === true) is called twice.

but I reallized the shape of argument of onNotification is different between first one and the second one.
so I just ignore the second one, and it's working now.
