### ISSUE TITLE
Local notifications aren't shown when screen is locked

### ISSUE THREAD

**Issue by nkalichynskyi** [zo0r/react-native-push-notification#506]
Local notifications work fine until screen is locked. When screen is locked notification is triggered(I can see it in notification center after unlock) but nothing showed on locked screen.
Can someone suggest something?
RN - 0.45.1
lib version - 3.0.0
target - Android 7.0 (Nougat) - API 24

UPDATE: figured out that thing that I need is something like this:
```java
 WakeLock screenLock = ((PowerManager)context.getSystemService(Context.POWER_SERVICE)).newWakeLock(
                 PowerManager.SCREEN_BRIGHT_WAKE_LOCK | PowerManager.ACQUIRE_CAUSES_WAKEUP, "TAG");
            screenLock.acquire();

//later
screenLock.release(); 
```
Would be nice to have some flag of property in this lib that will allow WakeLock

**Comment by jailsonpaca** [comment]
I tried to solve with the visibility param: `PushNotification.localNotification({ visibility:"public" ...`
