### ISSUE TITLE
android: foreground == false when the app is in the foreground

### ISSUE THREAD

**Issue by b-asaf** [zo0r/react-native-push-notification#509]
Hi,
I want to cancel local notification repetition when the App in in the foreground but I encounter 2 issues:
1. notification is not called
2. foreground is false, (instead of my expectation) and not 'true'.

i am using RN 0.45.1 
an push-notification 3.0.0

my code looks like:
PushNotification.configure({
            onNotification: (notification) => {
                console.log('NOTIFICATION:', notification); // eslint-disable-line no-console
                const clicked = notification.userInteraction;

                if (clicked || notification.foreground === true) {
                    if (Platform.OS === 'ios') {
                        PushNotification.cancelLocalNotifications({ id: notification.id });
                    } else {
                        PushNotification.cancelLocalNotifications({ id: notification.id });
                    }
                }
            },
        });

**Comment by lucask42** [comment]
+1 notification.foreground seems to always be false.

I would also like to find a way to suppress / skip notifications when the app is open.  My notifications are reminders to use the app so are distracting when the app is open.

**Comment by ahmedabadie** [comment]
The system shows notification dropdown alert even when the app is open. So I assume it is something with Android, however, I am not really sure because it's bad user experience.

@lucask42 how about cancelling all notifications when the app is launched and reschedule when terminated/entered background?
