### ISSUE TITLE
No visible notification when app is running/foreground

### ISSUE THREAD

**Issue by vvavepacket** [zo0r/react-native-push-notification#513]
Why is that my app does not show the visible notification when it is running.. But I see the onNotification method is triggered. How do we enable it?

![image](https://user-images.githubusercontent.com/8295642/29146568-bd3ffebe-7d2f-11e7-9fac-6829d8282ccb.png)

**Comment by vvavepacket** [comment]
closing as solved. i found out we can use a silent notification, and inside there, we can manually trigger a local notification.

**Comment by rochapablo** [comment]
@vvavepacket, do you have an example?

**Comment by linhho** [comment]
@rochapablo 
PushNotification.configure({
...
    onNotification: function(notification) {
        //console.log( 'NOTIFICATION:', notification );
        alert(notification.alert);// or you can use Alert.alert() to config alert head, button...
    },
...
});

**Comment by AugustoAleGon** [comment]
I still can not see the Notifaction when is clicked just when the app is running. What happened?

**Comment by iiitmahesh** [comment]
@AugustoAleGon have solved the problem. I have same issue???

**Comment by rochapablo** [comment]
Some things that you should try:

1. Run in your mobile (not the emulator)
2. Configure the firebase
3. Configure the backend to send the notifications according to the firebase setup
