### ISSUE TITLE
Notification icon defaults to stock android for XiaoMi phone

### ISSUE THREAD

**Issue by gavin-gmlab** [zo0r/react-native-push-notification#515]
Have implemented this module successfully in my project. However, have weird case where the notification icon for a remote notification on a XiaoMi phone is not the ic_launcher icon, but the default android green droid. The icon is fine for other phones like Samsung, Oppo, OnePlus etc. Didn't do anything specific to define the icon anywhere in the code.

JS config:
PushNotification.configure({

      onRegister: (token) => {
        if (__DEV__) console.log('PUSHTOKEN:', token)
        simpleStore.save('PUSH', token).then(() => {
          // if (__DEV__) console.log("done storing into store", token)
        }).catch(function (error) {
          if (__DEV__) console.log('Push token problem: ' + error.message)
        })
      },
      // (required) Called when a remote or local notification is opened or received
      onNotification: (notification) => {
        if (__DEV__) console.log('NOTIFICATION:', notification)

        if (notification.foreground) {
        NavigationActions.listScreen({type: 'reset'})
          Vibration.vibrate()
        }
      },
})

Anything I'm missing?

**Comment by MichaelPintos** [comment]
in MIUI they do not use the notification icons, but they use the icon of the application. copies the same files from the `drawable` folders to the `mipmap` folders with the corresponding size.

**Comment by gavin-gmlab** [comment]
Thanks! That helped.

**Comment by figgcoder** [comment]
@MichaelPintos @gavin-gmlab  I did as mentioned above but it's not working. I am sending following notification about remote 

`  var message = new GCM.Message({
    data: {
      id: '0',
      ticker: 'My Notification Ticker', // (optional)
      autoCancel: true, // (optional) default: true
      largeIcon: 'app_icon', // (optional) default: "ic_launcher"
      smallIcon: 'ic_notification',
      bigText: 'My big text that will be shown when notification is expanded',
      subText: 'This is a subText', // (optional) default: none
      color: 'red', // (optional) default: system default
      vibrate: true, // (optional) default: true
      vibration: 300,
      tag: 'some_tag', // (optional) add tag to message
      group: 'group', // (optional) add group to message
      ongoing: false, // (optional) set whether this is an "ongoing" notification

      // alertAction: // (optional) default: view
      // category: // (optional) default: null
      // userInfo: // (optional) default: null (object containing additional notification data)

      title: 'My Notification Title',
      message: 'My Notification Message', // (required)
      playSound: false, // (optional) default: true
      soundName: 'default',
      number: '10',
      // repeatType: 'day',
      actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
    },
  });
`
My client code looks like this
` PushNotification.configure({
    // (optional) Called when Token is generated (iOS and Android)
    onRegister(token) {
      console.log('TOKEN:................', token);
      updateFn(token);
    },

    // (required) Called when a remote or local notification is opened or received
    onNotification(notification) {
      console.log('NOTIFICATION:', notification);
      if (notification.foreground && !notification.userInteraction) {
        PushNotification.localNotification(notification);
      }
    },
`



I have following files in my mipmap-* folders 
app_icon.png (size as mentioned in android appicon specs) 
ic_notification (size as mentioned in android notification_icon conf) 
ic_launcher.png (same size as ic_notification)

I also have drawable folder with
splash screen and ic_launcher icon (as in mipmap-*).

Really appreciate any help in this regard.
