### ISSUE TITLE
onNotification not called in foreground ( Noisy remote / IOS )

### ISSUE THREAD

**Issue by theohdv** [zo0r/react-native-push-notification#517]
According to whats is described in the troubleshooting document for noisy remote notification:

> Your app will not be invoked if it is running in the background, and the notification will result in an alert in the notification centre. If you app is running in the foreground, onNotification will be called with something like

Everything works fine for me except that when my application is in foreground and I receive a noisy remote notification, `onNotification` is not triggered.

**Comment by michchan** [comment]
same problem here, when my app is in background the notification is well received.

**Comment by JClackett** [comment]
I'm having the same issue

**Comment by calintamas** [comment]
It seems to be working on iOS 10.3.3, but not on newer iOS versions (tested and not working on 11.0.3). Anyone got any clue?

**Comment by padampadam** [comment]
same issue here, any news?

**Comment by arfa123** [comment]
same issue here, when app is in background onNotification triggers but not triggers when app is in foreground.
