### ISSUE TITLE
Today Widget not Showing Contents When PushNotificationIOS activated

### ISSUE THREAD

**Issue by charlesfamu** [zo0r/react-native-push-notification#519]
I've been having trouble understanding why my today widget isn't working after integrating the react-native-push-notification into my application. Has anyone experienced this problem? For example, I'm trying to display something as simple as: `<Text>Hello World</Text>` in my today widget. I followed the procedures to implement the widget in this article. 
https://medium.com/@davidskaarup/add-ios-today-widget-to-your-react-native-app-ed9c9b601cc

**Comment by matejkriz** [comment]
The article you linked is about local notifications. How did you implement the today widget?

**Comment by charlesfamu** [comment]
@matejkriz, I figured out the problem. The libraries and frameworks "must" be the same for the widget and the project. If they aren't, the widget and notifications won't work together properly.
