### ISSUE TITLE
Android ApplicationBadgeHelper.java user or overrides a deprecated API

### ISSUE THREAD

**Issue by Metroninja** [zo0r/react-native-push-notification#520]
Getting warnings compiling in Android studio.

RN 0.47.1

**Comment by dbyilmaz** [comment]
@Metroninja you can remove the override notation of deprecated method createJSModules.

**node_modules/reacr-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/ReactNativePushNotificationPackage.java**

remove this method:
```
  @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
```

**Comment by Metroninja** [comment]
@dbyilmaz - That's what I did, just wanted to post his here for others that will be looking as they upgrade RN to >47.  I'm sure a new release will be cut soon enough

**Comment by brunoosilva** [comment]
Run `yarn add react-native-push-notification@3.0.1` or `npm i react-native-push-notification@3.0.1`, worked!
