### ISSUE TITLE
Compilation error with RN 0.47

### ISSUE THREAD

**Issue by antonioturdo** [zo0r/react-native-push-notification#522]
With version 0.47 of react-native I get the following error:

`\android\src\main\java\com\dieam\reactnativepushnotification\ReactNativePushNotificationPackage.java:20: error: method does not override or implement a method from a supertype
    @Override
    ^`

In this version of react-native the method createJSModules has been removed from ReactPackage.
Maybe it was not a great idea, because it seems like a breaking change. 
However I suppose method must be deleted to have a version of this package compatible with RN 0.47.

**Comment by zeusi83** [comment]
Oh, a pull request was already opened about this

**Comment by zeusi83** [comment]
#523

**Comment by nilehmann** [comment]
Any expected date for a release with this fix?

**Comment by NguyenThaiHoc1** [comment]
just remove the @Override in this file

**Comment by purumvisum** [comment]
Any updates?

**Comment by conanak99** [comment]
@NguyenThaiHoc1 's solution worked for me. This can be a workaround solution for somebody needed.

**Comment by m-vdb** [comment]
last commit on this repo is 3months old :(

**Comment by brunoosilva** [comment]
Run `yarn add react-native-push-notification@3.0.1` or `npm i react-native-push-notification@3.0.1`, worked!

**Comment by vspedr** [comment]
AS @brunoosilva mentioned, version 3.0.1 solves the issue
