### ISSUE TITLE
onNotification not called (onNewIntent not called either) on first boot of application

### ISSUE THREAD

**Issue by kingkian** [zo0r/react-native-push-notification#527]
Hi all, 

Using local notifications only. No changes in AndroidManifest. 

onNotification is not called (onNewIntent not called either) when I click a notification on the first boot of my application after launch. If I open the app, kill it, then reopen, things will work fine. 

Has anybody seen this issue?

**Comment by nonsense66** [comment]
I've seen a problem with onNotification not being called. Can you provide more details Platform/Code?

**Comment by nonameolsson** [comment]
@nonsense66 Did you solve it? I have the same problem https://youtu.be/NwcBsameqQ0 #170
