### ISSUE TITLE
Deprecated API problem on android

### ISSUE THREAD

**Issue by Batuhan-Akkaya** [zo0r/react-native-push-notification#529]
![](https://preview.ibb.co/mJbk7F/Ekran_Resmi_2017_08_17_14_34_24.png)

I got the attached error when i ran the app after installation of the plugin. Deleting "override" section seems like the only solution for this error. Is there any alternative solution for this problem?

**Comment by mauriciopasquier** [comment]
Same issue: #522

**Comment by dbyilmaz** [comment]
@Batuhan-Akkaya 
`{yourApp}/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/ReactNativePushNotificationPackage.java`
bu dosyayı açtıktan sonra dosyanın içinden altta bulunan kodları sildiğinde düzelecek
```
    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
```
createJSModules() yüzünden bu hatayı veriyor

**Comment by brunoosilva** [comment]
Run `yarn add react-native-push-notification@3.0.1` or `npm i react-native-push-notification@3.0.1`, worked!
