### ISSUE TITLE
How do you get the device token in android?

### ISSUE THREAD

**Issue by cubbuk** [zo0r/react-native-push-notification#53]
Hi,
How could I get the device token for android using this library. I configured the `PushNotification` object as documented. I can send local notifications, but callback for `register` event is never called. Do I need to call some method? Thanks

**Comment by zo0r** [comment]
Use `PushNotification.configure(...)` to setup your listeners.

The `onRegister` event is called when the registration token is received for Android and iOS. Also remember to set your `senderID` in Android (its your Google Console Project ID).

**Comment by cubbuk** [comment]
Thanks for the response. I registered to GCM and put my `senderID` into `PushNotification.configure(...)` but `onRegister` event is still not triggered. Do I need to call any method?

**Comment by cubbuk** [comment]
I think it was due to emulator, on real device the event started triggering, thanks for guidance.
