### ISSUE TITLE
Redirect on page when click on notification 

### ISSUE THREAD

**Issue by ranashahidbashir** [zo0r/react-native-push-notification#535]
is there any why we redirect on a specific page when  click  on notification from tray??

**Comment by MackayBravo** [comment]
+1

**Comment by kievu** [comment]
Doesn't depends on what navigation method you use? I fixed this issue just now, by using react-native-router-flux. Handling it by sending a callback of `setState` to `onNotification` and let the function find out what the group `notification.data.group` is set to. The state set by onNotification is passed as a prop to the component I create scenes and I set `initialScene` depending on it.

**Comment by ajithamp** [comment]
Hi @kievu, can you share some example code for the one that you have mentioned above.

**Comment by ranashahidbashir** [comment]
hi @kievu  and @ajithamp  i have fixed this issue by using setTimeout function in notification opened_from_tray block.

**Sample Code**


`redirect(){
    this.props.navigator.push({name:"DetailPage", data:this.state.pageData[1]});
}`

`


    this.notificationListener = FCM.on(FCMEvent.Notification, notif => {
      console.log("Notification recived", notif);
      if(notif.local_notification){
         console.log("Notification recived local", "local notification");

          if(notif.opened_from_tray){

             console.log("Notification recived local ", "opened from tray");

            setTimeout(() => {

            //    console.log('setting page call!'); 
            console.log('this is props',props);
              this.redirect()
              // this.props.navigator.push({name:"Sports"});
            //  // this.props.navigator.push({name:'DetailPage',data:Data});
            }, 5000);

             //this.props.navigator.push({name:"Settings"});

          }
        
        return;
      }
      if(notif.opened_from_tray){

         console.log("Notification recived tray ", "opened from tray");
         //this.props.navigator.replacePrevious({name:"Settings"});
        return;
      }

      if(Platform.OS ==='ios'){
              //optional
              //iOS requires developers to call completionHandler to end notification process. If you do not call it your background remote notifications could be throttled, to read more about it see the above documentation link.
              //This library handles it for you automatically with default behavior (for remote notification, finish with NoData; for WillPresent, finish depend on "show_in_foreground"). However if you want to return different result, follow the following code to override
              //notif._notificationType is available for iOS platfrom
              switch(notif._notificationType){
                case NotificationType.Remote:
                  notif.finish(RemoteNotificationResult.NewData) //other types available: RemoteNotificationResult.NewData, RemoteNotificationResult.ResultFailed
                  break;
                case NotificationType.NotificationResponse:
                  notif.finish();
                  break;
                case NotificationType.WillPresent:
                  notif.finish(WillPresentNotificationResult.All) //other types available: WillPresentNotificationResult.None
                  break;
              }
      }

`

**Comment by shaheerakhlaq** [comment]
Getting error: undefined is not an object (evaluating 'props.navigation.navigate')

**Comment by fahadhaq** [comment]
@shaheerakhlaq  I am getting the same error. How did you resolve this issue?
