### ISSUE TITLE
iOS 11 Beta 

### ISSUE THREAD

**Issue by JonesN7** [zo0r/react-native-push-notification#536]
Did anyone test this with the iOS 11 beta? I'm having issues scheduling local notifications on an iPhone 7 running iOS 11 beta 6, however I have not done much debugging yet so not sure if this is really the problem. All my other devices work fine.

**Comment by jasonmerino** [comment]
@JonesN7 were you able to verify that you could schedule local notifications on iOS 11?

**Comment by JonesN7** [comment]
I am working on reproducing and documenting the errors I get at the moment, but no, I am still having issues scheduling local notifications on iOS 11. Sometimes they work, and sometimes they don't, and I'm still trying to figure out exactly how to reproduce and/or how to avoid this issue.

**Comment by JonesN7** [comment]
My problem was that on iOS you can only schedule 64 notifications at a time. On iOS 10 and below I always got the 64 first of my scheduled notifications, and did not notice the problem. On iOS 11 i got the 64 last of notifications, and therefore the issue was more noticeable.
