### ISSUE TITLE
List upcoming notifications

### ISSUE THREAD

**Issue by Martin25699** [zo0r/react-native-push-notification#538]
Hello! Tell me how to view the queue of notifications installed through PushNotification.localNotificationSchedule(params)?

**Comment by nonameolsson** [comment]
Is this possible? Did you solve it? Would really like to know how you did.

**Comment by Martin25699** [comment]
@nonameolsson for android of this possibility did not find, for iOS is in the documentation of the reaction [here](https://facebook.github.io/react-native/docs/pushnotificationios.html#getscheduledlocalnotifications)
