### ISSUE TITLE
can't receive push message when app is killed

### ISSUE THREAD

**Issue by waltChang1** [zo0r/react-native-push-notification#539]
i can received he push message when app is running or backed,but when i killed the app ,i can't receive push message ,just can saw 
"broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10000000 pkg=com.pushtest (has extras) }"
from Android Monitor.
who can tell me how to solve the problem,thank u

**Comment by MichaelPintos** [comment]
+1

**Comment by felixjamestin** [comment]
+1

**Comment by AriHietamaki** [comment]
Is this with all Android devices or just with some brand? 

I have seen this happen with Huawei devices, but haven't been able to replicate this issue with my Oneplus device.

For Huawei devices there is known issue with push notifications if app is not added to "protected apps" list. To get that easier there is component done for that https://github.com/pgengoux/react-native-huawei-protected-apps

**Comment by onlydave** [comment]
Getting this on my nexus 5x but not other devices
