### ISSUE TITLE
Can't see notifications in the iOS tray, but still listen to the sound

### ISSUE THREAD

**Issue by jsdario** [zo0r/react-native-push-notification#540]
When in foreground the app does not show notification or sound, but when fired in the background (both with `PushNotification.localNotification` and `PushNotification.localNotificationSchedule`) it does not appear in the tray. I have tried with different meta configurations, but still nothing.

Also I noticed that the `PushNotification.localNotificationSchedule` is scheduling always immediately, but I have not isolated it properly.

I am using `react-native@^0.47` and `react-native-push-notification@3.0.1`.

Hope it leads somewhere.

**Comment by ducpt2** [comment]
+ 1, i have same issue.

**Comment by jsdario** [comment]
It happened when testing a reinstalled app, that lacked permissions. To get more insights about this in iOS I logged and added UX around notification permissions. It is annoying but we have to make sure that we always count with notification permissions to prompt the note.

**Comment by ducpt2** [comment]
@jsdario you mean: requestPermissions: true, in PushNotification.configure({...})? If not, can you show me how to do it? Thanks.

**Comment by jsdario** [comment]
Not like that. But that would simplify the problem.

I mean that we have to make sure that we are testing in an app that has notification permissions for all 3 cases (sound, badge, alert). The moment this was a bug for me, the reason was that I _lacked_ those permissions.

**Comment by ducpt2** [comment]
@jsdario i'm petty sure i have 3 cases permissions. Still don't know why it not work. :) btw, thank you.

**Comment by zhonggithub** [comment]
same  issue
