### ISSUE TITLE
Token is not generated

### ISSUE THREAD

**Issue by renishghetia** [zo0r/react-native-push-notification#542]
getting exception 

java.io.IOException: INVALID_SENDER
com.google.android.gms.iid.zze.zzb(Unknown Source)
com.google.android.gms.iid.zze.zza(Unknown Source)
com.google.android.gms.iid.InstanceID.zzc(Unknown Source)
com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService.onHandleIntent(RNPushNotificationRegistrationService.java:23)
android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by HsanBenJobrane** [comment]
How did you solve this? I'm getting the same error

**Comment by gino8080** [comment]
same
