### ISSUE TITLE
Can it support Firebase

### ISSUE THREAD

**Issue by DongpingQi** [zo0r/react-native-push-notification#546]

**Comment by hhsadiq** [comment]
any answers?

**Comment by danieloprado** [comment]
+1

**Comment by L3V147H4N** [comment]
+1

**Comment by EzeRangel** [comment]
Yes, you need to copy/paste your Firebase sender ID into the `senderID` in the `configure` method.

**Comment by RyanWarner** [comment]
@EzeRangel when I paste my `project_number` from `google-services.json` into the `senderID`, my app starts crashing. Any idea why or how I can debug this?
