### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithDexForDebug'. > 

### ISSUE THREAD

**Issue by nabeelnazir163** [zo0r/react-native-push-notification#548]
I am having this issue, can anyone help me to sort this out ?

![untitled](https://user-images.githubusercontent.com/30865060/30050406-cdb68642-9237-11e7-8e10-d43d35c23154.png)

**Comment by Shhzdmrz** [comment]
I don't know exact error but this piece of code solve my issue.

instead of:
```
compile ('com.google.android.gms:play-services-gcm:8.1.0')
```
and use:
```
compile ('com.google.android.gms:play-services-gcm:+') 
```
