### ISSUE TITLE
Notification for Killed/Closed App

### ISSUE THREAD

**Issue by MuruganDurai** [zo0r/react-native-push-notification#55]
When trying to push the notification for closed app, got an error like 'undefined is not an object (evluating 'RCTToastAndroid.SHORT')'. Is this behaviour handled or did I missed something? please clarify. I am using RN 18.5.
## logcat

W/ReactNativeJS(15109): Warning: Native component for "SMXIconImage" does not exist
W/ReactNativeJS(15109): Warning: Native component for "SMXIconImage" does not exist
E/ReactNativeJS(15109): undefined is not an object (evaluating 'RCTToastAndroid.SHORT')

Thanks.

**Comment by npomfret** [comment]
@MuruganDurai do you still have this issue?  if so, have you tried the latest release?  if not, can we close it?
