### ISSUE TITLE
iOS - clearing notifications in notification tray by hitting the 'x' doesn't clear the notification count on the app icon

### ISSUE THREAD

**Issue by lucask42** [zo0r/react-native-push-notification#551]
I would like the notification count to be cleared if the notification in the tray goes away.  Any ideas how to make this happen?

**Comment by swl367** [comment]
The notification center and your app badge icon are not dependent on each other. If you do want to associate push notifications with your badge count dismissal in any way, I would suggest using the push notification actions (slide to view more options on a push notification) to individually count something as "viewed".

**Comment by lucask42** [comment]
Thanks for explaining that, makes sense.
