### ISSUE TITLE
Action does not open app if app is closed

### ISSUE THREAD

**Issue by tallmorgan** [zo0r/react-native-push-notification#552]
I'm trying to get an Android app to come to the foreground on clicking an action. For iOS, `holmesal`'s `react-native-ios-notification-actions` uses `{activationMode: 'foreground'}` to achieve this effect. I read the documentation, but `foreground` only seems to appear as a parameter to `onNotification`. Am I missing something?

**Comment by sumesh1993** [comment]
@varungupta85  any suggestions ?

I am just trying to snooze the notification from an action, which works fine if the app is running in background.
But if the app is killed, my Snooze action button does nothing.

How can i make the action button work even when the app is closed.

**Comment by varungupta85** [comment]
Running some code when a user clicks a notification action is a bit tricky. I am assuming you are asking this for Android. What you will need to do is start the app in the background if the app is not running and then broadcast the action. You can check if the app is running by checking if there is a valid react context. If not, then create a react context which should also start the app and then take care of the action. I am sorry I can't share any code snippets at the moment.

Thanks,
Varun
