### ISSUE TITLE
Allow user to specify "message" field name for Twilio Notify support on Android

### ISSUE THREAD

**Issue by evancorl** [zo0r/react-native-push-notification#558]
We're encountering an issue with Android in our project using Twilio Notify (See here: #557).

Twilio provides `twi_body` instead of `message`, and because of the validation check below, our bundle isn't being sent to the notification centre:

https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L139

It seems silly for us to fork this package for such a minor issue. Would you be open to allowing the user to specify the name of the `message` field (the default being `message`)? Doing so would allow us to continue using this package.

Thanks!

**Comment by khrizt** [comment]
Hi, I'm working on this issue also. I managed to get it work while the app is open but not when the app is closed, [the changes are these](https://github.com/coverfy/react-native-push-notification/commit/1b8c1f185b47bfb73e7a43a9d451ee8496acefe1), so if anyone can help...

The main problem is that I can pass an array of string as alternative message field names but when the app is closed and a notification is received the list is always null as it happens before calling the configure method from react-native.

**Comment by peterp** [comment]
I really wish this would get merged.
