### ISSUE TITLE
Android - My local scheduled notifications pop up while my app is open

### ISSUE THREAD

**Issue by lucask42** [zo0r/react-native-push-notification#560]
Hi, I'd like to prevent my own notifications from popping up while my app is open.

Is there some kind of setting in RN-PN to enable/disable this behavior?

In OneSignal there is a setting called: `inFocusDisplaying` is there any equivalent in RN-PN?

**Comment by gavin-gmlab** [comment]
I have this in my code:
`
 onNotification: (notification) => {
        if (__DEV__) console.log('NOTIFICATION:', notification)

        if (!notification.foreground) {
          NavigationActions.mainScreen({type: 'reset'})
        } else {
          if (__DEV__) console.log('local Notification')
          Vibration.vibrate()
        }
      },
`

**Comment by daominhsangvn** [comment]
If you're using `react-native-onesignal` then try to use following this to disable the notification displays as popup:
```
OneSignal.inFocusDisplaying(2);
```

**Comment by rynatk** [comment]
Is there not a way to disable scheduled local notifications on Android when the app is in the foreground?

The default behavior on iOS is not to show them, so it seems weird there wouldn't be a standard way to achieve platform parity.

**Comment by lucask42** [comment]
If the maintainers are interested in adding this feature I wouldn't mind creating a PR for it
