### ISSUE TITLE
Payload containing both `data` and `notification` properties unable to trigger `onNotification` event on click 

### ISSUE THREAD

**Issue by stonecold123** [zo0r/react-native-push-notification#561]
The library works fine in regards to receiving the notifications. 
My payload is like this:
````
{
    notification:{
          "title": "Hello there",
          "message": "some message text"
    },
    data:{
           "key":"value"
    }
}
````
The `onNotification` works fine when the app is in the frontend. However, when it's in the backend, I cannot bring the app to the frontend on clicking the notification.  The `onNotification` never gets called on click. 
It only works when the `notification` property is removed from the payload and changed to this:
````
{
    data:{
           "title": "Hello there",
          "message": "some message text"
    }
}
````
Why does the `notification` property in the payload object structure would cause the failure of `onNotification` when the app is in the back?

**Comment by stonecold123** [comment]
Closed. I guess I must put all of the notification properties to the data in order for it to work.

**Comment by witalobenicio** [comment]
@stonecold123 How you solve that issue? In Android I just don't know when user clicked on a notification

**Comment by developercode1** [comment]
@stonecold123 Putting all the attributes in data object doesn't work in Android Oreo 8 release build. How can we trigger the onNotification event when we have the notification object and the data object too in the payload ?
