### ISSUE TITLE
iOS - notification doesn't appear

### ISSUE THREAD

**Issue by paranat9221** [zo0r/react-native-push-notification#562]
hi,

I have a problem when I use push notification in iOS, It's work fine in android simulator and Device but when I use in iOS simulator and device it doesn't appear.

I follow the set up and I think it's should be work

I use this code to test notification

```
PushNotification.localNotification({
     message: "Hello world"
})
```

and in Xcode log appear this message
```
'NOTIFICATION:', { foreground: true,
  userInteraction: false,
  message: 'Hello world',
  data: {},
  badge: 0,
  alert: 'Hello world',
  sound: 'default' }
```

but in iOS device doesn't have any response

hope someone can help me. thank!! :)

**Comment by efiorello** [comment]
Did you find the problem?

**Comment by paranat9221** [comment]
@efiorello oh I already know it.
This is my error. I didn't know that notification for iOS will not appear when app are working but in android work. its make me misunderstood that iOS app not working
