### ISSUE TITLE
Can't launch App when click on action of remote notification.

### ISSUE THREAD

**Issue by taduyde** [zo0r/react-native-push-notification#566]
I implemented actions for remote notifications as below, But I click Button accept, the App don't launch.

import PushNotificationAndroid from 'react-native-push-notification'

(function() {
  // Register all the valid actions for notifications here and add the action handler for each action
  PushNotificationAndroid.registerNotificationActions(['Accept','Reject','Yes','No']);
  DeviceEventEmitter.addListener('notificationActionReceived', function(action){
    console.log ('Notification action received: ' + action);
    const info = JSON.parse(action.dataJSON);
    if (info.action == 'Accept') {
      // Do work pertaining to Accept action here
    } else if (info.action == 'Reject') {
      // Do work pertaining to Reject action here
    }
    // Add all the required actions handlers
  });
})();

How can launch APP when click button actions remote notification?

**Comment by MrPeproni** [comment]
Hello @taduyde, Is this issue solved? I am having same issue.

**Comment by lluis-sancho** [comment]
Same problem here.

**Comment by nikhilninawe** [comment]
Any solution for this?

**Comment by lluis-sancho** [comment]
@nikhilninawe as a workaround you can open the app with Linking when pressing the button.

**Linking.openURL('app_name://')**. 

In Android you need to put in your manifest;

<activity
            android:name="com.package....MainActivity"
            android:label="@string/app_name"
            **android:launchMode="singleTask"** 
...
</activity>

**Comment by Fadi-Ghattas** [comment]
Any Help or Solution  ??

**Comment by lluis-sancho** [comment]
Hi @Fadi-Ghattas , 

an example:

      DeviceEventEmitter.addListener('notificationActionReceived', function(action){
        const info = JSON.parse(action.dataJSON);
        //props.pushNotification.setApplicationIconBadgeNumber(0)
        if (info.action == 'Profile') {
          Linking.openURL('app_name://')
        ...
      }
    }
