### ISSUE TITLE
[Android] When app is in background, userInteraction keeps in 'false'

### ISSUE THREAD

**Issue by fbazzana** [zo0r/react-native-push-notification#569]
Hi,
In Android, when the app is in background and we receive a push, if the user touch the notification window ```userInteraction``` flag keeps in 'false', so we can't handle this correctly (we have several ways to manage push according to 'types', we are receive this ok).

This works well on iOS.
I'm using ```react-native-push-notification 2.2.1``` and ```react-native 0.37```.

Did anyone have the same issue?

**Comment by keenubee** [comment]
The same thing with 3.0.1 build from npm

**Comment by fbazzana** [comment]
Same again with ```react-native-push-notification 3.0.1``` and ```react-native 0.49```

**Comment by Ilario17** [comment]
@fbazzana I have this problem too, is there a solution?

**Comment by brianfoody** [comment]
Causing major issues for me as I only want to act on notifications that have been interacted with by the user. Is there a workaround?

**Comment by namxam** [comment]
I am having the same issue. Any update on this?

**Comment by haifahrul** [comment]
I am having the same issue. Any update on this?

**Comment by strawberry-code** [comment]
I am having the same issue. Any update on this?
