### ISSUE TITLE
Cancel local notifications is not working - iOS

### ISSUE THREAD

**Issue by Sushant-Sardeshpande** [zo0r/react-native-push-notification#570]
- React Native: 0.48
- Plugin version: 3.0.1

Tried both, the `cancelLocalNotifications({ id })` with a notification object as:

```
PushNotification.localNotificationSchedule({
        id,
        title,
        message,
        date: moment().toDate(),
        largeIcon: 'app_icon',
        smallIcon: 'app_icon',
        color: 'blue',
        userInfo: {
            id
        }
    })
```

Also, tried cancelAllLocalNotifications() without success.

I can confirm that it is working for Android but not for iOS.

**Comment by EyalSi** [comment]
This is the version that worked for me on Android + iOS (with cancel...):
PushNotification.localNotificationSchedule({
        id: ''+recordID, // must be id of type STRING so that the cancel will work on android
        userInfo: {
          id: ''+recordID, //IMPORTANT!! adding the userInfo, so that the cancel will work!
        },
        number:0, // must have this otherwise it fails.
        data: {
          recordID: recordID,
        },
        message: message,
        date: someDate,
      });

later on:
    PushNotification.cancelLocalNotifications({id: ''+recordID}); // must be id of type STRING so that the cancel will work on android

**Comment by peterlazar1993** [comment]
@EyalSi Confirmed working on Android. Will update after testing on iOS

**Comment by lytieunuong1** [comment]
Thank @EyalSi <3 Important thing is the **id** for cancel must be **String**. Then I solved this issue
`PushNotification.cancelLocalNotifications({id: ''+recordID});`

**Comment by rdewolff** [comment]
Works on iOS.

**Comment by kalraneeraj24550** [comment]
it is not working foe me. my functions are like this:-

const localNotification = (fromUserName, data, orderId) => {
    PushNotification.localNotification({
      id: ''+orderId,  
      autoCancel: true,
      largeIcon: JointDeliveryLogoIcon,
      smallIcon: JointDeliveryLogoIcon,
      bigText: `You got a message for (OrderId:-${orderId})`,
      subText: "",
      number:0,
      vibrate: true,
      vibration: 300,
      userInfo: {
        id: ''+orderId, 
    },
      color: "green",
      title: `${fromUserName}`,
      message: `Message:- ${data}`,
      playSound: true,
      soundName: 'default',
    });
   };



   const cancelLocalNotifications = (notificationId) => {

    console.warn('notification id gettinggggggg=====', notificationId)

    PushNotification.cancelLocalNotifications({
      id: ''+notificationId
    });

**Comment by kalraneeraj24550** [comment]
anybody please help me

**Comment by calintamas** [comment]
Refer to this: https://stackoverflow.com/a/53909899/8886649
