### ISSUE TITLE
When i create my release build push notifications doesn't shows up on android

### ISSUE THREAD

**Issue by AFMW** [zo0r/react-native-push-notification#572]
I have my project done in development environment and everything works fine but when i build my release apk it finishes the build and when i install it on a real device it doesnt show any push notifications.

Im using these dependencies:
"react": "16.0.0-alpha.12",  
"react-native": "0.48.2",  
"react-native-push-notification": "^3.0.1",

You guys have any ideas?
this is the code im using for handle the push notifications:
`
	componentDidMount(){

			  MessageBarManager.registerMessageBar(this.refs.alert);
		 
		PushNotification.configure({
			
			 onNotification: function(notification) {
			        console.log( 'NOTIFICATION:', notification );
			        dataMio= notification

						
			        console.log( 'dataMio:', dataMio );

			         var numeroNotif= notification.badge

				     PushNotification.setApplicationIconBadgeNumber(numeroNotif--);
				         

			     if (notification.tipoPush=="inbox") {
			     	console.log("entro")
			     	

			        if (banderaPush=='active') {
			        	MessageBarManager.showAlert({
						  title: 'Ha llegado un mensaje',
						  message: notification.alert,
						  position: 'top',
						  alertType: 'success',
						  onTapped: ()=>{idMensajePush=notification.id
							        	Actions.inbox()
							        	Actions.DetalleMensajes({data:idMensajePush,bandera:""})}
					
						});

			        }else if (banderaPush=='background') {
			        	idMensajePush=notification.id
			        	Actions.inbox()
			        	Actions.DetalleMensajes({data:idMensajePush,bandera:""})

			        }else{
			        	idMensajePush=notification.id
			        	 setTimeout(() => {
                  	
	                		Actions.inbox()
				        	Actions.DetalleMensajes({data:idMensajePush,bandera:""})
                      
                           }, 2000);
			        	
			        }
			        	
			     }

			    },
			    requestPermissions: true, 
			    senderID: "foo",
			    permissions: {
							    alert: true,
							    badge: true,
							    sound: true
							  },
			    onRegister: function(token) {
		        console.log( 'TOKEN:', token );

		        tokenMIO=token

		         AsyncStorage.setItem("tokenRemoto",tokenMIO.token);
				AsyncStorage.setItem("os",tokenMIO.os);
			    loginJson.body.tokenRemoto= tokenMIO.token
			    loginJson.body.os=tokenMIO.os
		    },
		});

	

				
	}
`

**Comment by nonsense66** [comment]
@AFMW I think, you are having same issue as I do. Have you tried to send push notification to a device when app is open? I can only receive push notifications when it's open. Here is my stackoverflow question https://stackoverflow.com/questions/46911548/gcm-messages-deliver-only-when-app-is-open

**Comment by nonsense66** [comment]
@zo0r do you have any ideas?

**Comment by nonsense66** [comment]
@AFMW are you sending notification payload? seems like it doesn't work properly for non-notification payloads.

**Comment by sitompul** [comment]
@nonsense66 i'm having the same issue like yours. But on my case, it's a lil bit different. I was using it on local. And the notification won't show up when the app is running in background

**Comment by Shubham-Sinha** [comment]
Were you able to fix this ?
