### ISSUE TITLE
Notification icon not shown on MIUI phone 

### ISSUE THREAD

**Issue by figgcoder** [zo0r/react-native-push-notification#576]
I am testing my application in MIUI global 8.5 | stable 8.5.8.0 (Redmi Note 4).

While I read somewhere MIUI doesn't show small Icon and only shows App Icon for notifications. However, in my case, It's not even showing app icon and only showing default android icon (Green Android). I tried even copying icons from drawables to mipmap to drawables and nothing working. 

I am using react-native-push-notification 3.1.0 and react-native 0.44. Really appreciate any help in solving this issue.

**Comment by dotomaz** [comment]
+1

**Comment by figgcoder** [comment]
I found this was due to caching of icons by MIUI. When I changed theme then icon cache is cleared and new app install does work as intended.

**Comment by figgcoder** [comment]
@dotomaz I found this if you want to try out. 

https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/GenerateNotification.java#L408

**Comment by phamhieu1412** [comment]
i have same error on MIUI, 

react-native: 0.70.5
react-native-push-notification: 8.1.1
what is the solutions....?

**Comment by Rapcon88** [comment]
``

**Comment by DhaivatKhanparaPanamax** [comment]
same issue
