### ISSUE TITLE
Android - Badge Shows but No Push Notification 

### ISSUE THREAD

**Issue by scgough** [zo0r/react-native-push-notification#579]
Hi,
I've got an app and I'm currently working on the Android version. Part of that work is to include Push Notifications. 
I've implemented as per the instructions but I have an issue: When I receive a notification on my Android device, I see the badge number increment but the push notification itself doesn't show up.

I'm a bit baffled as to why this is. 

I have recently moved to a new Google account (so have new Firebase Cloud Messaging keys) but I've checked those and they are all correct.

**Comment by dotomaz** [comment]
I have the same problem :(

**Comment by scgough** [comment]
Figured what this was. You might notice the notification does come through if the android device screen is off/locked. 
We found this issue and work around and notifications work now. Basically, convert the remote notif to a local one on receipt. 

https://github.com/zo0r/react-native-push-notification/issues/219#issuecomment-321113943

**Comment by dotomaz** [comment]
For me the problem was that the floating and lock screen notifications weren't enabled in the settings. Once I enabled them they showed correctly
