### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by jedrichards** [zo0r/react-native-push-notification#580]
Wondering if anyone could help me with a couple of usage questions.

### Permissions denied vs. notifications off vs. permissions unrequested

The permissions object seems identical `{ alert: 0, badge: 0, sound: 0 }` in all of these scenarios:

1. User clicked "Don't allow" when permissions were requested
1. User allowed notifications but later turned them off in settings
1. We haven't requested permissions yet

This seems to make it impossible to design a UI that accurately shows notifications permission state. Has anyone got an approach or work around for this?

### Calling `configure` and `onRegister` multiple times

Does the `onRegister` method get called every time the `configure` method gets called?

Should it be called multiple times, or just once when you first request permissions?

Does the token change as you call `configure` or is it static and bound to the device?

**Comment by lfkwtz** [comment]
`PushNotification.requestPermissions` resolves with a promise of the permissions object
`PushNotification.checkPermissions` accepts a callback that asynchronously returns the permissions object

Using a mix of those, and `AsyncStorage`, you can:

1. Check permissions -- if they don't exist, check if they've been asked before
2. If they've been asked before, show information regarding how to reenable
3. If they haven't been asked before, ask for permissions and set flag marking them as having been asked
