### ISSUE TITLE
iOS - Doesn't receive notification when device is locked

### ISSUE THREAD

**Issue by MartinCamen** [zo0r/react-native-push-notification#583]
Everything is working fine as long as the device isn't locked. I've tried back and forth multiple times and I have had it working, but since I made *some* change I won't get notifications whilst the device is locked.

This is my settings:

```
PushNotification.configure({
    onRegister: function(token) {
        UserStore.storeDeviceToken(token)
    },

    onNotification: function(notification) {
        if (notification) {
            PushHandler.notificationReceived(notification)
        }
    },

    permissions: {
        alert: true,
        badge: true,
        sound: true
    },

    popInitialNotification: true,
    userInteraction: true,
    requestPermissions: true
})
```

**Comment by tronin** [comment]
Hm, try to check application notification permissions in your iOS settings. It is the first thing what I've thought when saw your question. 

I used this plugin and everything is ok
