### ISSUE TITLE
onNotification calls inconsistently 

### ISSUE THREAD

**Issue by andrei-m-code** [zo0r/react-native-push-notification#585]
I've been using react-native-push-notification library for quite some time for local notifications. Now I need remote silent notifications. Basically I send a notification that gets delivered to onNotification callback and I send local notification to the notification center.

**Android only**

I expect onNotification callback to trigger every time I receive notification and I open an app by clicking on notification. The problem is, depending on where I call PushNotification.configure({...}), it triggers onNotification when notification gets delivered OR when I click on it, but never both! My code:

```
// if here: calls onNotification when it's received
PushNotifications.configureNotifications();

export default class App extends React.Component {
    constructor(props) {
        // if here: calls onNotification when I click on it to open an app
        PushNotifications.configureNotifications();
        super(props);
    }

    render() { ... }
}

```
PushNotifications.configureNotifications() - it's just a simple wrapper over the library configure call. Yes, tried to keep it in both places - doesn't work. What am I doing wrong?

Yes I read this document https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md#3-silent-remote-push-notifications and silent push notifications section in particular.

I always send data payload to the app from the server.

https://stackoverflow.com/questions/46978190/react-native-push-notification-onnotification-callback-is-inconsistent

**Comment by calcazar** [comment]
This post couldn't have been more helpful!!!! seriously! 

It is true that you get 2 separate behaviors depending on where you add the code. It looks like it's related to mReactInstanceManager starting the react native app in the background and keeping it in an uninitiated state.

I wish I could figure out a way that would close the app in the background once all pushes have been received but my Java knowledge is limited

**Comment by calcazar** [comment]
https://product.farewell.io/visible-react-native-push-notifications-that-work-on-both-ios-and-android-5e90badb4a0f
