### ISSUE TITLE
recurring notifications send at the wrong time after DST change

### ISSUE THREAD

**Issue by TimoGlastra** [zo0r/react-native-push-notification#589]
I have local notifications setup for my app on Android and the Daylight saving time just went in here last week. After that all the notifications came one hour early. I have recurring notifications that will notify the user once a day on a predefined time.

If i cancel the notification and then set it again it will work fine, cause it has been adjusted to the right time.

I'm not familiar with Android development besides react-native, so is this a issue with this package? Or is this something Android developers should handle manually?

**Comment by karltaylor** [comment]
How are you setting the predinfed time?
