### ISSUE TITLE
Android: Is there any way to control if a notification vibrates and/or makes a noise?

### ISSUE THREAD

**Issue by hyperh** [zo0r/react-native-push-notification#59]
I want to give the users the option to turn on/off vibration and noise from a local notification in Android. I haven't seen anything in the docs that mentions that.

**Comment by codyhazelwood** [comment]
Also the ability to set a custom sound would be nice

**Comment by npomfret** [comment]
https://github.com/zo0r/react-native-push-notification/issues/84

**Comment by npomfret** [comment]
Custom sound is implemented is master now, but not released yet.  Would you be able to help test it before we push the release?

**Comment by codyhazelwood** [comment]
Yes, I'll try to get to it tonight.  Thanks!

**Comment by codyhazelwood** [comment]
Sorry, I'm not going to be able to test it for a while.  I'm still back on RN 0.26.0, and have way too many dependencies that break by moving to the latest RN.

**Comment by codyhazelwood** [comment]
@npomfret I can confirm custom sounds are working for Android.  Thanks!

**Comment by npomfret** [comment]
@hyperh do you still have this issue?  if so, have you tried the latest release?  if not, can we close it?

**Comment by hyperh** [comment]
@npomfret I haven't tried it, the project I was working on that used this library was canceled, so if someone else has confirmed the fix you can go ahead and close it. Thanks!

**Comment by Ilario17** [comment]
I've the same issue.. on iOS its ok but on Android I can't mute or remove vibration of the push notification changing the payload in php like: 
{
  ...
  sound: 'nosound',
  vibrate: 0
}

the app seems to ignore these settings..
