### ISSUE TITLE
Set badage 0/remove existing badage 

### ISSUE THREAD

**Issue by salimbutex** [zo0r/react-native-push-notification#591]
Well,
First of all thanks a lot for this awesome library. It's working really great. 
I am having a little issue. I am sending remote notifications. After receive it, user enter into app. 
I want when user leave app, badge will be 0 in app icons...

PushNotification.localNotification({
            number:4,
          });

this worked great...
PushNotification.localNotification({
            number:0,
          });

but this is not working. In short I want to make badge 0, when user leave app. 

thanks for any ideas...

**Comment by tronin** [comment]
You can use ```setApplicationBadgeNumber``` if you want. But would be better to look into the source code for Android https://github.com/zo0r/react-native-push-notification/blob/master/component/index.android.js

And API for iOS https://facebook.github.io/react-native/docs/pushnotificationios.html

**Comment by salimbutex** [comment]
thanks for your response. 
I am working for ios. I have checkout https://facebook.github.io/react-native/docs/pushnotificationios.html
But unfortunately did not get any reference of setApplicationBadgeNumber
or did nit get any  function to make badage 0.
Can u give me any reference setApplicationBadgeNumber?

**Comment by tronin** [comment]
@salimbutex please close the issue, if you can. Thank you!

**Comment by RedkoVO** [comment]
PushNotification.setApplicationIconBadgeNumber(0) - works for iOS only!
