### ISSUE TITLE
How to check if local notification is showing

### ISSUE THREAD

**Issue by andreassavva** [zo0r/react-native-push-notification#593]
I am developing an app that sends a local notification every 5 minutes. I want to check whether the previous notification is still showing on the phone so that I don't send more and spam the user. Is there a way to do that?

**Comment by tronin** [comment]
It's not possible while user didn't react to notification before. Maybe you can play with category/group but I'm not sure.

**Comment by Cygnus2112** [comment]
> you need to implement state controller inside onNotification method

Please elaborate, @sitompul
