### ISSUE TITLE
More detailed documentation on each field

### ISSUE THREAD

**Issue by James2516** [zo0r/react-native-push-notification#595]
Under `localNotification`:
```
    ticker: "My Notification Ticker", // (optional)
    autoCancel: true, // (optional) default: true
    largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
    smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
    tag: 'some_tag', // (optional) add tag to message
    group: "group", // (optional) add group to message
    ongoing: false, // (optional) set whether this is an "ongoing" notification

    /* iOS only properties */
    category: // (optional) default: null
```
Can anyone explain what these fields do? I played around with them, don't seem to notice any difference.

**Comment by leoskyrocker** [comment]
I had to dig all the way through to the Android Documentation to understand what `autoCancel` does.
And yeah it'd be nice if we can come up with more documentation on these fields, so here's one of them:
> Setting this flag will make it so the notification is automatically canceled when the user clicks it in the panel.
