### ISSUE TITLE
Local Notification is not working on background

### ISSUE THREAD

**Issue by sitompul** [zo0r/react-native-push-notification#601]
My code is shown below

```
PushNotification.configure({
  onNotification: (notification) => {
    Actions.notifications();
  },
  popInitialNotification: true,
  requestPermissions: true,
});

componentDidMount() {
if (Platform.OS === 'android') {
      setTimeout(() => {
        PushNotification.localNotification({
          title: 'Something happened',
          message: 'Notification Message',
          foreground: false,
          userInteraction: true,
        });
      }, 5000);
    }
}

```

**Platform : Android
RN : 0.46.4
RN Notification: 3.0.1**

**Comment by RailtonMatthew** [comment]
Hi, did you close this because it is now working?  If so then how did you fix it?

Thanks,

**Comment by sitompul** [comment]
@RailtonMatthew add this to your main React Component

```
import PushNotification from 'react-native-push-notification';
import { AppState } from 'react-native';

const onNotification = notification => {
  // Your on notification function
};

PushNotification.configure({
  onNotification,
  popInitialNotification: true,
  requestPermissions: true,
});

const appStateListener = (state) => {
  if (state === 'active') {
    PushNotification.popInitialNotification((notification) => {
      if (notification) {
        onNotification(notification);
      }
    });
  }
};

AppState.addEventListener('change', appStateListener);
```

**Comment by RailtonMatthew** [comment]
Thanks, this is a little different to my code so will try and see if it helps.

Are you just using localNotification or localNotificationSchedule?  I'm scheduling and having inconsistent results.  My flow is as follows:

1) When app goes into background call localNotificationSchedule with id='2222'
2) When app is opened clear notifications using PushNotification.cancelLocalNotifications({id: '2222'});

I tried without specifying an id and using cancelAllLocalNotifications but I get a red error screen if a notification has not been scheduled.

Thanks again for your help.

**Comment by sitompul** [comment]
@RailtonMatthew your **PushNotification** will always be replaced by the new **PushNotification** object everytime your app went background, so it will lose its config/state, to prevent this i add a **appStateListener**. Have you tried to implement the **appStateListener**?

**Comment by RailtonMatthew** [comment]
Yes, I have the listener.  The issues I've been having is that the notification does not appear at all.

**Comment by RailtonMatthew** [comment]
I've uninstalled the app, rebooted phone and it seems to working now.  Fingers crossed it will stay that way. :)

**Comment by bwoodlt** [comment]
@sitompul Did you attach the appStateListener to a lifecycle method? I implemented similar as what you have, but when my app goes in background or device is locked, I don't receive notifications. Any thoughts?

**Comment by sitompul** [comment]
@bwoodlt as you can see from my code above i **did NOT** attach it to a life-cycle method.

Can you elaborate with your code?

It seems like your method is affected by react lifecycle

**Comment by bwoodlt** [comment]
@sitompul have got this code in my PushNotification.js file. `const PushNotification = require('react-native-push-notification');

PushNotification.configure({

  onNotification: (notification) => {
    if (!notification.userInteraction) {
      PushNotification.setApplicationIconBadgeNumber(0);
    }
    if (notification.foreground) {
      PushNotification.setApplicationIconBadgeNumber(0);
    }

    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },
  popInitialNotification: true,

  requestPermissions: true,
  'content-available': 1
});
`

And when using, I use like so:
`PushNotification.localNotification({
              title,
              message
            });`

I also have in my `componentDidMount()` this bits:
`  componentDidMount() {
    this.props.subscribeToNewLikes();
    if (!IS_SIGNED_IN) {
      IS_SIGNED_IN = true;

      navigation.navigate('LoginScreen');
    }
    AppState.addEventListener('change', (state) => {
      if (state === 'active') {
        PushNotification.popInitialNotification((notification) => {
          if (notification) {
            Alert.alert(notification);
            // onNotification(notification);
          }
        });
        PushNotification.setApplicationIconBadgeNumber(0);
      }
    });`

I get notifications when app is in background but not when device is locked or not active. I'm probably missing something..

**Comment by sitompul** [comment]
@bwoodlt it looks like that you **did not follow** my instruction
**do not** put it inside a react native lifecycle method
your main component code supposed to be like this

```
import PushNotification from 'react-native-push-notification';
import { AppState } from 'react-native';
import React from 'react';

const onNotification = notification => {
  // Your on notification function
};

PushNotification.configure({
  onNotification,
  popInitialNotification: true,
  requestPermissions: true,
});

const appStateListener = (state) => {
  if (state === 'active') {
    PushNotification.popInitialNotification((notification) => {
      if (notification) {
        onNotification(notification);
      }
    });
  }
};

AppState.addEventListener('change', appStateListener);

class MainComponent extends React.Component {
  componentDidMount() {
    //some action
  }
  render() {
    //your render method
  }
}

export default MainComponent;
```

**Comment by jenalgit** [comment]
> @RailtonMatthew add this to your main React Component
> 
> ```
> import PushNotification from 'react-native-push-notification';
> import { AppState } from 'react-native';
> 
> const onNotification = notification => {
>   // Your on notification function
> };
> 
> PushNotification.configure({
>   onNotification,
>   popInitialNotification: true,
>   requestPermissions: true,
> });
> 
> const appStateListener = (state) => {
>   if (state === 'active') {
>     PushNotification.popInitialNotification((notification) => {
>       if (notification) {
>         onNotification(notification);
>       }
>     });
>   }
> };
> 
> AppState.addEventListener('change', appStateListener);
> ```

Bang ada tutorialnya ga,,, baru di RN nih.. butuh notif pas lagi ga dibuka appnya
