### ISSUE TITLE
Found Error in IOS "Native Module cannot be null"

### ISSUE THREAD

**Issue by manoj2166** [zo0r/react-native-push-notification#603]
Hi 
I am using it for local notification on my ios device. In Android device working fine but in ios giving me error of "Native module cannot be null"
![simulator screen shot - ipad pro 9 7-inch - 2017-12-04 at 18 46 15](https://user-images.githubusercontent.com/12066525/33554617-7d648ee0-d923-11e7-9fb1-cba0620b7927.png)

**Comment by SamiChab** [comment]
This issue already exists: #501 #279

**Comment by GastonEDiaz** [comment]
In you folder ios find the proyect .xcworkspace and delete. Build your .xcodeproj

**Comment by manoj2166** [comment]
Fixed it by manual link. React-native link only able to link in android not for iOS you have to manually link this for ios.
Working fine for me after manual link

**Comment by askarhu** [comment]
Linking manually for iOS solved the issue for me as well. It's fairly easy, but the documentation has to explicitly mention this manual need, as the node-modules folder only has an Android folder and nothing for iOS and also when you run `react-native link` it confirms linking for Android only.

**Comment by nuvorm** [comment]
hello
