### ISSUE TITLE
How to use ID?  Does it need to be unique or not?

### ISSUE THREAD

**Issue by RailtonMatthew** [zo0r/react-native-push-notification#604]
I'm having issues on Android with local notifications not always working.  From the documentation is it unclear on how the id should be used.

In my app I use the local push notification to indicate when an action needs to happen when the app is in background.  My questions are as follows:

1) Can the id be fixed, i.e. always use the same value, such as 12345, when scheduling the notification or does it need to be different each time it is scheduled.
2) Currently I use a fixed value and use PushNotification.cancelLocalNotifications({id: '12345'}); when the app changes to foreground.  This is to avoid notifications when the app is being used.  Is this the correct approach?
3) If using a unique number for each call then would I need to track the numbers that have been used and cancel them by referencing the id?
4) Currently I get intermittent errors is I use PushNotification.cancelAllLocalNotifications();  The error is: Invalid int: "pcNotification"

Any guidance on the above is much appreciated.

Thanks.

**Comment by dccabao** [comment]
No reply for this? Sad.
