### ISSUE TITLE
notification will not popup if app is in the foreground

### ISSUE THREAD

**Issue by majd-kho** [zo0r/react-native-push-notification#607]
When I receive notifications in the background they popup with no issues.
However, when I am using the app, the push notification will not pop up.
Is there a way to configure it to popup ?
Thanks!

**Comment by EzeRangel** [comment]
As far as I know this is the default behaviour, perhaps you could throw a localNotification when you receive the data in the `onNotification` callback.

**Comment by majd-kho** [comment]
@EzeRangel  I will give that a try, thanks!

**Comment by witalobenicio** [comment]
@majd-kho did you solve that? How to show if the app is in the foreground?

**Comment by majd-kho** [comment]
@witalobenicio I tried what @EzeRangel  suggested, and pushed a local notification when a  remote notification is pushed and the app is in the foreground.

**Comment by witalobenicio** [comment]
@majd-kho So if the app is on foreground there is open there is no way to show a notification?

**Comment by witalobenicio** [comment]
@majd-kho I tried to show a local notification when I get a notification from server, but it didn't work. Just doesn't show nothing.

**Comment by 1nfinity-5starZ** [comment]
@EzeRangel Thanks, that solved it for me !
