### ISSUE TITLE
Question: What's a good pattern on repeated local notifications?

### ISSUE THREAD

**Issue by jeveloper** [zo0r/react-native-push-notification#615]
Hi all

Just wanted to get an idea what would be a good way of implementing local notifications that would appear every day at a particular time.

I understand that i can schedule multiple all at once. Or is there a another way?

thanks

**Comment by kckunal2612** [comment]
I guess you can schedule a notification for the next day in the "onNotification" method when configuring this component. That ways, everytime a notification is received, a new notification is automatically scheduled for the next day.

**Comment by jeveloper** [comment]
hey @kckunal2612  , that would be a terrible code :)  , ill have to identify what message was sent as i dont want to schedule more than once for the same day :) 

in RN ios implementation there is a repeat type property but this is not exposed through this library unfortunately , hence im looking for a work around.

**Comment by dluksza** [comment]
I'm scheduling notification for each day of week with given time and `repeatType` set to `week`. It works on iOS and Android

**Comment by jeveloper** [comment]
hey @dluksza  , i thought this lib hasn't merged that pull request which added a property repeatType. Are you confirming that this lib has that property and it passes it through properly?

Thanks

**Comment by dluksza** [comment]
Are you referring to this commit https://github.com/zo0r/react-native-push-notification/commit/90c77d2742e0754f3c50ff0c8b0d9cb09e5eff65 it was merged and works for me on both platforms.

**Comment by jeveloper** [comment]
Yes, ohh i thought it was not working

Thank you again !!

**Comment by SSTPIERRE2** [comment]
Hi all!

I've got something like ``` PushNotification.localNotificationSchedule({ date: new Date(), repeatType: 'minute' }); ``` working on both platforms like @dluksza said. But I'm wondering if you can further control the repeat interval using repeatType and repeatTime (in milliseconds as the docs suggest) with this method. Anyone try something like that? Thanks!

**Comment by jeveloper** [comment]
@SSTPIERRE2 Hey Steve, yes that would be an anti-pattern, ideally you should control all of that from the backend where you can take into consideration timezones and also support multiple devices linked to your user account
