### ISSUE TITLE
notification.finish is not a function

### ISSUE THREAD

**Issue by andreassavva** [zo0r/react-native-push-notification#618]
In the `README.md` file it says that it is required to call `notification.finish(PushNotificationIOS.FetchResult.NoData);` at the end of the `onNotification` function, in `PushNotification.configure`.

I get the error on an iPhone that this function does not exist.

**Comment by andreassavva** [comment]
My bad, I realized I didn't have the latest version.

**Comment by FunkyGeorge** [comment]
This thread actually helped me still.  notification.finish is not a function was an error on package version 3.0.1 but I just updated to 3.0.2 and that seemed to fix it.
