### ISSUE TITLE
iOS local notification in the foreground mode doesn't show notification!

### ISSUE THREAD

**Issue by zootopia106** [zo0r/react-native-push-notification#619]
Hello, @zo0r .
I am now using this library for local notification functions and it's not showing the notifications when the app is in foreground mode.
Can you teach me how to show notification in foreground mode?
Thanks

**Comment by damir-sirola** [comment]
This library uses React Native implementation of push notifications on iOS so consult with their documentation (https://facebook.github.io/react-native/docs/pushnotificationios.html) or open an issue on React Native repository

**Comment by zootopia106** [comment]
I checked for that. but there was no answer on react native.
In native ios development, there was a solution and that's why I thought RN can also have its own solution.

**Comment by hszeto** [comment]
I have same issue on iOS. When the app is active, the notification doesn't show... However, onNotification did trigger... when the app is in background, the notification shows. 

any idea?

**Comment by hugoh1995** [comment]
I have the same issue I'm trying to figure it out.

**Comment by bwoodlt** [comment]
Anyone able to solve this issue? Having similar issue..

**Comment by joaom182** [comment]
@zootopia106 iOS 10+ change this behavior. The notifications will show on notification center only if app is killed or in background. When app is in foreground, will fire the event `onNotification`, but not show in notification center, so you need implement you own way to notify the user in this case.

**Comment by SabriLachihab** [comment]
I use this code 
``` PushNotification.configure({

  // (required) Called when a remote or local notification is opened or received
  onNotification: function (notification) {
    if (notification.foreground) {
      Alert.alert(notification.message)
    }
    console.log(notification)
    // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
    if (Platform.OS === 'ios') {
      notification.finish(PushNotificationIOS.FetchResult.NoData)
      PushNotification.localNotificationSchedule({
        title: 'Hello'
        message: 'World'
        number: 1,
        date: new Date(Date.now() + (10 * 1000)), // in 10 secs
        foreground: true,
      })
    }
  },
  permissions: {
    alert: true,
    badge: true,
    sound: true
  },
}) ```

So the notification doesn't work on foreground ?
Why ???

**Comment by SFRohan** [comment]
This will work for you. Notification will be shown when the app is in background and also when it's in foreground (open) :
```

FCM.on(FCMEvent.Notification, notif => {
            // if (notif.fcm && notif.fcm.body) {
            /* Create local notification for showing in a foreground */

            console.log("  >> notificationListener: ", notif)
            console.log(" success register fcm >> notificationListener: ", notif)

            if (notif.local_notification) return;
            FCM.presentLocalNotification({
                body: notif.fcm.body,
                priority: "high",
                title: notif.fcm.title,
                sound: "default",
                show_in_foreground: true,
                local_notification: true,
                "large_icon": "ic_launcher",// Android only
                icon: "ic_launcher",
                "show_in_foreground": true, /* notification when app is in foreground (local & remote)*/
                vibrate: 300, /* Android only default: 300, no vibration if you pass null*/
                "lights": true, // Android only, LED blinking (default false)
                status: "400"
            });
        })
```

**Comment by SFRohan** [comment]
` local_notification: true`

has been added to avoid infinite loop of messages on iOS device.

**Comment by zootopia106** [comment]
Thanks for your help , @SFRohan 
If so, do i have to integrate FCM apart from this library?

**Comment by SFRohan** [comment]
Hi @zootopia106 , yes you would need to integrate FCM for this from "react-native-fcm"

**Comment by zootopia106** [comment]
@SFRohan , do you mean, I don't need to use the "react-native-push-notification" library?

**Comment by zootopia106** [comment]
make sense what you mean, 
Thanks, @SFRohan

**Comment by SFRohan** [comment]
You're welcome @zootopia106 
Cheers.

**Comment by zedtux** [comment]
I'm looking for a working solution for local notifications. Anyone found a way to make them working ?

**Comment by amitassaraf** [comment]
For anyone who came across this thread, someone found a solution for this problem on a separate thread in this project.

[Fix for foreground notifications on iOS](https://github.com/zo0r/react-native-push-notification/issues/275#issuecomment-333907923)

Enjoy <3

**Comment by joaom182** [comment]
Same issue on Android

**Comment by zedtux** [comment]
Here we are! The bot game has started 🤦

**Comment by Dallas62** [comment]
Hi @zedtux,
Glad to see you are still active on this issue.
Bot is there to filter old issues and focus on current developer needs and avoid spend too much times on the initial 650 issues + 75PRs.
The Stale bot is configured to notify issues/PR without activity for 1 year, which is long enough. Then developers have 1 month to notify if the issue is still required, which is again long enough.
If you have time to spend on filtering issues, I will disable the bot and let you filter them 😉 

By looking at this issue, I see it's related to iOS, so you should probability take a look to this repository:
https://github.com/react-native-community/push-notification-ios
Since it's the library used for iOS.

If this error is about Android, I think it has been solved in recent changes. If not please open a new issue.

**Comment by zedtux** [comment]
Yeah ... the problem with the bots is that very often it's the repo's maintainers which aren't giving updates, and we (the requesters) are fighting with those stupid bots to not get our issues closed.

Whatever 🤷
