### ISSUE TITLE
Not receiving notifications after long period of inactivity with app

### ISSUE THREAD

**Issue by hyperh** [zo0r/react-native-push-notification#62]
I'm not receiving notifications after I stop using the app for a while. Once I start using the app, any new notifications will come in as expected. But the one sent before I started using it again is never received.

**Comment by npomfret** [comment]
@hyperh do you still have this issue?  if so, have you tried the latest release?  if not, can we close it?

**Comment by hyperh** [comment]
@npomfret I haven't tried it, the project I was working on that used this library was canceled, so if someone else has confirmed the fix you can go ahead and close it. Thanks!
