### ISSUE TITLE
InvalidRegistration onRegister(registration.token)

### ISSUE THREAD

**Issue by jaysmoodge** [zo0r/react-native-push-notification#620]
Im getting this error.
![image](https://user-images.githubusercontent.com/35086221/34547582-276f4814-f137-11e7-9408-a095ff0ce866.png)

**Comment by avinashwigroup** [comment]
Did you solve it ?

**Comment by jaysmoodge** [comment]
Hi, didn't solve it actually, but i change from GCM to FCM then got it worked.

**Comment by arifdegozaru** [comment]
got the same error, does anyone solve this?
