### ISSUE TITLE
Could not invoke RNPushNotification.presentLocalNotification.

### ISSUE THREAD

**Issue by vvavepacket** [zo0r/react-native-push-notification#622]
I am getting the following error everytime my Android device received a notification

![image](https://user-images.githubusercontent.com/8295642/34645339-530f7056-f318-11e7-84c8-26faca64b871.png)

I am using:

    compileSdkVersion 26
    buildToolsVersion "26.0.2"

Anyone encountered the same?

**Comment by Hanzig** [comment]
@vvavepacket , try importing PushNotificationIOS from react-native
https://github.com/zo0r/react-native-push-notification/pull/617

**Comment by davidrochin** [comment]
I have the same problem and @Hanzig suggestion did not work. Did you find a solution @vvavepacket ?
