### ISSUE TITLE
Opt out GCM for local notification

### ISSUE THREAD

**Issue by piu130** [zo0r/react-native-push-notification#624]
In the [installation instruction](https://github.com/zo0r/react-native-push-notification#android-manual-installation) for android you add `play-services-gcm`.

If I only use local notification, which lines of code do I need? Is it possible to remove `gcm service`?

**Comment by Rudloff** [comment]
Hello,

I would also be interested in a way to build this library without Play Services.
The Play Services dependency prevents any app using this library from being included in free software repositories like [F-Droid](https://f-droid.org/).

Would it be possible to have an option to build without the `play-services-gcm` dependency? (Even if it means that only local notifications would work.)

**Comment by piu130** [comment]
I found [this](https://github.com/zo0r/react-native-push-notification/issues/639) post but I don't know if its still up-to-date.

I think the project should be a bit more modular and we should have some shares components and a local and push notification library. When I used this project a year ago it was kind of dead. I don't know if this is still the case.
