### ISSUE TITLE
Android: Notifications actions doesn't work when app is not running

### ISSUE THREAD

**Issue by dluksza** [zo0r/react-native-push-notification#626]
I've followed the documentation, added `actions` property to notification data. Also added listener for `notificationActionReceived`. Everything works fine... when app is running (either in foreground or background). But when it is not active (eg. was stopped/killed by user) tapping on notification action doesn't work.

In such case notification stays in place and nothing happen. It is not dismissed nor executed.

Do I missing something eg. in AndroidManifest or another listener?

/cc @varungupta85

**Comment by eddnav** [comment]
Same issue

**Comment by dluksza** [comment]
You can try my PR, it fixes this issue.

**Comment by dluksza** [comment]
BTW. Read through readme first, it requires some modifications in app code.

**Comment by vishalmanohar** [comment]
@dluksza So you were able to get notfications (not actions) to show when app was killed?  I am able to get notifications to show when app is running/background but not when it was killed. Can you please document your config and the notification message? TIA.

**Comment by dluksza** [comment]
Yes, I'm getting notifications on Android when app is not running. The data structure (aka message configuration) that I'm passing to `PushNotification.localNotification` function, has `number` property set to a `"1"` (yes, this is a number within a string). Don't remember exactly what this was fixing, but for sure I had some issues with notifications working properly.

**Comment by adirzoari** [comment]
@dluksza can you show example how you get notifications when app is not running? I'm get notification only when app is running.

**Comment by vvavepacket** [comment]
@dluksza I second this. I also encounter this issue. When app is in background, push notifications are triggered. However, when it is forced closed and killed. It is not coming anymore. Can you elaborate more on the fix you found?

**Comment by dluksza** [comment]
@adirzoari, @vvavepacket have a look into the readme file of my fork https://github.com/dluksza/react-native-push-notification/#notification-actions 

BTW. I've reimplemented this feature in `react-native-firebase` where it was merged and has a decent documentation how to use it https://rnfirebase.io/docs/v4.2.x/notifications/android-actions

The key in both cases is the exported service that listens for incoming actions from the notification.
