### ISSUE TITLE
Is it possible to open the app automatically when GCM message received?

### ISSUE THREAD

**Issue by bemaxima** [zo0r/react-native-push-notification#627]
Hello;

Consider a video call app, I need to **open my app immediately** after a GCM message (calling signal) received.

I didn't find any documentation about this requirement. Does this repo support such a requirement?

thanks.

**Comment by thevolcanomanishere** [comment]
This isn't possible. You can pass information to an application and the app can do something with that data when it is opened, but you cannot trigger the app to open an app automatically

**Comment by noambonnie** [comment]
I can't provide much information but do note that those using react-native-navigation library were experiencing a bug on android only where the app would launch when a notification is received. So it looks like it is possible. Maybe if you dig more into what react-native-navigation does you'll find clues.

https://github.com/zo0r/react-native-push-notification/issues/470

**Comment by grit96** [comment]
This might be a solution if you're still looking for one: https://github.com/lvlrSajjad/react-native-launch-application.
