### ISSUE TITLE
Can't build for Android probably due to a conflict of Google Play Services

### ISSUE THREAD

**Issue by victorsferreira** [zo0r/react-native-push-notification#628]
I setup my app with 'react-native-firebase' to receive the notifications. The problem now is that I have to find a way to show the notifications

I installed react-native-push-notifications and now I cant build the prpject anymore. I get the error at 96%

" UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define"

It seems to be a conflict with the two libraries. How can i fix it?

**Comment by wmonecke** [comment]
I have the same:
```
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/zzb$zza;
```

**Comment by evezzaro** [comment]
For anybody looking for an answer. 

I solved this problem by replacing:

    compile ('com.google.android.gms:play-services-gcm:8.1.0') {
        force = true;
    }

with: 

    compile ('com.google.android.gms:play-services-gcm:11.8.0') {
        force = true;
    }

in android/app/build.gradle.
