### ISSUE TITLE
Silent local notifications

### ISSUE THREAD

**Issue by supercamilo** [zo0r/react-native-push-notification#630]
Is there any way to schedule **silent** local notifications?

I'm looking for a way to cancel the "visible" alerts when scheduling a local notification so I can handle the UI myself.

The `onNotification` callback is only triggered when I click the alert on the notification center and not when the notification is received as stated in the [docs](https://github.com/zo0r/react-native-push-notification#handling-notifications).

At least, is there a way to trigger the  `onNotification` callback for local notifications without the user having to click on the alert?

**Comment by amazingmarvin** [comment]
It's not possible to have silent local notifications.  But you can have `onNotification` called without user interaction *if* the app is in the foreground.  See #574.

```
npm install --save https://github.com/ErikMikkelson/react-native-push-notification#af7357844f3e5965d4a97f23fe447dc851d1cd32
```

**Comment by supercamilo** [comment]
Thanks @amazingmarvin!, that works exactly as expected when the app is in the foreground or background.

**Comment by amazingmarvin** [comment]
Great! You're welcome :).
