### ISSUE TITLE
Is this package actually working cross-platform or being maintained?

### ISSUE THREAD

**Issue by wmonecke** [zo0r/react-native-push-notification#633]
I tried for a whole day to install this package just to be confronted by tons of issues. It seems to work on iOS but not so much for Android. Just installed it on an Android device just for it to crash once you tap the app. Is this being maintained at all?

If this is the first package that appears in google search for push notifications in RN, at least update the README or notify that it is not being maintained. Wasted too much time on this.

**Comment by danyim** [comment]
Experiencing the same thing when attempting to put this plugin in a Android-targeted RN app.

**Comment by froatsnook** [comment]
I've been using 2.2.1 in production for more than a year on Android and have 99.19% crash-free sessions (and my crashes seem unrelated to react-native-push-notification)!  Possibly you did it wrong?  I have another app on the latest version that also runs without crashing, although there I'm currently only using local notifications.

**Comment by lucasltv** [comment]
Did someone run it in the background?

@froatsnook, did you?

Thanks!
