### ISSUE TITLE
Looking for documentation or a guide for onNotifications (or crowdsourcing info for writing one)

### ISSUE THREAD

**Issue by arnthorsnaer** [zo0r/react-native-push-notification#634]
Hi there

Can anybody point me in the right direction?
I'm looking for a reference / doc og a guide on using foreground and userInteraction to deal with incoming notifications on iOS and Android platforms.

This should of course not be complicated but the documentation is pretty sparse on this and I'm finding contradicting info from users in the issues here.

In short I want to discover the intended behaviour for both platforms and the following scenarios. When notification arrives (and onNotification is called) the app can be in three states, in foreground, in background or simply not active (user has killed it or phone reboot). Also when user taps the notification the app is opened and presumably onNotification is called again. 

So what I would expect to be able to find is a guide / reference that enumerates each state and how I as an developer can discover the state through the variables provided.

If nothing like this exists I would be happy to write something up and contribute it to this project but I prefer to crowdsource as much info as I can be

**Comment by arnthorsnaer** [comment]
So far this is what I'm finding when got my device hooked up to Xcode and sending notifications through the sandbox APN.

Notification is delivered when the app is open (foreground) 
* onNotification receives:
`{"foreground":true,"userInteraction":false ...}`

Notification is delivered when user has home screen open / app was recently closed
* onNotification receives:
`{"foreground":false,"userInteraction":true ...}`

Notification is delivered when user has lock screen open / or display is turned off
* onNotification receives:
`{"foreground":false,"userInteraction":true ...}`

When user taps the notification from lock screen or home screen
* onNotification receives:
{"foreground":false,"userInteraction":true ...}


Now let's look at the definition of both of these attributes from the readme:

> foreground // BOOLEAN: If the notification was received in foreground or not

This seems to check out although there is a way to write this out to be less ambiguous.

>userInteraction // BOOLEAN: If the notification was opened by the user from the notification area or not

Here is where this goes south. This value is true in a few cases where the notification was *not* opened by the user - yet it remains true. Either userInteraction is buggy or the docs are.

So what's the damage here? 
Well - my code in onNotification can not really be sure if the user is interested or not in viewing the "article" that just got pushed. So my options currently appear to be that I either respond to none of these or all of them.

**Comment by nickabb** [comment]
Hey @arnthorsnaer, I was just skimming through the code and you're right: foreground and userInteraction are actually just opposites of each other.  Seems like these are more just for clarity, (although it may just end up being more confusing).

This snippet of code begins on line 217 of index.js

```
	if ( this.onNotification !== false ) {
		if ( Platform.OS === 'ios' ) {
			this.onNotification({
				foreground: ! isFromBackground,
				userInteraction: isFromBackground,
				message: data.getMessage(),
				data: data.getData(),
				badge: data.getBadgeCount(),
				alert: data.getAlert(),
				sound: data.getSound(),
  			finish: (res) => data.finish(res)
			});
```
