### ISSUE TITLE
Notification not fired when device is locked or app in background

### ISSUE THREAD

**Issue by bwoodlt** [zo0r/react-native-push-notification#635]
Hi all,

Have been struggling with this for a few hours. Local push notification not firing when on home screen and when device is locked. This is on iOS. 

Anyone been able to solve this issue? Please help a brother.

Thanks all,

**Comment by bwoodlt** [comment]
@IgorUsoltsev did you set 'content-available' inside your PushNotification.LocationNotification({ "content-available" : 1}}?

**Comment by bwoodlt** [comment]
Here's my code and setup:

Have got this code in my PushNotification.js file. 

```
  const PushNotification = require('react-native-push-notification');

   PushNotification.configure({

   onNotification: (notification) => {
    if (!notification.userInteraction) {
      PushNotification.setApplicationIconBadgeNumber(0);
    }
    if (notification.foreground) {
      PushNotification.setApplicationIconBadgeNumber(0);
    }

    notification.finish(PushNotificationIOS.FetchResult.NoData);
    },
    popInitialNotification: true,

  requestPermissions: true,
  'content-available': 1
});

```

And when using, I use like so: 
```
PushNotification.localNotification({
              title,
              message
            });
```

I also have in my `componentDidMount()` this bits:
```
 componentDidMount() {
    AppState.addEventListener('change', (state) => {
      if (state === 'active') {
        PushNotification.popInitialNotification((notification) => {
          if (notification) {
            Alert.alert(notification);
            // onNotification(notification);
          }
        });
        PushNotification.setApplicationIconBadgeNumber(0);
      }
    });
```

I get notifications when app is in background but not when device is locked or not active. I'm probably missing something..

**Comment by IgorUsoltsev** [comment]
@bwoodlt I send them from my backend server. But I guess this could work from local notification as well.

As for your locked/not active device - I didn't meet this issue as I use APN/GCM to send messages. And they come as generic push notifications that you can open anytime and launch app.

**Comment by getabatu** [comment]
change your 'active' to 'backgroud'

**Comment by zhaonian** [comment]
@bwoodlt How did you solve this issue?

**Comment by tijp** [comment]
I had the same issue because the 'Do Not Disturb' feature on my iPhone was turned on. When turning that off it worked again.

**Comment by vijayapios** [comment]
i also getting same issue, can any one help me out
