### ISSUE TITLE
Why do you set all android notification category as CATEGORY_CALL?

### ISSUE THREAD

**Issue by jordenchang55** [zo0r/react-native-push-notification#640]
I notice that you write ```notification.setCategory(NotificationCompat.CATEGORY_CALL);``` in android native module. This will cause that every notifications are treated as incoming call notification. Under some conditions, this will misleading the target that will receive the notification.
For example, I created a app which needs to send calendar event notification, but the category is CATEGORY_CALL instead of CATEGORY_EVENT. Strange, isn't it?

Is this setting for some special purpose?
Or category setting should be exposed as a parameter?

**Comment by rocboronat** [comment]
Well done React Native 👏👏👏👏👏👏
