### ISSUE TITLE
Can not push notification on the token generated by onRegister But through FCM

### ISSUE THREAD

**Issue by talhamuhammadashraf** [zo0r/react-native-push-notification#643]
`react-native-push-notification` is using gcm for token but when i used the token generated by gcm , i was unable to send push notification through firebase function ,but when i used the token generated by fcm (which was different) ,that enabled messaging but **twice** ,one through fcm and other through gcm but using the token generated by fcm,**that mean gcm token not working while using firebase notifications**

**Comment by xinlangzi** [comment]
I am facing the same challenge. Please help. Thank you.

```
 RNPushNotification failed to process intent Intent { cmp=com.practicalstrategies.tz/com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService (has extras) }
 java.io.IOException: SERVICE_NOT_AVAILABLE
     at com.google.android.gms.iid.zzl.zzb(Unknown Source)
     at com.google.android.gms.iid.zzl.zza(Unknown Source)
     at com.google.android.gms.iid.InstanceID.zzb(Unknown Source)
     at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
     at com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService.onHandleIntent(RNPushNotificationRegistrationService.java:26)
     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:145)
     at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by talhamuhammadashraf** [comment]
@xinlangzi i have used `react-native-fcm` package and removed gcm added by `react-native-push-notification` ,problem solved

**Comment by xinlangzi** [comment]
I just tried to move to `react-native-fcm` but I have some challenge on google-service version. Do you have sample code I can see what happen in my code? I still can't make it work well.

**Comment by talhamuhammadashraf** [comment]
okay but you should check if fcm and gcm are coinciding that can cause duplicate

**Comment by xinlangzi** [comment]
This is my first time to use push notification. I don't know how to apply gcm sender id, I only apply fcm sender id. If there is gcm sender id, does that mean this plugin react-native-push-notification still work well? I did make it work well on IOS. 

Thank you for your reply!

**Comment by talhamuhammadashraf** [comment]
if usinf firebase no need to use this package

**Comment by xinlangzi** [comment]
I tried this `react-native-fcm`, then I have a plugin use google-service 11.8.0, but react-native-fcm only support google-service 11.4.2. The conflict made my app crash down if I downgrade all google-service to 11.4.2.

**Comment by xinlangzi** [comment]
@talhamuhammadashraf 

Can you share with me how you use react-native-fcm to setup running on your RN app?

Thank you very much!

**Comment by xinlangzi** [comment]
@talhamuhammadashraf 

I just made it work by using react-native-push-notification. I did register FCM send ID, but I have to go to my google developer account to link. then it works for me

![image](https://user-images.githubusercontent.com/1171370/35811735-33494a34-0aca-11e8-945f-5cf3554c46bd.png)

**Comment by fidoe** [comment]
@xinlangzi I'm facing the same issue you were facing, only it not work only in production (when use with react-native run-android it work!!!!??!?!).

I tried link sender ID with app on Android Play Store, but still onRegister never is called and I do not get a device token.  Did it take some time for it to work after you linked the ID?  I only did it a few hours ago.

**Comment by xinlangzi** [comment]
@fidoe 

Yes. It need some time to work after registering on FCM service on google.

**Comment by minhphung210** [comment]
@xinlangzi xin i have same problem . Have you resolved yet?
