### ISSUE TITLE
Prevent Android push notifications from relaunching app when closed

### ISSUE THREAD

**Issue by tmaly1980** [zo0r/react-native-push-notification#649]
I'm working with a project that utilizes react-native-push-notification with react-native-navigation as the nav system, and noticing an issue with Android, where the app will launch if it's closed when a notification gets received. 

There had been some discussion here about switching over to react-native-notifications, https://github.com/wix/react-native-navigation/issues/566, but also a semi-discussed solution to work around the issue. We're already very much invested in this library so we don't want to switch over to the wix version.

Effectively, this is what I have come up with, but there's a missing piece to determine whether or not the code was called from a push notification. 

index.android.js:

```
import { Navigation, NativeEventsReceiver } from 'react-native-navigation';
import { registerScreens } from './app/screens/registerScreens';
import logInNavigationConfig from './app/screens/logInNavigationConfig';

registerScreens();


function appOpenedFromPushNotification() {
    return false // ??? What goes here ???
}

Navigation.isAppLaunched()
  .then(appLaunched => {
    if (appLaunched || appOpenedFromPushNotification()) {
        startApp();
    } else {
        new NativeEventsReceiver().appLaunched(startApp());
    }

  });

function startApp() { // Start the app
    Navigation.startSingleScreenApp(logInNavigationConfig);
```

https://github.com/wix/react-native-navigation/issues/566#issuecomment-327404439 refers to appOpenedFromPushNotification(), but that was never actually discussed anywhere.

What am I missing?

**Comment by noambonnie** [comment]
@tmaly1980 As I said in the other thread, I just solved this by a boolean checking whether the app is already launched and ignoring it.

**Comment by tmaly1980** [comment]
@noambonnie My problem is a bit different, the app isn't even in the background - I have killed the app entirely. The push notification gets received, but it automatically opens the app regardless, even though I didn't press on the notification. 

How do I prevent the app from launching when it's receiving a push notification? I'm missing that functionality above

**Comment by noambonnie** [comment]
@tmaly1980 I think that depends on the type of notification you're sending. Silent notifications are supposed to launch the app in the background (otherwise why send them?). 

You may want Noisy remote notifications as described here: https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md

**Comment by tmaly1980** [comment]
OK, nevermind, it turns out that after my rehydration was complete, the app relaunched so it could remove the login screen and go to the user-only screens. I had to implement the headless code twice, once in my index.js and another in my rehydration reducer:

https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=compatibility-with-headlessjs

**Comment by witalobenicio** [comment]
@tmaly1980 You were able to prevent your app from relaunch? Every time I click in a notification, app is relaunched.

**Comment by alnsantosh** [comment]
@tmaly1980 I am facing the exact same issue which you have faced. The app starts automatically when the app is killed in background. How did you differentiate the cause of launch.. i.e., is it possible to differentiate the launch which occurs when we click on app icon , with the launch which occurs automatically when push notification is received?

**Comment by tmaly1980** [comment]
I'm specifically using react-native-navigation (not react-navigation), so I only call Navigation.startTabBasedApp based on the result of Navigation.isAppLaunched . That parameter determines if the user tapped on the icon on the home screen (true) or triggered from a push notification (false) . 

The one thing I do when it's manually launched is set a global variable somewhere, ie in my navigation config file..... my push notification handler checks whether that variable is set, which means the app is still open. If I close the app, then when the headless code loads, it will be the default and I can avoid triggering the navigation (UI). 

Not sure if that makes sense, it's very specific to my use case, and the code is scattered across several files, probably not very usable unless you're also using react-native-navigation

**Comment by alnsantosh** [comment]
@tmaly1980 Even I am using react-native navigation. I am completely new to react native and am figuring out a way to resolve this issue. I kind of understood what you meant but can you please elaborate and if possible please share the code snippet. That would be a great help.

**Comment by tmaly1980** [comment]
It's a lot of code.... Hopefully you can figure out what's relevant and what's not (I'd rather leave too much code than possibly omit anything)

App.js:
```
import React from "react";
import { Platform } from "react-native";
import { Navigation, NativeEventsReceiver } from "react-native-navigation";
import { registerScreens, setAppLaunched } from "./screens/registerScreens";
import logInNavigationConfig from "./screens/logInNavigationConfig";
import { Provider } from "react-redux";
import configureStore from "./store/configureStore";
import { PersistGate } from "redux-persist/integration/react";
import { onRehydrated } from "./reducers/rootReducer";

const { store, persistor } = configureStore();

const ProviderWrapper = ({ store, loading, children }) => (
  <Provider store={store}>
    <PersistGate
      loading={loading || null}
      persistor={persistor}
      onBeforeLift={() => onRehydrated(store.getState())}
    >
      {children}
    </PersistGate>
  </Provider>
);

registerScreens(store, ProviderWrapper);

function startApp() {
  // Start the app
  setAppLaunched(true); // We're launching the UI, so get rehydration to auto-login anyway.
  Navigation.startSingleScreenApp(logInNavigationConfig);
}

class App {
  constructor() {
    // Redux Persist configuration
    // codePush.sync();
    this.bootstrap();
  }

  bootstrap() {
    if (Platform.OS === "android") {
      // android push notifications should not open UI
      Navigation.isAppLaunched()
        .then((appManuallyLaunched) => {
          setAppLaunched(appManuallyLaunched);
          if (appManuallyLaunched) {
            startApp(); // App was launched directly (not push notifications) -> show UI
          } // otherwise, code is headless and got triggered from push notification handler
          new NativeEventsReceiver().appLaunched(startApp); // save launcher for when push notification gets clicked
        })
        .catch((error) => {
          throw new Error(error.message);
        });
    } else {
      // ios
      startApp();
    }
  }
}

export default App;
```

rootReducer.js:
```
import { LOGOUT_USER } from "../actions/actionTypes";
import userReducer from "./userReducer";
// other reducers ....
import { Navigation, NativeEventsReceiver } from "react-native-navigation";
import tabNavigationConfig from "../screens/tabNavigationConfig";
import onboardNavigationConfig from "../screens/onboardNavigationConfig";
import updateNavigationConfig, {
  isAppOutdated
} from "../screens/updateNavigationConfig";
import { isAppManuallyLaunched } from "../screens/registerScreens";
import { Platform, Alert } from "react-native";
import { isPreonboardingComplete } from "../storage/onboardingWizardStorageService";

import { persistCombineReducers } from "redux-persist";
import storage from "redux-persist/es/storage";

const config = {
  key: "root",
  debug: true,
  storage
};

const appReducer = persistCombineReducers(config, {
  // Reducers go here.
  // Ex:
  //   user: userReducer
});

let didAppStart = false;

const startApp = (userId) => {
    Navigation.startTabBasedApp(
      JSON.parse(JSON.stringify(tabNavigationConfig))
    );
};

const rootReducer = (state = {}, action) => {
  // ...
};

export const onRehydrated = (state) => {
  if (state && state.user && state.user.userId && !didAppStart) {
    didAppStart = true;

    if (isAppManuallyLaunched() || Platform.OS === "ios") {
      startApp(state.user.userId); // App was launched directly -> show UI
    } // otherwise, code is headless and got triggered from push notification handler
    new NativeEventsReceiver().appLaunched(() => startApp(state.user.userId)); // save launcher for push notification click
  } else if (!didAppStart) {
    didAppStart = true;

    startApp(null);
  }
};

export default rootReducer;
```

registerScreens.js:
```
import { Navigation } from "react-native-navigation";

/**
 * Tab Screens would be imported here...
 */

import { createTransform } from "redux-persist";

// Need to keep track whether app manually launched or via push notifications
// So rehydrate from processing push notification doesn't trigger loading (authorized) screens
export let appManuallyLaunched = false;

export const setAppLaunched = (launched) => {
  appManuallyLaunched = launched;
};

export const isAppManuallyLaunched = () => {
  return appManuallyLaunched;
};

// other screen registration stuff....
}
```

**Comment by alnsantosh** [comment]
@tmaly1980 Thanks for the code snippet. This is a great help. 
At this point I am able to differentiate the manual launch with automatic launch using appManuallyLaunched variable. However, I am using mobx-react package instead of redux package.Hence, I cannot use onBeforeLift() callback function. Is there any equivalent to the onBeforeLift() callback function in mobx?

**Comment by PokoGroot** [comment]
Hi i'm currently having this issue, when app is in background and show localnotification it launch the app when i clicked on notification.
Is there any way to prevent app from launch ?
I'am using react-navigation
