### ISSUE TITLE
Clear notification when open the app

### ISSUE THREAD

**Issue by ammichael** [zo0r/react-native-push-notification#65]
Hello!

Is there a way to clear notifications in notification center, when some action is triggered? Like just opening the app?

**Comment by gamezinfantes** [comment]
i have the same question

**Comment by gamezinfantes** [comment]
`          var PushNotification = require('react-native-push-notification');
          PushNotification.cancelAllLocalNotifications();`

**Comment by ammichael** [comment]
Yeah, I think that is a way: cancelling all and rescheduling again. But I don't think it's a really good solution. In my case, I've more than 500 notifications scheduled. Would be a problem if I reschedule all them everytime the app is opened

**Comment by npomfret** [comment]
@ammichael do you still have this issue?  if so, have you tried the latest release?  if not, can we close it?

**Comment by ammichael** [comment]
@npomfret I don't think it is an issue.. It's a nice feature that is not available yet, and I still think it would be useful

**Comment by npomfret** [comment]
I think you can call `PushNotification.cancelLocalNotifications({id: '123'});`
