### ISSUE TITLE
App crashing when opening remote notification (iOS)

### ISSUE THREAD

**Issue by nickabb** [zo0r/react-native-push-notification#650]
I've been searching to see if there was another issue reported on this but all I seem to be able to find are Android issues.

My app currently crashes ~75% of the time when opening a notification from the notification center, and always crashes if the app is open when the notification is received. 

I always receive the notification from the server correctly if the app is closed or in the background, the issue is opening it or if the app is open which leads me to believe the issue is the onNotification listener/function (also leading to this suspicion is an api call in onNotification not being made, along with other functions in there such as setApplicationIconBadgeNumber not being called).  I can't seem to get any sort of device logs for the crash.  I attempted to make an api call from onNotification sending the notification object to the server to debug, but can't get it to send.  

Has anyone else run into this? Here's whats being sent from the server.

```
 {  encoding: 'utf8',
    payload: { messageFrom: 'Nick' },
    compiled: false,
    aps: { badge: 1, sound: 'ping.aiff', alert: 'Testing push' },
    expiry: 1518062686, 
    priority: 10,
    userInteraction: true,
    topic: BUNDLE_IDENTIFIER }
```

I am using react-native .47.2 and react-navigation (i noticed there was an issue with wix, but that doesn't seem to apply here.)

EDIT: Ok so the issue seems to be having any sort of code in onNotification.  For example:

```
onNotification: (notification) => {
      notification.setApplicationIconBadgeNumber(0);
    },
```
Crashes application
```
onNotification: (notification) => {
     notification.finish(PushNotificationIOS.FetchResult.NoData);
    },
```
Crashes application
```
onNotification: (notification) => {
     // Do nothing
    },
```
Does not crash application, but obviously this isn't desirable - I want to do something on receiving the notification.  Is there something wrong with the notification object I am sending maybe?  Even a console.log of the notification object crashes the application

EDIT again:

Oof.  Seems like notification was undefined causing a javascript reference error.  Leaving this here in case anyone in the future comes across this.  You need to brace your code like so: 
```
onNotification: (notification) => {
         if (notification) {
             // Do something
         }
    },
```

**Comment by JuanDeLeon** [comment]
I'm having the same issue. When I have the screen locked AND my app was running (so it's running on background), I receive the notification and choose Open, the app opens and immediately crashes. 

If my app was NOT running on background, then it starts up and loads without problem. I will try your code for the first scenario, thanks!

**Comment by durghe** [comment]
i can build the app but as soon as i start debugging on real device or emulator my app crashes. when i deinstall this package, my app works again..
i can't fix it...

**Comment by jhon312020** [comment]
I too have the similar issue as reported app crashing. 
In my case for android
1) I only receive the push notification, if the app is running in the background.
2) When I click on the app notification from the notification center the app crashes.

For IOS
1) It works fine in the ios app.

Code sample

>  onNotification: function (notification) {
        console.log('NOTIFICATION on dashboard:', notification);
        if (Platform.OS === 'ios') {
          notification.finish(PushNotificationIOS.FetchResult.NoData);
        } else {
          console.log('Called me');
        }
      },
> 
When I check the console on receiving the notification.  It prints the following

1. Notification Object
2. Called me.

After opening if I check it only prints notification object and the app crashes.
1. Notification object.

Hope this gives the clear idea of the problem and let me know if anyother information is needed from my end.  Advance thanks.

**Comment by nickabb** [comment]
Hey @jhon312020, couple of things.  By iOS app I assume you mean the Simulator? You wouldn't be able to reproduce the issue there, Push Notifications are never called in the Simulator. 

Listening to your issue, it sounds similar to what I was going through with an undefined variable error. Doesnt seem like you have anything undefined in your code though, so you're probably going to have to debug a bit deeper.

Something that really helped me was logging my crashes and the console.logs around them.  Fabric.io is a great tool for this.  This article was a great help for ios, although I'm sure you can find something for Android too out there: https://medium.com/delivery-com-engineering/add-crashlytics-to-your-react-native-ios-app-69a983a9062a
