### ISSUE TITLE
Error when compiling android

### ISSUE THREAD

**Issue by wmonecke** [zo0r/react-native-push-notification#651]
I get a successful build when I run `react-native run-android` but the app crashes on start after installing `react-native-push-notification`.

I get the following error:
```
AndroidRuntime: FATAL EXCEPTION: Thread-3
02-14 12:44:40.530  6966  7011 E AndroidRuntime: Process: com.lisdo, PID: 6966
02-14 12:44:40.530  6966  7011 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzr, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
```

This error is very similiar to [this one](https://github.com/react-community/react-native-maps/issues/1408) but I have no clue on what to exclude in my dependencies in `android/app/build.gradle`.

Any help is welcome!

**Comment by david0u0** [comment]
I have encountered the same issue. Did you solve it?
