### ISSUE TITLE
How to know when user tapped in a notification?

### ISSUE THREAD

**Issue by witalobenicio** [zo0r/react-native-push-notification#658]
In android I can't see a way to get that information to manage what screen open.
It's possible? How?

**Comment by vishrut** [comment]
You can use the `onNotification `handler for this. The handler is invoked whenever a user taps on the notification with the `userInteraction` property set to true.

**Comment by lklepner** [comment]
I've found that iOS always returns `userInteraction` equal to true even when the notification is received in the background and then again if the user enters the app w/o interacting with the notification.

**Comment by marvinPlasmatic** [comment]
Was there any verification on this issue?
I also get that the userInteraction is always true, with or without the user tapping the notification.

**Comment by EdgarHSM** [comment]
Having the same issue @marvinPlasmatic and @lklepner mentioned.
