### ISSUE TITLE
Not receiving token when app is published

### ISSUE THREAD

**Issue by vbohdanets** [zo0r/react-native-push-notification#659]
Everytihing works fine on debug/release mode, but when app is published(ios and android) token is null

**Comment by fidoe** [comment]
Im haing the same issue, trying to use Firebase senderID.  No luck so far.  Any solution @HenIchaer ?

**Comment by bhd-vasyl** [comment]
@fidoe 
I had another package name of the app, so i've created new senderID and api key on the FCM (not GCM) and added this senderID to the **Services & APIs**  and it seem's to work for me
