### ISSUE TITLE
implement all the steps, but still not firing onError or onRegister when app is up

### ISSUE THREAD

**Issue by roysG** [zo0r/react-native-push-notification#660]
I am using the latest version and implemented the code inside function: "componentDidMount"

react-native-cli: 1.0.0
react-native: 0.51.0

**Comment by sarahmarciano** [comment]
same issue here
@roysG did you solve it?

**Comment by sarahmarciano** [comment]
so finally my issue was that I didn't made the required changes in thee AndroidManifest file
