### ISSUE TITLE
Checking if app notification is enabled on Android

### ISSUE THREAD

**Issue by James2516** [zo0r/react-native-push-notification#662]
User is able to turn off app notification on Android. Is there a way to check if the user did so?

**Comment by idlework** [comment]
@James2516 you could use [react-native-permission-settings](https://github.com/alienslab02/react-native-permission-settings) , it's android only.

**Comment by James2516** [comment]
@idlework unfortunately it no longer works with RN v55 / Android 8.0. I just opened an issue there. 
Any other suggestions?

**Comment by James2516** [comment]
Notification permission checking is added to Android in 2016: https://developer.android.com/reference/android/support/v4/app/NotificationManagerCompat.html#areNotificationsEnabled()

**Comment by idlework** [comment]
@James2516 maybe use [permissionsandroid api](https://facebook.github.io/react-native/docs/permissionsandroid.html) or look in the [react-native-permission-settings](https://github.com/alienslab02/react-native-permission-settings) project to see how they solved it.

**Comment by James2516** [comment]
@idlework PermissionsAndroid does not support notification permission. 
Why did you link the library that I just said no longer works again?

I just found [react-native-notification-android-permission-library](https://github.com/shivam-aditya/NotificationAndroidPermissionLibrary/blob/d0ba8826103289bd94038ce81dee7aff03065dc7/android/src/main/java/com/reactlibrary/RNNotificationAndroidPermissionLibraryModule.java#L35) which does work because it uses the `NotificationManagerCompat` API from Android. 

Would be convenient if this library is updated to support it.

**Comment by ManAnRuck** [comment]
is there a way to include this in this library?

**Comment by Dallas62** [comment]
This [`PushNotification.checkPermissions(callback: Function)`](https://github.com/zo0r/react-native-push-notification#checking-notification-permissions) is not working ?
