### ISSUE TITLE
Notifications with delay?

### ISSUE THREAD

**Issue by MatheusGithubb** [zo0r/react-native-push-notification#663]
Notifications take much more than 1 minute to appear, is this normal? How long does the average delay take? Thanks.

**Comment by joaom182** [comment]
You are scheduling notifications or firing immidiatly?

**Comment by MatheusGit** [comment]
@joaom182  What is the best option?

**Comment by joaom182** [comment]
Depends your requirements. But in any option there should be no delay.

**Comment by stuart-ithands** [comment]
i am facing the same issue, any solution
