### ISSUE TITLE
can't success to build for android

### ISSUE THREAD

**Issue by eran322** [zo0r/react-native-push-notification#664]
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-push-notification'.
      > Failed to notify project evaluation listener.
         > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

what i am doing wrong?

**Comment by diaraujo13** [comment]
solved?

**Comment by beausmith** [comment]
I was having this issue and here is what fixed it for me: https://stackoverflow.com/a/50930048/101290

cc @eran322 @diaraujo13
