### ISSUE TITLE
Group notifications?

### ISSUE THREAD

**Issue by filipemerker** [zo0r/react-native-push-notification#665]
Is there a solution for this already?

**Comment by ejoncas** [comment]
You can get a simple grouping done with the payload here: https://github.com/zo0r/react-native-push-notification/issues/935

But support for configuring the "group summary" and allowing multiple different groups of messages seems to be unsupported :

https://github.com/zo0r/react-native-push-notification/issues/935

**Comment by filipemerker** [comment]
Had to remove this library completely. We're using One Signal now for push notifications and [this library](https://github.com/OneSignal/react-native-onesignal) is great and allows you to group notifications and all.

Still, for those that have the same need, I wouldn't close this issue.

**Comment by Dallas62** [comment]
Hi @filipemerker 
Group notifications are already implemented.
Regards,

**Comment by filipemerker** [comment]
Hey, @Dallas62,

That's for a localNotification tho.
How to group notifications that come from a remote server?

**Comment by Dallas62** [comment]
You can send a data-only notification, and pass the data to `localNotification` method:
```js
PushNotification.configure({
  // (required) Called when a remote is received or opened, or local notification is opened
  onNotification: function (notification) {
    console.log("NOTIFICATION:", notification);

    if(!notification.userInteraction) {
       PushNotification.localNotification(notification.data);
    }
    else {
    // process the notification
    }

    // (required) Called when a remote is received or opened, or local notification is opened
    notification.finish(PushNotificationIOS.FetchResult.NoData);
  },
});
```

You can add more condition than just passing the `notification.data` to `localNotification`, but it's a basic exemple.

**Comment by filipemerker** [comment]
Fair enough, thanks for the snippet, I hope it's useful for somebody in the future!
