### ISSUE TITLE
app crashing when i install this library

### ISSUE THREAD

**Issue by durghe** [zo0r/react-native-push-notification#667]
Hello everyone,

i just installed this library step by step for a second time, and the app is crashing on emulator and real device. I can't open the app. I have no problems with building it. When i deinstall this library my app works..
Iam on Android by the way...

What am i doing wrong? I need this library

Thanks,

**Comment by durghe** [comment]
just gcm version 10.0.1 works for me...

**Comment by andidev** [comment]
@durghe 
I'm having the same issue. How did you solve it? What is gcm and how do I update it?
