### ISSUE TITLE
Azure Notifications Hub

### ISSUE THREAD

**Issue by sarahmarciano** [zo0r/react-native-push-notification#671]
Hi everyone,
I am trying to integrate this package with Azure notifications hub, but, for the moment with no success :(
did anyone do that? can someone guide me with that?
any kind of help will be highly appreciated
Thanx in advance!

**Comment by Jakst** [comment]
Have you looked at this tutorial?
http://reactnative.vn/integrate-remote-push-notification-gcm-azure-hubs-and-react-native-in-android/

**Comment by MyGuySi** [comment]
I'd have to check without our backend developer but pretty sure there's no "integration" between this library and Azure Notification Hub. Azure should support the Cloud Messaging platform so from what I remember (it was a while ago now...) I only had to give her the certificate I generated.

Let me know if you need more information though and I can check with her 👍
