### ISSUE TITLE
Possible compatibility issue with react-native-navigation

### ISSUE THREAD

**Issue by 3210jr** [zo0r/react-native-push-notification#672]
Hey all, this is a great package and thanks @zo0r & contributors for this.

By following the same exact instructions in the Readme, local notifications will only RARELY (1 out of 1000) trigger 'onNotification' event when clicked on, whether or not the app is in foreground.

I have noticed a pattern in that, this only happens in projects where I use `react-native-navigation` package, otherwise the notifications don't usually cause such persistent problems.

I have tested with: 
react-native 49.0 and 50.0 and 51.0
react: 16.0.0
react-native-navigation: 1.1.369 
react-native-push-notification: 3.0.2

I would change the navigation package but we are working on a huge app and re-writing it is no easy task.

REPRODUCE:
There are no steps to reproduce, just followed the instructions (several times) and it doesn't work. 

Any help appreciated!

**Comment by wynch** [comment]
Wix has its own notifications library, and they mention this integration issue: `react-native-navigation` expect a different structure of your project (only 1 activity / ViewController for normal react-native apps, several in case of `react-native-navigation` ). [See this page](https://github.com/wix/react-native-notifications/wiki/Android:-working-with-RNN) for discussion

**Comment by 3210jr** [comment]
Thanks for that. Seems like that notifications library needs some some extra work styling the notifications. Thats fine.

I have really enjoyed working with library though, sad that I have to consider dropping it :(
We will try and see if we can find a way to make them work together. 

Closing the issue for now.

**Comment by ReggaePanda** [comment]
@3210jr do you find a way?

**Comment by DavitVosk** [comment]
Any success here?
