### ISSUE TITLE
how to get all local notification scheduled as a list? help me to solve this

### ISSUE THREAD

**Issue by vinothjdx** [zo0r/react-native-push-notification#673]

**Comment by Apak00** [comment]
I need something like this too, in order to achieve setting schedule once on login if already exist dont schedule new local notification

**Comment by ammichael** [comment]
I also have this problem. Apparently, there is no way to do this using the lib API. It would be really great if implemented.

**Comment by lukebars** [comment]
@Dallas62 I'm thinking it would be possible to save scheduled notification list in Java code. I could try to submit a PR for this, I don't know if you would be up to review it

**Comment by Dallas62** [comment]
Hi @lukebars 
Notifications are saved in JSON in the module, then when it’s time, the JSON is used to trigger the notification.
The problem of this feature is the compatibility with iOS.
It would be great to avoid too much difference with the API 😕

**Comment by lukebars** [comment]
@Dallas62 Oh so that make's it a lot easier then. What about a wrapper function that would get notifications from iOS native side (`getScheduledLocalNotifications()`) and for android it would get pending notifs from JSON? Would be happy to submit this kind of solution

**Comment by lukebars** [comment]
@Dallas62 I've created a pull request #1466
