### ISSUE TITLE
Local notification scheduler limits

### ISSUE THREAD

**Issue by joaom182** [zo0r/react-native-push-notification#685]
Hi,

I have 100+ notifications to schedule, and is not working, no notification is shown. If i schedule some notifications (i.e 5 notifications) works perfectly.

Have any limitation to schedule local notifications?

EDIT:

I found the answer.

https://stackoverflow.com/questions/7721362/schedule-number-of-local-notifications

iOS has limitation up to 64 local notifications schedule.

**Comment by kaiyes** [comment]
@joaom182  what's the android limit ?  Also, how did you handle the issue ? 

The SO link tells us to to check if there are 64 notifications in queue and when the number is 63, just push the latest one. Is that it ?
