### ISSUE TITLE
VOIP Notification Android?

### ISSUE THREAD

**Issue by basitsattar** [zo0r/react-native-push-notification#688]
Just like there is pushkit for ios which automatically opens app, how can we achieve this functionality for android? Currently I have to click the notification which then opens the app and shows incoming call screen. Probably this commit that was reverted? https://github.com/zo0r/react-native-push-notification/commit/e4dbdc6f83fc29eb1501458ddf49664ed3af9538 

Can anyone tell the steps required to achieve this functionality? I want to auto open app on notification and show call screen. Is this possible in react-native-push-notification?

**Comment by krajay015** [comment]
@zo0r @asantos2 @naimmustafa can you guys help us to resolve this issue?

**Comment by tiagocorreiaitcenter** [comment]
@basitsattar where you able to solve it somehow?
