### ISSUE TITLE
how to use this.props inside onRegister

### ISSUE THREAD

**Issue by laksh1010** [zo0r/react-native-push-notification#693]
in my case i get undefined in this.props and its a total different **this** shown when i console log. 

anyone know a work around ? because i need to save token data to my redux state via mapDispathToProps.

Thanks a lot

**Comment by jhon312020** [comment]
As the current this will point to the pushNotification object.  So you can declare like the below

> let thisObj = this;

Then you can use that variable to access the component parent object.
