### ISSUE TITLE
How can I set the local scheduled notification for iOS if I want notification to occur after every 2nd Day or nth Day?

### ISSUE THREAD

**Issue by tanviag** [zo0r/react-native-push-notification#699]

**Comment by infinitbility** [comment]
You can use `repeatTime which should the number of milliseconds between each interval.`

https://github.com/zo0r/react-native-push-notification#repeating-notifications

**Comment by anhquan291** [comment]
> You can use `repeatTime which should the number of milliseconds between each interval.`
> 
> https://github.com/zo0r/react-native-push-notification#repeating-notifications

But it is not working with IOS. any solution? thanks
