### ISSUE TITLE
Could not find com.google.android.gms:play-services-gcm:8.4.0

### ISSUE THREAD

**Issue by nicholasstephan** [zo0r/react-native-push-notification#70]
I'm getting the following trying to run on Android:

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-push-notification'.
   > Could not resolve all dependencies for configuration ':react-native-push-notification:_debugCompile'.
      > Could not find com.google.android.gms:play-services-gcm:8.4.0.
        Searched in the following locations:
            ...
        Required by:
            My101:react-native-push-notification:unspecified`

What am I missing?

**Comment by zo0r** [comment]
Related: https://github.com/zo0r/react-native-push-notification/issues/7#issuecomment-170382549

**Comment by nicholasstephan** [comment]
I works! I added Google Play Services, but not Repository. Should have looked harder for that answer, I guess. 

Thanks for the quick response.
