### ISSUE TITLE
How to handle notification when app is closed(not background mode)

### ISSUE THREAD

**Issue by leventyildirim61** [zo0r/react-native-push-notification#700]
Hello.

How to handle notification when app is closed(not background mode)

**Comment by gusilveiramp** [comment]
+1

**Comment by devlargs** [comment]
Create an app exit listener and fire:

PushNotifications.cancelAllLocalNotifications()

**Comment by gusilveiramp** [comment]
@devlargs Thanks for tip, but how? How to create an exit listener? 
And why call PushNotifications.cancelAllLocalNotifications() if this function remove all listeners? Could you explain better or give an example? Thank you!

**Comment by devlargs** [comment]
Hi. I surely misunderstood this one. I thought you're saying how to remove a notification after you close the app.

If you are going to push a notification when the app is closed, you need another plugin for that. As for what I am using: 

https://github.com/jamesisaac/react-native-background-task. (but the task fires for a minimum time of 7m30s). 

But if you are going to fire a notification from one phone to another phone (like chatting... etc), Im not sure that feature is supported yet.

See also: https://github.com/zo0r/react-native-push-notification/issues/219
