### ISSUE TITLE
onNotification is fired when application is in the background while pushing remote notifications

### ISSUE THREAD

**Issue by ronilitman** [zo0r/react-native-push-notification#701]
Hi,
I am experiencing strange behaviour while pushing notifications.
It seems that when my application in the background, onNotification callback is invoked and it is even called with `userInteraction: true` which does not make sense at all. It does not always invoke, and I wonder what is the right behaviour for this.

I think that onNotification should not be invoked right away, but it should invoke only after the user clicked on the push notification with `userInteraction: true`.

I have not changed anything in my configuration and just used the documentation example:

    // (optional) Called when Token is generated (iOS and Android)
    onRegister: function(token) {
        console.log( 'TOKEN:', token );
    },

    // (required) Called when a remote or local notification is opened or received
    onNotification: function(notification) {
        console.log( 'NOTIFICATION:', notification );

        // process the notification

        // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
        notification.finish(PushNotificationIOS.FetchResult.NoData);
    },

    // ANDROID ONLY: GCM Sender ID (optional - not required for local notifications, but is need to receive remote push notifications)
    senderID: "YOUR GCM SENDER ID",

    // IOS ONLY (optional): default: all - Permissions to register.
    permissions: {
        alert: true,
        badge: true,
        sound: true
    },

    // Should the initial notification be popped automatically
    // default: true
    popInitialNotification: true,

    /**
      * (optional) default: true
      * - Specified if permissions (ios) and token (android and ios) will requested or not,
      * - if not, you must call PushNotificationsHandler.requestPermissions() later
      */
    requestPermissions: true,

Did anyone encounter this? Thanks in advance!

**Comment by nickabb** [comment]
@ronilitman what do you mean the onNotification callback is invoked when it is in the background?  Your app is opening from the background and the logic is executed when the push notification is received?

**Comment by stevenconner** [comment]
I'm experiencing the same issue. When receiving a notification in background when app is 'dead' (force quit, or hasn't been ran for a while), the app starts automatically from the background without user interaction on the notification. Would love to get this resolved! :)

**Comment by vvavdiya** [comment]
Please have look at [here](https://github.com/zo0r/react-native-push-notification/issues/547#issuecomment-351713972)

After modifing java file onNotification get called when app is in background.

**Comment by iamrutvik** [comment]
React Native Push Notifications clearly states that we need to call configure outside of the React Native Lifecycle. This is very important. 

https://product.farewell.io/visible-react-native-push-notifications-that-work-on-both-ios-and-android-5e90badb4a0f

https://prnt.sc/k61hz7

**Comment by EdgarHSM** [comment]
I also followed the example in the documentation and I'm having a similar issue on iOS, as soon as the device receives a push notification while the app is in the background (not closed, just "minimized"), onNotification is triggered and the "userInteraction" flag is true, it doesn't wait for the user to click on the notification.
