### ISSUE TITLE
Is there a way to customize remote notifications?

### ISSUE THREAD

**Issue by filipemerker** [zo0r/react-native-push-notification#702]
Local notifications are [very customizable](https://github.com/zo0r/react-native-push-notification#local-notifications).
The problem is that I have a chat implemented on my app and I need to be able to configure my remote notifications as well. This would be one way to group notifications, for example, for I would be able to create a notification that says "20 messages in group X" instead of stacking 20 notifications.

**Comment by Rah1x** [comment]
in my case, ive send the payload inside `data` instead of `notification`. I passed empty `notification` instead.
```
"collapse_key": "type_b",
  "notification": {}, 	
  "data": {
  	"subText":"sub title R",
  	"title":"Notification Heading R",
  	"message":"Short Message R",
  	"bigText":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam",
  	"color":"#3F81C5"
  }
```

**Comment by filipemerker** [comment]
@Rah1x But how do you do that? At least on amazon SNS you need to send a pre-formated JSON which requires the `message` attribute at the root. This way, when a remote notification arives, it fires a notification and goes through `onNotification`, as expected. But I fail to see where could I intercept the push notification before it is shown in order to customize it and send as a local notification instead...

**Comment by nickabb** [comment]
Hey @filipemerker, you need to pass the data through from the server (or Amazon SNS) and then filter it out based on the background property of the notification option if you want to send a local notification.  

The "customization" aspect should be done before the push notification even hits the device.  The onNotification function should just receive the data and display it.

The way I do it is this: I add a payload member to my notification object on the server with a "message", and then in onNotification I do something like this:

`
if (notification.foreground == false) {
    // Logic for when its in the background
}

if (notification.data) {
    if (notification.data[0].message) {
        // logic for your local notification solution here
        console.log(`Log this local notification message: ${notification.data[0].message}`);
    }
}
`

I also have some other logic for handling notifications that don't have a message, but that would be based on your use case.

**Comment by Rah1x** [comment]
@filipemerker Well, I use CFM and its working

**Comment by adirzoari** [comment]
@Rah1x do you have payload for show notification in background?

**Comment by Rah1x** [comment]
@adirzoari No I dont have a 2nd payload. The payload I mentioned is up in the message. Though ive made a lot of changes to the whole `react-native-push-notification` module manually. Here is my guide:
https://github.com/zo0r/react-native-push-notification/issues/697
