### ISSUE TITLE
PushNotificationIOs is not defined

### ISSUE THREAD

**Issue by GastonEDiaz** [zo0r/react-native-push-notification#704]
![captura de pantalla 2018-04-05 a la s 12 00 39](https://user-images.githubusercontent.com/11540408/38374174-6620f736-38c9-11e8-96b5-4e154f9096a5.png)

Emulator: iPhone 6
Xcode Version: 9.2
react: 16.0.0
react-native: 0.50.3 
react-native-push-notification: ^3.0.2

![captura de pantalla 2018-04-05 a la s 12 06 14](https://user-images.githubusercontent.com/11540408/38374680-a83bcf46-38ca-11e8-8d6e-876f468abfc1.png)

the error line is in notification.finish(PushNotificationIOS.FetchResult.NoData);

i import configuration in AppDelegate.m

**Comment by GastonEDiaz** [comment]
Sorry, the error is don't implement PushNotificationIOS in de import from react-native 

`import { View, Text, StyleSheet, Image, Button, PushNotificationIOS } from 'react-native';`

fixed

**Comment by sashiksu** [comment]
I have got the same error message when I'm running RN android project. Don't know why getting this even without running the iOS project of RN app.

**Comment by sashiksu** [comment]
> I have got the same error message when I'm running RN android project. Don't know why getting this even without running the iOS project of RN app.

If you are using iOS only method on android add logic to not execute it when Platform.OS == 'android' 
in my case, I was using `notification.finish(PushNotificationIOS.FetchResult.NoData);`
