### ISSUE TITLE
Cannot read property 'scheduleLocalNotification' of undefined

### ISSUE THREAD

**Issue by DeViL-mAy-CrY** [zo0r/react-native-push-notification#706]
I'm on 3.0.2

I want the notification to come up when app is run in background but it has an error like in the title

![screenshot_1523343747](https://user-images.githubusercontent.com/2336175/38541052-18b3a0cc-3cc8-11e8-8f04-6c8e235458a3.png)

this is the code I tried to test it

     import React, { Component } from 'react';
     import { View } from 'react-native';
     import PushNotification from 'react-native-push-notification';
     import PushController from './PushController.js'; //The push controller created earlier

     class App extends Component {

     constructor(props) {
        super(props);
      this.state = { 
      };

      this.handleAppStateChange = this.handleAppStateChange.bind(this);
      this.sendNotification = this.sendNotification.bind(this);
    }

    componentDidMount() {
      AppState.addEventListener('change', this.handleAppStateChange);
    }

    componentWillUnmount() {
      AppState.removeEventListener('change', this.handleAppStateChange);
    };

    handleAppStateChange(appState) {
      if (appState === 'background') {
          // Schedule a notification
          PushNotification.localNotificationSchedule({
            message: 'Scheduled delay notification message', // (required)
            date: new Date(Date.now() + (3 * 1000)) // in 3 secs
          });
      }
    };

    sendNotification() {
      PushNotification.localNotification({
        message: 'You pushed the notification button!'
      });
    };
  
    render() {
          return (
            <View>
                <PushController />
            </View>
          );
      }
    }
    export default App;

**Comment by mukeshsoni** [comment]
Where did you configure PushNotification? https://github.com/zo0r/react-native-push-notification#usage

**Comment by DeViL-mAy-CrY** [comment]
I configure it in another class here.   

    import React, { Component } from 'react';
    import PushNotification from 'react-native-push-notification';

    export default class PushController extends Component {

	  componentDidMount() {
		  PushNotification.configure({ 		
			  onNotification: function(notification) {
				  console.log('NOTIFICATION', notification);
			    },

			  popInitialNotification: true,
		  });
	  }

	  render() {
		  return null;
	  }
  }

**Comment by ospfranco** [comment]
isn't the name of the method `localNotificationSchedule` instead of `scheduleLocalNotification`?

**Comment by chrissnape** [comment]
What happened with this? I am getting the same issue.

**Comment by pie6k** [comment]
I've just wasted hour of debugging because I was using `scheduleLocalNotification` instead of `localNotificationSchedule`...

Why is this different method even there?
