### ISSUE TITLE
  PushNotification.cancelLocalNotifications not working 

### ISSUE THREAD

**Issue by uendar** [zo0r/react-native-push-notification#708]
I try to cancel my notification using   PushNotification.cancelLocalNotifications({id:id} but i get 
**undefined is not a function (evaluating 'PushNotification.cancelLocalNotifications({ id: id })')**

Any idea how to solve this?

**Comment by mukeshsoni** [comment]
@uendar It's better to ask this question on stackoverflow. Also, include the code where you get this error.
