### ISSUE TITLE
Random number in iOS badge

### ISSUE THREAD

**Issue by jdelafon** [zo0r/react-native-push-notification#712]
I am using `localNotificationSchedule` like this:

        const notif = PushNotification.localNotificationSchedule({
            message: message,
            date: date,
            number: ''+ someId,
            applicationIconBadgeNumber: 0,
        });

Every time a new single local notification is received in the background, the app's badge in iOS show a random 3 to 5 digits number. 

![2018-04-12_18-35-46](https://user-images.githubusercontent.com/12040845/38691173-58b66308-3e80-11e8-9677-98cb0b3a270c.png)

So after the first notification it might show "92'675", and on the next one "3'417". I removed the field `number` (which is so badly documented that I only added it because the message it cannot be canceled otherwise...) and now even without any scheduling, the app show always the same number on startup: "73'864".

**Where does this number come from ?** 

Can I remove the badge completely ? I tried the  `applicationIconBadgeNumber` option as above but it has no effect, and I only managed to remove the badge when the app starts.

**Comment by jdelafon** [comment]
Actually it happens even if I remove every mention of notifications in my code. The problem appeared as soon as I installed this lib, though. I will narrow down the reason.

**Comment by vishnumishra** [comment]
@jdelafon any luck on this. I'm also getting the random number in applicationIconBadgeNumber

**Comment by jdelafon** [comment]
@vishnumishra I remember that for me in the end it was not a mistake in the code, or maybe it was in a previous version and was persisted across updates, something weird. Afair I deleted the app completely from the simulator and reinstalled, then it worked.

Try reverting to the very first commit of your app to see if it remains, and delete/reinstall.

**Comment by vishnumishra** [comment]
Thanks @jdelafon 
i got it working. It was not issue with the library. We were setting the numbers in the local notification.
