### ISSUE TITLE
onNotification does not get triggered when the client receives notification from server.

### ISSUE THREAD

**Issue by halaharr** [zo0r/react-native-push-notification#714]
Hi,
    onNotification event does not get triggered in android when the app receives the initial notification. It does only when you tap on the notification. I wanted to capture the message sent by the server in onNotification event and display localNotification in onNotification event.

Thanks

**Comment by iamrutvik** [comment]
React Native Push Notifications clearly states that we need to call configure outside of the React Native Lifecycle. This is very important. 

https://product.farewell.io/visible-react-native-push-notifications-that-work-on-both-ios-and-android-5e90badb4a0f

https://prnt.sc/k61hz7

**Comment by steveleec** [comment]
Hi,
I did configure it outside of RN's life cycle but still 'onNotification' method is not getting fired. @iamrutvik could you point out which versions of the libraries are you using? That might help. THanks!
