### ISSUE TITLE
Onclick on Notification

### ISSUE THREAD

**Issue by ErickVoodoo** [zo0r/react-native-push-notification#715]
Hello guys, what is the action when user tries to click on arrived notification? How to handle only click on the notification when app is live/foreground?
Simple case:
Click on notification and redirect user to another page in app. (or open app and do the same thing)
Thanks!

**Comment by martinlavanant** [comment]
+1

**Comment by Faolain** [comment]
@zo0r or @Gp2mv3 any ideas if this is possible or something that is planned?

**Comment by MBakhtiyor** [comment]
+1

**Comment by chukitow** [comment]
Hey Guys! the notification has a boolean property called `userInteraction`, this means the user pressed on the notification.

```
onNotifictaion(notificication) {
  ....
  if(notification.userInteraction) {
    // Redirect wherever you want  
  }
}
```

**Comment by FonDorn** [comment]
@chukitow unfortunately `userInteraction` work if a user clicks on Notif in background.
For handler on click event on **iOS**, you can register next handler:
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
          didReceiveNotificationResponse:(UNNotificationResponse *)response
          withCompletionHandler:(void (^)(void))completionHandler {
   // The user launched the app.
   if ([response.actionIdentifier isEqualToString:UNNotificationDefaultActionIdentifier]) {
     NSMutableDictionary *newUserInfo = [[NSMutableDictionary alloc]initWithDictionary:response.notification.request.content.userInfo];
     [newUserInfo setObject:[NSNumber numberWithBool:TRUE] forKey:@"userInteraction"];
     
     [RNCPushNotificationIOS didReceiveRemoteNotification:newUserInfo];
   }
}
```
and check this native event in your js event `onNotification`. For example:
```
onNotification = (notification) => {
  ...
  if (notification.data.userInteraction) {
    navigate(ROUTE_NAME);
  }
 ...
};
```
