### ISSUE TITLE
Notice - Project may be abandoned - Alternatives List

### ISSUE THREAD

**Issue by Rob117** [zo0r/react-native-push-notification#716]
If you check the issues, you'll notice that react-native link only works for android, and will create a native module cannot be null error.

These issues have been open #603, #501, #428, #541 for a long time, once since **2016**.

Additionally, key parts of both the example code (`var PushNotification = require('react-native-push-notification');`), and the Readme are dangerously out of date and have been for months - see #617 

@zo0r I'm not knocking all the work that you put into this, you've done a fantastic job and are the go-to solution for pushing notifications right now. 

Which is precisely what worries me. Looking at how long some of the repeat issues have existed for and the lack of maintenance (as of writing, 48 open pull requests and 333 open issues), maybe consider either marking the project as abandoned and redirecting people to https://github.com/invertase/react-native-firebase (which certainly has its own issues) or adding maintainers if the project is proving to cumbersome to maintain.

**Comment by Rob117** [comment]
As an addendum, I want people to know about the other alternatives out there. Google the below to find their repositories.

Wix has push notification services, but if you're using react-native navigation it might be difficult to integrate as of this writing. Or if you're looking for deep android customization, the documentation seems confusing.

Expo has build in push notifications. If you are using expo (NOT ExpoKit, as you lose push notifications that way), they manage everything for you. Downsides - if Expo decides one day to stop maintaining their cloud / making push notifications free, and you already released your app, you're going to scramble to get something else in place.

OneSignal - the goto push service. Completely free for all use cases, this push service is apparently very, very easy to use - popular SDKs and integrations make sending notifications a breeze. This also seems to me the most popular. **MASSIVE CAVEAT** - the freedom comes at the cost of them selling pretty much all the data your app uses to any company interested in it. Put another way - if you would be uncomfortable with anyone (competitor, researcher) having data on your users, or if you have a level of privacy that forbids you from sending third parties user-specific information, you either pay money (no idea how much, but "Contact sales" always equals "$$$"), or use something else. [Data Collected](https://documentation.onesignal.com/docs/data-collected-by-the-onesignal-sdk)

Firebase FCM - use firebase to manage your push notifications. No real idea how this works, to be perfectly honest with you. I would absolutely love feedback on this by someone more knowledgable, but it _seems_ like you use cloud functions on their serverless backend to send messages? I do wonder how you would integrate this with your own service - i.e. send a notification to everyone who lives in New York City - without also storing that data on their service. Again, if anyone knows, please give feedback.

AWS SNS + native setup - good for broad targeting campaigns, cheap, great security. Absolute monster to get setup unless you are familiar with AWS services, but doesn't have any external dependencies.

AWS Pinpoint/AWS Amplify - New solution, still researching. [Pinpoint](https://aws.amazon.com/pinpoint/) [Amplify](https://aws.github.io/aws-amplify/media/push_notifications_setup)

**Comment by abarisic86** [comment]
There already was an initiative to ask them nicely to let go maintenance of this library to someone else with no results. https://github.com/zo0r/react-native-push-notification/issues/575

There was one great suggestion. To hand over the maintenance to [React Native Community](https://github.com/react-native-community). @zo0r what do you think about that?

**Comment by calcazar** [comment]
FYI: https://github.com/zo0r/react-native-push-notification/issues/727

@abarisic86  @Rob117

**Comment by Rob117** [comment]
@calcazar I 100% support this.

**Comment by daominhsangvn** [comment]
I still able to use this package for latest react-native version without any problems.

**Comment by Rob117** [comment]
@daominhsangvn that's the problem.

**Comment by alexsegura** [comment]
Same conclusion here, this repo seems abandoned + GCM is now deprecated by Google. 

I'm now migrating to [react-native-firebase](https://github.com/invertase/react-native-firebase) on Android + [PushNotificationIOS](https://facebook.github.io/react-native/docs/pushnotificationios.html) on iOS. 
It works, but of course the setup is more complicated. 

I'm still experimenting, but it should be quite easy to abstract away things under a common interface like this library does.

**Comment by Gp2mv3** [comment]
This repo isn't abandoned anymore. @zo0r had no more time to manage it but he gave me access to the repo some days ago.
I'm trying to merge everything that has to be merged.

Don't hesitate to help with the repo. :wink:

**Comment by pro-nasa** [comment]
Maybe you should give this repo to the `react-native-community`?

**Comment by ebaynaud** [comment]
After 2 years with https://github.com/zo0r/react-native-push-notification I moved to https://github.com/wix/react-native-notifications. 1 day to migrate and it's simply working great while I add a lot of issues with this repo. You guys should migrate as well, that effort will be profitable believe me.

**Comment by jessep** [comment]
> This repo isn't abandoned anymore. @zo0r had no more time to manage it but he gave me access to the repo some days ago.
> Don't hesitate to help with the repo. 😉

@Gp2mv3 Any chance you can share why this isn't transferred to react-native-community?

It still seems abandoned. Any way we can convince you to transfer it? This is a really important type of library for anyone using react-native, and this particular library has the most references when Googling around. You'd be doing a great service to the world of developers by enabling the community to contribute.

**Comment by Gp2mv3** [comment]
@jessep because I have no rights on this repo. I'm only able to merge to the master branch. It's @zo0r's responsibility to transfer the repo to the community I think?
Personally, I would be more than happy to help to transfer the repo.

**Comment by calcazar** [comment]
Guys.. Just a friendly tip. 

Go check out [https://github.com/wix/react-native-notifications](react-native-notifications) instead of this repo.. It's very similar with the same register and onNotification events. Should take no more than an hour tops to replace RNPN with RNN.

**Comment by ruslanchek** [comment]
> Wix
> Expo
> OneSignal
> Firebase FCM
> AWS SNS
> AWS Pinpoint/AWS Amplify
None of them, unfortunately, does support local notifications. It would be great to find something that supports this feature.

**Comment by abarisic86** [comment]
Wix is not supporting local notifications? Isn't just the documentation
outdated?

**Comment by ruslanchek** [comment]
> Wix is not supporting local notifications? Isn't just the documentation outdated?
> […](#)

I'm Sorry. WIX and Firebase are!

**Comment by itzsaga** [comment]
Wix doesn't support local notifications on Android yet.
