### ISSUE TITLE
unregister function not working !

### ISSUE THREAD

**Issue by ManveeYew** [zo0r/react-native-push-notification#723]
Try to unsubscribe push notification using "PushNotification.unregister();" but i still receiving remote push notifications. Any idea?

**Comment by kyaroru** [comment]
😉Refer to : https://github.com/surialabs/react-native-push-notification/commit/39d7adbb7bf1b620167ca7cc0491366b8ce716fc

For Android & iOS
- To enable, fire `requestPermissions()`, and to disabled fire `abandonPermission()`
