### ISSUE TITLE
GCM to FCM

### ISSUE THREAD

**Issue by rayjadore** [zo0r/react-native-push-notification#724]
please when csn we expect the version of this package that uses the new FCM ?

**Comment by nirpeled** [comment]
+1

**Comment by hugoh1995** [comment]
+1 please

**Comment by rayjadore** [comment]
i dont understand your reply

**Comment by nirpeled** [comment]
@rayjadore +1 means "me too" 😄

**Comment by rayjadore** [comment]
ok

**Comment by nbastoWM** [comment]
Hi. I've been using this package with FCM. I just create a new firebase project, use the sender ID and the Cloud Messaging server key from the Firebase admin panel and it works fine.

**Comment by yangnana11** [comment]
@nbastoWM As I know, we can't use fcm for ios when it goes background, is it correct?

**Comment by Gp2mv3** [comment]
I can confirme @nbastoWM I also use FCM that way with that plugin. So it's compatible.

**Comment by nbastoWM** [comment]
@yangnana11 I'm just using FCM for Android. In iOS I use the Apple APN.

**Comment by danielgreane** [comment]
GCM is being deprecated March 27th
https://developers.google.com/cloud-messaging/faq

"We will turn off most GCM services in April 2019, so you should plan to have most of your services migrated by then.

Note that client SDKs and GCM tokens will continue to work indefinitely. However, you won't be able to target the latest version of Google Play Services in your Android app unless you migrate to FCM."

Am I right in thinking we'd be locked in to older versions of play services whilst depending on GCM on react-native-push-notification ?
