### ISSUE TITLE
Cloned Library for the sake of support

### ISSUE THREAD

**Issue by calcazar** [zo0r/react-native-push-notification#727]
Hey Guys,

I hate to be "that" guy but I really want this library to move forward. I noticed this library is under the MIT license so I went ahead and cloned it here: https://github.com/calcazar/react-native-push-notification

If you'd like to be a contributor and help me get this (cloned) library updated, reach out to me and I'll make it so. 

Again.. I know this is kinda taboo considering that the original creator did an awesome job getting this to where it is now.. but like I said before.. it's time for the community to take over given the lack of viable alternatives.

**Comment by Rob117** [comment]
I don't think it's taboo at all. There is still clearly a great deal of interest in this library that the maintainers are not handling. Starred!

**Comment by karlmosenbacher** [comment]
I think this is a good idea and initiative! Hopefully will the community help this library get on its feet again.

**Comment by jedrichards** [comment]
Thanks for this.

What's the status of https://github.com/calcazar/react-native-push-notification-CE ?

Keen to test out your FCM updates ASAP.

**Comment by calcazar** [comment]
@jedrichards 

Go ahead and test now, FCM pushes work on my project using the CE clone.

There is a bug I'm currently trying to chase down where onNotification doesn't get triggered if the app is closed and you tap the notification to bring it up.

Regular behavior is that when you tap on the notification, the onNotification function gets called upon app launch

**Comment by dlombardi** [comment]
hey @calcazar -- thanks for picking up this project!  how's the "tap on notification when app is backgrounded not firing onNotification function issue" going?

**Comment by calcazar** [comment]
Made some headway and trying to figure the why.

There is a solution though. Make sure you configure outside of the react tree at the most root level of your app.

In the componentDidMount of the most top level react component do

PushNotification.popInitialNotification((notification) => {
       Console.log(notification);
})

Try that out :)

**Comment by dlombardi** [comment]
@calcazar thanks for the quick response.  No luck on iOS though :(. onNotification is not being fired when app is backgrounded and a push notification is clicked on.

**Comment by calcazar** [comment]
Can you open an issue over at my clone so I can follow it and add it to my todo tag?

**Comment by dlombardi** [comment]
@calcazar  https://github.com/calcazar/react-native-push-notification-CE/issues/2

**Comment by vinoa-team** [comment]
Maybe a stupid comment, but obviously you need to make sure that `popInitialNotification` is set to true as if it's set to false, the library won't handle notifications that are received when the app is not running at all

**Comment by Dallas62** [comment]
Hi,
If some changes are missing on the Library, feel free to open a PR based on the fork, I will take a look at it.
I'm a new maintainer of the library and if anyone want to join as maintainer; Feel free to ask for it!
Forks are great but the majority of developers are on the main repository and don't have visibilities on them.
Regards,
