### ISSUE TITLE
Can we lower the dependency to play-services-gcm?

### ISSUE THREAD

**Issue by pedro** [zo0r/react-native-push-notification#73]
Anyone knows if the play-services-gcm dependency has to be at 8.4.0? I see [it was bumped here](https://github.com/zo0r/react-native-push-notification/commit/77115ee3c35ec86ae512e90a56ae0df80bb0ce6e), but not sure about the context.

I just ask because we've seen devices that have gcm at 7.x, and updating is surprisingly painful to the user (basically on this one device I simply don't see "Google Play Services" in the list of apps that needs to be updated, and can't seem to find it searching the Play store either).

The good news is that I was able to get the basic flow of asking for permissions and getting a token to work with this package with dependency set to 7.8.0, so I'm wondering if we can't just lower it here.

**Comment by zo0r** [comment]
Sure! I notice that happens to some of my users too.

https://github.com/zo0r/react-native-push-notification/commit/b5fee4111b8566b350fc1a9c92be304cf3109a1c
