### ISSUE TITLE
How localNotification when application is closed in iOS

### ISSUE THREAD

**Issue by arieldll** [zo0r/react-native-push-notification#731]
Hi all,

I am having a problem with React native push notifications.
I am implementing this code for android and ios. 
I need to show notifications when the application is in background and when the application is closed. 
Android is working fine, but the iOS is not working when application is closed.
I am calling the PushNotification.configure({...}) and after, I am calling PushNotification.localNotification({}).
Need I change any code part when the application is closed?

Best regards,
Ariel

**Comment by filiperc** [comment]
Hi,
Maybe you will have to schedule the notification:

```
PushNotification.localNotificationSchedule({
      message: "My notification message.", // (required)
      date: new Date(Date.now() + 60 * 1000) // in 60 secs
    });
```

Regards, 
Filipe

**Comment by arieldll** [comment]
Tank you @filiperc but schedule notifications is not working too. 
I am trying with 
PushNotification.localNotificationSchedule({
      message: "My notification message.", // (required)
      date: new Date(Date.now() + 5000) // in 60 secs
    });

Any ideas?

Regards,
Ariel

**Comment by mikpalm** [comment]
Are you sure that you have closed the app on ios before the 5 sec has passed. try running this function and close/hide the app immediately or append some more secs before closing. wait and it should appear. works for me in ios simulator.

**Comment by delia-m** [comment]
+1 
ios 11.3
notification appears after 5 secs WHEN app foreground
never comes up(and no console) before app foregrounded

**Comment by LuisBonsembiante** [comment]
The same issue for me...any news about that?..thanks
