### ISSUE TITLE
Notification doesn't show when app is open under lock screen?

### ISSUE THREAD

**Issue by pedro** [zo0r/react-native-push-notification#74]
Hey folks,

I can push messages via GCM to my Android app most of the time, but in some devices the push doesn't seem to work if the app is just "behind" the lock screen (eg: you have the app open, then just lock the device). In this case the message is simply not displayed.

I'm assuming this means the app still got the notification, so the OS decided to not show the message banner... If that's the case, do I have to manually publish a local notification to get it to display in the lock screen? Is that a common practice in Android?

Thanks,

**Comment by zo0r** [comment]
Yes, its a normal behavior in Android and iOS. As you said, to show a notification in the notification center while the app is in foreground you have manually to publish a local notification.
