### ISSUE TITLE
onNotification handler not being fired

### ISSUE THREAD

**Issue by ndc466** [zo0r/react-native-push-notification#740]
I have remote push notifications setup correctly using a 3rd party service + APNS and my iOS device is both calling the `onRegister` callback correctly and receiving subsequent notification alerts but the `onNotification` handler is not being called at all. This is a problem because it prevents me from `PushNotification.setApplicationIconBadgeNumber()` in an appropriate manner. I'm pretty sure that the handler is not being called at all because, in Xcode, I am not even receiving the provided log output of `onNotification` in the example `PushNotification.configure` code (`console.log( 'NOTIFICATION:', notification );`). I am, however, receiving the log output of `onRegister` (`console.log( 'TOKEN VALUE: ' + token );`

**Comment by vanhungoz** [comment]
@ndc466 , did you resolve it? i also got the same issues. i have tried some way but it didn't work.

**Comment by ndc466** [comment]
@vanhungoz No, this is still an open issue/possible bug.

**Comment by vanhungoz** [comment]
@ndc466  i realize that it doesn't happen with equal and greater ios 10.3

**Comment by HoogsterInc** [comment]
I have this problem on Android when the app is closed or in the background. onNotification is not called

**Comment by MarkRamsden** [comment]
> @ndc466 , did you resolve it? i also got the same issues. i have tried some way but it didn't work.

did you ever get to the bottom of this ? Having same issue with ios11 kind of halted my development now

**Comment by mrtomhoward** [comment]
@MarkRamsden I spent several hours dealing with this issue the other day, and the thing that got it working was to ensure the message payload object had **only** a **data** key and **nothing else**.

All the time I was having troubles, my message payload object had other keys (eg "notification") in addition to data.  When that was the case, the message looked different in the Android notifications drawer (large icon was missing), and it didn't trigger **onNotification** when I tapped it. 

When I removed all keys other than **data**, the message looked the same in the notifications drawer as it did when the app was in the foreground, and it triggered **onNotification** when I tapped it.

**Comment by mrtomhoward** [comment]
@HoogsterInc I spent several hours dealing with this issue on Android the other day, and the thing that got it working was to ensure the message payload object had only a data key and nothing else.

All the time I was having troubles, my message payload object had other keys (eg "notification") in addition to data. When that was the case, the message looked different in the Android notifications drawer (large icon was missing), and it didn't trigger onNotification when I tapped it.

When I removed all keys other than data, the message looked the same in the notifications drawer as it did when the app was in the foreground, and it triggered onNotification when I tapped it.

**Comment by experionarjun** [comment]
> @HoogsterInc I spent several hours dealing with this issue on Android the other day, and the thing that got it working was to ensure the message payload object had only a **data** key and **nothing else**.
> 
> All the time I was having troubles, my message payload object had other keys (eg "notification") in addition to data. When that was the case, the message looked different in the Android notifications drawer (large icon was missing), and it didn't trigger onNotification when I tapped it.
> 
> When I removed all keys other than data, the message looked the same in the notifications drawer as it did when the app was in the foreground, and it triggered onNotification when I tapped it.
> 
> I also had to take care to ensure Firebase was installed correctly, but simply following the instructions in the [readme](https://github.com/zo0r/react-native-push-notification/blob/master/README.md) was enough to get that right.

Could you paste a sample of your payload?

**Comment by VicEsquivel** [comment]
@ndc466 is this still an issue? Or did you find a way to solve this?
