### ISSUE TITLE
Not get notification when app in background in android

### ISSUE THREAD

**Issue by adirzoari** [zo0r/react-native-push-notification#745]
Hello,
I'm not getting notification when app is closed. 
I'm looking to implement to get notification when app is closed and when I press on notification is open the app. is any have any example of it?

```
`componentDidMount() {
        const { currentState } = AppState
        
        this.initPushNotification()
        this.initEventPushNotification()
    
    }
```

    initEventPushNotification(){
        AppState.addEventListener('change', (state) => {
            console.log(state)
            if (state === 'background') {
              PushNotification.popInitialNotification((notification) => {
                if (notification) {
                  this.onNotification(notification);
                }
              });
              PushNotification.setApplicationIconBadgeNumber(0);
            }
          });
    }
    

    initPushNotification(){
        console.log('init')
        PushNotification.configure({

            // (optional) Called when Token is generated (iOS and Android)
            onRegister: function(token) {
                AppStore.setFCMToken(token.token)
                FirebaseService.setTokenData(token.token)
            },
        
            // (required) Called when a remote or local notification is opened or received
            onNotification: function(notification) {
                if (!notification.userInteraction) {
                    PushNotification.setApplicationIconBadgeNumber(0);
                  }
                if(notification){
                    console.log(notification)
                    PushNotification.localNotification({
                        /* Android Only Properties */
                        id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
                        ticker: "My Notification Ticker", // (optional)
                        autoCancel: true, // (optional) default: true
                        largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
                        smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
                        bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
                        subText: "This is a subText", // (optional) default: none
                        color: "red", // (optional) default: system default
                        vibrate: true, // (optional) default: true
                        vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
                        tag: 'some_tag', // (optional) add tag to message
                        group: "group", // (optional) add group to message
                        ongoing: false, // (optional) set whether this is an "ongoing" notification
                    
                        /* iOS only properties */
                    
                        message: "My Notification Message", // (required)
                        playSound: false, // (optional) default: true
                        soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
                        number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
                        repeatType: 'day', // (Android only) Repeating interval. Could be one of `week`, `day`, `hour`, `minute, `time`. If specified as time, it should be accompanied by one more parameter 'repeatTime` which should the number of milliseconds between each interval
                        actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
                    });
                }
                // process the notification
        
                // required on iOS only (see fetchCompletionHandler docs: https://facebook.github.io/react-native/docs/pushnotificationios.html)
                // notification.finish(PushNotificationIOS.FetchResult.NoData);
            },
        
            senderID: "xxxxxxxxxxxxxx",// I removed because the example
        
            // IOS ONLY (optional): default: all - Permissions to register.
            permissions: {
                alert: true,
                badge: true,
                sound: true
            },
        
            // Should the initial notification be popped automatically
            // default: true
            popInitialNotification: true,
        
            /**
              * (optional) default: true
              * - Specified if permissions (ios) and token (android and ios) will requested or not,
              * - if not, you must call PushNotificationsHandler.requestPermissions() later
              */
            requestPermissions: true,
        });
        
        
    }`

**Comment by aspidvip** [comment]
https://github.com/zo0r/react-native-push-notification/issues/547

**Comment by iamrutvik** [comment]
React Native Push Notifications clearly states that we need to call configure outside of the React Native Lifecycle. This is very important. 

https://product.farewell.io/visible-react-native-push-notifications-that-work-on-both-ios-and-android-5e90badb4a0f

https://prnt.sc/k61hz7
