### ISSUE TITLE
cannot build android anymore: Could not find common.jar

### ISSUE THREAD

**Issue by schumannd** [zo0r/react-native-push-notification#748]
Without changing anything about the code, I cannot build android anymore.
The following error happens when running `./gradlew clean`:

```

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-push-notification'.
      > Could not find common.jar (android.arch.core:common:1.0.0).
        Searched in the following locations:
            https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar
```

What could be the issue here?

react-native-cli: 2.0.1
react-native: 0.51.0
react-native-push-notification@3.0.2

**Comment by puneet94** [comment]
same issue

**Comment by medportal2016** [comment]
same issue

**Comment by saynorio** [comment]
I am facing the same issue

**Comment by prpateldev** [comment]
same issue with runtime.jar

**Comment by FreddyPoly** [comment]
Seems like bintray has some problem with their files, you can change your `android/build.gradle` file to fix it temporarly and add another source to download from:

```javascript
allprojects {
    repositories {
        mavenLocal()
        maven { url 'https://maven.google.com' } <-- add this
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
```

Thanks to this [response](https://stackoverflow.com/questions/50563338/could-not-find-runtime-jar-android-arch-lifecycleruntime1-0-0/50564224)

**Comment by saynorio** [comment]
@FreddyPoly Your solution works for me. Many Thanks

**Comment by RossKinsella** [comment]
@FreddyPoly Your workaround solved the issue for me two weeks back but it seems I'm getting jcenter releated build failures again. Any ideas?

```
Download https://jcenter.bintray.com/android/arch/lifecycle/common/1.0.0/common-1.0.0.jar

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
```

**Comment by leofernandezg** [comment]
+1 Please fix this issue.

**Comment by ASteinheiser** [comment]
@joshuapinter Thank you for that snippet of information. That made a huge difference for me :)
