### ISSUE TITLE
onNotification is fired off in the background, not when notification is clicked. 

### ISSUE THREAD

**Issue by jgconti96** [zo0r/react-native-push-notification#751]
I have seen many people struggling with the same thing along with others not struggling at all. Is this an issue with the package or just the way each person implements it? My onNotification is being called when I receive a notification in the background rather than when it is clicked. 

The package specifies that " // (required) Called when a remote or local notification is opened or received" for onNotification. Does this mean that there is an option to fire off onNotification when it is received OR when it is clicked? I am very confused by this.

If anyone has some input on this, I'd appreciate it!

**Comment by xralphack** [comment]
struggle in this problem +1,  onNotification only called after user click the notification

**Comment by xralphack** [comment]
I used iOS 10.10 unnotificationcenter to achieve this, but this package do not support yet

**Comment by Gp2mv3** [comment]
Can you log the parameter sent to onNotification ?
Normally, you should receive two notifications: One for background and one because of the click on the icon.

**Comment by Luckygirlllll** [comment]
@Gp2mv3  here  is notification in onNotification
collapse_key :"com.xxx"
foreground:true
google.message_id:"xxx"
google.sent_time:1530884451638
google.ttl:2419200
id:"-1209190223"
notification:{body: "You’ve got $1 on the way", icon: "ic_launcher", title: "Approved"}
show:"CONFIRMATION"
userInteraction:false

**Comment by Luckygirlllll** [comment]
I receive only one notification, when app is opened, when app is closed, and I'm clicking on the notification, onNotification method is not triggered at all.

**Comment by muhzi4u** [comment]
@Luckygirlllll Did you any solution?

**Comment by muhzi4u** [comment]
@Luckygirlllll #547 Resolved  the issue

**Comment by Luckygirlllll** [comment]
@muhzi4u How did you exactly resolve the issue? You just copied and pasted RNPushNotification class as it was shown in issue 547?

**Comment by muhzi4u** [comment]
@Luckygirlllll Yes
