### ISSUE TITLE
Push notification doesn't work when closing android app

### ISSUE THREAD

**Issue by oron11** [zo0r/react-native-push-notification#752]
I changed the file as said in this issue: 
https://github.com/pismo/react-native-push-notification/commit/7d4dad8e0f5c87d2d8e5240cd28295726bd3e6d0

 and still when I'm closing the app on the app list view with 'x'
The notification doesn't executed, In addition I don't see any error on the log.
I have checked and sure that my code gets there.

This is the original issue:
https://github.com/zo0r/react-native-push-notification/issues/547

**Comment by bodhish** [comment]
+1, Any fix for this issue?

**Comment by oron11** [comment]
I solved that by doing a `service` in the native code.
The service register as any other service in the android and activate the method `onTaskRemoved`
when user closing the app:

`public class MyService extends Service {

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    @Override
    public void onTaskRemoved(Intent rootIntent) {
        System.out.println("onTaskRemoved called");
        super.onTaskRemoved(rootIntent);
        //do something you want

        Intent service = new Intent(getApplicationContext(), NotificationActionHandlerService.class);
        Bundle bundle = new Bundle();
        bundle.putString("foo", "bar");
        service.putExtras(bundle);
        getApplicationContext().startService(service);
        System.out.println("---> Send from service to the second service");
        //stop service
        this.stopSelf();
    }
}`
 
and from there the service activate a method in the react native code.

**Comment by bodhish** [comment]
@oron11 Not experienced with native coding. 
Can you explain what could be the easy hack to get scheduled notifications even if the app is closed.

**Comment by oron11** [comment]
@bodhish Unfortunately I could not find an easier solution

**Comment by bodhish** [comment]
@oron11 Thanks for sharing. 👍
