### ISSUE TITLE
update badge without sending notification (Android)

### ISSUE THREAD

**Issue by ghjer** [zo0r/react-native-push-notification#759]
I'd like to update the badgeNr on Android without sending a notification. 
Currently the listener creates a message, title, sound, color if left empty resulting in a notification even though my notification block in the gcm request is left empty (https://stackoverflow.com/questions/36555653/push-silent-notification-through-gcm-to-android-ios)

https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationListenerService.java

**Comment by ghjer** [comment]
I've bypassed it by just sending empty message,title, sound and color:
```
                    [
                      'message' => '',
                      'title' => '',
                      'sound' => '',
                      'color' => '',
                    ]
```

**Comment by peacechen** [comment]
Note in the documentation:
https://github.com/zo0r/react-native-push-notification/blob/a071458feafc80a7a23cc43258d43f645833c0e9/trouble-shooting.md#4-mixed-remote-push-notifications

> By adding `message` field to a silent notification the library will synthesize a local notification as well as deliver a silent notification to your app.

In order to block notifications from automatically popping up in the phone's notification center, remove the `message` key in the `data` field (in addition to omitting the `notification` key).

**Comment by grit96** [comment]
@ghjer setting an empty message still triggers a local notification to show (but with no message or title).

@peacechen removing the message field from the notification will cause it to not be sent to the notification centre (https://github.com/zo0r/react-native-push-notification/blob/master/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L143) thus never setting the badge number.

Is there a way of setting the badge number without sending a visible local notification?
