### ISSUE TITLE
Cannot find symbol. DefaultHardwareBackBtnHandler

### ISSUE THREAD

**Issue by ys27** [zo0r/react-native-push-notification#76]
I'm running a new project with this module and I am getting this error. I've followed the installation steps, except that MainActivity extends ReactActivity instead of Activity (which causes more errors). In both cases, however, I get the cannot find symbol error.

**Comment by anandrew1995** [comment]
I imported the DefaultHardwareBackBtnHandler by adding
import com.facebook.react.modules.core.DefaultHardwareBackBtnHandler;

not sure if this is the right way. Also, the same error (cannot find symbol) happens to 
 new VectorIconsPackage(),
 new FabricPackage(),

which I just commented out for now.
