### ISSUE TITLE
Alert is not displayed....When clicking on push notifications.

### ISSUE THREAD

**Issue by harikanammi** [zo0r/react-native-push-notification#760]
Hi, I am running sample application..... I am using this module for push notifications..... My problem is when clicking on push notifications after clearing the instance of the app...In onNotification() console is printed but alert is not displayed even try to keep time out for the alert but it doesn't work..... this is problem is getting for only iOS....... Please give any suggestions.......

**Comment by Gp2mv3** [comment]
Did you manage to fix your issue ?
Can you show a code snippet ?
