### ISSUE TITLE
Notifications are not working on Android when application is closed

### ISSUE THREAD

**Issue by massoprod** [zo0r/react-native-push-notification#761]
We have problem with remote notifications, when application is closed on Android, then notifications are not working.
But when I have application in Debug mode (Debug JS remotely), console will reboot after send remote notification but notification will not be displayed.
When application is on foreground or minimized, notifications are working.

Package react-native-push-notification is normaly working in our app, we can see device info and other log informations about notification event in console, but when we close the app, notification is not displayed and phone is not ringing and we can not see notification in notification center.

**This problem is only on Android devices.**

`"react-native": "0.45.1"`
`"react-native-push-notification": "3.0.2"`

**Comment by vvavepacket** [comment]
Somebody implemented a fix for this, please check this out and try it out

https://github.com/zo0r/react-native-push-notification/issues/626

**Comment by vvavepacket** [comment]
I'm also encountering the same issue.

**Comment by massoprod** [comment]
Problem was solved with upgrade google-services

**Comment by manuTro** [comment]
@massoprod  how do you solve?

**Comment by muhzi4u** [comment]
@massoprod How did you solve the problem?

**Comment by nikhilgohil11** [comment]
I am facing the same issue. Notification only appears in a tray with sound if the app is connected to debuger on chrome. Even I tried generating debug apk but Notification doesn't appear.
