### ISSUE TITLE
Notification image

### ISSUE THREAD

**Issue by mj-mehdizadeh** [zo0r/react-native-push-notification#764]
How to place a custom image instead of the app icon? 
I want to show Avatar of user in a messenger application

**Comment by Gp2mv3** [comment]
The plugin doesn't handle big pictures currently. It can be something interesting to add indeed !

**Comment by GabeConsalter** [comment]
Any prediction for this resource @Gp2mv3 ?

**Comment by Gp2mv3** [comment]
I'm not planning on developing this feature myself. Feel free to propose a PR.
