### ISSUE TITLE
notification not working in android 8 galaxy s8

### ISSUE THREAD

**Issue by roysG** [zo0r/react-native-push-notification#768]

**Comment by roysG** [comment]
I get token, but none of notification is shown.

**Comment by Gp2mv3** [comment]
Isn't it related to Oreo ? See PR #771 which is now merged.

**Comment by batuhanorhn** [comment]
I have same problem. Please help.

**Comment by MaximusBaton** [comment]
I'm was facing with the similar issue, and updated this lib from git directly.
However, custom music is not working on my Android 8.0 (API26)
Works fine on API 19 - 25

Is there any workaround to fix it?

**Comment by Gp2mv3** [comment]
@MaximusBaton Can you open another issue for that ? It's indeed related but different as this bug.
