### ISSUE TITLE
GCM joins Firebase CM

### ISSUE THREAD

**Issue by sibelius** [zo0r/react-native-push-notification#77]
https://developers.google.com/cloud-messaging/faq

It looks like Google Cloud Messaging is now part of Firebase Cloud Messaging

This package will upgrade to FCM ? or should we start a react-native-fcm as FCM is cross-platform?

**Comment by vmakhaev** [comment]
[react-native-fcm](https://github.com/evollu/react-native-fcm)

**Comment by dcworldwide** [comment]
@vmakhaev @sibelius Thanks for info. So for firebase apps, should we not use this package and instead use react-native-fcm exclusively?

**Comment by wakeless** [comment]
As far as I'm aware, Firebase is backwards compatible with GCM. Certainly, I've just developed a solution with this and Firebase.

**Comment by sibelius** [comment]
@wakeless what is the GCM Sender ID in the case of using FCM?

**Comment by sibelius** [comment]
@dcworldwide did u find the answer for ur question?

**Comment by agenthunt** [comment]
@wakeless .  I am trying to do similar stuff using firebase backend with only react-native-push-notification module. I am not using react-native-fcm.   
However, onNotification is not being called. Is there anything special that needs to be done when using with firebase backend?

**Comment by sibelius** [comment]
@agenthunt FCM tokes are different from GCM tokens used in react-native-push-notication

**Comment by agenthunt** [comment]
@sibelius How is that relevant here w.r.t react-native-push-notification ? Please correct me If I am wrong. My understanding was that device tokens are used to identify device to APNs and not relevant to push service be it GCM or FCM or onesignal etc ?

**Comment by sibelius** [comment]
FCM has its own tokens that differ from GCM and APNs, so if u have a GCM or APN token u can't use firebase in ur backend.

First u need to convert them to FCM token, there is an import tool on firebase to handle this

Idk if there an export tool if u wanna leave Firebase after some time

**Comment by geekvijay** [comment]
is it works with FCM ?

**Comment by kjprice** [comment]
Helpfully this might help someone. 

First off, be sure to register for GCM https://developers.google.com/mobile/add. Super important.

Once you register, note that you will receive an API key and a sender id. Be sure to use the **sender id** in the `PushNotification.configure` method
