### ISSUE TITLE
Is there any plan to update the plugin to work with android oreo?

### ISSUE THREAD

**Issue by roysG** [zo0r/react-native-push-notification#770]

**Comment by gongmingqm10** [comment]
I have created one PR to fix the Android Oreo notification channel issue.

https://github.com/zo0r/react-native-push-notification/pull/771

**Comment by sinhpn92** [comment]
we have change this repository source to use on android oreo.
Hope you fix this issue as soon as @gongmingqm10 :)

**Comment by Gp2mv3** [comment]
I merged PR #657 to handle the Oreo Channels ID. It should be ok now with the package version from git directly.
