### ISSUE TITLE
[Solved] Notification icon on wearable

### ISSUE THREAD

**Issue by guidovizoso** [zo0r/react-native-push-notification#773]
Hi everyone!

I have a little problem: The icon on wearables (Samsung Gear to be precise) is always the default 'ic_launcher' icon. I already replaced the original icon and it displays fine on the phone but not on the watch. Does anyone knows where this icon is coming from?

```
PushNotification.localNotificationSchedule({
      date: new Date(Date.now() + (15 * 1000)),
      title: "Edesur está por vencer",
      message: "Tu factura de $ 353,40 vence el viernes 29/6",

      // Android only
      actions: '["Pagar", "Cerrar"]',
      largeIcon: 'ic_launcher', 
      smallIcon: 'ic_launcher',

      // iOS only
      alertAction: 'Pagar',

    });
```
![screenshot_20180628-105531](https://user-images.githubusercontent.com/27702539/42039394-96862b8a-7ac3-11e8-8e05-3fa1731a0d6b.jpg)

![img_20180628_105527 1](https://user-images.githubusercontent.com/27702539/42039408-9d457002-7ac3-11e8-987f-b99dfe88839f.jpg)

Thanks in advance!

**Comment by guidovizoso** [comment]
Making a new project solved the issue. Maybe it was the watch's cache.

**Comment by ThanhQuang1410** [comment]
@guidovizoso Hi there! I'm having the same code as your. But my icon is default of android not my ic_launch i want. After re-check I found that only drawable folder have my ic_launch. Do you have any solution to get icon from drawable.

Thanks
