### ISSUE TITLE
How to handle iOS notification opened when user click into notification?

### ISSUE THREAD

**Issue by sinhpn92** [zo0r/react-native-push-notification#774]
Hello,
I have used:
```
"react": "^16.0.0",
"react-native": "^0.55.3",
"react-native-push-notification": "^3.0.2",
```
I have issue on iOS device, when the user click into notification. The callback `onNotification` do not call. So i can't handle next action for user after click into notification. I have tested on Android device and it's work fine but iOS dont.

I have tried to add:
```
componentDidMount() {
      PushNotification.popInitialNotification(notification => {
          console.log('PushNotification.popInitialNotification222', notification)
      })
  }
```
But it still nothing to return callback.

Have any problem here and how can i handle notification when user click into notification?

**Comment by Gp2mv3** [comment]
I've the same issue, clicking the app icon.

**Comment by AaronDRS** [comment]
I'm facing the same issue, any idea or soon fix to handle this?

**Comment by mehulmpt** [comment]
Any update?
