### ISSUE TITLE
Android checkPermissions method

### ISSUE THREAD

**Issue by gpawlik** [zo0r/react-native-push-notification#775]
I am wondering whether the permission check feature on Android is planned to be introduced soon. Currently there is only a placeholder for that method in the `component/index.android.js`:

```
NotificationsComponent.prototype.checkPermissions = function(callback: Function) {
	/* Void */
};
```

In case it is not in the roadmap I would like to ask if you are aware of any workarounds to check this permission?

**Comment by Gp2mv3** [comment]
There is a PR for that: #721 can you review it ?

**Comment by Gp2mv3** [comment]
PR #721 is merged so I close this Issue too. Thanks !

**Comment by TommyLeong** [comment]
Late to party. But I don't manage to get any respond back from the following, any mistake spotted? 

```
async componentDidMount() {
PushNotification.checkPermission().then((response) => {
      if (response && response.alert !== 0) {
        console.log(response)
        return; 
      }
        console.log(response)
    });

}
```
