### ISSUE TITLE
Notification bar clicked remote notification doesn't work onNotification

### ISSUE THREAD

**Issue by batuhanorhn** [zo0r/react-native-push-notification#776]
App when background click notification in notification bar doesn't work onNotification. 

Please help me.

**Comment by Gp2mv3** [comment]
Did you put popInitialNotification to true ?
What OS are you testing on (iOS/Android) ?

**Comment by batuhanorhn** [comment]
I solved the problem. You can follow the steps there.

https://github.com/zo0r/react-native-push-notification/issues/547
