### ISSUE TITLE
failed to find Build Tools revision 23.0.2 - react 0.26

### ISSUE THREAD

**Issue by TUNER88** [zo0r/react-native-push-notification#78]
```
Building and installing the app on the device (cd android && ./gradlew installDebug...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-push-notification'.
   > failed to find Build Tools revision 23.0.2
```

**Comment by TUNER88** [comment]
Fixed by running project from Android Studio, it asks for installing the missing build tools version

**Comment by mklb** [comment]
For all others not working with android studio, update your build tools like: `android list sdk -a  `
this prints a list of all available versions 
install the version via `android update sdk -a -u -t YOUR_VERSION_ROW_NUMBER` (for me the version was number: 7)

**Comment by devekoperiOS** [comment]
I have updated my SDK from android studio. But still it gives me the same error.
