### ISSUE TITLE
Getting the notification when custom server has new data

### ISSUE THREAD

**Issue by yangnana11** [zo0r/react-native-push-notification#781]
Hello,

I am looking around for anything suit my purpose, but I found none. I hope someone could help me to reach my objective....
I have my own database, which I get or post the data through API. There is a table in my database which shows the messages and titles which I need to send to my mobile app as notification if they are new and my mobile haven't seen before.
I figured out there are three types of notifications here: local, schedule and push.
- Push: out of question. I use my own database and I don't know how to make it as a server to push data automatically. FCM seems good I have to stuck with this database.
- Local: seems okay, but I don't know how to make it run automatically when the app goes background. I made it timer and when I close it, the timer stops.
- Schedule: my last hope. But I need to check it first: if.... I will send a notification, if fail, send nothing .

I am new to this, it's been only 2 days so I know I missed a lot of things. But is there a way for my objective?

Thanks for reading this,
Nana,

**Comment by Gp2mv3** [comment]
It seems to be the exact use case of Push notifications.
You can use node-fcm or node-gcm to do this with node JS for instance.

But it's not really an issue related to this package so I close it.
