### ISSUE TITLE
background notification not showed on android

### ISSUE THREAD

**Issue by manuTro** [zo0r/react-native-push-notification#782]
Hi,
I've just upgraded my app to react-native 0.55.4 and react-native-push-notification from 3.0.0 to 3.0.2. 
Notifications were working fine, but now I'm receiving the notification (I can see them in my console) but on background nothing happens. What is changed??
i can see that the notification has arrived from the console log but on the notification bar nothing..

thx

**Comment by deorukhkarchaitanya** [comment]
+1

**Comment by Gp2mv3** [comment]
How do you send the notification ? What's the payload you send ?

**Comment by deorukhkarchaitanya** [comment]
So my notifications are working fine on gradle-2.14.1 but not working on gradle-4.4

**Comment by manuTro** [comment]
Anyone found a solution?

**Comment by SimonBao** [comment]
I'm also currently facing this issue, any information would be appreciated!

**Comment by loyoliteabid** [comment]
I am also not getting notification on android after updating react-native-push-notification to `"react-native-push-notification": "^3.1.1",`

It was working fine on `"react-native-push-notification": "^3.0.2",`

Any solution?
```
"react": "16.4.1",
    "react-native": "0.56.0",
```

**Comment by Taylor123** [comment]
Any update on this issue. Currently unable to get the notifications to show in the notification center on android when the app is backgrounded. Have tried the trouble-shooting guide as well.
