### ISSUE TITLE
Strange Behavior on the second button

### ISSUE THREAD

**Issue by Angelk90** [zo0r/react-native-push-notification#783]
@zo0r, @Gp2mv3:
Strange Behavior on the second button, as seen in the image when the second button is selected.

![](https://i.imgur.com/vqUdk7u.jpg)

**Comment by Gp2mv3** [comment]
You don't need to mention me in your issue message. :wink: 

How did you declare the two buttons ?

**Comment by Angelk90** [comment]
@Gp2mv3 :  As in the example you find in the readme file of the local notification function

**Comment by Gp2mv3** [comment]
What's your Android version ?

**Comment by Angelk90** [comment]
@Gp2mv3 : Android 7.0.

**Comment by Angelk90** [comment]
@Gp2mv3 : Are there any news?

**Comment by Gp2mv3** [comment]
Frankly no, I even think it's an Android bug. Did you try with 3 buttons ? Is it always happening with the last button ?

**Comment by joruro** [comment]
Actions just don't work. I click on them an nothing happens

**Comment by Gp2mv3** [comment]
It works but not when app is in background. I'm on it.
