### ISSUE TITLE
Notification not coming

### ISSUE THREAD

**Issue by batuhanorhn** [zo0r/react-native-push-notification#784]
I applied all the necessary settings. Token coming but  notification not coming please help me.

Version:
React: 16.3.1
React-Native: 0.55.4

**Comment by Dhanraj-bidchat** [comment]
i believe this is android Oreo[target version >= 27] issue.
Two methods to solve this:
1)Downgrade your android targetSdkVersion to 26 or less under 'android/app/build.gradle'.
2)I forked and fixed this. You can add this in your projects package.json : 
**"react-native-push-notification": "git+https://github.com/Dhanraj-bidchat/react-native-push-notification.git"** and remove 'react-native-push-notification: ''3.0.1', 
Then **delete react-native-push-notification** under node_modules
Then run **npm install**.

**Comment by batuhanorhn** [comment]
Resolved. I forgot to add that line:(android/app/build.gradle)

apply plugin: 'com.google.gms.google-services'

dependencies just outside

**Comment by manuTro** [comment]
@batuhanorhn for my all is working fine with android 8 but notification are not coming with android 7.. Was this same problem as yours?

**Comment by batuhanorhn** [comment]
No, I did not have a problem like that.

**Comment by manuTro** [comment]
so your notification works fine also for android 8?

**Comment by batuhanorhn** [comment]
No, i didn't try Android 8

**Comment by manuTro** [comment]
may I ask your build settings? (tarket sdk, compileSdk ecc..)?
