### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by rodrigobdz** [zo0r/react-native-push-notification#785]
Where can I find a **changelog** for [react-native-push-notification](https://github.com/zo0r/react-native-push-notification)? Without it it's hard to notice what changes between versions.
Related to #200.

What about [keep a changelog](https://keepachangelog.com/en/1.0.0/)?

**Comment by Gp2mv3** [comment]
It's indeed a good idea ! I think it's also important to release tags at the same time as releasing new updates to npm. That way, we have a sync between Github and npm.

**Comment by Gp2mv3** [comment]
Here you are, freshly pushed ! :wink: https://github.com/zo0r/react-native-push-notification/blob/master/CHANGELOG.md

**Comment by rodrigobdz** [comment]
Nice, thanks. 
Btw, in 6be5ed4762ed89780dd40864a3272f885d813a17 (_Corrected changelog links_) you added `#` to PRs. Unfortunately, Github does not convert it to links.

**Comment by Gp2mv3** [comment]
Indeed, I thought it was smart enough to figure out... I'll add the links for clarity.
