### ISSUE TITLE
error channel in Android Oreo 26 SDK

### ISSUE THREAD

**Issue by bhram** [zo0r/react-native-push-notification#788]
i used this pull https://github.com/zo0r/react-native-push-notification/pull/657

it's work fine but when app is in background it's show error 

> Failed to post notification on channel “null” Target Api is 26

**Comment by 1Jesper1** [comment]
Is there a fix for this? Is the latest version on NPM?

**Comment by Gp2mv3** [comment]
No, the latest version is not on NPM yet.
But you can use the version from git directly in npm.

**Comment by 1Jesper1** [comment]
Thanks for the advice @Gp2mv3 !
