### ISSUE TITLE
undefined is not an object ('evaluating data.getMessage')

### ISSUE THREAD

**Issue by micahmills** [zo0r/react-native-push-notification#79]
I am new to React Native so this could easily be a user error on my part, but I have included the code from the documentation into my index.ios.js and index.android.js files. It works perfectly for Android after following the instructions for Android installation. However on iOS I get a message that says "undefined is not an object ('evaluating data.getMessage')".

Do I need to do some setup to get this to work with iOS?

**Comment by soniaparikh** [comment]
You can display your notification object by using following line.
  console.log(JSON.stringify(notification));
Then by looking JSON string you can fetch value accordingly for example:
notification._data.alertBody

**Comment by dnish** [comment]
Having the same issue after adding the code:

```
PushNotification.configure({

    // (optional) Called when Token is generated (iOS and Android)
    onRegister: function(token) {
        console.log( 'TOKEN:', token );
    },

    // (required) Called when a remote or local notification is opened or received
    onNotification: function(notification) {
        console.log( 'NOTIFICATION:', notification );
    },

    // ANDROID ONLY: (optional) GCM Sender ID.
    senderID: "YOUR GCM SENDER ID",

    // IOS ONLY (optional): default: all - Permissions to register.
    permissions: {
        alert: true,
        badge: true,
        sound: true
    },

    // Should the initial notification be popped automatically
    // default: true
    popInitialNotification: true,

    /**
      * IOS ONLY: (optional) default: true
      * - Specified if permissions will requested or not,
      * - if not, you must call PushNotificationsHandler.requestPermissions() later
      */
    requestPermissions: true,
});

```

**Comment by bangerang** [comment]
You need to setup Push for iOS specifically, please see: https://facebook.github.io/react-native/docs/pushnotificationios.html#content

**Comment by npomfret** [comment]
@micahmills  do you still have this issue? if so, have you tried the latest release? if not, can we close it?

**Comment by npomfret** [comment]
Closing due to lack of response.
