### ISSUE TITLE
:react-native-push-notification:verifyReleaseResources

### ISSUE THREAD

**Issue by yoannHertienne** [zo0r/react-native-push-notification#799]
Hello, 

I got this error 👍 

Execution failed for task ':react-native-push-notification:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

This is my app/build.gradle config:
android {
   compileSdkVersion 26
   buildToolsVersion "26.0.2"
   ....

dependencies {
....
compile project(':react-native-push-notification')
compile "com.android.support:appcompat-v7:26.0.1"
    compile ('com.google.android.gms:play-services-gcm:8.1.0') {
        force = true;
    }
...

And the complete log is : 
Users/yoann.hertienne/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/17350a1e68a50ef55ecfa74fa7c33b1a/res/values-v24/values-v24.xml:3:5-157: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/Users/yoann.hertienne/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/17350a1e68a50ef55ecfa74fa7c33b1a/res/values-v24/values-v24.xml:4:5-135: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
/Users/yoann.hertienne/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/17350a1e68a50ef55ecfa74fa7c33b1a/res/values-v26/values-v26.xml:13:5-16:13: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
    
/Users/yoann.hertienne/Documents/Projects/LiquidStudio/AppBeLux/AppBelux/node_modules/react-native-push-notification/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/Users/yoann.hertienne/Documents/Projects/LiquidStudio/AppBeLux/AppBelux/node_modules/react-native-push-notification/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

/Users/yoann.hertienne/Documents/Projects/LiquidStudio/AppBeLux/AppBelux/node_modules/react-native-push-notification/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

**Comment by yoannHertienne** [comment]
You can modify your android/build.gradle according to : https://github.com/react-community/react-native-image-picker/issues/882

`subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27
                buildToolsVersion "27.0.2"
            }
        }
    }
} `

**Comment by kgricour** [comment]
@yoannHertienne  your explaination has fix my problem, however you are forgot '=' 
`subprojects {
  afterEvaluate {
    project -> if (project.hasProperty("android")) {
      android {
        compileSdkVersion = 27
        buildToolsVersion = "27.0.2"
      }
    }
  }
}`
