### ISSUE TITLE
compile sdk version 23, but NotificationChannel needs >26

### ISSUE THREAD

**Issue by ilonny** [zo0r/react-native-push-notification#801]
compile sdk version 23, but NotificationChannel needs >26
how to use with sdk 23?
https://github.com/zo0r/react-native-push-notification/blob/44cb23006087bce22c0e7763c3598931d1aee14d/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotificationHelper.java#L7

**Comment by giankotarola** [comment]
+1

**Comment by Gp2mv3** [comment]
You can't really use SDK 23. And your app won't be allowed on Play store if you target an SDK less than 26.
