### ISSUE TITLE
Download icons from URLs

### ISSUE THREAD

**Issue by khrizt** [zo0r/react-native-push-notification#810]
Hi,

I'm trying to do a PR to allow this case, sending the icons as URLs and download the images in the app to show the image as icon (large or small). I'm struggling a bit on how to do that because the RNPushNotificationListenerService starts a main thread runnable (to be able to get the ReactInstanceManager if I understood it correctly) therefore I can't run async tasks in the code. Other react libraries download the images in the FirebaseMessagingService because they don't use the main thread.

Anyone has any idea on how to do that? If I can I'll create a PR to support this.

**Comment by Thanasis1101** [comment]
Is there anything new about this issue? Because I'm trying to use icons from urls on notifications for my app. Is it supported somehow?

**Comment by gluons** [comment]
@github-actions Please no.
