### ISSUE TITLE
Notification not display when app is closed

### ISSUE THREAD

**Issue by javadi69** [zo0r/react-native-push-notification#812]
I use firebase messaging to send remote notification to my android application and displaying it with localNotification,
Everything is fine when app is in foreground or background while device screen is on.
But when app is closed or press back to exit app and then i lock device, I don't get any notifcation.

PushNotification configuration: 
<pre>
componentWillMount() {
    PushNotification.configure({
      onRegister: function(token) {
        console.log(token);
      },
      onNotification: function(notification) {
        if (notification.userInteraction) {
          this.handleNotificationPress(notification);
        } else {
          PushNotification.localNotification(notification);
        }
      }.bind(this),
      senderID: "*****",
      requestPermissions: true,
    });
    PushNotification.popInitialNotification((notification) => {
      if (notification) {
        if (notification.userInteraction) {
          this.handleNotificationPress(notification);
        } else {
          PushNotification.localNotification(notification);
        }
      }
    });
}
</pre>

AndroidManifest.xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" tools:node="remove" />
    <uses-permission android:name="${SYSTEM_ALERT_WINDOW}" tools:node="remove"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="26" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
      <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
          <intent-filter>
              <action android:name="android.intent.action.BOOT_COMPLETED" />
          </intent-filter>
      </receiver>
      <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
      <service
          android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
          android:exported="false" >
          <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
      </service>
      <activity
          android:name=".MainActivity"
          android:label="@string/app_name"
          android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
          android:windowSoftInputMode="adjustResize"
          android:launchMode="singleTop">
          <intent-filter>
              <action android:name="android.intent.action.MAIN" />
              <category android:name="android.intent.category.LAUNCHER" />
          </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

My PHP code to send notification:
<pre>
function sendNotification($devices) {
        $fcmUrl = 'https://fcm.googleapis.com/fcm/send';
        $fcmNotification = [
            'data' => [
                'title' => 'Title',
                'message' => 'Message,
                'data' => [
                    'key1' => 'value1',
                    'key2' => 'value2'
                ]
            ],
            'registration_ids' => $devices,
            'priority' => 'high',
            'time_to_live' => 600
        ];
        $headers = [
            'Authorization: key=__KEY__',
            'Content-Type: application/json'
        ];
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,$fcmUrl);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fcmNotification));
        $rs = curl_exec($ch);
        curl_close($ch);
}
</pre>

**Comment by Ilario17** [comment]
have you find a solution?

**Comment by peacechen** [comment]
The only way I've found to show a notification when the app is closed or killed is for the server to set the `notification` key.   This won't trigger JS code to run in the app though.  The user has to click on the notification which opens the app.

**Comment by rikur** [comment]
https://github.com/zo0r/react-native-push-notification/issues/1329#issuecomment-613158114
