### ISSUE TITLE
DST impact on repeating notifications

### ISSUE THREAD

**Issue by GustawOhler** [zo0r/react-native-push-notification#819]
How does DST affects repeating notifications? I have two use cases of this type notifications in my application - daily and once every few days so i have to use repeatType "day" and "time" and I wonder if DST time changes won't mess up notification making it hour too early or too late. Do anyone have some informations about that?

**Comment by jSkrills** [comment]
@Gp2mv3, I am using **PushNotification.localNotificationSchedule** and just noticed my notifications were showing up an hour too early after DST. Several different repeatTypes were showing this behavior. Let me know if I can provide any other information.
