### ISSUE TITLE
Documentation should be updated about what data we suppose to send from server.

### ISSUE THREAD

**Issue by Durgaprasad-Budhwani** [zo0r/react-native-push-notification#82]
Hi Jorge Trujillo,

First of all, thank you very for for wonderful react native package.  When my application is closed, I was not able to get push notification. After 1 day debug, I found that when we send notification message from server, we have to include title and message as key otherwise notification will not be visible.

e.g 
```
message.addData('title', 'This is my title');
message.addData('message', 'This is my message');
```

Can you please update document accordingly.

Regards,
Durga

**Comment by npomfret** [comment]
See my comments in #84
