### ISSUE TITLE
Notification not shown on device

### ISSUE THREAD

**Issue by nhuurnink** [zo0r/react-native-push-notification#825]
Hi,

I used your configuration to setup notifications for our react native application. I'm using the notification hub from azure to send messages, and from the azure portal, I get a valid response when pushing to the PNS, confirming the message is sent to 1 target.

However I don't see any notifications on my device, also when I don't use tags. Is there a proper way to debug this? We are using firebase and configured the senderID and everything.

When working through https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-push-notification-fixer and comparing this with zo0r documentation, I see microsoft requires a projectID, as wel as using the ListenConnectionString somewhere on te client. According to your documentation, this is not required at all.

I'm not sure where to go from here, any thoughts?

**Comment by nhuurnink** [comment]
Ok it is sending the notification, but our app crashes... As in other issues already out there. Therefore I close.

**Comment by cassianomon** [comment]
@nhuurnink Hey, could you give me the steps you followed to get the notification?

I configured the steps from the repository documentation, but I don't see where to connect the azure with the firebase, I just put the firebase Server key on Azure notification hub, and the Firebase app senderID on my PushController, don't see where to go now...
