### ISSUE TITLE
Allow automatic deployment 

### ISSUE THREAD

**Issue by rhdeck** [zo0r/react-native-push-notification#827]
Right now the library requires manual edits to the Android Manifest and a couple build.gradle files. Let's add some rnpm link directives to allo deployments to happen automatically.

**Comment by Gp2mv3** [comment]
I just saw your issue and PR. Why did you revoke it finally ? Wasn't it working "as-is" ?

**Comment by rhdeck** [comment]
I've made a new PR - #836. There was a dependency on `react-native-update-gradle` that I had not included in the prior package.
