### ISSUE TITLE
Close notification  on tap

### ISSUE THREAD

**Issue by humbleBeginner** [zo0r/react-native-push-notification#832]
Hello, is there a way to automatically close the notification when `notification.userInteraction` is `true`.

**Comment by Gp2mv3** [comment]
Hey,
Did you try the autoCancel to the payload ?

**Comment by humbleBeginner** [comment]
@Gp2mv3  Yes, I've tried that already. And the doc says the default is `autoCancel: true`

**Comment by humbleBeginner** [comment]
Suddenly it works! The notification auto hides when tapped.
