### ISSUE TITLE
Not working when app is closed on a `release build`.

### ISSUE THREAD

**Issue by karlmarxlopez** [zo0r/react-native-push-notification#838]
Related to #812

How can I properly configure the library to work even if the app is completely closed(i.e not running on background)

**Comment by sebinator** [comment]
any news about the issue?

**Comment by sebinator** [comment]
same here, working in foreground+background. But not when app closed/killed

**Comment by mak12** [comment]
Any update?

**Comment by lisichka999** [comment]
@karlmarxlopez, have the same issue, it it Android? Should it work in debug mode as well?

**Comment by karlmarxlopez** [comment]
@lisichka999 We've used `react-native-firebase` instead of this library. It is a lot easier to use and the documentation is awesome.

**Comment by lisichka999** [comment]
@karlmarxlopez we use firebase v5, but because of v6 of firebase does not include notifications I want to try to switch to this library
