### ISSUE TITLE
No res/raw directory for adding custom sound

### ISSUE THREAD

**Issue by pohara9720** [zo0r/react-native-push-notification#840]
I am trying to add custom .wav sound clip into my project. I have added the file to the IOS Resources in Xcode but i cant find a res/raw directory to add it for android.

**Comment by pohara9720** [comment]
I've added the directory myself and will hope that will work for android. For anyone else looking at this confused about sounds
IOS requires .wav .aiff .caf file audio formats and must be below 30 seconds in duration.
Android requires .wav .mp3 .ogg audio formats and doesnt seem to have a time restriction.

**Comment by HasnainAD** [comment]
@pohara9720  You saved my many hours. Just to add one more thing res/raw is not necessary in IOS. Just add audio files to Bundle Resources.  Also Please close this issue.
