### ISSUE TITLE
Support for SFMC (Salesforce Marketing Cloud)

### ISSUE THREAD

**Issue by sanketpardeshi** [zo0r/react-native-push-notification#841]
Hi,

Quick help needed. Can we use this package with SFMC (Marketing cloud) to receive push notification sent via SFMC?

**Comment by rkaartikeyan** [comment]
> Hi,
> 
> Quick help needed. Can we use this package with SFMC (Marketing cloud) to receive push notification sent via SFMC?

I am stuck with Android with SFMC, can you help me out what changes required to receive push in React Native?
