### ISSUE TITLE
JSON value '<null>' of type NSNull cannot be converted to NSDictionary

### ISSUE THREAD

**Issue by vikrantnegi** [zo0r/react-native-push-notification#843]
# Description
I'm using the example project files in my project to test the notifications and it is working fine in Android.

But on iOS, I'm getting this error

`JSON value '<null>' of type NSNull cannot be converted to NSDictionary`

whenever I'm clicking on local as well as schedule notification. Although It is working fine and I'm receiving the notification but I'm getting this error every time I'm clicking on them.

![img_0196](https://user-images.githubusercontent.com/3294287/44571125-8356ad80-a79d-11e8-9062-c222575243ab.jpg)

# Details
"react-native-push-notification": "^3.1.1",
"react": "16.4.1",
"react-native": "0.56.0",

**Comment by vygandas** [comment]
Same here.

**Comment by efstathiosntonas** [comment]
same here

**Comment by jriiringan** [comment]
i tried to fix this by passing an empty object on userInfo instead of null value for notification.

**Comment by vikrantnegi** [comment]
@jriiringan I'm getting the same error. Were you able to fix it using that?

**Comment by jriiringan** [comment]
@vikrantnegi  yes i did. the default example send "null" value so i replace it by an Object.

**Comment by SCJMENGMENG** [comment]
Modify the NotifService's "category" to be a string,'userInfo'to be a dictionary, and'number' to be a number.

**Comment by anhvd** [comment]
@SCJMENGMENG s
thank for your answer, that's true.

**Comment by hungdev** [comment]
@SCJMENGMENG it's worked for me. thank u.

**Comment by e1016** [comment]
In my case, for future references, the problemas was a `null` value for `Image uri` getted from server

`<Image source={{ uri: data }}>` <- `data is null`

**Comment by Dallas62** [comment]
I fixed the README and example application.

**Comment by kovkev** [comment]
Has anyone gotten react-native-push-notification working with node-pushnotifications ?

I try to get node-pushnotification to send a push notification to my app, which shows a push notification on ios, but then when I click on it (react-native-push-notification is handling here), then I get the same error as above:

`JSON value '<null>' of type NSNull cannot be converted to NSString`

**Comment by kovkev** [comment]
It was happening because I did 

```
PushNotification.cancelLocalNotification({ id: notification.data.notificationId });
```
