### ISSUE TITLE
Sound Android

### ISSUE THREAD

**Issue by mobileDevNativeCross** [zo0r/react-native-push-notification#85]
Hello.
I sent notification from server:
`curl -X POST -H "Authorization: key=key" -H "Content-Type: application/json" -d '
{
  
  "notification": {
   "sound": "default", }
  "data": {
    
    "notification": {
      "title": "Hello",
      "subject": "Hello GCM",
      "message": "Hello from the server side!"
    }
  },
  
  "to" : "<to>"
}' 'https://gcm-http.googleapis.com/gcm/send'`
I have sound but, not see message in my Android Studio and missing text on top curtain

**Comment by npomfret** [comment]
This might help you: https://github.com/zo0r/react-native-push-notification/issues/84#issuecomment-223525439
