### ISSUE TITLE
Update Application Icon Badge Number iOS when userInteraction is false 

### ISSUE THREAD

**Issue by YahiaJabeur** [zo0r/react-native-push-notification#853]
I want to update the Application Icon Badge Number iOS when the app is closed.
I can update it when userInteraction is true, but when userInteraction is false it won't work

Background Modes and Remote notifications are enabled in the iOS project
 
Anyone can help ????

Everything works perfectly for Android.

**Comment by sergiulucaci** [comment]
@YahiaJabeur can you please share what the issue was? Having the same and I can't find a workaround.
