### ISSUE TITLE
How to not show notification in foreground

### ISSUE THREAD

**Issue by prih** [zo0r/react-native-push-notification#857]
How do not show notification if foreground = true?
In the previous version, the notification was not displayed if the application in foreground, I tried the current master... and have notification...

**Comment by prih** [comment]
but the current version 3.1.1 has problems with FCM... Does anyone even use this module? Or do all forks? it's strange how you can work so actively on the project and always keep it in an inoperative state... shine and poverty with open source

**Comment by cherniv** [comment]
Hey, can you please tell how did you solve it?

**Comment by prih** [comment]
@cherniv check this #859

**Comment by strawberry-code** [comment]
I am still seeing notifications shown when Android app is in active/open state. Why?
