### ISSUE TITLE
how to update badge number in background and close app IOS

### ISSUE THREAD

**Issue by nguyenvanphuc2203** [zo0r/react-native-push-notification#860]
im try use PushNotification.setApplicationIconBadgeNumber() to update remote notification IOS,
but it not work fine when app background and close!
any idea

**Comment by DavitVosk** [comment]
You need to send `badge` param in push notification and the badge will be changed automatically

**Comment by dmackinn** [comment]
Unfortunate that this was auto-closed. I'm having this issue as well, foreground notifications update the badge count but background does not

**Comment by Maddumage** [comment]
This issue still there :(
