### ISSUE TITLE
GCM

### ISSUE THREAD

**Issue by silentlight** [zo0r/react-native-push-notification#861]
Hello,

When the `fixGcm` branch will be pulled to `master` branch? I am using SNS for push notifications and I need support for GCM.

Thanks

**Comment by silentlight** [comment]
I installed this version 3.1.1 on my other computer and `RNPushNotificationListenerServiceGcm.java` is still not there. Can someone fix this problem?

**Comment by pedrofneves** [comment]
Same problem here. The app crashs when receives the notification with java.lang.ClassNotFoundException

**Comment by silentlight** [comment]
@pedrofneves I am not sure if anyone maintains this repo anymore. I tried in many channels and no response. It's a shame because I think it is a really simple thing to fix.

**Comment by pedrofneves** [comment]
Someone has pulled the branch fixGcm to master. I forked the master and now it's working!

**Comment by pedrofneves** [comment]
Yes. I don't know they generated this bugged version. Just fork the master and change the package.json: 

"react-native-push-notification": "https://github.com/XXXX/react-native-push-notification/tarball/master",

where XXXX is your git account.

Delete this module from node_module directory and run npm i

**Comment by silentlight** [comment]
Thanks @pedrofneves.

It's a really big shame that no one from maintainer hasn't fixed that and we have to do those hacks. 
I bet it's just as simple as bumping version.
I could do it for them, but not sure how to go about it :)
