### ISSUE TITLE
Custom Notification sound not working on Android when using API v26

### ISSUE THREAD

**Issue by skb1129** [zo0r/react-native-push-notification#863]
The notification custom sounds were working fine when I was using API v25 but it doesn't work with API v26. It has something to do with the new Notifications Channels on Android. Customs sounds works well on iOS though.

**Comment by MaximusBaton** [comment]
check this out https://github.com/zo0r/react-native-push-notification/issues/789

**Comment by mirzaam786** [comment]
Is there any reason why this has not been merged into the latest branch. This code is required to allow more then one sound notification - you need to have a notification channel per sound and i can't see how the latest branch can work without this change
