### ISSUE TITLE
symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by jeveloper** [zo0r/react-native-push-notification#87]
Does anyone know why RCT Push notifications is causing this 

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTPushNotificationManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64

Is it because of absence of push notifications on a simulator?

thanks

**Comment by danielbraun** [comment]
No. Seems like you haven't linked the iOS library properly:
http://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking

**Comment by jeveloper** [comment]
does rnpm link no longer work with this lib?

yeah i manually linked it, it worked

**Comment by npomfret** [comment]
@jeveloper do you still have this issue? if so, have you tried the latest release? if not, can we close it?

**Comment by jeveloper** [comment]
It's all good, non issue

thanks

**Comment by mcaranay** [comment]
I've been checking all the threads, googled and everything leads to this manual linking. What am i missing? I did follow all the necessary steps(multiple times) on this basic app just to test Notifications but still get the error.

Please help.

Followed/used:
https://github.com/zo0r/react-native-push-notification
https://facebook.github.io/react-native/docs/pushnotificationios.html#content
https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking

Also Updated AppDelegate.m according to instruction.

{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.4",
    "react-native-push-notification": "^3.1.2"
  },
  "devDependencies": {
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "24.1.0",
    "jest": "24.1.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-test-renderer": "16.6.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

<img width="864" alt="screen shot 2019-02-14 at 9 23 25 am" src="https://user-images.githubusercontent.com/10537716/52793213-3b715e80-303b-11e9-9b0b-5a411f86dc5a.png">
<img width="1134" alt="screen shot 2019-02-14 at 9 22 05 am" src="https://user-images.githubusercontent.com/10537716/52793241-4a581100-303b-11e9-9fe2-890109852351.png">
<img width="870" alt="screen shot 2019-02-14 at 9 22 28 am" src="https://user-images.githubusercontent.com/10537716/52793256-517f1f00-303b-11e9-9723-ef724f482faa.png">

**Comment by jeveloper** [comment]
@mcaranay  hey Michael, i'd recommend installing using react-native link <lib name> , then check appdelegates that all things have been added , also make sure your xcode project capabilities has push notifications enabled and setup.  Clean, rebuild. Also consider using firebase for push notifications

**Comment by mcaranay** [comment]
> @mcaranay hey Michael, i'd recommend installing using react-native link , then check appdelegates that all things have been added , also make sure your xcode project capabilities has push notifications enabled and setup. Clean, rebuild. Also consider using firebase for push notifications

Push Notification enabled also in capabilities.
![screen shot 2019-02-14 at 11 29 18 am](https://user-images.githubusercontent.com/10537716/52801444-d96d2500-304b-11e9-920d-702e340c676d.png)
I only need to test Local Notifications, so I think  i don't need firebase.
I'm new to react-native and I really appreciate your help. I have these issue for 2 days already, trying to make it work in IOS.

I have some follow up questions:

1. "Install using react-native link": Do you mean after these(install) two commands? 

npm install --save react-native-push-notification?
react-native link react-native-push-notification

2. "Check appdelegates that all things have been added": Could you please specify which exact file/location this can be checked?

Im thinking to redo everything(react-native init AwesomeProject) and follow all the instructions, setup, and see if its still the same. Im also following this [guide](https://www.youtube.com/watch?v=TQmudJLhPx8&feature=youtu.be)

**Comment by jeveloper** [comment]
Hey, firebase lib also contains local notifications , either way. 1 - yes , 2 - RN documentation has this info for objective C code you need in your appdelegate 

based on your error, it seems that xcode project isn't picking up your linked library.

**Comment by mcaranay** [comment]
It seems that way even though i already did the linking, as if the file/library is not existing. I do notice **libRCTPushNotification.a** is tagged RED(file does not exist?) by xcode. Tried searching file on finder and nowhere to be found. I thought clean and rebuild will regenerate it but still RED. Any idea if thats the cause? 

Will try firebase also. Thanks

**Comment by jeveloper** [comment]
That libRCT should be in node_modules unless something changed in RN which i doubt.
It seems that you need to check search paths.

**Comment by SerotoninaAbad** [comment]
I had the same error just now. My problem was that when I dragged the libRCTPushNotification.a, I wasn't selecting the right TARGET. I dragged into 'nameoftheapp'Tests instead to the target 'nameoftheapp'. I hope it helps.
