### ISSUE TITLE
The app is not opening on clicking the notification in the status bar

### ISSUE THREAD

**Issue by muhsin-k** [zo0r/react-native-push-notification#870]
I am able to get the remote notification in the status bar. But when I click on this notification, the app is not opening  [Here app is in the closed state]

**pushService.js**
```
import PushNotification from 'react-native-push-notification';
export default function() {
  PushNotification.configure({
    // (optional) Called when Token is generated (iOS and Android)
    onRegister(regToken) {
      console.log('TOKEN-->', regToken);
    },
    onNotification(notification) {
    },
    checkPermissions(result) {
    },
    popInitialNotification: true,
    requestPermissions: true,
  });
}
```
**AndroidManifest.xml**
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.app_id">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>


    <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:allowBackup="false" android:theme="@style/AppTheme">
        <activity android:name=".MainActivity" android:launchMode="singleTop" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize" android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />


        <receiver android:name="com.google.android.gms.gcm.GcmReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService" android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>

     </application>

    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />

    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>

</manifest>

```
**Version**
```

{
    "react": "16.4.1",
    "react-native": "^0.55.4",
    "react-native-push-notification": "^3.1.1",
}
```

**Comment by EJohnF** [comment]
@muhzi4u @illestrater did you found a solution for this problem? I experience the same problem

**Comment by muhzi4u** [comment]
@EJohnF Yes. I noted down the fix somewhere. I need to check the code. I will let you know

**Comment by EmpireJones** [comment]
@muhzi4u @EJohnF  Either of you have details on resolving this?

**Comment by EJohnF** [comment]
Hi @EmpireJones 
yea,  I solved it somehow... But absolutly don't remember how :-(

I suspect it was something related to manifest. Mine is 
`
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
                  android:value="Messages"/>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                  android:value="Notification about new messages in feeds, group and private channels"/>
      
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                  android:resource="@android:color/white"/>
      <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
               android:exported="false" >
          <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT" />
          </intent-filter>
      </service>`

now. 


And also don't forget that in order to process push notification when app is killed - you need to have `PushNotification.configure({` outside of any components definition (on top-level)

**Comment by priyak-sdei** [comment]
Getting the same error. Any solution yet.
