### ISSUE TITLE
Unable to Resolve Module

### ISSUE THREAD

**Issue by cyb3rsalih** [zo0r/react-native-push-notification#871]
I installed the Component  and link it , after make configurations I run the app on Android and getting this error.

>  Module `react-native-push-natification` does not exist in the Haste module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`."

I tried the solutions mentioned in error log. But There is nothing to change.

Did you face this problem? How to fix it?

**Comment by thc0309** [comment]
react-native-push-notification not react-native-push-natification

**Comment by shehan1995** [comment]
Use yarn add 'module name' instead of npm install.
This worked for me 
yarn add react-native-push-notification

**Comment by aakrandan** [comment]
> yarn add react-native-push-notification

Thank you, this helped.
