### ISSUE TITLE
unsubscribeFromTopic on Android?

### ISSUE THREAD

**Issue by omaksi** [zo0r/react-native-push-notification#872]
Hello, I'm curious if there's any way to unsubscribe from a notification topic on Android.

I need to unsubscribe from one topic and subscribe to another when the user moves to a different part of the app.

**Comment by experionarjun** [comment]
Currently it is not implemented. I have raised a PR #917 for this.

**Comment by omaksi** [comment]
Just FYI I ended up using https://github.com/invertase/react-native-firebase
Topics work great on both iOS and Android
