### ISSUE TITLE
onNotification getting called before tapping notification

### ISSUE THREAD

**Issue by bhushansethi** [zo0r/react-native-push-notification#873]
For remote push notifications: onNotification is getting called as soon as notification receives before even user taps notification. 
For local notifications: It doesn't call onNotification even after tapping it.
I am using index.js referring to app.ios.ts and app.android.ts.
I have tried adding PushNotification.configure in index.js and app.android.ts to keep it out of react native lifecycle but same result. 
Also, I am using react-native-navigation library in app.android.ts and that might be conflicting with it.
Anybody facing same issue?

**Comment by colaskirschoff** [comment]
Same here, I'm using `localNotificationSchedule` and when I receive it `onNotification` does not trigger, not even when I tap it. Any idea why ?

**Comment by colaskirschoff** [comment]
Same here, I'm using localNotificationSchedule and when I receive it onNotification does not trigger, not even when I tap it. Any idea why ?

**Comment by colaskirschoff** [comment]
@bhushansethi I guess you added the `#import <React/RCTPushNotificationManager.h>` to your `AppDelegate.m` otherwise the remote notifications wouldn't trigger anything but maybe you forgot this part ?  

```
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
{
  [RCTPushNotificationManager didReceiveLocalNotification:notification];
}
```
