### ISSUE TITLE
App boots when notification is received

### ISSUE THREAD

**Issue by ChrisEdson** [zo0r/react-native-push-notification#874]
Hello -

We're having an issue where our App is booting when a notification is received on Android.

We understand this is probably because we're using the 'data' field on the payload from our server - and that's causing `onMessageReceived` to fire - causing our entire app to boot up.

But that's not ideal or intended - it's causing lots of unintended behaviour, because our navigation then doesn't work when the user opens the app after it's booted from the notification.

**Comment by matthieu-brillaxis** [comment]
I think this issue can help you.
https://github.com/zo0r/react-native-push-notification/issues/470
