### ISSUE TITLE
IOS 12 no remote push notifications [clarification]

### ISSUE THREAD

**Issue by djleonskennedy** [zo0r/react-native-push-notification#880]
Hello Sorry for the issue, i cannot find any info.

Could you clarify about push notifications on **IOS 12**, 
after update cannot receive remote notifications

Thank you

**Comment by mlbz198** [comment]
Me too, Hope for help

**Comment by djleonskennedy** [comment]
Hello

**We've fixed** this issue on backend, apple has new format now

`{
	"aps":
	{
		"alert":
		{
			"title": "Title push",
			"body": "Body push"
		},
		"sound":"default",
		"category":"Notification",
		"key":"role.Administrator",
		"id":0,
		"badge":0
	}
}`

I'll live this issue opened for further investigation
