### ISSUE TITLE
Push notifications and routing

### ISSUE THREAD

**Issue by flashkiller58rus** [zo0r/react-native-push-notification#885]
Hi!

I use react-native-push-notification this way:

**index.js**

`const isPushEnabled = async () => {
    if(Platform.OS === 'ios') {
        const permissions = await new Promise((resolve) => {
            PushNotificationIOS.checkPermissions(resolve)
        })

        return Boolean(permissions.alert)
    }

    return Promise.resolve(true)
}

const onRegister = async ({ token }) => {
    console.warn(`PUSH TOKEN:\n ${token}`)

    const is_push_enabled = await isPushEnabled() // eslint-disable-line camelcase

    try {
        await api('POST', '/devices', {}, {
            device: {
                platform: Platform.OS,
                name: getDeviceModelSync(),
                is_push_enabled,
                token,
            },
        })
    } catch (e) {
        console.warn('Can\'t POST push-notification token to API:', e)
    }
}

if(Platform.OS === 'ios') {
    PushNotificationIOS.addEventListener('registrationError', async (error) => {
        console.warn('PushNotification registration error: ', error)

        try {
            // On simulators `registrationError` called each time when permissions requested
            const pushRegisterHadFailed = await AsyncStorage.getItem('pushRegisterHadFailed').catch(() => null)
            if(!pushRegisterHadFailed) {
                await api('POST', '/devices', {}, {
                    device: {
                        platform: Platform.OS,
                        name: getDeviceModelSync(),
                        is_push_enabled: false,
                    },
                })

                await AsyncStorage.setItem('pushRegisterHadFailed', 'true')
            }
        } catch (e) {
            console.warn('Can\'t POST device info to API:', e)
        }
    })
}

const appStateListener = (state) => {
    if (state === 'active') {
      AppState.removeEventListener('change', appStateListener);
      PushNotification.popInitialNotification(notification => notification && onNotification(notification));
      console.log('Here we are!');
    }
};

export default class app extends React.Component {
    

    handleNotification(notification)
	{
        console.log('handleNotification');
	}

    componentDidMount() {
      
        AppState.addEventListener('change', appStateListener);

        var that = this;
        PushNotification.configure({
            onRegister,
            onNotification(notification) {
				console.log('onNotification')
				console.log( notification );

				that.handleNotification(notification);
			},
            senderID: '183710680608',
            permissions: {
                alert: true,
                badge: true,
                sound: true,
            },
            popInitialNotification: true,
            requestPermissions: false,
        })
    }

    render() {
        const initialRouteStack = []

        let initialRoute = { name: accountStore.onboardingViewed ? 'authPhone' : 'onboarding' }

        if(authStore.token) {
            if(accountStore.isParent) {
                initialRoute = { name: 'children' }
            } else {
                initialRoute = { name: 'home' }
            }
        } else if(authStore.loginPhone) {
            // Push authPhone scene in histiry as previous one
            initialRouteStack.push({ name: 'authPhone' })
            initialRoute = { name: 'authCode' }
        }

        initialRouteStack.push(initialRoute)

        return (
            <View style={{ flex: 1 }}>
                <StatusBar barStyle="light-content" />
                {
                    this.state.initialized ? (
                        <Provider
                            account={accountStore}
                            auth={authStore}
                            news={newsStore}
                            lessons={lessonsStore}
                            payment={paymentStore}
                            pushes={pushStore}
                            initializeStores={initializeStores}
                        >
                            <Router
                                initialRoute={initialRoute}
                                initialRouteStack={initialRouteStack} />
                        </Provider>
                    ) : (
                            null
                    )
                }
            </View>
        )
    }
}`

**router.js**

 `export default class Router extends React.Component {
    state = {
        activityLoading: false,
    }
    _navigator = null
    _routeHandler = null

    activityLoading = {
        show: () => {
            this.setState({
                activityLoading: true,
            })
        },
        abort: () => new Promise((resolve) => {
            this.setState({
                activityLoading: false,
                // Workaround due Modal and Alert dead-locks
                // https://github.com/facebook/react-native/issues/10471
            }, () => {
                if(Platform.OS === 'ios') {
                    setTimeout(resolve, 1200)
                } else {
                    resolve()
                }
            })
        }),
        replaceWith: (route, force) => new Promise((resolve) => {
            const method = force ? 'resetTo' : 'push'

            this.setState(
                { activityLoading: false },
                // Delay route transition until modal are closing
                () => setTimeout(() => {
                    this._navigator[method](route)
                    resolve()
                }, 400),
            )
        }),
    }

    renderScene = (route, navigator) => {
        const { name, ...routeParams } = route,
            RouteHandler = routes[name]

        return (
            <AppBackground>
                <RouteHandler
                    ref={routeHandler => navigator._routeHandler = routeHandler}
                    navigator={navigator}
                    activityLoading={this.activityLoading}
                    {...this.props}
                    {...routeParams} />
            </AppBackground>
        )
    }

    configureScene(route) {
        const { configureScene } = routes[route.name].navbar || {}

        if(configureScene) {
            return configureScene(route) || Navigator.SceneConfigs.PushFromRight
        }
        return Navigator.SceneConfigs.PushFromRight
    }

    render() {
        const {
            initialRoute = { name: 'authPhone' },
            initialRouteStack = null,
        } = this.props

        console.log(showPushesScreen);

        return (
            <View style={{ flex: 1 }}>
                <Modal
                    animationType="fade"
                    transparent
                    visible={this.state.activityLoading}
                    onRequestClose={() => {}}
                >
                    <AppBackground style={{ opacity: 0.7 }} />
                    <ActivityLoadingScreen />
                </Modal>
                <Navigator
                    ref={navigator => this._navigator = navigator}
                    style={{ flex: 1 }}
                    initialRoute={initialRoute}
                    initialRouteStack={initialRouteStack}
                    renderScene={this.renderScene}
                    configureScene={this.configureScene}
                    navigationBar={
                        <Navbar />
                    } />
            </View>
        )
    }
}`

Any suggestions on how I can access navigator in the index.js "handleNotification" method?

PS I need to route user to the some screen when push notification pressed?

PPS Maybe i'm in a wrong direction? Any advice are welcome!

**Comment by OtacilioN** [comment]
Hey, I am using the [Navigating without the navigation prop](https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html) to do this.
