### ISSUE TITLE
no way to get delivered notifications on Android

### ISSUE THREAD

**Issue by naveenkonduru** [zo0r/react-native-push-notification#887]
There is no documentation found anywhere about how to get delivered notifications on android. Can anyone please post any references.

**Comment by DarkXelus** [comment]
+1

**Comment by dolphinflow86** [comment]
+1

**Comment by qsdamar** [comment]
+1

**Comment by saranya20-t** [comment]
I'm still struggling to get the delivered notifications on android, anyone who found a way please guide me in this. When I use getDeliveredNotifications() method, the userInfo/data is missing. So, I can't find which notification to be removed based on the data.
