### ISSUE TITLE
unfortunately myapp has stopped

### ISSUE THREAD

**Issue by SaeedArshinchiBonab** [zo0r/react-native-push-notification#888]
Hello
When adding push notifications to the program, the program with unfortunately myapp has stopped Encountered
Can you look at the app's photos? 
http://uupload.ir/files/z5ls_screenshot_1538479398.png
http://uupload.ir/files/862w_1.jpg
http://uupload.ir/files/7dab_2.jpg
http://uupload.ir/files/0lc7_3.jpg
http://uupload.ir/files/r7ns_4.jpg

**Comment by tarikchakur** [comment]
Same Issue.  App crashes on startup after installing react-native-push-notification@3.1.1
Using react-native@0.55.4.
Thanks in advance

**Comment by linux08** [comment]
I had a similar issue, 
https://github.com/linux08/react-native-map-push-notification/blob/master/android/build.gradle 
Check my configuration there i believe that will solve the problem

**Comment by wasd171** [comment]
Same with `react-native@0.57.2` and `react-native-push-notification@3.1.1` on Android

**Comment by shoaibehmed** [comment]
I had the same issue with version 3.1.1

Fixed with 
`ext {
    googlePlayServicesVersion = "+"
}`

in `android/build.gradle` .

**Comment by Kamill90** [comment]
What if I don't use googlePlayService ? I need local notification only and I have the same issue only after installing the library. Android only. Ios works fine
