### ISSUE TITLE
add RNPushNotificationPublisher as receiver in AndroidManifest.xml not mentioned in the documentation

### ISSUE THREAD

**Issue by joseNetdevices** [zo0r/react-native-push-notification#89]
Hello,

I didn't understand why schedule notification didn't work although immediate notifications did.
It worked after adding the following line the my application manifest 
`<receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />`

**Comment by zo0r** [comment]
Thanks https://github.com/zo0r/react-native-push-notification/commit/3decf675ba1d7ddc02fb4bb4c069b54e7295b43e
