### ISSUE TITLE
Cannot get Notification content if app is in background

### ISSUE THREAD

**Issue by fernandomatheus** [zo0r/react-native-push-notification#890]
I can recevie the notification from firebase remotly. If the app is runing in foreground, 
I receive the notification content normally, but if the app is in background, I receive the notification and when click on notification, the app opens up, but the method: `onNotification` is not called for some reason. I have seen a lot of issues based on this problem, but no success.

here is my AndroidManifest.xml

`<application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/icon"
      android:allowBackup="false"
      android:theme="@style/AppTheme">

        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@mipmap/icon"/>

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>

      <activity
        android:name=".SplashActivity"
        android:label="@string/app_name">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>

      <activity
        android:name=".MainActivity"
        android:theme="@style/SplashTheme"
        android:label="@string/app_name"
        android:launchMode="singleTop"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>`

and here is my App.js
```JavaScript

import PushNotification from 'react-native-push-notification';

    class App extends Component {
      state = { color: 'red' };
      constructor() {
        super();
        PushNotification.configure({
          onRegister: ({ token }) => this.register(token),
          onNotification: notif => this.receivePushNotification(notif),
          senderID: 'XXXX',
          requestPermissions: true
        });
     }

        componentDidMount = () => {
          SplashScreen.hide();
          AppState.addEventListener('change', this.handleAppStateChange);
        };

        handleAppStateChange = appState => {
          if (appState === 'active') {
            PushNotification.popInitialNotification(notification => {
              console.warn('notification', notification); //notification is null
            });
          }
        };

        register = token => {
          console.warn('token', token);
        };

        receivePushNotification = notification => {
          console.warn('notification', notification); //only enter here if I receive the notification in foreground mode, if I receive in background and click on notification, this method is not being called
        };
    }

```

If anybody knows how to solve this, or know if FCM is supported by this library I would greatly appreciate it.

**Comment by fernandomatheus** [comment]
If anybody is using SplashActivity as a launcher to display a SplashScreen while app loading like me, maybe removing these lines from `<activity android:name=".SplashActivity" ...>`:

```
<intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
```

and put them on MainActivity: 
```
<activity
    android:name=".MainActivity" ...>
<intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
</activity>
```

It worked for me, I hope this could help someone who is facing this same problem.

**Comment by hoangpm2** [comment]
Hi @fernandomatheus , I got the same issue, but i dont know how to solve. Can you explain for me how to fix using react-native-splash-screen or do you have any other solutions ? 
Thank you so much.

**Comment by fernandomatheus** [comment]
Hi @hoangpm2 

Try to edit your `AndroidManifest.xml`

similar to this:
```
<application android:name=".MainApplication" ... />
<activity
        android:name=".SplashActivity"
        android:label="@string/app_name"
        android:launchMode="singleTop"
        android:theme="@style/SplashTheme">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:launchMode="singleTop"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>
```
 `SplashActivity.java`, add this method:

 ```
@Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Intent fcmIntent = this.getIntent();
        Bundle bundle = fcmIntent.getExtras();

        Intent intent = new Intent(this, MainActivity.class);
        intent.putExtras(fcmIntent);
        startActivity(intent);
        finish();
    }
```

and make sure that you have all `<service>` mentioned on documentation.

this changes worked for me!

**Comment by hoangpm2** [comment]
Thank you @fernandomatheus .
I tried your solution but it did not work for me.
After 3 days finding solutions but not work, i decided to use another library and it worked. ;)

**Comment by uzairkhan01** [comment]
I am also facing same issue.
@hoangpm2 which library are you using now react-native-fcm ?

**Comment by hoangpm2** [comment]
@uzairkhan01  I am using react-native-firebase.
[https://rnfirebase.io/](url)

**Comment by uzairkhan01** [comment]
Thank you @hoangpm2
