### ISSUE TITLE
Use LocalNotifications as Remote

### ISSUE THREAD

**Issue by losheredos** [zo0r/react-native-push-notification#892]
I have implemented the package successfuly (I guess), but I find remote notifications compilcated and dont want to do it. So I just thought that I can pop notifications after fetches if a selected event happens, I tried with this logic and it works fine.

My question, I want my app to fetch in background even when app is closed ( I try it now with react-native-background-task ) . Do you think it would work? or for my way would you suggest me some other way?

**Comment by Gp2mv3** [comment]
No it wont and if it does, you'll drain the user's battery.
Juste have a look at packages that do remote notifications for you. For example, we use `node-gcm` which handles everything for you.

**Comment by Gp2mv3** [comment]
@therise3107 Indeed, it's also possible. There are tons of solutions to do the same. :wink:

**Comment by therise3107** [comment]
@losheredos I have checked their documentation, it looks promising and their documentation is easy to follow but I have been using firebase and I prefer to use tightly coupled architecture for integrated services.

**Comment by peacechen** [comment]
@losheredos  You haven't explained your specific use case, but it sounds like you don't really need push notifications, just local notifications.  If you need to periodically fetch something from the server even if the app is in the background, try [react-native-background-timer](https://github.com/ocetnik/react-native-background-timer)

**Comment by ParthSolanki7** [comment]
> No it wont and if it does, you'll drain the user's battery.
> Juste have a look at packages that do remote notifications for you. For example, we use `node-gcm` which handles everything for you.

what for react native ?

**Comment by ParthSolanki7** [comment]
> @therise3107 Indeed, it's also possible. There are tons of solutions to do the same. 😉

can you please provide the references or solution
