### ISSUE TITLE
Conflict zo0r/react-native-push-notification and @aws-amplify/pushnotification

### ISSUE THREAD

**Issue by ththugues44** [zo0r/react-native-push-notification#893]
Hello

I do not know how to do it because I have a conflict of package namely:
i am using @aws-amplify/pushnotification for remote push notifications and i want to use zo0r / react-native-push-notification for local notifications and badge. Here is the problem :

in the MainApllication.java file for the @ aws-amplify / pushnotification package we need to include importing this import com.amazonaws.amplify.pushnotification.RNPushNotificationPackage and add new RNPushNotificationPackage (). for the zo0r / react-native-push-notification package we need to import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage and add ReactNativePushNotificationPackage.

I have an error NATIVE model RNPushNotification tried to override RNPushNotificationModule for Mofule name RNPushNotification if this was your intention, set canOverrideExistingModule = true. (See photos ) => http://www.noelshack.com/2018-41-1-1539003383-conflict-package.jpeg

i think there is a conflict between @ aws-amplify / pushnotification and zo0r / react-native-push-notification, please how do I resolve this conflict because i need local notifications and badges for my application?

Source Code File File MainApllication.java
` package com.katika;
import android.app.Application;
import com.facebook.react.ReactApplication;
import com.oblador.vectoricons.VectorIconsPackage;
import com.android.freshchatSdk.FreshChatReactPackage;
import com.amazonaws.amplify.pushnotification.RNPushNotificationPackage;
import com.robinpowered.react.Intercom.IntercomPackage;
import io.intercom.android.sdk.Intercom;
import com.masteratul.RNAppstoreVersionCheckerPackage;
import io.xogus.reactnative.versioncheck.RNVersionCheckPackage;
import com.microsoft.codepush.react.CodePush;
import io.invertase.firebase.RNFirebasePackage;
import com.ocetnik.timer.BackgroundTimerPackage;
import io.underscope.react.fbak.RNAccountKitPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import io.underscope.react.fbak.RNAccountKitPackage;
import io.invertase.firebase.analytics.RNFirebaseAnalyticsPackage;
import io.invertase.firebase.notifications.RNFirebaseNotificationsPackage;
import io.invertase.firebase.functions.RNFirebaseFunctionsPackage;
import io.invertase.firebase.messaging.RNFirebaseMessagingPackage;
import io.invertase.firebase.fabric.crashlytics.RNFirebaseCrashlyticsPackage; // <-- Add this line
import io.invertase.firebase.crash.RNFirebaseCrashPackage; // <-- Add this line
import io.invertase.firebase.firestore.RNFirebaseFirestorePackage; // <-- Add this lin.util.Arrays;e
import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage ;  // <--- Import Package

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

        @Override
        protected String getJSBundleFile() {
        return CodePush.getJSBundleFile();
        }

    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new VectorIconsPackage(),
            new FreshChatReactPackage(),
            new RNPushNotificationPackage(),
            new IntercomPackage(),
            new RNAppstoreVersionCheckerPackage(),
            new RNVersionCheckPackage(),
            new CodePush("bySq16a9P0d2pIdf9ZZvyaRJbzcOSJ8Sg7bHX", getApplicationContext(), BuildConfig.DEBUG),
            new RNFirebasePackage(),
            new BackgroundTimerPackage(),
            new RNAccountKitPackage(),
            new RNFirebaseAnalyticsPackage(),
            new RNFirebaseNotificationsPackage(),
            new RNFirebaseFunctionsPackage(),
            new RNFirebaseMessagingPackage(),
            new RNFirebaseCrashlyticsPackage(),
            new RNFirebaseFirestorePackage(),
            new RNFirebaseCrashPackage(),
            new ReactNativePushNotificationPackage () // <-- Add this line
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    Intercom.initialize(this, "android_sdk-83be2abcbbe01abc199897d691de1c8b47f703d3", "tduveiqw");
  }

}
`

**Comment by bernhardt1** [comment]
hey @noellaby did you manage to resolve this?

I'm in the same situation. I want to use aws-amplify push notifications for the remote sending of notifications along with the react-native-push-notification package for displaying local notifications and badges.

I'm thinking this is a very difficult issue and likely not worth solving since these two packages conflict with each other in so many ways.

How did you proceed?

**Comment by GremeAllanBryce** [comment]
I too have the same issue

**Comment by Kamill90** [comment]
Any solution here? I have same issue with react native 0.60

**Comment by bneigher** [comment]
+1

**Comment by FortisFortuna** [comment]
+1

**Comment by FortisFortuna** [comment]
I ended up using 
https://github.com/wix/react-native-notifications
for the local notifications portion and it worked nearly out of the box

**Comment by rjuevesano** [comment]
Encountered the same issue. 

> I ended up using
> `Notifications.postLocalNotification({ ... })` in
> https://github.com/wix/react-native-notifications
> after aws-amplify recieved the remote.

I tried that but the scheduling won't work on android.

**Comment by Dallas62** [comment]
https://stackoverflow.com/questions/29273362/java-package-import-alias/29273414

**Comment by Dallas62** [comment]
You can also use the full namespace to avoid import.

**Comment by rjuevesano** [comment]
> You can also use the full namespace to avoid import.

Can you give an example on how to do that?

**Comment by Dallas62** [comment]
Oh ! I saw the issue, it's not a Java issue, it's in the package naming. I will look into it.

**Comment by usmansbk** [comment]
Ended up using `react-native-onesignal` for remote notifications
