### ISSUE TITLE
3.2.0  || 3.1.2 Release

### ISSUE THREAD

**Issue by CapitanRedBeard** [zo0r/react-native-push-notification#899]
@zo0r @Gp2mv3 We've had 45 wonderful commits since the tagged 3.1.1. Several large bugfixes and issues completed. Should be about time to cut a new release. 
Not sure how the release system works on this repo, but any instructions on how to get a new release out the door? 

I can curate a changelog with to inform the masses if you'd like.

Thanks for maintaining this repo, let me know how I can help

**Comment by wregis** [comment]
Agreed, I am now facing some crashes relared to `requestPermissions` method that seens to be fixed already on master (I am yet to check if it is fixed fo me), plus the notification sound is always the default and also seens to be fixed.

**Comment by martinzangl-santexgroup** [comment]
any news @Gp2mv3 about a new release?
Thanks, man!

**Comment by Gp2mv3** [comment]
Indeed, Can you create a PR for Changelog ? I'll ask for a npm release to @zo0r.

**Comment by CapitanRedBeard** [comment]
@Gp2mv3 	Appreciate it man, you can find the updates to [CHANGELOG.md here](https://github.com/zo0r/react-native-push-notification/pull/906)

**Comment by CapitanRedBeard** [comment]
Closing since version 3.1.2 is cut.

Thanks @Gp2mv3 for the support!
