### ISSUE TITLE
Separate between on recieve and on click

### ISSUE THREAD

**Issue by avishayil** [zo0r/react-native-push-notification#9]
Is there any way to separate events between receiving notification and clicking on the notification?

**Comment by brianjd** [comment]
If I understand the question correctly - aren't you able to inspect the value of 'foreground' in the notification?

**Comment by avishayil** [comment]
Hi,
Yes I am able to log the value. few problems for my usecase:
Usecase: when a notification appears I want to achieve to things:
1) On receive - check the data of the notification and validate it, then decide if to display it to the user.
2) On click - perform a custom action based on the notification data (I.E, navigate to a specific article page using navigator).

Problems:
1) When a notification appears while the app is running, the action is being performed regardless if the user clicked on the notification or haven’t.
2) When attempting to send a local notification, I can’t figure when the user clicked on the notification or received it. Because the onNotification both listens to receive / click, It would create endless loop and every time I’ll press the notification - new notification would arrive.

    onNotification: function(notification) {
        console.log( 'NOTIFICATION:', notification );
        PushNotification.localNotification({
            /* Android Only Properties */
            // id: 0, // (optional) default: Autogenerated Unique ID
            title: notification.title, // (optional)
            ticker: "My Notification Ticker", // (optional)
            largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
            smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"

            /* iOS and Android properties */
            message: notification.message // (required)
        });
				// setTimeout(() => {
				// 	_navigator.to('main.post', notification.message, {
				// 		article: {
				// 			title: notification.message,
				// 			link: JSON.parse(notification.data).url,
				// 		}
				// 	});
				// } ,500);
    },


-- 
Avishay Bassa
Sent with Airmail

On January 17, 2016 at 2:45:23 AM, b_d (notifications@github.com) wrote:

If I understand the question correctly - aren't you able to inspect the value of 'foreground' in the notification?

**Comment by pewh** [comment]
Hi,

I was able to receive notification and got `Object {foreground: false, message: "hello world", collapse_key: "do_not_collapse"}`. But when I click notification, I got same value  `Object {foreground: false, message: "hello world", collapse_key: "do_not_collapse"}`.

From the documentation said `onNotification` is called when a remote or local notification is opened or received. So is there any method to distinguish between received and opened?

**Comment by ch0992** [comment]
i have same problem too. how can i seperate when receive and onClick. Always same AppState & foregroud value. i want when click the notification then move to url of notification messages.

**Comment by xphaul** [comment]
@ch0992  did you managed to solve your problem?

**Comment by frangeris** [comment]
Now you can, `userInteraction` in **2.0.1** [#122 (comment)](https://github.com/zo0r/react-native-push-notification/issues/122#issuecomment-233709484)

**Comment by IronTony** [comment]
Hi, and sorry for the silly question, but how can I `userInteraction` to redirect user to a specific page in app (maybe using router flux)? Or also in general, how can I use `userInteraction`?

**Comment by Yara-the-devil-princess** [comment]
how can I userInteraction to redirect user to a specific page in app (maybe using router flux)? Or also in general, how can I use userInteraction?

**Comment by crzycoder** [comment]
@frangeris can you guide us how to navigate to specific screen by clicking notification in background state..
Thanks
