### ISSUE TITLE
show notifications count

### ISSUE THREAD

**Issue by SoftBrain001** [zo0r/react-native-push-notification#90]
hi
how can i show notifications count on android ? i already added  
permissions: {
          alert: true,
          badge: true,
          sound: true
      },
but it seems that it doesnt work on android

**Comment by npomfret** [comment]
I don't think badges are supported on android.

**Comment by sorenburon** [comment]
True, there is no standard API for doing this in Android. Samsung achieves it through their TouchWiz. Others do it by using widgets or custom launchers.

**Comment by az-iB** [comment]
is there a way to add the ShortcutBadger?

**Comment by kfiroo** [comment]
@SoftBrain001 @npomfret @sorenburon @az-iB Created a PR for this using ShortcutBadger, check it out :)
https://github.com/zo0r/react-native-push-notification/pull/168

**Comment by npomfret** [comment]
In iOS i think the badge number is set using the _number_ field (rather than an explicit _badge_ field).  It would be good to have them behave the same.

**Comment by kfiroo** [comment]
According to apple `badge` is the right field to use
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html

**Comment by npomfret** [comment]
@SoftBrain001 do you still have this issue? if so, have you tried the latest release? if not, can we close it?

**Comment by npomfret** [comment]
Closing due to lack of response.

**Comment by AndreyPatseiko** [comment]
Automatic badges counter not working in RN 0.59.9 and "react-native-push-notification": "^3.1.3". 
If I send badge counter manually from firebase cloud message all work fine, but if I don't send it  badge don't show even if send couple push messages.
