### ISSUE TITLE
Why the data is not contained at bundle on android?

### ISSUE THREAD

**Issue by MarkRunWu** [zo0r/react-native-push-notification#901]
Document has:
```
{
    foreground: false, // BOOLEAN: If the notification was received in foreground or not
    userInteraction: false, // BOOLEAN: If the notification was opened by the user from the notification area or not
    message: 'My Notification Message', // STRING: The notification message
    data: {}, // OBJECT: The push data
}
```
But just realize the `data` is never existed when running on android.

**Comment by MarkRunWu** [comment]
Due to android [push notification format](https://developers.google.com/cloud-messaging/http-server-ref#notification-payload-support), the node `data` is flatten into `notification` bundle.

Do you have any plan to modify the existing notification format into the one on iOS ?

On Android
```
{
  'title': 'title',
  'data_field_1': 'test' 
}
```
into
```
{
  'title': 'title',
  'data': {
    'data_field_1': 'test' 
  } 
}
```

**Comment by RomanAbramenko** [comment]
I'm also have the same problem
