### ISSUE TITLE
Push notification not showing in foreground 

### ISSUE THREAD

**Issue by arshidkv12** [zo0r/react-native-push-notification#908]
Push notifications are working, if the app in the closed state. But not working, if the app is in the foreground. 
I am using FCM.

**Comment by timbielawski** [comment]
Hi,

I was experiencing the same issue then noticed a difference in the AndroidManifest.xml config.
This fixed it for me


 <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerServiceGcm"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>

**Comment by HarshitMadhav** [comment]
@timbielawski this is for gcm But what to do if I want fcm foreground push notification.

**Comment by zashishz** [comment]
This worked for me:
I updated my AndroidManifest.xml with instructions shown on this page.
[https://rnfirebase.io/docs/v4.2.x/messaging/android](https://rnfirebase.io/docs/v4.2.x/messaging/android)

**Comment by akshgods** [comment]
> This worked for me:
> I updated my AndroidManifest.xml with instructions shown on this page.
> https://rnfirebase.io/docs/v4.2.x/messaging/android

@zashishz  can you explain what you change or can you add androidManifest.xml file here

**Comment by zashishz** [comment]
> > This worked for me:
> > I updated my AndroidManifest.xml with instructions shown on this page.
> > https://rnfirebase.io/docs/v4.2.x/messaging/android
> 
> @zashishz can you explain what you change or can you add androidManifest.xml file here

@akshgods I made these changes as mentioned in link for AndroidManifest.xml.

```xml
<application ...>
  <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
    <intent-filter>
      <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
  </service>
  <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
    <intent-filter>
      <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
    </intent-filter>
  </service>
</application>
```

**Comment by TaraSinghDanu** [comment]
<meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
            android:value="true"/>.

**Comment by AhmedRazaVerge** [comment]
@TaraSinghDanu 
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground" android:value="true" />
i change according to doc but it does not work

`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.pushnotification_test1">

  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.WAKE_LOCK" />
  <uses-permission android:name="android.permission.VIBRATE" />
  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme">
    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />


    
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground" android:value="true" />
    
    <meta-data android:name="com.dieam.reactnativepushnotification.notification_color" android:resource="@color/white" /> 

    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
    <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
      <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
        <action android:name="android.intent.action.QUICKBOOT_POWERON" />
        <action android:name="com.htc.intent.action.QUICKBOOT_POWERON" />
      </intent-filter>
    </receiver>

    <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService" android:exported="false">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>
  </application>

</manifest>
`

**Comment by AhmedRazaVerge** [comment]
<meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground" android:value="true" />

make value true if false and use version 5.1.1.
i have same issue in version 6. version 5.1.1 hava all kinds of notifications

**Comment by Dallas62** [comment]
Hi @AhmedRazaVerge 
Do not ask for rollback versions. The v6 have breaking changes describe in the CHANGELOG and RELEASE NOTE.
Please read documentation before asking rollback.

**Comment by AhmedRazaVerge** [comment]
Dear @Dallas62 
i was using the v6.

<meta-data android:name="com.dieam.reactnativepushnotification.notification_foreground" android:value="true" />
i make changes according to the documentation to get notification pop in foreground but i did not get pop of notification.i just get the notification object.
so i try version 5.1.1 because i am using the this version in another project it works fine.
when i downgrade from v6 to 5.1.1 in current project i work.i get the notification popup.

**Comment by Dallas62** [comment]
Hi @AhmedRazaVerge 
If you take a look in the last ten issues you will get an answer to this issue.
Regards

**Comment by Dallas62** [comment]
https://github.com/zo0r/react-native-push-notification/issues/1671
