### ISSUE TITLE
Include "Every" atribute

### ISSUE THREAD

**Issue by ammichael** [zo0r/react-native-push-notification#91]
Hello!

I'm coming from Cordova development, which has [this](https://github.com/katzer/cordova-plugin-local-notifications) awesome plugin for local notification, where you can do this:

> cordova.plugins.notification.local.schedule({
>     id: 1,
>     title: "Production Jour fixe",
>     text: "Duration 1h",
>     firstAt: monday_9_am,
>     every: "week",
>     sound: "file://sounds/reminder.mp3",
>     icon: "http://icons.com/?cal_id=1",
>     data: { meetingId:"123#fg8" }
> });

Right now if I want to schedule a notification to repeat every day, I would use a for. Not sure if it's the best way, but it would work fine. But it would be really, really cool if this were simpler to do, like in Cordova's version.

**Comment by skleest** [comment]
@ammichael, how are you using a 'for' to schedule a repeating local notification indefinitely?

**Comment by ammichael** [comment]
Actually I'm not scheduling indefinitely. I'm scheduling just the next three months, and whenever the user opens the app it checks the last schedule date, if it was 60 days or more, it reschedule the next 90 notifications.

```
for(var i = 1; i <= 90; i++){
	let quoteDate = new Date();
	quoteDate.setDate(quoteDate.getDate()+i);
	let p = QuotesService.getQuoteOfTheDay(quoteDate, true);
	p.then((quoteOfDay) => {
	      this.scheduleNotification(quoteDate, notifHour, quoteOfDay);
        })
}
```

**Comment by skleest** [comment]
Makes, sense thanks!
