### ISSUE TITLE
Can't getting notification data when the app is in killed

### ISSUE THREAD

**Issue by Tatvanish** [zo0r/react-native-push-notification#911]
"react-native": "0.55.2",
"react-native-push-notification": "3.0.2",

@zo0r 
When app in background/foreground notification working fine but when in killed state getting notification but not getting data/content in android only. in ios working fine.

**Comment by ydv0121** [comment]
how to get notification when app is in foreground??
only get remote notification when app is in background..
please help

**Comment by abbasashraf** [comment]
any solution ??

**Comment by fahadhaq** [comment]
anyone got a solution for this?

**Comment by shashinbhayani** [comment]
is there any solution for this ?
