### ISSUE TITLE
cancelLocalNotifications fails on parseInt 

### ISSUE THREAD

**Issue by jrounsav** [zo0r/react-native-push-notification#913]
I don't think this qualifies as an issue but I'm posting it here as a heads up for anyone else who might run into it, since I spent more time than I'd like to admit reviewing a coworkers code without realizing why a parseInt might fail.

Basically, my team was generating IDs for local notifications based on IDs coming from another data set concatenated with the day of the week. What we ended up with was a String similar to "2447483007"

RN Push Notification runs a parseInt on that value for the ID, however int max is "2147483647". Since our IDs were larger we were getting crashes on only some of our reminders.

Removing unnecessary concats(007 above) fixed this for us.

**Comment by likern** [comment]
This should solve problem
```
const getRandomInt = (min, max) => {
  var rand = min + Math.random() * (max + 1 - min);
  rand = Math.floor(rand);
  return rand;
};

const getRandomUInt32 = () => {
  const min = 0, max = 2147483647;
  return getRandomInt(min, max);
};
```
