### ISSUE TITLE
Move PushNotificationIOS from react-native to this repo?

### ISSUE THREAD

**Issue by matthargett** [zo0r/react-native-push-notification#914]
Hi @zo0r (and other maintainers) ! My name is Matt and I'm a React Native contributor. As part of the slimming down the React Native core, we are deprecating some built-in components and moving them out to community-managed packages. This allows those packages to iterate and release at a different cadence, maintain compatibility with a broader set of RN versions, and just generally provide a better developer experience.

We are looking to move PushNotificationIOS out of RN itself, and react-native-push-notification looks like it might be a good place to move it to. Would you and your maintainers be open to that?

If you are, we would move the relevant code into your repo in a PR that adds appropriate build and test scripts, put a runtime deprecation warning in the RN code, and then remove it from the RN core a few releases after the warning was added. We've already done the first couple of steps with WebView.

Looking forward to a good discussion, Thanks for reading!

**Comment by msluther** [comment]
As a new consumer of this library, I would love to see this happen and perhaps have it move onto the new UNNotification* APIs at the same time.

Thoughts @Gp2mv3 ?

**Comment by indexzero** [comment]
@matthargett heads up that @msluther and I are colleagues – our current plan is to take a pass at migrating `PushNotificationiOS` source from `react-native` into this repository with a PR expected in late December / early January. Migrating that native code to `UNNotification*` APIs may be part of that or a separate follow-up effort depending on how much time the team can carve out from product work.

Hopefully this catches your eye before then @zo0r / @Gp2mv3 –– if it does please also know we're happy to commit additional time to actually helping with day-to-day on-going maintenance as well. But if not keep an eye out for that PR 🎉
