### ISSUE TITLE
Remote push notifications

### ISSUE THREAD

**Issue by Blutude** [zo0r/react-native-push-notification#915]
The title says React native local and remote push notifications, but on the Read Me there is only a section on local push notifications. Can I get pointed to the right direction for dealing with remote push notifications?

I am planning on using Django channels because I am creating a chat for my app. I can probably use that to send remote push notifications, but when the app is completely closed, I don't think Django channels would help, am I right? Because on the client side, I need to have an open connection with the websocket and if the app is not open, then the websocket is not open.

So is there a way to deal with remote push notifications on react native? Do I have to do it directly on IOS and Android?

**Comment by Blutude** [comment]
Found this https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1

Maybe add that to the read me?

**Comment by kailashvele** [comment]
And for Android?
