### ISSUE TITLE
popInitialNotification() deprecated

### ISSUE THREAD

**Issue by iggyfisk** [zo0r/react-native-push-notification#92]
As of react-native v0.28.0-rc.0, `popInitialNotification()` in PushNotificationIOS is deprecated in favor of `getInitialNotification()` which means using this library throws a warning. Here's the react-native change facebook/react-native@1623e34c5135fc50d67272c30c123426d4b0036d

**Comment by zo0r** [comment]
**0.28.+** is in RC stage yet.

To avoid this warning use _(before `PushNotification.configure({...})`)_:
```javascript
console.ignoredYellowBox.push('PushNotificationIOS.popInitialNotification() is deprecated. Use getInitialNotification() instead.');
```

**Comment by bcalik** [comment]
I get error on v0.27.2.

<img width="342" alt="screen shot 2016-06-18 at 01 50 10" src="https://cloud.githubusercontent.com/assets/9222368/16166807/26200b0e-34f7-11e6-953c-f37bd30f48be.png">

**Comment by KBLNY** [comment]
@bcalik This module uses React Native's PushNotificationIOS for iOS devices.
Have you configured your iOS Project as followed:
```
Manually link the PushNotificationIOS library

Be sure to add the following to your Header Search Paths: $(SRCROOT)/../node_modules/react-native/Libraries/PushNotificationIOS
Set the search to recursive
Finally, to enable support for notification and register events you need to augment your AppDelegate.

At the top of your AppDelegate.m:

#import "RCTPushNotificationManager.h"
```
(cf. [https://facebook.github.io/react-native/docs/pushnotificationios.html](https://facebook.github.io/react-native/docs/pushnotificationios.html) for full reference)

In addition, please be sure that the `RCTPushNotification` has been added to your iOS Project's `Libraries`. If not, add it by right-clicking on `Libraries` folder, then `Add Files to <Your Project Name>...`. Finally, when the `RCTPushNotification` is added, select your project (in the XCode left panel), select `Target`, Click on the `General` tab and add `libRCTPushNotification.a` to the list of `Linked Frameworks and Libraries`.

Hope it works well now

**Comment by bcalik** [comment]
@KBLNY The error was from Android.

**Comment by zo0r** [comment]
@iggyfisk https://github.com/zo0r/react-native-push-notification/commit/2eafd1961273ca6a82ad4dd6514fbf1d1a829089
