### ISSUE TITLE
57.3 PushNotificationIOS.FetchResult.NoData incorrect configure

### ISSUE THREAD

**Issue by Djinne** [zo0r/react-native-push-notification#920]
Hi, since updating to 57.3, I get an error when I call finish. It says **UIBackgroundFetchResultNewData** should be **backgroundFetchResultNewData**
      `notification.finish(PushNotificationIOS.FetchResult.NewData);`

It seems like PushNotificationIOS.FetchResult.NewData has the incorrect config as when I use the following code it seems fine. 
      `notification.finish("backgroundFetchResultNewData");`

Maybe this is a change with IOS?

**Comment by amie-wilt** [comment]
I'm getting this as well. Has there been movement?

**Comment by mohammadsufyan** [comment]
I was having same error.
solved by using delegate method:
`- (void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler
 {
    [RNFIRMessaging willPresentNotification:notification withCompletionHandler:completionHandler];
 }

 #if defined(__IPHONE_11_0)
 - (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler
 {
     [RNFIRMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
   }
 #else
 - (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)())completionHandler
 {
     [RNFIRMessaging didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
   }
 #endif
`

**Comment by ddthuan87** [comment]
I was having same error. =((

`Invalid UIBackgroundFetchResult 'UIBackgroundFetchResultNoData'. should be one of: (
    backgroundFetchResultFailed,
    backgroundFetchResultNewData,
    backgroundFetchResultNoData
)`

**Comment by thehellmaker** [comment]
I have the same issue. Any updates on this?

**Comment by petekp** [comment]
Same issue.

**Comment by ThomasLarge** [comment]
I believe this needs to be a string for it to work so I have been using the following 

`notification.finish('backgroundFetchResultNewData)`

**Comment by kishanbharda** [comment]
I made following changes here ` push-notification-ios/js/index.js` and worked perfectly.
 
```js
static FetchResult: FetchResult = {
    NewData: 'UIBackgroundFetchResultNewData',
    NoData: 'UIBackgroundFetchResultNoData',
    ResultFailed: 'UIBackgroundFetchResultFailed',
  };
```

to 

```js
static FetchResult: FetchResult = {
    NewData: 'backgroundFetchResultNewData',
    NoData: 'backgroundFetchResultNoData',
    ResultFailed: 'backgroundFetchResultFailed',
  };
```

**Comment by fspider** [comment]
i am also having the same issue. +1
Is this final solution?

**Comment by gbmahili** [comment]
@fspider I believe so, it has worked for me too.

**Comment by harsh-p-eq** [comment]
It working perfect

**Comment by Dallas62** [comment]
Did someone made a PR on the iOS repository ?
It would be helpful
