### ISSUE TITLE
[IOS] onNotification not working (triggered)  when app on foreground

### ISSUE THREAD

**Issue by sandropoluan** [zo0r/react-native-push-notification#922]
Everything is doing fine on Android and IOS.  Except when on IOS and receiving and then clicking the notification when app on foreground, the onNotification callback is not working.
But when I received and clicking the notification while the app is killed or not running, the app is starting up and then the onNotification callback work perfectly.

I use `PushNotification.localNotificationSchedule`.

Any idea what is going on?

**Comment by jacquesdev** [comment]
@sandropoluan - I'm experiencing the same problem, have you been able to resolve this by any chance?

**Comment by arfa123** [comment]
I have also facing same problem. what is solution?

**Comment by izzisolomon** [comment]
Same problem here

**Comment by izzisolomon** [comment]
After spending 3 days on this, in my case turns out the APN notification generated by the backend was missing the property "content-available": 1 . once I added that to the "aps" object, onNotification started to fire! here is an example notification structure (from the apple docs): 

[-.txt](https://github.com/zo0r/react-native-push-notification/files/2862436/-.txt)

**Comment by Cody1009** [comment]
same problem here.
 @izzisolomon 
I want to try your solution but where did you write that code? I use local notification from pure react-native module.

**Comment by izzisolomon** [comment]
@Cody1009 if you trigger the notifications locally you don't really need onNotification to fire, do you? I mean you can just call whatever you want at the same time you trigger the notification

**Comment by HyeonjuPark** [comment]
@izzisolomon  What if I schedule local notification and want to check the user came from the notification or not?
