### ISSUE TITLE
onNotif not called when opening app manually (instead of through remote notification)

### ISSUE THREAD

**Issue by Blutude** [zo0r/react-native-push-notification#928]
I receive remote notifications successfully when the app is running on foreground, on the background and even when the app is not running.

When the app is running on foreground and a remote notification arrives, onNotif gets called immediately.
When the app is running on background and a remote notification arrives, I click on the notification, the app comes to foreground and onNotif gets called.
When the app is not running at all and a remote notification arrives, I click on the notification, the app comes to foreground and onNotif gets called.

The issue is when the app is running on backgroung or not running at all, and I receive a remote notification, but instead of clicking on it I launch the app myself, then onNotif does not get called. didReceiveRemoteNotification does not get called either.

So I am wondering, is it possible to make onNotif get called when app gets opened but not through clicking on the remote notification?

**Comment by Walaa106** [comment]
same :(
