### ISSUE TITLE
"Invalid int" error when running cancelAllLocalNotifications() method

### ISSUE THREAD

**Issue by sandropoluan** [zo0r/react-native-push-notification#929]
I have no problem when creating scheduled or local notification. 
But when I run `PushNotification.cancelAllLocalNotifications()` method, I got this error.

![photo_2018-10-31_16-14-28](https://user-images.githubusercontent.com/11922251/47778054-94d1ae00-dd28-11e8-843c-64809bc117a0.jpg)

**Comment by KeithM23** [comment]
the hyphen in your 123-4551 is what's throwing the error

Android only takes int e.g. 1, 2, 3, 4, 5, etc....

if you changed it to 1234551 it should work
