### ISSUE TITLE
Android mixed notification documentation

### ISSUE THREAD

**Issue by peacechen** [zo0r/react-native-push-notification#935]
I believe that the example snippet for mixed notifications needs updating.
https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md#android-mixed-remote-push-notifications

The server should sent both a `data` key as well as a `notification` key.
```
{
  "to": "<token>",
  "time_to_live": 86400,
  "collapse_key": "new_message",
  "delay_while_idle": false,
  "data": {
    "title": "title",
    "message": "this is a mixed test 14:03:29.676",
    "your-key": "your-value"
  }
  "notification": {
    "title": "title",
    "message": "this is a mixed test 14:03:29.676",
  }
}
```

Took a lot of experimentation to figure that out.  Has anyone else done this as well?

**Comment by bthuan** [comment]
@peacechen Thank you for posting this. I was struggling as well until i found out your post.

**Comment by peacechen** [comment]
2 years later and the docs still haven't been fixed 🙄

**Comment by Dallas62** [comment]
Hi @peacechen 
Feel free to make a PR ;)
Regards

**Comment by Dallas62** [comment]
Also this kind of notification is not supported anymore.
