### ISSUE TITLE
When to use configure()?

### ISSUE THREAD

**Issue by GustawOhler** [zo0r/react-native-push-notification#938]
Ok, my issue isn't really a bug, it's more of a question, but it isn't clear in documentation. When to use configure() method? I mean should I use it on the first launch of the app, on every launch or on every screen (I have react navigation for navigating through app) where I use notifications?

**Comment by joaovpmamede** [comment]
Use it when it makes sense for you.
If you have some sort of login/auth I'd put it after the user logins.

**Comment by GustawOhler** [comment]
> Use it when it makes sense for you.
> If you have some sort of login/auth I'd put it after the user logins.

I asked more about how long does the configure() works. Does it have to be called again after minimalization of the app, restarting it or after going to other screen? But from your reply I suppose after restarting it.
