### ISSUE TITLE
Local notification data?

### ISSUE THREAD

**Issue by bcalik** [zo0r/react-native-push-notification#94]
I would like to send localNotification and then handle the data when the notifications is clicked.
But how can I pass the data?

When I send the notification from server, there is no problem because I can access the data attribute when it received. But using localNotification, I can not pass data.

**Comment by mlumbroso** [comment]
I'm trying to do the exact same thing, I think I will use the tag property for Android, and the userInfo for iOS, but it would definitely be nice to be able to send a data object !

**Comment by varungupta85** [comment]
I am not sure if I misunderstood the question. But I am using this package to schedule local notifications and pass in data in the scheduled local notifications which I received as is in the local notification handler. I am scheduling the notification like below:

    PushNotificationAndroid.localNotificationSchedule({
        id: notificationId,
        message: alertBody,
        date: new Date(time),
        ...info
      });

where `info` object contains that I want to access in the local notification handler. In the notification handler, I am receiving all the items in the `info` object as is.

**Comment by npomfret** [comment]
@bcalik do you still have this issue? if so, have you tried the latest release? if not, can we close it?

**Comment by bcalik** [comment]
@npomfret I don't remember actually, it was 6 months ago, I probably solved it somehow. Closing.

**Comment by ryanhomer** [comment]
@varungupta85 Sending in an `info` object doesn't work for me (on Android). Is there no way to do this on Android?

**Comment by sungwoncho** [comment]
@varungupta85 Adding arbitrary key-value pairs to local notification configuration object did not work for me. They do not show up in the local notification handler. I find that only the keys documented in https://github.com/zo0r/react-native-push-notification#local-notifications show up.

**versions**

react-native-push-notification: 2.2.1
React Native: 0.41.2
Android: 6

Anything I can do to help make this work?

**Comment by mldoscar** [comment]
This worked for me in both platforms:

```javascript
PushNotification.localNotificationSchedule({
	userInfo: { foo: 'bar' },
	title: "my_title",
	message: "my_message",
	date: new Date(Date.now() + 10 * 1000) // within 10 secs
});
```
```javascript
PushNotification.configure({
	// (required) Called when a remote or local notification is opened or received
	onNotification: notification => {
		// IOS:
		console.log(notification.data.foo); // Will print: 'bar'
		// ANDROID:
		console.log(notification.userInfo.foo); // Will print: 'bar'
	}
});
```

**Comment by katunins** [comment]
<img width="486" alt="image" src="https://github.com/zo0r/react-native-push-notification/assets/61758341/0dae4458-4fa6-484f-80c7-4680f0f68219">


<img width="431" alt="image" src="https://github.com/zo0r/react-native-push-notification/assets/61758341/421ae9fa-6a20-47f3-a81f-e09c485e25a7">
