### ISSUE TITLE
Conditional scheduled notifications

### ISSUE THREAD

**Issue by ibarrae** [zo0r/react-native-push-notification#940]
I have been checking through this library and I have this case that I would like a scheduledNotification to show only with a condition, but I can seem to find any way to achieve this. 

Is there any way to do this even if it is hacky?

**Comment by chyoon2** [comment]
@ibarrae hi , i want to do the same thing, did you find a solve for this?

**Comment by sarthakgupta072** [comment]
Any update here? How to do this expo?
