### ISSUE TITLE
Add clearLocalNotification documentation to README.

### ISSUE THREAD

**Issue by juanfer0002** [zo0r/react-native-push-notification#941]
Hello.

There's a method named `clearLocalNotification` that doesn't appear in the readme.

**Comment by noway** [comment]
second this. how to use it?

**Comment by juanfer0002** [comment]
It's been a year I've not been using this lib, but if you go to this line, you'll see the method https://github.com/zo0r/react-native-push-notification/blob/b4ea8fbf4b9443be186c5ee9fa8f77dc07905961/index.js#L295

I couldn't try it, but I guess you can use like canceling a notification: https://github.com/zo0r/react-native-push-notification#cancelling-notifications

`PushNotification.clearLocalNotification({id: '123'});`

**Comment by noway** [comment]
should be used like this:
```javascript
PushNotification.clearLocalNotification(parseInt(notificationToRemove.androidNotificationId, 10));
```
