### ISSUE TITLE
how to manage multiple users in the same device

### ISSUE THREAD

**Issue by jose920405** [zo0r/react-native-push-notification#943]
How is the correct management to user with 2 accounts?: 

- Start a session with the first account
- `Allow` the prompt permission and inside `onRegister` register the device to `backend` and later in `amazon`.
- delete first account from settings in my app.
- Start a session with the second account
- Notification prompt never comes back and `onRegister` it's never dispatched.

**How can I make `onRegister` works again for the second account?**

**Comment by pedrosimao** [comment]
I am also trying to delete user / token when user logs out. 
I didn't find a way to do that yet.

**Comment by hohien** [comment]
Did you resolve this problem. I'm having the same like you

**Comment by gSrujana26** [comment]
any solution for this?
