### ISSUE TITLE
how do i know when to click to notif and when to receive notif from GCM ?

### ISSUE THREAD

**Issue by hoangpm2812** [zo0r/react-native-push-notification#944]
Hi, at function onNotification i dont know how to separate between local notif is opened or received.
For example, when i receive a message from GCM, i will call function locaNotification to show notif from server. But when i press that notif, it will call function localNotification again a the new notification will be shown again and again... Please help me.

Thanks.

**Comment by noce30** [comment]
because onNotification was Called when a remote or local notification is opened or received

**Comment by huyvm** [comment]
you can check userInteraction attr in message. true for click action and false for receive event.
