### ISSUE TITLE
Action click brings app from background to foreground

### ISSUE THREAD

**Issue by ssajnani** [zo0r/react-native-push-notification#945]
I am using HeadlessJS to create localNotifications in background. When I click any of the actions for my notifications they automatically open up the application. Is there a setting to turn off this activity and to continue in the background.

**Comment by ihurrahi** [comment]
Seems to have happened in this commit: https://github.com/zo0r/react-native-push-notification/commit/6b732623c62f3b4fdbcc47aa786556ae23da17a7. Version 3.1.1 doesn't seem to have this problem.

**Comment by mathiasmoeller** [comment]
I am still facing this problem. Did anyone find a solution yet?

**Comment by mathiasmoeller** [comment]
@ihurrahi How did you manage to do it in 3.1.1?
