### ISSUE TITLE
RNPushNotification: java.lang.NullPointerException

### ISSUE THREAD

**Issue by l0ger** [zo0r/react-native-push-notification#949]
Local notification not do anything.

here is logcat output:

11-25 18:46:38.373   618   735 E RNPushNotification: failed to send push notification
11-25 18:46:38.373   618   735 E RNPushNotification: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference
11-25 18:46:38.373   618   735 E RNPushNotification:    at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.getMainActivityClass(RNPushNotificationHelper.java:56)
11-25 18:46:38.373   618   735 E RNPushNotification:    at com.dieam.reactnativepushnotification.modules.RNPushNotificationHelper.sendToNotificationCentre(RNPushNotificationHelper.java:137)
11-25 18:46:38.373   618   735 E RNPushNotification:    at com.dieam.reactnativepushnotification.modules.RNPushNotification.presentLocalNotification(RNPushNotification.java:156)

gradle info:

        buildToolsVersion = "27.0.3"
        minSdkVersion = 19
        compileSdkVersion = 27
        targetSdkVersion = 27
        supportLibVersion = "27.1.1"

**Comment by rensphilipsen** [comment]
See [https://github.com/zo0r/react-native-push-notification/issues/946#issuecomment-440614001](https://github.com/zo0r/react-native-push-notification/issues/946#issuecomment-440614001). I was having the same issue.

**Comment by gbferreira** [comment]
Same problem.

**Comment by Dallas62** [comment]
Hi @gbferreira 
Please open a new issue, this one is too old.
