### ISSUE TITLE
No reference to this

### ISSUE THREAD

**Issue by Naoto-Ida** [zo0r/react-native-push-notification#95]
None of the traditional methods of applying context to `this` such as `bind()` do not work.

I am trying to get reference to the Navigator which is in the same class.

So use case would be, I get a notification, the notification payload contains a `path`,
and depending on that, a different view is shown.

**Comment by jeveloper** [comment]
Can you paste your code or part of it ?

FYI i normally use (data)=> ... which wraps a call and passes this

**Comment by Naoto-Ida** [comment]
Thanks @jeveloper!

Here is the exact code:

```
PushNotification.configure({
  onNotification(notification) {
    if (notification.data.test !== undefined) {
      this.refs.nav.replace({
        component: Something,
        sceneConfig: Navigator.SceneConfigs.FloatFromRight
      })
    }
  }
}, this)
```

I cannot get access to `this.refs`.

**Comment by jeveloper** [comment]
this will work

above PushNotifiation.configure ...
let thisref = this

within your function use thisref.refs.nav....

i would recommend however to refactor your code and use promises or at least a callback

**Comment by jeveloper** [comment]
I also just realized you're using this library incorrectly 
configure will need a json and one of the fields is a function 

onNotification: _notificationHandler,


_notificationHandler is a function

**Comment by npomfret** [comment]
@Naoto-Ida do you still have this issue? if so, have you tried the latest release? if not, can we close it?

**Comment by jeveloper** [comment]
all good

**Comment by Naoto-Ida** [comment]
Oh, sorry, I stopped using it and went to Firebase, so not sure how it is on latest release.
Will be closing now.

**Comment by ravirupareliya** [comment]
Did anyone find solution for this?
