### ISSUE TITLE
onNotification is not called when send message from FCM at backgroud

### ISSUE THREAD

**Issue by hoangpm2** [zo0r/react-native-push-notification#951]
Hi,
I put console.log(notification) in function onNotification(). When i send a message from fcm in foreground, it works fine. But in background, i dont see any log of notification. I tried with GCM but GCM work well, and FCM is error like that. Did i miss something in file AndroidManifest.mxl ? Please help me.
Thank you so much.

**Comment by gontovnik** [comment]
Facing the same issue. To me it feels like the app gets re-opened when I receive FCM notification while being in background.

**Comment by cristianocca** [comment]
Did you figure this out? Can you confirm that this library allows you to receive remote push notifications while the app is closed, and also show an alert to the user?
Thanks.

**Comment by rashidul-hasan** [comment]
> Facing the same issue. To me it feels like the app gets re-opened when I receive FCM notification while being in background.

Facing the same problem. Anyone found a solution for this yet?

**Comment by Ethan0007** [comment]
@hoangpm2  sir, just want to ask on how did you configure it using react-native-firebase?
