### ISSUE TITLE
Android local notification reinizialize app

### ISSUE THREAD

**Issue by stoppiNeobiz** [zo0r/react-native-push-notification#957]
Hi to all, I would have a question about android local notifications. In my app send a notification when a timer arrive at 0. If the notification box appear while app is open and I click it, the app return to home page. If I click the box while app is in background, reopen the same page correctly. 
Why this happens? 
Thanks.
This is my simple code:
```
sendNotification = () => {
        PushNotification.localNotificationSchedule({
            date: new Date(Date.now() + (this.state.timer * 1000)),
            title: this.state.notificationTitle,
            message: this.state.notificationMessage,
        });
}
```

**Comment by Helga108** [comment]
This also happens with remote notifications.

**Comment by tbfreitas** [comment]
Same issue here. Anyone ?

**Comment by tinpt123** [comment]
same issue
