### ISSUE TITLE
what i can do ?

### ISSUE THREAD

**Issue by islamabujamea** [zo0r/react-native-push-notification#962]
when I install the plugin and make clean for a project become some errors :( 
- Failed to resolve: support-core-utils
- Failed to resolve: support-compat

![image](https://user-images.githubusercontent.com/45818682/49866817-825f8f80-fe11-11e8-8c84-a928dd16e5d4.png)

**Comment by hussainahmad** [comment]
did you added `google() ` in your project level gradle..
```buildscript {
      repositories {
          google() // here
          jcenter()
      }
     ............
  }
  allprojects {
      repositories {
          google() // and here
          jcenter()
  }
```
