### ISSUE TITLE
Android : No custom sound on android > 7

### ISSUE THREAD

**Issue by jean-ben-guigui** [zo0r/react-native-push-notification#964]
Hello

I have been using this plugin for a while now and I thank you for this great work.
I was wondering if there is a way of using custom sound with android oreo when using remote gcm notifications. In my app it works with android versions < 8.

Maybe I just missunderstood the good way to play a custom sound but if it is a real issue, is there a workaround?

Thanks

**Comment by Gys** [comment]
Not solved, but already reported: Android: No custom sound #921
