### ISSUE TITLE
How leave app on background when onNotification is fired

### ISSUE THREAD

**Issue by likern** [zo0r/react-native-push-notification#965]
When I press action on notification `onNotification` callback is called.
If my application was in `background` it moves to `foreground`.
**How can I still leave application in background** when `onNotification` is called?

**Comment by likern** [comment]
I found this description in [troubleshooting guide](https://github.com/zo0r/react-native-push-notification/blob/master/trouble-shooting.md)
> If a user taps an alert, your app will be started or brought to the foreground and onNotification will be called.

But I need something opposite  - call `onNotification` **but not bring app to foreground** (I'm writing a ToDo list and want to **complete** task by tapping notification action `Complete`, without showing app in foreground, if app is in background).

**Comment by mathiasmoeller** [comment]
Did you find a solution to your problem @likern? Facing the same issue!
