### ISSUE TITLE
April 2019 full removal of gcm dependency

### ISSUE THREAD

**Issue by maieonbrix** [zo0r/react-native-push-notification#979]
Hello,

First of all, thank you for your great work, I open this issue to ask if we need to prepare for the full-on deprecation of GCM to com (https://developers.google.com/cloud-messaging/android/android-migrate-fcm) 

> As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019. Migrate GCM apps to Firebase Cloud Messaging (FCM), which inherits the reliable and scalable GCM infrastructure, plus many new features. See the migration guide to learn more.

I did found #875 but since it was closed by the author no one really answered

My questions are : 
- do we need to prepare a PR now for the next april ?
- update the readme + everything according to google's migration guide : https://developers.google.com/cloud-messaging/android/android-migrate-fcm

Really, I do know that you might already be aware of this, and sorry if I may have missed some prior communication about this, I do want to work on this though \o/

Thanks again for your work

**Comment by dittmarconsulting** [comment]
Hi there,

I'm working on the FCM integration as well and need guidance how to set it up using this library.

Many thanks in advance.

**Comment by hatlestad** [comment]
I would be interested in this as well.

**Comment by Faolain** [comment]
@Gp2mv3 any thoughts on this?

**Comment by kingbin** [comment]
Less than a month and this lib has "com.google.android.gms:play-services-gcm:xxx" compile and testCompile/testApi need to be updated to implementation and testImplementation respectively.

Is there a fork that is in alpha we can test?
