### ISSUE TITLE
 Could not find support-core-utils.jar (com.android.support:support-core-utils:27.1.1)

### ISSUE THREAD

**Issue by amirmn722** [zo0r/react-native-push-notification#982]
when i link push notification and run my project this error will show:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':react-native-push-notification:debugCompileClasspath'.
> Could not find support-core-utils.jar (com.android.support:support-core-utils:27.1.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-core-utils/27.1.1/support-core-utils-27.1.1.jar
> Could not find support-compat.jar (com.android.support:support-compat:27.1.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-compat/27.1.1/support-compat-27.1.1.jar

what can i do?

**Comment by peymanifar** [comment]
you have to upgrade your gradle 
close everything first ,then 

in mac use : 
`./gradlew build --refresh-dependencies`

in windows use: 
`gradlew build --refresh-dependencies`



*** if you're a developer from middle east always use a good vpn  before the upgrade !!!  ***
