### ISSUE TITLE
Repeating notification is not working on IOS

### ISSUE THREAD

**Issue by rodrigowpl** [zo0r/react-native-push-notification#983]
Repeating notification don't working on IOS

Here is my code
```
PushNotification.localNotificationSchedule({
  message: 'test',
  date: ...,
  repeatType: 'time',
  repeatTime 120000 // 2 minutes
})
```

On Android it works normally. But on IOS only the first notification is received.

I already see another issues about that. But I don't understand If was resolved or not.

Any idea?

**Comment by rynatk** [comment]
@rodrigowpl This issue is also affecting me. Same description, I see the first notification, but none of the repetitions.

**Comment by Johny8811** [comment]
Same here, plus setup with **repeatType** (doesn't matter on value of repeatType)

`
PushNotification.localNotification({
  message: 'test',
  repeatType: 'minute',
})
`
on android cause infinite loop of notifications. **localNotificationSchedule** works correctly on android.

I try it on example project.

**Comment by apppro123** [comment]
The problem can be caused, because from react native itself the PushNotificationIOS doesn't support repeatType "time".
[https://facebook.github.io/react-native/docs/pushnotificationios](url)
see under scheduleLocalNotification => repeatInterval

**Comment by daheeahn** [comment]
any solution?

**Comment by bostnis** [comment]
Is this repository active? most of sensitive issues are stale or closed by bot...

**Comment by Dallas62** [comment]
Hi @bostnis 
All staled / closed issues by bot are inactive for at least a year. If it's important, this should be active and with reproducible project.
Most of issue are  duplicated because no one search in history. And I don't have time to look 500 issues where there is no informations and outdated version.

**Comment by bostnis** [comment]
Hi @Dallas62 
Thanks for the response. Currently I am struggling with ios issue..
repeatType: 'day' not working on ios apps and I checked most of issues posted here but couldn't find good solution yet.
If I made you confused, sorry for that. 

Regards
