### ISSUE TITLE
Display images in Push notification

### ISSUE THREAD

**Issue by saifkamaal** [zo0r/react-native-push-notification#984]
I need to show images as part of the potification in Android and iOS. for simplicity if the image is avaible via a uri then which is the property i should be looking in the api and will it automatically render the image in the notification area, when the notification arraives ?

**Comment by fouad1994** [comment]
did you solve this issue I need the same thing?

**Comment by FirdousNath** [comment]
waiting for the same :(

**Comment by melchua** [comment]
Also need the same. Did you come to any resolution @saifkamaal? Thanks :)

**Comment by vincentzierigen** [comment]
Any solutions? I was able to do it on Android but not iOS.

**Comment by jaidHashem** [comment]
> Any solutions? I was able to do it on Android but not iOS.

Can you kindly share how you did it on Android

**Comment by dilipsuthar97** [comment]
Can anyone share how to display image in notification via image uri.
