### ISSUE TITLE
iOS: Can't remove local notifications from Notification Center 

### ISSUE THREAD

**Issue by simonepauro** [zo0r/react-native-push-notification#985]
### After showing a local notification with

```
PushNotification.localNotification({
    ...
    userInfo: { id: '123' }
    ...
});
```

### I tried the following methods to remove it from the Notification Center

- PushNotification.cancelLocalNotifications({id: '123'});
- PushNotification.cancelAllLocalNotifications();

Both of them are not working for me so I found a workaround

## Workaround

This method is for Android only:
`PushNotification.clearAllNotifications();
`

I edited it from this
```
function() {
    return this.callNative('clearAllNotifications', arguments);
}
```

to this
```
function() {
    if (Platform.OS === 'ios') return this.callNative('removeAllDeliveredNotifications', arguments);
    return this.callNative('clearAllNotifications', arguments);
}
```

So now it works for iOS and I can use it to remove all the notifications

**Comment by joemeyer-pear** [comment]
A workaround in any shared code looks very similar:

```
import { Platform, PushNotificationIOS } from 'react-native';
...
if (Platform.OS === 'ios') {
  PushNotificationIOS.removeAllDeliveredNotifications();
}
```

Thanks for putting me on the right path @simonepauro !
