### ISSUE TITLE
NSInvalidArgumentException when running Example App on iOS.

### ISSUE THREAD

**Issue by owenhope** [zo0r/react-native-push-notification#988]
Hi,

I am trying to get the example version running, however I have run into a number of issues... 

First I had to make sure that category, userInfo and number under "localNotification" were set to a string, object and integer (not null, or string for "number" either as the comment say.

Next I am getting constant crashes on userInfo in iOS.
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil'`

My localNotif() now looks like this, but my app crashes everytime I try and fire a Local Notification:

```
localNotif() {
    this.lastId++;
    PushNotification.localNotification({
      id: ''+this.lastId, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
      ticker: "My Notification Ticker", // (optional)
      autoCancel: true, // (optional) default: true
      largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
      smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
      bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
      subText: "This is a subText", // (optional) default: none
      color: "red", // (optional) default: system default
      vibrate: true, // (optional) default: true
      vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
      tag: 'some_tag', // (optional) add tag to message
      group: "group", // (optional) add group to message
      ongoing: false, // (optional) set whether this is an "ongoing" notification

      alertAction: 'view', // (optional) default: view
      category: "Hunch", // (optional) default: null
      userInfo: { id: '123' }, // (optional) default: null (object containing additional notification data)**

      title: "Local Notification", // (optional)
      message: "My Notification Message", // (required)
      playSound: false, // (optional) default: true
      soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
      number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
      actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
    });
  }
```

Any help would be much appreciated.

**Comment by owenhope** [comment]
Update, when I breakpoint this is where its failing, it seems to be something with the app being active.

`// If the app is active we do not show the alert, but we deliver the notification to the experience.

  EXPendingNotification *pendingNotification = [[EXPendingNotification alloc] initWithNotification:notification];
  if (![[EXKernel sharedInstance] sendNotification:pendingNotification] && [EXEnvironment sharedEnvironment].isDetached) {
    _pendingNotifications[pendingNotification.experienceId] = pendingNotification;
  }

  completionHandler(UNNotificationPresentationOptionNone);`

**Comment by incrediblink** [comment]
@owenhope Hi, I run into the same error. Did you resolve this problem?
