### ISSUE TITLE
Android notification without small icon

### ISSUE THREAD

**Issue by cubbuk** [zo0r/react-native-push-notification#99]
Is it possible to not use smallIcon when sending notification. Right now it shows a small empty squara under the notification icon, on notification bar? Any idea?

**Comment by vitorhorta** [comment]
+1, same issue

**Comment by kyawmoehaynes** [comment]
+1, same issue

**Comment by kyawmoehaynes** [comment]
@cubbuk @vitorhorta I've found the solution for this. Basically, you just need to put in transparent (no color) ic_notification.png in mipmap folders. It's important that it's completely transparent with no color. Otherwise, it won't work.
Solution: https://blog.clevertap.com/fixing-notification-icon-for-android-lollipop-and-above/
ic_notification.png size guide: http://iconhandbook.co.uk/reference/chart/android/

**Comment by cubbuk** [comment]
When I use transparent icon I start seeing gray icon, is there any way to totally remove that small icon? But thanks for the guides these were useful

**Comment by idjugostran** [comment]
You can set empty string to largeIcon parameter, and notification will use smallIcon as a large, but it will be no color. To change tint color may be used **color** option.

**Comment by mchlltt** [comment]
This didn't end up being a good fit for me, but I thought I'd  save anyone else with this issue the time to create transparent pngs in various sizes. Image is below the size label. 
22x22
![ic_notification](https://cloud.githubusercontent.com/assets/15218445/24481939/82950ca8-14b3-11e7-9100-16832ad53ba9.png)
33x33
![ic_notification](https://cloud.githubusercontent.com/assets/15218445/24481936/7ed9f3bc-14b3-11e7-9469-283b57d12de5.png)
44x44
![ic_notification](https://cloud.githubusercontent.com/assets/15218445/24481941/865e376a-14b3-11e7-8590-1c9892568956.png)
66x66
![ic_notification](https://cloud.githubusercontent.com/assets/15218445/24481942/8a6a6f40-14b3-11e7-82b1-e43dbe6b20e9.png)

**Comment by Rah1x** [comment]
just use this tool and generate the icons and in the correct folder.. 
https://romannurik.github.io/AndroidAssetStudio/index.html

**Comment by TaraSinghDanu** [comment]
How to get large icon when app is in background?
