### ISSUE TITLE
Can I display local notifications when the app is in background and the phone is locked?

### ISSUE THREAD

**Issue by lfa9603** [zo0r/react-native-push-notification#990]
I am trying to schedule a notification to be displayed 10 minutes after the app has been opened but I noticed that on Android (haven't tested iOS) the local notification will not display if the phone is locked. Any suggestions? Should I even be able to do it?

**Comment by kumaranubhaw** [comment]
I have problem with react native local push notification in Android. When app is background push notification is not received, when app comes in foreground then notification received. I am using react-native-firebase-messaging for remote notification and react-native-push-notification for local notification.

**Comment by cymonbr** [comment]
I used to background tasks a background timer for local notification and it worked well for me, you can try it.
