### ISSUE TITLE
Badge count was not updated automatically in iOS after notification was read

### ISSUE THREAD

**Issue by mpeng** [zo0r/react-native-push-notification#994]
Also when local or schedule PN arrives, the badge count is not increased.

If I send PN through FCM console and specify a badge count number, the number is used correctly.

Both increase and decrease works perfectly in Android. 

So the question is do I need add ios specific logic to handle the badge count update ?

I don't mind handling logic in the code, but I thought I might miss something.

**Comment by abarisic86** [comment]
I think you need to update that yourself. Gmail app has problems with that.

**Comment by mpeng** [comment]
@abarisic86, thank you, Glad to know I did not miss any configuration on my end.

**Comment by isakki** [comment]
Fresh chat notification badge count is not updating in iOS

Unread message count is updating only when I refresh the app

Freshchat.addEventListener(
Freshchat.EVENT_UNREAD_MESSAGE_COUNT_CHANGED,
() => {
console.log("onUnreadMessageCountChanged triggered");
Freshchat.getUnreadCountAsync((data) => {
console.log("Message count",data.count)
PushNotificationIOS.setApplicationIconBadgeNumber(data.count);
});
}
);
