### ISSUE TITLE
[Android] insecure Random Number Generator found in pen testing

### ISSUE THREAD

**Issue by benleah** [zo0r/react-native-push-notification#997]
Pen testing the Android build with MobSF (https://github.com/MobSF/Mobile-Security-Framework-MobSF) reveals a 'high severity' issue with use of an "insecure Random Number Generator" in the following modules...

RNPushNotification.java
RNPushNotificationListenerService.java
RNPushNotificationListenerServiceGcm.java

MobSF doesn't provide any additional detail.

***

React Native v0.57.5
react-native-push-notification v3.1.2

**Comment by majirosstefan** [comment]
There is another linked issue, too:   https://github.com/zo0r/react-native-push-notification/issues/1333 
Most people laugh, but it is a little tricky to convince secOps guys - so it would be great to replace Random Generator from java.util, for the one that is more secure, I guess (so the users will not be forced to make forks of this repo).

**Comment by Dallas62** [comment]
Hi,
I will look into it, but yes SecOos are looking at report and not context.
The Random value is used when the developer doesn’t provide a notification ID.
Not sure if this is a “sensitive” field...
But will look into it... 😉

**Comment by majirosstefan** [comment]
Thanks for the fast reply.
According to the Android docs, SecureRandom is supported by API (1), so it should be enough just to replace Random with SecureRandom. 

Check the following, please: https://github.com/zo0r/react-native-push-notification/pull/1497/files
