### ISSUE TITLE
Local Notification Sound not working in MI Xiaomi mobiles

### ISSUE THREAD

**Issue by codemeall** [zo0r/react-native-push-notification#999]
I followed all the steps, and I see the notification sound permission in MI is disabled, I don't know that may be the issue or something else, any suggestion or help would pe appreciated thanks.

**Comment by usmansbk** [comment]
Hey! @codemeall, Having the same problem. Did you get to fix it?

**Comment by Irfanhaidermomin** [comment]
Hey ! I'm also having same problem. Did you fixed it?

**Comment by u15767** [comment]
Hi, this really doesn't work. It is not a matter of custom sound. I debugged the code, especially the RNPushNotificationHelper.java

All notifications with default settings will be notified in a channel with the id
`rn-push-notification-channel-id-4-300`
This is the same id as the one generated for the default channel (see method checkOrCreateDefaultChannel), which is generated per default. Unfortunately, this channel is created without any sound. This means, any usage of notfications with all parameters set to defaults will not play sound although the default for sound is to play sound.

I don't know which solution you would prefer. I could think of providing the default sound also for the default notification channel. Another solution could be to ensure that notifications with all defaults used use a different channel.

As I don't want to decide this, I did not make a pull request out of it.

A solution by now is to set the vibration to something different than 300, e.g. 301.

**Comment by Dallas62** [comment]
Hi!
You can check in issues and in Firebase documentation. 
There is an entry in AndroidManifest to make this works.
```xml

<meta-data
    android:name="com.google.firebase.messaging.default_notification_channel_id"
    android:value="@string/default_notification_channel_id" />
```

**Comment by Dallas62** [comment]
And unfortunately, there is no better way to make the current API works with channels in another way without refactoring.
All the API is focus on channel, while Android focus on channels in recent versions.
With FCM in server-side you can also add the preferred channel-id.

**Comment by khamaman** [comment]
Having the same issue with MIUI 12
